### ISSUE TITLE
Wrogn icons display and bitmap update stop @ 50/66 SD icons files

### ISSUE THREAD

**Issue by kattivik76** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1]
I have make a new .bin file from source, it's include TFT_SD or OnboadSD printing functions, details:

Hardware version: BIGTREETECH-TFT35-V1.2
Firmware version: BIQU_TFT35_V1.2.20.bin (previously -> BIQU_TFT35_V1.2.13.x.bin but same issues)

I have used the complete and original bmp files folder from github [https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/new](url)

the issues is:

1. no correct icons display in "print" menu, after start print from TFT_SD or OnboardSD, the "printing" menu don't display some icons, display the white square

![print_menu](https://user-images.githubusercontent.com/52204987/61357702-0af75000-a879-11e9-9d1b-f1dd60086f26.jpg)

2. in this "printing" menu is't present the "back" icon button to return on main page, after printing a file from SD, the TFT display can be reset "poweroff - poweron" to return on the main page.

![printing_menu](https://user-images.githubusercontent.com/52204987/61357626-e9966400-a878-11e9-9ce4-6544904134da.jpg)

3. no correct icons display in "Babystep" 

![babystep1_menu](https://user-images.githubusercontent.com/52204987/61357746-26faf180-a879-11e9-9a73-f70528ab093b.jpg)

and

![babystep2_menu](https://user-images.githubusercontent.com/52204987/61357759-2e21ff80-a879-11e9-9074-b35c9498c4e8.jpg)

`MENUITEMS babyStepItems = {
//   title
  LABEL_BABYSTEP,
//icon                        label
 {{ICON_DEC,                  LABEL_DEC},
  {ICON_BACKGROUND,           LABEL_BACKGROUND},
  {ICON_BACKGROUND,           LABEL_BACKGROUND},
  {ICON_INC,                  LABEL_INC},
  {ICON_NOZZLE,               LABEL_NOZZLE},
  {ICON_01_MM,                LABEL_01_MM},
  {ICON_NORMAL_SPEED,         LABEL_VALUE_ZERO},
  {ICON_BACK,                 LABEL_BACK},}
};`

4. when firmware updating from TFT_SD, the updating bmp files process whas display some icons pics and count of total icons, stop any bmp icons update whet OS reach 50 icons of 66 icon present. the complete firmware update continue without any error.

5. I have try to update only the last bmp files like:

-  OnTFTSD.bmp
- OnBoardSD.bmp
- U_Disk.bmp

**Comment by bigtreetech** [comment]
hi，if you are using ‘BIQU_TFT35_V1.2.20.bin’， please copy this 3 icons to SD Crad path “TFT35/bmp”
![image](https://user-images.githubusercontent.com/38851044/61455754-0c1e9f00-a997-11e9-9df1-d0f401a23e78.png)

**Comment by robbycandra** [comment]
It is because ICON NAME enum and BMP name is not sync.

**Comment by kattivik76** [comment]
> hi，if you are using ‘BIQU_TFT35_V1.2.20.bin’， please copy this 3 icons to SD Crad path “TFT35/bmp”
> ![image](https://user-images.githubusercontent.com/38851044/61455754-0c1e9f00-a997-11e9-9df1-d0f401a23e78.png)

### Hi, i have try to move all file in TFT35/dmp and TFT35/font, now work fine!!!!

please update the howto documentation because the destination folder and bmp color deep isn't correct:

1- need to put all bmp files in SD_root/TFTxx/bmp folder
2- need to put all font files in SD_root/TFTxx/fontfolder
3- need to put new firmware update in SD_root folder
4- correct folder structure for TFT35 is:

```
SD_root/BIQU_TFT35_V1.2.20.bin "new firmware update"
SD_root/TFT35/bmp "all icons for 3.5" display"
SD_root/TFT35/font "all fonts for 3.5 display"
```

note, the SD_root/TFTxx folder is:
1- TFT35 >> 3,5" display
2- TFT28 >> 2.8" display
3- TFT24 >> 2.4" display

**Comment by robbycandra** [comment]
Its already written in the last paragraph of readme.md

![image](https://user-images.githubusercontent.com/4693418/61624117-2c55a300-aca2-11e9-9dbe-8934972b9e55.png)

**Comment by guruathwal** [comment]
@kattivik76 please close the issue if your problem is solved.

**Comment by guruathwal** [comment]
@bigtreetech please close this issue
