### ISSUE TITLE
Cleanner history with rebase

### ISSUE THREAD

**Issue by robbycandra** [bigtreetech/BIGTREETECH-TouchScreenFirmware#10]
Dear @bigtreetech , it is cleaner if PR not merged but rebased.

**Comment by thisiskeithb** [comment]
Yes, please!

**Comment by robbycandra** [comment]
Hello @thisiskeithb , nice to meet you here.

**Comment by thisiskeithb** [comment]
You too! My TFT24 finally cleared customs, so now I'm busy putting in PRs :)

**Comment by robbycandra** [comment]
I am still slow. Wait and see where the wind blow.

**Comment by robbycandra** [comment]
@thisiskeithb , for me, its like split version of MKS Robin TFT. 
We need a big map on how this UI will talk with Marlin.
Do you have any idea about it ?

**Comment by thisiskeithb** [comment]
The TFT side is just like the MKS TFTs since it's basically a standalone controller that sends gcodes back to Marlin.

For the 12864 emulation, it's just like the standard `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER`/uses the standard Marlin UI.

**Comment by robbycandra** [comment]
I make this Screen as Extensible UI. I love it because it has Encoder Button. Maybe i will rebuild the firmware.

**Comment by thisiskeithb** [comment]
I'd be curious to see it! Have a link? :)

**Comment by robbycandra** [comment]
It still in very early development. 
First thing I do is make a status screen like UltraLCD. 

BTW. we can also use code from here to build the "missing" MKS Robin TFT code

**Comment by robbycandra** [comment]
![image](https://user-images.githubusercontent.com/4693418/63139217-b118b000-c007-11e9-8230-e844955ecc8f.png)

**Comment by thisiskeithb** [comment]
> this is what happened to my screen.

It's fine if you ignore the GUI side. 🙂But really, this probably won't change.

**Comment by vMeph** [comment]
sorry to jump in @robbycandra and @thisiskeithb but it seems this is the only active issue lol
was wondering if this TFT 35 at some point will have some basic display like the reprap lcd
like first screen show x y z position temp of bed and hotend fan  and then yes go into menus
thats what seems to make sense in this LCD to have
at this point it seems that the  TFT firmware is missing alot stuff, i wanted to move my machine to have this LCD but  im waiting to see if the firmware becomes a litle more useful

**Comment by robbycandra** [comment]
@vMeph , Marlin firmware already have something called Extensible UI that will take care communication between User Interface and Marlin. But it still need more work And The work must be done in LCD firmware and Marlin Firmware.

**Comment by guruathwal** [comment]
@robbycandra Should this be closed now ?

**Comment by robbycandra** [comment]
Yes Close

**Comment by guruathwal** [comment]
Then please close it.
