### ISSUE TITLE
[Q] Bootloader TFT50

### ISSUE THREAD

**Issue by Rebel3D-CZ** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1000]
Hi, I have a TFT50 with a faulty CPU. I replaced the CPU with a new one. Is it possible to get a bootloader for TFT50 with the procedure how to upload it?
I have ST-Link. I will connect to the processor.

**Comment by radek8** [comment]
maybe someone who has the same display will help and copy the chip's memory :-)
viz
https://github.com/bigtreetech/BIGTREETECH-TFT35-V3.0/issues/20

**Comment by radek8** [comment]
instructions try this one
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/blob/master/TFT35_V2%20Bootloader%20fix/BTT-TFT35-V2.0-Bootloader-flashing-guide-CH340-debugger.pdf

**Comment by Rebel3D-CZ** [comment]
I believe the manufacturer's support is solid and the bootloader will provide its customers :)

**Comment by Rebel3D-CZ** [comment]
Is the support really unable to provide customers with a bootloader? Very sad :(

**Comment by av71966** [comment]
> Hi, I have a TFT50 with a faulty CPU. I replaced the CPU with a new one. Is it possible to get a bootloader for TFT50 with the procedure how to upload it?
> I have ST-Link. I will connect to the processor.

Hi, i have simmilar problem and have second working tft50 and want to repair broken one. If you help me with copying eeprom i can send it to You

**Comment by Rebel3D-CZ** [comment]
Hi, I have another TFT50 in about 2 days. I'll read the bootloader and save it here. Chinese ST-LINK V2 is enough to read. Then I will try to help or I will proceed here, but now I am 2 days on vacation :)

**Comment by Rebel3D-CZ** [comment]
Everything you need here :)

https://1drv.ms/u/s!AvBL3Ps7S-g3ktIRlwZE_Jj3X-WJCQ?e=6MwVQf

**Comment by radek8** [comment]
Great.
Don't you want to post it on the github page so that it is available to others who might need it?

**Comment by Rebel3D-CZ** [comment]
Unfortunately, I don't have much experience with github. I don't know where it can or cannot be given and what the rules are. If you can, put the data where it belongs.

CZ: Radku, vůbec nevím kam bych to měl či neměl dát, s gitem jsem nikdy moc nedělal, jsem rád že sem umím něco napsat a zeptat se :D Ale klidně to dej jak to myslíš, aspoň příště budu vědět. Dík Dan

**Comment by radek8** [comment]
OK

**Comment by av71966** [comment]
> Everything you need here :)
> 
> https://1drv.ms/u/s!AvBL3Ps7S-g3ktIRlwZE_Jj3X-WJCQ?e=6MwVQf
Thank U! U are my hero)

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Thank you
