### ISSUE TITLE
How to set this up on a mks gen l

### ISSUE THREAD

**Issue by mgrenier25** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1001]
I am trying to get this TFT35v3 to work with a mks gen l board

I connected both ribbon cables as well as the 5 pin serial

The screen in stuck on mode selection screen, turning/pushing/holding the encoder seems to be doing nothing, reset button works fine, brings me back to the same mode selection screen.

**Comment by radek8** [comment]
If you have the display mounted in a box or frame, try removing the display so that it is free.

**Comment by mgrenier25** [comment]
It is mounted from one side on a plexiglass, I don't think it is a heat issue.

**Comment by radek8** [comment]
It's not about the heat.
The pressure of the frame on the edge of the display can cause a short circuit in the touch layer

**Comment by mgrenier25** [comment]
Well I removed it from the plexiglass panel and it is behaving the same way, stuck on mode selection screen.
Tbh I am not even sure this is plugged in the right way, I could barely find any info on how to connect the tft35 to an mks board.

**Comment by radek8** [comment]
Touch mode must work even if the printer is not connected. It will only tell you that the printer is not connected

**Comment by radek8** [comment]
Attention MKS has connectors EXP1 and EXP2 turned against BTT !!

**Comment by radek8** [comment]
Connect the serial line to RS232 on the display and to AUX1 on the MKS GenL
You connect 5v, GND, D1, D2
You leave RST unconnected

**Comment by mgrenier25** [comment]
Do I flip both of them or only top one?

**Comment by radek8** [comment]
EXP1 and EXP2

**Comment by radek8** [comment]
if touch mode does not connect to the printer, swap pins between D1 and D2 of the Aux-1 connector

**Comment by radek8** [comment]
Of course Marlin must be properly configured :-)

**Comment by mgrenier25** [comment]
Works like a charm, tyvm

**Comment by radek8** [comment]
Close this ticket.
