### ISSUE TITLE
[Q] How can I set up my TFT 35 to use the mini UPS on PS_ON port not with config.ini

### ISSUE THREAD

**Issue by jedisintraining3** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1003]
How can I set up my TFT 35 to use the mini UPS on PS_ON port without using config.ini, i am not using the relay.

**Comment by oldman4U** [comment]
Hi

One month and no answer. What is the status of the reported issue my young Padawan?

Please let me know

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
