### ISSUE TITLE
Complie errors due bad merging

### ISSUE THREAD

**Issue by UnknownHero99** [bigtreetech/BIGTREETECH-TouchScreenFirmware#101]
@bigtreetech there were compile errors for 2 merges in a row now please create development branch and merge it with master when tested, check pull requests more carefully and i guess merge only pull requests with no conflicts, or at least after merging check for compile errors before pushing it to master

[version](https://github.com/UnknownHero99/BIGTREETECH-TouchScreenFirmware) before making it useless compiles ok, but some icons are missing..

**Comment by bigtreetech** [comment]
Complie errors has be fixed now. Actually, I'm a novice of GIT  ^_^, so sorry for that. 
missed icons will be uploaded later, (TFT24/TFT28 icons and font also will be uploaded lader)

**Comment by UnknownHero99** [comment]
no problem, everyone needs to start somewhere but please consider making development branch :P

**Comment by UnknownHero99** [comment]
@bigtreetech oh and thumbs up because ur applying merges so quickly and bltouch icons are nice too :D
