### ISSUE TITLE
[BUG] (Touchscreen mode, fans menu; speed percent not updating when FULL or STOP is pressed)

### ISSUE THREAD

**Issue by NAPCAL** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1016]
### Description

The fan issue is with any fan, the **FULL** and **STOP** don't update the screen %.

### Steps to reproduce

1. Have speed percentage as the default. 
2. Select Fan menu
3. Use FULL or STOP, doesn't update when the speed percentage but stays with the previous value.  
4. Code changes to correct this provided below.

**Expected behavior**
When selecting FULL then the display should update to 100%.
When the percent is greater than 0% then selecting STOP then the display should update to 0%.

**Actual behavior**
When selecting FULL the fan does go to full speed but the display shows the previous set value.
When selecting STOP the fan does stop but the display shows the previous set value.

**Worked a fix by changing this code in TFT\src\User\Menu\Fan.c**

      case KEY_ICON_5:
        fanSetSpeed(curIndex, infoSettings.fan_max[curIndex]);
        break;

      case KEY_ICON_6:
        fanSetSpeed(curIndex, 0);
        break;

To this:

      case KEY_ICON_5:
        if (infoSettings.fan_percentage ==  1)
        {
        fanSetSpeedPercent(curIndex, 100);
        }
        else
        {
          fanSetSpeed(curIndex, infoSettings.fan_max[curIndex]);
        }
        break;

      case KEY_ICON_6:
        if (infoSettings.fan_percentage ==  1)
        {
        fanSetSpeedPercent(curIndex, 0);
        }
        else
        {
          fanSetSpeed(curIndex, 0);
        }
        break;

P.S. there have been so many changes to the code for the TFT's but no update to the firmware version. I think this is just asking for trouble since it will be very hard to relate to what code revision has the error.

**Comment by traffic-light** [comment]
I agree. There should be a firmware version.
Maybe everyday/ one time a week at the end of the day/ week creating binaries and a release. And for example: vxx.x.26.3 instead of 26.x

With a small description what is changed and fixed

**Comment by oldman4U** [comment]
Has there been a PR for this?

**Comment by oldman4U** [comment]
Any news?

**Comment by NAPCAL** [comment]
I think it was addressed by another BUG report.

**Comment by oldman4U** [comment]
So the problem is solved for you?!!

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
👍🏻
