### ISSUE TITLE
Solution for this error?

### ISSUE THREAD

**Issue by ivindor** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1018]
![5C88A015-19CB-450F-8863-5C854C84EF8D](https://user-images.githubusercontent.com/70163648/91072472-dfc55f80-e639-11ea-9227-3acb983e8973.jpeg)
**Your question or details you need. Please describe.**
A clear and concise question or detail you would like to ask. Like Hardware related or firmware related.

**specify the device variant related to your question.**

**Additional context**
Add any other context or screenshots about the question here.

**Comment by ivindor** [comment]
starts printing and after a while the printing stops and this error occurs

**Comment by ivindor** [comment]
![C07ABBA6-077B-41FC-9EAA-5B1DA6064C72](https://user-images.githubusercontent.com/70163648/91074983-a55dc180-e63d-11ea-81f5-530051f665a7.jpeg)

**Comment by oldman4U** [comment]
Which mainboad?
Which firmware board and tft?
New problem and what changed?
Which slicer software?

**Comment by ivindor** [comment]
Skr 1.4 turbo 
Firmware Marlin 2.06 and the tft is last update 9438192
yesterday I changed the firmware of the tft to solve the bug of the f0 fan and now this appears
And the slicer is test whit prusaslicer and superslicer

**Comment by ivindor** [comment]
![D7035C2C-165F-4E08-919B-E25BA406BCE2](https://user-images.githubusercontent.com/70163648/91077239-063ac900-e641-11ea-8e2b-8c3a6d5c53e9.jpeg)

**Comment by snakesrules94** [comment]
the gcode file was tested with the previous FW of the screen ? What was the FW version before updating ?

**Comment by Tygrys-1** [comment]
1) Try to use different SD card.
2) Try to print from USB
3) Verify, that shown errorr lines are correct in the file. The begining of the lines looks corrupted.

**Comment by radek8** [comment]
Will this error appear even if you print from Marlin mode?

**Comment by ivindor** [comment]
No appear in touch mode

**Comment by oldman4U** [comment]
Hi.

What is the status of this ticket?

Please let us know

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
