### ISSUE TITLE
[BUG] (short description)CHANGE FLOW RATE & SPEED DURING PRINTING NOT WORKING PROPERLY

### ISSUE THREAD

**Issue by Jeripimo** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1019]
### Description

When changing the print speed or flow rate during printing the value not stable and jumps back to lower value
Error message: ' busy processing, please wait ....'

### Steps to reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior**

**Actual behavior**

### Additional Information
* Include a ZIP file containing your `Configuration.h` or use [Pastebin](https://pastebin.com/) and paste a link in this issue.
* Provide pictures or links to videos that clearly demonstrate the issue.

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
