### ISSUE TITLE
SKR Pro + TMC5160 + PT100 using MAX31865+ BTT TFT35 v2 = no attached printer

### ISSUE THREAD

**Issue by code505** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1020]
**Your question or details you need. Please describe.**
I'm having issue working this configuration
#define SERIAL_PORT -1 #define SERIAL_PORT_2 1

I'm using this guide to connect MAX31865 in software SPI configuration:
https://drive.google.com/file/d/1zOky07F_R_DO_-XxZx6C3xULqhuxYMOi/view?usp=sharing

once I change TEMP_SENSOR_0 to -5, I got the no attached printer, otherwise TFT is working

any thoughts
the baudrate is 115200 on both the board and the TFT

what I want to emphasise on, is that when I put,
TEMP_SENSOR_0 1 >>>> TFT is working with no issue
if
TEMP_SENSOR_0 -5 >>>> TFT show no printer attached

**Additional context**
![IMG_8996](https://user-images.githubusercontent.com/58148264/91217155-bd0d7680-e71f-11ea-8f88-5771378c98c8.jpg)

**Comment by carl1961** [comment]
In Marlin -5 means  INDEX_NONE = -5  I would think you may need marlin mode to use the PT100
I searched BTT touch code for MAX31865 is it did  showed MAX31865 any where so may not be supported yet.

**Comment by oldman4U** [comment]
@code505 

Seems this issue got some covering in the SKR Pro repo. So could you please close this ticket here.

Thank you and i hope you will find a solution finally

**Comment by oldman4U** [comment]
Hi. 

Could you please close this ticket. Seems it is well covered in the SKR Pro repo. 

Thank you
