### ISSUE TITLE
[FR] Alternate elapsed/remaining time during printing.

### ISSUE THREAD

**Issue by hackra76** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1026]
**Is your feature request related to a problem? Please describe.**
Would it be possible to alternate the elapsed and remaining print time during printing on the screen in the small rectangle where print time is displayed ??? Kind of like the Speed and Feedrate is alternating ? I think that it would be a cool feature...

Thanks.

**Comment by traffic-light** [comment]
That can be hard to make.
It could be possible to check the percentage it's currently at and the time it took.

But that's not really a reliable way.

When the slicer can calculate the time and prints it somewhere in the gcode it could be subtracted from there.

**Comment by Tygrys-1** [comment]
The Marlin does this that way - maybe inaccurate, but better than nothing. It is an ETA, not a prophet to fulfill ;-)
The slicer might be inacurate too. It does not know all the hardware defaults you changed.

**Comment by traffic-light** [comment]
Okay. If no one is making it within 3 weeks please remind me. maybe I'll have time to make it

**Comment by cctl01** [comment]
@traffic-light friendly reminder.. this info is already available in marlin FW mode as Tygrys-1 described.

**Comment by traffic-light** [comment]
> @traffic-light friendly reminder.. this info is already available in marlin FW mode as Tygrys-1 described.

i know. but not in tft mode

**Comment by cctl01** [comment]
This looks like miscommunication, you originally asked to be reminded. 
In my reminder I added the additional info of the feature being available in marlin mode because perhaps that helps you or someone else implementing. Also I fail to see why the request  has been closed in the meantime.

**Comment by hackra76** [comment]
Closed by my mistake, sorry..

**Comment by oldman4U** [comment]
Hello hackra76.

Could you please be so kind and close this ticket. Your feature request is covered in the pinned Feature Request ticket #1177 

Thank you
