### ISSUE TITLE
all freeze after preheat any tamplate

### ISSUE THREAD

**Issue by JediRAMA** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1032]
when i try any preheat, everything freezing
https://www.youtube.com/watch?v=16HtzF1VPJE
skr 1.4 turbo,  tft35 firmware from 21.08.2020,  marlin 2.0.5.4
[Configuration.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5137883/Configuration.zip)

**Comment by traffic-light** [comment]
This is not really a bug.
You need to upload the new config.ini.
When you do that it will not freeze anymore.

**Comment by traffic-light** [comment]
@JediRAMA 
Did it solve your problem?

**Comment by traffic-light** [comment]
@bigtreetech I think this one can be closed. The user didn't updated the config.ini. that's for sure.

And is not responding.

**Comment by oldman4U** [comment]
New users starting their first ticket and never reply after that is an ongoing problem. Such tickets are often hanging around forever.

**Comment by traffic-light** [comment]
Jup... Pretty anoying

**Comment by oldman4U** [comment]
@bigtreetech 

Could you please close this ticket from the same user: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/362

Thank you

May the force be with you
