### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by Arevlis** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1042]
**Your question or details you need. Please describe.**
A clear and concise question or detail you would like to ask. Like Hardware related or firmware related.

**specify the device variant related to your question.**

**Additional context**
Add any other context or screenshots about the question here.

**Comment by Arevlis** [comment]
Notice spelling error of configuration.h
TFT>src>User>C Configuration.h
1  #ifndef _CONFIGRATION_H_
2  #define _CONFIGRATION_H_

**Comment by traffic-light** [comment]
Added to my pr
