### ISSUE TITLE
[Q] (Change TFT28 Layout?)

### ISSUE THREAD

**Issue by JaviPraPi** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1044]
Hi! Im using the BIQU TFT 2.8 to run a CNC.
However, there are a lot of options that are not needed in a CNC. (Heating, Leveling,Fan, bed, extrude...) and id like to have a custom buton in the main page to home each axes.

Wich file do i have to change to modify the Menu Overview?

BIQU TFT 28
Skr V1.3

**Comment by radek8** [comment]
If you have to ask this, you better not do it yourself

**Comment by radek8** [comment]
https://github.com/BlomsD/MPCNC-TFT35-V2.0

**Comment by Tygrys-1** [comment]
> 
> 
> https://github.com/BlomsD/MPCNC-TFT35-V2.0

This one is quite outdated and for TFT35 v.2.0 only.

**Comment by oldman4U** [comment]
Ticket #571 and #574 are already covering this CNC related features.

Please close this ticket, thank you
