### ISSUE TITLE
[BUG] Update the print speed value when printing

### ISSUE THREAD

**Issue by radek8** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1048]
If I change the print speed while printing (for example, with an encoder directly in Marlin), the speed will not change on the PrintingMenu screen until I open the Speed Control menu. Only then will the Speed value be updated.
If it does not print, the StatusScreen screen works fine

https://youtu.be/kRYwBqbGrRU

**Comment by oldman4U** [comment]
I am sure it is great to be able to solve bugs which you found right before;-)

**Comment by radek8** [comment]
Unfortunately it doesn't work well :-(

**Comment by oldman4U** [comment]
😞

**Comment by oldman4U** [comment]
So what are your plans?

**Comment by radek8** [comment]
solved in PR #1060

**Comment by oldman4U** [comment]
The usual suspect.  Gurmeet👍🏻
