### ISSUE TITLE
[Q] May I flash MKS TFT7.0 with BTT 7.0 bootloader and firmware?

### ISSUE THREAD

**Issue by karabas2011** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1049]
As I know both diplays use  the same processor STM32F407
So can I flash MKS TFT7.0 with BTT 7.0 bootloader and firmware?

**Comment by traffic-light** [comment]
Processor doesn't mean that the pin out is the same.
You could try it out.

**Comment by traffic-light** [comment]
@karabas2011 You can close the ticket when it's not longer needed ;-)
