### ISSUE TITLE
[BUG] TFT70 freeze after connect U disk

### ISSUE THREAD

**Issue by yarkiks** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1052]
### Description
After flashTFT70 V3.0 with newest firmware I cant print form U disk. When pendrive or even empty SD card reader is connected pendrive led blink less than one second, TFT is getting freeze and I have to unplug USB device and restart TFT. Otherwise TFT is black.
When i comment lines U_DISK_SUPPORT and USE_USB_OTG_FS in file PIN_TFT70_V3_0.h TFT is working and pendrive led is lighting normally but U Disk option is disabled. Latest working precompiled binary is #839 

### Steps to reproduce
1. Insert U DISK

**Expected behavior**
Print form U DISK

**Actual behavior**
TFT freeze

### Hardware Variant
TFT 70 V3.0 and SKR PRO V1.2

**Comment by traffic-light** [comment]
Did you compile with the latest release in the master?

**Comment by yarkiks** [comment]
Yes, when I compile situation is worse because even when I compile #814 TFT is freezing after USB connection

**Comment by traffic-light** [comment]
Okay. maybe it's screen related..
No problems here. Maybe you should format the usb stick. When there is a corrupt file it could be possible to make the screen crash

**Comment by oldman4U** [comment]
Maybe there is a problem with the power and the TFT does not get enough of it...

**Comment by oldman4U** [comment]
...and not to forget our evergreen - the config.ini file....

**Comment by yarkiks** [comment]
Format U disk many times. I will try with FAT but TFT freeze also with USB card reader without card inside.
I dont think that could be power problem, I,m using stock wires and everything is working good with stock firmware.
I'm using standard config file with no modifications.

**Comment by traffic-light** [comment]
It could be a power problem, like oldman said. Could you try connecting a extra powerline to the lcd's screen powerin connector?

**Comment by yarkiks** [comment]
I will try, probably tommorow.

**Comment by yarkiks** [comment]
Powered up from laboratory PSU-Korad KA3005P and TFT draws 430mAmps with 100% brightness and 225mA with 20%.
Only power is connected to board.
When connecting pendrive current reach 290mA for a few seconds, TFT is freezing and current goes to 200mA. 
When connecting pendrive that it can draw current and data lines are disconnected everything draws 280mA. Led on it is lighting but data lines aren't connected so TFT is not freezing.

**Comment by oldman4U** [comment]
So it freezes as soon as the data lines are connected but not without data lines connected. And you tried different brands of U Disks?

If so, i would expect a broken screen.

**Comment by yarkiks** [comment]
I was trying with 2 U Disks and one card reader.
For me it is weird that with first two precompiled binaries everything is working and with latest one TFT is freezing. 
I will contact BTT directly via mail.

**Comment by oldman4U** [comment]
So it has been working and still works when using an older firmware!!??

yarkiks <notifications@github.com> schrieb am Fr. 4. Sep. 2020 um 17:00:

**Comment by yarkiks** [comment]
Yes, when I'm using first binary provided to TFT70 everything is working well.

**Comment by oldman4U** [comment]
I am sorry. Reading the ticket again from the beginning I can see that you perfectly described everything!

Can you see whose code broke it and add him to this ticket using @andthenickname

**Comment by yarkiks** [comment]
I have to learn how to do it and I will add him. Any links will be helpful

**Comment by oldman4U** [comment]
Now the funny part starts for you....

I assume you have a PC or Mac. Then i would follow this video to install VSC and PIO as the first step:

**Comment by yarkiks** [comment]
Already installed VSC and PIO. I was thinkinking about links how to see whose code is breaking TFT.

**Comment by oldman4U** [comment]
Perfect!

Please see attached screenshot which shows the important parts.

This website
Code tab
The MASTER Branch which has to be selected and
the two arrows.

When you click on such a arrow button, a new page opens which allows you to download the code from exactly this point of the development.

<img width="1668" alt="Screenshot 2020-09-04 at 23 02 03" src="https://user-images.githubusercontent.com/54359396/92284821-2f8e0b80-ef03-11ea-91f1-f095356c988d.png">

Let me know

**Comment by traffic-light** [comment]
> Perfect!
> 
> On the main page click on this:
> 
> <img alt="Screenshot 2020-09-04 at 23 09 07" width="1142" src="https://user-images.githubusercontent.com/54359396/92285119-d4104d80-ef03-11ea-9cb3-0d67014f0710.png">
> 
> The next screenshot shows the important parts.
> 
> This website
> Code tab
> The MASTER Branch which has to be selected and
> the two arrows.
> 
> When you click on such a arrow button, a new page opens which allows you to download the code from exactly this point of the development.
> 
> <img alt="Screenshot 2020-09-04 at 23 02 03" width="1668" src="https://user-images.githubusercontent.com/54359396/92284821-2f8e0b80-ef03-11ea-91f1-f095356c988d.png">
> 
> Let me know

Ooh! Good description. May I use those pictures in my manual? I will.credit you on the credits page

**Comment by oldman4U** [comment]
@bigtreetech 
@Msq001 

I believe it would be good, if you could check this ticket.

Thank you

**Comment by yarkiks** [comment]
So I build and install this fw https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/tree/3b6206679ea42c7650cf284920afb71db6ca38f3

**Comment by oldman4U** [comment]
Yes, this is the current release. Now you can check the releases between the one which works and the newest to find out where it breaks and which one is the last which works.

For example does this work?
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/tree/fb861864aff4f5651abe5e7708559235c088c544

**Comment by yarkiks** [comment]
My head just exploded. Compiled and installed firmware from your link - freezing TFT. Installed precompiled binary - not freezing. 
Is it possible that @bigtreetech have different drivers or using different compiler and their binaries are working good?

**Comment by oldman4U** [comment]
@traffic-light Do you have a TFT70 also and you run the latest firmware without problems and you can print from U Disk?

@yarkiks Do you want to try this: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/tree/01805c79c34bebaa5336cf44836df45530909ea1

This is right before the Cura Preview was added.

To see if the precompiled makes a difference, you can try this: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/tree/b4a7efe18202fd93d9b5a9daba4383d14e861572

Please let me know

**Comment by yarkiks** [comment]
Only binaries compiled by btt are working. When connecting U disk led on it blinks one time. Next led on U disk gets off, TFT shows notification that U disk is connected and then led on U disk is on again.
When firmware is compiled on my computer first blink is short and TFT is freezing.

**Comment by yarkiks** [comment]
Just watch videos.
https://drive.google.com/drive/folders/1dSJy6TUGEsrCtxMvKTpmRM20XPNuRhm8?usp=sharing

**Comment by oldman4U** [comment]
So when you compile this: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/tree/b4a7efe18202fd93d9b5a9daba4383d14e861572

and you upload it to your screen, you see the problem?

**Comment by oldman4U** [comment]
OK. So I do not know for sure, but this is the firmware right before the official compiled version has been released. So this should give you the same results.

When you update the firmware, which files and folders do you have on the root of the SD card?

**Comment by yarkiks** [comment]
Folder TFT70, files config.ini and BIGTREE_TFT70_V3.0.26.x.bin
Gcodes that I printed from SD and 4 stock folders from Ender 5 SD.
As I say only two binaries precompiled by @bigtreetech working.

**Comment by oldman4U** [comment]
OK.

Please forgive my stupid question, but when you upload a home brewed firmware, you are also copying the TFT70 folder and the config.ini from that new version onto the SD card, and you are not using the one from the precompiled version?

**Comment by yarkiks** [comment]
Compiled by myself
binary: BIGTREETECH-TouchScreenFirmware-master\.pio\build\BIGTREE_TFT70_V3_0
config: BIGTREETECH-TouchScreenFirmware-master\TFT\src\User or BIGTREETECH-TouchScreenFirmware-master\Copy to SD Card root directory to update - Unified Menu Material theme
Both not working
TFT70: BIGTREETECH-TouchScreenFirmware-master\Copy to SD Card root directory to update - Unified Menu Material theme
Precompiled:
all files: BIGTREETECH-TouchScreenFirmware-b4a7efe18202fd93d9b5a9daba4383d14e861572\Copy to SD Card root directory to update - Unified Menu Material theme

**Comment by oldman4U** [comment]
What do you mean with "both not working".

When you compile your own firmware, you also have to use the TFT folder (which includes the font and the bmp folder) and the config.ini from the same firmware folder, like shown in this screenshot:
<img width="525" alt="Screenshot 2020-09-07 at 20 32 04" src="https://user-images.githubusercontent.com/54359396/92411705-4160f000-f149-11ea-8ded-95fb4fedcdb9.png">

Using the self compiled firmware and the TFT folder and the config.ini from another version will not work.

**Comment by JackTFG** [comment]
Hello, same problem for me. I bought a tft70, was working fine with skr mini e3 v2. Decided to put the latest firmware and boom usb freezing. Will try to find an old firmware which works..

**Comment by oldman4U** [comment]
Good to have a second user with the same problem.

**Comment by JackTFG** [comment]
Yes, so you know. It is just a firmware problem

**Comment by oldman4U** [comment]
Seems so. Now we need someone fixing it. Or we wait for the next precompiled version😀

**Comment by JackTFG** [comment]
Will try to compile tomorrow, and if it Don t works will wait the next version...

**Comment by oldman4U** [comment]
Great. Please let me know.

Thank you

JackTFG <notifications@github.com> schrieb am Di. 8. Sep. 2020 um 08:26:

**Comment by JackTFG** [comment]
Yes sûre!

**Comment by yarkiks** [comment]
![Adnotacja 2020-09-08 134522](https://user-images.githubusercontent.com/70610715/92472793-491ca500-f1da-11ea-9b56-79a42151f911.png)
Have you same warning?

**Comment by oldman4U** [comment]
This is the whole compile process??

This is how it looks like on my machine and there
<img width="1679" alt="Screenshot 2020-09-08 at 19 52 40" src="https://user-images.githubusercontent.com/54359396/92505611-03c59b00-f20d-11ea-966e-d9e5fab11aa5.png"> are some lines missing in between
...

<img width="1679" alt="Screenshot 2020-09-08 at 19 52 52" src="https://user-images.githubusercontent.com/54359396/92505597-ff00e700-f20c-11ea-8f5c-6985487b535a.png">

**Comment by oldman4U** [comment]
Warning seems "normal":

https://community.platformio.org/t/custom-linker-script-stm32cube/8217

**Comment by oldman4U** [comment]
Arrrgh. You compiled before and because of this it does not have to compile the whole stuff again. Looks the same on my machine when compiling not for the first time...

You could try to delete the existing folders like shown here, to see if a complete new compiling solves the issue...

Navigate to the existing folder
<img width="515" alt="Screenshot 2020-09-08 at 20 32 17" src="https://user-images.githubusercontent.com/54359396/92510256-3e7f0180-f214-11ea-95a3-1bc38fa0f357.png">

delete everything or just the selected items.
<img width="867" alt="Screenshot 2020-09-08 at 20 32 50" src="https://user-images.githubusercontent.com/54359396/92510280-43dc4c00-f214-11ea-88c9-050d407ba876.png">

**Comment by yarkiks** [comment]
Didnt helped.
Probably tomorrow I will have more free time and will try to compile older versions.

**Comment by yarkiks** [comment]
![image](https://user-images.githubusercontent.com/70610715/92567213-a9185780-f27d-11ea-95c2-eb6538ef700e.png)
Maybe it is stupid question but why board is STM32F103VC. Microcontroller used in tft is STM32F407VGT6

**Comment by oldman4U** [comment]
I have to call for the pro's....

**Comment by oldman4U** [comment]
Hi.

We can stop looking for the problem, it is in firmware. Just got the confirmation from another person who has the same TFT...

Hope we will hear about a fix very soon.

**Comment by guruathwal** [comment]
@oldman4U  I can confirm the freeze.
@yarkiks the last know working fimware you mentioned is a precompiled file on July 23, which is very old compared to the changes in the firmware. Can you point to a closer commit which was working ? If possible.

**Comment by yarkiks** [comment]
last working precompiled binary
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/tree/b4a7efe18202fd93d9b5a9daba4383d14e861572

**Comment by JackTFG** [comment]
> last working precompiled binary
> https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/tree/b4a7efe18202fd93d9b5a9daba4383d14e861572

thx a lotttttttt it works for me too. Try other version, try to compile myself etc... nothing worked. Your version work, some features are missing but it works. thx !

**Comment by JackTFG** [comment]
Well..... works, untill i launch a print, then my screen freeze....

**Comment by yarkiks** [comment]
try this one
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/commit/caf5836d98a6b24a699f2e9c41b11953ad402df7

**Comment by guruathwal** [comment]
It looks like the problem is from the beginning. Even the first commit here https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/814 has the same issue.
The TFT will freeze as soon as the USB drive is connected. 
The precompiled files also have the same issue with the device I have.

**Comment by Msq001** [comment]
confirm and sorry for that,   debuging in progress

**Comment by oldman4U** [comment]
@Msq001 

Would have been great if you or BTT could have checked this 6 days ago.

Maybe next time.

Thank you

**Comment by Msq001** [comment]
I'm so sorry to reply so late...
Can someone help confirm if #1078 works?

**Comment by yarkiks** [comment]
YEAH working!

**Comment by oldman4U** [comment]
👍🏻

**Comment by JackTFG** [comment]
yessss

**Comment by NAPCAL** [comment]
Fixed.

**Comment by oldman4U** [comment]
👍🏻
