### ISSUE TITLE
TFT35 E3V3 freezes when entering the preheating menu

### ISSUE THREAD

**Issue by Moreman73** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1054]
When the preheat menu is selected, the preheat menu opens, but the display stops responding to touching the screen and two of the six icons are missing labels 
![IMG_20200903_110117](https://user-images.githubusercontent.com/66413573/92082186-459dae00-edd5-11ea-944d-55032c58ac6c.jpg)

**Comment by traffic-light** [comment]
Okay.. i'll add this one to my faq...
Use the search function and you will find out that you didn't update your .in file.

Please close the ticket

**Comment by traffic-light** [comment]
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/1032

**Comment by oldman4U** [comment]
traffic-light is faster than light....;-)

**Comment by Moreman73** [comment]
thanks, now everything works fine

**Comment by oldman4U** [comment]
Moreman73

Please close also this ticket: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/757

Thank you
