### ISSUE TITLE
Смена нити

### ISSUE THREAD

**Issue by SerjPr** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1056]
If I want to change, then I have to go to the menu from the beginning. Then I have to go to the extrusion menu, wait until it heats up and then give the command to unload or load. It is not comfortable. It would be nice if you give the command to unload or load, the heating is automatically turned on or a menu appears with a choice of the type of thread. Heated loading or unloading with the STOP button. And then the heating was turned off.

Если я хочу сменить нить то я должен с начало зайти в меню нагрева и включить нагрев. Затем я должен зайти в меню экструзия подождав пока нагреется а затем дать команду выгрузка или загрузка. Это не удобно. Было бы хорошо если даешь команду выгрузка или загрузка включался автоматически подогрев или появлялось меню с выбором типа нити. Происходил подогрев затем загрузка или выгрузка с возможностью нажать СТОП. А затем подогрев выключался.

**Comment by AnHardt** [comment]
When writing not in English your audience is not as large as it could be.

**Comment by SerjPr** [comment]
Так вы будете знать что это проблема Google переводчика а не моего мышления.

**Comment by oldman4U** [comment]
And please check all the other tickets before. Your feature request to have a load and unload has been asked before.

Please close this ticket

Thank you

**Comment by SerjPr** [comment]
> И пожалуйста, проверьте все остальные билеты перед этим. Ваш запрос функции на загрузку и разгрузку был запрошен ранее.
> 
> Пожалуйста, закройте этот билет
> 
> Спасибо

Have you read? These are completely different topics.

**Comment by oldman4U** [comment]
If i understand right you are asking for a button which allows to load and unload filament on a bowden printer. Right?

**Comment by SerjPr** [comment]
So that there was an option for automatic loading and unloading of the thread.

**Comment by oldman4U** [comment]
Ok, so I understood it correctly.  I am on the mobile phone right now so I can not search easily the tickets but there are a few asking for this feature. So it is absolutely  possible that this function will be available in the future.

**Comment by SerjPr** [comment]
You have an upload and download button. But first you need to go to another menu and press warm-up. And this is not convenient

**Comment by oldman4U** [comment]
Look at this for example. It is the same feature request and includes a link to a possible work around.
