### ISSUE TITLE
error in config.ini

### ISSUE THREAD

**Issue by Thijsvanzwam** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1064]
### Description

updating config.ini gives an error on the LCD saying: "invalid Values.  fan_ctrl_count: 0"
changed value to 1 but error remains

### Steps to reproduce

update to latest firmware, self compiled

**Expected behavior**
no errors
**Actual behavior**
all works after update but not sure if I will encounter problems in the near future.
Did not do a test print yet

### Hardware Variant
tft 3,5 v3
### TFT Firmware Version & Main Board Firmware details
Latest marlin

**Comment by Guilouz** [comment]
Same here

**Comment by traffic-light** [comment]
mmmm strange. Its configured correctly in the firmware project. It should load the setting correctly...

**Comment by blueeagle69** [comment]
I just tested on my TFT35 e3 V3.
I never noticed the day before yesterday as I walked away when flashing the firmware. Decided to re-upload my config to the screen and I'm seeing the same error.
