### ISSUE TITLE
Z home and auto bed leveling

### ISSUE THREAD

**Issue by lawsjr** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1068]
So got the printer working . I have a BLTouch and have it enabled in the firmware. I am getting a failed to enable auto bed leveling and when I try to do a z home the z axis doesn't move at all

**Comment by traffic-light** [comment]
Does it work in marlin mode?
If that's not working there is something off in your marlin firmware

**Comment by lawsjr** [comment]
Right now it fails as soon as the printer is powered on. No self test or anything

**Comment by radek8** [comment]
Do you have a BLTouch connected correctly?

**Comment by lawsjr** [comment]
It came with the plug backwards on the probe itself.  Probe is working but won’t Z home

**Comment by radek8** [comment]
send Configuratin.h and configuration_adv.h

**Comment by blueeagle69** [comment]
What mainboard is it?
Possibly sounds like you need;
#define USE_PROBE_FOR_Z_HOMING
#define Z_MIN_PROBE_PIN P0_10 (SKR 1.4)

**Comment by lawsjr** [comment]
Got the probe to work and  now working on the auto bed leveling. The probe was plugged in wrong when installed at the factory.
