### ISSUE TITLE
Russian and Armenian font/Language not displaying correctly

### ISSUE THREAD

**Issue by guruathwal** [bigtreetech/BIGTREETECH-TouchScreenFirmware#107]
May be anyone has noticed or not. the Russian and Armenian languages are not displaying correctly.

**Comment by guruathwal** [comment]
both languages displaying correctly in latest build.

**Comment by GrishaKh** [comment]
I just tried to use the latest version again, but problems with fonts again occurred. I had to download the Vx.x.22 version and add Armenian letters to it. The result is quite good.

Link - [https://github.com/GrishaKh/Arm_Printer](https://github.com/GrishaKh/Arm_Printer)
