### ISSUE TITLE
Warmup Temps not shown w/ TFT35 E3 V3.0 (firmware 26.x) print from Board SD

### ISSUE THREAD

**Issue by bringbackgroupb** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1070]
When printing from the touch screen interface on the TFT35 E3 v3.0 running the latest 26.x firmware (as of Aug 5, 2020) the target and actual temperature are not shown in the printing interface.

### Steps to reproduce

1. Select print from on board SD card
2. Select file to print

**Expected behavior**
Bed temp set point >0, bed starts heating with actual temp reported.
Hot end temp set point >0, hot end starts heating with actual temp reported.
Home, then print

**Actual behavior**
Bed and hot end temp set points stay at 0. Actual reported temp is same as when print was started.
Home, then print.
After 1st layer has started, temperatures are now reported correctly.

### Hardware Variant
BTT TFT35 E3 V3.0
BTT SKR Mini E3 V2.0

### TFT Firmware Version & Main Board Firmware details
TFT - BIGTREE_TFT35_V3.0_E3.26.x.bin
Mainboard - Marlin 2.0.X (020006) (self configured)

### Additional Information
All configs included below:
[MarlinConfigFiles.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5185805/MarlinConfigFiles.zip)
[TFTconfig_20200907.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5185814/TFTconfig_20200907.zip)

**Comment by abacabie** [comment]
I have never actually got this to work when printing from the mainboard sd slot, the layer height doesn’t show either.

**Comment by blueeagle69** [comment]
The layer info was working. But the latest builds have broken it as far as I can tell.
I was going to open a bug report.
I'm using Prusaslicer.
I was given a hint to put this in my Before Layer Change Gcode and the on-screen Layer info did work.
But not now it appears.

**Comment by lococnc** [comment]
I can confirm this is a BUG, also TFT35 E3 V3.0 with SKR Mini E3 V2.0

**Comment by Grazuncle** [comment]
Yes I have noticed this.. it does seem to wake up later.

bit disconcerting though when i use Preheat and think nothing is happening LOL

you can feel the temp rising on the bed without actually touching it

**Comment by feiticeir0** [comment]
I've just opened a new bug for TFT35 v2.0 and SKR 1.4

**Comment by Grazuncle** [comment]
This will be a welcome fix..

thanks for reporting it.. 

I'd like to know what the distance icon does on the movement screen is LOL

That's new to me!

**Comment by jalensailin** [comment]
does whats suggested in #1127 help?

**Comment by oldman4U** [comment]
@Grazuncle You mean Distance in the Leveling menu? This is to define the distance from the border of your printer bed to the levelling points. This is 20mm by default, 50 works better for me, because usually my prints are printing in the middle of the bed.

Attached also a movie which shows the temp changing while heating up for a print from on board SD Card. I had to trim it a bit in the middle by 10sec to make it small enough to be able to upload it. This is using the TFT firmware from Oct. 19th and SKR E3 DIP on Marlin 2.0.7.2. Hope this helps
[Temp Changing print from SD card.mov.mov.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5422158/Temp.Changing.print.from.SD.card.mov.mov.zip)

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by blueeagle69** [comment]
I just tested on my screen.
If I print from onboard SD warmup temps do not update.
If I print from Udisk it works.

**Comment by oldman4U** [comment]
Then something has to be wrong with your or with my printer.

**Comment by blueeagle69** [comment]
Yep very odd.
Updates fine from TFT media but not onboard.
Cancelling a print from onboard media is also giving me the never-ending loading screen again. Again fine from TFT media.

**Comment by oldman4U** [comment]
Maybe the mainboard or Marlin makes a difference. The movie which shows it working well has been made using an SKR E3 DIP mainboard.

**Comment by oldman4U** [comment]
Please check out PR #1244 for a possible solution.

Thank you

**Comment by blueeagle69** [comment]
> Please check out PR #1244 for a possible solution.
> 
> Thank you

I have made the relevant change to my source, compiled and uploaded to my screen.
Just got to test now.

Thanks all!

**Comment by Cricket-15** [comment]
i had the exact same thing, i changed #### Temperature ACK from 0 to 1 and #### Persistent Temperature Info from 0 to 1 in the config.ini before i did a firmware update, fixed mine, ail are working now.
