### ISSUE TITLE
Where is jerk?

### ISSUE THREAD

**Issue by etimoe** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1071]
**Your question or details you need. Please describe.**
A clear and concise question or detail you would like to ask. Like Hardware related or firmware related.

**specify the device variant related to your question.**

**Additional context**
Add any other context or screenshots about the question here.

**Comment by zonalimitatore** [comment]
There isnt yet

**Comment by traffic-light** [comment]
> There isnt yet

That's not true ;-)

I've made a option in the machine settings menu ;-)

**Comment by zonalimitatore** [comment]
Yep...me to have add it,but not with the original one

**Comment by traffic-light** [comment]
> Yep...me to have add it,but not with the original one

I don't understand what you mean. I'm sorry

**Comment by zonalimitatore** [comment]
I mean that i dont have that option in the last firmware.
I had to write a firmware myself with the custom commands for editing jerk params

**Comment by traffic-light** [comment]
That's strange. When you compiled the newest firmware it should be there.

See #1033

**Comment by zonalimitatore** [comment]
i dont know why...i've not

**Comment by traffic-light** [comment]
Me neither. Did you compile the newest firmware by yourself?

**Comment by etimoe** [comment]
the jerk option does not appear in any menu of the last update

**Comment by zonalimitatore** [comment]
> Me neither. Did you compile the newest firmware by yourself?

Yes

**Comment by zonalimitatore** [comment]
> the jerk option does not appear in any menu of the last update

So I'm not the only one

**Comment by traffic-light** [comment]
Are you looking at the right location?
Menu --> Settings --> Machine --> Prameters

Search in the list for jerk.
![image](https://user-images.githubusercontent.com/37051137/92730174-ac8e0a80-f373-11ea-8c2c-21615a30ded0.png)

![image](https://user-images.githubusercontent.com/37051137/92730193-b283eb80-f373-11ea-881c-6e1aaf5a30ea.png)

**Comment by etimoe** [comment]
yes, parameters, but no jerk option

**Comment by traffic-light** [comment]
What do you need for options?
In the parameters menu is good enough. at least, that's what I think. 

I don't understand what you want/ need

**Comment by AnHardt** [comment]
The decision if to use jerk(speed) or junction deviation?
That's a compile-time decision in marlin. No display or g-code can have influence upon this.

**Comment by zonalimitatore** [comment]
Keep out junction,use jerk

**Comment by etimoe** [comment]
I do not request anything.
I comment that in the last version, the one from 6 days ago I don't have the Jerk setting.
Tft35 and Bigtree tft35 v.3.0.26

**Comment by traffic-light** [comment]
> I do not request anything.
> I comment that in the last version, the one from 6 days ago I don't have the Jerk setting.
> Copy to SD Card root directory to update - Unified Menu Material theme/
> Tft35 and Bigtree tft35 v.3.0.26
> 4-9-2020

There is your problem. The pre-compiled binary is not up to date. You've got to compile it on your own.

**Comment by etimoe** [comment]
Thought it was already compiled.
I have compiled it as is without changing anything and I already have yerk.
