### ISSUE TITLE
[FR] Smart RGB encoder control

### ISSUE THREAD

**Issue by LordBBQ** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1072]
It would be very useful to be able to have the encoder LED change colour based on the current printer state, like in marlin when using the touchscreen.

Example:
Idle: Off
Heater: from blue to red
Print: white
Completion: green
Idle: Off

**Comment by traffic-light** [comment]
I'm currently working on a firmware change that will change the encoder knob color when heating (while printing)
When it's complete it will become green ;-)

I can't test my code. My screen is broken. So you've got to wait ;-)

**Comment by traffic-light** [comment]
A better link:

https://github.com/traffic-light/BIGTREETECH-TouchScreenFirmware_peter/tree/neopixel_sequential_whileprint

(Pasted the wrong one before 😬 )

**Comment by LordBBQ** [comment]
Thanks. My TFT35 E3 should come soon and I should be able to test it shortly.

**Comment by thisiskeithb** [comment]
> I'm currently working on a firmware change that will change the encoder knob colour when heating (while printing).

Please make this configurable/allow it to be disabled.

**Comment by traffic-light** [comment]
> > I'm currently working on a firmware change that will change the encoder knob colour when heating (while printing).
> 
> Please make this configurable/allow it to be disabled.

That's already implemented ;-)

**Comment by thisiskeithb** [comment]
> That's already implemented ;-)

I’m aware you can change the default knob LED color or on/off state.

> I don't see any reason to make it configurable

For users who don’t want the knob color to change while heating/prefer the static (on or off) state instead.

**Comment by traffic-light** [comment]
> > I don't see any reason to make it configurable

>For users who don’t want the knob colour to change while heating/prefer the static (on or off) state instead.

As already mentioned.. I already implemented this in my code. You can turn off the sequential mode.

**Comment by thisiskeithb** [comment]
> (maybe i was not clear for you. but it's implemented in my fork...)

I didn’t try your fork. I’m just asking that it be configurable/disabled by default when you put in a PR here.

**Comment by traffic-light** [comment]
It is configurable in the feature menu. It is already ;-)

I think I disable it by default

Outlook for Android<https://aka.ms/ghei36> downloaden
________________________________

**Comment by oldman4U** [comment]
Hi. What is the status of the development?

**Comment by traffic-light** [comment]
The status is: waiting for my package to arrive .. I'm starting to be annoyed by the slooooow delivery......
CGO / Depart from airport
2020-09-12 21:03

深东凤岗仓 / Depart from facility to service provider.
2020-09-04 09:23

深东凤岗仓 / Shipment arrived at facility and measured.
2020-08-25 15:28

深东凤岗仓 / 4px picked up shipment.
2020-08-25 15:28

**Comment by oldman4U** [comment]
Next time I send you one of mine😎

Peter van Weeterloo <notifications@github.com> schrieb am Mo. 28. Sep. 2020
um 08:43:

**Comment by traffic-light** [comment]
hahah. that would be nice. The most annoying thing is that they also ship from europe since a short time...

**Comment by oldman4U** [comment]
BTT? Or a certain store you mean?

Peter van Weeterloo <notifications@github.com> schrieb am Mo. 28. Sep. 2020
um 09:36:

**Comment by traffic-light** [comment]
btt ships skr 1.4 and tft screens  (and some more) from europe.

Met vriendelijke groet;
Peter van Weeterloo
________________________________
Van: oldman4U <notifications@github.com>
Verzonden: maandag 28 september 2020 09:38
Aan: bigtreetech/BIGTREETECH-TouchScreenFirmware <BIGTREETECH-TouchScreenFirmware@noreply.github.com>
CC: Peter van Weeterloo <info@petrossystems.nl>; Comment <comment@noreply.github.com>
Onderwerp: Re: [bigtreetech/BIGTREETECH-TouchScreenFirmware] [FR] Smart RGB encoder control (#1072)


BTT? Or a certain store you mean?

Peter van Weeterloo <notifications@github.com> schrieb am Mo. 28. Sep. 2020
um 09:36:

**Comment by oldman4U** [comment]
Hi traffic-light. Are you still waiting for the TFT? Or are you working on something w?

**Comment by traffic-light** [comment]
> Hi traffic-light. Are you still waiting for the TFT? Or are you working on something w?

Yes... It's still not here.... Still waiting for it to arrive at the airport. And then i've got to wait until the customs think it's okay to send to the Netherlands where i live.

I'll never order again through biqu.equipment. it's horribly slow. And they can't say: Its because of covid19

**Comment by oldman4U** [comment]
Maybe we should further improve your readme first in the meantime and maybe also work on the FR list. Do you have an idea how this could work best?

**Comment by traffic-light** [comment]
> Maybe we should further improve your readme first in the meantime and maybe also work on the FR list. Do you have an idea how this could work best?

Would love to do that. But the problem is that i'm currently do a graduation internship and I've 4 re-exams.. So.. I don't have a lot of time for myself. So I'll have to finish that first...

It should be finished in march. From then on I'm an Embedded Systems Engineer :-P

**Comment by oldman4U** [comment]
Hey. Good luck!!

Wrong priorities for me, but if you think this is important for you....🤪

**Comment by traffic-light** [comment]
Haha yes. I wan't to finish it as soon as possible ;-)

My loan is already too high -_-'

**Comment by oldman4U** [comment]
Don’t ask. My daughter  did the BAR  in SF yesterday and today after
studying law for 6 years.  And we have 5 children

Peter van Weeterloo <notifications@github.com> schrieb am Mi. 7. Okt. 2020
um 23:27:

**Comment by traffic-light** [comment]
Aiiii.

A couple of years ago we could receive money from the government when you study and live on your own (without paying it back). But they changed that 5~6 years ago.

So now the only option is to receive a loan from the government....


Outlook for Android<https://aka.ms/ghei36> downloaden
________________________________

**Comment by oldman4U** [comment]
Or to have parents like us and a grandparents with a bit money in the
pocket.

Peter van Weeterloo <notifications@github.com> schrieb am Mi. 7. Okt. 2020
um 23:46:

**Comment by oldman4U** [comment]
OK. I am working on the FR list and it is almost done.

Not sure how far this project has been going so far, but finally this ticket is s duplicate of #634, so could you please be so kind and close this ticket.

The feature itself will be part of this list of course!

Thank you

**Comment by Stellarspace** [comment]
> I'm currently working on a firmware change that will change the encoder knob colour when heating (while printing).
> When heating is done it become the colour you did set in the feature settings
> When the print is finished it will be green.
> 
> When leaving the print menu it will be, again, the colour you did set in the feature settings
> 
> I also implemented it so that the neopixel will do the same as it would when printing form marlin:
> Heating: Blue to red
> Printing: White
> Done: Green
> 
> I will also make the colour of the knob red when PID tuning is buzzy and green when ready ;-)
> 
> I can't test my code. My screen is broken. So you've got to wait ;-)
> 
> What screen type do you use?
> I could send you a binary to test my current progress.
> 
> (You can find the code here: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/compare/master...traffic-light:neopixel_sequential_whileprint?expand=1
> 
> It needs some fine tuning. But I hope it works. Can't test it....)

What about adding an Auto button to the LED controls on the TFT? There is an OFF button and buttons to change the color, but no AUTO.

**Comment by traffic-light** [comment]
My screen and mainboard Will be delivered today :-D

**Comment by oldman4U** [comment]
Holy moly!!!! This is 😊

**Comment by oldman4U** [comment]
Which mainboard?

**Comment by traffic-light** [comment]
It's still a dream 😝
But I received it :-)

![IMG_20201024_141817](https://user-images.githubusercontent.com/37051137/97081613-ca51bf00-1603-11eb-964b-9636bc92f254.jpg)

And looks like it's working correctly

**Comment by traffic-light** [comment]
It's exactly 2 months ago I did place the order ;-)

**Comment by oldman4U** [comment]
But worth the time 😁 SKR TURBO.

**Comment by oldman4U** [comment]
> It's still a dream 😝
> 
> But I received it :-)
> 
> 
> 
> ![IMG_20201024_141817](https://user-images.githubusercontent.com/37051137/97081613-ca51bf00-1603-11eb-964b-9636bc92f254.jpg)
> 
> 
> 
> And looks like it's working correctly

So you don't need any help with connecting and firmware update!!?? A bit disappointing I must say😎

**Comment by traffic-light** [comment]
Hhahahaha

I received some error when stating the UBL probe. Probing failed... Can't figure out the problem. Can you huys help me? What did i do wrong
