### ISSUE TITLE
[Q] Can I delete Bump Sensitivity on touch mode?

### ISSUE THREAD

**Issue by zonalimitatore** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1073]
Like title,I've 2208 and Inthe params settings I've that voice. 
Can I delete it?

**Comment by traffic-light** [comment]
You could do it on you're own. I don't know your programming skills but it would be some work to do.
I can give you some help after "work"

**Comment by zonalimitatore** [comment]
Ok thanks. I ask that only because if that can cause a problem.
I mod and recompile it

**Comment by radek8** [comment]
You can leave the choice in the menu, nothing will happen even if you click on it

**Comment by zonalimitatore** [comment]
Yep,I notice 👍😉
