### ISSUE TITLE
Where is the "ABS" icon for TFT70? 

### ISSUE THREAD

**Issue by killrob** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1077]
Hi all i want to change the ABS icon for the TFT70 in touch mode and also the text below.
Where can i find it?
Regards.

**Comment by radek8** [comment]
Change the icon name in the CONFIG.INI file
You can only change an icon for everyone at once by replacing it in the icon folder before flashing

![image](https://user-images.githubusercontent.com/46979052/92954133-3bc61b80-f463-11ea-9482-d67e53abda47.png)

**Comment by oldman4U** [comment]
Hello killrob.
It seems that you are collecting tickets.

When you start a ticket and you do not need it anymore, please close the ticket afterwards by clicking the corresponding knob at the end of the ticket.

Same for this ticket: https://github.com/bigtreetech/BIGTREETECH-SKR-V1.3/issues/367

Thank you
