### ISSUE TITLE
[BUG] SOLVED (short description)TFT35 E3 V.30 / Ender 3 / "no printer attached"

### ISSUE THREAD

**Issue by pierremilcent** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1080]
SOLVED : see comment at the end 

Ender 3 Pro worked fine with Creality 1.1.4 board (Marlin 1.1.6 with BLTouch cofigured)
Then i installed the just new SKR minin E3 V2 and TFT35 E3 v3 i received.
Swapping board and TFT in the same session.
Turned on the printer : all working : printer connected, moving X,Y, Z, starting hot end and bed.

This was captured just after this initial step.
![119161349_10158818386495984_1014213513762818954_n](https://user-images.githubusercontent.com/38214885/92986449-3f858c80-f4bb-11ea-90a8-7a69356bd0d1.jpg)

BLTouch was in error since by default the firmware loaded in the factory is not for supporting bltouch.
So i decided to update the firmware with the one including bltouch support.
This is then that all stopped working with "no printer connected" message. So i tried to reload the default still with no success.
My conclusion is : the TFT is working. The board is not working since no firmware loaded, so no connection

![119215018_10158818658800984_1913885861816451178_n](https://user-images.githubusercontent.com/38214885/92986450-401e2300-f4bb-11ea-92fa-27bdd58da037.jpg)

![119441441_10158818659480984_2780558891254717907_n](https://user-images.githubusercontent.com/38214885/92986451-401e2300-f4bb-11ea-9157-a3da953c1682.jpg)

**Comment by radek8** [comment]
Do you have a second ribbon cable connected?
Switch to Marlin mode.
Does Marlin work?

**Comment by radek8** [comment]
Do you have the same communication speed set in marlin and in the display?

**Comment by pierremilcent** [comment]
I have both cable connected as seen on screenshots : the gray and the black.

![IMG_1137](https://user-images.githubusercontent.com/38214885/92990232-03622400-f4db-11ea-99d3-aa0800bf2985.jpg)
![IMG_1138](https://user-images.githubusercontent.com/38214885/92990234-04935100-f4db-11ea-849c-7336ce116733.jpg)

And also to the TFT 35 screen.

![IMG_1144](https://user-images.githubusercontent.com/38214885/92990250-1e349880-f4db-11ea-88f8-768a187cf552.jpg)

I did not compile my own marlin, just using the one proposed by BTT here firmware.bin for the non bltouch support and firmware.bltouch.bin for bltouch support
https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/tree/master/firmware/V2.0

**Comment by pierremilcent** [comment]
> Do you have a second ribbon cable connected?
> Switch to Marlin mode.
> Does Marlin work?

Marlin does not work with this config : black screen on the TFT.

**Comment by pierremilcent** [comment]
I switched back the original display from creality using this BTT SKR 2.0 board and i also have a blank, in fact a blue, screen.

I tried again a firmware update with the "reset" button on the board, still no success.
As shown here https://1drv.ms/v/s!AjmZKEaxghvAiXysZgGJ6cqJw4kj

**Comment by radek8** [comment]
Then there is no problem with the display, but with the SKR board.
Reload the new FW

**Comment by blueeagle69** [comment]
I heartedly recommend knowing how to configure and compile your own firmware  :)

**Comment by pierremilcent** [comment]
I am managing this, i already build my own marlin 1.1.9 for creality 1.1.4 board with bltouch support using arduino 1.8.
I already installed vscode and platform.io for such purpose on this board with marlin 2.x

**Comment by pierremilcent** [comment]
This is the source of my problem : bltouch black and white wired not connected at the right place. See picture.
I need to understand what provide a connection to the others pins and additional feature if any.
![image](https://user-images.githubusercontent.com/38214885/92995049-12a79880-f500-11ea-8cb8-4c0c94ea7ea6.jpeg)
