### ISSUE TITLE
[Q] how does config.ini work?

### ISSUE THREAD

**Issue by ssombra** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1082]
I have some questions regarding the config.ini file: how does it work? should I set all parameters in the file and put it in the SD card root? or just those I want to change? Does the SD card needs to be there every time I turn the printer so the screen is updated with the config.ini settings? or the changes are permanent until I flash the screen again?

**Comment by oldman4U** [comment]
Hi

From the main page of this repository:

Configuration

The Firmware can be configured using the config.ini file from from one of these folders: Copy to SD Card root directory to update or Copy to SD Card root directory to update - Unified Menu Material theme

Editing configuration (config.ini) file

To edit the config.ini file follow the instruction here: Detailed Instructions here

Updating Firmware Configuration

To update the Firmware configuration:

Edit the settings in config.ini.
Copy the config.ini file to the root of the SD card. (The SD card capacity should be less than or equal to 8GB and formatted as FAT32)
Insert the SD card in the TFT's SD card slot and restart the TFT by pressing the reset buttion or disconnecting and connecting the power cable.
The TFT will update and store the configuraiton form config.ini file.


Hope this answers your question. Please close the ticket if so

Thank you

**Comment by ssombra** [comment]
Thanks. I didn't know the instructions were there. However, the main questions remain. I'll read them to see if I can find the answers.

**Comment by oldman4U** [comment]
The TFT will update and store the configuraiton form config.ini file.

**Comment by oldman4U** [comment]
Any questions left. Please let us know

**Comment by ssombra** [comment]
Thanks, I think I got it!
