### ISSUE TITLE
[FR] (3D Preview of the model you are printing:))

### ISSUE THREAD

**Issue by jascdk** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1085]
Hi 

This is only a question. Have it been thought about making the display show 3d previews of the model you are printing. I am thinking in the way that the Prusa Mini LCD is capable of.

All the best

Jacob

**Comment by radek8** [comment]
But it already works :-)

**Comment by radek8** [comment]
https://github.com/bigtreetech/Bigtree3DPlugin

@traffic-light Can you put it in the manual?
Thank you

**Comment by jascdk** [comment]
Ahh cool - thanks:D

**Comment by traffic-light** [comment]
> https://github.com/bigtreetech/Bigtree3DPlugin
> 
> @traffic-light Can you put it in the manual?
> Thank you

I will do that

**Comment by oldman4U** [comment]
@jascdk 

Please close this ticket once you do not need it anymore. 

Thank you

**Comment by traffic-light** [comment]
> https://github.com/bigtreetech/Bigtree3DPlugin
> 
> @traffic-light Can you put it in the manual?
> Thank you

Done. I've placed it in the FAQ
