### ISSUE TITLE
3D model (TFT43)

### ISSUE THREAD

**Issue by DeltaDesignRus** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1087]
Could you upload a 3D model of the screen? I want to model a case for it.

**Comment by bigtreetech** [comment]
Hello, Is it helpful [here](https://github.com/bigtreetech/BIGTREETECH-TouchScreenHardware/tree/master/BTT%20TFT43%20V3.0/3D)

**Comment by oldman4U** [comment]
Hi

Please close this ticket once you don't need it anymore. Thank you
