### ISSUE TITLE
[Q] Can the SD Card sort order be changed?

### ISSUE THREAD

**Issue by blueeagle69** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1088]
Hi.

When printing from the onboard SD card in Marlin mode, new gcode appears at the top of the list.
However when printing in touch mode, new gcode appears at the bottom of the list.
But be a bit of a pain when you have have a few files on your SD card.
Can this be changed?

Thanks.

**Comment by zonalimitatore** [comment]
No,its a marlin's setting.U need to mod the firmware under config_adv.h

**Comment by blueeagle69** [comment]
In Marlin mode, new Gcode appears at the top.
In TFT mode it appears at the bottom.
In Marlin I have #define SDCARD_RATHERRECENTFIRST enabled.
If it works fine in Marlin, changing this would only make things worse.

**Comment by zonalimitatore** [comment]
Let me check if in config.ini for TFT there is an option

**Comment by blueeagle69** [comment]
Cheers, but I didn't notice one when compiling.

**Comment by zonalimitatore** [comment]
Sorry. For now I haven't find somethink that tell me how not order the files

**Comment by blueeagle69** [comment]
Cheers for the help.
I'll see if I can get my head around it  👍

**Comment by zonalimitatore** [comment]
No problem dude

**Comment by oldman4U** [comment]
Hi. This is a duplicate of #601. 

Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by blueeagle69** [comment]
> Hi. This is a duplicate of #601.
> 
> Please help the community and close the ticket once you do not need it anymore. Thank you

Apologies, I missed that  one.
Will close now.

**Comment by oldman4U** [comment]
No problem at all. Thank you

👍🏻

blueeagle69 <notifications@github.com> schrieb am Fr. 25. Sep. 2020 um
16:31:
