### ISSUE TITLE
[Q] (my tft50 has some weird beeping)

### ISSUE THREAD

**Issue by Unkowntheifer** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1089]
my tft50 will display the home screen and during that it will beep quietly. but after that it will display a error message that reads "all high" or something like that and will start beeping very loudly.

**Comment by oldman4U** [comment]
Hi.

Which mainboard and firmware (mainboard and TFT) do you use?

Has this happen before or is this new after doing what?

**Comment by Unkowntheifer** [comment]
I just got the tft50 so literally brand new. I am also using a brand new bigtreetech gtr v1.0 board. but I have not changed the firmware on that yet. if this helps it also says "no printer attached" at the top of the display

**Comment by oldman4U** [comment]
OK, so the firmware is likely old.

Which cables do you have connected (pictures) and what is the baud rate defined in the menu of the TFT. If it is 11520 try 250000 and vice versa to see if the no printer error disappears.

**Comment by guruathwal** [comment]
The issue is with the mainboard and marlin firmware, most probably due to TMC drivers.

**Comment by oldman4U** [comment]
So when you switch to Marlin mode you will see TMY ERROR at the bottom of the screen

**Comment by oldman4U** [comment]
@Unkowntheifer 

Any news regarding the reported issue. Please let us know.

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
