### ISSUE TITLE
[BUG] Menu MachineSettings freezes

### ISSUE THREAD

**Issue by radek8** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1090]
After merging the last PR
When you open the MacineSettings menu, the display freezes

TFT35 E3 V3.0

**Comment by radek8** [comment]
My fault .
I was missing the tune_extruder.bmp icon on the card.
The menu does not freeze when the icon is added.

**Comment by blueeagle69** [comment]
Feel free to close  if you are sorted 😊

**Comment by oldman4U** [comment]
@blueeagle69 

This is my part😁

radek8. Please close the ticket. 

Now you can close it....

Thank you 🦅

**Comment by blueeagle69** [comment]
lol

**Comment by oldman4U** [comment]
👍🏻😁

blueeagle69 <notifications@github.com> schrieb am Mi. 16. Sep. 2020 um
23:14:

**Comment by radek8** [comment]
just have fun :-)

**Comment by oldman4U** [comment]
HOW!!!???

Now that you closed the ticket!!??

😃🤪😁
