### ISSUE TITLE
TFT error after update

### ISSUE THREAD

**Issue by Ski3d** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1094]
Compiled my self and also tryed the precompiled and with and without the icons. But can flash to an older version.
![119701833_3434917309899997_3456452497371664430_o](https://user-images.githubusercontent.com/61573573/93421425-517e7b00-f87f-11ea-85ec-d81c9c95e213.jpg)

**Comment by oldman4U** [comment]
Have you tried the standard TFT35 bmp's?

**Comment by oldman4U** [comment]
This is a new feature which seems to work. 

You updated the firmware and the TFT folder but not the config.ini. 

@traffic-light something for you to add!?

**Comment by traffic-light** [comment]
> This is a new feature which seems to work.
> 
> You updated the firmware and the TFT folder but not the config.ini.
> 
> @traffic-light something for you to add!?

That could be. but for now I think the message is clear enough...

**Comment by Ski3d** [comment]
Ok then the github instructions is little dated,  i see further down in the instructions is talks about the config.ini. but before i could edit in PIO then compile and both the .bin and the icons on an sd and be good to go. But now you need 3 files total. Thanks


![Screenshot_20200917-145733_Samsung Internet](https://user-images.githubusercontent.com/61573573/93515057-ffc50780-f8f5-11ea-96f4-6805d4c4d35f.jpg)

**Comment by oldman4U** [comment]
Hi

You are right and i would do exactly the same thing you did. 

Try to find a way to update the Readme. Never did that before. 

Finally the great thing is that it is enough to edit the config.ini. No recompile is needed. Try it.

**Comment by Ski3d** [comment]
They basically did this so the average joe dont need to download PIO , find the config, compile, then find the file and then move to the sd. But this needs documentation so all the people that have these screens before the update, will have the same problem. Yes i know this is not release version but im not the only one that ran into this problem. I did the same way i aways have.

**Comment by oldman4U** [comment]
Many things would need documentation...
