### ISSUE TITLE
Misleading manual

### ISSUE THREAD

**Issue by oldman4U** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1095]
The current manual does not include the config.ini. Who can change this. Please. 

Copy both the BIGTREE_TFT*_V*.*.*.bin and TFT* folder to the root of a blank SD card that is <8GB and formatted as FAT32:

image

Place SD card with BIGTREE_TFT*_V*.*.*.bin & TFT* folder into the TFT's SD card reader and power cycle your printer to start the update process.

This should be after the config.ini part. 

Copy the config.ini, the BIGTREE_TFT*_V*.*.*.bin and the TFT* folder to the root of a blank SD card that is <8GB and formatted as FAT32:

HERE WE WOULD ALSO NEED A NEW SCREENSHOT. 

Place SD card with the config.ini, the BIGTREE_TFT*_V*.*.*.bin and the TFT* folder into the TFT's SD card reader and power cycle your printer to start the update process.

Thank you

**Comment by Ski3d** [comment]
Thank you!!! I completely agree

**Comment by Ski3d** [comment]
#1094

**Comment by oldman4U** [comment]
👍🏻

Can someone who knows how the Read Me can be changed help us. Please. 

If you explain to me how this can be done i would do it. 

Thank you

**Comment by traffic-light** [comment]
If I find some time I will take a look at it.

**Comment by oldman4U** [comment]
Hi my friend.

I will try it by myself. My first PR...

Hope the original owner likes it;-)

![Screenshot 2020-09-18 at 21 07 47](https://user-images.githubusercontent.com/54359396/93636170-bfe44a00-f9f3-11ea-881f-202b3bb587a1.png)

**Comment by oldman4U** [comment]
It's me again.

Likely I did something wrong. Using GitHub Desktop for Mac, I changed the Readme and pushed a PR, but it does not show up here on GitHub.

Can someone help me please

Thank you

![Screenshot 2020-09-18 at 22 09 51](https://user-images.githubusercontent.com/54359396/93641145-16ee1d00-f9fc-11ea-8db4-142306e957c4.png)

**Comment by traffic-light** [comment]
Good job oldman4u

**Comment by oldman4U** [comment]
Thank you

First PR - DONE

😎

Peter van Weeterloo <notifications@github.com> schrieb am Fr. 18. Sep. 2020
um 23:12:
