### ISSUE TITLE
[Q]  How to setup delta auto calibration button?

### ISSUE THREAD

**Issue by karabas2011** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1096]
Cannot find button for delta autocalibration (marlin 2.0) on TFT35
What I missed?

**Comment by traffic-light** [comment]
That's because it's not implemented (yet).
You can use the terminal on the TFT screen to execute the G33 command.

If this solved it for now you can close the ticker.
When you want this as a feature create a feature request and close this ticket ;-)

**Comment by oldman4U** [comment]
..... or make a custom gCode command

and close the ticket

@traffic-light - you are copying me .....

;-)

@karabas2011 do you know how to use the Terminal or how to generate custom gCode commands?

Please let us know

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Thank you
