### ISSUE TITLE
[BUG] (short description)

### ISSUE THREAD

**Issue by nictronik99** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1097]
### Description

When the printer starts up, an error is displayed stating that ABL could not be activated. After doing the ABL manually, you can activate it without errors. Is there a way to stop that error appearing when the printer starts up?

### Hardware Variant

BTT TFT35 V3.0 

### TFT Firmware Version & Main Board Firmware details

TFT fw version: 3.0.26 last version 
Marlin version: 2.0.6.1

### Additional Information
* Include a ZIP file containing your `Configuration.h` or use [Pastebin](https://pastebin.com/) and paste a link in this issue.
* Provide pictures or links to videos that clearly demonstrate the issue.
[Video & Fw versions](https://www.facebook.com/groups/505736576548648/permalink/1041069513015349/)

**Comment by traffic-light** [comment]
Did you do a abl from the menu and set the fade height?

**Comment by oldman4U** [comment]
Could you please change the headline of this ticket. Thank you

**Comment by traffic-light** [comment]
Is it solved @nictronik99 ?

If it's solved please close the ticket.

**Comment by nictronik99** [comment]
yes, you had to store the probing data in the eeprom, i'll close It now

**Comment by oldman4U** [comment]
👍🏻
