### ISSUE TITLE
Support 500000 baudrate

### ISSUE THREAD

**Issue by cepxuo** [bigtreetech/BIGTREETECH-TouchScreenFirmware#11]
Does TFT35 hardware support higher baudrate? My marlin settings set up to 500000 baudrate.

**Comment by carl1961** [comment]
you can try and add it to the menu. 
![baudrate500000](https://user-images.githubusercontent.com/3056821/65476553-f4591080-de48-11e9-9082-3811b865ed17.PNG)
![baudrate500000-2](https://user-images.githubusercontent.com/3056821/65476554-f4591080-de48-11e9-8509-8222caa56501.PNG)

**Comment by dineshvyas** [comment]
yes it does. mine is 1000000

**Comment by mikefromups** [comment]
I found where I can change the default label "LCD12864 Simulator" in Configuration.h

#define ST7920_BANNER_TEXT "LCD12864 Simulator"
