### ISSUE TITLE
[FR] (standard deviation on repeatability test )

### ISSUE THREAD

**Issue by nictronik99** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1102]
**Is your feature request related to a problem? Please describe.**

it would be nice to also be able to enter the standard deviation along with the other data when the test repeatability is performed. 

![IMG_20200918_182458.jpg](https://user-images.githubusercontent.com/62067513/93621998-af74a500-f9dc-11ea-95f1-6ae8f0d45221.jpg)

**Comment by traffic-light** [comment]
That would be indeed great. The only problem is that marlin doesn't report the standard deviation of the probes... 

Then someone have to make a custom repeatability test...

**Comment by nictronik99** [comment]
![IMG_20200918_183754.jpg](https://user-images.githubusercontent.com/62067513/93622833-16df2480-f9de-11ea-83d3-81e3a40753c4.jpg)
This is Marlin's M48 command
...

**Comment by traffic-light** [comment]
Yeah I know. Forgot about it. Someone should catch that part of the message and print it ;-)

It's a new message. So it should be combined with the previous message

**Comment by nictronik99** [comment]
if I knew where to put my hands I would

**Comment by ssombra** [comment]
Is there a M48 option in the BLTouch menu?

**Comment by nictronik99** [comment]
> Is there a M48 option in the BLTouch menu? 

there is the repeat button that does what the M48 command does ... only in the window that comes out at the end, the standard deviation is missing from the data ...

**Comment by ssombra** [comment]
> > Is there a M48 option in the BLTouch menu? 
> 
> there is the repeat button that does what the M48 command does ... only in the window that comes out at the end, the standard deviation is missing from the data ...

Oh, I didn't know what that button was for! Thanks

**Comment by oldman4U** [comment]
Hello nictronik99.

Could you please be so kind and close this ticket. Your feature request is covered in the pinned Feature Request ticket #1177 

Thank you

**Comment by oldman4U** [comment]
Thank you

**Comment by kisslorand** [comment]
Check PR #1484.
