### ISSUE TITLE
[BUG] Interrupt printing

### ISSUE THREAD

**Issue by radek8** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1106]
In the last week, printing ended in error 3 times.
It is annoying when this happens after 5 hours of printing.
I print from SD card in TFT35 E3 v3.0
I have compiled the latest FW to TFT display
and 14 days old FW Marlin bugfix 2.0.
I'm using a serial port speed of 250000.
Where can the problem be?

It looks like a loss of communication over the serial port

![IMG_20200919_071052_resized_20200919_042021567](https://user-images.githubusercontent.com/46979052/93669560-59176d00-fa95-11ea-984c-921d3e90c6a7.jpg)
![IMG_20200919_071126_resized_20200919_042021743](https://user-images.githubusercontent.com/46979052/93669562-5ae13080-fa95-11ea-9be1-4f4794c5173a.jpg)

**Comment by oldman4U** [comment]
Hi. 

Try to change the order in which you defined the serial ports. In case you use an SKR E3 DIP you can also have such issues when using the 512k mode. But finally you are a much more experienced user - so it is a bit strange for me if I try to help you🥺

**Comment by radek8** [comment]
This problem does not happen every time you print, but only sometimes.

**Comment by oldman4U** [comment]
And you expect a firmware issue to be the reason for this. Right?

**Comment by oldman4U** [comment]
BTW. Thank you for trying to help me with those two hopeless tickets. Not sure where such unfriendly people comes from...

**Comment by radek8** [comment]
I suspect serial communication errors, if it happens again, I will reduce the speed of the COM port

**Comment by oldman4U** [comment]
I use 115200 since day one without this kind of problems. Hope you find the problem soon.

**Comment by radek8** [comment]
So it seems that the problem is caused by unwanted communication of the PC with the printer via WiFi. Or I'm the first to have an antivirus in the printer :-)))

![IMG_20200925_162919_resized_20200925_081915687](https://user-images.githubusercontent.com/46979052/94302733-fcbcbd80-ff6c-11ea-8218-4bc4884f8ec4.jpg)
![IMG_20200925_162846_resized_20200925_081915255](https://user-images.githubusercontent.com/46979052/94302758-0514f880-ff6d-11ea-9b43-9fecc7de65ba.jpg)
![IMG_20200925_162857_resized_20200925_081915466](https://user-images.githubusercontent.com/46979052/94302768-09d9ac80-ff6d-11ea-8b56-dadf61e8a694.jpg)
![IMG_20200925_162815_resized_20200925_081915098](https://user-images.githubusercontent.com/46979052/94302782-12ca7e00-ff6d-11ea-8fa0-27b5fd27d075.jpg)

**Comment by oldman4U** [comment]
What is antivirus?

Sorry but i am using macOS...

😊

**Comment by oldman4U** [comment]
And what was the solution for the problem!!??

Radek <notifications@github.com> schrieb am Do. 8. Okt. 2020 um 22:31:
