### ISSUE TITLE
[FR] Correct report from marlin firmware\skr board for M117 messages via terminal etc

### ISSUE THREAD

**Issue by radfordwill** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1125]
**Is your feature request related to a problem? Please describe.**
Marlin firmware reports m117 messages to the lcd in Ender 3. I am assuming it is that way with most printer\lcd combos. The firmware for the tft35 v2.0, at least from the BTT SKR DIP v1.1 in my case, does not process M117 messages from anywhere but internally sent messages.

**Describe the solution you'd like**
I read python and some c++ but I can't find anywhere to start adding support for this problem. Can this be added? Octoprint plugins like [Display Layer Progress](https://plugins.octoprint.org/plugins/DisplayLayerProgress/) would be an asset to this lcd's functionality. Any Ideas?

**Additional context**
[M117 - Set LCD Message](https://marlinfw.org/docs/gcode/M117.html)

**Comment by oldman4U** [comment]
Hi.

Searching for M117 gives me the following results:
![Screenshot 2020-09-25 at 21 15 36](https://user-images.githubusercontent.com/54359396/94307059-57a5e300-ff74-11ea-82c8-0611eb830151.png)

So there are already several tickets related to this topic, maybe you want to join one and close this ticket after that.

Thank you

**Comment by radek8** [comment]
I don't know what news you are missing.
Unwanted M117 messages can be suppressed in the parseACK.c file
Search there if you want to display a message.

**Comment by radfordwill** [comment]
> Hi.
> 
> Searching for M117 gives me the following results:
> ![Screenshot 2020-09-25 at 21 15 36](https://user-images.githubusercontent.com/54359396/94307059-57a5e300-ff74-11ea-82c8-0611eb830151.png)
> 
> So there are already several tickets related to this topic, maybe you want to join one and close this ticket after that.
> 
> Thank you

Reading through those now. I've read several and they don't cover it. It is not a bug.  I am asking for a feature added.

**Comment by radfordwill** [comment]
> I don't know what news you are missing.
> Unwanted M117 messages can be suppressed in the parseACK.c file
> Search there if you want to display a message.

What port on the tft are you using? 1 or 3?

**Comment by radek8** [comment]
![image](https://user-images.githubusercontent.com/46979052/94336260-f4529a00-ffe1-11ea-8334-5aebc6469942.png)

**Comment by radfordwill** [comment]
> I do not understand the question
> 
> ![image](https://user-images.githubusercontent.com/46979052/94336260-f4529a00-ffe1-11ea-8334-5aebc6469942.png)

I followed this to the letter with the V2.0 of the TFT35. It does not appear to have the same options the 3.0 board has without the EXP3 port receiving the commands maybe.  In ant case, probably an old board that is not going to work even if they add it to the newer boards. Closed request for TFT35 V2.0. Out of date board Bigtree should quit selling. 

@radek8 - Thanks for the pointers and directions in the [other thread](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/1050)

**Comment by radek8** [comment]
That's right TFT35 V2.0 is a failed model
