### ISSUE TITLE
[BUG] Tuning menu = screen freeze

### ISSUE THREAD

**Issue by zonalimitatore** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1133]
In TFT mode with last firmw,with tft24 screen.
When I click on tuning menu,all freeze,and I'm constrict to reset the printer.

**Comment by oldman4U** [comment]
Pre or self compiled firmware?

**Comment by zonalimitatore** [comment]
Pre,because I've errors with autobuild

**Comment by oldman4U** [comment]
The precompiled version seems to have serious issues. So I would strongly recommend to compile your own firmware and see if this solves the problem.

**Comment by zonalimitatore** [comment]
Allright. Now I try to recompile it,hoping errors leave!
Let you know if the problem still

**Comment by traffic-light** [comment]
Please post the error's here when it go's wrong ;-)

**Comment by oldman4U** [comment]
And this is from the document of our traffic-light.

Q: Unexpected freezes when entering a menu after newly compiled firmware

A: Did you also update the config.ini on you're screen after the update? For example the freezing in preheat menu is caused by using a old config.ini.
Please try if this work. When it didn't work place an issue and tell that you did update config.ini ;-)

**Comment by zonalimitatore** [comment]
Well. I've compile the firmware,and the config too.
But the problem still... When I press tuning screen freeze with a little white point. I post the photo soon

**Comment by oldman4U** [comment]
Which firmware version? Check the Info of the screen.

**Comment by zonalimitatore** [comment]
![Uploading IMG_20200927_200121.jpg…]()
[Uploading VID_20200927_200044.mp4…]()

**Comment by radek8** [comment]
When you uploaded the FW to the display, the icons were also recorded. Did you miss one icon?

**Comment by radek8** [comment]
do you miss the Tune_extruder.bmp icon on the SD card?

**Comment by zonalimitatore** [comment]
i check

**Comment by zonalimitatore** [comment]
Thank you so much....Solved

**Comment by oldman4U** [comment]
And the winner is... RADEK8!!

So the missing icon caused this!!?? Have you ignored the warning during updating the firmware?

**Comment by zonalimitatore** [comment]
Honestly, I didn't care (idiot)

**Comment by oldman4U** [comment]
We all learned it step by step.

😎

zonalimitatore <notifications@github.com> schrieb am So. 27. Sep. 2020 um
22:38:

**Comment by zonalimitatore** [comment]
Yeah!!!Thanks at all
