### ISSUE TITLE
[FR] Add ability to get to home screen with 1 click from any screen please

### ISSUE THREAD

**Issue by krudoy** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1137]
Can you please add ability to get to home screen with a single click from any screen. It is really boring to click multiple time 'Back' button

**Comment by traffic-light** [comment]
There is not really space for a button that returns you to home.

What, maybe, could be done is pressing a button for 3 sec. But then, when you press for 5sec, the screen goes into mode selection

**Comment by oldman4U** [comment]
traffic-light. Wouldn't it be good to collect all those FR in a single ticket like your ReadMe FIRST...

**Comment by oldman4U** [comment]
@krudoy 

I agree with you, but the underlying problem here is the depth of menu items. Currently some functions are 4 (or if you also count the function itself - 5) clicks away. If this could be reduced to 3 and maybe the most important once to 2 clicks - your FR would mean 1 or 2 clicks to the home button. I have a concept for reducing the clicks needed to reach all menu items, hope this will be available once.

**Comment by traffic-light** [comment]
> traffic-light. Wouldn't it be good to collect all those FR in a single ticket like your ReadMe FIRST...

No not really (atleast, that's my opinion).
You can search for functionrequest with the label enhancement ;-)



> @krudoy
> 
> I agree with you, but the underlying problem here is the depth of menu items. Currently some functions are 4 (or if you also count the function itself - 5) clicks away. If this could be reduced to 3 and maybe the most important once to 2 clicks - your FR would mean 1 or 2 clicks to the home button. I have a concept for reducing the clicks needed to reach all menu items, hope this will be available once.

Sometimes it's needed to have a multiple layers of menu's. There are only 8 buttons max per page.

The only easy way i can think of is pressing the return button for a longer time....

(by the way, marlin is also without a return to home button ;-) )

**Comment by krudoy** [comment]
> (by the way, marlin is also without a return to home button ;-) )

That's why we like to have a touchscreen with different functionality. And Marlin has an option to get to Info screen after some period of inactivity

I like idea of long or double click. I also consider that 5sec long click to switch between modes can be fully replaced by long click on a wheel.

**Comment by traffic-light** [comment]
I don't agree with long clicking on the wheel. You shouldn't use the encoder too much when in touchmode.

Go back to the homescreen after x seconds as an setting could be possible ;-)

You're right. It's a diffrent thing ;-)

**Comment by oldman4U** [comment]
Now we are 3 persons with 3 opinions. Add 2 persons more for a total of 6 or seven opinions 😁

**Comment by traffic-light** [comment]
And add 3 more on that and it's infinity 😝

**Comment by oldman4U** [comment]
Exactly

😎

Peter van Weeterloo <notifications@github.com> schrieb am Mo. 28. Sep. 2020
um 23:13:

**Comment by cbaugher** [comment]
> 
> Sometimes it's needed to have a multiple layers of menu's. There are only 8 buttons max per page.
> 
> The only easy way i can think of is pressing the return button for a longer time....

Why is there an 8 button maximum per page?

An auto-return to main menu after timeout would ok if adding another button is not possible.


C|

**Comment by makmillion** [comment]
Auto-return to main menu after x- seconds of inactivity sounds like a fantastic idea.

**Comment by oldman4U** [comment]
#296 covers this already.

**Comment by oldman4U** [comment]
Hello krudoy.

Could you please be so kind and close this ticket. Your feature request is covered in the pinned Feature Request ticket #1177 

Thank you

**Comment by kisslorand** [comment]
A press on the title bar would be ideal but that will remove the notification menu that is assigned to title bar pressing.
What if pressing the title bar goes to notification menu only in the home screen?
Is notification so important that it should be available from any menu?

**Comment by oldman4U** [comment]
Before the ability to see the notification by pressing the title bar has been added, the last notifications received has only been visible in the little echo window of the main screen.

So I could imagine that using the title bar to home could work nicely!

**Comment by kisslorand** [comment]
@krudoy 
Check PR #1531.
