### ISSUE TITLE
Did I cook my TFT 3.5 E3 V3.0?

### ISSUE THREAD

**Issue by Quickset45** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1141]
I have an ender 3 pro.
I am using the SKR-Mini E3 V2.0 board and the TFT 3.5 E3 V3.0 screen.
I've updated the board firmware using the ender .bin file. -no problem
I started to flash the TFT screen but neglected to included the TFT or config.ini files on the first try. Shortly, the error screen came up "found outdated data: fonts, config.  Please insert the SD card with the files and press restart button"
I was being called for dinner and leaving the display it in its error state, I powered down the unit. <<<<<
I came back later, and properly included all three files, but now it always stops after the first file with the same error message.
even after I insert the SD card with the correct files and hit the reset button.

I tried all three files from both the root directory to update, and the root directory to update - Unified Menu Material theme.
neither set of files will budge the error message. In fact when I power the unit with no card at all, I get the same error message.
I've reset the board a dozen times,.
Here are the files/folder in the root director of the SD card:
BIGTREE_TFT35_V3.0_E3.26.x.bin
TFT35 (folder)
config.ini

any help would be appreciated! I'm going to leave it unplugged for a while.

**Comment by radek8** [comment]
Does the TFT folder contain songs and icons, or has it just uploaded an empty folder?

**Comment by oldman4U** [comment]
The TFT does not like songs from Michael Jackson😎

**Comment by radek8** [comment]
> The TFT does not like songs from Michael Jackson😎

I do ;-)

**Comment by Thijsvanzwam** [comment]
format the SD card and then try again, that worked for me once.

**Comment by oldman4U** [comment]
> > The TFT does not like songs from Michael Jackson😎
> 
> 
> 
> I like him ;-)

Me too. 😎

**Comment by Quickset45** [comment]
Thanks for all the comments... you are all Number Ones!
so... I re-formatted my 128 gig SD card Fat... (3 hrs later)
I  re-installed the 3 components... same error message.
yes radek 8, I did check the folder on the SD card to verify that the fonts and .bmp files were in the folders.
So, I have another screen on the way,  and an 8 GB SD card.

**Comment by radek8** [comment]
FAT or FAT33?

**Comment by radek8** [comment]
Does TFT SD card support 128G?

**Comment by oldman4U** [comment]
For firmware update you have to use <8GB SD card. Use the card which came with the hardware.

**Comment by Quickset45** [comment]
Windows 10 format gave me the option of Fat x, or NTFS.
No card came with my display,  just cables.
The micro SD card that came with my SKR mini board won't fit on the display, SD only.
will 8G be ok?

**Comment by radek8** [comment]
8G is fine

**Comment by radek8** [comment]
> Žádné ocenění za odkaz na album Michaela Jacksona „číslo jedna“? :100:

**Comment by Quickset45** [comment]
8GB did the trick!
Now to tackle the issue where LCD12864 is all I see when trying to go to Marlin mode.

**Comment by radek8** [comment]
Do you have a connected display and a SKR 10pin connector?
The display connected to the EXP3 connector?

**Comment by oldman4U** [comment]
Q: Switching to Marlin mode is giving me a empty screen

A: Check your ribbon cable connections to the TFT screen.
When this problem doesn’t occur when first booting in Marlin mode, you should try rotating the encoder wheel. This way Marlin is forced to redraw the screen

Using an "E3" based mainboard, make sure that ONLY the "CR10_STOCKDISPLAY" is activated in Configuration.h.
For all other mainboards, ONLY the "REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER" has to be activated.

**Comment by Quickset45** [comment]
all is now working well.  I had the 10pin cable connected to EXP2 instead of EXP3 on my SKR mini board. 
Many thanks.
