### ISSUE TITLE
[BUG] (update the software on my tft35 screen)

### ISSUE THREAD

**Issue by rasmus-wallin83** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1146]
I got this error when I tried to update the software on my tft35 screen

I'm using the latest update

![DSC_0159](https://user-images.githubusercontent.com/72239765/94883683-8f78c300-046b-11eb-9a79-caef09e4dd1b.JPG)

### Steps to reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior**

**Actual behavior**

### Additional Information
* Include a ZIP file containing your `Configuration.h` or use [Pastebin](https://pastebin.com/) and paste a link in this issue.
* Provide pictures or links to videos that clearly demonstrate the issue.

**Comment by oldman4U** [comment]
Please read the manual on the front page and update the title to something meaningful.

**Comment by BlackDragon2020** [comment]
Take the time to post correctly, but close the ticket after your solution is found.

You need to copy the config.ini to the sd card.
