### ISSUE TITLE
[Q] Switch to Marlin/12864/Emulation mode

### ISSUE THREAD

**Issue by shuffleznl** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1148]
Hi there! 
**TL;DR:** how can I switch to Marlin/12864/Emulation mode w/o touchscreen?
Is there a SW/FW option or short-circuit (like with bootloader update) shortcut to get this?

**Background:** I managed to get my GTR v1.0 working on CoreXY (much less documentation vs SKR :)).
Sadly whilst fitting a printed case for TFT35 E3 the touchscreen broke.
I still have image in BTT Touch mode, and the right third of screen (near the flex cable) still works (I can get into Print menu).

Thanks!

**Comment by zonalimitatore** [comment]
Keep press knob,until select menu
Or load a config.ini file, where indicate use touch mode (but if your touch not work,im not sure you can do a lot)

**Comment by shuffleznl** [comment]
Thanks @zonalimitatore :) I know **how** to switch if the touchscreen worked :)
Keeping the button pressed shows the option for _Marlin Mode_ but because touchscreen area doesn't work I can't actually select it :) The area to select _Touch Mode_ does still work. I'll look into the config-file!

**Comment by zonalimitatore** [comment]
You can choose with knob?
If no,no way,need to edit the config file

**Comment by oldman4U** [comment]
Upload new config.ini withe zhe default mode set.

**Comment by shuffleznl** [comment]
> You can choose with knob?
> If no,no way,need to edit the config file

Pressing knob for 3 sec shows the two options yes, but rotating the knob doesnt work there.

**Comment by shuffleznl** [comment]
> Upload new config.ini withe zhe default mode set.

Have tried this, but now keep getting Found Outdated data, Insert SD with required files and reset notification.
I have cloned the entire git-folder, so all files are actual. Checking now with default config.ini.
