### ISSUE TITLE
TFT35 v3: EEPROM icon not loading

### ISSUE THREAD

**Issue by Hukuma1** [bigtreetech/BIGTREETECH-TouchScreenFirmware#115]
Using the unified theme (which is great btw!) and the save.bmp is not showing up. Probably needs to be EEPROM_Save.bmp?

**Comment by thisiskeithb** [comment]
Try renaming it to EEPROMSave.bmp and re-loading it via SD card to see if it updates.

**Comment by Hukuma1** [comment]
That solved it., thanks! :) Should I close issue?

**Comment by thisiskeithb** [comment]
> Should I close issue?

It's still a "bug", so leave it open for now. @guruathwal: FYI

**Comment by guruathwal** [comment]
> > Should I close issue?```

> 
> It's still a "bug", so leave it open for now. @guruathwal: FYI/FYA

```
Pushed PR for the same. Please check and close the issue.
