### ISSUE TITLE
Include G34 Auto-Alignment to Movement/BedLevel UI

### ISSUE THREAD

**Issue by R0bin3D** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1150]
Please include the command G34 into the bedlevel menu for better user-experience for user with more than one Z-axis.

**Comment by ETE-Design** [comment]
Would like this option :-) Also G34 Bed Tramming would be great as an option...

**Comment by radek8** [comment]
What's your idea?

**Comment by R0bin3D** [comment]
Extra buttons in the bedlevel-menu-point for G34 Auto-Align und G35 Assist-Tramm. That makes it easyer to use. I missed the buttons and must use the cute little terminal on the display atm.

**Comment by radek8** [comment]
G34 is started with some parameter, or are the parameters stored in eeprom and just run the G34 command without parameters?
  The parameters could then be edited in the Printer Parameters Menu

**Comment by radek8** [comment]
Can you save the output of the M503 and M422 commands from a printer on which you have two stepper motors on the Z axis?

**Comment by oldman4U** [comment]
Hello R0bin3D.

Could you please be so kind and close this ticket. Your feature request is covered in the pinned Feature Request ticket #1177 

Thank you

**Comment by radek8** [comment]
oldman, Why?

**Comment by oldman4U** [comment]
Radek8. 

Read the pinned ticket to see why. One place which covers all.

**Comment by radek8** [comment]
@R0bin3D Can I ask for an answer to my question? Thank you

**Comment by radek8** [comment]
> Radek8.
> 
> Read the pinned ticket to see why. One place which covers all.

That's why he had to stay open

**Comment by oldman4U** [comment]
Typo. Ticket is #1170

SORRY

**Comment by oldman4U** [comment]
You can and should still use the ticket. Even it is closed. So we get a single place with all FRs, a usable ticket system and a place where people can discuss about the solution. 

Alternativ we have a ticket system with feature requests on page 2-5 noone reads, duplicate requests and several developers working on the same issue without knowing.

**Comment by Chad541121** [comment]
I would like this menu feature also.

**Comment by Dtcreation** [comment]
I would like this menu feature too

**Comment by BlackDragon2020** [comment]
I was thinking about this, but in a different way. Some people only have one stepper driver but 2 motors. 

What if the tft preformed the g34 and could use some type of relay or multiplex setup that would ground out one of the stepper motors so the other could be adjusted.

I was thinking go over the gcode to see how it works, come up with the parts list and wire gauges so they work for correct amps. I think it would be a great feature and an awesome addon kit BTT could end up selling.

**Comment by radek8** [comment]
This isn't real. The solution is two pulleys and a strap.

**Comment by radek8** [comment]
Such a connection would be too complicated and difficult to operate from the display. The solution of two motors on one driver is synchronization using a toothed belt

![image](https://user-images.githubusercontent.com/46979052/106376827-fdd97d80-6398-11eb-885d-62965e4c2e9d.png)

**Comment by digant73** [comment]
@oldman4u this feature was added. G34 support is configurable in config.ini. Once enabled, the g34 feature is available in Bed Leveling two Layer menu. So this FR can be removed from the list
