### ISSUE TITLE
[Q] How to flash directly without SD card?

### ISSUE THREAD

**Issue by flolas** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1153]
**Your question or details you need. Please describe.**
After a upgrade following instructions from here, the "Menu" button show white screen with glitches and SD Card is not working, then I cant re-upgrade the tft... ¿What can I do for fixing the issue? 
Thanks

**specify the device variant related to your question.**

TFT43 V3 flashed with latest .bin previously compiled from github repository

**Comment by oldman4U** [comment]
Follow exactly the Readme and do not ignore errors and warnings during update. This will solve the problem

**Comment by oldman4U** [comment]
No upgrade without SD card - just to answer your question. 😎

**Comment by flolas** [comment]
@oldman4U I followed the readme and did not ignore errors.
The problem was the SD card provided by SKR board. Really bad quality
