### ISSUE TITLE
TFT35 V2.0 wifi support

### ISSUE THREAD

**Issue by ssombra** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1156]
Hi. I have the TFT35 V2.0 and I wonder if currently it is possible to add a wifi module to it (as I use the SKR 1.3 board I cant add the module there). When I got it several months ago the support was not implemented. Now I did a search on the issues and didn't find specific new information on this. I understand that this screen doesn't have the socket for the module but, if the support in the firmware is there, it should be an easy solder. Anyone could point me to the correct direction?

**Comment by Slimgig** [comment]
The screen does have a socket for the wifi module there are plenty of videos on YouTube for it I have the wifi module but have not hooked it up yet just got it the other day

**Comment by Slimgig** [comment]
But I have seen videos for it too that I am going to go off of

**Comment by ssombra** [comment]
> The screen does have a socket for the wifi module there are plenty of videos on YouTube for it I have the wifi module but have not hooked it up yet just got it the other day

The V2.0? 
I have mine in a case right now, but I think there is not one in my screen, just the space and the pins to solder one like in the manual:

![image](https://user-images.githubusercontent.com/42944253/95224266-13121700-07c0-11eb-9a29-e97401ecc5dd.jpeg)

**Comment by radek8** [comment]
You have 3 options
1. You can solder the connector to the WIFI position
2. use the USART3 connector
3. connect WIFI to SKR1.3

https://www.youtube.com/watch?v=nEhDPCGki80

![image](https://user-images.githubusercontent.com/46979052/95231540-930da080-0803-11eb-8f62-1eb7d3f71ba3.png)

**Comment by Slimgig** [comment]
I have the 3.0 sorry about that

**Comment by ssombra** [comment]
> You have 3 options
> 
> 1. You can solder the connector to the WIFI position
> 2. use the USART3 connector
> 3. connect WIFI to SKR1.3
> 
> https://www.youtube.com/watch?v=nEhDPCGki80
> 
> ![image](https://user-images.githubusercontent.com/46979052/95231540-930da080-0803-11eb-8f62-1eb7d3f71ba3.png)

Thank you very much for that. If I buy the module from BTT (ESP01S) I guess the easiest way is option #1. How is the wiring for option #2? I only see 3 pins while the modules usually have 8.

**Comment by oldman4U** [comment]
What kund of functionality would you expect from the WIFI connection?

**Comment by radek8** [comment]
connection for flash is here
![Zapojení pro flash2](https://user-images.githubusercontent.com/46979052/95256908-c6602780-0823-11eb-8dc6-69ade0ee30c5.PNG)

**Comment by radek8** [comment]
![Uploading image.png…]()

**Comment by ssombra** [comment]
> What kind of functionality would you expect from the WIFI connection?

Basic controls (temperature, movement, a terminal, print files from the board SD). The modules are cheap so why not adding it to the printer.

**Comment by ssombra** [comment]
> connection for flash is here
> ![Zapojení pro flash2](https://user-images.githubusercontent.com/46979052/95256908-c6602780-0823-11eb-8dc6-69ade0ee30c5.PNG)

Thanks for all the information Radek8! I will definitely take a look into it.

**Comment by oldman4U** [comment]
> > What kind of functionality would you expect from the WIFI connection?
> 
> 
> 
> Basic controls (temperature, movement, a terminal, print files from the board SD). The modules are cheap so why not adding it to the printer.

The web interface is ok and offers most functions Pronterface has. So it should do what you want. You have no SKR PRO, right!?

**Comment by ssombra** [comment]
> > > What kind of functionality would you expect from the WIFI connection?
> > 
> > 
> > Basic controls (temperature, movement, a terminal, print files from the board SD). The modules are cheap so why not adding it to the printer.
> 
> The web interface is ok and offers most functions Pronterface has. So it should do what you want. You have no SKR PRO, right!?

No, SKR 1.3. I already ordered the module from BTT along with a writer.

**Comment by oldman4U** [comment]
Perfect. 

Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by ssombra** [comment]
Sure, thanks everyone for the support.

**Comment by oldman4U** [comment]
Reopen it if needed.

Thank you and happy printing

ssombra <notifications@github.com> schrieb am Mi. 7. Okt. 2020 um 22:50:

**Comment by SerjPr** [comment]
I just soldered the WIFI module to the contacts. After pre-flashing it. Everything works great.
![20201008_233344](https://user-images.githubusercontent.com/43146313/95494403-b1200000-09bf-11eb-9d17-7a54ed76f959.jpg)

**Comment by SerjPr** [comment]
ESP07, ESP12E, ESP12F, без проблем подходят. Только под них надо подложить прокладку. Чтоб плата не касалась контактов.

**Comment by oldman4U** [comment]
Congratulations. Looks great!

**Comment by ssombra** [comment]
If I am not wrong, the module that BTT sells has only 8 pins, right? This seems to have 16.

**Comment by radek8** [comment]
the car has 4 wheels and a motorcycle 2, and you will drive on both :-)

**Comment by SerjPr** [comment]
> If I am not wrong, the module that BTT sells has only 8 pins, right? This seems to have 16.

Only "TX, RX, VSS, GND, Ch_PD" is used. You can only solder them. Well, and the resistor on GPIO 15, or just short-circuit to the case.

**Comment by SerjPr** [comment]
But there is a flaw in my way. If you need to reflash it, then the module needs to be soldered. Or at least unsolder "RX ,TX". And they will be soldered to them for firmware

**Comment by ssombra** [comment]
Well, I received the ESP module from BTT and it was way more easy than I imagined. On the one hand, it turns out that my TFT (TFT53 V2.0) did have the socket already soldered, I guess it is a newer version that the one shown in the manual. On the other hand, the ESP modules sold by BTT are already flashed with ESP3D, so it was pretty much a plug and play operation. Thanks everyone for the support.
