### ISSUE TITLE
TMC 2208 UART FYSTEC

### ISSUE THREAD

**Issue by IIIxpHunterIII** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1162]
The question I've got is how do you enable UART on said driver in Marlin?

It reports no UART capable drivers on M119 even though i Put the Jumpers in like BIGTREETECH sais.
[Marlin_Configuration.h.txt](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5351021/Marlin_Configuration.h.txt)

Patform:
SKR1.4
FYSTEC 2208 V1.2

**Comment by traffic-light** [comment]
You know that this has nothing to do with the tft firmware?

**Comment by radek8** [comment]
you need to measure the jumper correctly on both the SKR and the TMC2208 controller

**Comment by radek8** [comment]
![image](https://user-images.githubusercontent.com/46979052/95509657-0f93b100-09b5-11eb-86c6-a67c453c39c8.png)

![image](https://user-images.githubusercontent.com/46979052/95509737-2a662580-09b5-11eb-90c5-af5f766468f3.png)

**Comment by IIIxpHunterIII** [comment]
Is the solderbridge necessary for the V1.2?

![image](https://user-images.githubusercontent.com/16221970/95514796-d5c6a880-09bc-11eb-8b0f-50421aade375.png)

**Comment by radek8** [comment]
If you want to run in UART mode, yes
You don't have an F6 board

**Comment by IIIxpHunterIII** [comment]
Ahh okay, I was wondering about that one.

**Comment by radek8** [comment]
what are you solving?
It is a small ball of tin or you wrap 2 pins with wire

**Comment by radek8** [comment]
https://www.makenprint.uk/3d-printing/3d-printing-guides/skr-v1-3-setup-guide/

In order to setup UART mode on the TMC2208 drivers themselves we need to enable the feature. It requires a light bit of soldering of two contacts as circled above and is a quick job. Time your time there is no rush.

If the TMC2208 driver you are using are version 3 from BIGTREE-TECH then skip the soldering part it is already done for you.

**Comment by IIIxpHunterIII** [comment]
Ive done that yesterday after you told me to, tmc debugging (m119 if i remember correctly) says it works. Te only remaining prob would be that m119 only gives an ok but no other info such as vrev

**Comment by zonalimitatore** [comment]
M119?

**Comment by IIIxpHunterIII** [comment]
It was 122, I was mistaken. Could you maybe explain those terms, i couldn't find good explainations on them? And another question would be (I know, wrong thread) how do I configure dual Z endstops, it says I've gotten something wrong:

 #error "Z2_USE_ENDSTOP has been assigned to a nonexistent endstop!"

//
// For Z set the number of stepper drivers
//
#define NUM_Z_STEPPER_DRIVERS 2   // (1-4) Z options change based on how many

#if NUM_Z_STEPPER_DRIVERS > 1
  #define Z_MULTI_ENDSTOPS
  #if ENABLED(Z_MULTI_ENDSTOPS)
    #define Z2_USE_ENDSTOP          _XMAX_
    #define Z2_ENDSTOP_ADJUSTMENT   0
    #if NUM_Z_STEPPER_DRIVERS >= 3
      #define Z3_USE_ENDSTOP        _YMAX_
      #define Z3_ENDSTOP_ADJUSTMENT 0
    #endif
    #if NUM_Z_STEPPER_DRIVERS >= 4
      #define Z4_USE_ENDSTOP        _ZMAX_
      #define Z4_ENDSTOP_ADJUSTMENT 0
    #endif
  #endif
#endif

//
// Limit Switches
//
#ifdef X_STALL_SENSITIVITY
  #define X_STOP_PIN                  X_DIAG_PIN
  #if X_HOME_DIR < 0
    #define X_MAX_PIN                      P1_26  // E0DET
  #else
    #define X_MIN_PIN                      P1_26  // E0DET
  #endif
#else
  #define X_STOP_PIN                       P1_29  // X-STOP
#endif

#ifdef Y_STALL_SENSITIVITY
  #define Y_STOP_PIN                  Y_DIAG_PIN
  #if Y_HOME_DIR < 0
    #define Y_MAX_PIN                      P1_25  // E1DET
  #else
    #define Y_MIN_PIN                      P1_25  // E1DET
  #endif
#else
  #define Y_STOP_PIN                       P1_28  // Y-STOP
#endif

#ifdef Z_STALL_SENSITIVITY
  #define Z_STOP_PIN                  Z_DIAG_PIN
  #if Z_HOME_DIR < 0
    #define Z_MAX_PIN                      P1_00  // PWRDET
  #else
    #define Z_MIN_PIN                      P1_00  // PWRDET
  #endif
#else
  #ifndef Z_STOP_PIN
    #define Z_STOP_PIN                     P1_27  // Z-STOP
  #endif
#endif

**Comment by IIIxpHunterIII** [comment]
Oh and that solved my question from befor 👍 
"TMC_DEBUG adds more reported information."

**Comment by oldman4U** [comment]
What is the question? Dual z?

It is a function of the board. For Marlin you have to configure it like you would have a single z axis.

**Comment by IIIxpHunterIII** [comment]
It doesnt compile bacause of this: #error "Z2_USE_ENDSTOP has been assigned to a nonexistent endstop!"

**Comment by IIIxpHunterIII** [comment]
I have configured dual Z endstops, because...well problems.

//
// For Z set the number of stepper drivers
//
#define NUM_Z_STEPPER_DRIVERS 2 // (1-4) Z options change based on how many

#if NUM_Z_STEPPER_DRIVERS > 1
#define Z_MULTI_ENDSTOPS
#if ENABLED(Z_MULTI_ENDSTOPS)
#define Z2_USE_ENDSTOP XMAX
#define Z2_ENDSTOP_ADJUSTMENT 0
#if NUM_Z_STEPPER_DRIVERS >= 3
#define Z3_USE_ENDSTOP YMAX
#define Z3_ENDSTOP_ADJUSTMENT 0
#endif
#if NUM_Z_STEPPER_DRIVERS >= 4
#define Z4_USE_ENDSTOP ZMAX
#define Z4_ENDSTOP_ADJUSTMENT 0
#endif
#endif
#endif

**Comment by IIIxpHunterIII** [comment]
> What is the question? Dual z?
> 
> It is a function of the board. For Marlin you have to configure it like you would have a single z axis.

And if i specify the Pins like this:
// Limit Switches
//
#define X_MIN_PIN P1_29
#define X_MAX_PIN P1_26
#define Y_MIN_PIN P1_28
#define Y_MAX_PIN P1_25
#define Z_MIN_PIN P1_27
#define Z_MAX_PIN P1_00

It rips the Z1 connector apart -> eg no Z1 Stop

**Comment by oldman4U** [comment]
This exceeds what I know about Marlin, sorry. The machine I have which uses dual Z has TMC2209 and sensorless homing, so no physical endstops at all on min, and software endstops for max. Never configured dual motor drivers or endstops before.

My advise. Start with a simple setup and add features and functions later on. To start from zero to everything, incl. power control and filament sensor and LED and..... will not work and will leave you back frustrated.

My 2 cents

**Comment by IIIxpHunterIII** [comment]
Thats a pity, but I wont start from the beginning... it took me two days to configure it since it's my first marlin build 😅 I'll figure it out somehow I guess

**Comment by oldman4U** [comment]
Sounds like a big adventure to me. 👍🏻

**Comment by radek8** [comment]
I also have two trapezoidal screws on the Z axis.
But I find the use of two engines unnecessarily complicated, so the second screw I have transferred to a pulley with a belt.
So I have no experience with your configuration

**Comment by oldman4U** [comment]
Hi.

Please close the ticket once you do not need it anymore. The problem related to the TFT seems to be solved;-)

Thank you and happy printing

**Comment by IIIxpHunterIII** [comment]
> I also have two trapezoidal screws on the Z axis.
> But I find the use of two engines unnecessarily complicated, so the second screw I have transferred to a pulley with a belt.
> So I have no experience with your configuration

I cannot do that, since the I3 has no space for that :(
