### ISSUE TITLE
[Q] I got error message notification

### ISSUE THREAD

**Issue by islonina** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1164]
I got 3 notification error:

-material hetup parameters
-PID settings
-filament load/unload lengths

Can't find them on machines setup

**Comment by oldman4U** [comment]
Please help the community and close the other ticket. 

Thank you

**Comment by oldman4U** [comment]
Thank you.

When did you get the notification after doing what?

Maybe a picture could also help.

Thank you

**Comment by islonina** [comment]
I get this on power on printer every time. When I enter notification many on the main panel.![IMG_20201009_120209.jpg](https://user-images.githubusercontent.com/25852721/95570558-64700f80-0a27-11eb-86c4-a44e4a087b01.jpg). When I push 117 ABL notification ![IMG_20201009_120322.jpg](https://user-images.githubusercontent.com/25852721/95570643-7ea9ed80-0a27-11eb-876b-796a5efe6ff5.jpg)

**Comment by oldman4U** [comment]
It is a new feature. Previous version only showed the last Echo message.
The new version still shows one Echo message but in addition you can click
on the message „window“ or the upper bar to see the 3 last messages.

No bug but a feature.

;-)

islonina <notifications@github.com> schrieb am Fr. 9. Okt. 2020 um 12:04:

**Comment by islonina** [comment]
But I can't find where to I need to enter this value. Length and pod. I know that pod I probably pid value after auto tune but length load and unload? I have set this on firmware for marlin lcd

**Comment by oldman4U** [comment]
These are information and not errors. Like I wrote before, with the older version you would not have seen the, even they always exist. Now you see them.

**Comment by islonina** [comment]
I know it's information but I assume after : they should be a value like on fade high:5

**Comment by oldman4U** [comment]
Yes, there should be everything shown related to a message, but I guess there is simply not enough space to show it. Those messages are usually very short and sometimes useful;-)

**Comment by islonina** [comment]
Ok. Now i have problem. ftf doesnt save mesh value. When i run MBL on marlin mode everytking is saved when i run M503 i see all point value. When i run MBL on TFT the value doesnt exist even after manual M500 commend on TFT

**Comment by oldman4U** [comment]
Close this ticket in case you do not need it anymore. Check existing open and closed tickets and make a new ticket if needed.
