### ISSUE TITLE
Unknown command: "M503 (S0)"

### ISSUE THREAD

**Issue by alibaaab** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1173]
After update from older version (Jun 17 2020) to latest (BIGTREE_TFT35_V3.0_E3.26.x.bin) on my TFT35-E3 am I am still getting echo about M503 like the title says. It is quite disturbing. I tried to add it to knownEcho to ignore it, but there is no more space on the board for this change. Is there some fix for it? Do you know why it is happening?

**Comment by radek8** [comment]
Can you attach a photo?

**Comment by alibaaab** [comment]
So, just after boot:
![justBoot](https://user-images.githubusercontent.com/25647439/96091642-24e37080-0eca-11eb-8b8a-c10d8839f8be.JPEG)

Detail screen of errors after boot (no other action between):
![detailafterBoot](https://user-images.githubusercontent.com/25647439/96091743-417fa880-0eca-11eb-8e45-33be24c40c8c.JPEG)

After first (basically after each command):
![afterEachHoming](https://user-images.githubusercontent.com/25647439/96091825-5a885980-0eca-11eb-9983-1fc5b07fc4b8.JPEG)

For now i just hide it by marlin
`#define DISABLE_M503   `

**Comment by radek8** [comment]
You must enable M503 in Marlin

**Comment by alibaaab** [comment]
Just for take this pictures i did this change to marlin 
`// #define DISABLE_M503   `
but i this case i got still this errors, so i hide it by:
`#define DISABLE_M503   `

**Comment by radek8** [comment]
set:
#define EEPROM_SETTINGS     // Persistent storage with M500 and M501
//#define DISABLE_M503        // Saves ~2700 bytes of PROGMEM. Disable for release!

#define EXTENDED_CAPABILITIES_REPORT

**Comment by alibaaab** [comment]
OK in configuration.adv.h i have 
`#define EXTENDED_CAPABILITIES_REPORT`
and in configuration.h i have 
`#define EEPROM_SETTINGS       // Persistent storage with M500 and M501
// #define DISABLE_M503        // Saves ~2700 bytes of PROGMEM. Disable for release!
// #define EEPROM_CHITCHAT       // Give feedback on EEPROM commands. Disable to save PROGMEM.
#define EEPROM_BOOT_SILENT    // Keep M503 quiet and only give errors during first load
#if ENABLED(EEPROM_SETTINGS)
  //#define EEPROM_AUTO_INIT  // Init EEPROM automatically on any errors.
#endif`

**Comment by radek8** [comment]
you have to comment
// #define DISABLE_M503

**Comment by alibaaab** [comment]
I have it in comment (enable feature) M503, but in this case i always got message 
`Unknown command: "M503 (S0)`
I want to use 503, but seem like problem is not on display but on board since same error i got by manual call gcode M503

**Comment by radek8** [comment]
The problem will be in the Marlin configuration
please attach files
configuration.h
configuration_adv.h

**Comment by alibaaab** [comment]
[Configuration_adv.txt](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5383505/Configuration_adv.txt)
[Configuration.txt](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5383507/Configuration.txt)

**Comment by alibaaab** [comment]
i have other changes on pin setup for set properly 3d touch sensor, but should not be related

**Comment by radek8** [comment]
Try deleting to comment on this volume
#define EEPROM_CHITCHAT

**Comment by radek8** [comment]
Máte Desku BTT_SKR_V1_4_TURBO
Proč máte povolený ovladač pro konektor EXP3?
 #define CR10_STOCKDISPLAY
správě by jsi měl povolit 
#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
a použít 2 ploché vodiče EXP1 a EXP2
Aby ti fungoval imulovaný Marlin mod

**Comment by radek8** [comment]
Enable these 2 values
#define EMERGENCY_PARSER
#define EXTRA_FAN_SPEED

**Comment by radek8** [comment]
if you are using the TMC2208 in UART mode
turn on
#define HYBRID_THRESHOLD

**Comment by alibaaab** [comment]
nice now retro simulation is working, thanks radku but :
> Y stepper motor is much louder even when i return #define HYBRID_THRESHOLD back into comment
> 503 error still appear
For change confirm i add new version of configs:
[Configuration.txt](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5387350/Configuration.txt)
[Configuration_adv.txt](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5387351/Configuration_adv.txt)

**Comment by radek8** [comment]
I understand that your display is already working in Marlin mode and the error with the M503 is still appearing. 
I didn't understand the other one. Can you be more accurate?

**Comment by radek8** [comment]
If you have ender3 and you haven't changed the pulleys, you have the wrong stride lengths

![image](https://user-images.githubusercontent.com/46979052/96182701-20ed3800-0f36-11eb-92d3-b0515e5256d3.png)

**Comment by radek8** [comment]
I would allow
#define RESTORE_LEVELING_AFTER_G28

**Comment by radek8** [comment]
you still haven't commented on this choice !!!!!

//#define DISABLE_M503

**Comment by radek8** [comment]
comment the choice
//#define SLIM_LCD_MENUS

**Comment by alibaaab** [comment]
> 
> 
> If you have ender3 and you haven't changed the pulleys, you have the wrong stride lengths
> 
> ![image](https://user-images.githubusercontent.com/46979052/96182701-20ed3800-0f36-11eb-92d3-b0515e5256d3.png)

This was changed because from some reason i got differents between controller coordinate agains real one. So i calculate these numbers and now it is occured because of that.



> 
> 
> comment the choice
> //#define SLIM_LCD_MENUS

Sorry for that, already did.

**Comment by alibaaab** [comment]
Sorry for my insolence, but can we call?

**Comment by radek8** [comment]
enable option
#define LONG_FILENAME_HOST_SUPPORT
#define SCROLL_LONG_FILENAMES

**Comment by radek8** [comment]
I don't speak English

**Comment by alibaaab** [comment]
> 
> 
> I don't speak English

but i think radek is czech name and i am speaking cesky ;)

**Comment by radek8** [comment]
724064325

**Comment by alibaaab** [comment]
I suggest for all to settup config according on rader's comments

**Comment by radek8** [comment]
The steps on the X-axis are strange.
Can you please disconnect the TMC2208 from the board and take a picture of the socket?
The x-axis does not appear to be in UART mode, but has a manually set microstep at 8x

**Comment by hiskynet** [comment]
> You must enable M503 in Marlin

thanks helped in my e-step calibration for Geeetech A10M
