### ISSUE TITLE
bug in code

### ISSUE THREAD

**Issue by borsegbr** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1176]
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/blob/dd12c39659f3ca54f82f5da4f2f6e20476f24010/TFT/src/User/API/Printing.c#L184

E_axis indeed is Z_axis
correct with 
Line 184 in dd12c39

 mustStoreCmd("G1 Z%.3f F%d\n", tmp.axis[Z_AXIS] + infoSettings.pause_z_raise, infoSettings.pause_feedrate[Z_AXIS]);

**Comment by radek8** [comment]
@guruathwal Can you please check this reported error?
This is your PR #733 code
Thank you
