### ISSUE TITLE
[Suggestion] Different layout for showing filesystem

### ISSUE THREAD

**Issue by Hukuma1** [bigtreetech/BIGTREETECH-TouchScreenFirmware#118]
![oldscreen](https://user-images.githubusercontent.com/54511555/69023846-1d8fac00-0975-11ea-8374-5ad28b4fbbb5.png)

Did a quick mockup of how it currently is, and what I think could be an improvement. Right now it's hard to read the filenames and you have to wait for it to scroll through to confirm you got the right one. This way you would have more room to see the whole file. Any thoughts?

![newscreen](https://user-images.githubusercontent.com/54511555/69023877-38fab700-0975-11ea-8d6e-4ff2886a794c.png)

**Comment by guruathwal** [comment]
This would be nice.

**Comment by Sthopeless** [comment]
this would be very nice!

**Comment by Aleks-MO** [comment]
Well read long file name, more information.

**Comment by thisiskeithb** [comment]
This is how file selection works on the MKS Nano (with “dumb” TFT), or at least on the Lotmaxx SC-10:

![4D648421-E8C6-4AB6-B6C4-E0D7A514711E](https://user-images.githubusercontent.com/13375512/68572019-377f3b00-0419-11ea-950a-c9984fca505a.jpeg)
Source: [Chris Taylor/Nerys - Lotmaxx SC 10 Analysis T3DP](https://youtu.be/n_JcMkiBRfw)

I like the compactness of the buttons on the right and we’re all in agreement that a list would improve readability.

**Comment by Aleks-MO** [comment]
@thisiskeithb  
Better option 2, lines! The icons here are redundant.

**Comment by guruathwal** [comment]
I agree with @Aleks-MO

**Comment by Sthopeless** [comment]
I also agree with @Aleks-MO & @guruathwal the list looks by far better!

**Comment by thisiskeithb** [comment]
Gcode previews do look nice, though:

![87D9E189-73D8-48BF-988B-7DB7D8F4C699](https://user-images.githubusercontent.com/13375512/68578574-22110d80-0427-11ea-9743-60768c3ab879.jpeg)

**Comment by Sthopeless** [comment]
yes they do. maybe isn't possible to have it as a selectable option(?) one way shows the menu vertically where we can read the names properly the other one has the preview mode in horizontal view.

**Comment by Aleks-MO** [comment]
@thisiskeithb 
Do you need these little thingies and lace? Need a print! )))

**Comment by Hukuma1** [comment]
![newexample](https://user-images.githubusercontent.com/54511555/68606697-d29d0280-0463-11ea-9335-912d29676da9.png)

How about both?

**Comment by Aleks-MO** [comment]
Need to see a photo of the screen?

**Comment by Hukuma1** [comment]
![this1](https://user-images.githubusercontent.com/54511555/68611819-e0588500-046f-11ea-9bce-4790c6097b09.jpg)

You mean like this?

**Comment by Aleks-MO** [comment]
Yes! ))

**Comment by Hukuma1** [comment]
Updated the previews of the idea above. Slight change to accommodate for space on screen.

**Comment by ShaggyDog18** [comment]
Absolutely support that development: the current Print list with 8-char file names looks... like jumping back to the last century. Please, re-design this page, show full file names in the vertical list... No doubt that would improve usability of TFT screens.

**Comment by Aleks-MO** [comment]
@ShaggyDog18  Little willing, everyone wants icons... It came to the point that the vertical location of the screen for its filling with information was accepted.

**Comment by guruathwal** [comment]
![photo_2019-11-24_23-04-02](https://user-images.githubusercontent.com/22422544/69499691-c3658c80-0f1a-11ea-93f1-513c32f965b8.jpg)

Welcome back again to 21st century #179

**Comment by Hukuma1** [comment]
![happening](https://user-images.githubusercontent.com/54511555/69499921-c8d7be00-0eab-11ea-9c73-6698345358a1.gif)

Thank you, @guruathwal. :) I would like to suggest we mask the file name extension (.gcode). Or maybe an option to? And how about replacing device source text (SD:/) with icon as well? 21st century looking nice. :D

**Comment by Aleks-MO** [comment]
@guruathwal Did it come in? It is perfectly! 
I have not seen it yet. ¯\_(ツ)_/¯

**Comment by Sthopeless** [comment]
thank you @guruathwal looks ALOT! better, but mine is missing up, down, back icons? I see only 2 squares on each button

**Comment by guruathwal** [comment]
@Sthopeless you need to update the fonts also..

**Comment by Hukuma1** [comment]
@Sthopeless jumped ahead into 23rd century with those missing font alien symbols. :D

**Comment by guruathwal** [comment]
> @guruathwal Did it come in? It is perfectly!
> I have not seen it yet. ¯_(ツ)_/¯

👍

**Comment by Sthopeless** [comment]
@Hukuma1 true that :P 
I didn't even noticed the folder and files icons were also missing

**Comment by Aleks-MO** [comment]
@guruathwal    when they upgrade package to public access  the TFT35 and bin (version xxx.24.3)???  ;-(

**Comment by Hukuma1** [comment]
@Aleks-MO I'm impatient too. So I downloaded the files before they were approved for master branch:

Download these 2 files and re-flash your firmware from SD card:

1. https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/blob/b487c6fe9b16626ef57a8dfc4805a699edab5dd1/Copy%20to%20SD%20Card%20root%20directory%20to%20update%20-%20Unified%20Menu%20Material%20theme/BIGTREE_TFT35_V3.0.25.bin

2. https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/blob/b487c6fe9b16626ef57a8dfc4805a699edab5dd1/Copy%20to%20SD%20Card%20root%20directory%20to%20update%20-%20Unified%20Menu%20Material%20theme/TFT35/font/word_unicode.fon

Replace the FON file that's in your TFT35\font directory.

Just tested it on TFT35 V3. Looks great!

**Comment by Aleks-MO** [comment]
@Hukuma1  ))) 
Thank you, I will try .. My personal opinion is that everything should be brought to a single system and issue the final version here. Downloaded, installed. Not all TFT programmers!

**Comment by Hukuma1** [comment]
I think they need to make material theme the default and simply delete the other icons/theme altogether. ;) And split downloads to specific models for less tech-savvy users. That way TFT35 V3.zip can simply have the 95x95 icons, and the corresponding firmware.bin. So install would be as easy as unzipping to SD card for upgrade. Not searching which folder to choose, etc.

**Comment by Aleks-MO** [comment]
Yes,  there will be less confusion ...

**Comment by guruathwal** [comment]
@Aleks-MO @Hukuma1 
I will try to simply the files and update process to be easier for everyone..👍

**Comment by Hukuma1** [comment]
![printconfirmation](https://user-images.githubusercontent.com/54511555/70267056-838c7980-1752-11ea-83a7-18a539b1b370.png)

Maybe we can have an intermediary screen before we start print? Could be useful if a) you wanted to confirm a print file (visual), or b) maybe you clicked on wrong file because a list view is slightly harder to click than icons.

**Comment by Aleks-MO** [comment]
@Hukuma1  My opinion is superfluous ... Better think, why 2 com? Can it be used for LEDs?

**Comment by Hukuma1** [comment]
Bad translation? Not sure what you mean?

**Comment by Aleks-MO** [comment]
Думаю это лишнее.  Как использовать дополнительные порты COM на TFT.  Можно  его использовать для светодиодов?

**Comment by Hukuma1** [comment]
No idea about additional COM ports on the board or anything about LEDs. That's for another topic I think. :P

**Comment by GenaUser** [comment]
@Hukuma1 I agree with your visual proposition.

**Comment by Hukuma1** [comment]
You’ll have to see if @guruathwal think it’s possible to implement. 👍🏼

**Comment by Aleks-MO** [comment]
@Hukuma1  Он (@guruathwal) здесь все управляет?

**Comment by guruathwal** [comment]
@Aleks-MO  not at all.. I am just a contributor 👍 .
@Hukuma1 sure it is possible, but need some time.. 👍

**Comment by Aleks-MO** [comment]
@guruathwal  Жаль..))   Хозяина здесь не хватает... 
Видел твои обновления , пожалуйста делай фото основного экрана и экрана печати., для большей наглядности как это выглядит. Кто пробовал, говорят что русские шрифты очень плохие.  Спасибо что правишь прошивки. 
@guruathwal Is a pity.)) The master here is missing...
Saw your updates, please take a photo of the main screen and the print screen., for more clarity, what it looks like. Who tried, they say that Russian fonts are very bad. Thanks for ruling the firmware.

**Comment by gordo3di** [comment]
I've recently been trying to get the thumbnails to show up again in the printing screen. After two full days of messing around I am no further along. Something is wrong in the ICON_PREVIEW code but I still can't figure out why. I was also trying to get the thumbnail to show up in the start print popup which is what started all this.

In PrintingMenu.c I just forced the model_DirectDisplay to see if I could get it to show up. In the code below it will show for a brief millisecond then is immediatly replaced by the move icon.

```c
    printingItems.items[KEY_ICON_5].icon = (infoFile.source < FS_ONBOARD_MEDIA && isPrintModelIcon()) ? ICON_PREVIEW : ICON_BABYSTEP;
    //gCreate testing to make preview thumb work
    //printingItems.items[KEY_ICON_5].icon = (infoFile.source < FS_ONBOARD_MEDIA && isPrintModelIcon()) ? ICON_BABYSTEP : model_DirectDisplay(getIconStartPoint(5), infoFile.path);
    printingItems.items[KEY_ICON_5].icon = model_DirectDisplay(getIconStartPoint(5), infoFile.path);
```

Changing it to ICON_PREVIEW will have some icon show up that I've never seen with no brief thumbnail.

```c
    printingItems.items[KEY_ICON_5].icon = (infoFile.source < FS_ONBOARD_MEDIA && isPrintModelIcon()) ? ICON_PREVIEW : ICON_BABYSTEP;
    //gCreate testing to make preview thumb work
    //printingItems.items[KEY_ICON_5].icon = (infoFile.source < FS_ONBOARD_MEDIA && isPrintModelIcon()) ? ICON_BABYSTEP : model_DirectDisplay(getIconStartPoint(5), infoFile.path);
    printingItems.items[KEY_ICON_5].icon = ICON_PREVIEW;
```
![PXL_20221108_202738626](https://user-images.githubusercontent.com/11464057/200669016-0c8ad68d-775e-444b-8ddb-52aeaf68a761.jpg)
