### ISSUE TITLE
[BUG] Z-Offset ABL crashes gantry

### ISSUE THREAD

**Issue by chill-uk** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1183]
### Description

Everytime I try and enable z-offset to configure ABL, my Ender 3 tries to move past the end-stops, crashing the gantry.

### Steps to reproduce

1. Go to Movement
2. ABL
3. z-offset -> on

**Expected behavior**
3D Printer will auto-home, then probe the bed.

**Actual behavior**
3D Printer tries to move past the end-stop, causing the gantry to crash.

### Hardware Variant
BIGTREE_TFT35_V3.0_E3

### TFT Firmware Version & Main Board Firmware details
BIGTREE_TFT35_V3.0_E3.26.x.bin

### Setup
Ender3 + SKR Mini E3 v2.0

System: Marlin 2.0.7.2 (Oct 16 2020) 
[Firmware_BLTouch](https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/blob/master/firmware/V2.0/firmware-bltouch.bin)

### Additional Information
* [Reddit Post](https://www.reddit.com/r/ender3/comments/jdfy00/btt_zoffset_abl_crashes_gantry/)
* [Youtube video](https://www.youtube.com/watch?v=nVrJM1YBoGo)

**Comment by radek8** [comment]
Our problem is not caused by the touch screen but by the wrong setting of the limit switches in Marlin.
Check the Marlin configuration and perform a new compilation of Marlin

**Comment by digant73** [comment]
also remember that PR #1154 will restore the original "software endstops" state exiting from Z offset menu.
So if in your Marlin FW you disabled "software endstops", that state will be restored when you exit from Z Offset menu.
Currently the software endstops are always enabled exiting from Z offset menu

**Comment by chill-uk** [comment]
Hi @radek8 @digant73 , I have only used the official pre-compiled firmwares for both SKR and TFT.

If there is a Marlin config issue, it would suggest that they are present in those builds:
[SKR Mini E3 v2.0](https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/blob/master/firmware/V2.0/firmware-bltouch.bin)
[TFT35](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/blob/master/Copy%20to%20SD%20Card%20root%20directory%20to%20update%20-%20Unified%20Menu%20Material%20theme/BIGTREE_TFT35_V3.0_E3.26.x.bin)

I'm not sure if that helps ?

**Comment by radek8** [comment]
Compile your own Marlin.
It is difficult to determine what parameters are stored in the BIN file.

**Comment by oldman4U** [comment]
Please check if #1188 solves the problem. 

Do you know how to compile the firmware or do you need help?

**Comment by digant73** [comment]
@chill-uk it's better that you compile the firmware. The problem should not be present also in the current main branch. Z offset menu simply performs homing and then moves nozzle to Z 0. The endstops are disabled just to allow to move nozzle to negative Z values (so to decrease Z offset value).
PR #1188 fixed the bug related to original endstops state not restored exiting from Z offset menu. But that should not be your problem

**Comment by digant73** [comment]
From the video I see a z offset set to -1.85. Is it the value you set?

**Comment by digant73** [comment]
You are also using an old version of the FW. Try the latest one

**Comment by oldman4U** [comment]
@chill-uk 

Is your problem solved?

Please let us know 

Thank you

**Comment by chill-uk** [comment]
Hi All,
I really appreciate all of your input and help. 
Unfortunatelly, I haven't had a chance to get around to compile my own firmware yet (life commitments).
Feel free to close the bug report if needed.

**Comment by digant73** [comment]
I will compile it for you my current PR

**Comment by digant73** [comment]
Attached the PR #1188 compiled for your TFT35. unzip it in the root directory of the SD card.
Change first the settings in config.ini according to your printer and then flash the FW.
Let us know the result

[TFT35.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5443931/TFT35.zip)

**Comment by chill-uk** [comment]
Hi @digant73, I've tried your compiled version (and modified the config.ini), but the problem persists.

Unfortunately, I won't have much time to test/diagnose the issue (new baby due very soon), so I'll close the ticket.

Thanks everyone for your time and effort with this bug.
I hope to be able to contribute back somehow.

Stay safe 👍

**Comment by oldman4U** [comment]
Good luck!
