### ISSUE TITLE
[Q] System info not showing Marlin version

### ISSUE THREAD

**Issue by zeruspocus** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1185]
Hello guys,
Am I missing something here? The info screen is not showing the Marlin Version (2.0.7) and I think that is leading to some other potential issues I'm having.
Is there anything that I should have in mind when I compile Marlin for the TFT35? 
Is this Marlin Version 2.0.7 not communicating properly with the screen?

TIA
![info](https://user-images.githubusercontent.com/72356635/96437527-4bc9db80-1217-11eb-8496-f186516728d8.jpeg)

**Comment by zeruspocus** [comment]
![info2](https://user-images.githubusercontent.com/72356635/96444059-a0bd2000-121e-11eb-8ef7-4b0754769fe5.jpeg)
Not sure how, but now it's there

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
