### ISSUE TITLE
[Q] (How to edit *.fon file?)

### ISSUE THREAD

**Issue by dzario** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1195]
I want change font file for special character in Slovak language and other with character : č,š,ľ,ď,ž,á... etc ..
What program I can use for this .

**Comment by oldman4U** [comment]
Please update the latest firmware according to the document on this page. This allows you also to select a language.

https://github.com/oldman4U/BIGTREETECH-TouchScreenFirmware/tree/Oldman4U

**Comment by dzario** [comment]
Update ..

... Working thanks ... now charset are perfect ..
