### ISSUE TITLE
[BUG] Terminal outputs "Busy paused for user" after every print

### ISSUE THREAD

**Issue by blueeagle69** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1199]
Hi.

After every print the terminal outputs a constant "busy: paused for user" and will not respond to any further commands.
However if you press the encoder wheel  once the busy command goes away and the printer will then respond.
Also if you click the encoder once after a print the screen does not respond to the first click, but it does on subsequent clicks.
It's like as if the screen is asleep and the click of the encoder wakes it up, because once I click the encoder the LCD goes to full brightness and the busy output to the terminal goes away.
The issue occurs in TFT and Marlin mode,
I can't tell if this is a Marlin firmware or TFT issue, or a "feature".  But I do now I never got it on my other printer that has a standard full graphic LCD.

Thanks.

**Comment by oldman4U** [comment]
Do you have end gcode activated?

**Comment by blueeagle69** [comment]
Hi.

No, End Gcode is not activated.
I could test with it activated.
But saying that, does the start/end Gcode get used in Marlin mode? I don't think it does.

Thanks!

**Comment by oldman4U** [comment]
Try it and we all will know.

**Comment by blueeagle69** [comment]
Hi.
I enabled End Gcode.
Printed from Marlin mode.
Same thing.
Printer constantly outputs busy message at the end of a print until the encoder is clicked.

**Comment by oldman4U** [comment]
And what does the TFT. How does it look like after a print?

**Comment by blueeagle69** [comment]
Hi.

I will  do a test later and respond.

Thanks.

**Comment by blueeagle69** [comment]
Hi.
I'm pretty-sure when printing from TFT it brings up a "Print Complete" dialogue box with an "OK" button.
Could that be why in Marlin mode it outputs a busy message until the encoder is clicked?

**Comment by blueeagle69** [comment]
Okay, when printing in TFT mode it brings up the "Print Complete" box.
While this is on the screen the printer outputs the busy message.
When I click Okay, I am left with this screen.
![20201027_005409](https://user-images.githubusercontent.com/9963876/97244673-380f0e00-17f1-11eb-8aa6-1b25e57116a9.jpg)
Requiring me to hit Stop.

**Comment by oldman4U** [comment]
Well, this looks exactly the same on my screens.

I know only one who can help us, @radek8.

Do you know if this is the expected behaviour or not?

Please help

Thank you

**Comment by radek8** [comment]
Check the end code in your slicing software.
A pause starts before the end of printing.
According to the icon in the photo, it looks like the print is not finished but only paused.
Please attach a file to print that you have a problem with. We'll see if my reasoning is correct

![image](https://user-images.githubusercontent.com/46979052/97344192-b7035580-1888-11eb-9217-a49b138dfa56.png)

**Comment by blueeagle69** [comment]
Hi.
My end Gcode consists of M300 tone commands which of course only work in Marlin mode, and an
M524 which I was testing to see if it would end the print and stop the TFT bringing up the pause at the end of the print, which not did not.

**Comment by CBDesignS** [comment]
I had a problem simmilar when I tweaked the end gcode in cura a while ago. I just copied most of the code from one of my previous repg generated files thinking that it should work . it did but it caused a bit of pausing at the end of the print. the only problem is I can not remember what gcode command it was that done it. Maybe post your end code from your slicer then more knolegable users maybe able to help you ??

**Comment by blueeagle69** [comment]
G91 ; Absolute positioning
G1 E-5 F300
G27
M104 S0 ; Set Hotend Temperature to 0
M140 S0 ; Set Bed Temperature to 0
M18  
M300 S860 P150 
G4 P100 ; Wait 1 second
M300 S960 P100
G4 P100 
M300 S1160 P150
M150 R0 G0 B0 W0

**Comment by CBDesignS** [comment]
I am no gcode wizard but I though a G27 command needed passing parameters. 
I have just looked at the Marlin Gcode bible and it says :- 
G27 [P<0|1|2>]

[P<0\|1\|2>] | Z axis action   P0: If current Z-pos is lower than Z-park then the nozzle will be raised to reach Z-park height   P1: No matter the current Z-pos, the nozzle will be raised/lowered to reach Z-park height   P2: The nozzle height will be raised by Z-park amount but never going over the machine’s limit of Z_MAX_POS
-- | --

to me that might as well be written in greek .

**Comment by blueeagle69** [comment]
No, G27 will run without parameters. You only need the P Switch if you want the Z axis to rise.

**Comment by CBDesignS** [comment]
ok. just a thought. I just send the extruder to a position with a G0 command then I know it will always lower my bed (upside down printing) and be well away from the final print. G0X255Y150Z140

**Comment by blueeagle69** [comment]
I'm not really bothered with the fact the TFT doesn't end correctly as I mostly print in Marlin mode.
What I was on about was the fact that when I'm printing in Marlin mode, the printer sends out a constant Busy message until I click the encoder (Marlin) or in TFT mode, close the Print Complete box.
Actually if the TFT brings up a Print Complete box, then surely it isn't pausing anywhere?

**Comment by CBDesignS** [comment]
the only other thing is you use M150 R0 G0 B0 W0 and I think the G0 shouldd be U0 as G0 is a gcode command. maybe try changing M150 R0 G0 B0 W0 to M150 R0 U0 B0 W0 ???

**Comment by blueeagle69** [comment]
Thanks, I will do that, although I don't think it will help the overriding issue with the constant Busy output which requires me to click the encoder.

**Comment by blueeagle69** [comment]
I just decided to try a test print with no end Gcode defined in my slicer, sure enough the print ended, and in my terminal I had the normal "echo:busy: paused for user". Once I clicked the encoder the pause message went away.

**Comment by radek8** [comment]
Do you have end code enabled in marlin?
The Configuration.h file
// End G-code - run this G-code after finishing print
#define PRINT_END_GCODE "G90\nG1 E-4\nG92 E0\nM18\n" // Switch to absolute positioning, reduce filament pressure by performing small retract, reset extruder position, disable steppers

**Comment by blueeagle69** [comment]
Unless I'm mistaken, no I don't.
In fact I cannot find that setting in the latest Marlin.
DO you mean the TFT firmware?
Because I can find that line in the TFT firmware but not Marlin.
In the TFT I have tried with it enabled or disabled, same result, printer outputs busy at the end of a print until I click the encoder.

**Comment by blueeagle69** [comment]
Just printed again (In TFT mode) with no end gcode defined in my gcode and End Gcode disabled in LCD.
Same issue.
The printer outputs this;
echo:busy: paused for user
echo:busy: paused for user
echo:busy: paused for user
I click the OKAY button on the Print Complete box and I get this; (In Marlin Mode I have to press the encoder to get rid of the paused for user.)
**M106 P0 S0**

**Comment by radek8** [comment]
send the file to print you have a problem with!

**Comment by blueeagle69** [comment]
Take your pick it happens with every sliced gcode with or without any end gcode in the slicer or the tft. But I will upload a gcode for you.

**Comment by oldman4U** [comment]
radek8. Could you make a short movie showing what happens on your TFT at the end of a print. What blueeagle69 describes is exactly what I can see also, even I thought this would be a strange behaviour and not really a bug...

**Comment by blueeagle69** [comment]
Cheers @oldman4U

**Comment by CBDesignS** [comment]
This is past the limits of my help so I will have to bow out and leave this to others. but before I pop off are you using tft35 E3 v3 ? I only have the tft35 v3 and have not seen this happen since I removed a rogue unsupported gcode from my  Replicator G end code days. Maybe this is specific to E3 V3 screens

**Comment by blueeagle69** [comment]
My screen is apparently a variant of the TFT35 E3 according to Biqu/Bigtreetech which came installed on my Biqu B1. It has the colour changing encoder but MicroSD instead.

**Comment by blueeagle69** [comment]
> This is past the limits of my help so I will have to bow out and leave this to others. but before I pop off are you using tft35 E3 v3 ? I only have the tft35 v3 and have not seen this happen since I removed a rogue unsupported gcode from my Replicator G end code days. Maybe this is specific to E3 V3 screens

I did try it with or without End Gcode in my slicer (Prusaslicer) and the TFT. Same issue regardless.
Thanks.

**Comment by radek8** [comment]
send the file to print

**Comment by blueeagle69** [comment]
Here you go.

[xyzCalibration_cube_0.2mm_PLA_36m.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5467966/xyzCalibration_cube_0.2mm_PLA_36m.zip)

**Comment by radek8** [comment]
it looks fine.
So it will be a setting in Marlin ...

**Comment by blueeagle69** [comment]
It may be a setting causing the TFT screen not to end correctly.
But the printer outputting the Busy paused for user, which goes sway when I press the encoder or close the Print Complete box when in touch mode is down to the TFT.

**Comment by blueeagle69** [comment]
@oldman4U Closed as it's kindly been added to the list.

**Comment by oldman4U** [comment]
I will take care of your bugs and fr. For this particular ticket I will upload a Movie which shows the end of a print on my printer asap. So we can see if radek8 gets something different.

**Comment by oldman4U** [comment]
Hi.

I wanted to know from you radek8 and blueeagle69  if your screen behaves the same after a print, so I made a short movie showing my TFT35.

Please let me know

Thank you

[End of print.mov.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5506816/End.of.print.mov.zip)

**Comment by oldman4U** [comment]
So there is NO Print complete message on my screen after a print

**Comment by radek8** [comment]
Oldman4U on your video has the print done correctly.
The STOP icon changes to BACK when done

![image](https://user-images.githubusercontent.com/46979052/98472099-f454d500-21f0-11eb-88b2-64dcb6ce958c.png)

![image](https://user-images.githubusercontent.com/46979052/98472110-0767a500-21f1-11eb-8bf6-00718c21636a.png)

**Comment by oldman4U** [comment]
But I have no confirm print and using Esp WIFI connection I also see no
strange communication. So where does this confirm comes from?

Radek <notifications@github.com> schrieb am So. 8. Nov. 2020 um 18:35:

**Comment by radek8** [comment]
What confirmation do you mean?

**Comment by oldman4U** [comment]
What blueeagle wrote a few days ago.

_Then again. In TFT mode it correctly brings up the "Print Complete" so I can't see it being a "Marlin Setting"._

**Comment by radek8** [comment]
That he would use old FW?

**Comment by blueeagle69** [comment]
Hi.
With my Marlin and TFT is up to date. 
I get the Print Complete in TFT but then I get the Stop button showing after clearing the Print Complete popup. 
I also noticed yesterday that if I print in Marlin mode and switch back to TFT afterwards,  I'm still greeted with the Stop button, but this time it does nothing.

**Comment by radek8** [comment]
> Hi.
> My Marlin and TFT is up to date.
> I get the Print Complete in TFT but then I get the Stop button showing after clearing the Print Complete popup.
> I also noticed yesterday that if I print in Marlin mode and switch back to TFT afterwards, I'm still greeted with the Stop button, but this time it does nothing.

So did you compile your own FW into TFT?

**Comment by blueeagle69** [comment]
I compile my own.
The only thing I do change is in Selectmode.

Changing "12864 Mode" to "Marlin Mode" It triggers me!

**Comment by radek8** [comment]
> I compile my own.
> The only thing I do change is in Selectmode.
> 
> Changing "12864 Mode" to "Marlin Mode" It triggers me!

to nastavíš v config.INI
#### Text displayed at the top of the TFT in Marlin Mode.
marlin_title:LCD12864 Simulator

**Comment by radek8** [comment]
> Co napsal blueeagle před několika dny.
> 
> _Pak znovu. V režimu TFT správně vyvolá „Tisk dokončen“, takže nevidím, že se jedná o „Nastavení Marlin“._

haven't you changed this setting?

 * Options: [OFF: 0, POPUP: 1, TOAST: 2]
 *  OFF:   No notification. The message is ignored.
 *  POPUP: Display a popup window for user confirmation.
 *  TOAST: A Toast notification is displayed for few seconds. No user interaction is needed
 *
 */
#define ACK_NOTIFICATION_STYLE 1

**Comment by blueeagle69** [comment]
> What confirmation do you mean?

If you replying to me. I mean the Print Complete popup box.

**Comment by blueeagle69** [comment]
> > Co napsal blueeagle před několika dny.
> > 
> > _Pak znovu. V režimu TFT správně vyvolá „Tisk dokončen“, takže nevidím, že se jedná o „Nastavení Marlin“._
> 
> haven't you changed this setting?
> 
>  * Options: [OFF: 0, POPUP: 1, TOAST: 2]
>  *  OFF:   No notification. The message is ignored.
>  *  POPUP: Display a popup window for user confirmation.
>  *  TOAST: A Toast notification is displayed for few seconds. No user interaction is needed
>  *
>  */
> #define ACK_NOTIFICATION_STYLE 1

I believe so but in config.ini.
Do you need my config? I can upload later

**Comment by radek8** [comment]
> > What confirmation do you mean?
> 
> If you replying to me. I mean the Print Complete popup box.

I don't have a pop-up window completed. Printing is complete when the STOP icon changes to BACK.
As seen in the oldman4U video.
Your print job will end with a pause, me for an unknown reason

**Comment by radek8** [comment]
> > > Co napsal blueeagle před několika dny.
> > > _Pak znovu. V režimu TFT správně vyvolá „Tisk dokončen“, takže nevidím, že se jedná o „Nastavení Marlin“._
> > 
> > 
> > haven't you changed this setting?
> > 
> > * Options: [OFF: 0, POPUP: 1, TOAST: 2]
> > * OFF:   No notification. The message is ignored.
> > * POPUP: Display a popup window for user confirmation.
> > * TOAST: A Toast notification is displayed for few seconds. No user interaction is needed
> > 
> > 
> > */
> > #define ACK_NOTIFICATION_STYLE 1
> 
> I believe so but in config.ini.
> Do you need my config? I can upload later

If you changed this to Config.ini, try to return the default value
in config.ini
ack_notification: 1

**Comment by blueeagle69** [comment]
Will do.
At the moment, when in tft mode I get a Print complete popup with an okay button. 
I close that and get the Stop button in the bottom right.

**Comment by oldman4U** [comment]
Eagle. Could you send a picture with the info screen please.

**Comment by blueeagle69** [comment]
@radek8 
Just an update.
In Config.ini I have ack_notification: 1

**Comment by blueeagle69** [comment]
@oldman4U 
![20201109_214035](https://user-images.githubusercontent.com/9963876/98599765-6f42ec00-22d4-11eb-962d-e7e2b56e8636.jpg)

**Comment by radek8** [comment]
FW TFT it can't be I have the same and it behaves normally. Couldn't it be in a Marlin configuration?
Can you attach configuration files from Marlin to compare what's the difference?

**Comment by blueeagle69** [comment]
Certainly 😀
[Marlin Configs.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5513486/Marlin.Configs.zip)

**Comment by blueeagle69** [comment]
Just noticed another weird thing to.
On the Info screen if I press the encoder button instead of touching the screen the printer homes to x/y 0 and the bed heats to 60 degrees and the nozzle to 200. (My PLA temps). I'll take that number for the exorcist if you have it 🤣

**Comment by blueeagle69** [comment]
This is what I get after a print in TFT mode.
![20201109_220832](https://user-images.githubusercontent.com/9963876/98602407-52a8b300-22d8-11eb-857f-b337e889e810.jpg)
![20201109_220809](https://user-images.githubusercontent.com/9963876/98602419-5805fd80-22d8-11eb-8bff-a657382ce8bc.jpg)

**Comment by radek8** [comment]
You must not press the encoder, it is a documented problem.
guruathwal  is working on a fix but this is a HW issue and will not work for any Marlin board.

**Comment by blueeagle69** [comment]
Sweet, thought my TFT was trying to become self-aware.

**Comment by blueeagle69** [comment]
Update to my config files, I just enabled;
#define LCD_SET_PROGRESS_MANUALLY
 #define USE_M73_REMAINING_TIME.
I was just getting an unknown command M73 when printing from UDisk.

**Comment by blueeagle69** [comment]
Sorry for the constant updates.
Just did a test print from Udisk instead of onboard.
This time I do not get the "Print Done" box and the Stop button correctly disappears and changes to "Back".
So the issue is onboard again.

**Comment by radek8** [comment]
I did not see large differences against my configuration.
in addition, I have this option enabled
#define HOST_START_MENU_ITEM

**Comment by blueeagle69** [comment]
I'll give it a try.
Although I thought that just added a menu item to Marlin.

**Comment by radek8** [comment]
For me, the print completed pop-up window does not appear.
Only STOP changes to Back and the head is raised and parked at the edge
I consider this a normal condition.

**Comment by radek8** [comment]
> I'll give it a try.
> Although I thought that just added a menu item to Marlin.

I guess you're right

**Comment by blueeagle69** [comment]
Yeah like I said. If I print from my SKR onboard I get the Print Done box and the Stop button stays there.
If I print from TFT, like you I don't get the Print Done box and the Stop button changes to back.
The issue is onboard SD again.

**Comment by radek8** [comment]
That makes sense :-)
I never print from a card on the SKR. There is no reason :-)

**Comment by radek8** [comment]
What you describe will be standard behavior ...

**Comment by radek8** [comment]
I use the SKR card to emulate EEPROM

**Comment by blueeagle69** [comment]
I think I'm doing the same thing for EEPROM.
I print from the onboard SD because I don't have to remove the MicroSD card to slice to it.
I use Release Media to slice to it, followed by Init SD to remount back to the printer.

**Comment by blueeagle69** [comment]
@oldman4U 
The problem with the stop button showing at the end of a print etc. is caused by Printing from the onboard SD it seems. It works as intended when printing from TFT media.

**Comment by oldman4U** [comment]
And whats about the message on serial in this case?

blueeagle69 <notifications@github.com> schrieb am Mo. 9. Nov. 2020 um 23:26:

**Comment by blueeagle69** [comment]
Hi.
When printing from tft media, the busy output does not appear. I don't get the Print Fine popup either.
So the problem appears to be onboard related again :(

**Comment by radek8** [comment]
My view on this issue is this:
When printing from TFT, the display recognizes the end of printing and displays the DONE button.
When printing from the integrated SD reader on the Marlin board, Marlin controls the printing and the user is informed about the end of printing by the text that marlin sends to the serial port and the display displays it in a pop-up window.
I assume that the dieplay cannot detect that printing is finished and therefore the DONE button will not be displayed

**Comment by oldman4U** [comment]
Please check #1359.

**Comment by kisslorand** [comment]
> My view on this issue is this:
> When printing from TFT, the display recognizes the end of printing and displays the DONE button.
> When printing from the integrated SD reader on the Marlin board, Marlin controls the printing and the user is informed about the end of printing by the text that marlin sends to the serial port and the display displays it in a pop-up window.
> I assume that the dieplay cannot detect that printing is finished and therefore the DONE button will not be displayed
> In both cases, I am informed of the end of printing, but each time in a different way.

That was EXACTLY what was happening. It was a bug in Marlin (as I remember dated from 2019), Marlin didn't send "Done printing file" after the print was finished. I made a PR in Marlin repository about this and as of today it is merged.
