### ISSUE TITLE
Firmware update "stuck"

### ISSUE THREAD

**Issue by TVAVAE** [bigtreetech/BIGTREETECH-TouchScreenFirmware#12]
When putting BIGTREE_TFT24_V1.1.21.bin and the TFT24 folder alone at the root of the SD and re-powering. The screen says: 

Program size: 82kb
Updating:  %

And stays like this the whole time.

**Comment by doughy2002** [comment]
I had this problem.  Change of memory card solved the problem

**Comment by TVAVAE** [comment]
Indeed, changed +- 8 different cards and finally worked...

**Comment by poisson21** [comment]
I found that on a exp1 exp2 config, no serial(for my case,didn't test with). to be able to flawlessly flash new firmware you have disconnect exp2 to make it work. I think the feedback of the "sd card presence" pin interfere with the upload.

**Comment by nmavor** [comment]
@poisson21 workaround work for me (pull exp2 out)

**Comment by mantoles** [comment]
This whole experience is pathetic.  Does not recognize the printer for me and only works in touch screen mode not serial too many bugs

**Comment by hillsh** [comment]
Disconnecting EXP2 worked for me with a 32GB card.
