### ISSUE TITLE
[Q] How do I install the TFT firmware on the Sidewinder X1?

### ISSUE THREAD

**Issue by Stellarspace** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1200]
**Your question or details you need. Please describe.**
How do I install the firmware on the Sidewinder X1? I compile, then I put the required files/folders on a microSD card, then turn the 3D Printer on, but all it does is say the following: Updating... 100%

**Specify the device variant related to your question.**
Sidewinder X1

**Comment by oldman4U** [comment]
Which TFT and which firmware version (date)?

**Comment by Stellarspace** [comment]
> Which TFT and which firmware version (date)?

TFT28, I’m trying to build from master.

**Comment by oldman4U** [comment]
And you followed the instructions?

https://github.com/oldman4U/BIGTREETECH-TouchScreenFirmware/tree/Oldman4U

**Comment by Stellarspace** [comment]
> And you followed the instructions?
> 
> https://github.com/oldman4U/BIGTREETECH-TouchScreenFirmware/tree/Oldman4U

Yes, could it be that the TFT28 is a clone?

**Comment by oldman4U** [comment]
I believe you should ask the manufacturer. No idea.

Stellarspace <notifications@github.com> schrieb am So. 25. Okt. 2020 um
18:07:

**Comment by radek8** [comment]
Attention TFT28 is in two versions. Did you use the correct version?

**Comment by Stellarspace** [comment]
> Attention TFT28 is in two versions. Did you use the correct version?

It says TFT28 v1.0 in the Info section on the 3D Printer so I thought it would be v1.0 still.

**Comment by digant73** [comment]
You have to use mks32 v1.4 for your tft

**Comment by Stellarspace** [comment]
> You have to use mks32 v1.4 for your tft

Okay, thanks. I'll try it.

**Comment by oldman4U** [comment]
@traffic-light 

Maybe something for your ReadMe?
