### ISSUE TITLE
Multiple Icon Profiles

### ISSUE THREAD

**Issue by Sthopeless** [bigtreetech/BIGTREETECH-TouchScreenFirmware#121]
Hello everyone! 

Recently I see here and on facebook a lot of users releasing pack of icons for the TFT's.
And instead of having to 'reflash' everything I want to change icons pack, would it be possible to integrate them all in the firmware and choose which one to use directly on the TFT?

**Comment by guruathwal** [comment]
That would need a lot of storage space.
The TFTs have very limited flash storage.

**Comment by Hukuma1** [comment]
Is there a reason the icons aren't crushed PNGs instead of BMPs?

Did a quick test:
BackGroundColor.bmp = 28,672 bytes
BackGroundColor.png = 8,192 bytes

So in theory we could probably have 3X icons/different packs using the same space we do now with BMPs for 1 set.

**Comment by Sthopeless** [comment]
cant the images be saved and load from the sdcard and only have loaded the package se choose?!

**Comment by guruathwal** [comment]
> Is there a reason the icons aren't crushed PNGs instead of BMPs?
> 
> Did a quick test:
> BackGroundColor.bmp = 28,672 bytes
> BackGroundColor.png = 8,192 bytes
> 
> So in theory we could probably have 3X icons/different packs using the same space we do now with BMPs for 1 set.

Yes there are reasons.
First the Flash storage used in these devices is not like the normal SD card or USB drive. each file is stores as binary data in the form of bytes.
These flash storage do not have any file system to handle files.
The image data is read by specifying the starting byte address and the total byte counts with just few lines of coding. This is where BMP is used.
BMPs always have the same file size for specific dimensions. changing the color or design does not affect the size. In short BMP is uncompressed image.
Other formats like JPG, PNG, GIF etc. are compressed image format. File size will change if just one pixel is changed, making it difficult to track the data location for each image and will result in just garbage.

**Comment by guruathwal** [comment]
> cant the images be saved and load from the sdcard and only have loaded the package se choose?!

The software will crash when you will remove the sd card for copying gcode files as there will be no storage to load data from.

**Comment by Sthopeless** [comment]
> > cant the images be saved and load from the sdcard and only have loaded the package se choose?!
> 
> The software will crash when you will remove the sd card for copying gcode files as there will be no storage to load data from.

I see, but wouldn't be possible for example have all the icon packs in different named folders on the sdcard and on the TFT when we choose which pack to use the 'software' loads into it the necessary image?!

**Comment by thisiskeithb** [comment]
> I see, but wouldn't be possible for example have all the icon packs in different named folders on the sdcard and on the TFT when we choose which pack to use the 'software' loads into it the necessary image?!

This is how I envisioned initial support for this feature could work (a select a pack from SD card and reboot to load it).

**Comment by guruathwal** [comment]
> I see, but wouldn't be possible for example have all the icon packs in different named folders on the sdcard and on the TFT when we choose which pack to use the 'software' loads into it the necessary image?!

how hard can it be? may be possible like this:
1. copy icon packs in seperate folders (TFT35/Pack1 , TFT35/Pack2, TFT35/Pack3)
2. list all packs in a menu
3. select a pack
4. renames old selection to Pack4 (like "TFT35/BMP" to "TFT35/PACK4")
5. renames new selection to default icon folder(like "TFT35/PACK1" to "TFT35/BMP")
6. Reset to apply new pack.

**Comment by thisiskeithb** [comment]
Now that I know PIO Core 4.0.3 can generate working firmware (4.1 won't), I will be able to work on this some more over the weekend.

I think improving the file selection interface would tie in nicely to this request.

**Comment by Sthopeless** [comment]
@thisiskeithb on my TFT35 v2.0 I dont see a option to babystep if I am printing through Octoprint maybe we could have babystep somewhere all the time for when we are printing throught Octoprint.

maybe we could have have a few configurable pages that we could define which gcode each button sends, something like this:
![67166538_702288623531339_5299916680359575552_n](https://user-images.githubusercontent.com/6695214/68504118-a1a2af00-0264-11ea-8f11-0d214a42f36f.jpg)

**Comment by Sthopeless** [comment]
Also awhile ago I saw this picture 
![75375602_2129999540628306_3289178649260982272_n](https://user-images.githubusercontent.com/6695214/68504466-4e7d2c00-0265-11ea-911a-d218941f0e3e.jpg) couldn't something like this be done and enabled TFT35 v2.0 to also have the 12864 emulator? There should be enough pins available to connect to our boards

**Comment by guruathwal** [comment]
> @thisiskeithb on my TFT35 v2.0 I dont see a option to babystep if I am printing through Octoprint maybe we could have babystep somewhere all the time for when we are printing throught Octoprint.
> 
> maybe we could have have a few configurable pages that we could define which gcode each button sends, something like this:
> ![67166538_702288623531339_5299916680359575552_n](https://user-images.githubusercontent.com/6695214/68504118-a1a2af00-0264-11ea-8f11-0d214a42f36f.jpg)

I think @Msq001 is already working on it. He has added a custom option in the 'MachineSettings.c' in PR #91 , but it is not complete yet.
@Msq001 please confirm?

**Comment by Msq001** [comment]
> > @thisiskeithb on my TFT35 v2.0 I dont see a option to babystep if I am printing through Octoprint maybe we could have babystep somewhere all the time for when we are printing throught Octoprint.
> > maybe we could have have a few configurable pages that we could define which gcode each button sends, something like this:
> > ![67166538_702288623531339_5299916680359575552_n](https://user-images.githubusercontent.com/6695214/68504118-a1a2af00-0264-11ea-8f11-0d214a42f36f.jpg)
> 
> I think @Msq001 is already working on it. He has added a custom option in the 'MachineSettings.c' in PR #91 , but it is not complete yet.
> @Msq001 please confirm?

yeah. The purpose is that user can customize the gcode to be sent and the name of the button in the configuration. h file. I'm doing this now,  And I will write some documents to explain the screen firmwre in detail including how to add languages, customize fonts, customize icons, and explain the effect of each option in configuration. h

**Comment by Msq001** [comment]
> @thisiskeithb on my TFT35 v2.0 I dont see a option to babystep if I am printing through Octoprint maybe we could have babystep somewhere all the time for when we are printing throught Octoprint.
> 
> maybe we could have have a few configurable pages that we could define which gcode each button sends, something like this:
> ![67166538_702288623531339_5299916680359575552_n](https://user-images.githubusercontent.com/6695214/68504118-a1a2af00-0264-11ea-8f11-0d214a42f36f.jpg)

I will add "BabyStep" in "MachineSetting", Thank you for your advice

**Comment by Sthopeless** [comment]
That's all great news, thank you a lot guys!

Please think dearly about enabling 12864 emulation on other TFT's that have enough pins available. BTT Legend really deserves it.

Also is there any way to make the touch screen aware that the printer is printing or being used thought Octoprint?!

**Comment by hapklaar** [comment]
> That's all great news, thank you a lot guys!
> 
> Please think dearly about enabling 12864 emulation on other TFT's that have enough pins available. BTT Legend really deserves it.
> 
> Also is there any way to make the touch screen aware that the printer is printing or being used thought Octoprint?!

That would be great and maybe a starting point for giving the TFT mode a proper 'live' status screen? Not sure if this is even possible, would love some insight from you guys as development for this TFT seems at an all-time high at the moment.

**Comment by thisiskeithb** [comment]
[This Touch UI thread](https://github.com/MarlinFirmware/Marlin/issues/10008) would be a good read related to Marlin/LCDs/TFTs.

If there’s a way to help drive a new (better) standard, then I think it’d be worth pursuing.

**Comment by Sthopeless** [comment]
If your printer only has touchscreen mode and you use Octoprint it can be very frustrating at times :)

Stop button on the TFT doesn't stop the print (only reset) and once turned off the heating of my hotend and bed and kept printing until the extruder started grinding on the dry filament but most of the time just stops homes and starts the print again from 0 on top of the old print.

Babystepping is always fun.. if you start the print from the tft sdcard (i never tried from the board sdcard) babystep function is there but is never happening on real time and if it is a big print sometimes I have to wait long time to see it changing, causing me sometimes to just have to restart the print. 
I cannot save the value so every time i reboot the printer is gone and most of times I forget to set it before starting the print..

Through octoprint the function is not there. there is now a gcode console but i think it still needs some improvements to be used

**Comment by guruathwal** [comment]
> If your printer only has touchscreen mode and you use Octoprint it can be very frustrating at times :)
> 
> Stop button on the TFT doesn't stop the print (only reset) and once turned off the heating of my hotend and bed and kept printing until the extruder started grinding on the dry filament but most of the time just stops homes and starts the print again from 0 on top of the old print.
> 
> Babystepping is always fun.. if you start the print from the tft sdcard (i never tried from the board sdcard) babystep function is there but is never happening on real time and if it is a big print sometimes I have to wait long time to see it changing, causing me sometimes to just have to restart the print.
> I cannot save the value so every time i reboot the printer is gone and most of times I forget to set it before starting the print..
> 
> Through octoprint the function is not there. there is now a gcode console but i think it still needs some improvements to be used

The stop button on TFT sends a emergecy stop Gcode "M112" to the printer. you need to enable `EMERGENCY_PARSER` for an instantaneous M112 command or else it will wait for the command  queue to clear.

Babystepping on TFT works by sending the gcode to the printer.  it will also wait for the command  queue to clear.

**Comment by Sthopeless** [comment]
@guruathwal thanks! actually i did not know about having to enable ```EMERGENCY_PARSER``` for it to work properly!

About the babystepping I had that figured already, which makes me wonder if a display sending gcode that's queued in line is the 'way to go' for a viable display.

**Comment by guruathwal** [comment]
> @guruathwal thanks! actually i did not know about having to enable `EMERGENCY_PARSER` for it to work properly!
> 
> About the babystepping I had that figured already, which makes me wonder if a display sending gcode that's queued in line is the 'way to go' for a viable display.

for the babystepping there should be hard wired buttons connected directly to the main board. i don't know why no one has tried to implement that.

**Comment by Sthopeless** [comment]
sorry i dont think adding wired buttons is a solution, more as a 'hack around to get it working'

Wouldn't it be a better solution to 'redesign' the firmware's make it integrated with Marlin's (has a real LCD option we enable on Marlin) and make it only 1 firmware where we define if there is external rotary encoder or buttons in screen etc, the emulator doesn't need to be a emulator and all can be just one thing across all TFT's, Isn't something like this possible and more functional?

**Comment by guruathwal** [comment]
Redesigning firmware for the TFT from almost scratch is a long way to go.

**Comment by Sthopeless** [comment]
@guruathwal I understand that. But maybe inspiration can be taken from TFT's like from Prusa(?)

Anyhow I know that is a big shoot...

I gave some thoughts about the 'icons profiles' and maybe it could be done like this,
We have a folder on TFT SDCard for the icons profiles with a main picture for each profile and file name of the "Icon Pack"(maybe a preview of the icon pack) something like this:
![72266339_10220816220259828_3589457744412803072_n](https://user-images.githubusercontent.com/6695214/68543871-1a1c8380-03bd-11ea-9207-0ed6e9f465a7.jpg)

Then everytime the TFT reboots would look into that folder see how many pictures/'icon packs' there are list them with the main picture name (without .bmp or whatever extension is used) and when clicked we'd see the main picture and a 2 options "cancel" which would go back to the icons pack select menu or appy that would reboot the tft and copy the necessary icons fonts etc into the memory 

'Main Picture' and 'Icons Pack folder' can maybe have the same name so the TFT knows which folder to copy.

This would also give us a option to also preview a little the packs before applying and would allow to add/remove more in the future without major changes in the firmware

**Comment by Chaumezz** [comment]
Hola!   Me parece muy interesante este hilo, pero la comunicacion de la TFT siempre van a tener que pasar por el serial y no va a ser directamente sobre el manejo de la placa.
Me gustaria saber donde encontrar packs de iconos para la TFT35 para renovar su aspecto.
Gracias!
