### ISSUE TITLE
[FR] Move X, Y, and Z Axes While Paused

### ISSUE THREAD

**Issue by Stellarspace** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1211]
**Is your feature request related to a problem? Please describe.**
If the end-user would like to switch to a filament with a different color and/or material while the printer is on paused, the filament could end up extruding on the incomplete printed object. This also applies to when the end-user runs out of filament.

**Describe the solution you'd like**
The end-user should have access to the Move menu to move the extruder and/or bed. Confirmation as POPUP might be required as moving the extruder and/or bed while the print is on pause could be destructive in certain situations.

**Additional context**
A user by the name of [caroloking](https://www.thingiverse.com/caroloking/designs) on Thingiverse suggested this feature.

**Comment by Stellarspace** [comment]
I didn't realize this is M600.

**Comment by bigtreetech** [comment]
Hello, It sounds like adding babystep to the XY axis?

**Comment by radek8** [comment]
I think that in Marlin it can be set, when printing is paused (for example to change the thread), the head is parked in the specified place. When the pause is canceled, the print returns to its original position.

**Comment by Stellarspace** [comment]
> Hello, It sounds like adding babystep to the XY axis?

You could say that.

> I think that in Marlin it can be set, when printing is paused (for example to change the thread), the head is parked in the specified place. When the pause is canceled, the print returns to its original position.

When printing is paused, it already parks in a specific place, but for some reason, caroloking wanted access to the Move menu while paused as well. There is also M600, which has to be manually typed into the Terminal menu.

**Comment by oldman4U** [comment]
Personally there are FR's where I can not see why I would need it and this is one of theses requests. Anyway, it is for sure more important then the ability to execute PID and Steps tuning WHILE printing, so I added this FR to the FR list.

If it is OK for you, it would be great if you could close this ticket.

Thank you

**Comment by oldman4U** [comment]
👍🏻

Stellarspace <notifications@github.com> schrieb am Mi. 4. Nov. 2020 um
21:25:

**Comment by digant73** [comment]
@oldman4u the parking area is configurable on both marlin and TFT now. Once paused by TFT the user can move to the extruder/(un)load menus etc._. so this FR is already implemented and could be removed from the list. Furthermore this FR was not even requested by the user that opened the FR that simply reported the thougth of another user that cannot even clarify his/her use caseses
