### ISSUE TITLE
Invalid Value Temperature at 475 degrees for Mosquito Hotend

### ISSUE THREAD

**Issue by Matdos** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1217]
I have installed a Mosquito Hotend and want to set the maximum temperature of 450 degrees, but the error message Invalid Value appears. 

How can I set this?
![09671030-4390-432B-9A1F-F3F8CF05832E](https://user-images.githubusercontent.com/51334337/97636707-cd9cde80-1a39-11eb-8bb1-5d158f837583.jpeg)

**Comment by oldman4U** [comment]
Hi.

It is always helpful to attache the config files here.

**Comment by Matdos** [comment]
I dont now what is the problem.

[config.docx](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5467735/config.docx)

**Comment by GregSKR** [comment]
Currently, temperatures over 300°C are not allowed:
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/blob/8a5b9a1ccb0f3c2d3f6b2d14bfdd2e015a6ea0c8/TFT/src/User/API/config.h#L154

If you compiled the firmware youself, change the value to **500** (max temp for mosquito hotends).

You should create a PR for this... :wink:

**Comment by Matdos** [comment]
hello, thanks a lot, I didn’t find it, I habe search for more than 4 hours.
