### ISSUE TITLE
[BUG]Touchscreen not responding after update, TFT43

### ISSUE THREAD

**Issue by rennwaffen** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1233]
### Description

I had just updated my newly acquired TFT43. The touch screen was working before the update. After the update, the touchscreen stopped working. The wiring wasn't changed, and the screen isn't in a case to be pressing on the edges. Also, the LED for the knob is not working, even though it's configured to power on when the printer is on. 

### Steps to reproduce

1. Install firmware
2. Power on printer
3. Touch screen not working

**Expected behavior**
Touch screen to work and knob LED to light up

**Actual behavior**
Touch screen doesn't work and knob LED doesn't light up

### Hardware Variant
TFT43
### TFT Firmware Version & Main Board Firmware details
Marlin 2.0.5.3 and TFT 3.0.26

**Comment by blueeagle69** [comment]
Hi.

Try placing a Reset.txt file on your TFT SD to see if that fixes it.

**Comment by rennwaffen** [comment]
> Hi.
> 
> Try placing a Reset.txt file on your TFT SD to see if that fixes it.

I actually don't have the reset.txt file, and I didn't get an sd card with my display. Is it available on GitHub?

**Comment by oldman4U** [comment]
There is s readme at the main page. Please read it and come back if it does not help. 

Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by rennwaffen** [comment]
Placed a blank text file in the sd card and named it "reset". This helped recalibrate the display and solve the issue. Thanks!

**Comment by blueeagle69** [comment]
> Placed a blank text file in the sd card and named it "reset". This helped recalibrate the display and solve the issue. Thanks!

Good to hear!

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Bin mir nicht ganz sicher, weshalb du mir einen Daumen runter gibst, wenn ich dich dazu auffordern muß etwas zu tun, was eigentlich selbstverständlich sein sollte.
