### ISSUE TITLE
[Q] Bootloader for TFT70

### ISSUE THREAD

**Issue by soul1988** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1239]
Hi, I have a TFT70 with a faulty CPU. I replaced the CPU with a new one. Is it possible to get a bootloader for TFT70?

**Comment by oldman4U** [comment]
I am just curious to know- why do you replace the CPU of a hardware which is clearly under warranty?

**Comment by soul1988** [comment]
Because I was the one who damaged it, and now I'm trying to repair it.

**Comment by oldman4U** [comment]
Ok. 👍🏻

soul1988 <notifications@github.com> schrieb am Mo. 9. Nov. 2020 um 17:20:

**Comment by darkspr1te** [comment]
i'am not 100% sure of the cpu/pinouts of the 7inch screen but i have two bootloaders that work with mkstft and btt tft screens, if your device is different it should not take much to port to the device.

**Comment by soul1988** [comment]
I have burned the bootloader for the TFT50 that made the screen work, but the touchscreen does not work. STM32F407VGT6
The processor on this screen is the STM32F407VGT6, I don't know if those bootloaders are compatible, but I can try and see if it works.

**Comment by darkspr1te** [comment]
this bootloader is for the stm32f407 https://github.com/darkspr1te/mkstft35_V1_open_bootloader , in mks circles it works on the 3.5/7 , not sure about the 5" ,

**Comment by radek8** [comment]
> I have burned the bootloader for the TFT50 that made the screen work, but the touchscreen does not work.
> The processor on this screen is the STM32F407VGT6, I don't know if those bootloaders are compatible, but I can try and see if it works.

Did you try to reset the touch layer?
Upload an empty reset.txt file to the SD

**Comment by oldman4U** [comment]
Any news?

**Comment by soul1988** [comment]
Ok, is working now.
I just had to rename the files From TFT70 to TFT50 with the bootloader of TFT50.

**Comment by darkspr1te** [comment]
@soul1988. If the issue is resolved, could you close this issue.

**Comment by radek8** [comment]
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/discussions/1596#discussioncomment-2935828
