### ISSUE TITLE
[Q] 8.3 file names on TFT35 printing screen when print from board SD

### ISSUE THREAD

**Issue by lompyka** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1245]
On the print screen top left corner I can see only the current gcode file in 8.3 format when I print from the motherboard's SD card. In the file list when I browsing the sd for the *.gcode the long filenames are appears but when I choosing one in the popup window also the 8.3 format appears and then on the printing screen too.

I'm using a TFT35 v3.0 with latest master branch FW (TFT35, firmware, lang, config.ini are updated to latest)
and SKR v1.3 with latest bugfix-2.0.x FW

in config.ini:
long_filename_support:2
in board Configuration_adv.h:
#define LONG_FILENAME_HOST_SUPPORT
#define SCROLL_LONG_FILENAMES

What else am I set for display long file names everywhere?
Thanks
![20201114_123716](https://user-images.githubusercontent.com/58642873/99146241-8daf3b80-2676-11eb-84ad-1854ccf8aa45.jpg)

**Comment by blueeagle69** [comment]
Hi.
Unfortunately it's a known issue.
At the moment, when printing from the onboard SD you will see long filenames in the file list, but short 8.3 when printing etc.
I hopeful that some clever soul will find the answer.

**Comment by oldman4U** [comment]
I add this to the known issues list.

Thank you for reporting this, you can close the ticket if you want.

**Comment by kisslorand** [comment]
Check PR #1488.

**Comment by oldman4U** [comment]
Or #1487

**Comment by kisslorand** [comment]
> Or #1487

That's not complete, it is not taking in account if printing from USB host and onboard SD hence wrong filename is shown and it is not showing long filename in filament statistics.

**Comment by guruathwal** [comment]
@kisslorand  #1488 is still using +4bytes of RAM

**Comment by kisslorand** [comment]
My VSCode tells me otherwise. Compiling "master" branch and compiling PR #1488 yields the exact same RAM usage.

**Comment by guruathwal** [comment]
@kisslorand  check again

**Comment by kisslorand** [comment]
OK. I just checked again. Same results, 0 (ZERO) extra RAM usage.

![Master_vs_Longfile](https://user-images.githubusercontent.com/50251547/104122570-66ab7800-534e-11eb-96ea-77033715a3b2.jpg)

**Comment by guruathwal** [comment]
There is clearly something wrong in the calculation for MKS28

![master](https://user-images.githubusercontent.com/22422544/104123159-74252a00-536f-11eb-870a-34de189b1ae6.jpg)
![pr1488](https://user-images.githubusercontent.com/22422544/104123166-7a1b0b00-536f-11eb-9520-c264cf802565.jpg)

**Comment by kisslorand** [comment]
> There is clearly something wrong in the calculation for MKS28

... or in the calculation for the other TFT or you are checking against the wrong master.

**Comment by kisslorand** [comment]
> Or #1487

That PR added some more bugs, go figure! Nice tip @oldman4U ;)

**Comment by carryreynolds** [comment]
The misreporting of reduced RAM usage is being caused by `"\a"` in `FILAMENTDATA filData = {"\a", 0, 0, 0, 0};` in PrintingMenu.c line number 39 in #1488. The `\a` is escape sequence for `BEL` character with ASCII index of 7 which is used to play beep sounds on computers. In this case, for some devices, the character is not being interpreted correctly by the compiler.

**Comment by kisslorand** [comment]
Almost... Replace "\a" with "???", or "abcdefgh" or whatever else you like and check the compiled size again.

**Comment by carryreynolds** [comment]
replace `"\a"` with `""` and see the result

**Comment by kisslorand** [comment]
FILAMENTDATA filData = {"", 1, 0, 0, 0}; and check ;)

**Comment by oldman4U** [comment]
Hello @lompyka

As of today, the reported issue is solved and therefore removed from the FR list. Please install the master firmware to solve the reported issue.

Happy printing
