### ISSUE TITLE
[Q] On TFT35 V3.0 the layer remains on 0.00 during print when I print from board SD

### ISSUE THREAD

**Issue by lompyka** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1248]
On the printing screen when I print from motherboard SD the Layer is remain on 0.00 mm, if I print from TFT-SD the layer is growing during the print.

I'm using a TFT35 v3.0 with latest master branch FW (TFT35, firmware, lang, config.ini are updated to latest)
and SKR v1.3 with latest bugfix-2.0.x FW

Am I need to set something in the board's marlin fw or in the TFT firmware or it is a bug?

Thanks

![20201114_123716](https://user-images.githubusercontent.com/58642873/99149153-93178080-268c-11eb-85d0-d87b55ff52e0.jpg)

**Comment by abacabie** [comment]
Yip, i think this is well known, its never worked for me.

**Comment by oldman4U** [comment]
Please see the pinned Feature Request ticket. 

Please help the community and close the ticket once you do not need it anymore. Thank you
