### ISSUE TITLE
TFT 24 V1.1 on a GT2560

### ISSUE THREAD

**Issue by Halefopa** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1250]
Is it possible to use the TFT24 V1.1 display on a GT2560 (3D printer board)?
Is there any firmware for this combnation?
Normal the GT 2560 is used by the LCD 12864 / LCD 2004.

![GT2560 Board](https://user-images.githubusercontent.com/49936514/99184790-c4a05280-2745-11eb-9a1a-0589fa621b0b.png)
![GT2560 LCD](https://user-images.githubusercontent.com/49936514/99184792-c702ac80-2745-11eb-9e8d-abb3ab5edfbc.png)
![GT2560 SD Card](https://user-images.githubusercontent.com/49936514/99184793-c9650680-2745-11eb-8403-15e55f3fc9af.png)
![PIN setup TFT24 EXP](https://user-images.githubusercontent.com/49936514/99184848-3c6e7d00-2746-11eb-9835-4ed668115b78.png)

**Comment by radek8** [comment]
This board does not have pins on the serial interface.
So only the simulated Marlin mode will work for you.
For touch mode you will have to solder and it will be to your risk

https://arduino.stackexchange.com/questions/39414/where-are-rx-and-tx-pins-on-the-gt2560

**Comment by radek8** [comment]
Depending on the connection, additional RX and TX outputs are output on the LCD connector. They might go to use but will need to edit the PINout file in Marlin
![image](https://user-images.githubusercontent.com/46979052/99189257-a005a400-2760-11eb-825c-80a9d66ce97b.png)

**Comment by Halefopa** [comment]
Thank you radek8 for your prompt reply.
The Iformatons were very helpful.
At the moment I'm still looking for a suitable Marlin firmware that I can modify for this Projekt (GT2560 + TFT 24 V1.1).

**Comment by oldman4U** [comment]
Hello.

What is the status of this ticket?

Please close it once you do not need it anymore.

Thank you

**Comment by Halefopa** [comment]
Hey,

No there is a remaining problem...

Status: 
+ I think, the GT2560 and TFT24V1.1 are wired correctly.
+If I plug in the USB-cable of the GT2560, first the System starts updating.
+ after the update it loading all icons.

- but... after loading the Icons, I getting the message:

![Error message](https://user-images.githubusercontent.com/49936514/99398144-4a5a0480-28e4-11eb-976d-72fa54ddf24c.png)

I m naot sure you can read that, that message calls:

"Found outdated data:
 Config: Update required
 Icons: Update required
Insert the SD card with the required files and press the reset button to update."

So now I have to fix that problem, but at the Moment i have no idea how to do that.
Thats the Firmware on SD-Card:

![Firmware setup](https://user-images.githubusercontent.com/49936514/99403349-a6c02280-28ea-11eb-9fd6-b0959625e99c.png)

(https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware)

Can anyone help to fix that?

**Comment by radek8** [comment]
Read the manual on the title page !!!

A config.ini file with your configuration is required.
download config.ini and customize to your needs.
copy to SD card and paste to TFT.

**Comment by Halefopa** [comment]
Ok thanks,

just the icon-error-message is left.
I found no setting in config.ini to fix that.
Can you tell me the concerned file / setting, to fix that last error?

**Comment by oldman4U** [comment]
Do the same with tft24 folder. 

Have you read the readme?

**Comment by radek8** [comment]
Use this BIN file :-)
[BIGTREE_TFT24_V1.1.26.x.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5556072/BIGTREE_TFT24_V1.1.26.x.zip)

**Comment by radek8** [comment]
Exposed bin files are 2 months out of date and not compatible with BMP files.

**Comment by Halefopa** [comment]
It works!

Thank you so much radek8! for all your helpfull comments and the final .bin!

I'm so happy if I meet helfull people like you in a Forum.

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you 

radek rules😁

**Comment by oldman4U** [comment]
@Halefopa 

Please close this ticket by pressing the Close button at the bottom of this ticket. This will help us to maintain this ticket system and therefore to help other users like we helped you.
