### ISSUE TITLE
[BUG] TFT 35 Touch slow respondig - SKR Mini E3 V2.0

### ISSUE THREAD

**Issue by KVC87** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1266]
Hello,

I have a SKR Mini E3 V2 with the TFT 35 Touchscreen.

Some features have slow reaction, if i press the fan to go on or off, it takes about a minut to go on or of. Also with the move > home en stof or pause button, i takes time to stop.

Temperatue from nozzle and bed goes directly.

Is this normal?

**Comment by oldman4U** [comment]
Which firmware versions?

Any hint why you believe it is TFT and not SKR related?

**Comment by KVC87** [comment]
> Which firmware versions?
> 
> Any hint why you believe it is TFT and not SKR related?

The latest one, but somer research made me do think that when you send the command,the code have to wait in line...

**Comment by oldman4U** [comment]
Send a picture of Menu - Settings - Info.

Stop and Pause has to clear the buffers first, so this depends on the buffer settings. Fan should change immediately, or at least it should not take a minute.

**Comment by KVC87** [comment]
![Uploading E9CDAB4D-AE39-4DC2-83AD-D5D41FE89DDD.jpeg…]()

**Comment by oldman4U** [comment]
Please let the Upload end before you click on Comment.

**Comment by KVC87** [comment]
![EEE3FDFF-6993-4978-BB53-06D4B54CC4BB](https://user-images.githubusercontent.com/74624246/99593042-554e8b00-29f1-11eb-9569-55e179d05898.jpeg)

**Comment by oldman4U** [comment]
Please follow the update description from here:
https://github.com/oldman4U/BIGTREETECH-TouchScreenFirmware - scroll down on the page -
using the firmware from here:
https://github.com/radek8/BIGTREETECH-TouchScreenFirmware/tree/updateBIN

**Comment by KVC87** [comment]
Thanks, I will update it right now and make a print to see if this works out.
I

**Comment by oldman4U** [comment]
Wonderful.

**Comment by KVC87** [comment]
Owkay, its faster. Bu it is also a smaller print. I see when i push to start the fan sometimes its start after 5 seconds sometimesafter 10. So i think its more thathe is waiting in line.

**Comment by oldman4U** [comment]
You will have to change the RT and TX buffers in Marlin firmware for faster response.

Are you printing from SD card of the mainboard or from something connected to TFT?

**Comment by oldman4U** [comment]
Any news?

**Comment by KVC87** [comment]
I’m printing from the sd slot on the screen. The slot on the board is not accesible because i build it onther case. 

Their is still a little delay, but not that long i can live with it 😀
![A3DF80D9-4B9F-4E7C-898F-471B45C72F9F](https://user-images.githubusercontent.com/74624246/99870889-b71c1a00-2bd6-11eb-9cb6-f8fa93b7d98b.jpeg)

**Comment by oldman4U** [comment]
A little delay is normal.... as long as it is less than a minute;-)

Please close this ticket.

Happy printing
