### ISSUE TITLE
[BUG] No response displayed for M503 in Terminal (Response ~2500 characters)

### ISSUE THREAD

**Issue by kisslorand** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1267]
### Description

When an M503 gcode is issued in Terminal there's no response shown. Actually only the last few characters are shown:
cho: M410 S1
OK P:15 B:15

### Steps to reproduce

1. [Open Terminal]
2. [Type M503]
3. [Press Send]

**Expected behavior**

The full response for M503

**Actual behavior**

Only the last few characters are shown:
Rcv: cho: M410 S1
Rcv: OK P:15 B:15

### Hardware Variant

MKS TFT clone on Artillery Sidewinder X1 with SKR 1.4Turbo mainboard
### TFT Firmware Version & Main Board Firmware details
TFT FW: 0.0.26.1, Marlin 2.7.2

### Additional Information

When M503 S0 is issued the response is full.

**Comment by radek8** [comment]
I can confirm this behavior.

@digant73 
Was the output on the M503 command terminal suppressed in your last PR?

**Comment by radek8** [comment]
Comment on these 3 lines.
It might help ....

![image](https://user-images.githubusercontent.com/46979052/99455022-86628900-2927-11eb-8fa9-a4da338fad41.png)

**Comment by kisslorand** [comment]
Would be easier to allow "knownEcho" to be shown in terminal, I just cannot find a way to do it.

**Comment by radek8** [comment]
I wrote that to you

**Comment by kisslorand** [comment]
In "menu.c"  "parseACK()" is called where "syncL2CacheFromL1(SERIAL_PORT)" fills "dmaL2Cache". The "knownEcho" elements must be removed somewhere from "dmaL2Cache" since they are not shown in terminal.

**Comment by radek8** [comment]
Unfortunately, I won't help you anymore.

**Comment by kisslorand** [comment]
It is not about me.

**Comment by radek8** [comment]
I can't help, this is where my knowledge ends :-(

**Comment by digant73** [comment]
no changes were made on Terminal related to gcode handling. Also M503 correctly works on my side (5 pages of output)

**Comment by kisslorand** [comment]
M503 S0 works for me too, the plain M503 gives me trouble.
M503 gives a larger response than the "ACK_MAX_SIZE", M503 S0 gives a smaller response than "ACK_MAX_SIZE".

**Comment by oldman4U** [comment]
Looks like this on my TFT. ![image](https://user-images.githubusercontent.com/54359396/99509434-0c152180-2986-11eb-81ff-869b13765594.jpeg)

![image](https://user-images.githubusercontent.com/54359396/99509552-31099480-2986-11eb-816e-148129133c3e.jpeg)

![image](https://user-images.githubusercontent.com/54359396/99509635-4d0d3600-2986-11eb-92b7-53f3cfc2ab7e.jpeg)

**Comment by kisslorand** [comment]
From the pictures I can see it has much less response characters than in my situation. Also this TFT uses different MCU than mine. This one is with STM32F207 and mine has STM32F107. My TFT has no issue to display the response from M503 S0 which has around 1500 opposed to the ~2500 characters it gets from the simple M503 gcode (no S0 parameter).

**Comment by oldman4U** [comment]
So there is a problem with your TFT and others like mine work well. What is your screen size?

**Comment by kisslorand** [comment]
It is the original 2.8" TFT on the Artillery Sidewinder X1.
Radek8 also confirmed the behaviour I described.

**Comment by radek8** [comment]
I can confirm the same behavior as kisslorand.
But my HW is a TFT 35 E3 V3.0 like Oldman4U.

**Comment by radek8** [comment]
If I send the M503 command from the PC via Wifi, the response is correct and complete.

**Comment by oldman4U** [comment]
Can u send a picture?

Radek <notifications@github.com> schrieb am Mi. 18. Nov. 2020 um 15:03:

**Comment by radek8** [comment]
I'll send in the evening

**Comment by oldman4U** [comment]
Not sure how many characters it is, but on my TFT28 M503 gives me 6 pages
[IMG_7445.HEIC.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5561107/IMG_7445.HEIC.zip)

**Comment by radek8** [comment]
M503
![IMG_20201118_163020_resized_20201118_061130856](https://user-images.githubusercontent.com/46979052/99564418-b57e0680-29ca-11eb-95d9-a4057ac598ab.jpg)

**Comment by radek8** [comment]
M503 S0
![IMG_20201118_163053_resized_20201118_061130505](https://user-images.githubusercontent.com/46979052/99564476-cfb7e480-29ca-11eb-87b2-1f41fa38a7f8.jpg)
![IMG_20201118_163058_resized_20201118_061129921](https://user-images.githubusercontent.com/46979052/99564507-d9d9e300-29ca-11eb-8aff-d1a97b133fca.jpg)
![IMG_20201118_163105_resized_20201118_061130672](https://user-images.githubusercontent.com/46979052/99564531-e0685a80-29ca-11eb-8e8e-9536ffba8005.jpg)
![IMG_20201118_163112_resized_20201118_061130315](https://user-images.githubusercontent.com/46979052/99564549-e4947800-29ca-11eb-84b1-f70c94407382.jpg)
![IMG_20201118_163121_resized_20201118_061130997](https://user-images.githubusercontent.com/46979052/99564583-eb22ef80-29ca-11eb-8357-6609cd5fbc29.jpg)
![IMG_20201118_163131_resized_20201118_061130132](https://user-images.githubusercontent.com/46979052/99564596-ef4f0d00-29ca-11eb-8e76-c4543f734a72.jpg)

**Comment by kisslorand** [comment]
![M503](https://user-images.githubusercontent.com/50251547/99567921-6ee2d900-29d7-11eb-811c-010b436cb0f4.jpg)
Disregard the SmileyFace, it's from my phone.

**Comment by oldman4U** [comment]
Strange. So it works on my machine, but not on yours. I will test another machine and let you know...

**Comment by oldman4U** [comment]
Thats my SKR E3 DIP TFT35 E3 v3 based Ender 3.

![IMG_7446](https://user-images.githubusercontent.com/54359396/99643504-0d5d5180-2a4d-11eb-8f56-b196d7c4debd.jpeg)
![IMG_7447](https://user-images.githubusercontent.com/54359396/99643500-0b938e00-2a4d-11eb-97ed-eca44333c16d.jpeg)
![IMG_7448](https://user-images.githubusercontent.com/54359396/99643480-046c8000-2a4d-11eb-9b00-d23ace40f9c2.jpeg)
![IMG_7449](https://user-images.githubusercontent.com/54359396/99643516-11896f00-2a4d-11eb-8731-dde52b7282e9.jpeg)

**Comment by kisslorand** [comment]
What Marlin version are you on? 
I am on 2.7.2 bugfix.
I went as far with debugging as checking the "infoHost.rx_ok[SERIAL_PORT] " after sending "M503". It gets "true" only two times. I checked it in "parseACK.c" after "syncL2CacheFromL1(SERIAL_PORT);" (line 263).
Since it gets "true" only two times it is no surprise the terminal shows only two lines of response.

**Comment by oldman4U** [comment]
Marlin 2.0.7.2 from Oct. 22nd. I guess this is the date where this firmware version has been released officially.

I must say that I always use 115200 baud rate and set the TFT connection as the first serial connection and -1 or nothing as the second serial connection.

Let me know in case I can help somehow but must add, that I am no developer. So may it is more work for you to explain to me what I have to do, than the amount of work I can do;-)

**Comment by kisslorand** [comment]
Problem solved, the size of the response for M503 didn't fit the DMA and Terminal buffer. Solved it by enlarging those buffers.

**Comment by radek8** [comment]
May I ask a solution to the problem?
Thank you

**Comment by oldman4U** [comment]
@kisslorand 

Are you going to make a PR for this?

**Comment by kisslorand** [comment]
I fixed it for my printer, others might check if it is OK with theirs.
Here's the PR: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/1276

**Comment by radek8** [comment]
Good job.
It already works as it should :-)

![IMG_20201121_183144_resized_20201121_063406055](https://user-images.githubusercontent.com/46979052/99883819-148d8680-2c2a-11eb-9c4b-faa0a6b17b90.jpg)
![IMG_20201121_183214_resized_20201121_063406287](https://user-images.githubusercontent.com/46979052/99883823-16574a00-2c2a-11eb-9560-75c2d98438b5.jpg)
