### ISSUE TITLE
knob led tft35-E3 v3.0 it does not work

### ISSUE THREAD

**Issue by ivindor** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1271]
Hi I wanted to ask to see if someone can solve my problem.
I have an ender 3 pro with a skr 1.4 turbo and the tft35-E3 v3.0 and I can't get the button led to work.
I am attaching my configuration in case you can help me solve my problem, thank you very much.

[conf marlin 2.0.7.2.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5568496/conf.marlin.2.0.7.2.zip)
[conf tft35-E3 v.3.0.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5568515/conf.tft35-E3.v.3.0.zip)

**Comment by traffic-light** [comment]
That's strange. It should work.

You did turn in on in feature settings?
You can change the color over there

**Comment by radek8** [comment]
Compile your own FW.
The precompiled BIN file is 2 months out of date

**Comment by oldman4U** [comment]
@bigtreetech @Msq001 

Could you please take over support for all those users using several months old firmware because you are not able to merge PRs which are already available.

Thank you

**Comment by traffic-light** [comment]
The bin files should be removed and replaced with a good instructive readme. (That's my opinion)

**Comment by radek8** [comment]
Not every user is able to compile on their own

**Comment by oldman4U** [comment]
@ivindor 

The LED of the knob should work independent of your Marlin or TFT settings. Please take a picture from Menu - Settings - Info and also from Menu - Settings - Feature (go down two pages) and attach it here.

**Comment by Doyle4** [comment]
@ivindor You are not on your own, im trying to sort this also.

**Comment by oldman4U** [comment]
Then please add the same photos here.

**Comment by Doyle4** [comment]
![Uploading 8B6DE7DD-834D-4B3A-8771-652881588DFF.jpeg…]()

**Comment by Doyle4** [comment]
![1625FEB3-05E6-44AF-9929-A013DF0CE016](https://user-images.githubusercontent.com/65953502/99787336-87f2a380-2b17-11eb-8b67-bfda8f44b451.jpeg)

**Comment by Doyle4** [comment]
![0923A2C8-548D-42DF-801C-4BB7E8898AE2](https://user-images.githubusercontent.com/65953502/99787465-aeb0da00-2b17-11eb-8aa3-2bfa20ca0d4a.jpeg)

**Comment by oldman4U** [comment]
OK.

No idea what it could be.

If you want you can make the final test by removing all cables from the TFT, cut a USB cable and connect the red wire to 5V and the black wire to GND of the TFT to see if it works then.

**Comment by Doyle4** [comment]
If the little trick works, this could mean the led can power on if the LCD was connected to a PSU as it has the option.

I find it odd, on my SKR 1.4T the LED worked fine, I wonder if it has to do with my board

**Comment by Doyle4** [comment]
![2E021EF9@7C426C58](https://user-images.githubusercontent.com/65953502/99792000-5e894600-2b1e-11eb-8218-ebf82ce57296.jpg)

**Comment by Doyle4** [comment]
![2E021EF9@7C426C58](https://user-images.githubusercontent.com/65953502/99792053-75c83380-2b1e-11eb-8dc5-51feb45f549d.jpg)

**Comment by traffic-light** [comment]
I think I know what happened. Can you dissable rotary knob idle and restart the screen?

**Comment by Doyle4** [comment]
How would I disable it sorry?

**Comment by Doyle4** [comment]
Changed Rotary knob idle LED to on, restarted screen, after reboot is was off, no LED function still

**Comment by traffic-light** [comment]
![image](https://user-images.githubusercontent.com/37051137/99792541-85984580-2b27-11eb-9b84-6eef7bbfe0be.png)
the one on the bottom

**Comment by Doyle4** [comment]
Tried with a LED colour set, enabled, restarted.

This time it stayed set to on and LED colour showed Blue, still no function.

**Comment by oldman4U** [comment]
No.

This only shows if the TFT works properly or not.

Doyle4 <notifications@github.com> schrieb am Fr. 20. Nov. 2020 um 11:51:

**Comment by Doyle4** [comment]
Not sure if helps, but the problems started when I installed it onto my MKS SGEN L V2.0 (2020 edition)

**Comment by traffic-light** [comment]
> Tried with a LED colour set, enabled, restarted.
> 
> This time it stayed set to on and LED colour displayed set to Blue, still no function.

Did you try disable the Rotary Knob LED idle? (red dot next to it)

**Comment by Doyle4** [comment]
yeah, tried both methods :(

**Comment by radek8** [comment]
nemůže ten rámeček krytu bránit šíření světla LED diody kolem hřídele knoflíku?

**Comment by Doyle4** [comment]
It could do for sure, but the enclosure I have for mine was designed to have the LED light shine through

**Comment by ivindor** [comment]
I have compiled again with the most recent fimrware and I put the config knob on but it still does not turn on I attach photos and the config for you to review
![WhatsApp Image 2020-11-20 at 15 52 37](https://user-images.githubusercontent.com/70163648/99813880-84c3db80-2b48-11eb-8664-68418fcb8095.jpeg)
![WhatsApp Image 2020-11-20 at 15 52 36 (1)](https://user-images.githubusercontent.com/70163648/99813903-8b525300-2b48-11eb-87d1-4d7b31816bc1.jpeg)
![WhatsApp Image 2020-11-20 at 15 52 36](https://user-images.githubusercontent.com/70163648/99813922-8f7e7080-2b48-11eb-84cc-f0ab94eb7098.jpeg)

**Comment by ivindor** [comment]
plug it into an external source and it still doesn't work.
I also put a multimeter on the knob LEDs and they pass 4.98v


![WhatsApp Image 2020-11-20 at 16 05 01](https://user-images.githubusercontent.com/70163648/99815156-3a435e80-2b4a-11eb-8e0a-b57dadf2096b.jpeg)
![WhatsApp Image 2020-11-20 at 16 05 14](https://user-images.githubusercontent.com/70163648/99815163-3c0d2200-2b4a-11eb-83d0-b40d578cb73d.jpeg)

**Comment by oldman4U** [comment]
Works on my TFT.

Have you tried to remove the TFT from the Ender 3 metal frame to see if it works then. Evergreen alarm;-)
![IMG_7451](https://user-images.githubusercontent.com/54359396/99832412-c6f91700-2b60-11eb-8119-b1e360303632.jpg)

**Comment by ivindor** [comment]
> Works on my TFT.
> 
> Have you tried to remove the TFT from the Ender 3 metal frame to see if it works then. Evergreen alarm;-)
> ![IMG_7451](https://user-images.githubusercontent.com/54359396/99832412-c6f91700-2b60-11eb-8119-b1e360303632.jpg)

I just tried it too and nothing does not light the led either

**Comment by oldman4U** [comment]
Ok. Guess this is a hardware related issue because i am not aware that the
TFT firmware can cause this.

Sorry

ivindor <notifications@github.com> schrieb am Fr. 20. Nov. 2020 um 18:55:

**Comment by Doyle4** [comment]
Could it be anything to do with Pins? on the SKR1.4T the Rotary LED worked.
Also whats different with the MKS SGEN L V2 is the pins for the black cable with 4 connections and 1 reset, on MKS there is no where for the reset connector.

Just a thought.

![Screenshot 2020-11-20 at 6 10 59 pm](https://user-images.githubusercontent.com/65953502/99834966-e477b200-2b5b-11eb-9b3b-688b5cd349e7.jpg)

**Comment by radek8** [comment]
Yes, on the MKS it is necessary to turn the connectors EXP1 and EXP2 by 180 °
There is no need to remap anything.
The EXP2 connector has a reset pin.
Even if you do not connect the reset pin to the RS232 connector, the reset will work.

**Comment by Doyle4** [comment]
One of mine is 180, if i do both it fails as a whole.

**Comment by radek8** [comment]
The ice on the rotary knob is switched by the processor.
so it has nothing to do with the type of board with Marlin.
Ice should be neopixel. The 4.98V power supply is OK.
The question is whether it is okay to wake them up.
Therefore, the diode may be defective or excited. you can't measure it with a voltmeter

**Comment by radek8** [comment]
> Jeden z mých je 180, pokud udělám obojí, selže jako celek.

You have to turn them both over, otherwise the Marlin mod won't work

**Comment by radek8** [comment]
What kind of display driver did you use in Marlin?
must be
#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

**Comment by radek8** [comment]
![image](https://user-images.githubusercontent.com/46979052/99838829-0415d700-2b6a-11eb-8610-59e381d31afa.png)

**Comment by radek8** [comment]
The LED at the knob is controlled by pin PC7
PC 7 is connected to connector EXP1
Therefore, if you connect it incorrectly (rotate 180 ° or connect to EXP2), the LED will not light up, or the input may be destroyed.

![image](https://user-images.githubusercontent.com/46979052/99840081-26a8ef80-2b6c-11eb-94f9-d17f8fbb2850.png)

**Comment by oldman4U** [comment]
@Doyle4 Tty the 5v and ground only and see if it works.

**Comment by ivindor** [comment]
> The LED at the knob is controlled by pin PC7
> PC 7 is connected to connector EXP1
> Therefore, if you connect it incorrectly (rotate 180 ° or connect to EXP2), the LED will not light up, or the input may be destroyed.
> 
> ![image](https://user-images.githubusercontent.com/46979052/99840081-26a8ef80-2b6c-11eb-94f9-d17f8fbb2850.png)
> 
> Connect the cables properly, if that doesn't help, take a picture of how you're connected and connect the marlin configuration.h

![WhatsApp Image 2020-11-20 at 20 20 21](https://user-images.githubusercontent.com/70163648/99841201-13971f00-2b6e-11eb-9a24-2f41b23b75e6.jpeg)
my tft only works in ext3 I don't know why it doesn't connect in ext1-ext2

**Comment by Doyle4** [comment]
Not manage to try the 5V trick yet.

Finding this all strange, think soon im going pretend there isn’t an LED.

Exp1 is connected exp1 and same with 2.
One of them had to be rotated, cant remember which. 
How I have it now is the only way it works, if i change to any other combination, whole lcd stops working.

**Comment by radek8** [comment]
send photo of engagement

**Comment by radek8** [comment]
@ivindor  what kind of record do you have marlin?

**Comment by ivindor** [comment]
> @ivindor what kind of board do you have marlin?

#define SERIAL_PORT  0

/**
 * Select a secondary serial port on the board to use for communication with the host.
 * :[-1, 0, 1, 2, 3, 4, 5, 6, 7]
 */
#define SERIAL_PORT_2  -1
  this??

**Comment by radek8** [comment]
No.
What hardware do you have on Marlin? so send a photo of where the connector is going

**Comment by radek8** [comment]
SKR 1,4 turbo?

**Comment by ivindor** [comment]
> SKR 1,4 turbo?

yes i have skr 1.4 turbo

**Comment by radek8** [comment]
Then you have it badly connected

**Comment by ivindor** [comment]
> Then you have it badly connected

How do I connect it?

**Comment by radek8** [comment]
You have to connect two cables. EXP1 and EXP2
In Marlin you have to set
#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
Send configuration.h

I'm writing this for the second time. Please read what I write.

**Comment by ivindor** [comment]
> You have to connect two cables. EXP1 and EXP2
> In Marlin you have to set
> #define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
> Send configuration.h
> 
> I'm writing this for the second time. Please read what I write.

You have to connect two cables. EXP1 and EXP2
In Marlin you have to set
#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
Send configuration.h

I'm writing this for the second time. Please read what I write.
I have it defined the same in my marlin that I put configuration.h in my first post

**Comment by radek8** [comment]
You have an error here - configuration.h
You must comment on a line
// #define CR10_STOCKDISPLAY

**Comment by radek8** [comment]
Then connect the 2 connectors EXP1 and EXP2
It has to work

**Comment by ivindor** [comment]
![WhatsApp Image 2020-11-20 at 21 07 30](https://user-images.githubusercontent.com/70163648/99845159-7db2c280-2b74-11eb-9bc5-eed3fbe1c5e6.jpeg)


> Then connect the 2 connectors EXP1 and EXP2
> It has to work

It is also commented

**Comment by ivindor** [comment]
with that configuration it only connects in ext3 for a second that I take a picture

**Comment by ivindor** [comment]
![WhatsApp Image 2020-11-20 at 21 10 28](https://user-images.githubusercontent.com/70163648/99845421-e69a3a80-2b74-11eb-9481-2d25908ebc88.jpeg)
![WhatsApp Image 2020-11-20 at 21 10 29](https://user-images.githubusercontent.com/70163648/99845425-e863fe00-2b74-11eb-9f9c-ca4685e24268.jpeg)

**Comment by radek8** [comment]
You have an error in the attached file.
![image](https://user-images.githubusercontent.com/46979052/99845432-eb5eee80-2b74-11eb-8578-e14503735056.png)

**Comment by radek8** [comment]
![image](https://user-images.githubusercontent.com/46979052/99845673-53153980-2b75-11eb-86eb-3ffe40ea6afc.png)

**Comment by ivindor** [comment]
ok sorry I compile it and try again to see if it works

**Comment by radek8** [comment]
In the picture, the connectors are already well connected.
Marlin repairs

**Comment by Doyle4** [comment]
> send a photo of the connector connections

Cant sadly at the moment, Had to put printer back together for now.
Im going to keep an eye on this page whilst I go through BTT help service, if they swap it, all good, if not.. back here I come and I'l make sure I have access to whats needed.

**Comment by radek8** [comment]
@ivindor, so that you don't have to solve other problems, check if you have permission:
M115_GEOMETRY_REPORT (in Configuration_adv.h)
M114_DETAIL (in Configuration_adv.h)
REPORT_FAN_CHANGE (in Configuration_adv.h)
EMERGENCY_PARSER (in Configuration_adv.h)
SERIAL_FLOAT_PRECISION 4 (in Configuration_adv.h)
HOST_ACTION_COMMANDS (in Configuration_adv.h)

For printing from onboard SD
SDSUPPORT (in Configuration.h)
AUTO_REPORT_TEMPERATURESS (in Configuration_adv.h)
AUTO_REPORT_SD_STATUS (in Configuration_adv.h)
LONG_FILENAME_HOST_SUPPORT (in Configuration_adv.h)
SDCARD_CONNECTION ONBOARD (in Configuration_adv.h)

**Comment by radek8** [comment]
> > send a photo of the connector connections
> 
> Cant sadly at the moment, Had to put printer back together for now.
> Im going to keep an eye on this page whilst I go through BTT help service, if they swap it, all good, if not.. back here I come and I'l make sure I have access to whats needed.

everything is valid for you too

**Comment by kad** [comment]
I also have problem with tft knob leds... and I start to suspect it is hardware design issue. And actually might be connected with quality of components that BTT is using: on TFT E3 3.0 neopixels are using PC7. In firmware it can be at the same time output for neopixels and input from exp2. BTT is using "buffer"  SN74LVC1G125 between PC7 of MCU and knob neopixels.
I tried to check output of that chip with logic analyser, and it seems it shows only "0", which sounds like broken chip.
Those chips are used also on SKR mini E3 and other boards, and I suspect that BTT had bad batch of those, as on my SKR mini E3 v2.0 neopixel port also doesn't work with similar symptoms - nothing on signal output pin.

**Comment by radek8** [comment]
> I also have problem with tft knob leds... and I start to suspect it is hardware design issue. And actually might be connected with quality of components that BTT is using: on TFT E3 3.0 neopixels are using PC7. In firmware it can be at the same time output for neopixels and input from exp2. BTT is using "buffer" SN74LVC1G125 between PC7 of MCU and knob neopixels.
> I tried to check output of that chip with logic analyser, and it seems it shows only "0", which sounds like broken chip.
> Those chips are used also on SKR mini E3 and other boards, and I suspect that BTT had bad batch of those, as on my SKR mini E3 v2.0 neopixel port also doesn't work with similar symptoms - nothing on signal output pin.

it is quite probable that the problem with the diode is related to the damaged HW

**Comment by oldman4U** [comment]
Any news @ivindor?

**Comment by ivindor** [comment]
I had problems compiling the marlin so it took a while to see the results but I regret to report that the knob led still does not work now if the tft is connected well through the ext1-ext2 ports but the led is still off

**Comment by oldman4U** [comment]
Disconnect ALL cables from the TFT. Cut an old USB cable and connect the red line to 5V and the black line to GND. Make sure they are not shorted and connect the USB cable to a power outlet. The TFT starts and you should be able to touch all buttons and also to turn the knob on and off using the corresponding settings.

If this does not work, a hardware issue is most likely.

**Comment by Doyle4** [comment]
Update from me, I'll no longer be adding here, I have been refunded as it was an hardware fault for me.

Now the question is, TFT35 V3 standard, or 43/50/70? hmmmmmmm

**Comment by oldman4U** [comment]
Good question. Please keep in mind that only the 70 gives you higher pixel density, where the 43 and 50 have a lower pixel density, even they have a bigger screen.

Please close this ticket once you do not need it anymore.

Thank you and happy printing

**Comment by Doyle4** [comment]
@oldman4U Thank you for the little bit of information, I think i’ll go for the 43, any larger and its going to be too big and pointless.

Sadly this isn't my post, so I can't close it sorry.

**Comment by oldman4U** [comment]
;-)

ivindor will follow your way I guess...;-)

I ordered a 43 so I can test it, but for me the bigger once are like for you just too big. Not sure how to mount it to my printer.

Anyway, happy printing

**Comment by Doyle4** [comment]
Exactly, I think the big ones can be OTT, but I can them coming in handy for larger printers, or if you need to see info from a distance.

Im going for the 43, will keep an eye on you for working firmwares :P

**Comment by radek8** [comment]
As Oldman wrote
43 "has worse resolution than 35" :-(

**Comment by Doyle4** [comment]
TFT35 non E3 version it is then :)

**Comment by oldman4U** [comment]
But not the v2, this is crap.

**Comment by kad** [comment]
> TFT35 non E3 version it is then :)

TFT35 E3 with non-working knob lights is practically the same as TFT35 V3.

**Comment by Doyle4** [comment]
hmmmm, think im going to hold off for a little longer :)

Bit of change of subject, anyone noticed lag when changing things like fan speed? need to have 1 second intervals between changing or it goes back to previous state? or turning off fan takes around 5seconds for the command to be accepted and turn off. if need be i'll open up a case.

**Comment by oldman4U** [comment]
Hi. This is "normal" behavior and depends on your RX/TX buffer setting in Marlin, how busy the TFT and therefore also the bus is and some other parameters. The firmware of today has some improvements in it so I would give it a try.

**Comment by thebiggestgit** [comment]
Re the LED light on the rotary dial, I had same issue with the latest firmware (I downloaded and compiled on 23-12-20) with the "Rotary Knob LED" and "Rotary Knob LED idle" settings no longer showing under the settings on the latest firmware, but showing in the GUI (with on/off and colours) but setting those did nothing.  This did work on a recent firmware (I had downloaded and compiled on 7-12-20) however, and showed the options under settings.  So appeared these settings were disabled but present in the GUI (Menu, Settings, Machine, LED Colour).

**Comment by thebiggestgit** [comment]
For me I found I had flashed the WRONG firmware as have the E3 board not the standard and although appeared to work OK, the rotary LED features didn't work and show under features, although did show in the GUI. As soon as I had flashed the E3 version of the firmware with the new language file it worked.  Note the default config with the latest is not compiling BIGTREE_TFT35_E3_V3_0 so edited the platformio.ini file so it would.  Changed "default_envs = BIGTREE_TFT35_V3_0" to "default_envs = BIGTREE_TFT35_E3_V3_0".

**Comment by oldman4U** [comment]
@Doyle4. Please check https://github.com/kisslorand/BIGTREETECH-TFT/tree/Flow-Speed-Fan for improved TFT handling changes of speed, Flow and Fan.

@ivindor. What is the status of the reported issue?

**Comment by Doyle4** [comment]
@oldman4U 

Tried this firmware, Sadly My fan speed etc still drops by 1% at a time, if using knob or touch buttons, it will jump back to 1% less than it was before.

I also spotted when ABL'ing, the first time it will read a couple spots and think its complete, starting again solves the problem.

**Comment by oldman4U** [comment]
Could you please attach a movie showing this behaviour.

**Comment by Doyle4** [comment]
@oldman4U 
ABL is working now from that one issue, but things like Fan speed change still are 1% drops, would you like this filming still?

**Comment by oldman4U** [comment]
Yes. 👍🏻

Doyle4 <notifications@github.com> schrieb am Sa. 2. Jän. 2021 um 11:11:

**Comment by Doyle4** [comment]
Sweet, will do that soon as I can

**Comment by kad** [comment]
@oldman4U tried to flash recent build (5b66d674bcb8e7faefdeda90e7ce812bf3464850), situation became even worse.
With serial_always_on=0 - it boots and works. With serial_always_on=1, and trying to boot in LCD12864 mode - TFT hangs with almost 100% rate (tried 10 times, same hang, even before the Marlin logo appears, just blank screen with title).

**Comment by Doyle4** [comment]
@oldman4U Sorry taken so long, not been home much to do it sorry.

**Comment by Doyle4** [comment]
https://user-images.githubusercontent.com/65953502/103525025-74588d80-4e76-11eb-9c7a-2e9b06125e20.mp4

**Comment by Doyle4** [comment]
This happens with anything that can have its % changed during print

**Comment by oldman4U** [comment]
Yes, because you use old TFT firmware. Update and it will show 2 values. The current one and the selected, so it is easily visible that you are using an old TFT firmware.

**Comment by oldman4U** [comment]
Thanks to the old fan, you can even hear the changes in this video.

kisslorand fixed this.

https://user-images.githubusercontent.com/54359396/103533647-c3f68380-4e8d-11eb-9ce4-c1bae4fc05d4.mov

**Comment by Doyle4** [comment]
hmmm this odd as I downloaded the Fan speed etc fix, can you point me to correct version please? thanks again.

**Comment by Doyle4** [comment]
Have you tried changing speed during print? My fan will change fine when not printing like yours also.

**Comment by oldman4U** [comment]
It is the master from yesterday which I have loaded. You have to see two
values like shown in my movie then you have automatically the fix for the
issue also. During print the reaction time is a bit slower but still very
good.

Doyle4 <notifications@github.com> schrieb am Mo. 4. Jän. 2021 um 13:17:

**Comment by Doyle4** [comment]
Have they removed it? Master for me was last edited 6days ago, and the fix was last updated 24days ago?

Sorry just a little confused with what firmware I need, or which two I need to merge together.

Thanks.

**Comment by oldman4U** [comment]
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware.git

**Comment by Doyle4** [comment]
i had no notification on this sorry, thank you!

**Comment by Doyle4** [comment]
> > I also have problem with tft knob leds... and I start to suspect it is hardware design issue. And actually might be connected with quality of components that BTT is using: on TFT E3 3.0 neopixels are using PC7. In firmware it can be at the same time output for neopixels and input from exp2. BTT is using "buffer" SN74LVC1G125 between PC7 of MCU and knob neopixels. I tried to check output of that chip with logic analyser, and it seems it shows only "0", which sounds like broken chip. Those chips are used also on SKR mini E3 and other boards, and I suspect that BTT had bad batch of those, as on my SKR mini E3 v2.0 neopixel port also doesn't work with similar symptoms - nothing on signal output pin.
> 
> hi, it have been a time... from this post, just past to say tha my problem was that U5 (SN74LVC1G125, Mark C255) bad, not in short but low resistence in pin (in), that resistor pull-down 472 (4.7kOHM) have a read of 100 ohm before remove U5... there are more foruns, that people have the same symtom. ( I suspect that BTT had bad batch of those) i am to :) after 1 year ...kkk i did repair mine ....

How did you fix it? I still have yet to resolve mine.

**Comment by Pedro-1-Veloso** [comment]
hi Doyle, i did replace that U5, it was bad.  Everyting was ok but that drive (u5) was killing the sinal to the rgb led.
![SN74LVC1G125](https://user-images.githubusercontent.com/99433134/154372425-3491a09b-7447-4c70-890e-3a50c0633a56.jpg)

see in the schematic, sinal enter in A, and get out in Y, OE (is on or off) allways on conect to ground. in A point (in my board )have 100ohm to ground, this was de error  ( bad U5), remove UA and that 100 ohm disappear. cpu give 3.3v, but leds work on 5 v, that drive does that. A point enter 3.3v, and get out 5v point Y. you can test direct, remove U5 and conect A to Y, and see if will work ( i did ..kkkk). 

if you need more help, just ask :) maybe you have the same error or not. 
1º thing i will do in your case is to measure that resistor (R10) just in the right of the 3 U5 legs, and see how much he have. is marking 472 ( that is 4.7kohm), my case it read (100 ohm), that resistor is conect  to point A. after the repair it read as correct 4,7Kohm

![imagem](https://user-images.githubusercontent.com/99433134/154374106-6f5520de-b601-48e0-8fa4-74a97f5677e0.png)

**Comment by Doyle4** [comment]
> hi Doyle, i did replace that U5, it was bad. Everyting was ok but that drive (u5) was killing the sinal to the rgb led. ![SN74LVC1G125](https://user-images.githubusercontent.com/99433134/154372425-3491a09b-7447-4c70-890e-3a50c0633a56.jpg)
> 
> see in the schematic, sinal enter in A, and get out in Y, OE (is on or off) allways on conect to ground. in A point (in my board )have 100ohm to ground, this was de error ( bad U5), remove UA and that 100 ohm disappear. cpu give 3.3v, but leds work on 5 v, that drive does that. A point enter 3.3v, and get out 5v point Y. you can test direct, remove U5 and conect A to Y, and see if will work ( i did ..kkkk).
> 
> if you need more help, just ask :) maybe you have the same error or not. 1º thing i will do in your case is to measure that resistor (R10) just in the right of the 3 U5 legs, and see how much he have. is marking 472 ( that is 4.7kohm), my case it read (100 ohm), that resistor is conect to point A. after the repair it read as correct 4,7Kohm
> 
> ![imagem](https://user-images.githubusercontent.com/99433134/154374106-6f5520de-b601-48e0-8fa4-74a97f5677e0.png)

Thank you very much for the reply,
I will will test this tomorrow and see what its reading :)

**Comment by Doyle4** [comment]
Managed to test:
Resistor is 4K, and I get 4.8V from A to Y.. hmmmm, worth removing U5 and connecting A to Y like you have said?

**Comment by Doyle4** [comment]
More awake today and re did test, I get 150ohm from A to Resistor, so it is looking like U5 is also damaged on mine.
What do I need to replace it with? do you know the part number?

**Comment by Pedro-1-Veloso** [comment]
kkkkkk yeap it feels like mine, a dead U5 150 ohm to ground (same as r10 resistor).

**Comment by Pedro-1-Veloso** [comment]
SN74LVC1G125 this is the part smd marking C255.

https://pt.aliexpress.com/item/1005003561611552.html?spm=a2g0o.productlist.0.0.49e35eb9TbQVAO&algo_pvid=078603df-cb87-4329-9d4e-a4320b90b0d7&algo_exp_id=078603df-cb87-4329-9d4e-a4320b90b0d7-9&pdp_ext_f=%7B%22sku_id%22%3A%2212000026291927353%22%7D&pdp_pi=-1%3B5.38%3B-1%3B468%40salePrice%3BEUR%3Bsearch-mainSearch

i dont know if i can print this, if not delete pls. :)
