### ISSUE TITLE
How can I not use the .ini file to update the firmware ?

### ISSUE THREAD

**Issue by Chukozor** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1274]
I'm really frustrated by the "maximum of 50 characters" for the code running at "pause/end" of a print, I'm used to compile the firmware and use the .bin where there were not this limitation of 50 characters.
I tried updating the firmware with the .bin file but it does not override the .ini.
How can I update the firmware ONLY by using the .bin file so I can write more characters for the code at the pause/end of print than the 50 limit of the .ini ?
Thank you

**Comment by Doyle4** [comment]
if you still have the config.ini.CUR that is working, remove the .CUR and change it back to config.ini and drag it across with the firmware and fonts. Just a guess, how I have done it, but not exceeding the 50 max.

**Comment by radek8** [comment]
There was an error in the comment. The maximum is 75 characters.
It is already fixed in the new ini file

**Comment by radek8** [comment]
The limit does not apply to the end code you have in the slicer :-)

**Comment by radek8** [comment]
By using current files, you will avoid many mistakes.
Compile the bin file yourself, it is obsolete or you download it from #1265

**Comment by oldman4U** [comment]
There is no way to "not" use the ini file besides using a very old version of the firmware. The ini overrules all other configurations and can be used "stand alone".
