### ISSUE TITLE
BIQU116-A2 mosfet module does not turn off

### ISSUE THREAD

**Issue by Decalis1979** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1279]
I bought a BIQU116-A2 mosfet module connected to GTR V1.0. I found out that the Mosfet doesn't work, the table heats up immediately after turning on the printer. Can someone help me please.

**Comment by oldman4U** [comment]
Hi.

How is this related to the firmware of the TFT?

**Comment by radek8** [comment]
If you have it properly connected and Marlin configured correctly. It has to work.
If it does not work, the mofset transistor is likely to be damaged. It is a sensitive component. It can also be damaged by static electricity.

**Comment by radek8** [comment]
https://3dprint.wiki/reprap/electronics/heatbed_mosfet

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
