### ISSUE TITLE
several bugs / feature requests

### ISSUE THREAD

**Issue by danorder** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1287]
encountered bugs / flaws with the tft e3 3.5 drop in display. 
ram usage is insane in compiler suggest remove power loss recovery its redundant.
jerk remains missing /acceleration menu remains incomplete 
printing around 200mms and high acceleration may result in a nozzle crash 2 carriage plates bent as a result -possibly buffer related? 
print from onboad sdcard allegedly no longer works on display with  older marlin firmware suggest revert or fix not everyone has a 32 bit board... marlin 2.0 is known to use larger libs which is not optimal for melzi board... 
suggest- make stable github fork to get around big trees lack of developer support for drop in models.

**Comment by oldman4U** [comment]
Hi.

Could you please check #1170 and #1218 to see which of the topics are already covered and adjust your valuable ticket. Seems also that you have some experience as a developer, so it would be great if you could help us to improve the firmware.

**Comment by kisslorand** [comment]
> M503 doesn't always report via terminal otherwise missing info via esp module

Check out [this](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/1276) PR.

> icon refresh appears to be patched z on vase mode rapid refreshes result in stuttering presumably other issues may be linked to nozzle crashes / garbled gcode to the mainboard

Check out [this](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/1284) PR.

**Comment by danorder** [comment]
ill adjust in reference to mentioned tickets.

**Comment by Bastlwastl84** [comment]
> encountered bugs / flaws with the tft e3 3.5 drop in display.
> ram usage is insane in compiler suggest remove power loss recovery its redundant.
> jerk remains missing /acceleration menu remains incomplete
> printing around 200mms and high acceleration may result in a nozzle crash 2 carriage plates bent as a result -possibly buffer related?
> print from onboad sdcard allegedly no longer works on display with older marlin firmware suggest revert or fix not everyone has a 32 bit board... marlin 2.0 is known to use larger libs which is not optimal for melzi board...
> suggest- make stable github fork to get around big trees lack of developer support for drop in models.

I needed to format the SD Card (not fast formating fat32 and standard-blocksize and set to 250000 Baud, than i coulded Connect to the sd card onboard from tft

**Comment by danorder** [comment]
does that make the icon appear 250000 on latest firmware. prior firmware it
simply disappeared. due to other mentioned issues i have yet to flash the
config.ini with onboard specified vs the autodetect which may be all it is
on my older version. note

**Comment by oldman4U** [comment]
@danorder 

I do not really understand your last reply. Could you please explain again?

Thank you

**Comment by danorder** [comment]
the onboard sdcard icon disappears in older versions of marlin. 2.05 it is
no longer present. i am not certain if the config.ini needs to be
specified from auto detect or not to make it reappear. on another note i
updated to later 2.0.7 which returned the onboard sdcard option. Prior tft
firmware detected onboard sdcard with marlin 2.05 then stopped detecting i
think on the first version of tft firmware with the 3d preview addon for
cura. allegedly after those changes the tft no longer can read
onboard sdcards if the main board is using older marlin. far from ideal if
that is in fact the case. note i haven't invested much interest in the tft
i updated to 2.07 for other reasons but can confirm the icon is now present
and can print off skr1.3 again without swapping to marlin mode. as for the
mentioned ui issues i think the primary focus should be to have complete
menus / fill in blanks like jerk / junction , fw retract cant use - on the
keypad which requires swap to marlin to use a - retract. , im probs
forgetting other ui qwerks currently i find swapping back fourth makes the
tft borderline useless, the other mention if it fully replaced marlin ui /
others it would only require 1 wire for touch only vs 3 in some cases
depending on the board.

**Comment by oldman4U** [comment]
Hi.

There is and there will always be a kind of dependency in case 2 or more systems have to work together. In many situations the TFT firmware has to adjust because of something changed in Marlin.

Missing features are listed as well as known issues. So what is the outcome of this particular ticket?
