### ISSUE TITLE
BTT-TFT35-E3-V3.0 filament runout don't beep any alarm and X & Y mottors are lock disabled after a while...

### ISSUE THREAD

**Issue by mpcolman** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1296]
Hi, have two question with the same procedure.....
When filament out, TFT activate "filament runout" and appears the alrt message but without any beep sound like alarm, can I set up a beep alarm with a specified time beeps?? in Marlin mode it's work fine but not with the TFT, have connected the sensor directly to the TFT screen.

And when a certain time passes (don't have certainly time lapse) the motors of the X&Y get unlocked, free moves and lost positions, bed and filament heaters still get on, but the motors don't in lock mode......, in Marlin mode its works fine......
thank for the help

I have instaled the latest firmware.
in Marlin have loaded this parameters...
ADVANCED_PAUSE_FEATURE 
#define ADVANCED_PAUSE_FEATURE
#if ENABLED(ADVANCED_PAUSE_FEATURE)
  #define PAUSE_PARK_RETRACT_FEEDRATE         80  // (mm/s) Initial retract feedrate.
  #define PAUSE_PARK_RETRACT_LENGTH            5  // (mm) Initial retract.
                                                  // This short retract is done immediately, before parking the nozzle.
  #define FILAMENT_CHANGE_UNLOAD_FEEDRATE     20  // (mm/s) Unload filament feedrate. This can be pretty fast.
  #define FILAMENT_CHANGE_UNLOAD_ACCEL        25  // (mm/s^2) Lower acceleration may allow a faster feedrate.
  #define FILAMENT_CHANGE_UNLOAD_LENGTH      150  // (mm) The length of filament for a complete unload.
                                                  //   For Bowden, the full length of the tube and nozzle.
                                                  //   For direct drive, the full length of the nozzle.
                                                  //   Set to 0 for manual unloading.
  #define FILAMENT_CHANGE_SLOW_LOAD_FEEDRATE   6  // (mm/s) Slow move when starting load.
  #define FILAMENT_CHANGE_SLOW_LOAD_LENGTH     0  // (mm) Slow length, to allow time to insert material.
                                                  // 0 to disable start loading and skip to fast load only
  #define FILAMENT_CHANGE_FAST_LOAD_FEEDRATE   20  // (mm/s) Load filament feedrate. This can be pretty fast.
  #define FILAMENT_CHANGE_FAST_LOAD_ACCEL     35  // (mm/s^2) Lower acceleration may allow a faster feedrate.
  #define FILAMENT_CHANGE_FAST_LOAD_LENGTH     60  // (mm) Load length of filament, from extruder gear to nozzle.
                                                  //   For Bowden, the full length of the tube and nozzle.
                                                  //   For direct drive, the full length of the nozzle.
  //#define ADVANCED_PAUSE_CONTINUOUS_PURGE       // Purge continuously up to the purge length until interrupted.
  #define ADVANCED_PAUSE_PURGE_FEEDRATE        6  // (mm/s) Extrude feedrate (after loading). Should be slower than load feedrate.
  #define ADVANCED_PAUSE_PURGE_LENGTH        100  // (mm) Length to extrude after loading.
                                                  //   Set to 0 for manual extrusion.
                                                  //   Filament can be extruded repeatedly from the Filament Change menu
                                                  //   until extrusion is consistent, and to purge old filament.
  #define ADVANCED_PAUSE_RESUME_PRIME          0  // (mm) Extra distance to prime nozzle after returning from park.
  //#define ADVANCED_PAUSE_FANS_PAUSE             // Turn off print-cooling fans while the machine is paused.

                                                  // Filament Unload does a Retract, Delay, and Purge first:
  #define FILAMENT_UNLOAD_PURGE_RETRACT       13  // (mm) Unload initial retract length.
  #define FILAMENT_UNLOAD_PURGE_DELAY       5000  // (ms) Delay for the filament to cool after retract.
  #define FILAMENT_UNLOAD_PURGE_LENGTH         1  // (mm) An unretract is done, then this length is purged.
  #define FILAMENT_UNLOAD_PURGE_FEEDRATE      25  // (mm/s) feedrate to purge before unload

  #define PAUSE_PARK_NOZZLE_TIMEOUT           300  // (seconds) Time limit before the nozzle is turned off for safety.
  #define FILAMENT_CHANGE_ALERT_BEEPS         10  // Number of alert beeps to play when a response is needed.
  #define PAUSE_PARK_NO_STEPPER_TIMEOUT           // Enable for XYZ steppers to stay powered on during filament change.

  #define PARK_HEAD_ON_PAUSE                    // Park the nozzle during pause and filament change.
  //#define HOME_BEFORE_FILAMENT_CHANGE           // If needed, home before parking for filament change

  #define FILAMENT_LOAD_UNLOAD_GCODES           // Add M701/M702 Load/Unload G-codes, plus Load/Unload in the LCD Prepare menu.
  //#define FILAMENT_UNLOAD_ALL_EXTRUDERS         // Allow M702 to unload all extruders above a minimum target temp (as set by M302)
#endif

**Comment by oldman4U** [comment]
Hi.

I can not really help, because I am not using a filament runout sensor...

@radek8 Do you know if there is a way to define a beep in case of certain events like filament run out and do you know why the motors are turned off in such a case after a while and if it is possible to prevent this?

Would be great if we could help this lost soul after waiting fro an answer for 2 days;-)

Thank you

**Comment by radek8** [comment]
I don't know. I don't use a filament sensor

**Comment by oldman4U** [comment]
OK, thank you.

I would recommend to search all tickets, open and closed for more information on filament sensor.

**Comment by mpcolman** [comment]
@oldman4U  thanks for your concern, I searched but not found about this throuble, I still waiting a few days more, maybe before I create a bug for this...... thank you again!

**Comment by oldman4U** [comment]
OK. Please do so.

**Comment by Chad541121** [comment]
Im watching this thread also.  I currently have the same question posted.  I was advised to update firmware on the board and the tft.  I am currently trying to figure it out.
[https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/1285](url)

**Comment by mpcolman** [comment]
@Chad541121 your issue appears at the moment when the filament runout starts or when spend a time waiting for the filament change? it's a t the moment (not in my case) you need to activate the ADVANCED_PAUSE_FEATURE in marlin......

**Comment by Chad541121** [comment]
ADVANCED_PAUSE_FEATURE is working!  I want to note that I have the filament runout sensor hooked to the tft35.  I only need to figure out how long the nozzle will stay locked for?  I print at work and may run out of filament when I'm gone for the weekend.

**Comment by oldman4U** [comment]
Maybe you can close this ticket, now that you opened the same in the firmware repository.

Thank you

**Comment by Chad541121** [comment]
The newest firmware resolved the motors not locking issue for me.

**Comment by mpcolman** [comment]
tested again with the last published firmware, after about 15 mins paused in filament out mode and tried to move the head and it moves freely.... not resolved.....

**Comment by oldman4U** [comment]
@Chad541121 

Latest Marlin or TFT firmware solved the problem for you?

**Comment by Chad541121** [comment]
It was the latest marlin firmware that solved my issue

**Comment by oldman4U** [comment]
Thank you

Mpc. What is the Marlin version you are using?

**Comment by mpcolman** [comment]
@Chad541121  you save my day! 
I change to "0" the  DEFAULT_STEPPER_DEACTIVE_TIME, and "false" for  DISABLE_INACTIVE ,and all work fine, locked motors are fine right now....
Pending the beep alarm for  when activate the filament runout.....
@oldman4U  you think that I close this issue and open another one for the filament runou beep exclusively??

**Comment by oldman4U** [comment]
Yes. Close this and start a new one.

👍🏻

mpcolman <notifications@github.com> schrieb am Do. 10. Dez. 2020 um 22:01:

**Comment by oldman4U** [comment]
@mpcolman Please close also the ticket in TFT Firmware: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/1338
