### ISSUE TITLE
[FR]  the button terminalACK

### ISSUE THREAD

**Issue by radek8** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1298]
@digant73 your modification of the menuTerminal is great.
Could it be further improved with a button that would turn "terminalACK" on and off directly from the terminal environment?
Thank you

**Comment by kisslorand** [comment]
What would be the benefit of it?

**Comment by radek8** [comment]
Directly in the terminal window I can turn on and off the communication of the display with the printer without having to go to the menu of printer parameters

**Comment by oldman4U** [comment]
Should we add this to the FR list?

**Comment by radek8** [comment]
If no one else wants it, you don't have to.
It's not that important.

**Comment by oldman4U** [comment]
YOU want it and you do a lot for this project. So I add it and hopefully it will be available one day. 👍🏻

**Comment by radek8** [comment]
:-)

**Comment by oldman4U** [comment]
Thank you @digant73

Please check PR #1563
