### ISSUE TITLE
TFT70 V3.0 Touch not working

### ISSUE THREAD

**Issue by steirerman** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1306]
TFT70 V3.0 the touch function does not work for me and the font is moved. Any Idea ? The software is current version.
![Drucker](https://user-images.githubusercontent.com/49448230/100537439-07bff280-3229-11eb-9b97-6ad15b571f00.jpg)

https://youtu.be/C4Upu3F0W_4

**Comment by traffic-light** [comment]
Did you try this:

Q: Touchscreen doesn’t respond/ stay’s in the “Choose mode” selection

    Answer: .......

    b) The screen doesn't respond to any touch
    The touchscreen settings could be corrupted. The screen doesn't know at this moment how to correctly respond to a touch.
    A way to solve this:
    Place a text file reset.txt in the root of a SD-card and insert this in the screen
    Reset the screen.
    When the screen is booted there will be a touchscreen callibration screen. Calibrate the screen and it should be solved.


See: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/1047

**Comment by traffic-light** [comment]
Did you update the fonts after updating the screen?

**Comment by steirerman** [comment]
THANKS !! Working :)

**Comment by traffic-light** [comment]
That's good to hear 😉 

Next time you could first check the readme for faster fixes


Please close the ticket when it's solved 😉

**Comment by steirerman** [comment]
Many thanks for the support
