### ISSUE TITLE
[BUG] TFT35 stucks on loading from onboard SD card

### ISSUE THREAD

**Issue by Davidoff77test** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1307]
On TFT35 E3 V3 I want to print from onboard SD card in touch mode. But if SD card contains some .gcode files display stucks on loading... message. From Marlin Mode it works.

### Steps to reproduce

1. Select Print->On Board SD Card
2. Select On Board SD Card

**Expected behavior**
I can see list of gcode files.

**Actual behavior**
Display stucks with Loading... message

### Hardware Variant
TFT35 E3 V3
### TFT Firmware Version & Main Board Firmware details
Marlin: 2.0.7.2
TFT fw: commit 198f14e from master branch

### Additional Information
[config.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5612014/config.zip)

**Comment by radek8** [comment]
This is a duplicate ticket.
please see # 1294 and # 1297

**Comment by oldman4U** [comment]
@Davidoff77test 

Please help the community and close this ticket.

Thank you

**Comment by kisslorand** [comment]
Check PR #1326.
