### ISSUE TITLE
weird extrude menu open up when clicked on any preheat button and back button kicks you out to main screen

### ISSUE THREAD

**Issue by carryreynolds** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1308]
### Description
The extrude menu opens the preheat menu and the preheat button is opening a weird extrude menu which looks incomplete.
and then clicking on the back button takes you to the main screen. 
This firmware now feels like a badly patched sailboat. instead of making things easier to access it is making things more complicated.

### Steps to reproduce

open extrude menu in the main menu and click any preheat button.

**Expected behaviour**
open extrude menu

### Hardware Variant
TFT35-V2
### TFT Firmware Version & Main Board Firmware details
TFT35_V2.0.26.X Nov 29 2020

@bigtreetech Why are new features/codes being added without testing and any supervision? currently, there is no one supervising this repository. Someone like @guruathwal who is familiar with this firmware should be appointed to oversee the changes and development in this repository to make sure proper development in this repository and bugs like these are avoided.

**Comment by traffic-light** [comment]
Did you also update the icons&fonts and the config.ini?

**Comment by traffic-light** [comment]
And did you compile the firmware on your own?

**Comment by carryreynolds** [comment]
yes all fonts, icons, config flashed and compiled the firmware myself.

**Comment by kisslorand** [comment]
Check PR #1304.

**Comment by oldman4U** [comment]
@carryreynolds 
This issue is solved.

Please check with latest firmware and close this ticket.

Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
@carryreynolds 

You opened this ticket. Could you please test the latest master firmware and update the ticket accordingly.

Thank you

**Comment by oldman4U** [comment]
9 day wonder.

It is very unfriendly not to answer.

Please close the ticket

**Comment by carryreynolds** [comment]
I am sorry for not replying. Not everyone enjoys free internet.
