### ISSUE TITLE
Persistent "No Printer Attached!" Message, Unable to Control Printer (TFT35 E3 v3.0, SKR mini E3 v2.0) What should I do?

### ISSUE THREAD

**Issue by ThePootisMann** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1310]
Hello everyone. Yesterday my SKR mini e3 v2.0 and TFT35 E3 v3.0 arrived from Amazon today, and I was quite excited to get it set up and start printing. However, after I put everything together, I received the "No Printer Attached!" message. From thereon, I have tried exactly these things to try and fix the problem, but to no avail:

Fixing/Moving serial connector on the board and monitor

Updating the firmware on the TFT35 E3 v3.0

Updating the firmware on the SKR mini e3 v2.0 (modified in PlatformIO, changing serial port values)

Changing the Baudrate in the firmware and on the TFT35

Modifying the TFT35 firmware in PlatformIO

Attempting to use Marlin Mode (which resulted in the "LCD12864 Simulator" Message)\

I truly feel as if I am running out of options. I have searched for threads all over the internet relating to this issue and trying out their solutions, but none have worked so far. Could you please help me determine a solution to the problem? Thank you.

**Comment by radek8** [comment]
Send a photo of how it's connected.
Attach configuration files

**Comment by ThePootisMann** [comment]
![IMG-3035](https://user-images.githubusercontent.com/75214246/100549175-54162d00-323f-11eb-861f-6748c67ae782.JPG)
![IMG-3036](https://user-images.githubusercontent.com/75214246/100549177-55dff080-323f-11eb-86de-91979fedb1c0.JPG)
How do I upload my configuration files? When I try to do it, it says the file format is unsupported.

**Comment by ThePootisMann** [comment]
> Send a photo of how it's connected.
> Attach configuration files

**Comment by ThePootisMann** [comment]
I closed it by mistake.

**Comment by radek8** [comment]
use zip

**Comment by radek8** [comment]
incorrectly connected EXP3 connector

![image](https://user-images.githubusercontent.com/46979052/100550904-96f6f580-327d-11eb-9639-46d30b73677e.png)

**Comment by radek8** [comment]
Send a better photo of this connector
![image](https://user-images.githubusercontent.com/46979052/100551002-4d5ada80-327e-11eb-8086-62e771329033.png)

**Comment by ThePootisMann** [comment]
![connector](https://user-images.githubusercontent.com/75214246/100551172-0a344380-324d-11eb-8822-5beda1da5107.jpg)
[Marlin-2.0.7.2-SKR-mini-E3-V2.0.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5612700/Marlin-2.0.7.2-SKR-mini-E3-V2.0.zip)

**Comment by ThePootisMann** [comment]
[config.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5612704/config.zip)

**Comment by radek8** [comment]
the photo is blurred

**Comment by ThePootisMann** [comment]
![unblurry](https://user-images.githubusercontent.com/75214246/100551434-73688680-324e-11eb-827d-818461f1c851.jpg)

**Comment by radek8** [comment]
OK the serial cable is OK.
Did you reconnect the EXP3 cable?

You have a badly defined serial port in configuration.h.
-1 is a USB connector
2 is a serial port for TFT
 
I recommend a change
#define SERIAL_PORT 2
#define SERIAL_PORT_2 -1

**Comment by ThePootisMann** [comment]
I did in fact reconnect the EXP3. I will change those values.

**Comment by radek8** [comment]
you do not have some important parameters enabled in marlin
read the comment in config.ini

![image](https://user-images.githubusercontent.com/46979052/100551823-8c3f5f00-3283-11eb-9e6a-23aaf975e4a4.png)

**Comment by ThePootisMann** [comment]
I have just enabled them.

**Comment by ThePootisMann** [comment]
Marlin Mode now appears to be working. However, I cannot say the same for the touchscreen mode.

**Comment by radek8** [comment]
did you fix the serial port parameter?
#define SERIAL_PORT 2
#define SERIAL_PORT_2 -1

**Comment by ThePootisMann** [comment]
I did.

**Comment by radek8** [comment]
If you have the same speed set, touch mode should work.

**Comment by ThePootisMann** [comment]
I have set the Baudrate in both the SKR and TFT to 115200. Touch mode still refuses to work.

**Comment by radek8** [comment]
It responds to touch, but writes the printer is not connected?

**Comment by radek8** [comment]
If the printer writes not connected, check the RS232 cable.
Can it be defective?

**Comment by ThePootisMann** [comment]
It does respond to touch. The cable may or may not be the source of the issue.

**Comment by oldman4U** [comment]
Hi. Have you read the ReadMe? There are 3 things to keep in mind regarding the serial connection.

https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware

**Comment by radek8** [comment]
Check the cable. If ok, try this:

Connect a PC to run the Pronterface program
Send command M503 and M115
Does the printer write connected?

**Comment by ThePootisMann** [comment]
The printer can print normally when in Marlin Mode, but the touch screen mode does not communicate with the printer.

**Comment by oldman4U** [comment]
And after reading the ReadMe you know that the two modes use completely different connectors and therefore it is possible that one mode works, but the other does not?

And you know what has to be done to make the serial connection work?

**Comment by ThePootisMann** [comment]
I do not know what has to be done to make the serial connection work. Could you enlighten me?

**Comment by oldman4U** [comment]
Reading this: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware

**Comment by oldman4U** [comment]
I just wanted to add, that once the TFT gets power, the touchscreen will "work". This means you can change the menu by clicking on buttons and so on, WITHOUT a connection to a mainboard. The warning you get means, that the TFT can not "talk" to the mainboard and the ability to do so relies on the 3 points mentioned in the documentation above. Not more and not less.

**Comment by ThePootisMann** [comment]
> I just wanted to add, that once the TFT gets power, the touchscreen will "work". This means you can change the menu by clicking on buttons and so on, WITHOUT a connection to a mainboard. The warning you get means, that the TFT can not "talk" to the mainboard and the ability to do so relies on the 3 points mentioned in the documentation above. Not more and not less.

I have tried changing the serial ports defined in Marlin, and I have made sure the Baud rate is matched. Could it be the cable?

**Comment by oldman4U** [comment]
In case the serial port in Marlin is correct and also the Baud Rate matches, only the cable can be the problem. The serial connection is really easy compared to Marlin based connection.

3 things.

The pin in the middle of the connector which is attached to the mainboard looks a bit loose on the picture above. I would check it.

**Comment by radek8** [comment]
The cable or one of the serial port pins may be defective. First check the cable (ohm meter).

**Comment by oldman4U** [comment]
Any news?

**Comment by oldman4U** [comment]
Would be nice if you could let us know, thank you.

**Comment by ThePootisMann** [comment]
I am sorry for my lack of attention towards this thread. I have decided that the best solution may just be to order another serial cable from Bigtreetech, although I am still open to suggestion.

**Comment by oldman4U** [comment]
You can easily take 5 cables and make your own. An old HDMI cable for example would work great.

**Comment by ThePootisMann** [comment]
How can I do this? Could you send me a tutorial?

**Comment by oldman4U** [comment]
Can you crimp a connector?

**Comment by ThePootisMann** [comment]
I lack the tool to do that

**Comment by radek8** [comment]
If you are going to put a new connector, make a shielded cable (for example, from a cable from a PC mouse).
You will avoid other possible problems in the future.
You don't have to crimp, just solder and a shrink tube. :-)

**Comment by ThePootisMann** [comment]
I am going to close the issue for now. Thank you to all who assisted me. I may re-open if the need arises.

**Comment by oldman4U** [comment]
Ok.

Hope the new cable solves the problem

👍🏻

ThePootisMann <notifications@github.com> schrieb am Sa. 5. Dez. 2020 um
00:00:
