### ISSUE TITLE
TFT 24 display will not work in Marlin Mode

### ISSUE THREAD

**Issue by chance182** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1312]
I have an mini board E3 V 2 with a TFT 24 display installed on an Ender 3. I can not get the Marlin Mode to function. I have reflashed the latest firmware successfully with the main and the Oldman4U branch with the same problem. My marlin config includes CR10 display mode, as well as the advance config modes requested in the config ini of the TFT. The TFT works fine in touch screen mode. When I switch to dual mode I see the Marlin mode.  I can not switch to the mode with the knob as I have seen done on vids. When touch selected I do see the LCD simulator text. Text brightens when I press the button, but no marlin display. The 10 pin is connected to the EXP1 and the serial connector is plugged in. Reversed the serial and get the printer not connected. so thats not the problem. Looked through the previous issues but no success. Hope someone can help. Thanks

**Comment by chance182** [comment]
[config chanc182.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5612497/config.chanc182.zip)

**Comment by radek8** [comment]
The TFT24 V1.1 display does not have an EXP3 connector, so it does not support connection with SKR nini E3V2 in marlin mode

**Comment by radek8** [comment]
You bought the wrong combination of SKR board with TFT

**Comment by chance182** [comment]
My marlin config files attached

**Comment by chance182** [comment]
I was sold as a combination stating that it would work in the Marlin mode. https://www.banggood.com/BIGTREETECH-SKR-MINI-E3-V2_0-Control-Board-+TFT24-V1_1-Touch-Screen-Kit-for-3D-Printer-Parts-Creality-3D-Printer-p-1757905.html?rmmds=myorder&cur_warehouse=CN

**Comment by chance182** [comment]
Would another LCD controller selection in Marlin config work?

**Comment by radek8** [comment]
I recommend complaining to the seller

**Comment by radek8** [comment]
It could be connected.
You would have to overwrite the file with a pin connection
pins_BTT_SKR_MINI_E3_common.h
you would also have to reconnect the 10pin connector so that there is 1 connector on one side and 2 connectors on the other.
Complicated for a man who has never done it.

**Comment by oldman4U** [comment]
At AliExpress they offer the TFT24 for Ender3 and I am sure, you can get the cable also separate. It is the one I dragged the purple frame around.

Pleas help the community and close the ticket once you do not need it anymore.

Thank you

<img width="1040" alt="Screenshot 2020-11-29 at 22 39 32" src="https://user-images.githubusercontent.com/54359396/100554334-45a63080-3294-11eb-9b6a-5c61934f18c0.png">

**Comment by oldman4U** [comment]
I also updated the ReadMe to reflect this combination of hardware properly:

https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware

Please help the community and close this ticket.

Thank you

**Comment by chance182** [comment]
Will an update to the Marlin software be necessary with this cable? What is the pin to pin connection of this cable? Thank you.

**Comment by radek8** [comment]
Try this.
Use the display driver in Marlin
#define CR10_STOCKDISPLAY

![image](https://user-images.githubusercontent.com/46979052/100675971-3a243980-3368-11eb-8742-791dac59cd06.png)

**Comment by chance182** [comment]
This fix was successful once a custom cable was constructed. Thank you for your support

**Comment by oldman4U** [comment]
👍🏻

Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by chance182** [comment]
Thank you for your assistance

**Comment by oldman4U** [comment]
Happy printing

;-)
