### ISSUE TITLE
No rollbacks for TFT 70 v3.0 

### ISSUE THREAD

**Issue by Robenc** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1313]
No way to roll back to 26.1 for the tft70 that is not buggy as the new version is

**Comment by oldman4U** [comment]
Hi.

It would be great if you could update the title of this ticket to something more useful, thank you.

You can "go back in time" doing the following:
Click on Code and then on Commits like shown here: 
<img width="1152" alt="Screenshot 2020-11-30 at 10 55 13" src="https://user-images.githubusercontent.com/54359396/100595286-00691980-32fb-11eb-901a-e405674fb26c.png">
Then scroll down to the build you would like to use and click on the sign which I marked with the red frame:
<img width="1322" alt="Screenshot 2020-11-30 at 10 56 42" src="https://user-images.githubusercontent.com/54359396/100595365-1bd42480-32fb-11eb-97b5-5f8de17e575b.png">
This allows you to download an older firmware.

Please let me know if this solves your problem

Thank you

**Comment by Robenc** [comment]
well there is no rollbacks to prior versions , please fix my tft 70 is not working and need the lastest before the merge

**Comment by oldman4U** [comment]
Doing what I described above you can go to any version you want. Not sure what else I can do.

**Comment by oldman4U** [comment]
Any news?

**Comment by Robenc** [comment]
Been busy will check later

**Comment by Robenc** [comment]
found it thanks had to back before the 27th

**Comment by oldman4U** [comment]
Great you found it!

What are the bugs you are referring to?

**Comment by Robenc** [comment]
Load the screen with the btt skr mini v2
