### ISSUE TITLE
Touchscreen menu item for Dual Z Stepper Auto Align feature?

### ISSUE THREAD

**Issue by Chad541121** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1329]
Can a touchscreen menu item be added for the dual z stepper autoalign feature?  There is currently a menu item in marlin mode.

**Comment by oldman4U** [comment]
Hi Chad. Please update the title and I will add your FR to the pinned FR ticket. 

Thank you

**Comment by Chad541121** [comment]
oldman4U
sorry I see that someone requested G34 autoalign with ticket #1150

**Comment by oldman4U** [comment]
In case this covers your request, yes. Please close the ticket.

Thank you
