### ISSUE TITLE
[BUG] M75 implementation on TFT

### ISSUE THREAD

**Issue by BsCmOD** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1330]
Hi to every one I have to report a newly discoverd issue, with the TFT35V3 in touch mode the M75 command in start gcode lock the print, the hotend and bed won't reach the desired temperature and job won't to start. Hope to be usefull. Bye

**Comment by oldman4U** [comment]
Hi.

So the work around is to avoid the timer command in start gcode, right? But why would I define M75 in my start gcode, where the elapsed time is always shown automatically? By mistake?

**Comment by BsCmOD** [comment]
Right, it's the timer start command and yes, the timer start automatically but I noticed that if I print in touch mode the print time Marlin counter does not increase so I tried to "solve" this problem by using M75 command although it shouldn't be necessary to use it since the timer autostart is enabled in configuration.h in Marlin. That's it

**Comment by oldman4U** [comment]
The print time on screen or that there is no accumulated print time?

BsCmOD <notifications@github.com> schrieb am Mi. 2. Dez. 2020 um 22:58:

**Comment by BsCmOD** [comment]
I'm referring to accumulated print time, number of jobs, total extruded filament etc... those counters works only if I print in Marlin (native) mode. I'm not totally sure but I think some time ago this funtion has worked. It's sin to loose/not use these counters, it's not a foundamental functions anyway it could be helpfull to know the works hours of the machine.

**Comment by oldman4U** [comment]
@radek8 do you know if M75 is somehow implemented using the touchscreen?

**Comment by BsCmOD** [comment]
I don't know

**Comment by oldman4U** [comment]
radek8 is the one who knows everything;-)

**Comment by radek8** [comment]
The M75 command is not used on TFT

**Comment by oldman4U** [comment]
Thank you Radek, thought so.

@BsCmOD If you want I can add this to the FR list. To do so, please change the label to FR and if you want, you can close this ticket afterwards. I will take care that it is added to the FR list.

Happy printing

**Comment by oldman4U** [comment]
Maybe you also want to edit the headline and add some more information how you would see this feature being configured and used in touchscreen mode.

**Comment by BsCmOD** [comment]
Closed for FR

**Comment by oldman4U** [comment]
Please describe how this should  work.
 Which options are shown where and how and when is the collected data shown
or what does it „execute“?


BsCmOD <notifications@github.com> schrieb am Do. 3. Dez. 2020 um 21:41:

**Comment by BsCmOD** [comment]
M75 it's a command which activate Marlin timer during printing. I'd tried to use because I saw that the total amount counters in Marlin didn't increase if I use TFT (touch) mode, no problem in Marlin mode. When I tried to use it the results was a freeze of the machine after preheating and M75 injection command I solved obviously by deleting M75....

**Comment by kisslorand** [comment]
I actually use M75 in the start gCode of the TFT without any issues. No freezing whatsoever.

**Comment by digant73** [comment]
@oldman4u this was probably a bug that is no more present so this FR could be close
