### ISSUE TITLE
Bug? tft35 Unified menu switch in config.ini doesn't work?

### ISSUE THREAD

**Issue by CamWynd** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1339]
### Description
Unified Menu/Classic Menu switch seems to be broken.

Is there a problem in the new touch screen firmware? I tried to use the config.ini switch for the Unified Menu option, and it doesn't work on my TFT35 (end up with the Classic Menu). I revert back to an older software version and I get the Unified Menu.
### Steps to reproduce

1.  download new firmware
2.  pick the version for my screen
3. ensure the option switch 'unified_menu:1' is in fact set to 1
4. upgrade firmware
5 say many bad words after doing this multiple times

**Expected behavior**
I expected my Unified Menu to remain on the screen.

**Actual behavior**
display reverted to the Classic Menu,

#
## Hardware Variant
tft35-e3 v3.0
### TFT Firmware Version & Main Board Firmware details
TFT firmware: 3.0.26.x
Marlin firmware: 2.0.7.1

**Comment by oldman4U** [comment]
Self or precompiled firmware? Send a picture of Menu Settings Info.

**Comment by oldman4U** [comment]
Maybe you want to change the title of the ticket.

**Comment by CamWynd** [comment]
It's the precompiled BIGTREE_TFT35_V3.0_E3.26.x.bin file that I'm using. I could send pics, but they would only show the Classic menu option (on the new firmware) or the Unified menu on the old, both of which are on the site; or are you looking for something else?

I agree on the ticket title rename; how do I do that (first time posting a ticket)?

**Comment by oldman4U** [comment]
Can you self compile?

What is the version under Menu Settings Info?

You can click on the title and change it

CamWynd <notifications@github.com> schrieb am Fr. 4. Dez. 2020 um 18:16:

**Comment by CamWynd** [comment]
Never mind; I bought a new sd card and it works now?! 
Really weird that the 2 older cards both gave me the Classic menu, but the new (larger) card works. 

I'm really starting to hate technology.

**Comment by oldman4U** [comment]
we hate it and we love it....

Happy printing
