### ISSUE TITLE
implicit declaration of function 'bmpDecode'

### ISSUE THREAD

**Issue by ArturNadolski** [bigtreetech/BIGTREETECH-TouchScreenFirmware#135]
TFT\src\User\Menu\Print.c: In function 'gocdeListDraw':
TFT\src\User\Menu\Print.c:103:10: warning: implicit declaration of function 'bmpDecode' [-Wimplicit-function-declaration]
       if(bmpDecode(strcat(gnew,"_95.bmp"), ICON_ADDR(ICON_PREVIEW+i)))

**Comment by thisiskeithb** [comment]
There are several warnings in the most recent firmware, but they can be ignored. Errors (red text) are what stop the build from compiling.

We're also waiting on https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/136 before PIO Core 4.1 can generate working firmware for our TFTs.

**Comment by ArturNadolski** [comment]
Fixed with current version.
