### ISSUE TITLE
Question about "fil_runout:" in the config.ini file

### ISSUE THREAD

**Issue by slwise** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1353]
I have a TFT35 E3 V3.0 updated with the latest firmware which includes the filament sensor (#1336)bug fix. I also have the BTT SFS connected to the TFT. I changed the "fil_runout:0" in the config.ini file to "fil_runout:2" for the smart sensor. After the firmware update is done installing, I go into the settings menu and it only shows the filament sensor as being "on" and not set as "smart". I have to manually select "smart". Is this the correct way it is supposed to work? Would this have any effect on how the sensor responds?

I am still getting false positives when printing. I think the main reason may be I have a Micro Swiss direct drive/hotend and the SFS is mounted where the extruder use to be on my Ender 3 Pro. I feed the filament from the side due to height limitations where the printer is located. I have the SFS connected to the direct drive through a bowden tube as a guide. I have tried different values in the "fil_noise_threshold:" and "fil_runout_distance:" with limited success. If anyone has any suggested settings for a direct drive I would really appreciate it.

**Comment by oldman4U** [comment]
Hi.

Could you please reset your settings under Menu - Settings - Feature - Reset default settings to see if this solves your problem.

Thank you

**Comment by slwise** [comment]
I reset the TFT as you described and also tried reseting the TFT with the reset.txt file. Both set the filament runout sensor to off. When I load the config.ini with "fil_runout:2" then feature menu still shows the filament runout sensor set to "on" not "smart". This is a minor issue. I'm just trying to get the SFS to work with a direct drive extruder and just wanted to make sure this wasn't affecting it's operation. BTW, I did just load the latest precompiled version of the firmware and it still sets the runout to "on" and not "smart". Thanks for your help.

**Comment by oldman4U** [comment]
OK. After installing a new firmware also to the Reset default settings ...

**Comment by slwise** [comment]
I'm sorry. I meant to say I tried it before the firmware update and after with same results.

**Comment by oldman4U** [comment]
OK. I can confirm this behaviour. When you define smart in config.ini, on TFT it shows ON, but not smart.

Any other issue?

**Comment by oldman4U** [comment]
@guruathwal Is this your area?

**Comment by slwise** [comment]
No other issues. Thanks.

**Comment by guruathwal** [comment]
Yes,
Fixed

Regards,
GuruAthwal

**Comment by oldman4U** [comment]
👍🏻

Gurmeet Athwal <notifications@github.com> schrieb am So. 13. Dez. 2020 um
03:37:
