### ISSUE TITLE
[BUG] not printing after aborting a printjob, Onboard TF and TFT SD are changed

### ISSUE THREAD

**Issue by Bastlwastl84** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1358]
Skr Mine E3 V2
TFT 35 E3 V3
ESP01 with ESP3D V3.0

The ESP3D Software can see it correctly, at TFT Firmware it's turned.

Config is here: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/1357
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5652679/Config.2020-12-05.zip
The difference is, that i'm using now the ESP01

Video what happens:
https://drive.google.com/file/d/1Bh4X687au1YXdAbnoCoXIL4V2PNECvpR/view?usp=drivesdk

![20201207_184003](https://user-images.githubusercontent.com/69717507/101385576-435b5c00-38bc-11eb-88a5-372d4fb83a6a.jpg)

**Comment by oldman4U** [comment]
Have you reported the same on luc's repository?  v3 is very new and would expect some bugs are still present.

**Comment by Bastlwastl84** [comment]
This error with not printing happened before some weeks with esp3d v2.1 and not used the webinterface, too. There i it happened, like yesterdayas i canceled it with the tft. Only a power off makes it useable. I opened esp3d to check and tested the new interface.
-------- Ursprüngliche Nachricht --------Von: oldman4U <notifications@github.com> Datum: 08.12.20  00:46  (GMT+01:00) An: bigtreetech/BIGTREETECH-TouchScreenFirmware <BIGTREETECH-TouchScreenFirmware@noreply.github.com> Cc: Bastlwastl84 <thomas.aumeier@gmail.com>, Author <author@noreply.github.com> Betreff: Re: [bigtreetech/BIGTREETECH-TouchScreenFirmware] [BUG] not printing after aborting a printjob, Onboard TF and TFT SD are changed (#1358) 
Have you reported the same on luc's repository?  v3 is very new and would expect some bugs are still present.

**Comment by oldman4U** [comment]
Ok. Which firmware have you been using and how is this reproducible?

**Comment by Bastlwastl84** [comment]
Marlin 2 Bugfix and tft FW from 5.12.Von meinem Sprechknochen gesendet.
-------- Ursprüngliche Nachricht --------Von: oldman4U <notifications@github.com> Datum: 08.12.20  11:28  (GMT+01:00) An: bigtreetech/BIGTREETECH-TouchScreenFirmware <BIGTREETECH-TouchScreenFirmware@noreply.github.com> Cc: Bastlwastl84 <thomas.aumeier@gmail.com>, Author <author@noreply.github.com> Betreff: Re: [bigtreetech/BIGTREETECH-TouchScreenFirmware] [BUG] not printing after aborting a printjob, Onboard TF and TFT SD are changed (#1358) 
Ok. Which firmware have you been using and how is this reproducible?

**Comment by oldman4U** [comment]
Half of the questions answered.

**Comment by Bastlwastl84** [comment]
How this happened: i dont know it happened. I stopped and tried starting again and filmedVon meinem Sprechknochen gesendet.
-------- Ursprüngliche Nachricht --------Von: oldman4U <notifications@github.com> Datum: 08.12.20  16:20  (GMT+01:00) An: bigtreetech/BIGTREETECH-TouchScreenFirmware <BIGTREETECH-TouchScreenFirmware@noreply.github.com> Cc: Bastlwastl84 <thomas.aumeier@gmail.com>, Author <author@noreply.github.com> Betreff: Re: [bigtreetech/BIGTREETECH-TouchScreenFirmware] [BUG] not printing after aborting a printjob, Onboard TF and TFT SD are changed (#1358) 
Half of the questions answered.

**Comment by oldman4U** [comment]
But you are somehow able to reproduce it on your printer!?

**Comment by Bastlwastl84** [comment]
> But you are somehow able to reproduce it on your printer!?

I don't know what did it. 
Actually a Printjob now is running with Marlin Mode for more than 1 day Printtime. After that i can retry.

**Comment by oldman4U** [comment]
Please do so.

**Comment by Bastlwastl84** [comment]
> Please do so.

downloaded now new firmware and test it in some minutes

**Comment by oldman4U** [comment]
Could you please reset your settings under Menu - Settings - Feature - Reset default settings.

**Comment by Bastlwastl84** [comment]
> Could you please reset your settings under Menu - Settings - Feature - Reset default settings.

now that the TF onboard and TFT are changed are gone now after resetting the tft. after updating the FW i coudn't connet to Marlin Mode (now that error is gone, too. i'll try some more things now

**Comment by Bastlwastl84** [comment]
Everything reseted (board and tft) and i had the same error again with time is running, but not printing.I did before testing some M150 light settings before and than tft sd->printVon meinem Sprechknochen gesendet.
-------- Ursprüngliche Nachricht --------Von: oldman4U <notifications@github.com> Datum: 11.12.20  17:50  (GMT+01:00) An: bigtreetech/BIGTREETECH-TouchScreenFirmware <BIGTREETECH-TouchScreenFirmware@noreply.github.com> Cc: Bastlwastl84 <thomas.aumeier@gmail.com>, Author <author@noreply.github.com> Betreff: Re: [bigtreetech/BIGTREETECH-TouchScreenFirmware] [BUG] not printing after aborting a printjob, Onboard TF and TFT SD are changed (#1358) 
Could you please reset your settings under Menu - Settings - Feature - Reset default settings.

**Comment by oldman4U** [comment]
How is this problem reproducible?

**Comment by Bastlwastl84** [comment]
I didn't had found out what does start the issueVon meinem Sprechknochen gesendet.
-------- Ursprüngliche Nachricht --------Von: oldman4U <notifications@github.com> Datum: 11.12.20  20:07  (GMT+01:00) An: bigtreetech/BIGTREETECH-TouchScreenFirmware <BIGTREETECH-TouchScreenFirmware@noreply.github.com> Cc: Bastlwastl84 <thomas.aumeier@gmail.com>, Author <author@noreply.github.com> Betreff: Re: [bigtreetech/BIGTREETECH-TouchScreenFirmware] [BUG] not printing after aborting a printjob, Onboard TF and TFT SD are changed (#1358) 
How is this problem reproducible?

**Comment by oldman4U** [comment]
I would recommend to close this ticket and start a new one with more
information regarding the print not start issue.

Bastlwastl84 <notifications@github.com> schrieb am Fr. 11. Dez. 2020 um
20:31:

**Comment by oldman4U** [comment]
Any news?

**Comment by Bastlwastl84** [comment]
Bug is gone

**Comment by oldman4U** [comment]
Because of...?
