### ISSUE TITLE
90 degree rotation for vertical implementations

### ISSUE THREAD

**Issue by DrewCipher505** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1381]
Creality Ender 3 v2, CR-6, and other printers have a form factor with 90 degree vertically oriented control screen.

Please add capability to define a 90 degree orientation along with applicable graphics and functionality including but not limited to encoder navigation and touch navigation

**Comment by oldman4U** [comment]
Hi.

Please read the pinned FR Ticket #1170 and the ticket #524 to see, that this feature has been requested several months ago.

Please close this ticket after that.

Thank you

**Comment by DrewCipher505** [comment]
Thank you

**Comment by oldman4U** [comment]
You are welcome

Thank you

DrewCipher505 <notifications@github.com> schrieb am So. 13. Dez. 2020 um
04:25:

**Comment by oldman4U** [comment]
Please help the community and close this ticket.

Thank you

**Comment by oldman4U** [comment]
Sorry, is closed already...

My mistake
