### ISSUE TITLE
[Q] (BIGTREETECH BTT PITFT50 support brightness control?)

### ISSUE THREAD

**Issue by savenko-egor** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1385]
**Your question or details you need. Please describe.**
I got my PITFT50 display and try control brightness via [rpi-backlight](https://pypi.org/project/rpi-backlight/). I tried from pi user and from root but don't got any effect. Please specify I can control brightness with my PITFT50?

**specify the device variant related to your question.**
[BIGTREETECH BTT PITFT50](https://aliexpress.com/item/1005001270623489.html)

Thakns!

**Comment by oldman4U** [comment]
Hi.

This repository is related to the FIRMWARE for the BTT TFT touchscreens. Have you tried to ask your question in a RPi user group?

**Comment by savenko-egor** [comment]
This question about display supported control brightness or not. Only this.

**Comment by oldman4U** [comment]
So you know this is the wrong repository but hope that someone can answer the question?

**Comment by bigtreetech** [comment]
Hello, PITFT50 don't support brightness control.
