### ISSUE TITLE
[BUG] Onboard SD print - Layer display stops at x height

### ISSUE THREAD

**Issue by kisslorand** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1386]
### Description

Printing a small object from onboard SD and the layer height stops at 0.80 mm. If I do nothing it stays that way, if I click "More" and than "Back" the layer height is updated until the end of the print.

### Steps to reproduce

1. [Start print]
2. [Watch layer height]
3. [and so on...]

**Expected behavior**

 Layer to update until the end of the print job.

**Actual behavior**

Layer display stops at 0.8mm
### Hardware Variant

Clone of the MKS TFT 28

### TFT Firmware Version & Main Board Firmware details

Latest build as of 14.XII.2020
### Additional Information

Here's the gCode:

[Strap6mm.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5685793/Strap6mm.zip)

**Comment by oldman4U** [comment]
Like always, it works on my printer. In addition your gcode file surprises the print finished dialog and uses the classic print finished method.
[Layer_s.mov.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5688041/Layer_s.mov.zip)

**Comment by kisslorand** [comment]
I got it. It's a programming error. There was a ternary in an "if" conditional. It might work or it might not. In my case it didn't.

Instead of:
`if (a != (b=c) ? d : e)`
`___doSomething();`
one should use:
`f = (b=c) ? d : e;`
`if (a != f)`
`__doSomething();`

Grrrr, it took me 5-6 hours to find it...

The logical value of 0.xx is FALSE. As soon as the Z hit 1.00 it's logical value changed to TRUE. Using ternary in the "if" conditional made the layer comparisons to be logical comparisons, not numerical ones. In logical terms 3.30 equals 8.60, in numerical terms they are not equal.

**Comment by oldman4U** [comment]
Where can I find: if (a != (b == c) ? d : e)

Seems it does not exist in my VSC.

**Comment by kisslorand** [comment]
It's in "PrintinMenu.c", right under the "//Z_AXIS coordinate" comment.

**Comment by guruathwal** [comment]
> I got it. It's a programming error. There was a ternary in an "if" conditional. It might work or it might not. In my case it didn't.
> 
> Instead of:
> `if (a != (b == c) ? d : e)`
> `___doSomething();`
> one should use:
> `if (a != ((b == c) ? d : e))`
> `___doSomething();`
> 
> Grrrr, it took me 5-6 hours to find it...

This is a bit strange. How can a logic change its behaviour by just switching the menus? both are completely independent of each other.

**Comment by kisslorand** [comment]
When "curLayer" becomes "1.00" the "curLayer != (infoFile.source == BOARD_SD)" becomes FALSE.
When switching to another menu and than back "curLayer" gets initialized again and it's value becomes "0" and after that it will be higher than "1.00" so "curLayer != (infoFile.source == BOARD_SD)" will be TRUE.
"curLayer != (infoFile.source == BOARD_SD)" is FALSE only when "curLayer" is "1.00".

**Comment by guruathwal** [comment]
> When "curLayer" becomes "1.00" the "curLayer != (infoFile.source == BOARD_SD)" becomes FALSE.
> When switching to another menu and than back "curLayer" gets initialized again and it's value becomes "0" and after that it will be higher than "1.00" so "curLayer != (infoFile.source == BOARD_SD)" will be TRUE.
> "curLayer != (infoFile.source == BOARD_SD)" is FALSE only when "curLayer" is "1.00".

yes. 👌

**Comment by oldman4U** [comment]
Changed it and asked my son to see if the layer high updates. Even it has been working fine before;-)

When will you add this to your PR?

**Comment by kisslorand** [comment]
It might be tomorrow or the day after tomorrow.  I will integrate it in PR #1359 .  If anyone wants so to make a PR with this fix sooner, I don't mind it.
BTW, Marlin just merged my PR about this bug, so we're good to go with the onboard SD printing as it was meant to be.

**Comment by oldman4U** [comment]
No need to hurry I assume.

So Marlin update is needed when printing from SD Card. Maybe it would be
good to update the information about the dependency in config.ini also?

kisslorand <notifications@github.com> schrieb am Di. 15. Dez. 2020 um 21:31:

**Comment by kisslorand** [comment]
A Marlin update is not necessary but only if you want the print finish to be as it was designed.
Without a Marlin update the print itself will be just as before.

**Comment by oldman4U** [comment]
I would update the Marlin information. 

Great work!

**Comment by kisslorand** [comment]
Well... thanks for the appreciation but it was me who introduced this bug (or so I think).

**Comment by oldman4U** [comment]
You solved it and it was there because you coded a great feature.

**Comment by digant73** [comment]
@kisslorand 
is the fix simply:
if (a != ((b == c) ? d : e))
in that case I could add it in my current minor PR (just to speedup the merge). Let me know if I can add it

**Comment by kisslorand** [comment]
Yes, that's THE fix. Please add it to your PR. Thx

**Comment by oldman4U** [comment]
Thank you.

Do you want to close this ticket;-))))

**Comment by kisslorand** [comment]
Fixed. Closed.
