### ISSUE TITLE
Icons, text and menus scrambled TFT28

### ISSUE THREAD

**Issue by JRosello** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1388]
My TFT 28 is driving me crazy... since I first updated the firmware to use a new theme, some parts are messed up.
Broken and missing icons, weird text (characters) on top the Marlin simulator mode, etc...

I read past issues about that I tried to fix it with no results...
-Reformatting the SD to FAT32
-Every time I try to reinstall in the SD card are all items:
TFT28 folder with font and bmp foders inside
The firmware, in my case BIGTREE_TFT28_V3.0.26.x.bin
The config.ini file
And the language language_en.ini

In all the cases the update process show that are some missing bmp files, but I checked and they are in the bmp folder.
My modified 320x240 24bit bmp logo.bmp file never loads properly. Always looks like a corrupted files with weird patterns.

I always use the pre-compiled .bin file in the "BIGTREETECH-TouchScreenFirmware-master\Copy to SD Card root directory to update\BIGTREE_TFT28_V3.0.26.x.bin", never compiled my self the firmware.

So anyone can bring any light?
Thanks

**Comment by oldman4U** [comment]
Hi. What is the firmware version shown under Info?

**Comment by JRosello** [comment]
Marlin firmware is the latest bug fix release 2.0.8
The board model is BIGTREETECH_TFT28_V3.0
The Board Firmware is TFT28_V3.0.26.x (latest release I downloaded yesterday)

**Comment by JRosello** [comment]
![Fitxer_000](https://user-images.githubusercontent.com/58893499/102187759-b3697380-3eb4-11eb-8a44-16a673117433.jpeg)

**Comment by oldman4U** [comment]
OK.

Unfortunately I have no v3 but only a v1 TFT28, but I have been testing the precompiled firmware using the v1, also with config.ini and en language as well as TFT28 folder and it worked fine.

What is the size of the SD card you use to update the firmware?

**Comment by JRosello** [comment]
4Gb Sd FAT32

**Comment by oldman4U** [comment]
Could you make a movie which shows the update process and also a screenshot of the content of the SD Card before and after update.

Thank you

**Comment by JRosello** [comment]
SD Card contents... let some minutes and I tro upload a video...
![Captura01](https://user-images.githubusercontent.com/58893499/102234816-f72e9e00-3ef1-11eb-9fc6-4dffc95e25dc.JPG)
![Captura02](https://user-images.githubusercontent.com/58893499/102234820-f7c73480-3ef1-11eb-8afc-f246fa5f3d07.JPG)
![Captura03](https://user-images.githubusercontent.com/58893499/102234822-f85fcb00-3ef1-11eb-9ee5-32cdb8260a6a.JPG)
![Captura04](https://user-images.githubusercontent.com/58893499/102234940-14636c80-3ef2-11eb-9483-4b5a93d9d617.JPG)
![Captura05](https://user-images.githubusercontent.com/58893499/102235392-93f13b80-3ef2-11eb-9a84-e1aed93ffdc7.JPG)

**Comment by oldman4U** [comment]
The files seem to be fine and what you see on screen is definitely wrong.

Have you ever tried to reset the TFT according to the ReadMe which you can find on the first page of this repo?

**Comment by JRosello** [comment]
Now it's worst.... I cannot even update the firmware... starts the process but no update is made... the contents on the sd card didn't change to .CUR ....
Maybe it's a faulty unit?
The video: https://drive.google.com/file/d/1yNWHf5mRTq770gtKX8ElFyq2jo5XpAIG/view?usp=sharing

**Comment by JRosello** [comment]
> 
> 
> The files seem to be fine and what you see on screen is definitely wrong.
> 
> Have you ever tried to reset the TFT according to the ReadMe which you can find on the first page of this repo?

Reset? where? I cannot find how... I only see the reset the touch screen using a blank file called reset... but it's for the touch calibration options right?

**Comment by oldman4U** [comment]
No access to your GoogleDrive...

Most likely the issue is the SD Card. Try to low format the card or use another one and try it again.

**Comment by JRosello** [comment]
Sorry... try again now...
https://drive.google.com/file/d/1yNWHf5mRTq770gtKX8ElFyq2jo5XpAIG/view?usp=sharing

The reset procedures says this...
_To reset the TFT's touch screen calibration, create a blank file named reset.txt and place in root folder of the sd card. Insert the SD card into the TFT's SD card reader and power cycle your printer to start the reset process_

I'll try to low level format the SD

**Comment by oldman4U** [comment]
Can you show the whole update incl. TFT folder and config.ini.

Exactly

OK

**Comment by JRosello** [comment]
The whole config.ini

#--------------------------------------------------------------------
#
# DEFAULT CONFIG FILE FOR BigTreeTech TFT CONTROLLERS
#
#--------------------------------------------------------------------


#--------------------------------------------------------------------
# Supported TFT Variants
#--------------------------------------------------------------------
#
# BIGTREE_TFT35_V1_1 / BIGTREE_TFT35_V1_2    / BIGTREE_TFT35_V2_0
# BIGTREE_TFT35_V3_0 / BIGTREE_TFT35_E3_V3_0 / BIGTREE_TFT28_V1_0
# BIGTREE_TFT28_V3_0 / BIGTREE_TFT24_V1_1    / MKS_32_V1_4
# MKS_28_V1_0
#
# Firmware source: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware
#


#--------------------------------------------------------------------
# Supported Marlin Firmware Versions
#--------------------------------------------------------------------
#
# Minimum Marlin firmware version: 2.0.5.4
# Distribution date: 2020-05-12
# Firmware source: https://github.com/MarlinFirmware/Marlin/releases
#
# IMPORTANT NOTE:
#   Ensure that the following options are enabled in Marlin firmware
#
# General options:
#   M115_GEOMETRY_REPORT (in Configuration_adv.h)
#   M114_DETAIL (in Configuration_adv.h)
#   REPORT_FAN_CHANGE (in Configuration_adv.h)
#   EMERGENCY_PARSER (in Configuration_adv.h)
#   SERIAL_FLOAT_PRECISION 4 (in Configuration_adv.h)
#   HOST_ACTION_COMMANDS (in Configuration_adv.h)
#
# Options to support printing from onboard SD:
#   SDSUPPORT (in Configuration.h)
#   AUTO_REPORT_TEMPERATURES (in Configuration_adv.h)
#   AUTO_REPORT_SD_STATUS (in Configuration_adv.h)
#   LONG_FILENAME_HOST_SUPPORT (in Configuration_adv.h)
#   SDCARD_CONNECTION ONBOARD (in Configuration_adv.h)
#
# Options to support (Un)Load menu:
#   FILAMENT_LOAD_UNLOAD_GCODES (in Configuration_adv.h)
#


#--------------------------------------------------------------------
# General Settings
#--------------------------------------------------------------------
#

#### Unified Menu / Classic Menu
# Select a UI menu flavour
#
# Options: [Unified Menu: 1, Classic Menu: 0]
#
unified_menu:1

#### Baudrate
# Options: [2400: 0, 9600: 1, 19200: 2, 38400: 3, 57600: 4, 115200: 5, 250000: 6, 500000: 7, 1000000: 8]
#
baudrate:5

#### Default Touch Mode Language
# Select the language to display on the LCD while in Touch Mode.
# To add/flash a second language copy the required "language_xx.ini" file from "Language Packs" folder
# to the SD root folder. Then preset the reset button to load/flash the copied language file
#
# Options: [primary language (english): 0, secondary language: 1]
#
language:0

#### Default Touch Mode Colors
# Options: [ WHITE: 0,  BLACK: 1,  RED: 2,  GREEN: 3,      BLUE: 4,       CYAN: 5,  MAGENTA: 6,    YELLOW: 7,
#           ORANGE: 8, PURPLE: 9, LIME: 10, BROWN: 11, DARKBLUE: 12, DARKGREEN: 13,    GRAY: 14, DARKGRAY: 15]
#
# Or set the color (RGB888 format) hex value directly (start with “0x”).
# Such as: 0xFF0000 : Red, 0x00FF00 : Green, 0x0000FF : Blue
#

# Title background color
#
title_back_color:1

# Background color
#
background_color:1

# Font foreground color
#
font_color:0

# Reminder font color, such as: "No print attached", "Busy processing", etc
#
reminder_color:2

# Volume status/reminder font color, such as: "Card inserted", "Card removed"
#
volume_status_color:5

# Backgroud color for X Y Z position display in Status Screen menu
#
status_xyz_bg_color:15

# List View border color
#
list_border_color:15

# List View button background color
#
list_button_bg_color:15

# Color used by the Mesh Editor menu for drawing the mesh with the minimun value in the grid
#
mesh_min_color:7

# Color used by the Mesh Editor menu for drawing the mesh with the maximum value in the grid
#
mesh_max_color:2

#### Rotate UI
# Rotate UI by 180 degrees
#
# Options: [enable: 1, disable: 0]
#
rotate_ui:0

#### Temperature ACK
# Show or hide temperature ACK in Terminal menu
#
# Options: [show: 1, hide: 0]
#
terminal_ack:0

#### Inverted Axes For Move Menu
# Invert axis button function in Move menu in order it matches the actual axis
#
# Format: [X<option> Y<option> Z<option> E<option>]
#
# Options: [enable: 1, disable: 0]
#
invert_axis:X0 Y0 Z0

#### Persistent Temperature Info
# Show persistent temperature info on all menus
#
# Options: [enable: 1, disable: 0]
#
persistent_info:0

#### File List Mode
# Display files in list mode instead of icon mode
#
# Options: [enable: 1, disable: 0]
#
files_list_mode:1

#### Notification Style For ACK Messages
# Set the notification style to use for displaying the ACK messages which start with 'echo:'
#
# NOTE: The OFF value is applied to any ACK message type (e.g. even to known echo ACK).
#       It means that any kind of ACK message is silently discarded
#
# Options: [OFF: 0, POPUP: 1, TOAST: 2]
#   OFF:   No notification. The message is ignored
#   POPUP: Display a popup window for user confirmation
#   TOAST: A non-blocking Toast notification is displayed for few seconds. No user interaction is needed
#
ack_notification:1


#--------------------------------------------------------------------
# Marlin Mode Settings (only for TFT24_V1.1 & TFT28/TFT35/TFT43/TFT50/TFT70_V3.0)
#--------------------------------------------------------------------
#

#### Default Mode
# Options: [Marlin Mode: 0, Touch Mode: 1]
#
default_mode:1

#### Serial Always ON
# Keep UART (serial communication) alive in Marlin Mode.
# Allows seamless OctoPrint UART connection to the TFT's UART/serial expansion port no matter which mode the TFT is in
#
# Options: [enable: 1, disable: 0]
#
serial_always_on:0

#### Default Marlin Mode Background & Font Colors
# Options: [ WHITE: 0,  BLACK: 1,  RED: 2,  GREEN: 3,      BLUE: 4,       CYAN: 5,  MAGENTA: 6,    YELLOW: 7,
#           ORANGE: 8, PURPLE: 9, LIME: 10, BROWN: 11, DARKBLUE: 12, DARKGREEN: 13,    GRAY: 14, DARKGRAY: 15]
#
# Or set the color (RGB888 format) hex value directly (start with “0x”).
# Such as: 0xFF0000 : Red, 0x00FF00 : Green, 0x0000FF : Blue
#

# Marlin Mode background color
#
marlin_bg_color:1

# Marlin Mode font color
#
marlin_fn_color:3

#### Marlin Mode Title Support
# Show title in Marlin Mode
#
# Options: [enable: 1, disable: 0]
#
marlin_show_title:1

#### Marlin Mode Fullscreen Support
# Run Marlin Mode in fullscreen
#
# Note: Disable is recommended for TFT24
#
# Options: [enable: 1, disable: 0]
#
marlin_fullscreen:1

#### Marlin Mode Type
# Select Marlin Mode type
#
# Options: [LCD12864: 1, LCD2004: 0]
#
marlin_type:1

#### Marlin Mode Title
# Text displayed at the top of the TFT in Marlin Mode
#
marlin_title:Marlin Simulator


#--------------------------------------------------------------------
# Printer / Machine Settings
#--------------------------------------------------------------------
#

#### Hotend Count
# Options: [1 to 6]
#
hotend_count:1

#### Heated Bed Support
# Options: [enable: 1, disable: 0]
#
heated_bed:1

#### Heated Chamber Support
# The TFT will auto-detect if chamber heating is enabled in marlin firmware
#
# Options: [enable: 1, disable: 0]
#
heated_chamber:0

#### Extruder Count
# Options: [1 to 6]
#
ext_count:1

#### Fan Count
# Options: [1 to 6]
#
fan_count:1

#### Fan Controller Count
# Options: 0 to 2
#
fan_ctrl_count:0

#### Bed / Extruder / Chamber Maximum Temperatures
# Format: [max_temp: T0:<max temp> T1:<max temp> T2:<max temp> T3:<max temp> T4:<max temp> T5:<max temp> BED:<max temp> CHAMBER:<max temp>]
#
# Unit: [°C]
#
max_temp:T0:275 T1:275 T2:275 T3:275 T4:275 T5:275 BED:150 CHAMBER:60

#### Cold Extrusion Minimum Temperature
# Unit: [°C]
#
min_temp:180

#### Fan Maximum PWM Speed
# Format: [fan_max: F0:<max PWM> F1:<max PWM> F2:<max PWM> F3:<max PWM> F4:<max PWM> F5:<max PWM> CtL:<max PWM> CtI:<max PWM>]
#
# Value range: [min: 0, max: 255]
#
fan_max:F0:255 F1:255 F2:255 F3:255 F4:255 F5:255  CtL:255 CtI:255

#### Machine Size / Build Area
# The TFT will auto-detect the machine size (min and max) in Marlin firmware (requires enabling `M115_GEOMETRY_REPORT`
# in Configuration_adv.h in Marlin firmware)
#
# Format: [size_min: X<minimum distance> Y<minimum distance> Z<minimum distance>]
#         [size_max: X<maximum distance> Y<maximum distance> Z<maximum distance>]
#
# Unit: [mm]
#
# Value range: [min: -2000, max: 2000]
#
# Options: [X axis: X, Y axis: Y, Z axis: Z]
#
size_min:X0 Y0 Z0
size_max:X300 Y300 Z400

#### Default Move Speeds
# Format: [move_speed: S<feedrate mm/min> N<feedrate mm/min> F<feedrate mm/min>]
#
# Unit: [mm/min]
#
# Options: [slow: S, normal: N, fast: F]
#
move_speed:S1000 N3000 F5000

#### Default Extruder Speeds
# Format: [ext_speed: S<feedrate mm/min> N<feedrate mm/min> F<feedrate mm/min>]
#
# Unit: [mm/min]
#
# Options: [slow: S, normal: N, fast: F]
#
ext_speed:S60 N600 F1200

#### Auto Save Load Leveling Data
# The TFT will auto-detect if Auto Bed Level is available.
# Enable this will send "M500" after "G29" to store leveling value
# and send "M420 S1" to enable leveling state after startup
#
# Options: [enable: 1, disable: 0]
#
auto_load_leveling:1

#### Onboard / Printer SD Card Support
# On Marlin firmware, the TFT will auto-detect Onboard SD Card.
# Auto-detect is not available for other firmwares like Smoothieware
#
# Options: [enable: 1, disable: 0, auto-detect: 2]
#
onboard_sd_support:2

#### M27 Printing Status Refresh Time
# M27 printing status refresh time (this will be used if SD_AUTOREPORT is not detected by the TFT)
#
# Unit: [seconds]
#
M27_refresh_time:3

#### M27 Always Active
# Keep polling M27 even if not printing
#
# Options: [enable: 1, disable: 0]
#
M27_always_active:1

#### Long File Names Support
# On Marlin firmware, the TFT will auto-detect Long File Name support.
# Auto-detect is not available for other firmwares like Smoothieware
#
# Options: [enable: 1, disable: 0, auto-detect: 2]
#
long_filename_support:2

#### Fan Speed As Percentage
# Show fan speed as percentage
#
# Options: [enable: 1, disable: 0]
#
fan_speed_percent:1

#### Pause Settings
# Actions applied when a print is paused, such as:
#   Pause retract distance
#   Pause XY position
#   Pause Z raise
#   Pause feed rate
#
# Format: [pause_retract: R<retract length> P<Resume Purge length>]
#         [pause_pos: X<position in mm> Y<position in mm>]
#         [pause_z_raise: Z<distance in mm>]
#         [pause_feedrate: X<feedrate mm/min> Y<feedrate mm/min> Z<feedrate mm/min> E<feedrate mm/min>]
#
# Unit: [position & length: mm, feedrate: mm/min]
#
# Value range: [min: 0, max: 2000]
#
pause_retract:R15 P16
pause_pos:X10 Y10
pause_z_raise:10
pause_feedrate:X6000 Y6000 Z6000 E600

#### Manual Level Points Edge Distance
# Settings used by Manual Leveling menu, such as:
#   Leveling edge distance
#   Leveling Z position
#   Leveling Z raise
#   Leveling feed rate
#
# Format: [level_edge_distance: <distance from edge in mm>]
#         [level_z_pos: Z<position in mm>]
#         [level_z_raise: Z<distance in mm>]
#         [level_feedrate: X<feedrate mm/min> Y<feedrate mm/min> Z<feedrate mm/min>]
#
# Unit: [distance: mm, feedrate: mm/min]
#
level_edge_distance:20
level_z_pos:0.2
level_z_raise:10
level_feedrate:X6000 Y6000 Z6000

#### Preheat Temperatures
# Format: [T<hotend temp> B<bed temp>]
#
# Unit: [°C]
#
# Value range: [filament name: max 7 characters]
#
preheat_name1:PLA
preheat_temp1:T205 B65

preheat_name2:PETG
preheat_temp2:T240 B70

preheat_name3:ABS
preheat_temp3:T230 B90

preheat_name5:TPU
preheat_temp5:T220 B50


#--------------------------------------------------------------------
# Power Supply Settings (if connected to TFT controller)
#--------------------------------------------------------------------
#

#### Default Power Supply Mode
# Options: [OFF: 0, ON: 1, AUTO: 2]
#
ps_on:0

#### Power Supply Active HIGH
# Options: [HIGH: 1, LOW: 0]
#
ps_on_active_high:1

#### Power Supply Auto Shutdown Temperature
# Maximum hot-end temperature of automatic shut down after printing (only if auto power is enabled).
# Wait for the hot-end temperature to be lower than this value, then turn off the power automatically
#
# Unit: [°C]
#
auto_shutdown_temp:50


#--------------------------------------------------------------------
# Filament Runout Settings (if connected to TFT controller)
#--------------------------------------------------------------------
#

#### Default Filament Runout Sensor
# Options: [NONE: 0, NORMAL: 1, SMART: 2]
#
fil_runout:0

#### Inverted Filament Runout Logic
# Invert the logic of the sensor
#
# Options: [true: 1, false: 0]
#
fil_runout_inverting:1

#### Filament Noise Threshold
# Pause print when filament runout is detected for this time period
#
# Unit: [ms]
#
fil_noise_threshold:100

#### Smart Filament Runout Detection
# For use with an encoder disc that toggles runout pin as filament moves
#
# Unit: [mm]
#
fil_runout_distance:7


#--------------------------------------------------------------------
# Power Loss Recovery & BTT UPS Settings (if connected to TFT controller)
#--------------------------------------------------------------------
#

#### Default Power Loss Recovery Mode
# Enabled by default.
# Disable to reduce the loss of SD card or U disk
#
# Options: [enable: 1, disable: 0]
#
pl_recovery_en:1

#### Power Loss Recovery Homing
# Home before power loss recovery
#
# Options: [enable: 1, disable: 0]
#
pl_recovery_home:0

#### Power Loss Z Raise
# Raise Z axis on resume (on power loss with UPS)
#
# Unit: [mm]
#
pl_z_raise:10

#### BTT UPS Support
# Enable BTT UPS
#
# Options: [enable: 1, disable: 0]
#
btt_mini_ups:0


#--------------------------------------------------------------------
# Other Device-Specific Settings
#--------------------------------------------------------------------
#

#### Sounds / Buzzer
# Set sound ON or OFF
#
# Variants:
#   touch_sound: enable/disable this to control touch feedback sound
#   toast_sound: enable/disable this to control all toast notification sounds
#   alert_sound: enable/disable this to control all popup and alert sounds
#                like print finish alert, dialog sound etc
#
# NOTE: Error messages from printer will always play the error sound
#
# Options: [enable: 1, disable: 0]
#
touch_sound:1
toast_sound:1
alert_sound:1

#### Knob LED Color (only for TFT35 E3.0)
# Options: [LED_OFF: 0, LED_WHITE: 1, LED_RED: 2, LED_ORANGE: 3, LED_YELLOW: 4, LED_GREEN: 5, LED_BLUE: 6, LED_INDIGO: 7, LED_VIOLET: 8]
#
knob_led_color:5

#### Knob Idle State
# Options: [true: 1, false: 0]
#
knob_led_idle:1

#### Default LCD Brightness Levels (only for TFT35v3.0 & TFT28v3.0)
# Options: [(off) 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 (full)]
#
lcd_brightness:11
lcd_idle_brightness:4

#### Default LCD Idle Time (only for TFT35v3.0 & TFT28v3.0)
# Options: [Off: 0, 5sec: 1, 10sec: 2, 30sec: 3, 1min: 4, 2min: 5, 5min: 6, 10min: 7]
#
lcd_idle_delay:4


#--------------------------------------------------------------------
# Custom Gcode Commands
#--------------------------------------------------------------------
#

#### Custom Gcode Commands
# Up to 15 custom gcode commands that will be available in the Custom menu
#
# To enable a custom command, remove '#' at the begining of custom commands label & gcode.
# To disable a custom command, add '#' at the begining of custom commands label & gcode.
#
# Note: If the values are left blank then default name and gcode will be used
#
# Value range: [label: max 24 characters, gcode: max 70 characters]
#
custom_label_1:Disable steppers
custom_gcode_1:M84\n
custom_label_2:Init sd card
custom_gcode_2:M21\n
custom_label_3:Release sd card
custom_gcode_3:M22\n
custom_label_4:Restore leveling
custom_gcode_4:M420 S1\n
custom_label_5:Save to EEPROM
custom_gcode_5:M500\n
custom_label_6:Restore from EEPROM
custom_gcode_6:M501\n
custom_label_7:EEPROM defaults
custom_gcode_7:M502\n
#custom_label_8:custom8
#custom_gcode_8:M105\n
#custom_label_9:custom9
#custom_gcode_9:M105\n
#custom_label_10:custom10
#custom_gcode_10:M105\n
#custom_label_11:custom11
#custom_gcode_11:M105\n
#custom_label_12:custom12
#custom_gcode_12:M105\n
#custom_label_13:custom13
#custom_gcode_13:M105\n
#custom_label_14:custom14
#custom_gcode_14:M105\n
#custom_label_15:custom15
#custom_gcode_15:M105\n


#--------------------------------------------------------------------
# Start, End & Cancel Gcode Commands
#--------------------------------------------------------------------
#

#### Default Start Gcode Status
# Options: [enable: 1, disable: 0]
#
start_gcode_enabled:0

#### Default End Gcode Status
# Options: [enable: 1, disable: 0]
#
end_gcode_enabled:0

#### Default Cancel Gcode Status
# Options: [enable: 1, disable: 0]
#
cancel_gcode_enabled:0

#### Start Gcode
# Run this gcode before starting print
#
# Value range: [max 75 characters]
#
start_gcode:G28 XY R20\n

#### End Gcode
# Run this gcode after finishing print
#
# Value range: [max 75 characters]
#
end_gcode:M104 S0\nM140 S0\nM18\n

#### Cancel Gcode
# Run this gcode after canceling print
#
# Value range: [max 75 characters]
#
cancel_gcode:M104 S0\nM140 S0\nG28 XY R10\n

**Comment by oldman4U** [comment]
Not the files but a movie which shows the update.
Sorry

JRosello <notifications@github.com> schrieb am Di. 15. Dez. 2020 um 17:43:

**Comment by JRosello** [comment]
> 
> Can you show the whole update incl. TFT folder and config.ini.
> 
The TFT\bmp\ has 136 .bmp files and one Readme.md

This is the readme.md file contents:
```
ImageMagick command

convert Reserve_6.bmp -alpha set -define bmp:format=bmp3 -define bmp3:alpha=true Reserve_6.bmp
```

**Comment by JRosello** [comment]
The failed update video:
https://youtu.be/CpkEdpESgXE

**Comment by oldman4U** [comment]
Please make a movie like above but where everything is updated. Firmware, config.ini and TFT folder.

**Comment by JRosello** [comment]
> 
> 
> Please make a movie like above but where everything is updated. Firmware, config.ini and TFT folder.

I'll try... because seems now I cannot update any more.... it reads the card the gets the 100% firmware read and then jumps straight to the main menu... no update :/
I'll try another sd... I don't know if I have any SD below 8gb though

**Comment by JRosello** [comment]
@oldman4U Wow I just used a microSD with an adapter and updated successfully!!
is this normal?? the branded Kingston SD 4Gb didn't work an a Chinese not branded cheep microsd works?!

**Comment by oldman4U** [comment]
The reset.txt resets everything incl. the calibration. Try it.

**Comment by oldman4U** [comment]
What is normal...

I have more than 10 identical 4GB sd cards and one I can not use for
firmware update but works flawlessly otherwise;-)

Glad it works!!!

Please help the community and close the ticket once you do not need it
anymore. Thank you

JRosello <notifications@github.com> schrieb am Di. 15. Dez. 2020 um 21:47:

**Comment by JRosello** [comment]
I'll keep in mind the reset.txt file just in case
Thanks for all!!

**Comment by oldman4U** [comment]
You are welcome 

Happy printing
