### ISSUE TITLE
[BUG] TFT Freez after Update

### ISSUE THREAD

**Issue by iBims1Schnubbert** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1395]
TFT Freeze after Update
-->
### Description
The Firmware Update for TFT Freez after Update in selection Screen for Touch or Marlin mode

### Steps to reproduce

1. Copy Fils on SD
2. Put SD in TFT and Power it on
3. after Update only show the Selection Screen vor Touch or Marlin mode and Freez

**Expected behavior**

**Actual behavior**

### Hardware Variant
Bigtreetech TFT 24 - SKR1.4 Turbo Board
SD Card Size 128MB Fat Format 2048 Bytes Allocation units
### TFT Firmware Version & Main Board Firmware details
Bigtreetech Version 1.1.26

### Additional Information
* Include a ZIP file containing your `Configuration.h` or use [Pastebin](https://pastebin.com/) and paste a link in this issue.
* Provide pictures or links to videos that clearly demonstrate the issue.
[Dateien TFT-Marlin.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5697760/Dateien.TFT-Marlin.zip)

**Comment by oldman4U** [comment]
Please update the title of this ticket. 

Attach a movie which shows the whole update process and the issue.

**Comment by iBims1Schnubbert** [comment]
How do i update the title?

**Comment by oldman4U** [comment]
And let me know about the sd card size and format.

**Comment by iBims1Schnubbert** [comment]
check

**Comment by radek8** [comment]
Check that the frame does not press on the edge of the display (remove the display from the frame and try it)
If this does not help, calibrate the touch layer with the reset.txt file

**Comment by iBims1Schnubbert** [comment]
how do I do that with the reset? Copy an empty reset.txt file to the sd and boot into the display? or do you have to have another file on it?

**Comment by oldman4U** [comment]
Exactly as you wrote. Alone or with other files, it does not matter.

**Comment by iBims1Schnubbert** [comment]
THX worked great

**Comment by oldman4U** [comment]
Whats about the ability to switch and which firmware is installed now?

**Comment by iBims1Schnubbert** [comment]
Version 1.1.26 and witching is also possible

**Comment by oldman4U** [comment]
Sounds great. Check the Info of your TFT and let us know firmware date.

**Comment by iBims1Schnubbert** [comment]
Dec 15 2020 is the Date

**Comment by oldman4U** [comment]
Perfect!

Please close the ticket once you do not need it anymore.

Happy printing
