### ISSUE TITLE
Case sensitivity in include names

### ISSUE THREAD

**Issue by dmiart** [bigtreetech/BIGTREETECH-TouchScreenFirmware#14]
So, I wasn't able to compile the code until changed most of the filenames to the lowercase.  ex: Heat.h  -> heat.h  and so on.

**Comment by 3darena** [comment]
We have made patch to repair this issue. You can downloadt it:

[BIQU.diff.txt](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/3536288/BIQU.diff.txt)

**Comment by cwizard** [comment]
Can this be marked as closed
