### ISSUE TITLE
TFT 35 V2.0 icon labels gone after update 

### ISSUE THREAD

**Issue by Vern-K** [bigtreetech/BIGTREETECH-TouchScreenFirmware#140]
Had some stopping mid print issues, so updated firmware now all the labels for the icons are gone, I did go into the folder and change what was some other characters back to english characters and that did nothing. I also was trying to add a button for pre heating nylon and that build failed, that was after first update when I went digging though to see if I could find what was wrong. Please keep in mind I'm new and use small words and crayons.
Thanks 
Vern
![20191109_205523](https://user-images.githubusercontent.com/57025814/68538675-c450c880-0335-11ea-8008-9209a49ac9d4.jpg)
[BIGTREETECH-TouchScreenFirmware.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/3828063/BIGTREETECH-TouchScreenFirmware.zip)

**Comment by guruathwal** [comment]
you need to update the icons and fonts

**Comment by thisiskeithb** [comment]
Did you update the icons and fonts by copying the TFT35 folder to the root of your SD card?

**Comment by Vern-K** [comment]
so move this C:\Users\lucky\Desktop\BIGTREETECH-TouchScreenFirmware-master\BIGTREETECH-TouchScreenFirmware-master\Copy to SD Card root directory to update - Unified Menu Material theme\TFT35 
into 
C:\Users\lucky\Desktop\BIGTREETECH-TouchScreenFirmware-master\BIGTREETECH-TouchScreenFirmware-master\buildroot
??

**Comment by guruathwal** [comment]
No
copy the TFT35 folder to your SD card, it should look like this
(your sd card drive letter):/TFT35

**Comment by Vern-K** [comment]
Got it thanks, the preheat buttons are not on there but didn't get the nylon button, did get a PEGT button so will have to look into that more... I wasn't getting what folder I needed to put where.

Thanks

**Comment by my355vega** [comment]
I am having the same issue but im not understanding that fix, could someone explain more?
