### ISSUE TITLE
TFT35 E3 V3 Meshbug

### ISSUE THREAD

**Issue by Doyle4** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1403]
Hello, I think I have found a bug and I am sure it is the screen firmware and not Marlin as its only started doing it with latest source files.

Before update, ABL menu, Mesh menu never showed up as bed levelling had yet to be done and saved.

Now when I power my printer, the mesh menu is empty and freezes the printer and a hard reboot is needed.

Any ideas?

**Comment by Doyle4** [comment]
UPDATE: I have just done bed level on my printer and the Mesh Menu was still empty and froze my printer.

So after levelling the bug is still there.

**Comment by oldman4U** [comment]
Hi.

Unfortunately I can not help with this, not using BL at the moment...

@digant73 is your man!

**Comment by Doyle4** [comment]
No worries @oldman4U Thanks for tagging someone who maybe able to help 👎

**Comment by digant73** [comment]
it seems you are using a tft version afffected by some bugs introduced by a PR. This bug was fixed in the last TFT version.
Try to use last FW (compile it. Don't use the precompiled version)

**Comment by Doyle4** [comment]
Not compiled my own before so i'll have a try now.

**Comment by Doyle4** [comment]
@digant73 That solved the issue thanks!
@oldman4U Thanks again for pointing me in the right direction!

**Comment by oldman4U** [comment]
The Pro helped you. I am just a poor boy....

😁

Happy printing

Doyle4 <notifications@github.com> schrieb am Fr. 18. Dez. 2020 um 14:05:
