### ISSUE TITLE
[BUG] After stop not realse motors and not turn off bed heatrs

### ISSUE THREAD

**Issue by DanielSan1000** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1408]
### Description

Software after click stop printing not realese motors and not turn off bead heater

**Expected behavior**
Should relase everthing and turn off bed heater

### Hardware Variant
BIGTREETECH-SKR-mini-E3
BIGTREETECH-TFT35-V3.0
Marlin 2.7.0.2

**Comment by radek8** [comment]
I can confirm the error.
When you cancel printing, the hotend heating is switched off.
Remains on: Bed heating, cooling fan and stepper motors.

**Comment by radek8** [comment]
You can solve this by enabling Cancel Gcode

cancel_gcode:M104 S0\nM140 S0\nG28 XY R10\nM107\nM84\n

**Comment by kisslorand** [comment]
This ticket should be closed, it's not a bug. Cancel gCode is there for a reason: to use and adapt it to your needs.

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by DanielSan1000** [comment]
Thanks for help. Cancel g-code is working
