### ISSUE TITLE
Multi extruder Cold extrusion prevent

### ISSUE THREAD

**Issue by myunchulshin** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1419]
![KakaoTalk_20201223_081853317](https://user-images.githubusercontent.com/69189880/102942132-de2c7b00-44f7-11eb-96da-7a58e02d381f.jpg)

I am using a multi 4 color extruder.

Raise the hot end temperature and test Extruder No. 1, and it works.

After that, if you change it to 2,3,4, an error is displayed as shown in the figure.

I want to know how to fix it.

There were no errors in previous versions of the build.

**Comment by guruathwal** [comment]
What type of multi extruder are you using? single hotend with multiple extruders or separate hotend for each extruder?

**Comment by myunchulshin** [comment]
[Marlin.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5733591/Marlin.zip)
[config.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5733595/config.zip)

Thank you 

음성듣기번역하기언어전환영어
Attached is the file.

**Comment by guruathwal** [comment]
@myunchulshin  Can you check if #1427 solves your problem?

**Comment by myunchulshin** [comment]
> @myunchulshin Can you check if #1427 solves your problem?
The problem was not solved.
