### ISSUE TITLE
[BUG] ABL not saving mesh, current build as of 12-20-20

### ISSUE THREAD

**Issue by ki6wik** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1420]
Current build as of 12/20/2020 mesh not saving after running the ABL from menu. Invalid mesh error.
Pre compiled BIGTREE_TFT_28_V3.0.26.X.BIN
Also does not load mesh saved in marlin mode in unified menu mode. Was working from build 11/16/2020.

BTT SKR 1.3
BTT TFT28 v3

**Comment by oldman4U** [comment]
Hi.

Have you already tried the build from digant73 from here: https://github.com/digant73/BIGTREETECH-TouchScreenFirmware/tree/bugfix-2020-12-20

Please let us know if this solves your problem

**Comment by ki6wik** [comment]
Yes, this did correct the problem with the mesh not being saved and the error of invalid mesh.
Thank you 

Sent from Mail for Windows 10

**Comment by oldman4U** [comment]
Purrfect👍🏻

Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by ki6wik** [comment]
The bug fix took care of the issue of not saving the bed level mesh, resolving the invalid mesh error.
