### ISSUE TITLE
[BUG] Wrong values in menus

### ISSUE THREAD

**Issue by xhejtman** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1425]
If I go into the extrude menu, select 10mm extrude (instead of default 5mm), do load/unload, then exit extrude menu, return back to extrude menu, then 5mm extrusion is displayed while active extrusion is 10mm as set in the previous visit in this menu. I believe, this happens also in some other menus - you change some values, go back and default values are displayed while the changed ones are active.

**Comment by digant73** [comment]
try PR #1415. it should fix the bug on extrude menu

**Comment by xhejtman** [comment]
confirm, it is fixed, thanks.
