### ISSUE TITLE
Not good to continue printing...

### ISSUE THREAD

**Issue by AntoszHUN** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1430]
Does resume printing after "Pause" work for anyone else?

![IMG_20201224_103848](https://user-images.githubusercontent.com/45710979/103079630-7ac44b00-45d4-11eb-9eb4-037c05e3b4ef.jpg)
![IMG_20201224_103642](https://user-images.githubusercontent.com/45710979/103079643-8152c280-45d4-11eb-99f8-1067084f0e1b.jpg)
![IMG_20201224_103636](https://user-images.githubusercontent.com/45710979/103079655-857ee000-45d4-11eb-8929-f2c01f6a9a51.jpg)

I pause printing. Then I wanted to continue after that. The machine pushed the head into the print. Something is not right. In previous firmware, it still worked.

**Comment by oldman4U** [comment]
Hi.

Can you try to find which PR broke this?

**Comment by AntoszHUN** [comment]
I searched. But I don't know which statement could have changed it.

**Comment by oldman4U** [comment]
There have been some issues with config.ini. Try it again and let me know. Are you printing from on board sd? Maybe a movie would help.

**Comment by AntoszHUN** [comment]
> There have been some issues with config.ini. Try it again and let me know. Are you printing from on board sd? Maybe a movie would help.

All right. I'll see as soon as I have time. Yes, I print from a TFT card reader.

**Comment by oldman4U** [comment]
Any news related to this issue my friend?

**Comment by AntoszHUN** [comment]
> Any news related to this issue my friend?

I updated the firmware. but I haven't tried the pause yet.

**Comment by oldman4U** [comment]
Using the current firmware for the TFT

https://user-images.githubusercontent.com/54359396/103466309-322f2f00-4d44-11eb-8028-39ebc4f08ade.mov

**Comment by AntoszHUN** [comment]
> Using the current firmware for the TFT
> 
>  Pause.Print.mov

It seems good to me too. I will also close the topic. Thank you!

**Comment by oldman4U** [comment]
Works?

Zs.Antal <notifications@github.com> schrieb am Sa. 2. Jän. 2021 um 21:58:

**Comment by oldman4U** [comment]
Perfect!

👍🏻

Zs.Antal <notifications@github.com> schrieb am Sa. 2. Jän. 2021 um 21:58:
