### ISSUE TITLE
[BUG] Bad hotend and bed temperature update on status screen.

### ISSUE THREAD

**Issue by radek8** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1434]
Bad hotend and bed temperature update on status screen.
If I turn on the hotend heating and the bed turns off after reaching the temperature, the temperature on the status screen is updated and it can be seen that the temperature is falling.
If I restart the printer when the temperature is reached, the printer will display a high temperature. The temperature of the hotend and the bed drops, but the display still shows the high temperature it read after the reset.

SKRV1.4 + TFT35E3V3.0
Marlin Bugfix 2.0 from today
TFT own compilation from today:
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/commit/46d7434d8b463f160130543a2c5751aaeff1fd0c

**Comment by radek8** [comment]
The second option is to simulate this problem.
Marlin has a new setup. Can set the heating to switch on automatically when leveling starts (G29)

![image](https://user-images.githubusercontent.com/46979052/103142626-5799b880-4706-11eb-810f-e2fe5cd82401.png)

I will enable the preheat function before leveling in Marlin
I start leveling. The bed is heated and leveled in the bed. After leveling, the heating switches off automatically.
I jump to the status screen, but the status screen does not respond to a falling temperature and still shows a high preheat temperature.

**Comment by kisslorand** [comment]
For some reason your Marlin is not auto-reporting temperatures. Can you check this hypothesis?

**Comment by radek8** [comment]
There will be no problem with that
this is a record of communication on the serial line,
the hot end temperature is reported at 29 ° C but the display currently shows 36 ° C

**Comment by kisslorand** [comment]
Is your nozzle other than T0?

**Comment by radek8** [comment]
If I open the menu and return, the temperature is still bad.
if I open the heating menu, the temperature value is updated after 1 s.
after returning to the status screen, the temperature is updated correctly.

To update the wallpaper, I need to open the heating menu.

**Comment by radek8** [comment]
the same behavior is in bed and I don't have 2 beds :-)

**Comment by kisslorand** [comment]
OK, than the culprit is found.
Need to send M155 Sxx

**Comment by radek8** [comment]
I can already see the difference

**Comment by radek8** [comment]
printer response after restart

![image](https://user-images.githubusercontent.com/46979052/103143045-25d91f80-470f-11eb-889e-68db3ffafe39.png)

printer response after opening the heat menu

![image](https://user-images.githubusercontent.com/46979052/103143047-3093b480-470f-11eb-9ee1-3e1fd4d2cf65.png)

**Comment by kisslorand** [comment]
After you restart the printer, it looses the M155 Sxx command. So there's a need to send it again

**Comment by radek8** [comment]
The TFT cannot analyze the temperature message line if it contains the word OK

**Comment by kisslorand** [comment]
it can:
"      if(ack_seen("ok"))
      {
        infoHost.wait = false;
      }
      // parse temperature
      if((ack_seen("@") && ack_seen("T:")) || ack_seen("T0:"))
      {
        heatSetCurrentTemp(NOZZLE0, ack_value()+0.5f);
        if(!heatGetSendWaiting(NOZZLE0)) {
          heatSyncTargetTemp(NOZZLE0, ack_second_value()+0.5f);
        }
        for(uint8_t i = 0; i < MAX_HEATER_COUNT; i++)
        {
          if(!heaterIsValid(i)) continue;
          if(ack_seen(heaterID[i]))
          {
            heatSetCurrentTemp(i, ack_value()+0.5f);
            if(!heatGetSendWaiting(i)) {
              heatSyncTargetTemp(i, ack_second_value()+0.5f);
            }
          }
        }"

**Comment by radek8** [comment]
The status screen cannot process the m105 command
If heating is started, M155 is started,
if I reset the printer, the M155 command is executed from the Heat.c menu, or after switching on the heating again

![image](https://user-images.githubusercontent.com/46979052/103143131-2d012d00-4711-11eb-9c9f-41943152e69e.png)

![image](https://user-images.githubusercontent.com/46979052/103143201-c7617080-4711-11eb-93e2-c043cfc0366e.png)

**Comment by radek8** [comment]
If the TFT cannot analyze the M105 then it is unnecessary to send it and burden the communication if the M155 is used
using both in parallel is unnecessary.

**Comment by kisslorand** [comment]
M105 is sent only if infoMachineSettings.autoReportTemp is false, So, as I said, M155 Sxx must be sent again ig printer was disconnected and reconnected.
My latest PRs burned me out so I leave it to fellow colleagues to deal with it if they have the time.

**Comment by radek8** [comment]
After the printer restarts, find the temperature, but no longer update it.
The problem is either in the analysis of the response to the M105, and everyone will have it, or the format of the response has changed in the new version of Marlin.

Can you see in what format your Marlin corresponds to M105?

**Comment by kisslorand** [comment]
Not tonight (1:48AM here), maybe tomorrow.

**Comment by radek8** [comment]
0:49, I go to sleep :-)

**Comment by kisslorand** [comment]
Send: M105
Recv: ok T:20.31 /0.000 B:20.31 /0.000 @:0 B@:0

**Comment by radek8** [comment]
The repair works, thank you.
@guruathwal, not a bug in ParseACK.c yet?

![image](https://user-images.githubusercontent.com/46979052/103154454-99267400-4797-11eb-8ff1-2e9cab06feda.png)


should not be correct wording:
  if (ack_seen ("@") && (ack_seen ("T:") || ack_seen ("T0:")))

**Comment by guruathwal** [comment]
@radek8  it is correct.  some marlin versions report temperatures with `T0:` when there are more than 1 hotends. marlin also reports heater power with `@` which is being double-checked along with `T:` to ensure that the received string is a temperature update.

**Comment by radek8** [comment]
@guruathwal 
It is currently
If  (( a  && b) || c )
I think it should be
If  (a && ( b || c ))

**Comment by guruathwal** [comment]
@radek8 It is not necessary that `@` is always included in the temperature string. It was added to make it compatible with Repetier firmware because without it other responses with `T:` were getting parsed as temperature. This was changed in https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/959. Earlier it was like this: 
```C
if(ack_seen("ok T:") || ack_seen("T0:"))
```


![image](https://user-images.githubusercontent.com/22422544/103169574-f4716880-4862-11eb-8c28-db86e2858f1b.png)

**Comment by radek8** [comment]
OK
Thank you.
