### ISSUE TITLE
BTT TFT35 V2.0 firmware not mentioned in the list of files - which one should I use for the screen?

### ISSUE THREAD

**Issue by Feppofap** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1439]
It seems V2 is gone from the list - is that because you need to use V3 for that screen?

**Comment by kisslorand** [comment]
If you compile your own, there is an option for BTT TFT V2.0.

**Comment by radek8** [comment]
Use this one
[BIQU_TFT35_APP1_V2.0.26.x.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5743656/BIQU_TFT35_APP1_V2.0.26.x.zip)

**Comment by radek8** [comment]
![image](https://user-images.githubusercontent.com/46979052/103160308-85006800-47d3-11eb-85fd-d05b195b32c0.png)

**Comment by Feppofap** [comment]
OK - thanks. I didn't think that was the righrt one, since irt says APP in the filename :)
