### ISSUE TITLE
[BUG] Freezing TFT35 E3 V3

### ISSUE THREAD

**Issue by Bastlwastl84** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1442]
Freezing 
Power on
Preheat Nozzle PETG
also no Update of Temperature
Move
Messange Please wait ant non responsing
[config.ini.txt](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5746771/config.ini.txt)
resetted yesterday with reset.txt
firmware from yesterday
icons, font and languagefile from yesterday
https://youtu.be/bPxHzax0d1M
i also changed the cable to TFT with an old shielded USB Cabled

**Comment by kisslorand** [comment]
This reminder message appears only when the command queue is full.
Just checked and cannot reproduce the issue, no background process fills up the command queue.
Can you check the communication between TFT and motherboard after you press preheat?

**Comment by Bastlwastl84** [comment]
![20201228_132017](https://user-images.githubusercontent.com/69717507/103214097-d877d080-490f-11eb-882b-1cd764306c30.jpg)
![Uploading 20201228_131927.jpg…]()

![20201228_131937](https://user-images.githubusercontent.com/69717507/103214035-b9793e80-490f-11eb-95cc-4dfc67525278.jpg)
![20201228_131942](https://user-images.githubusercontent.com/69717507/103214040-bc742f00-490f-11eb-98db-ee38134d1e2b.jpg)
![20201228_131810](https://user-images.githubusercontent.com/69717507/103214044-bf6f1f80-490f-11eb-95d3-d738d77d0bd3.jpg)
![20201228_131957](https://user-images.githubusercontent.com/69717507/103214052-c302a680-490f-11eb-9ffd-f055122dde31.jpg)
![20201228_131901](https://user-images.githubusercontent.com/69717507/103214061-c72ec400-490f-11eb-8995-fe9599c44a01.jpg)
![20201228_132002](https://user-images.githubusercontent.com/69717507/103214068-ca29b480-490f-11eb-9334-f91f404882c8.jpg)
![20201228_131947](https://user-images.githubusercontent.com/69717507/103214074-cdbd3b80-490f-11eb-9707-3c65c04677c7.jpg)
![20201228_131952](https://user-images.githubusercontent.com/69717507/103214084-d1e95900-490f-11eb-88b8-5fc7ad76f9d7.jpg)
![20201228_131926](https://user-images.githubusercontent.com/69717507/103214094-d6157680-490f-11eb-99d4-7d1b6f064647.jpg)

**Comment by Bastlwastl84** [comment]
![20201228_131637](https://user-images.githubusercontent.com/69717507/103214239-32789600-4910-11eb-96b3-433de0addb5a.jpg)
![20201228_131910](https://user-images.githubusercontent.com/69717507/103214260-43290c00-4910-11eb-8df0-8b7a8d4c4018.jpg)
![20201228_131916](https://user-images.githubusercontent.com/69717507/103214265-46bc9300-4910-11eb-92a1-8eb2320cde49.jpg)

![20201228_131932](https://user-images.githubusercontent.com/69717507/103214289-576d0900-4910-11eb-8ac2-10df9f064337.jpg)
![20201228_131937](https://user-images.githubusercontent.com/69717507/103214298-5a67f980-4910-11eb-8a46-6927abc7a4c9.jpg)
![20201228_131942](https://user-images.githubusercontent.com/69717507/103214303-5f2cad80-4910-11eb-9927-31cc7e680d31.jpg)
![20201228_131957](https://user-images.githubusercontent.com/69717507/103214313-63f16180-4910-11eb-8b97-d190df2e36ca.jpg)
![20201228_132002](https://user-images.githubusercontent.com/69717507/103214315-6653bb80-4910-11eb-9cb8-7520a183358a.jpg)
![20201228_131947](https://user-images.githubusercontent.com/69717507/103214322-6a7fd900-4910-11eb-9788-487e0d34a737.jpg)
![20201228_131952](https://user-images.githubusercontent.com/69717507/103214330-6e136000-4910-11eb-98b9-e00a6e38061d.jpg)
![20201228_132017](https://user-images.githubusercontent.com/69717507/103214335-723f7d80-4910-11eb-9e4b-8500cd252abb.jpg)
![20201228_131927](https://user-images.githubusercontent.com/69717507/103214343-75d30480-4910-11eb-9ae7-bd4e4008d5a3.jpg)
![20201228_132007](https://user-images.githubusercontent.com/69717507/103214352-79668b80-4910-11eb-8d3b-6eb6540c90e8.jpg)
![20201228_132012](https://user-images.githubusercontent.com/69717507/103214360-7cfa1280-4910-11eb-9bf9-6c3bf9e41867.jpg)

**Comment by Bastlwastl84** [comment]
Couldn't it be done like before, if you had edited your configuration.h andxself compiled, than you don't need cinfig.bin

**Comment by kisslorand** [comment]
It seems you do not have the latest version where the memory allocated for language file is increased by 1KB.

**Comment by Bastlwastl84** [comment]
I downloaded it today again and than that many errors. I did inserted all settings identically. After that i was frustrated and installed the tft Firmware again from June.

**Comment by kisslorand** [comment]
[BIGTREE_TFT35_V3.0_E3.26.x.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5747984/BIGTREE_TFT35_V3.0_E3.26.x.zip)

Put these on your SD Card and edit config.ini to your needs. Pay attention to the baudrate, you have to write the baudrate itself, not its index in the list.

**Comment by Bastlwastl84** [comment]
I can try tomorrow. Printing now in Marlin Mode.

**Comment by oldman4U** [comment]
This user believes that he does not need config.ini even several users already told him.

**Comment by Bastlwastl84** [comment]
> This user believes that he does not need config.ini even several users already told him.

my old bin had the settings i selected at configuration.h?

**Comment by kisslorand** [comment]
ZIP file reuploaded, download it again.

**Comment by Bastlwastl84** [comment]
do you also have the german language file to integrate, too, when testing tomorrow?

**Comment by Bastlwastl84** [comment]
reset.txt, than powered off, reboot with this firmware and config.... only 1 error, cause of hotend maximum Temperature

**Comment by Bastlwastl84** [comment]
[btttft35e3v3.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5751746/btttft35e3v3.zip)

**Comment by Bastlwastl84** [comment]
Connected with Pronterface after that: While the TFT35 is not responsive i could controle the Printer with that tool. Plugged in esp Module. Responsive ESP01 Module, while not Responsive TFT. Same with ESP32

**Comment by kisslorand** [comment]
So the TFT freezes only if you go to preheat and after press Move? No other scenario leads to freezing?

**Comment by Bastlwastl84** [comment]
> So the TFT freezes only if you go to preheat and after press Move? No other scenario leads to freezing?
> Do you have M155 enabled in Marlin?

my marlinconfig is under last picture

**Comment by kisslorand** [comment]
So the TFT freezes only if you go to preheat and after press Move? No other scenario leads to freezing?

**Comment by Bastlwastl84** [comment]
i could try more tomorrow (printing in marlin mode now)

**Comment by Bastlwastl84** [comment]
it must be a serial communication problem. 

This Evening I plugged in, before this print in Marlin Mode, the ESP32-Cam, Now I lost communication from ESP32-Cam to Board again. I changed the cable to TFT with a old USB-Cable, i crimped, but nothing changed. 

The ESP32-Cam is Plugged in at RX3 and TX3 at TFT35. I asked Luc about Serial at ESP3D config. #define ESP_SERIAL_OUTPUT USE_SERIAL_0 
Luc said "yes if you use SERIAL0
which is the default one - same as usb"

**Comment by kisslorand** [comment]
Glad you find a possible issue!

**Comment by Bastlwastl84** [comment]
> Glad you find a possible issue!

perhaps i'll try Marlin 2.0.5.x to see, if there's the bug, too. 
but now printing Parts for a Veron 2.4

**Comment by Bastlwastl84** [comment]
![capture_20201231_180444_002](https://user-images.githubusercontent.com/69717507/103438843-f018c700-4c37-11eb-81a5-feeda5624708.jpg)
must be a Serial Problem, but where it comes from?

**Comment by Bastlwastl84** [comment]
at TFT 5V is 4,8V, Could that be the Problem?. Where to adjust?

**Comment by Dieter59-GIT** [comment]
I have the same problem and was able to find out some things.
I can confirm the assumption for a serial port problem.
My supply voltage is also 4.8V, but this is not a problem. The TFT35 board still works in my tests with about 4V.
I found out that the supply voltage of the printer controller board has a big influence on the occurrence of the error.
My board: SKR1.4 Turbo
Power supply: 24V (with quite strong disturbances when switching on the hotbed)
When printing, disturbances in the serial transmission occur several times during printing (wrong Gcode and wrong traverses) or the printer freeze sometimes. 
My attempts:
1. External supply of the SKR1.4 with a 11.4V-Lipo-battery -> print runs without errors
2. External supply of the SKR1.4 with two in series connected lipo-batteries (22.8V) -> print has failures
3. Internal 24v-supply via DC/DC-converter reduced to 13V and SKR1.4 operated with it -> print runs without errors

No. 3 (a DC/DC converter with filter element) is my solution at the moment.

**Comment by Bastlwastl84** [comment]
Could be a buffermodule, like the BTT UPS 24V (https://www.biqu.equipment/collections/all-product/products/btt-ups-24v-v1-0-resume-printing-while-power-off-module), bring the solution?

**Comment by Dieter59-GIT** [comment]
My hotend and hotbed is also controlled by external mosfet.
The disturbances on my 24V supply appear at high current load (narrow pulses with approx. f=140kHz). 
Whether the modules brings an improvement I can not say.
I have tried filter circuits of capacitors and inductors, but the problem always came back. Only the reduction of the 24V supply voltage to approx. 12V made error-free prints possible.
An adjustable DC/DC converter with 3-5A is sufficient for the reduction. 
At this point, however, I can't say what exactly is causing the communication problem.
It looks like synchronization is lost when sending char. This causes the sent data set to be garbled. If it happens in the numeric area, the print head goes strange ways, if it happens at the position of the G-command, an error message "Unknown Gcode ..." appears.  
I realize that this does not fix the cause but only the effect. 
However, I will continue to observe the behavior. 
Maybe it can be fixed by software (e.g. more stable RS232 communication).

**Comment by Bastlwastl84** [comment]
When powering the TFT35 i got many fast short beeps and at Display after Boot this messages. Correctly no SD Card is at Mainboard.
![20210103_180325](https://user-images.githubusercontent.com/69717507/103484324-40d22080-4dee-11eb-95cd-840499ce3d0a.jpg)

**Comment by Bastlwastl84** [comment]
![20210103_224750](https://user-images.githubusercontent.com/69717507/103489572-c9b08280-4e15-11eb-80d5-29914ea765cf.jpg)
![20210103_224638](https://user-images.githubusercontent.com/69717507/103489574-cb7a4600-4e15-11eb-8894-aa30f9e4019a.jpg)

**Comment by Bastlwastl84** [comment]
Again not updating
https://youtu.be/4fVjKl23IGE

**Comment by Bastlwastl84** [comment]
perhaps that? https://github.com/MarlinFirmware/Marlin/issues/20673

**Comment by Bastlwastl84** [comment]
I updated now again, freezing when opening Extruder.
