### ISSUE TITLE
How select the correct .bin?

### ISSUE THREAD

**Issue by nachogil** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1443]
Hi,

I'm having some difficulties to update my Bigtreetech TFT35 V3.

Basically there are those .bin options:

- BIGTREE_TFT35_V3.0_B1.26.x.bin
- BIGTREE_TFT35_V3.0_E3.26.x.bin
- BIGTREE_TFT35_V3.0.26.x.bin

But I'm not sure which .bin I must use
This is is my TFT

![IMG_20201228_105153](https://user-images.githubusercontent.com/378097/103209683-904eb300-48fb-11eb-8468-4241db0b8844.jpg)

**Comment by kisslorand** [comment]
It seems "BIGTREE_TFT35_V3.0.26.x.bin" would be the one for your TFT.

**Comment by oldman4U** [comment]
Hi.

According to the attached screenshot, you own a BIGTREETECH TFT35 v3, so firmware BIGTREE_TFT35_V3.0.26.x.bin is the correct variant.

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Nine day wonder.

Answer or close this ticket.
