### ISSUE TITLE
TFT 70 no touch funktion after update

### ISSUE THREAD

**Issue by DeltaLeines** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1464]
Hello, I bought a BTT TFT70 for my 3D printer. After updating to the latest firmware, the touch function no longer works. What can be the reason? Printer Board SKR1.4 turbo, Marlin 2.0.x.
Greetings Linus

**Comment by Codel1417** [comment]
create a file called reset.txt and place it in the sd card

**Comment by Sebazzz** [comment]
Same here, TFT50.

**Comment by oldman4U** [comment]
Please read this completely and follow the instructions step by step to install and update the TFT:
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware#connect-the-tft-to-the-mainboard

**Comment by Sebazzz** [comment]
Reset.txt helped.

**Comment by oldman4U** [comment]
@DeltaLeines Any news?

**Comment by DeltaLeines** [comment]
No

 

Von: oldman4U <notifications@github.com> 
Gesendet: Donnerstag, 31. Dezember 2020 10:10
An: bigtreetech/BIGTREETECH-TouchScreenFirmware <BIGTREETECH-TouchScreenFirmware@noreply.github.com>
Cc: DeltaLeines <dietmarundsandra@online.de>; Mention <mention@noreply.github.com>
Betreff: Re: [bigtreetech/BIGTREETECH-TouchScreenFirmware] TFT 70 no touch funktion after update (#1464)

 

@DeltaLeines <https://github.com/DeltaLeines>  Any news?

**Comment by oldman4U** [comment]
Ok

DeltaLeines <notifications@github.com> schrieb am Do. 31. Dez. 2020 um
10:11:

**Comment by DeltaLeines** [comment]
Hello, the problem is fixed. The reset with the reset.txt helped. Many thanks for the support.
Best Linus
