### ISSUE TITLE
Old Marlin interface detects printer, touchscreen doesn't...

### ISSUE THREAD

**Issue by HeartlessDarkangel** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1465]
*I just upgraded my Ender 3 to the SKR Mini E3 V2 and installed everything accordingly and even got the BLTouch working flawlessly, I can use the "old" screen no problem, but when I switch to the touchscreen version it keeps displaying "Printer not found"
I've checked the RS232 cable for continuity and its plugged in properly with the single pin towards the rear of my Ender 3
What could possibly be causing this?
Do I have a defective screen?
How do I perform an update?
TIA!

**Comment by oldman4U** [comment]
Hi.

Here is how you perform an update. Read it completely and follow the instructions step by step.

The message means, that the TFT can not see the mainboard, which can have the following reasons:

1. wrong type of serial port defined in Marlin
2. baud rate in Marlin and TFT does not match
3. TFT broken
4. mainboard broken
5. RS232 cable broken or wrong connected

**Comment by oldman4U** [comment]
Any news?

**Comment by HeartlessDarkangel** [comment]
> 
> 
> Any news?

Still can't get it to recognize the touchscreen version, ended up just installing the factory screen back...

**Comment by oldman4U** [comment]
Do you need further help?

HeartlessDarkangel <notifications@github.com> schrieb am Do. 31. Dez. 2020
um 16:35:

**Comment by HeartlessDarkangel** [comment]
> Do you need further help? HeartlessDarkangel <notifications@github.com> schrieb am Do. 31. Dez. 2020 um 16:35:
> […](#)

I just reflashed the newest firmware and updated fonts and icons and it’s now working 👏🏼
Thank you for your support.

**Comment by oldman4U** [comment]
👍🏻

Happy printing

HeartlessDarkangel <notifications@github.com> schrieb am Do. 31. Dez. 2020
um 19:27:
