### ISSUE TITLE
[Q]  Option "level_edge_distance:

### ISSUE THREAD

**Issue by radek8** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1467]
@guruathwal Why did you remove the option "level_edge_distance:" from the Config.ini file?
PR #1438

**Comment by guruathwal** [comment]
Oh, I would never remove it. It must have got removed during rebase. I will add it again. Thank you for pointing it out.

**Comment by digant73** [comment]
already fixed in my current PR
