### ISSUE TITLE
[BUG] Typo German language Pack

### ISSUE THREAD

**Issue by Bastlwastl84** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1474]
Typo. Should be "Dateien als Liste" and not "Datein als Liste"
![16097116519937826131123408737264](https://user-images.githubusercontent.com/69717507/103489938-a0452600-4e18-11eb-9fbe-41ea5252ede9.jpg)

**Comment by oldman4U** [comment]
If digit73 would not have fixed it already, it would be a good entry for trying to contribute. Especially the language files are very easy.

**Comment by digant73** [comment]
Sure. However It was also fixed
