### ISSUE TITLE
Z motion bug

### ISSUE THREAD

**Issue by wtfiAndrewNelson** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1485]
### Description

Z feed rate is the same as X and Y, meaning that if you use the manual buttons to Move Z it's too fast and the stepper can not move the Z this fast. This is for Slow, Normal, and Fast. I have changed the Slow speed to make it possible to use the Move Z function but that also means that X and Y are now at a crawl.

### Steps to reproduce

1. Press Menu button
2. Press Move button
3. Press Z up or Z down button(s)

**Expected behavior**

Z should raise and lower at Slow, Normal and Fast speeds (but they are all too high)

**Actual behavior**

Grinding Sound and no motion

### Hardware Variant

BIGTREETECH TFT35-E3 V3.0

### TFT Firmware Version & Main Board Firmware details

BIGTREETECH SKR Mini E3 V2

**Comment by kisslorand** [comment]
Z max speed should be set in Marlin:
#define DEFAULT_MAX_FEEDRATE          { X, Y, Z, E0 [, E1[, E2...]] }

**Comment by wtfiAndrewNelson** [comment]
The TFT is over riding the marlin features.

**Comment by kisslorand** [comment]
Please check:
Menu -> Settings -> Machine -> Parameter -> Max Feed Rate -> /Z

What value do you have there?

**Comment by wtfiAndrewNelson** [comment]
12, but it's being ignored by the move button. If I change the slow feedrate in the firmware and re-load it, which is what I have done, then it's fine but like I said that makes the x and y feedrate painfully slow.

**Comment by kisslorand** [comment]
That is really strange! Max feedrate cannot be override. This why it is called MAX feedrate.
I just checked, my printer obeys the max feedrate.
I can tell you for sure, the TFT cannot override the MAX feedrate.
Please check what is your Z acceleration, if above 1000 please try to set it at 1000.
If Z acceleration is at 1000 and still have problems with Z move, set the max feedrate to 10, 8... and check again.

**Comment by wtfiAndrewNelson** [comment]
Marlin max acceleration is 500

**Comment by wtfiAndrewNelson** [comment]
In configuration_adv.h this is my manual move definition:
#define MANUAL_FEEDRATE { 50*60, 50*60, 4*60, 2*60 } 
and it's ignored by the TFT which sets it to slow 1000 normal 3000 fast 5000 and that is superseding the marlin firmware. I have changed my slow to 300 and it works but it takes over all feedrates x y z

**Comment by kisslorand** [comment]
I am looking at the code, it is not ignored.

**Comment by wtfiAndrewNelson** [comment]
But it is, the TFT is superseding the Marlin, I don't understand how but it is.

**Comment by kisslorand** [comment]
OK, let's try a different approach.
What if you send a gCode in the terminal? Let's say `M203 Z10` and than `G0 Z100 F5000`.

**Comment by wtfiAndrewNelson** [comment]
I just gave that a try and it ran at 5000ish as it was clearly missing step running that fast. So, M203 was ignored.

**Comment by wtfiAndrewNelson** [comment]
I also ran M501 and my feed speed is still the same in the eprom. So both speeds were being ignored and the gcode feedrate superseded it. Unless I am missing something, the TFT commands supersede the Marlin firmware.

**Comment by kisslorand** [comment]
It seems to me that Marlin is ignoring the M203 setting. I cannot imagine why.
You sent gCodes, it doesn't matter where you sent them from.
Check the same with Pronterface or Octoprint or whatever else.

**Comment by wtfiAndrewNelson** [comment]
Yes it takes it and I get the ok. When I run M503 it reports it as z10. Gcode command supersedes it and it attempts to run at 5000ish buzzing all the way with missed steps. Then when I press the Z up or down button in my new slow speed of 300 it runs fine and at 300. So, once again, the commands from the TFT are apparently taking precedent over the Marlin firmware settings and the volatile memory setting and the eprom settings. So, like I said. The TFT is taking charge and not the Marlin. Now this may be a problem with the BIGTREETECH SKR Mini E3 V2 but it it behaving like it is the TFT overriding everything.

**Comment by kisslorand** [comment]
Just test it please with Pronterface or any other external program/device that can send gCodes over USB to Marlin.

**Comment by wtfiAndrewNelson** [comment]
Okay. I just tested it by USB and the same thing has happened. So it's not the TFT it's the Marlin limits being ignored by something on the BIGTREETECH SKR Mini E3 V2. I will investigate further. Thank you for your help.

**Comment by wtfiAndrewNelson** [comment]
However, that being said. I still need to be able to define Z feedrate to be different than X and Y so that even if there was not a bug in the BIGTREETECH SKR Mini E3 V2 that is allowing gcode feedrates to exceed the maximum feedrate in the Marlin firmware, I would still be able to define a slow, normal and high speed for my Z that is not just the XY feedrate limited to the Z maximum. Maybe this isn't a 'bug' but it's an oversight in the control setup of the TFT

**Comment by oldman4U** [comment]
@wtfiAndrewNelson 

Could you please check PR #1487 to see if this solves your issue.

Thank you

**Comment by wtfiAndrewNelson** [comment]
That seem to be just the thing.

**Comment by oldman4U** [comment]
Sounds good. 

Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Thank you
