### ISSUE TITLE
[BUG] Marlin bugfix-2.0.x - BTT GTR V1.0 - stepper motors at re-start

### ISSUE THREAD

**Issue by DrumClock** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1492]
After turning on the power or restarting the printer:

Some stepper motors "jerk" and then lock for a few seconds.
As soon as the FW starts, the stepper motors are released.

It does not matter if the driver is controlled by UART, SPI or STEP/DIR.

**Comment by oldman4U** [comment]
How is this related to the firmware of the touchscreen?

**Comment by DrumClock** [comment]
Hi @oldman4U 
Unrelated, sorry.
I'll create it in the right section, sorry

**Comment by oldman4U** [comment]
No reason to be sorry. Hope someone can help you.

Happy printing

DrumClock <notifications@github.com> schrieb am Sa. 9. Jän. 2021 um 21:28:
