### ISSUE TITLE
Cant read SD Onboard card (TFT35 / SKR TURBO

### ISSUE THREAD

**Issue by Grex3D** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1493]
HI,

Im trying to print with the sd card onboard but nothing work.

I use sdsuuport on/off
SD lcd connection on/off
etc

Nothing works. When i go in print > onboard SD the screen beep 2 or 3 time and return to print menu.

Someone can help me ?

**Comment by blueeagle69** [comment]
Hi.

Check Configuration_adv.h in the Marlin firmware to see if the following is set.
**#define SDCARD_CONNECTION ONBOARD**

**Comment by Grex3D** [comment]
> Hi.
> 
> Check Configuration_adv.h in the Marlin firmware to see if the following is set.
> **#define SDCARD_CONNECTION ONBOARD**

Yep but in the last version of Marlin bugfix i cant find this line.

**Comment by blueeagle69** [comment]
Strange, I just checked the latest Marlin Bugfix code and the setting is there.
Line 1396.

**Comment by Grex3D** [comment]
OK !!!! i understand now :)

I have to replace  LCD by ONBOARD !

That why i cant find #define SDCARD_CONNECTION ONBOARD :D

Im gonna try :)

**Comment by blueeagle69** [comment]
No probs.
Hope it sorts it.

**Comment by Grex3D** [comment]
Perfect its work
(And the TFT35 SD work too)
 thank you :)
