### ISSUE TITLE
[BUG] problem With Serial Communication

### ISSUE THREAD

**Issue by Bastlwastl84** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1502]
Problem with ESP32-Cam and Serial Communication. Can often not send gcode to TFT35 E3 V3 and SKR Mini E3 V2. At TFT is at Top "Please Wait ..." same happens at TouchMode, too, but i can read the Serial data.
![20210110_130627](https://user-images.githubusercontent.com/69717507/104122465-770b2500-5345-11eb-8a55-e4fdd1265dbd.jpg)
![Screenshot_20210110-130607_Chrome](https://user-images.githubusercontent.com/69717507/104122467-796d7f00-5345-11eb-926d-1a5a5e715c7b.jpg)
![Screenshot_20210110-130600_Chrome](https://user-images.githubusercontent.com/69717507/104122556-e84ad800-5345-11eb-9153-ab943b07b108.jpg)

Connected at UART-Port at TFT

[2021-01-08 skr mini v2 marlin + tft35e3v3.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5791706/2021-01-08.skr.mini.v2.marlin.%2B.tft35e3v3.zip)

**Comment by cjj25** [comment]
This is probably related to my issues seen here (with a fix): https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/1488#issuecomment-765656771
