### ISSUE TITLE
[FR][BUG] M117 messages are not showing if used in custom gcode

### ISSUE THREAD

**Issue by GenaUser** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1503]
M117 messages are not displayed on the screen if they are sent by a custom gcode.
On the other hand, they are shown if you use the screen terminal.
There is always a doubt about taking into account a selection on a touch screen. Being able to display a message confirming a gcode execution is important. 
For example, to confirm the TMC settings activation
(ex: M569 S1\ n M117 stealthChop activated)

**Comment by oldman4U** [comment]
In this case the search function works

Please see #1050

Thank you

**Comment by oldman4U** [comment]
Have you checked the ticket I mentioned above?

**Comment by oldman4U** [comment]
It would be great if you could answer to your own ticket.

Thank you

**Comment by 3dfixer** [comment]
Configuration_adv.h

#define HOST_ACTION_COMMANDS
#if ENABLED(HOST_ACTION_COMMANDS)
#define HOST_PROMPT_SUPPORT
#endif
