### ISSUE TITLE
[FR] Access to Smart Filament Detection settings in screen settings

### ISSUE THREAD

**Issue by GenaUser** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1504]
Would it be possible to allow the modification of the smart filament detector parameters in the machine settings on the screen?
These settings may need to be changed depending on the material specifications or printing type.
Downloading the firmware each time is not functional, especially since it is not possible during printing.

**Comment by oldman4U** [comment]
You can change the settings by changing the config.ini using a text editor.

If you want, I can add this feature request to the FR list

**Comment by sarvenn** [comment]
@oldman4U could please add invert filament run out logic option in the feature menu as well?
Mine was wrong and I changed it from config.ini file successfully. However these kind of features would be very good to have in the screen as standalone.

**Comment by GenaUser** [comment]
Thanks @oldman4U, you can add this feature to your FR list.
The important for this functionality is allowed access to the parameters directly on the screen, and if possible that they can be modified during printing.

The proposition of @sarvenn is relevant, I agree.

**Comment by oldman4U** [comment]
Done. Hope this will attract a developer soon.
