### ISSUE TITLE
 icon description?

### ISSUE THREAD

**Issue by Aleks-MO** [bigtreetech/BIGTREETECH-TouchScreenFirmware#152]
There are so many icons, can someone describe what they are responsible for? Can make a map of icons?

**Comment by thisiskeithb** [comment]
They are named based on their function. What info are you looking for specifically?

**Comment by Aleks-MO** [comment]
Lightbulb icons? When printing, is the MORE icon at the bottom right?

**Comment by thisiskeithb** [comment]
The light bulb icons named `RGB_*` are for controlling RGB LEDs and the `More` screen is for controlling your fan, LED color, extruder, filament sensor, etc.

Improved documentation is in the works, but keep in mind that this firmware is being actively developed by BigTreeTech and the community, so these features are subject to change.

**Comment by Aleks-MO** [comment]
Ok/

**Comment by thisiskeithb** [comment]
[Here's an older guide](https://github.com/bigtreetech/BIGTREETECH-TFT35-V1.2/blob/f8e52a5aafb071d30a86764b5d5fd72eda0a5430/TFT35%20screen%20customize.pdf) in the TFT35 V1.2 repo, but many icons and screens have been updated since that was originally posted.

**Comment by Aleks-MO** [comment]
This is how to collect new icons, you can explain to children what is responsible for what. Colored icons are more informative, red “heat”, Blue “movements” green “action” 
![Kamil Kaleta](https://user-images.githubusercontent.com/22274265/68648602-6a185900-0529-11ea-9e21-3b1189040219.jpg)

**Comment by guruathwal** [comment]
> Lightbulb icons? When printing, is the MORE icon at the bottom right?

When printing the third icon in second row is Percentage.bmp o to open the speed and flow setting.
Tune.bmp makes more sense.

**Comment by kkaleta** [comment]
> This is how to collect new icons, you can explain to children what is responsible for what. Colored icons are more informative, red “heat”, Blue “movements” green “action”


These icons will not match the latest firmware and I do not plan to update them. But I'm working on something new, less childish but still colorful.
![20191118_065355](https://user-images.githubusercontent.com/4312668/69076483-db796f80-0a33-11ea-8c71-b3a94da97c4b.jpg)

**Comment by thisiskeithb** [comment]
> These icons will not match the latest firmware and I do not plan to update them.

Any plans to release the source files so we can try to bring it up to date? It’s a nice icon pack, but wouldn’t be usable for anyone other than those with the exact firmware version you’re running.

**Comment by Aleks-MO** [comment]
I'm sorry. Everything turns into a mess .. (It seems time to change to TFT MKS.
