### ISSUE TITLE
label change and move

### ISSUE THREAD

**Issue by 3dfixer** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1532]
a couple of ideas for the TFT print menu
could we change the stop label to cancel?
could we swap the stop(cancel ) icon position with the more icon.
when I'm backtracking out of the "more" submenus i often tap once too often and stop print, most annoying

**Comment by oldman4U** [comment]
I hope you get a warning before the print really stops?

**Comment by oldman4U** [comment]
According to Gurmeet you can change the button label in the language file.

**Comment by oldman4U** [comment]
Would be great if you could answer your own ticket.

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by 3dfixer** [comment]
> Please help the community and close the ticket once you do not need it anymore. Thank you

why would i close it when no action has been taken???
if the powers that be don't want to rearrange the icons thats fine
and changing the language file has no effect

**Comment by oldman4U** [comment]
So you think not answering the own ticket is fine?

**Comment by kisslorand** [comment]
> and changing the language file has no effect

If you are using English, than go to language selection and select the second English in the list. That will use your language file, not the language encoded into the FW.

**Comment by 3dfixer** [comment]
> > and changing the language file has no effect
> 
> If you are using English, than go to language selection and select the second English in the list. That will use your language file, not the language encoded into the FW.

thank you, i thought just upgating language.ini did the job, didn't realize had to select it as well

**Comment by 3dfixer** [comment]
> So you think not answering the own ticket is fine?

really don't see what you mean by this statement.
if i could code in "C" i would not be asking for help/advice

**Comment by oldman4U** [comment]
So it is ok to ignore 3 replies and not to answer for several days? Maybe I just expect too much.
