### ISSUE TITLE
Babystep function on real time printing don't save to eeprom

### ISSUE THREAD

**Issue by mpcolman** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1534]
Hi everyone, I updated with one of the latest firmware with the upgrade issue for the filament runout beeps and it work fine, but when i adjust the babystep when printing, it's dont still saved on the eprom with the modified value.

But the stored message appears but the value don't be updated.....

If I make a correction outside the babysteping option and make the modification under the menu SETTINGS-----MACHINE----PARAMETER----- probe offstet.... Z.... and save the upgrade it stored on eeprom is OK.

I'm loosing something or it's a firmware bug????
regards!

**Comment by digant73** [comment]
This bug is fixed in PR #1518

**Comment by mpcolman** [comment]
Bltouch method enabled...
