### ISSUE TITLE
The Nozzle touch the bed when doing a tune steps

### ISSUE THREAD

**Issue by Dtcreation** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1537]
### Description

The Nozzle touch the bed when doing a tune steps

1. The Nozzle touch the bed when doing a tune steps
2. The filament can't go out

**Expected behavior**
The nozzle must be up the bed (50mm)

**Actual behavior**
The nozzle touch the bed at x0 y0 z0

### Hardware Variant

Last version on MKS 28

Last version with Marlin 2.0.7.2

**Comment by digant73** [comment]
what tuning are you referring to?

**Comment by Dtcreation** [comment]
Problem found. Thanks
