### ISSUE TITLE
A few issues with pause and filament runout TFT35 e3 v3 and SKR mini E3 V3 (04/02/2021 firmware update)

### ISSUE THREAD

**Issue by scathappens** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1538]
SO am new to Github but seems like the place to get some answers. 

I have installed a TFT35 E3 V3 and an SKR mini e3 V2 in my printer and there are a couple of bugs i cannot work out. 

I have the filament runout sensor attached to the TFT35 and i am printing from the SKR SD slot.

when the filament sensor notices a runout (printing from SD) the head parks as it should, then when i press resume it does nothing....then after a pause of about 30-60 seconds it says heater timout, when i press reheat it the heater turns off.
if i hit stop print at this time i get a message saying 'busy processing, please wait'

so the runout sensor is still not functioning as it should in the latest firmware (dated 04/02/2021)

I get the exact same reaction when i use the pause feature aswel, the head parks but then it will not resume in the same manner described as above

Any advice would be helpful

**Comment by oldman4U** [comment]
Add a M75 to your start gCode

Which firmware version are you using, send a screenshot from Info window

**Comment by scathappens** [comment]
Thanks for getting back to me, really appreciate it, i have had to take a crash course in marlin to get this printer working lol, its been a rough ride 

filament runout is connected to the TFT 
SKR mini Firmware 
![image](https://user-images.githubusercontent.com/77690628/105103001-b3f2bc80-5aa7-11eb-827a-bb3fbbd25a1d.png)

TFT 35 e3 V3 firmaware (i updated it to the latest version today) 
![image](https://user-images.githubusercontent.com/77690628/105103157-016f2980-5aa8-11eb-87b3-95ab2f1d7765.png)


adding M75 to my start gcode will solve the problem of the cancel g code not running? or is it something else?

**Comment by oldman4U** [comment]
M75 helps to recognize the sensor.

Pausing the print from on board sd does not work like mentioned before.

**Comment by scathappens** [comment]
thanks for that will do some more experimenting

**Comment by oldman4U** [comment]
Any news?

**Comment by scathappens** [comment]
@oldman4U i think this was also to do with the other issue of the runout sensor and the onboard sd slot...that issue is apparently sorted but i am not sure if the firmware has been updated...waiting on clarification and then i will install and see

**Comment by oldman4U** [comment]
Any news?

Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by scathappens** [comment]
how do i close a ticket?!?!

**Comment by oldman4U** [comment]
Using the web based interface you have a "close and comment" button.

**Comment by scathappens** [comment]
ah ok thanks, will do, have just flashed the tft53, tested the filament runout feature and it still is not working as expected, will test the pause...am playing with my marlin config to make sure there is no issue there....so at the moment i am unsure if the problem is fixed

**Comment by scathappens** [comment]
also after the filament runout has been tripped and it has notified that the heater has timed out and turned off, if i press stop i get a message saying 'busy processing, please wait'

**Comment by scathappens** [comment]
Just tested the pause feature too, when i press pause it parks the print head, when i press resume it does nothing and then after 30-60 seconds show the message heater timeout, i will edit the contents of this post with the updated issues

**Comment by scathappens** [comment]
i have tried to turn off the pause nozzle timout feature in marlin however when i do the build fails 

i did this by commenting out that definition
//#define PAUSE_PARK_NOZZLE_TIMEOUT

**Comment by scathappens** [comment]
here is a link to my marlin build if you want to have a look through it 

https://1drv.ms/u/s!Aj2EjE__0LLQhZsJTWdvdw1O5g-V5A?e=NhBaH7

**Comment by oldman4U** [comment]
Have you added M75 to the start gCode of your slicer?

**Comment by scathappens** [comment]
i haven't yet...i will try this today thanks :0) BTW you are doing stirling work @oldman4U really appreciate all the help

**Comment by scathappens** [comment]
i have had an interesting thing happen lately aswell, if i got to press buttons on the screen it inconsistently comes up with filament runout and then pauses the print (which i havent been able to resume from) i havent noticed a pattern to it yet so cant give you a steps to replicate but it happens from time to time when i press the 'more' buttton to then go and adjust temperature or something...i dont know if this is a known issue or not

**Comment by oldman4U** [comment]
You are welcome 

Add M75 to the slicer startcode and let me know.

**Comment by scathappens** [comment]
just tried it with m75 in the start gcode and it made no difference

**Comment by scathappens** [comment]
am now getting that if u use the touch screen during a print it starts doing things like skipping a layer advance....i think i will re-flsh the SKR and the screen....really inexplicable where these issues are coming from but i basically cant touch it during a print at the moment or something goes wrong

**Comment by scathappens** [comment]
i have reflashed the tft and formatted the print SD card, will see what happens

**Comment by scathappens** [comment]
ok so if baby step it to dial in the first layer then save to eprom the next layer happens lower than it should, also if i restart the print the new layer settings are ignored

**Comment by scathappens** [comment]
is there anywhere to get suport with these products as i am at my whits end, i have contacted bigtreetech direct 3 times and sent them my marlin builds as requested on each occasion etc but never heard any more from them

**Comment by oldman4U** [comment]
You understand that the software is open source?

scathappens <notifications@github.com> schrieb am So. 14. Feb. 2021 um
17:06:

**Comment by scathappens** [comment]
yeah sorry had a bad day with it all, got some help and solved todays trouble.....however the issues with the fillament runout and pause still remain.

I thought that this was a bigtreetech firmware, didn't realise all this was purely open source dev....do bigtreetech get involved at all?

**Comment by oldman4U** [comment]
BTT does the hardware the community the software.

**Comment by scathappens** [comment]
ah ok thats an interesting state of affairs

**Comment by oldman4U** [comment]
I have been testing filament runout for several hours using the TFT firmware from yesterday and it worked great. Sensor connected to TFT - printing from TFT storage it triggers correctly and purges at the pause position. @digant73 Please mention this ticket in your PR.

Thank you

**Comment by oldman4U** [comment]
I have to add, that printing from on board SD card is still not 100%, where the print resumes sometimes correctly at the first time. Sometimes it only resumes the print after the second or third time, but it does it finally. Resuming the print from a TFT storage works 100% at the first time.

Please try again and let us know

Thank you

**Comment by scathappens** [comment]
Thanks for that, i will update to the latest firmware and try again over the weekend

**Comment by oldman4U** [comment]
Please let us know once you tested it. What kind of sensor and how many wires?

**Comment by oldman4U** [comment]
And make sure you follow the notice related to Marlin:

# Minimum Marlin firmware version: 2.0.5.4
# Distribution date: 2020-05-12
# Firmware source: https://github.com/MarlinFirmware/Marlin/releases
#
# In order the TFT firmware is able to provide all of its functionalities/features,
# ensure that the following options are enabled in Marlin firmware.
#
# General options:
#   EEPROM_SETTINGS (in Configuration.h)
#   AUTO_REPORT_TEMPERATURES (in Configuration_adv.h)
#   M115_GEOMETRY_REPORT (in Configuration_adv.h)
#   M114_DETAIL (in Configuration_adv.h)
#   REPORT_FAN_CHANGE (in Configuration_adv.h)
#
# Options to support printing from onboard SD:
#   SDSUPPORT (in Configuration.h)
#   LONG_FILENAME_HOST_SUPPORT (in Configuration_adv.h)
#   AUTO_REPORT_SD_STATUS (in Configuration_adv.h)
#   SDCARD_CONNECTION ONBOARD (in Configuration_adv.h)
#
# Options to support dialog with host:
#   EMERGENCY_PARSER (in Configuration_adv.h)
#   SERIAL_FLOAT_PRECISION 4 (in Configuration_adv.h)
#   HOST_ACTION_COMMANDS (in Configuration_adv.h)
#   HOST_PROMPT_SUPPORT (in Configuration_adv.h)
#
# Options to support M600 with host & (Un)Load menu:
#   Options to support dialog with host (as pre requisite)
#   NOZZLE_PARK_FEATURE (in Configuration.h)
#   ADVANCED_PAUSE_FEATURE (in Configuration_adv.h)
#   PARK_HEAD_ON_PAUSE (in Configuration_adv.h)
#   FILAMENT_LOAD_UNLOAD_GCODES (in Configuration_adv.h)
#
# Options to support Babystep menu:
#   BABYSTEPPING (in Configuration_adv.h)
#
# Options to support repeatibility test to test probe accuracy (M48):
#   Z_MIN_PROBE_REPEATABILITY_TEST (in Configuration.h)
#
# Options to support aligment of multiple Z steppers using a bed probe (G34):
#   Z_STEPPER_AUTO_ALIGN (in Configuration_adv.h)

Please let me know

Thank you

**Comment by oldman4U** [comment]
Any news?

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
@Msq001 I believe all Pause and filament runout issues are solved now but this user does not reply anymore.

Thank you
