### ISSUE TITLE
BIQU TFT35 3.0Artifacts on icon names

### ISSUE THREAD

**Issue by Nino97** [bigtreetech/BIGTREETECH-TouchScreenFirmware#154]
I have a TFT35 V3.0 with the new update 24.2 I have artifacts on all the names of the icons and on every writing, how can I solve?
![IMG_1354](https://user-images.githubusercontent.com/57629975/68630227-e9386d80-04e6-11ea-8553-1cc37921e55c.jpeg)

**Comment by thisiskeithb** [comment]
Copy the TFT35 folder to your SD card to update those parts of the TFT. It contains your icons and font files.

**Comment by Nino97** [comment]
Do I have to copy only the TFT35 folder or something else?

**Comment by thisiskeithb** [comment]
Since you’ve already updated the main firmware with the .bin, that should be it.

**Comment by Nino97** [comment]
thank you it works now

**Comment by thisiskeithb** [comment]
Glad to help. Don’t forget to close the issue.
