### ISSUE TITLE
[BUG] BIGTREE TFT35 V3.0 backlight slowly turns off during firmware update

### ISSUE THREAD

**Issue by dreyco676** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1540]
### Description

BIGTREE TFT35 V3.0 backlight slowly turns off during firmware update

### Steps to reproduce

1. Put BIGTREE_TFT35_V3.0.26.x.bin, config.ini and TFT35 directory (any) on either 128MB SD or 8GB SD card
2. Power up with SD card in place. Starts loading
3. As it starts loading words the screen slowly dims until it is completely off at about 40%.
4. Waiting 5min the screen is still off and firmware is not loaded on restart

**Expected behavior**
My Firmware to update

**Actual behavior**
My Firmware does not update

### Hardware Variant
BIGTREE TFT35 V3.0 & SKR 1.4 Turbo
### TFT Firmware Version & Main Board Firmware details 
BIGTREE_TFT35_V3.0.26.x.bin & Marlin firmware 2.0.3

### Additional Information
* Side note the D2 LED on the PCB is red and the D1 is green.
![IMG_5778](https://user-images.githubusercontent.com/7094791/105127976-a1788300-5aa7-11eb-956b-0e18b0083934.jpg)

**Comment by radek8** [comment]
Sd card format on FAT32, or use another card.

**Comment by dreyco676** [comment]
They are already FAT32 and I've used two cards.

**Comment by dreyco676** [comment]
Tried a third card. Backlight completely turns off by 46%

**Comment by dreyco676** [comment]
See video

**Comment by gordo3di** [comment]
Very weird. I have 5 SKR turbos with the TFT35 v3's and Marlin 2.0.5 and I just updated all the firmware yesterday (January 19th 2020) and have never seen this issue. I do compile my own firmware and I don't use the precompiled files. I use class 4 4gb cards formatted as FAT32. Have you tried powering the screen without the SKR and updating?

**Comment by dreyco676** [comment]
![Uploading E03933F5-4C5D-437E-8D7F-60D33CCAAE2B.png…]()

**Comment by dreyco676** [comment]
I haven't tried that. How do I power it without the main board?

**Comment by dreyco676** [comment]
![198012AC-AC56-4F41-88BD-767A8F885447](https://user-images.githubusercontent.com/7094791/105202571-be44a300-5b07-11eb-8b4e-f4cd2a05a289.png)
![B201B87A-639B-4164-A69A-1A8630B4F397](https://user-images.githubusercontent.com/7094791/105202587-c43a8400-5b07-11eb-9919-fa0068c9b877.png)
![7FA4077E-CC7D-48E4-AB38-E60274C906FB](https://user-images.githubusercontent.com/7094791/105202610-c8ff3800-5b07-11eb-8ed6-c9bf5257e7ef.png)

**Comment by dreyco676** [comment]
![78FF9CB1-D32E-4E0A-A293-BD9053423970](https://user-images.githubusercontent.com/7094791/105202808-fa780380-5b07-11eb-969d-dea0ea7b8aa6.jpeg)
![702A3E22-3C62-4B83-92DE-FB4BC7222E1D](https://user-images.githubusercontent.com/7094791/105202830-fe0b8a80-5b07-11eb-9911-7f5dc3f32952.jpeg)
![B7B0B9CC-4059-465A-ADF0-5CD7A7F8D589](https://user-images.githubusercontent.com/7094791/105202846-0237a800-5b08-11eb-8d8a-8e29856afd7b.jpeg)

**Comment by dreyco676** [comment]
I tried starting it up without the EXP1 & EXP2 plugged in, it gets a bit further, 49% before the screen turns off.

**Comment by gordo3di** [comment]
I believe the board has a 2pin 5v connector that's just for powering the lcd. Check the pinout from biqu.

**Comment by dreyco676** [comment]
Is it possible to update firmware via USB instead of SD?

**Comment by oldman4U** [comment]
Sd card only.

Cut a USB cable and connect 5v and gnd to the corresponding pins of the RS232 connector. Make a connector or insulate the cables well to not shorten them.

**Comment by dreyco676** [comment]
I think the screen backlight is just broken. I got it to boot up without the update and it does the same fade out.

**Comment by oldman4U** [comment]
Try what I wrote and you will know.

**Comment by dreyco676** [comment]
I'll give it a shot.

**Comment by dreyco676** [comment]
Ok, so turns out you can power it over USB. I was able to successfully update the firmware. Looks like now I have to figure out why the touch screen is unresponsive but that's another issue.

**Comment by dreyco676** [comment]
Screen still does not stay back lit when connected to SKR

**Comment by dreyco676** [comment]
Seems like maybe I have a bad cable?

**Comment by oldman4U** [comment]
Or a bad board.

What means non responsive? Reset the TFT.

**Comment by dreyco676** [comment]
I've tried resetting (with the button). Unresponsive means it doesn't react to touch, I've even tried detaching it from my bezel to ensure its not being pressed on. The dial works however and i can get into Marlin mode.

**Comment by Codel1417** [comment]
add a file to the sd card called reset.txt and reboot to fix touch screen
not responding

**Comment by oldman4U** [comment]
Read the ReadMe from front page.

John Hogue <notifications@github.com> schrieb am Mi. 20. Jän. 2021 um 22:42:

**Comment by dreyco676** [comment]
Resetting with reset.txt forced a reflash of firmware. Still same issues. Going to chaulk it up to a bad board.

**Comment by oldman4U** [comment]
You should be able to press buttons on touchscreen as soon as it gets
power. No mainboard has to be connected for this.

John Hogue <notifications@github.com> schrieb am Mi. 20. Jän. 2021 um 23:31:

**Comment by dreyco676** [comment]
Yea no dice. Trying that either.

**Comment by dreyco676** [comment]
Ordered a new TFT, if that has no issues we'll say it was just a bad board and I'll close issue.

**Comment by oldman4U** [comment]
Which files have you had on sd card during firmware update?

**Comment by Greendog2020** [comment]
In my case, when I update the firmware, as I have "Auto power" enabled and the "bigtreetech relay module" connected to the screen, I have to reset the relay every 15 seconds or so until the firmware is installed, otherwise it would happen to me like you.

**Comment by dreyco676** [comment]
@oldman4U BIGTREE_TFT35_V3.0.26.x.bin, config.ini and TFT35 directory

@Greendog2020 where is "auto power" configured? I'm just using the precompiled firmware.

**Comment by oldman4U** [comment]
And everything updated without an error?

TFT does not dimm using USB power?

**Comment by dreyco676** [comment]
Correct everything updated without error. TFT does not dimm with USB power
and screen is much brighter.

**Comment by oldman4U** [comment]
Remaining issue is the inability to press buttons?

Anything else?

**Comment by dreyco676** [comment]
Yes touchscreen is unresponsive no matter what and without external USB
power the display slowly dimms until it is completely black.

**Comment by oldman4U** [comment]
Sorry to ask again.

With ONLY USB power, the display still dimms?

**Comment by dreyco676** [comment]
With only USB power, display does not dimm and touchscreen still does not
respond.

**Comment by oldman4U** [comment]
After reset you got a calibration screen?

John Hogue <notifications@github.com> schrieb am Do. 21. Jän. 2021 um 19:49:

**Comment by dreyco676** [comment]
After I reset with the reset.txt I got "illegal flash app" that wouldnt go
away until I reflashed the firmware.

**Comment by oldman4U** [comment]
You should read the ReadMe.

After flashing the  firmware, remove the sd card and restart the TFT.

Insert sd card with reset and see.

John Hogue <notifications@github.com> schrieb am Do. 21. Jän. 2021 um 19:57:

**Comment by dreyco676** [comment]
I've read the readme and followed the steps you outlined.. When I put only
the reset.txt on the SD card after restarting that is when I got a illegal
flash app message showing up.

**Comment by oldman4U** [comment]
You get the message in case a firmware.cur file is on the sd card at the
first start after the Update

John Hogue <notifications@github.com> schrieb am Do. 21. Jän. 2021 um 20:56:

> I've read the readme and followed the steps you outlined.. When I put only
> the reset.txt on the SD card after restarting that is when I got a illegal
> flash app message showing up.
>

**Comment by dreyco676** [comment]
Reformatted and tried several cards. Reset finally worked. We are all good now.

**Comment by oldman4U** [comment]
Almost expected this 👍🏻

Happy printing

John Hogue <notifications@github.com> schrieb am Fr. 22. Jän. 2021 um 05:24:
