### ISSUE TITLE
TFT35 E3 No Media Marlin Mode

### ISSUE THREAD

**Issue by Doyle4** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1542]
### Description

Screen was displaying SD Init Fail, updated to latest build today (says from 4 days ago) now displays No Media

### Steps to reproduce

Insert SD/USB Stick, Marlin Mode, Says No media

**Expected behavior**
To see files

**Actual behavior**
Screen displays No Media

### Hardware Variant
TFT3.5 E3 V2 I think it is? Dial at bottom right
### TFT Firmware Version & Main Board Firmware details

TFT
9b762cf 4 days ago

Marlin - Latest Bugfix 2.0.7.2

### Additional Information
[Configs.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5841894/Configs.zip)

**Comment by oldman4U** [comment]
Using your config, you can print from TFT SD card and nothing else. Is this what you want? Please check and let us know.

**Comment by Doyle4** [comment]
Hello @oldman4U Thanks again for advice and help.

I print from either SD or USB from TFT currently which is what Id like.

The onboard SD port on motherboard I only use for updating the board :)

**Comment by Doyle4** [comment]
Do I have it to Print from SD mainboard?

**Comment by oldman4U** [comment]
I BELIEVE printing from TFT in Marlin mode is only available in case you have EXP1 and EXP2 connected, but I can for the person who really knows.

@radek8. Is it possible to print from another media than on board SD in Marlin mode and does this depend on a certain connection?

**Comment by oldman4U** [comment]
doyle4, which mainboard do you have?

**Comment by Doyle4** [comment]
@oldman4U I have the MKS SGEN L V2.

I have a microsd extension im happy to use if it has to be from board.

**Comment by radek8** [comment]
he has BOARD_MKS_SGEN_L_V2

**Comment by radek8** [comment]
![image](https://user-images.githubusercontent.com/46979052/105397196-09060e00-5c21-11eb-8b32-0e4777135eca.png)

**Comment by radek8** [comment]
Do you have an EXP2 connector connected?

**Comment by Doyle4** [comment]
Yeah, I have both connected.

**Comment by radek8** [comment]
The marlin is a parameter
#define SDCARD_CONNECTION
which can have 3 values.
LCD - in both Marlin mode and touch mode, only the card on the TFT display is available, which is connected via the EXP2 connector. The SD card on the MKS is only available for Marlin updates, otherwise it is inaccessible.

ONBOARD - In Marlin mode, only the SD card on the MKS board is available.
Both TFT and MKS cards are available in touch mode. You can use both cards.

CUSTOM_CABLE - An SD card is available which is user-defined on other ports in the pin definition file.

Is it that understandable?

**Comment by radek8** [comment]
I prefer the ONBOARD parameter
I can then use both SD card slots.
Unfortunately, Marlin mode only supports one SD card.

**Comment by Doyle4** [comment]
If i was to change it from TFT to onboard, could I still use USB port? And if changed to onboard, can I still update via onboard sd? I know it doesn't mount when changed to onboard, thats the part that puts me off.

**Comment by radek8** [comment]
USB is still available. USB does not affect this setting.

Marlin is always updated to MKS from the onboard SD card.
Upgrading from a reader to a TFT would only be possible when loading an alternative botloader.
There is an alternative botloader for SKR, I don't know for MKS, I didn't need it.

**Comment by Doyle4** [comment]
So I never use the TFT sd, always a sd to usb stick as one on my computer has broke.

Would like to be able to print from Marlin mode, Im going to change it to Onboard and use a MicroSD extention adapter I have, my sd port is covered and little further back after upgrade.

**Comment by radek8** [comment]
It's your choice. If it doesn't suit you, you can always put it back

**Comment by Doyle4** [comment]
Thanks @radek8 so I need to change it from LCD to ONBOARD for access in Marlin mode, few options I like in Marlin mode so Im happy to change.

Spotted also, USB did not work in Marlin mode either, but that doesnt bother me, as long as SD works im happy.

**Comment by radek8** [comment]
USB to TFT will never be accessible in Marlin mode

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by Doyle4** [comment]
Onboard solved it thanks guys!

Sorry for late close, not been around much sorry.

**Comment by reallost** [comment]
I have and skr1.4 marlin 2.0.5 with tft35. Sd and usb work fine in marlin mode. 
i also have a skr 3ez marlin 2.1 bugfix and tft35. Both usb and sd dont work in marlin mode. Have swapped screens and nothing changes.  Both screen recognize in touch mode.  

> USB to TFT will never be accessible in Marlin mode
 So this isnt really a true statement
