### ISSUE TITLE
[Q] Touch screen calibration fail

### ISSUE THREAD

**Issue by luwi66** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1554]
I try to install the TFT35-E3 V3.0 to my printer.
Firmware update (V26.1) ok. Touch screen calibration doesn't work. I can touch three red dots, but the fourth red dot (lower left corner) doesn't show. So I always get "Adjustment failed. "

![Touch_Cal_Fail](https://user-images.githubusercontent.com/36111299/105606018-25c45200-5d97-11eb-8a3f-167e825c5e1b.jpg)

**Comment by sarvenn** [comment]
Because there isn't any red dot on the lower left corner. You need to press on the middle black dot after tapping on to lower right red dot.

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by luwi66** [comment]
That’s exactly what I did 20 times. But it would be nice if you could change the text to say „press black dot“ after the third red dot.OK, I got it working now. After many many tries with tipping to various spots suddenly SUCCESS. I can’t say what exactly caused the positive result. And I will not try to test calibration now it’s ok.I will close the ticket.Thanks  Gesendet von Mail für Windows 10 Von: sarvennGesendet: Samstag, 23. Januar 2021 17:31An: bigtreetech/BIGTREETECH-TouchScreenFirmwareCc: luwi66; AuthorBetreff: Re: [bigtreetech/BIGTREETECH-TouchScreenFirmware] [Q] Touch screen calibration fail (#1554) Because there isn't any red dot on the lower left corner. You need to press on the middle black dot after tapping on to lower right red dot.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
