### ISSUE TITLE
can be closed [Q] is Smart filament sensor working connected to TFT?

### ISSUE THREAD

**Issue by killrob** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1559]
I only would like to know if someone uses the smart filament sensor connected to TFT35 V3 E3 instead of motherboard, and if yes, if it works as expected.

**Comment by oldman4U** [comment]
Why not asking #GenaUser who opened a few smart filament sensor related tickets recently!?

**Comment by killrob** [comment]
> 
> 
> Why not asking #GenaUser who opened a few smart filament sensor related tickets recently!?

cause i didn't know that #GenaUser do that

**Comment by oldman4U** [comment]
But now you found it, great!

**Comment by killrob** [comment]
> 
> 
> But now you found it, great!

yes but.... maybe i will dig a little on the code ;)

**Comment by digant73** [comment]
If you solved the problem, please close your bug report
