### ISSUE TITLE
SD card on Menu Marlin Mode TFT35 V3

### ISSUE THREAD

**Issue by Nino97** [bigtreetech/BIGTREETECH-TouchScreenFirmware#156]
Has anyone managed to run the sd card on tft35 v3 in Marlin mode?

**Comment by Sthopeless** [comment]
Yes, connect EXP2 to your board, use this LCD `#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER` and if your board (mine did) has sdcard onboard change this line `#define SDCARD_CONNECTION LCD` in configuration_adv.h to `ONBOARD`.

**Comment by Nino97** [comment]
but I want to be able to use the sd card slot that there is a display not the one on the card, also because I have a skr pro 1.1, you who mount the card?

**Comment by traffic-light** [comment]
@bigtreetech can be closed
