### ISSUE TITLE
TFT3.5 V3 bootloader

### ISSUE THREAD

**Issue by artistan82** [bigtreetech/BIGTREETECH-TouchScreenFirmware#158]
Was playing around with SWD, creating a customized firmware and accidentally overwrote the bootloader.

Not all update needs to be performed via SWD.

Does anybody have a dump of the bootloader for TFT3.5 V3?

**Comment by Baltazart** [comment]
sorry for my English
First load the boot, then update for TFT35 / v3.0 it should revive LCD. there is a valid drop box link.
hoping to help you.

https://github.com/bigtreetech/BIGTREETECH-TFT35-V3.0/issues/20

**Comment by thisiskeithb** [comment]
You’ll see my comments in the issue, but I can confirm it works 🙂

**Comment by guruathwal** [comment]
> sorry for my English
> First load the boot ST-LINK, then update for TFT35 / v3.0 it should revive LCD. there is a valid drop box link.
> hoping to help you....
> 
> [bigtreetech/BIGTREETECH-TFT35-V3.0#20](https://github.com/bigtreetech/BIGTREETECH-TFT35-V3.0/issues/20)

👆This should be added to the repository.

**Comment by thisiskeithb** [comment]
I’ve asked BigTreeTech to open source it like the TFT35 V2, but was told it wouldn’t be for now.

**Comment by guruathwal** [comment]
@thisiskeithb can you point to TFT35 V2 bootloader source, i cant find it? all I found was the BIN file.

**Comment by Baltazart** [comment]
> @thisiskeithb peut -être allumé la source du chargeur d'amorçage TFT35 V2, je ne trouve pas? tout ce que j'ai trouvé, c'est le fichier BIN.

there is this boot, but apparently load by usb, see in picture.

https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/tree/master/TFT35_V2%20Bootloader%20fix

**Comment by Baltazart** [comment]
there is this boot, but apparently load by usb, see in picture.

https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/tree/master/TFT35_V2%20Bootloader%20fix

**Comment by guruathwal** [comment]
> > @thisiskeithb peut -être allumé la source du chargeur d'amorçage TFT35 V2, je ne trouve pas? tout ce que j'ai trouvé, c'est le fichier BIN.
> 
> there is this boot, but apparently load by usb, see in picture.
> 
> https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/tree/master/TFT35_V2%20Bootloader%20fix

👍  Thanks @Baltazart ... but I already know that. I pushed the PR for this one. @thisiskeithb is saying that the TFT35 V2 Bootloader is open source. I was asking about the location of the source code.

**Comment by Baltazart** [comment]
> > > @thisiskeithb peut -être allumé la source du chargeur d'amorçage TFT35 V2, je ne trouve pas? tout ce que j'ai trouvé, c'est le fichier BIN.
> > 
> > 
> > there is this boot, but apparently load by usb, see in picture.
> > https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/tree/master/TFT35_V2%20Bootloader%20fix
> 
> 👍 Thanks @Baltazart ... but I already know that. I pushed the PR for this one. @thisiskeithb is saying that the TFT35 V2 Bootloader is open source. I was asking about the location of the source code.

Sorry!

**Comment by thisiskeithb** [comment]
I misspoke. They didn’t open source it, just provided a copy.

**Comment by guruathwal** [comment]
@thisiskeithb ok. atleast the Binary for TFT35 V3 should be added to this repository.

**Comment by artistan82** [comment]
Confirmed working! Thank you so much.
I agree that they should have this open sourced.

**Comment by Baltazart** [comment]
> Confirmed working! Thank you so much.
> I agree that they should have this open sourced.

Happy for you ... lol
