### ISSUE TITLE
[BUG] BIQU B1 - Temperature Dosen't raise...

### ISSUE THREAD

**Issue by ETE-Design** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1583]
Have just updated and BIQU B1 with the firmware TFT firmware from today... I can do PID and All temperatures raise as it should and the TFT update the temp, but as soon I try to print anything the temp just stay at the last temp aviable before print... After that nothing happend cause the TFT dosen't update the temp so the printer won't start printing... If I shut down the printer and turn it on again it show the temperature it reached just before shutdown... Seems like a BUG in the firmware cause if I revert back to stock TFT Firmware it work fine :-)

**Comment by oldman4U** [comment]
Try to find the PR which broke it and call for the developer.

**Comment by oldman4U** [comment]
Any news? Have you found the relevant PR?

**Comment by ETE-Design** [comment]
@oldman4U Seems like it only work with their "Official" One for the B1 :-(

**Comment by kisslorand** [comment]
Check if your Marlin config fulfills the reqeuested config for the TFT firmware.

**Comment by oldman4U** [comment]
And maybe start a ticket in the B1 repository. For us, without owning such a printer, this is all guesswork.

**Comment by gordo3di** [comment]
@oldman4U I agree

**Comment by oldman4U** [comment]
Hi gordo!

Which mainboard do you have and do you have problems to Purge More when using the (Un)Load menu?

**Comment by gordo3di** [comment]
Skr V1.4 Turbo, TFT 35 V3, marlin 2.6.0.1

Unload works fine. Load keeps popping up with "pause wait for user". Never got to purge more even after extruding stops just same message. Funny, I never tried "Loading" I've always just extruded via the move menu our the custom gcode commands.
