### ISSUE TITLE
Long menu labels

### ISSUE THREAD

**Issue by AntoszHUN** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1587]
Hi! Could it be that the labels next to the toggle button in the menu of certain settings that hang on the buttons might appear as a conveyor belt label?

I attach a picture of what I am talking about.

![IMG_20210131_105322](https://user-images.githubusercontent.com/45710979/106380484-e0b1a880-63b2-11eb-88a3-4cfb56b4e3c5.jpg)

There are several such captions that hang on the buttons.
Can they run like "No printer connected" on the main screen?

Made By.: AntoszHUN

**Comment by radek8** [comment]
Not necessary.
Yesterday I played with it in the CZ translation
I had to shorten the description to fit the display while being understandable and concise.

**Comment by AntoszHUN** [comment]
I understand you. But you can't describe everything clearly in Hungarian and even it should be concise. Either understandable or I will abbreviate.

**Comment by AntoszHUN** [comment]
The Hungarian language is slowly consisting of only abbreviations.
