### ISSUE TITLE
[FR] is there a possibility of a mmu2 menu

### ISSUE THREAD

**Issue by pstit006** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1597]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by oldman4U** [comment]
Hi.

It does not happen very often that a ticket is unanswered for a week, so I will try it.

Yes, it is possible, BUT, this software is made and maintained by private users like you and me. So to implement this it would need a user with development skills willing to buy a MMU2 unit and the time to develop the functionality.

All I can offer you is, to put your FR on the FR list and hopefully, someone will pick it up one day.

Please let me know
