### ISSUE TITLE
[FR] Information on the filament consumed in two-color printing

### ISSUE THREAD

**Issue by radek8** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1605]
Please complete the final information on filament consumption in two-color printing.
The values could be side by side or as a sum.

Cura generates:

M118 P0 filament_data L: [0.58, 0.29] m
M118 P0 filament_data W: [1.92794625, 0.9545545239257811] g
M118 P0 filament_data C: [1.15676775, 0.5727327143554687] Kc

the display shows:

![image](https://user-images.githubusercontent.com/46979052/106820118-1a1c3980-667b-11eb-97bc-af27b4354d70.png)

Thank you

**Comment by kisslorand** [comment]
Can you test please (when you have time) what happens when you do not include filament data in your gCode? I am curious what will the TFT calculate.

**Comment by radek8** [comment]
If I delete the M118 information from the file.
The display calculates this

![image](https://user-images.githubusercontent.com/46979052/106955153-1fd65580-6735-11eb-8473-289ac44f601f.png)

**Comment by kisslorand** [comment]
Thank you. I will (try to) make the data displayed if filament info present to show the sum of filament data.

**Comment by radek8** [comment]
Note that the githubu counts a dot as a comma.

M118 P0 filament_data L: [0.58, 0.29] m
M118 P0 filament_data W: [1.92794625, 0.9545545239257811] g
M118 P0 filament_data C: [1.15676775, 0.5727327143554687] Kc

![image](https://user-images.githubusercontent.com/46979052/106956442-e272c780-6736-11eb-9387-2104914897a7.png)

**Comment by radek8** [comment]
Thank you

**Comment by kisslorand** [comment]
Is see no difference...

**Comment by radek8** [comment]
I am sorry
punctuation marks are fine.
The translator confused the dot with a comma

**Comment by kisslorand** [comment]
OK, I've done it, now the sum of  each data is shown. The character ";" cannot be a separator, as it means a comment but other than that anything (except "." of course).
The funny thing is that the code is now shorter with 8 bytes without any RAM addition. :)
A PR is imminent, I have to update the Readme and sleep... Actually the other way, sleep and update the Readme.

**Comment by kisslorand** [comment]
Done: PR #1607

**Comment by radek8** [comment]
Thank you

**Comment by oldman4U** [comment]
Hi radek8.

Could you please ask the user sogeniusio here: https://github.com/bigtreetech/BTT-TFT35-E3-V3.0/issues/28if he can provide the user name of the person who made the pdf: https://www.dropbox.com/s/k7tb4sck5d2h5bb/BTT%20TFT%20to%20BTT%20Mainboards%202021.pdf?dl=0

ripper blocked me

Maybe we can add this to the ReadMe - or do you think it would be too confusing for the average user?

Thank you

Oldman
