### ISSUE TITLE
Serial connection problems tft screen 24

### ISSUE THREAD

**Issue by cuchieco** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1615]
I bought two screens skr tft 2.4 ". One works fine. The other screen does not connect with the printer, I get the red message" No connection ". However, it does allow me to move the motors. Both screens have the same firmware and the same cable.

https://youtu.be/Q44G1xQGwo8

**Comment by oldman4U** [comment]
Hi. This repository is related to software.

Follow the setup and installation instructions described in the ReadMe and open a ticket in the corresponding hardware repository in case this does not help.

Thank you
