### ISSUE TITLE
[BUG] Long Extrusion refused and M701/M702 - unknown!

### ISSUE THREAD

**Issue by FlailAway** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1616]
### Description
Subject says it all

### Steps to reproduce

Marlin
#define PREVENT_LENGTHY_EXTRUDE
#define EXTRUDE_MAXLENGTH 1200

config.ini
custom_label_1:UN-LOAD Filament
#custom_gcode_1:G1 E-805 F1200\n   <<-- "Prevented too long extrusion"
custom_gcode_1:M702 U805\n            <<-- "Unknown command
custom_label_2:LOAD Filament
#custom_gcode_2:G1 E+805 F800\n   <<-- "Prevented too long extrusion"
custom_gcode_2:M701 L805\n             <<-- "Unknown command

**Expected behavior**

What I asked, feed in/out 850mm
**Actual behavior**

Error messages

### Hardware Variant

BIGTREE_TFT35_V3.0

### TFT Firmware Version & Main Board Firmware details
BIGTREE_TFT35_V3.0.26.x.bin

Marlin Stable 2.0.7
Marlin Bugfix 2.0.8

### Additional Information
* Include a ZIP file containing your `Configuration.h` or use [Pastebin](https://pastebin.com/) and paste a link in this issue.
* Provide pictures or links to videos that clearly demonstrate the issue.

**Comment by radek8** [comment]
check in the Marlin parameter
#define EXTRUDE_MAXLENGTH

**Comment by oldman4U** [comment]
Radek.

Please check the beginning of the ticket.

**Comment by radek8** [comment]
Sorry, I missed it.

**Comment by oldman4U** [comment]
In case you really have to extrude 850mm I would try to uncomment that function in Marlin to see it this solves the problem.

**Comment by sarvenn** [comment]
What if I print something in vase mode, will this long extrusion feature kick in?

**Comment by oldman4U** [comment]
No.

This is to un(fill) the bowden which makes such numbers unlikely. Have you
tried to disable like I recommended?

sarvenn <notifications@github.com> schrieb am So. 14. Feb. 2021 um 21:39:

**Comment by guruathwal** [comment]
it looks like a marlin issue. check and make sure the firmware is building and uploading successfully.

**Comment by oldman4U** [comment]
What is the status of the reported issue?

Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Another 9 day wonder which does not know how to behave right not answering his own ticket.

Answer or close this ticket
