### ISSUE TITLE
NEOPIXEL Sequential display for temperature change not working when print from SD card

### ISSUE THREAD

**Issue by Jeripimo** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1620]
**TOUCH SCREEN MODE**
When printing from SD card neopixel sequential display not working.
Cycle through colors at startup also not working.
Manual switch on neopixel IS working

MARLIN MODE it's working

Touch screen mode printing with octoprint it is working

CONFIG:
#define NEOPIXEL_LED
#if ENABLED(NEOPIXEL_LED)
  #define NEOPIXEL_TYPE   NEO_GRB   // NEO_GRBW // NEO_GRBW / NEO_GRB - four/three channel driver type (defined in Adafruit_NeoPixel.h)
  #define NEOPIXEL_PIN        PC7                      // LED driving pin
  //#define NEOPIXEL2_TYPE NEOPIXEL_TYPE
  //#define NEOPIXEL2_PIN     5
  #define NEOPIXEL_PIXELS     8                        // Number of LEDs in the strip, larger of 2 strips if 2 neopixel strips are used
  #define NEOPIXEL_IS_SEQUENTIAL                // Sequential display for temperature change - LED by LED. Disable to change all LEDs at once.
  #define NEOPIXEL_BRIGHTNESS 100              // Initial brightness (0-255)
  #define NEOPIXEL_STARTUP_TEST                 // Cycle through colors at startup

  // Use a single Neopixel LED for static (background) lighting
  //#define NEOPIXEL_BKGD_LED_INDEX  0               // Index of the LED to use
  //#define NEOPIXEL_BKGD_COLOR { 255, 255, 255, 0 } // R, G, B, W
#

used:
marlin 2.0.5.3
TFT35 /  3.0.26.x febr 4 2021
SKR mini v1.2

**Comment by DaStivi** [comment]
its a known issue for quite some time... 
there is some changes comming maybe that could fix it... 

https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/1209#issuecomment-772867520

**Comment by bigtreetech** [comment]
It's repeated with #1786, so close here. Let's discuss it together in #1786
