### ISSUE TITLE
tft70 text overlapping E-Steps calibration

### ISSUE THREAD

**Issue by jariddler** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1623]
tft70 text overlapping in e-steps calibration menu.
I'm using a skr mini e3 v2 with the tft70.
its running marlin bugfix 2.0.x
screen firmware was updated.
when you go to input length of filament left you cant see the numbers you're changing them to because they're behind the old 
e-steps value

[config files.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5975054/config.files.zip)
![149670456_5851078454917723_4819004863251951589_o](https://user-images.githubusercontent.com/26636977/107839850-26d41800-6d74-11eb-8d36-1524bfbd109f.jpg)

**Comment by oldman4U** [comment]
Please add E-Steps calibration to the title of your ticket.

Thank you

**Comment by oldman4U** [comment]
Thank you 

Please verify that the problem still exists with the firmware available since yesterday and let me know.

**Comment by jariddler** [comment]
Yes the new update fixed the issue. Thanks for the fast fix and all the dedication. Keep up the good work

Sent from Mail for Windows 10

**Comment by oldman4U** [comment]
Perfect. In this case BTT fixed it.

Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by jariddler** [comment]
The new update fixed the issue. Thanks
