### ISSUE TITLE
[BUG] MKS Rumba32 and TFT 35 E3

### ISSUE THREAD

**Issue by DrumClock** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1624]
Hi, If the TFT is connected using the EXP 1 and 2 connectors,
it is not possible to activate the DFU mode for FW Marlin recording on the MKS Rumba32 board.
When connecting TFT via UART, everything is fine

**Comment by oldman4U** [comment]
Hi. 

Where is the problem in the TFT firmware related to your ticket?

**Comment by Chris1231** [comment]
it is possible that you have to turn the connector 180 degrees. you have to compare the pin assignment of the TFT and the Rumba board.

**Comment by DrumClock** [comment]
Hi, the connectors are right because TFT in "Marlin mode" works fine.
I think there will be a problem in the FW TFT which blocks the Rumba32 board to switch to DFU mode. 
If I connect the old LCD 12864, everything is fine.

**Comment by DrumClock** [comment]
I found that the EXP2 connector blocks the start of DFU mode. 
I'll try to figure out which pin is causing it.

**Comment by DrumClock** [comment]
When I disconnect pins 3 and 5 on TFT EXP 2 conector it is possible to start the DFU mod on the Rumba32 board

![image](https://user-images.githubusercontent.com/64655979/107860210-594a4780-6e3e-11eb-8962-b5a946db1160.png)

pin3 - BTN EN1 - PB2 Rumba board
pin5 - BTN EN2 - PB1 Rumba board

**Comment by radek8** [comment]
These are contacts from the Encoder.
It's weird that the encoder does it.

**Comment by oldman4U** [comment]
I still don't understand how this is TFT firmware related!?

**Comment by radek8** [comment]
> I still don't understand how this is TFT firmware related!?

It only has a problem with the connected TFT.
It does not have a problem when connecting a classic display

**Comment by oldman4U** [comment]
DrumClock wrote that Marlin mode works fine. Still don't understand how this could be firmware related but it seems you take care. 👍🏻

**Comment by DrumClock** [comment]
@oldman4U is that how you understand it? 

![sss](https://user-images.githubusercontent.com/64655979/107871437-c93de980-6ea1-11eb-8dc2-20ecc6af09e6.png)

**Comment by oldman4U** [comment]
I do not understand it at all. The TFT firmware uses the existing hardware which provides a certain functionality. The TFT works fine with other mainboards but not with this one. So the firmware works.

For me it is like buying any tires and wondering why the do not fit my car and then to blame the car for it.

**Comment by DrumClock** [comment]
I just pointed out that TFT blocks the ability to run DFU mod on a Rumba32 board - so it's not compatible with this board.

If I connect pin3 - BTN EN1 on connector EXP2 (which is defined on pin PB2-BOOT1 Rumba board ),
the mod can be started and FW Marlin can be loaded.

Since the LCD 12864 does not cause it ...... so it must do the TFT 35 E3 display .....

**Comment by DrumClock** [comment]
The LCD 12864 display has a 0V pin on restart and therefore the DFU mode on the Rumba32 board can be started.
After loading the FW, the value changes to 3.3V

The TFT35 display has 3.3V on the pin when restarted !

**Comment by kisslorand** [comment]
If you check Marlin's "pins_RUMBA32_common.h" file you'll see this:
`  #define BTN_EN1                           PB2`
`  #define BTN_EN2                           PB1`
Since Marlin expects that PB1 and PB to be connected to the encoder, I do not see how it is a BTT TFT FW issue.
The only thing I see different is the that "BTN_EN1" and "BTN_EN2" are connected the wrong way. You can try exchanging them.

**Comment by DrumClock** [comment]
HI @kisslorand 
Change does not solve anything. 
The problem is that the PB2 pin also has the BOOT1 function and the TFT 35 has 3.3V on the BTN pins when restarted and does not allow starting the DFU mode on the Rumba32 board ..... I have been writing this for several times ....

**Comment by kisslorand** [comment]
I am just checking "LCD_Encoder.c" and `LCD_ENCA_PIN` and `LCD_ENCB_PIN` will be always in logical "1" state that is 3.3V in your case.
There is no FW bug.

**Comment by DrumClock** [comment]
The LCD display 12864 is in OV during a reset!
If I switch the pin from PB2 somewhere else, eg PD13,
so you can run DFU mod to upload FW to Rumba32 board.


If I'm not a jerk, then the error in TFT is that when restarting the pin is at 0V ..... or do you have another opinion?

**Comment by kisslorand** [comment]
My opinion is that the problem can be solved and it is not a FW issue.
Redefine your encoder pins in Marlin and move those two problematic wires to the newly defined pins.

**Comment by DrumClock** [comment]
Yes, but the Bigtreetech TFT display doesn't solve the problem.
It's the same with the TFT 50 and I believe it with the others.

**You should think about this and not that the user will remap the pins.**

**Comment by kisslorand** [comment]
> You should think about this and not that the user will remap the pins.

If you're talking to me than I have to let you know that I am also just a user who spent 1 hour of his free time on a Sunday afternoon to help you. I do not work for BTT, I never received any payment from them ever.

> Yes, but the Bigtreetech TFT display doesn't solve the problem.

Also true that the Bigtreetech TFT display didn't create the problem. It's an incompatibility issue and that's it., take it or leave it.

**Comment by DrumClock** [comment]
> I have to let you know that I am also just a user who spent 1 hour of his free time on a Sunday afternoon to help you. I

Thanks, I spent two days of my time doing that and basically he figured it all out on his own

**Comment by kisslorand** [comment]
Chill dude!
Happy printing, have a nice Sunday, stay safe, happy Valentine's Day, etc.!

**Comment by DrumClock** [comment]
> Later edit: Try to rotate the encoder while powering up, it might do the trick.

Chill dude, kisslorand !

late: I have already done HW and SW modification of the Rumba32 board, when it could not be solved FW TFT35 E3 ....

![PB3](https://user-images.githubusercontent.com/64655979/107973221-4312c780-6fb5-11eb-987b-ae24bcf6427d.jpg)
