### ISSUE TITLE
default settings?

### ISSUE THREAD

**Issue by 3dfixer** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1625]
so i'm following instruction on readme.md. install new firmware on tft. then told to :-

""On the TFT click on Menu - Settings - Feature and navigate to the last page. Click on
"Reset default settings ..."
power cycle and poof, all my settings/changes to config.ini disappear.

question?  where does it get default settings from? 
thought that was what config was for, and that resetting was to take
you back to config settings after you've been buggering about.

**specify the device variant related to your question.**
skr v1.4 & tft35 v3

Also, totally unrelated, i keep getting this pop up, dunno if bigtreetech are cursing me or not :-)
![20210213_132411](https://user-images.githubusercontent.com/17735661/107852168-1caf2980-6e07-11eb-82af-8588c3366cc4.jpg)

**Comment by digant73** [comment]
The default settings are the hard coded values while the config.ini is used to overwrite the defalut values. If you omit a param setting in config.ini, its default value is used

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by 3dfixer** [comment]
So dont reset settings if you use config.ini.  thanks digant73
