### ISSUE TITLE
[FR] Scroll long file names in TFT mode while printing

### ISSUE THREAD

**Issue by sarvenn** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1630]
**Is your feature request related to a problem? Please describe.**
While printing a thing long file names scrolls in Marlin mode (relevant feature is enabled in my marlin config), but in TFT mode file name does not scroll.
My request is to have long file name scroll feature in print screen.
![20210217_163432](https://user-images.githubusercontent.com/66178082/108212180-a0865000-713e-11eb-99e1-8a820801c438.jpg)

**Comment by kisslorand** [comment]
IIRC it was like that but it could hurt the print quality so it was removed.
During printing it's best to leave the TFT alone and let it do the most important job, to send printing gCodes.

**Comment by sarvenn** [comment]
Oh ok, so that request will have a load on the TFT processor and may cause issues during printing, right?
If so, it is better to leave like that :) It was just a "nice to have" idea.

**Comment by kisslorand** [comment]
Yes, scrolling text adds load to the TFT.
