### ISSUE TITLE
[Q] (How can i use turkish charset)

### ISSUE THREAD

**Issue by EmA04** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1631]
**Hello,
ı am using SKR V1.3 motherboard and TFT35 v2.0 touchscreen  i need use turkish charset How can i do it?**
A clear and concise question or detail you would like to ask. Like Hardware related or firmware related.

**TFT35 V2.0**

**Additional context**
Add any other context or screenshots about the question here.

**Comment by EmA04** [comment]
> **Hello, ı am using SKR V1.3 motherboard and TFT35 v2.0 touchscreen i need use turkish charset (example: ı İ ç Ç ğ) How can i do it?**
> A clear and concise question or detail you would like to ask. Like Hardware related or firmware related.
> 
> **TFT35 V2.0**
> 
> **Additional context**
> Add any other context or screenshots about the question here.

**Comment by radek8** [comment]
What do you need it for?
Terminal mode is used to send commands not to write novels :-)

**Comment by radek8** [comment]
My language also uses special accents and characters, but I don't miss the display.

**Comment by EmA04** [comment]
I want to use this characters for menu.

**Comment by radek8** [comment]
They are used in the Turkish menu

![image](https://user-images.githubusercontent.com/46979052/108246626-f0224700-7151-11eb-8a1d-805c47951860.png)

**Comment by EmA04** [comment]
those characters are not visible

**Comment by radek8** [comment]
![IMG_20210217_191237_resized_20210217_071525006](https://user-images.githubusercontent.com/46979052/108248810-9cfdc380-7154-11eb-97ba-7556d55276d5.jpg)
![IMG_20210217_191319_resized_20210217_071525280](https://user-images.githubusercontent.com/46979052/108248816-9ec78700-7154-11eb-8e15-a87643e100df.jpg)
![IMG_20210217_191247_resized_20210217_071525490](https://user-images.githubusercontent.com/46979052/108248830-a0914a80-7154-11eb-9e24-c1e5619127ef.jpg)
![IMG_20210217_191343_resized_20210217_071525638](https://user-images.githubusercontent.com/46979052/108248839-a1c27780-7154-11eb-9574-b32d8a211159.jpg)
![IMG_20210217_191348_resized_20210217_071525826](https://user-images.githubusercontent.com/46979052/108248849-a38c3b00-7154-11eb-9251-c852b564f9e1.jpg)
![IMG_20210217_191255_resized_20210217_071526064](https://user-images.githubusercontent.com/46979052/108248860-a555fe80-7154-11eb-89a0-72c797b04007.jpg)

**Comment by EmA04** [comment]
I could not. I choose the language as Turkish but different characters come out

**Comment by radek8** [comment]
You have an old FW

**Comment by EmA04** [comment]
I am using (THEME_Unified Menu Material theme) theme.

**Comment by radek8** [comment]
Did you update the font as well?

**Comment by EmA04** [comment]
No, i can't updated FW

**Comment by EmA04** [comment]
I'm getting an error while updating

**Comment by EmA04** [comment]
![dsadasf](https://user-images.githubusercontent.com/79212513/108249913-b576d980-7166-11eb-849d-00a910634938.PNG)
![fedew](https://user-images.githubusercontent.com/79212513/108249922-b7d93380-7166-11eb-8b0c-7c7ab5fc6dea.PNG)

**Comment by radek8** [comment]
You don't have to compile your own FW.
Use precompiled and configure ini file.
Follow the instructions on the title page

**Comment by sarvenn** [comment]
It is explained in the README section of the main page. Check the firmware update section in that text.

**Comment by EmA04** [comment]
The screen is not with me right now. I'll try again tomorrow and return

**Comment by EmA04** [comment]
peki menüden led menüsünü nasıl kaldırabilirim

**Comment by EmA04** [comment]
So how can I remove the led menu from the menu

**Comment by radek8** [comment]
That has already been solved here ...
If you don't know what you're doing, don't do it

**Comment by radek8** [comment]
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/1053

**Comment by EmA04** [comment]
Sorry but my english is not very good. I looked a little and couldn't find a Turkish source and had to ask here. Sorry to keep busy

**Comment by oldman4U** [comment]
In the ReadMe it says clearly self compiled OR a pre-compiled firmware, the config.ini and a TFT folder as well as OPTIONALLY a language pack.
<img width="927" alt="Screenshot 2021-02-17 at 22 09 20" src="https://user-images.githubusercontent.com/54359396/108268650-1f927d00-716d-11eb-905e-1e9ca7141c56.png">

Please help the community and close the ticket once you do not need it anymore.

Thank you and happy printing
