### ISSUE TITLE
Load/unload menu Nozzle button does not change the displayed Nozzle Number (T0 etc)

### ISSUE THREAD

**Issue by jimhiggs** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1637]
Searched but could not find this issue listed. 
Board: TFT35V2 
Firmware:  26x, Current?

### Description
Load/unload menu Nozzle button does not change the displayed Nozzle Number (T0 etc)

Solution:
In LoadUnload.c Line #100 is:
`curExt_index = (curExt_index + 1) % infoSettings.hotend_count;`
Should be:
`curExt_index = (curExt_index + 1) % infoSettings.ext_count;`

**Comment by kisslorand** [comment]
Good finding but hard to know which nozzle has to be heated. You can have IDEX or only DEX.
Someone introduced nozzle temp check before Load or Unload and it assumes you have IDEX, you have to have the nozzle attached to the extruder heated.

**Comment by jimhiggs** [comment]
I only have one mixing nozzle but three extruders so its great this now works for me.

**Comment by kisslorand** [comment]
I do not think it can be made "one size fits all". What if you have 2 carriages, one regular and the other one a mixing one with 5 etxruders? It's a nightmare to implement every possible situation/config.

**Comment by jimhiggs** [comment]
That is true. Seems to me we have mixing nozzle and multi-extruder fairly well sorted. At least at my fairly basic level of understanding.

**Comment by oldman4U** [comment]
Hi jimhiggs

Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by jimhiggs** [comment]
Has the bug been taken up for fix?

**Comment by oldman4U** [comment]
@kisslorand 

Anything you pr another developer can fix here?

**Comment by oldman4U** [comment]
No reply is also an answer.

Please help the community and close the ticket once you do not need it anymore. Thank you
