### ISSUE TITLE
[FR] (G26 mesh validation )

### ISSUE THREAD

**Issue by labotecno** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1645]
hello
 in marlin we have G26 mesh validation its a usefull option  , but when i get enable , i get a windows tft error :"G26 repeat must be specified when not using on lcd"

**Comment by labotecno** [comment]
i was see i need to put G26 R1  but now its give me "not sd printing ?"

**Comment by labotecno** [comment]
ok its working like this way G26 R99  if you put only one its not working 
it s possible to put one icone on abl menu ? thank you

**Comment by labotecno** [comment]
someone here ?

**Comment by labotecno** [comment]
[https://github.com/labotecno/BIGTREETECH-TouchScreenFirmware](url)

**Comment by oldman4U** [comment]
You are not alone 🤚🏻

**Comment by labotecno** [comment]
> 
> 
> You are not alone 🤚🏻

can you tell me if PR is ok ?

**Comment by oldman4U** [comment]
is it available? can not see it in the PRs...;-(

**Comment by oldman4U** [comment]
Do you need help pushing the PR? On Mac you can push the local repository directly to a PR on GitHub. It's magic how this works. 🤩

**Comment by labotecno** [comment]
> 
> 
> Do you need help pushing the PR? On Mac you can push the local repository directly to a PR on GitHub. It's magic how this works. 🤩

ok i think i get it now , but i have file on conflict i hope its not a problem , if is it how to resolve it ?

**Comment by Guilouz** [comment]
> > Do you need help pushing the PR? On Mac you can push the local repository directly to a PR on GitHub. It's magic how this works. 🤩
> 
> ok i think i get it now , but i have file on conflict i hope its not a problem , if is it how to resolve it ?

Because you don't use latest master with your pull request.

**Comment by labotecno** [comment]
> 
> 
> > > Do you need help pushing the PR? On Mac you can push the local repository directly to a PR on GitHub. It's magic how this works. 🤩
> > 
> > 
> > ok i think i get it now , but i have file on conflict i hope its not a problem , if is it how to resolve it ?
> 
> Because you don't use latest master with your pull request.

where is the latest master ? thank you

**Comment by kisslorand** [comment]
Here: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware

**Comment by ETE-Design** [comment]
@labotecno Seems like your PR disapeared?

**Comment by labotecno** [comment]
> 
> 
> @labotecno Seems like your PR disapeared?

i get some problem with conflict but now i think its ok ! thank you every one [https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/1688](url)

**Comment by digant73** [comment]
@labotecno please close this FR now that it was merged to main branch

**Comment by labotecno** [comment]
> 
> 
> @labotecno please close this FR now that it was merged to main branch

ok ready !

**Comment by ETE-Design** [comment]
@labotecno Did you ever got G26 merged so it has an Icon on the TFT?
