### ISSUE TITLE
[Q] What is the file format for the "printing.sys"?

### ISSUE THREAD

**Issue by Rodov** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1654]
**Your question or details you need. Please describe.**
Printed from LCD emulation. There was a surge in electricity. Printing has stopped. 
What is the file format for the "printing.sys"? 
I want to make the file and continue from the right place (I know the layer).

**Comment by oldman4U** [comment]
Maybe editing the gCode file is easier then. It is a text file.

**Comment by oldman4U** [comment]
Please keep in mind that this is not a user group but a repository related to firmware.

**Comment by Rodov** [comment]
Printing.sys has a closed format?
Anyway I used gcode editing as you advised.
