### ISSUE TITLE
A couple of conspicuous errors on the TFT70 display

### ISSUE THREAD

**Issue by AntoszHUN** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1659]
I have attached a couple of (picture) glaring bugs. These errors are quite noticeable on the TFT70 display.

![DSC_0017](https://user-images.githubusercontent.com/45710979/109671820-b51e0b80-7b74-11eb-92ed-5ba18a36cc80.JPG)
Does not show the height of the first layer when you start printing. Only update when you have finished 1-2 layers.

![DSC_0026](https://user-images.githubusercontent.com/45710979/109671996-df6fc900-7b74-11eb-8832-263c7675adb0.JPG)
Caption location is an obvious error.

Made By: AntoszHUN

**Comment by oldman4U** [comment]
Maybe you want to add TFT70 to the title.

**Comment by AntoszHUN** [comment]
> 
> 
> Maybe you want to add TFT70 to the title.

Ohh sorry.

**Comment by AntoszHUN** [comment]
During printing, there are moments when the subject cooler does not turn on or change gear.
