### ISSUE TITLE
[BUG] (short description)

### ISSUE THREAD

**Issue by burakturkoglu54** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1665]
#
### Steps to reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior**

**Actual behavior**

### Additional Information
* Include a ZIP file containing your `Configuration.h` or use [Pastebin](https://pastebin.com/) and paste a link in this issue.
* Provide pictures or links to videos that clearly demonstrate the issue.

**Comment by burakturkoglu54** [comment]
1633

**Comment by radek8** [comment]
Are you a 5 year old child who does not know what he is doing?

**Comment by kisslorand** [comment]
No, he's 6.:)
