### ISSUE TITLE
[FR] reopen #1179, add other tmc driver to the menu for current.

### ISSUE THREAD

**Issue by BlackDragon2020** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1671]
I found ticket number 1179, but could not comment.

Here is my comment to the ticket.

Going to see if I can reopen this. I for one am back to modding my rig. I have bought some motors that are different than stock and would benefit from being able to set current per driver. I set my z2 with the gcode.

If we are still space limited. Setting a few variable and if statement using preprocessing #define , #if etc.. could easily add N number of stepper drivers with very minimal extra space.

If this is something of interest and no one wants to take up I can see if I can go through the code and get back into the flow of this project, but someone who knows the tmc section and has a good grasp with c++ could bang this out in about 30min I bet. It would take me a few days of review I bet before I could start any coding.

**Comment by guruathwal** [comment]
I am working on separating dual/triple stepper for all X Y Z and E axes which would allow setting allof the parameter variables individually for each motor. You have to wait a little bit more as currently some code cleanup and bug spray is required before proceeding further.

**Comment by BlackDragon2020** [comment]
> I am working on separating dual/triple stepper for all X Y Z and E axes which would allow setting allof the parameter variables individually for each motor. You have to wait a little bit more as currently some code cleanup and bug spray is required before proceeding further.

You have been kicking @$$. Keep up the good work.
