### ISSUE TITLE
[BUG] Popup error.

### ISSUE THREAD

**Issue by radek8** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1676]
Pop-up error when printing was not completed.
If my primary language is set to English, a popup window will appear normally.
If the secondary language is set, both the window name and the dialog buttons have the wrong description.

EN
![image](https://user-images.githubusercontent.com/46979052/110221745-60f58d00-7ece-11eb-9ef4-b72954a94943.png)

PL
![image](https://user-images.githubusercontent.com/46979052/110221757-6fdc3f80-7ece-11eb-8302-a567a7d8a5b6.png)

CZ
![image](https://user-images.githubusercontent.com/46979052/110221844-be89d980-7ece-11eb-9701-daaf2e6f035b.png)

**Comment by kisslorand** [comment]
Can you check by using second language also English (or any other)?

**Comment by radek8** [comment]
Secondary English

![image](https://user-images.githubusercontent.com/46979052/110222282-5a1c4980-7ed1-11eb-913b-788bfea0b08f.png)

**Comment by kisslorand** [comment]
Thx for the test, the result makes it a general bug.
