### ISSUE TITLE
[FR] Make the LED/Lights menu in TFT mode more feature complete

### ISSUE THREAD

**Issue by lightmaster** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1687]
**Is your feature request related to a problem? Please describe.**
Can not set a Custom Light using the TFT Touch Screen mode without resorting to using terminal and `M150` command. If the average user that doesn't know much about gcode commands wants to change the LEDs to something besides Red, Green, Blue, and White, then they have to switch to Marlin mode and can then have full access to Marlin's much more fleshed out Lights menu. Furthermore, I propose expanding the preset colors to also include the other primary and secondary colors used by Marlin (ROY G BIV colors).

**Describe the solution you'd like**
Kinda feel that's pretty self explanatory from above, but I'd like the TFT Touch Screen LED menu to be more fleshed out and have the options that Marlin Mode has.

**Describe alternatives you've considered**
Encourage anyone wanting to play around with the LED colors to use Marlin Mode, or continue to require them to understand GCode and RGB color codes

**Additional context**

**Comment by oldman4U** [comment]
How many of this ecustom colours should be possible and how would such custom colours look like on screen, custom buttons?

I can see this a lot of work for little benefit and there are custom gCode commands which could be used for that.

my 2 cents

**Comment by bigtreetech** [comment]
Maybe it can add a custom button in the LED Color menu. After clicking in, it can directly set the value of each R/G/B by the keyboard?
It's a good idea, and It can reuse Custom icon without adding new icons avoid taking up more flash memory.
We are going to release a new version of firmware in the near future. The main task at present is to test and fix bugs. If you are willing to submit PR to add this function , I will be verry happy to test it.

**Comment by lightmaster** [comment]
Going back to the LED menu, I didn't realize how few space there is without shrinking the icons and potentially causing issues with smaller screens and bigger fingers....

So what about a Custom icon like @bigtreetech described, and potentially a second icon called "Other" to fill the final open spot and it directs to a menu that has a list various other colors. This menu would look like the Custom GCode menu.

**Comment by DaStivi** [comment]
i think it would be ah nice idea... I'd might have another one, do add some sort of option to auto enable lightning from the features menu? like to turn on white light from the start without having to go into the menu's or use the gcode

**Comment by lightmaster** [comment]
> 
> 
> i think it would be ah nice idea... I'd might have another one, do add some sort of option to auto enable lightning from the features menu? like to turn on white light from the start without having to go into the menu's or use the gcode

You mean when the printer turns on? My NeoPixel turns on at boot. If you have an RGB strip and it doesn't, that's probably a better thing to bring up in the Marlin Github. If you have NeoPixel, check your config: https://github.com/MarlinFirmware/Marlin/blob/b26516b3ac7cd7d15a751af4b299a38ac8ac7a57/Marlin/Configuration_adv.h#L1107

**Comment by oldman4U** [comment]
Hi. What is the status of the feature request?

**Comment by bigtreetech** [comment]
> Hi. What is the status of the feature request?

Waiting for implementation

**Comment by digant73** [comment]
Now it is implemented
