### ISSUE TITLE
[BUG] Issue with M600 when printing from SD/USB TFT

### ISSUE THREAD

**Issue by Guilouz** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1689]
### Description

There is a recent issue with the M600 when printing via SD / USB from the TFT (this has worked before).

M600 is considered like a simple pause, TFT does not indicate that the hotend has been parked (but it comes well parked
), no retraction of the filament is performed, no popup to ask the user to purge again or to restart the print. There is only the start button which allows you to resume printing as a simple pause.

No issue when printing from Octoprint, M600 plays the job as it should and the TFT displays the necessary popups.

### Steps to reproduce

Just print from SD/USB with M600 in Gcode file

I use latest TFT firmware from master and latest 2.0 bugfix from Marlin

**Comment by oldman4U** [comment]
Do you know which PR broke it?

**Comment by Guilouz** [comment]
> Do you know which PR broke it?

I tried to find it but without success:(

**Comment by kisslorand** [comment]
Check _interfaceCmd.c_ for:

        #ifdef NOZZLE_PAUSE_M600_M601
          case 600: //M600/M601 pause print
          case 601:
            if (isPrinting())
            {
              setPrintPause(true, false);
              // prevent sending M600/M601 to marlin
              purgeLastCmd();
              return;
            }
            break;
        #endif

and see what happens if you comment `purgeLastCmd()`.

**Comment by labotecno** [comment]
> 
> 
> Check _interfaceCmd.c_ for:
> 
> ```
>     #ifdef NOZZLE_PAUSE_M600_M601
>       case 600: //M600/M601 pause print
>       case 601:
>         if (isPrinting())
>         {
>           setPrintPause(true, false);
>           // prevent sending M600/M601 to marlin
>           purgeLastCmd();
>           return;
>         }
>         break;
>     #endif
> ```
> 
> and see what happens if you comment `purgeLastCmd()`.

yes will be a good thing to check every step of the script M600 like lcd grafic way .could be possible ?

**Comment by Guilouz** [comment]
> Check _interfaceCmd.c_ for:
> 
> ```
>     #ifdef NOZZLE_PAUSE_M600_M601
>       case 600: //M600/M601 pause print
>       case 601:
>         if (isPrinting())
>         {
>           setPrintPause(true, false);
>           // prevent sending M600/M601 to marlin
>           purgeLastCmd();
>           return;
>         }
>         break;
>     #endif
> ```
> 
> and see what happens if you comment `purgeLastCmd()`.

I'm testing this tonight. Thanks.

**Comment by Guilouz** [comment]
> Check _interfaceCmd.c_ for:
> 
> ```
>     #ifdef NOZZLE_PAUSE_M600_M601
>       case 600: //M600/M601 pause print
>       case 601:
>         if (isPrinting())
>         {
>           setPrintPause(true, false);
>           // prevent sending M600/M601 to marlin
>           purgeLastCmd();
>           return;
>         }
>         break;
>     #endif
> ```
> 
> and see what happens if you comment `purgeLastCmd()`.

Just try with purgeLastCmd() commented and it's worse, the screen freeze when M600 is supposed to trigger.

**Comment by kisslorand** [comment]
Try what happens if you send `M25 P`.
`M600` just sends `M600`, nothong more, nothing less.

**Comment by Guilouz** [comment]
> ADVANCED_PAUSE

Yes ADVANCED_PAUSE is enabled, all working fine when printing from Octoprint, just issue with SD/USB from TFT.

I will try with M25 P, with M125 in terminal no issue, I have 'Nozzle parked' popup, 'PurgeMore' etc...

**Comment by kisslorand** [comment]
This ticket is about `M600`. I will look into it. In fact I wanted to do that today but I am too tired.

**Comment by Guilouz** [comment]
> This ticket is about `M600`. I will look into it. In fact I wanted to do that today but I am too tired.

Yes M600, but it’s understood as a simple M25 pause when printing from SD / USB, that's why I wanted to test the M125 which behaves like an M600.

**Comment by kisslorand** [comment]
No, M25 is triggered only if printed from Onboard SD. M600 triggers the same as if you would press "Pause".

**Comment by Guilouz** [comment]
> No, M25 is triggered only if printed from Onboard SD. M600 triggers the same as if you would press "Pause".

Precisely the M600 is not supposed to trigger the same thing as a pause. That's you mean ?

A simple pause : press "pause" on tft, if PARK_HEAD_ON_PAUSE is enable, hotend is parked until you press "Resume"

With M600 : when is detected, TFT show a popup "Nozzle parked", filament is retracted, the heating of the hotend is stopped (safe if the user is not in front of his machine), TFT ask to user to heat hotend, when temperature is reached, a purge of filament is done, TFT ask to user if he want to purge more or continue the print. It's the same process as with a detection of filament sensor.

**Comment by bigtreetech** [comment]
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/blob/78a7560b3678f4456e130191a945af54fbf055ec/TFT/src/User/Configuration.h#L302
Can solve your problem from comment out here?

**Comment by digant73** [comment]
@Guilouz aren't you sure that in the past it worked because you commented out #define NOZZLE_PAUSE_M600_M601 in Configuration.h?
As far as I remember the emulated M600 (so handled by TFT) was always the same (a simple pause).
If you comment out #define NOZZLE_PAUSE_M600_M601 the M600 gcode is sent and handled by Marlin (if you configured it properly)

**Comment by Guilouz** [comment]
> https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/blob/78a7560b3678f4456e130191a945af54fbf055ec/TFT/src/User/Configuration.h#L302
> 
> 
> Can solve your problem from comment out here?

#define NOZZLE_PAUSE_M600_M601 is not commented in my configration.h

**Comment by kisslorand** [comment]
>  no retraction of the filament is performed,

Are you sure? Not even a few mm?

**Comment by oldman4U** [comment]
Do I understand this right that for one it works in case #define NOZZLE_PAUSE_M600_M601 is Deactivated and for the other one it works in case it is activated....?

**Comment by oldman4U** [comment]
Thank you. Makes sense.

**Comment by digant73** [comment]
> > Do I understand this right that for one it works in case #define NOZZLE_PAUSE_M600_M601 is Deactivated and for the other one it works in case it is activated....?
> 
> When disabled : M600 working as expected with configuration set in Marlin (nozzle parked, filament retraction, hotend heating deactivated until the user intervenes, possibility to purge more when the filament is inserted
> 
> When enabled : M600 behaves like a classic pause, like when pressing pause from the screen, just parked.

With M600 enabled you can also purge/retract with the extrude menu. So you should be able to do the same as the M600 handled by Marlin. Just using the features / menus provided by the TFT

**Comment by thsrp-bob-roger** [comment]
> With M600 enabled you can also purge/retract with the extrude menu. So you should be able to do the same as the M600 handled by Marlin. Just using the features / menus provided by the TFT

No, because you have a big retraction just before printing resumes and thus ruining the printing. But now with the M600 deactivated you have access to a real M600 with its configuration which was made in Marlin and it works perfectly ... In fact it is a bit strange and confusing to have to deactivate the M600 to have a REAL M600? ! Logic would have it the other way around ..?

**Comment by digant73** [comment]
Just to collect feedback for further improvements on emultaed M600, so the main problem with the emulated M600 is the excessive rectraction before the resume. Is everything else fine or there is something else that could be improved/fixed?
M600 is not supported on all the mainboard and in the past it was not properly handled by Marlin. For that reason by default emulated M600 was enabled.
The idea is to make the choice emulated M600 / real M600 configurable in config.ini in a further release

**Comment by thsrp-bob-roger** [comment]
> Now that M600 is properly handled by Marlin, the idea is to make the choice emulated M600 / real M600 configurable in config.ini in a further release

Yessss great idea !!
