### ISSUE TITLE
[Q] Z align can be with cmd console to see level acurate?

### ISSUE THREAD

**Issue by labotecno** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1692]
Z align can be with cmd console to see accurate level ? before i use it with the console i see the level of accuracy.
if someone tell me how to make it i will try to make the code . 
thank you

**Comment by Guilouz** [comment]
Maybe show a popup with values after completion ?

**Comment by labotecno** [comment]
> 
> 
> Maybe show a popup with values after completion ?

how to make that can you tell me ?
