### ISSUE TITLE
[BUG] serial always on option with esp3d not working

### ISSUE THREAD

**Issue by dielectric-code** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1700]
### Description

Enabling  'serial always on' option is not working as expected when switching TFT35 E3  mode to marlin mode
 ### Steps to reproduce

1. In touch mode, enable 'serial always on'
2. Switch to marlin mode from touch mode
3. Try to connect Octoprint via ESP3D wifi module installed on TFT35 E3 board via the wifi connector
4. The display is stuck with '...busy processing', no communication
5. Have to reset the printer
6. If we stay in the touch mode, all is OK.

**Expected behavior**

From what I understood in the comment of the conifig.ini, enabling serial always on should make serial communication from the TFT35 E3 board available in marlin mode also.

**Actual behavior**

No communication and display stuck with a busy processing message.

### Hardware Variant

TFT35 E3 V3
### TFT Firmware Version & Main Board Firmware details

TFT firmware taken from the 8 march 2121 'Copy folder'

**Comment by DaStivi** [comment]
> 3\. Try to connect Octoprint via ESP3D wifi module installed on TFT35 E3 board via the wifi connector

sorry don't understand that step... i've the ESP01s module on the UART port on the TFT, and octoprint connected via USB to the board directly... with latest tft fw and serial_always_on=enabled, and in marlin mode no problem to use ESP3D... everthing works as expected..

**Comment by DaStivi** [comment]
OK, interessting way of connecting.. Are there any benefites besides not having the USB? Question is really how stable is this connection?! 🤔

I gonna test this later...

**Comment by oldman4U** [comment]
Hi dielectric-code

Could you please try to connect via ESP3D web interface. I am also not able to verify what you report using ESP web interface.
![Screenshot 2021-03-10 at 09 15 11](https://user-images.githubusercontent.com/54359396/110597804-50b90880-8181-11eb-82a7-1b0047dce858.png)

**Comment by DaStivi** [comment]
i tried to home or even just read the printer config... but no matter if in touch or malin mode i didn't get any reaction from the TFT... but still i see updates in the terminal window... 🤷‍♂️ don't have to time to investigate further... but something strange..

**Comment by dielectric-code** [comment]
@DaStivi, the reason for a wifi connection is to have a rpi with octoprint/octodash that I can move around the house to monitor printing without using a PC all the time, like a "wireless head for the printer".
@oldman4U, Using ESP3D webui we have the same problem, if you try to retreive the printer parameters for example, sometimes nothing comes back ( as well as temperature and postions are not updated) we only see Temp. message from the terminal, sometimies nothing at all. Actually with further testing I noticed that we are receiving but if either ESP3Dwebui or octoprint send a command it does not go trough.

**Comment by dielectric-code** [comment]
I have made more test this morning, I suggest we close this for now.
I replaced the ESP3D module by a USB-serial adapter and it seems to work perfectly, so I suspect that this is not a problem with the TFT. I tested in marlin mode and touch mode (apart from minor difference in replies from the printer, all seems OK).
I really apologize for this, I should have done more tests!. Again sorry for all this. the problem is probably with the ESP3D module.

**Comment by DaStivi** [comment]
> I am testing with a usb to serial adapter connected via the wifi module port on the display. So the ESP3D wifi module is replaced by an FTDI232 module, I have the same results. This is bug is confusing to me, the marlin mode or TFT mode gives me the same problem, it seems that 'serial always on', seems ok. But for some unknown reason it seems the serial comm is "crashing" so to speak". It is a hit and miss situation, sometimes it works perfectly sometimes it does not. I will continue to test.

Could you just test ah older build like from 24.2. Because there where ah lot of fixes in the last weeks regarding the serial always in etc.. I where involved in some of. Them as I've reported them... And iam sure that with old builds reading the printer settings, etc all worked with esp3d!

**Comment by DaStivi** [comment]
Btw you did wrote something totally different be for editing isn't it? Because I just hit goto github from the Email notification, just to noticice after writing you wrote something completely different that what I just read ah minute before 😂🤔

**Comment by dielectric-code** [comment]
> Btw you did wrote something totally different be for editing isn't it? Because I just hit goto github from the Email notification, just to noticice after writing you wrote something completely different that what I just read ah minute before joythinking

Yes you are right, I thought there was no more problem using a serial-usb converter, but it turned out I was wrong ?!#@ duhh!

**Comment by dielectric-code** [comment]
@DaStivi, I will do more test this weekend, I have difficulty reproducing this behavior, I will be keeping the ftdi232 module for the tests and I will test all spare UARTs connections as well as the wifi port on the display board, plus I will test connecting directly to the main board (skr mini e3 v2) trough the TFT connections. Then all of this again with the ESP3D module, I will let you know.

**Comment by dielectric-code** [comment]
Made more tests this weekend,
with ftdi232 module, and using rpi3b rx/tx gpio pin connected to wifi port. both arrangement works ok, in marlin and tft mode (with serial always on enable). (conect, disconnect, print, disconect re-connect etc....)
Sometimes we get this 'busy message'. By a simple reset of the display and mainboard  we recover (I connected an rpi3b gpio pin to reset pin of display connector exp2.(control it with gpio octoprint plugin). I will try later on with the ESP3D module. I suggest that 'always on' serial option is OK and we could close this. The stuck on 'busy processing' message comes from either Marlin or a 'gone wild' display because some garbage was sent trough the serial connection, which is, in my opinion something else to look at.
![IMG_20210313_1225096](https://user-images.githubusercontent.com/78823828/111157851-bd5f4900-856d-11eb-8155-52f33da38228.jpg)
![IMG_20210313_1226325](https://user-images.githubusercontent.com/78823828/111157854-be907600-856d-11eb-99cf-431d0dc8b81a.jpg)
![IMG_20210314_0922282](https://user-images.githubusercontent.com/78823828/111157859-bf290c80-856d-11eb-86cb-fcdda43b72d5.jpg)
![IMG_20210315_0904295](https://user-images.githubusercontent.com/78823828/111157863-bfc1a300-856d-11eb-9834-5b001478c6e4.jpg)

**Comment by dielectric-code** [comment]
@DaStivi , @oldman4U , While using the printer using my last setup (rpi3 gpio serial connection and reset relay) I can repeat this behavior like I want;
1. Printer on, rpi3 on.
2. Initiate connect with Octoprint, on AUTO
3. It will fail.
4. Then reset the marlin and tft35  board, because it does not accept commands anymore (marlin or ttf35 ? this is what I do not konw) sometimes we get this busy message.
5. So after reset, initiate connect with Octoprint but using /dev/serial0 (that's how it is setup on rpi3b
6. It works, flawlessly for hours, tests ,prints, probe etc...
7. So there is nothing wrong with 'serial always on' option,.
8. Either marliin or TFT35 does not like the Octoprint 'port scan' and make it freeze. hmmm.
9. I htink next step is to connect directlyh to marlin tft serial port  ant test.
10. WIll report later.
