### ISSUE TITLE
M300 does not work through octoprint 

### ISSUE THREAD

**Issue by thsrp-bob-roger** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1702]
Hello Bigtreetech! 
Please, PLEASE...
Can you correct a little bug which should be easy to fix ... the Gcode M300 Play Tone (M300 Sxxx Pxxx) function works perfectly when printing through the SD card reader of the screen but is totally " silent "when printing through Octoprint 

Thank you Bigtreetech !!

**Comment by Guilouz** [comment]
Already reported here : https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/1099

**Comment by thsrp-bob-roger** [comment]
Yes but I don't know why BIGTREETECH hasn't done anything since September 2020 ?

**Comment by oldman4U** [comment]
This is an open source software project. So the question is more why no other user - like you and me - did it.

**Comment by oldman4U** [comment]
Like radek8 wrote. I am not sure this can be done in software even it looks like a trivial thing.

**Comment by bigtreetech** [comment]
BTT's touch screen is actually a host of the same level as octoprint. If M300 is sent from the TFT, the TFT will parse and control the buzzer to make the proper sound. However, if M300 is sent from octoprint to the motherboard, the motherboard's (Marlin) current protocol will not notify TFT through serial, so TFT can't know how and when to make the sound, To achieve this function, we need alse to modify the protocol in the mainboard(Marlin) first. Let Marlin broadcast the M300 code to other host through serial port when Marlin  received M300 code.

**Comment by bigtreetech** [comment]
> BTT's touch screen is actually a host of the same level as octoprint. If M300 is sent from the TFT, the TFT will parse and control the buzzer to make the proper sound. However, if M300 is sent from octoprint to the motherboard, the motherboard's (Marlin) current protocol will not notify TFT through serial, so TFT can't know how and when to make the sound, To achieve this function, we need alse to modify the protocol in the mainboard(Marlin) first. Let Marlin broadcast the M300 code to other host through serial port when Marlin received M300 code.

So the key point is whether this function is necessary to modify the Marlin section

**Comment by kind3r** [comment]
Or just connect your octoprint to the TFT, this way it will intercept M300 and buzz for you. The rest will go to Marlin.

**Comment by lightmaster** [comment]
I am unable to get M300 to play from a gcode file saved on SKR 1.4 Turbo's MicroSD card, even when that "print" is initiated by the TFT.

**Comment by lightmaster** [comment]
> Or just connect your octoprint to the TFT

How? The RPi3/4 can not be placed in OTG mode, therefore can not connect to a USB-A host.

**Comment by kind3r** [comment]
> I am unable to get M300 to play from a gcode file saved on SKR 1.4 Turbo's MicroSD card, even when that "print" is initiated by the TFT.

That is because the G-code is no longer passing through the TFT but instead read by the SKR straight from it's SD Card.

In 'normal' operation, when starting a print, the TFT reads the g-code from it's SD Card/USB and sends it to the printer. This way, it can 'see' what g-code it is sending and filter out and react to lines like M300.

> > Or just connect your octoprint to the TFT
> 
> How? The RPi3/4 can not be placed in OTG mode, therefore can not connect to a USB-A host.

Depending on the TFT you have, there may be extra serial ports on it. You can connect the PI to one of those ports instead of the SKR (you can use a USB/TTL adapter or the serial port on the GPIOs). Then the PI would send the commands to the TFT which will forward them to the SKR. This way, the TFT will 'see' all the g-code flowing from the PI to the SKR, filter and react to commands like M300.

**Comment by guruathwal** [comment]
There is only one speaker on the TFT. Only one device will be able to control it at a time. M300 will only work if it originated from TFT because Marlin does not forwards the commands to the TFT. When printing from the Onboard SD or through any other host, the TFT does not have any info about it.

**Comment by thsrp-bob-roger** [comment]
> There is only one speaker on the TFT. Only one device will be able to control it at a time. M300 will only work if it originated from TFT because Marlin does not forwards the commands to the TFT. When printing from the Onboard SD or through any other host, the TFT does not have any info about it.

Hello, what I do not understand is that with the original TFT screen (very low end) of the CR10S pro, we have the sound of the M300 when we print via Octoprint.? the original screen is connected in serial like the Bigtreetech, and the speaker is on the screen like the Bigtreetech ... The motherboard having no speaker or buzzer

**Comment by bigtreetech** [comment]
> Hello, what I do not understand is that with the original TFT screen (very low end) of the CR10S pro, we have the sound of the M300 when we print via Octoprint.? the original screen is connected in serial like the Bigtreetech, and the speaker is on the screen like the Bigtreetech ... The motherboard having no speaker or buzzer
That screen is a DWIN serial screen controlled by the EXTUI protocol of Marlin, not the general gcode protocol. The function of feedback M300 by serial port is encapsulated in EXTUI of Marlin.  Although they all communicate by UART, BTT TFT uses the general gcode protocol, which is different from DWIN EXTUI protocol.

**Comment by Eddiiie** [comment]
M600 not working this way is really bothering me.  What do we have to do to get this to work?    I have the EXP1 and EXP2 cables connected, it seems the TFT should be able to look at those?

Has anyone Connected Octoprint to the TFT screen?  Does this work OK?   I would do it; get rid of the USB cable going to the mainboard.

There are all sorts of wires, protocols, lights. buttons, but no whistles.    Need whistles!!
