### ISSUE TITLE
word_unicode and byte_ascii files cannot be update in TFT35 V1.2.

### ISSUE THREAD

**Issue by GrishaKh** [bigtreetech/BIGTREETECH-TouchScreenFirmware#171]
word_unicode and byte_ascii files cannot be update in TFT35 V1.2, but they are written in the boot.c file.
When I change the names word.fon and byte.fon, they are downloaded but not working correctly.
I've updated the firmware.

**Comment by guruathwal** [comment]
You need to copy the full TFT35 folder in your sdcard then preset reset button. It will update the fonts. Make sure you are using the latest font from the repository.

**Comment by GrishaKh** [comment]
I found the problem.
I am currently working on improving Armenian.
Thank you very much.
