### ISSUE TITLE
[BUG] Short press on 'Back' button often goes to main interface (but not always)

### ISSUE THREAD

**Issue by GregSKR** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1751]
Maybe I'wrong, but looks like the 'Back' button has sometimes a strange behavior...

eg (1):
-Go to: Menu > Movement > Bed Level > ABL
-Touch 'Preheat' button then 'Back'

eg (2):
-Go to: Menu > Extrude
-Touch 'Heat' button then 'Back'

Sometimes the 'Back' button goes to the previous menu (as it should), but sometimes (and always if you enter a temperature) it return to the main interface...

**Comment by digant73** [comment]
it seems the SMART_HOME feature enabled by default on Configuration.h.
A long press on Back button to move quickly on main screen.
Try to disabe it and you should solve it

**Comment by kisslorand** [comment]
@GregSKR 
When you short-press the Back button what sound do you hear? Everytime the same or sometimes a "click" sound and other times a double sound (like "tu-di")?

**Comment by oldman4U** [comment]
Welcome back Greg. Seems you missed some new features 😁

**Comment by GregSKR** [comment]
Thanks for your anwers!

@digant73 : thanks for the information, disabling SMART_HOME gives normal 'back' fonction everywhere
@kisslorand : the sound is 2 short bips "do"..."di" when returning to the main screen but different that the smart home sound.
@oldman4U : yes, I didn't make an update for a long time (was waiting for a stable version) and missed a lot of things 😁 

See the video: first press is a long press (smart home), all others are short press (touch_sound disabled in my config).
Sometimes, the back button goes back, but often it goes to the main interface (and sounds different than smart home).
I discovered that the problem is in all menus!

https://www.youtube.com/watch?v=SdptFecX5WA

My screen is a TFT35 v2.0
Will disable SMART_HOME (but it was a nice functionality) if there no other solution...

**Comment by bttguy** [comment]
@GregSKR Maybe update the fw or wait a few days for the sable version. I tried to force the issue as seen in the video, but for me it works 100% as intended using a few days old fw. Which version do you have?

**Comment by kisslorand** [comment]
@bttguy 
It doesn't matter which version he has, the smart_home hasn't been changed since it's been merged.
Looking at the video seems to me it is some kind of timer issue. The long "do"..."di" sound is a hint that the TFT is very busy with something (or the same timer issue), it cannot execute the two beep commands one after the other fast enough.
I cannot reproduce it. :(

**Comment by GregSKR** [comment]
I did a few more tests...
I changed the long press delay to 3 seconds
`#define LONG_TOUCH 3000`
What I can see now is that when a menu is displayed, a short press on 'Back' before 3 seconds gives normal back function, but if I wait  more than 3 seconds and short press 'Back', I got a smart home with 2 bips...

My screen is a TFT35 v2.0, so no Marlin mode, and no encoder knob, maybe something is different here from other screens?

I'm going to disable smart_home, it's buggy for my TFT.
Thanks for your help! 😉

**Comment by oldman4U** [comment]
So the value defines how long a return press is a previous page press instead of defining how long the button has to be pressed.

@kisslorand Would it make sense to see if it behaves the same on a BTT TFT28?

**Comment by kisslorand** [comment]
@GregSKR
Can you please reactivate touch sound and check if you hear it when it is not supposed to sound?

**Comment by GregSKR** [comment]
@kisslorand
touch sound reactivated: yes, I hear it when short press goes to main menu (got smart home sound too).
And doing a long press: touch sound when button is pressed, smart home sound when I release it.

**Comment by kisslorand** [comment]
I am working on a fix now. Is it OK for you if I upload a file and compile the FW with that file?
I cannot reproduce the issue so I rely on you. Until a fix is found it is pointless to make a PR for it.

**Comment by GregSKR** [comment]
@kisslorand 
Thanks! Yes I'm OK... 😃

**Comment by kisslorand** [comment]
Here's the file:

[menu.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/6178048/menu.zip)

**Comment by GregSKR** [comment]
Just tested... but the problem is still here, I see no difference 😢

**Comment by kisslorand** [comment]
I cannot find any software issue. The way I rewrote the procedure, it cannot go back to main menu unless the touch is long-pressed. I suspect a HW issue. Long press on any other icon triggers the Marlin/Touch selection menu?

**Comment by oldman4U** [comment]
TFT35 v2 has no encoder and can not switch to Marlin
![s-l300](https://user-images.githubusercontent.com/54359396/111916712-8fea3200-8a7c-11eb-89ca-efedfa528fdb.jpg)

**Comment by GregSKR** [comment]
Like @oldman4U just said, no Marlin mode here, so long press on other icons do the same than short press...

**Comment by kisslorand** [comment]
I have a MKS TFT28 without encoder and it enters into Marlin/Touch selection menu.

**Comment by GregSKR** [comment]
This is not related to the encoder, but the Marlin emulator.
In my case, `HAS_EMULATOR` is not def

**Comment by kisslorand** [comment]
Understood, I just wanted to see how does your TFT handles long press in another situation.
Would you please enable the emulator just to see what happens?

**Comment by GregSKR** [comment]
I added `#define HAS_EMULATOR` in **pin_TFT35_V2_0.h**
All is working as it should now!!!
Long press on the screen trigger the menu "Marli mode / Touch mode", long press on back trigger the smart home and short press on back always go back...

Try to comment `#define HAS_EMULATOR` in your firmware, i'm sure you will reproduce the bug !

**Comment by kisslorand** [comment]
Yes! I can reproduce it now. Back to fixing it...

**Comment by kisslorand** [comment]
@GregSKR 
Please test this file:
[menu.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/6178330/menu.zip)

**Comment by GregSKR** [comment]
Yesssss! You did it!
All is fine now 😃 

Thanks a lot, @kisslorand 👍🏼

**Comment by kisslorand** [comment]
No, I thank you! You've been more than helpful.
Let's make a nice PR of it...

**Comment by GregSKR** [comment]
Nice! Issue closed 😉
