### ISSUE TITLE
Neopixel header

### ISSUE THREAD

**Issue by sinole1987** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1764]
is there a way to control nonpixel header on TFT screens. it seems that it is in parallel to knob led and it can control only 2 LEDs like the knob. can you increase number of LEDs.

**Comment by bigtreetech** [comment]
Yes, it is in parallel to knob led. We'll add the function of modifying LED quantity in config.ini. The current firmware only allows you to modify the number of LED in source code  and then compile and update. 

https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/blob/318c98d7a4360cef0cf1696b51d95fadcf87a198/TFT/src/User/Variants/pin_TFT35_E3_V3_0.h#L13
For example, TFT35 E3 V3.0 needs to modify the number of `NEOPIXEL_PIXELS` in `TFT/src/User/Variants/pin_TFT35_E3_V3_0.h` from 4 to the number you want

**Comment by oldman4U** [comment]
Stupid question. Where are the additional leds connected to?

**Comment by sinole1987** [comment]
I don't think  its on every Variant of the board. here are some examples:
![TFT43-50-70--01_04](https://user-images.githubusercontent.com/44652024/115059674-b80e5a80-9e9b-11eb-8d38-7caf3247d60a.gif)

**Comment by oldman4U** [comment]
Thank you. So it is a dedicated port. Time to activate one of the TFTs which has it 😁

**Comment by oldman4U** [comment]
In the PR also the TFT35 E3 v3 is mentioned to be supported. But this screen does not have a dedicated port !? I am 🤪

**Comment by sinole1987** [comment]
my TFT43 Screen have so many ports that i have no idea what any of them do. I have UART ports near mounting holes, it was a nightmare designing a mount for this screen.

**Comment by oldman4U** [comment]
The perfect reason to buy a TFT70!!!😁
