### ISSUE TITLE
[BUG] tft 35 for ender fw blocking issue on pause/restart

### ISSUE THREAD

**Issue by EnzoCastellaneta** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1766]
### Description

Updated to last fw, adding red icons and italian language, the system when paused under a job, do not resume showing continuosly a window in asking "paused for user" and looping continuosly - no way to close it and start over the job.

Posted also on Reddit and several other users have the same problem
### Steps to reproduce

1. last firmware updated showing red icons
2. start a job
3. pause it. Then a window in saying "paused for user" pop ups and even if closed (pressing x) re-pops up asking the same thing. No way to restart the job. Cutting off current is the only way to restart - loosing the job.

**Expected behavior**
restart the job once I click the window and the button restart under that window

**Actual behavior**
I try to not stop and it works... but if ever I do need to pause... I will loose the job

### Hardware Variant
35 for ender
### TFT Firmware Version & Main Board Firmware details
Last one BIGTREE_TFT35_V3.0_E3.26.x and btt skr v2 last firmware too (compiled one with 3dtouch and z sensor removed)

### Additional Information
* Include a ZIP file containing your `Configuration.h` or use [Pastebin](https://pastebin.com/) and paste a link in this issue.
* Provide pictures or links to videos that clearly demonstrate the issue.

**Comment by oldman4U** [comment]
Read in config.ini which parameters in Marlin Firmware have to be activated and change your Marlin accordingly. Make sure to use nightly build Marlin otherwise a Marlin bug in STM32 will cause a freeze or crash when pressing Purge More. Once it works let all the other users on Reddit know and close this ticket. 

Thank you

**Comment by oldman4U** [comment]
Any news?

**Comment by EnzoCastellaneta** [comment]
hi,out of home, back on late friday - I will do my best yo support and give fbkInviato dal mio Galaxy
-------- Messaggio originale --------Da: oldman4U ***@***.***> Data: 24/03/21  17:31  (GMT+01:00) A: bigtreetech/BIGTREETECH-TouchScreenFirmware ***@***.***> Cc: EnzoCastellaneta ***@***.***>, Author ***@***.***> Oggetto: Re: [bigtreetech/BIGTREETECH-TouchScreenFirmware] [BUG] tft 35 for ender fw blocking issue on pause/restart (#1766) 
Any news?

**Comment by oldman4U** [comment]
Perfetto.

**Comment by oldman4U** [comment]
And now?

**Comment by digant73** [comment]
ciao Enzo, hai avuto modo di verficare? facci sapere per favore

**Comment by oldman4U** [comment]
He does not want to eat, even you put the spoon in his mouth...

Maybe someone can tell the lost souls at Reddit to read the manual...

Let the bot do the job here

**Comment by EnzoCastellaneta** [comment]
wise people listen others screaming in the lone silence of daily life.THE QUESTION IS: are you listening or screaming?Have a good day.E.Inviato dal mio Galaxy
-------- Messaggio originale --------Da: oldman4U ***@***.***> Data: 30/03/21  20:53  (GMT+01:00) A: bigtreetech/BIGTREETECH-TouchScreenFirmware ***@***.***> Cc: EnzoCastellaneta ***@***.***>, Author ***@***.***> Oggetto: Re: [bigtreetech/BIGTREETECH-TouchScreenFirmware] [BUG] tft 35 for ender fw blocking issue on pause/restart (#1766) 
He does not want to eat, even you put the spoon in his mouth...
Maybe someone can tell the lost souls at Reddit to read the manual...
Let the bot do the job here

**Comment by oldman4U** [comment]
And there are others screaming and crying because they do not read what is written.

Please close this ticket as it is unrelated to this repository and steals the valuable time of us.

Thank you

**Comment by EnzoCastellaneta** [comment]
Hi, just updated with last nightly build fw and other files. 
Checked config.ini.
Updated, saved, restarted - started printing - paused ... still same problem

![20210401_090300](https://user-images.githubusercontent.com/77235103/113256828-029fac80-92ca-11eb-8a40-0a4dfa66ab7b.jpg)

I add photo of it and details of what updated.
I also used 3h ago firmware update BIGTREE_TFT35_V3.0_E3.26.x.bin
In the following the config.ini

Pls. remember I add italian language file (updated) and red icons theme (same)

#--------------------------------------------------------------------
#
# DEFAULT CONFIG FILE FOR BigTreeTech TFT CONTROLLERS
#
#--------------------------------------------------------------------


#--------------------------------------------------------------------
# Supported TFT Variants
#--------------------------------------------------------------------
#
# BIGTREE_TFT35_V1_0    / BIGTREE_TFT35_V1_1 / BIGTREE_TFT35_V1_2
# BIGTREE_TFT35_V2_0    / BIGTREE_TFT35_V3_0 / BIGTREE_TFT35_E3_V3_0
# BIGTREE_TFT35_B1_V3_0 / BIGTREE_TFT43_V3_0 / BIGTREE_TFT50_V3_0
# BIGTREE_TFT70_V3_0    / BIGTREE_TFT28_V1_0 / BIGTREE_TFT28_V3_0
# BIGTREE_TFT24_V1_1    / MKS_32_V1_4        / MKS_28_V1_0
#
# Firmware source: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware


#--------------------------------------------------------------------
# Supported Marlin Firmware Versions
#--------------------------------------------------------------------
#
# Minimum Marlin firmware version: 2.0.5.4
# Distribution date: 2020-05-12
# Firmware source: https://github.com/MarlinFirmware/Marlin/releases
#
# In order the TFT firmware is able to provide all of its functionalities/features,
# ensure that the following options are enabled in Marlin firmware.
#
# General options:
#   EEPROM_SETTINGS (in Configuration.h)
#   AUTO_REPORT_TEMPERATURES (in Configuration_adv.h)
#   M115_GEOMETRY_REPORT (in Configuration_adv.h)
#   M114_DETAIL (in Configuration_adv.h)
#   REPORT_FAN_CHANGE (in Configuration_adv.h)
#
# Options to support printing from onboard SD:
#   SDSUPPORT (in Configuration.h)
#   LONG_FILENAME_HOST_SUPPORT (in Configuration_adv.h)
#   AUTO_REPORT_SD_STATUS (in Configuration_adv.h)
#   SDCARD_CONNECTION ONBOARD (in Configuration_adv.h)
#
# Options to support dialog with host:
#   EMERGENCY_PARSER (in Configuration_adv.h)
#   SERIAL_FLOAT_PRECISION 4 (in Configuration_adv.h)
#   HOST_ACTION_COMMANDS (in Configuration_adv.h)
#   HOST_PROMPT_SUPPORT (in Configuration_adv.h)
#
# Options to support M600 with host & (Un)Load menu:
#   Options to support dialog with host (as pre requisite)
#   NOZZLE_PARK_FEATURE (in Configuration.h)
#   ADVANCED_PAUSE_FEATURE (in Configuration_adv.h)
#   PARK_HEAD_ON_PAUSE (in Configuration_adv.h)
#   FILAMENT_LOAD_UNLOAD_GCODES (in Configuration_adv.h)
#
# Options to support Babystep menu:
#   BABYSTEPPING (in Configuration_adv.h)
#
# Options to support repeatibility test to test probe accuracy (M48):
#   Z_MIN_PROBE_REPEATABILITY_TEST (in Configuration.h)
#
# Options to support aligment of multiple Z steppers using a bed probe (G34):
#   Z_STEPPER_AUTO_ALIGN (in Configuration_adv.h)

#--------------------------------------------------------------------
# General Settings
#--------------------------------------------------------------------

#### Enable Status Screen
# Status screen or home screen displays the current temperature, fan and speeds.
# If this disabled, the main menu will become the default home screen.
#   Options: [Enable: 1, Disable: 0]
status_screen:1

#### Baudrate / Connection speed
# This baudrate setting is used for serial connection to the printer and other serial hosts like ESP8266.
#   Options: [2400: 0, 9600: 1, 19200: 2, 38400: 3, 57600: 4, 115200: 5, 250000: 6, 500000: 7, 1000000: 8]
baudrate:5

#### Default Touch Mode Language
# Select the language to display on the LCD while in Touch Mode.
# To add/flash a second language copy the required "language_xx.ini" file from "Language Packs" folder
# to the SD root folder. Then preset the reset button to load/flash the copied language file.
#   Options: [primary language (english): 0, secondary language: 1]
language:1

#### Default Touch Mode Colors
# Set colors used in touchscreen mode.
# Select an option from the provide list or set the color (RGB888 format) hex value directly (start with “0x”),
# such as: Red: 0xFF0000, Green: 0x00FF00, Blue: 0x0000FF.
#   Options: [ WHITE: 0,  BLACK: 1,  RED: 2,  GREEN: 3,      BLUE: 4,       CYAN: 5,  MAGENTA: 6,    YELLOW: 7,
#             ORANGE: 8, PURPLE: 9, LIME: 10, BROWN: 11, DARKBLUE: 12, DARKGREEN: 13,    GRAY: 14, DARKGRAY: 15]

## Title background color
title_back_color:1

## Background color
background_color:1

## Font foreground color
font_color:0

## Reminder font color, such as: "No print attached", "Busy processing", etc
reminder_color:2

## Volume status/reminder font color, such as: "Card inserted", "Card removed"
volume_status_color:5

## Backgroud color for X Y Z position display in Status Screen menu
status_xyz_bg_color:15

## List View border color
list_border_color:15

## List View button background color
list_button_bg_color:15

## Color used by the Mesh Editor menu for drawing the mesh with the minimun value in the grid
mesh_min_color:7

## Color used by the Mesh Editor menu for drawing the mesh with the maximum value in the grid
mesh_max_color:2

#### Rotate UI
# Rotate UI by 180 degrees.
#   Options: [enable: 1, disable: 0]
rotate_ui:0

#### Temperature ACK
# Show or hide temperature ACK in Terminal menu.
#   Options: [show: 1, hide: 0]
terminal_ack:0

#### Inverted Axes For Move Menu
# Invert axis button function in Move menu in order it matches the actual axis movement.
#   Format: [X<option> Y<option> Z<option>]
#   Options: [enable: 1, disable: 0]
invert_axis:X0 Y0 Z0

#### Persistent Temperature Info
# Show persistent temperature info on all menus.
#   Options: [enable: 1, disable: 0]
persistent_info:0

#### File List Mode
# Display files in list mode instead of icon mode.
#   Options: [enable: 1, disable: 0]
files_list_mode:1

#### Notification Style For ACK Messages
# Set the notification style to use for displaying the ACK messages which start with 'echo:'.
#
# NOTE: The OFF value is applied to any ACK message type (e.g. even to known echo ACK).
#       It means that any kind of ACK message is silently discarded.
#
#   Options: [OFF: 0, POPUP: 1, TOAST: 2]
#     OFF:   No notification. The message is ignored.
#     POPUP: Display a popup window for user confirmation.
#     TOAST: A non-blocking Toast notification is displayed for few seconds. No user interaction is needed.
ack_notification:1

#### Emulate M600
# The TFT intercepts the M600 gcode (filament change) and emulates the logic instead of demanding it to Marlin firmware.
#
# NOTE: Enable it, in case Marlin firmware does not properly support M600 on the mainboard.
#
#   Options: [enable: 1, disable: 0]
emulate_m600:1


#--------------------------------------------------------------------
# Marlin Mode Settings (only for TFT24_V1.1 & TFT28/TFT35/TFT43/TFT50/TFT70_V3.0)
#--------------------------------------------------------------------

#### Default Mode
#   Options: [Marlin Mode: 0, Touch Mode: 1]
default_mode:1

#### Serial Always ON
# Keep UART (serial communication) alive in Marlin Mode.
# Allows seamless OctoPrint UART connection to the TFT's UART/serial expansion port no matter which mode the TFT is in.
#   Options: [enable: 1, disable: 0]
serial_always_on:0

#### Default Marlin Mode Background & Font Colors
# Select an option from the provide list or set the color (RGB888 format) hex value directly (start with “0x”),
# such as: Red: 0xFF0000, Green: 0x00FF00, Blue: 0x0000FF.
#   Options: [ WHITE: 0,  BLACK: 1,  RED: 2,  GREEN: 3,      BLUE: 4,       CYAN: 5,  MAGENTA: 6,    YELLOW: 7,
#             ORANGE: 8, PURPLE: 9, LIME: 10, BROWN: 11, DARKBLUE: 12, DARKGREEN: 13,    GRAY: 14, DARKGRAY: 15]

## Marlin Mode background color
marlin_bg_color:1

## Marlin Mode font color
marlin_fn_color:8

#### Marlin Mode Fullscreen Support
# Run Marlin Mode in fullscreen.
#
# NOTE: Disable is recommended for TFT24.
#
#   Options: [enable: 1, disable: 0]
marlin_fullscreen:0

#### Marlin Mode Title Support
# Show title in Marlin Mode.
#   Options: [enable: 1, disable: 0]
marlin_show_title:1

#### Marlin Mode Title
# Text displayed at the top of the TFT in Marlin Mode.
#   Value range: [min: 3, max: 75 characthers]
marlin_title:Marlin Mode

#### Marlin Mode Type
# Select Marlin Mode type.
#   Options: [128x64 Full Graphic LCD: 0, 20x4 Character LCD: 1]
marlin_type:0


#--------------------------------------------------------------------
# RRF Mode Settings
#--------------------------------------------------------------------

####
#   Options: [default Custom Menu: 0, RRF Macros Menu: 1]
rrf_macros_on:0


#--------------------------------------------------------------------
# Printer / Machine Settings
#--------------------------------------------------------------------

#### Hotend Count
#   Value range: [min: 1, max: 6]
hotend_count:1

#### Heated Bed Support
#   Options: [enable: 1, disable: 0]
heated_bed:1

#### Heated Chamber Support
# The TFT will auto-detect if chamber heating is enabled in Marlin firmware.
#   Options: [enable: 1, disable: 0]
heated_chamber:0

#### Extruder Count
#   Value range: [min: 1, max: 6]
ext_count:1

#### Fan Count
#   Value range: [min: 1, max: 6]
fan_count:1

#### Fan Controller Count
#   Value range: [min: 0, max: 2]
fan_ctrl_count:0

#### Bed / Extruder / Chamber Maximum Temperatures
#   Format: [max_temp: T0:<max temp> T1:<max temp> T2:<max temp> T3:<max temp> T4:<max temp> T5:<max temp> BED:<max temp> CHAMBER:<max temp>]
#   Unit: [temperature in °C]
#   Value range: hotend:  [min: 20, max: 1000]
#                bed:     [min: 20, max: 200]
#                chamber: [min: 20, max: 100]
max_temp:T0:275 T1:275 T2:275 T3:275 T4:275 T5:275 BED:150 CHAMBER:60

#### Cold Extrusion Minimum Temperature
# Minimum temperature need to extrude/retract. Any extrude/retract below this temperature will be prevented.
#   Unit: [temperature in °C]
#   Value range: [min: 20, max: 1000]
min_temp:180

#### Fan Maximum PWM Speed
# Set minimum and maximum fan speed allowed by the printer.
#   Format: [fan_max: F0:<max PWM> F1:<max PWM> F2:<max PWM> F3:<max PWM> F4:<max PWM> F5:<max PWM> CtL:<max PWM> CtI:<max PWM>]
#   Unit: [PWM]
#   Value range: [min: 25, max: 255]
fan_max:F0:255 F1:255 F2:255 F3:255 F4:255 F5:255 CtL:255 CtI:255

#### Machine Size / Build Area
# The TFT will auto-detect the machine size (min and max) in Marlin firmware (requires enabling `M115_GEOMETRY_REPORT`
# in Configuration_adv.h in Marlin firmware).
#   Format: [size_min: X<minimum distance> Y<minimum distance> Z<minimum distance>]
#           [size_max: X<maximum distance> Y<maximum distance> Z<maximum distance>]
#   Unit: [distance in mm]
#   Value range: [min: -2000, max: 2000]
size_min:X0 Y0 Z0
size_max:X235 Y235 Z250

#### Default X & Y Move Speeds/feedrates
# Move speeds used in move menu to move X and Y axes.
#   Format: [move_speed: S<feedrate> N<feedrate> F<feedrate>]
#   Unit: [feedrate in mm/min]
#   Value range: [min: 10, max: 12000]
xy_speed:S1000 N3000 F5000

#### Default Z Speeds/feedrates
# Move speeds used in move menu to move Z axis.
#   Format: [move_speed: S<feedrate> N<feedrate> F<feedrate>]
#   Unit: [feedrate in mm/min]
#   Value range: [min: 10, max: 12000]
z_speed:S500 N1000 F2000

#### Default Extruder Speeds/feedrates
# Speed settings used to extrude/retract.
#   Format: [ext_speed: S<feedrate> N<feedrate> F<feedrate>]
#   Unit: [feedrate in mm/min]
#   Value range: [min: 10, max: 12000]
ext_speed:S60 N600 F1200

#### Auto Save Load Leveling Data
# The TFT will auto-detect if Auto Bed Level is available.
# Enable this will send "M500" after "G29" to store leveling value and send "M420 S1"
# to enable leveling state after startup.
#   Options: [enable: 1, disable: 0]
auto_load_leveling:1

#### TouchMI Settings (on ABL menu)
# Enable this option for settings TouchMI sensor on ABL Menu (Init, Z Offset, Save, Test).
#   Options: [enable: 1, disable: 0]
touchmi_sensor:0

#### Onboard / Printer SD Card Support
# On Marlin firmware, the TFT will auto-detect Onboard SD Card.
# Auto-detect is not available for other firmwares like Smoothieware.
#   Options: [enable: 1, disable: 0, auto-detect: 2]
onboard_sd_support:2

#### M27 Printing Status Refresh Time
# M27 printing status refresh time (this will be used if SD_AUTOREPORT is not detected by the TFT).
#   Unit: [time in seconds]
#   Value range: [min: 1, max: 100]
M27_refresh_time:3

#### M27 Always Active
# Keep polling M27 even if not printing.
#   Options: [enable: 1, disable: 0]
M27_always_active:1

#### Long File Names Support
# On Marlin firmware, the TFT will auto-detect Long File Name support.
# Auto-detect is not available for other firmwares like Smoothieware.
#   Options: [enable: 1, disable: 0, auto-detect: 2]
long_filename_support:2

#### Fan Speed As Percentage
# Show fan speed as percentage. If disabled fan speeed will be displayed as PWM values.
#   Options: [enable: 1, disable: 0]
fan_speed_percent:1

#### Pause Settings
# These settings are used when a print is paused.

## Pause Retract Length
#   Format: [pause_retract: R<retract length> P<resume purge length>]
#   Unit: [length in mm]
#   Value range: [min: 0, max: 20]
pause_retract:R15 P16

## Pause XY Position
# NOTE: It MUST BE a value >= 0 for a Cartesian printer.
#       It MUST BE a value <= 0 for a Delta printer.
#
#   Format: [pause_pos: X<position> Y<position>]
#   Unit: [position in mm]
#   Value range: [min: -2000, max: 2000]
pause_pos:X10 Y10

## Pause Z Raise
# Raise Z axis this much relative to the current layer height.
#   Unit: [distance in mm]
#   Value range: [min: 0, max: 2000]
pause_z_raise:10

## Pause Feed Rate
# Feedrate to use when moving an axis when printing is paused.
#   Format: [pause_feedrate: XY<feedrate> Z<feedrate> E<feedrate>]
#   Unit: [feedrate in mm/min]
#   Value range: [min: 10, max: 12000]
pause_feedrate:XY6000 Z6000 E600

#### Leveling Settings
# These settings are used for leveling.

## Leveling Edge Distance (Manual Leveling)
# Inset distance from bed edges. This distance is added to minimum X & Y bed coordinates and
# subtracted from maximum X & Y bed coordinates to calculate manual leveling points.
#   Unit: [distance in mm]
#   Value range: [min: 0, max: 2000]
level_edge_distance:20

## Z Position (Manual Leveling)
# Lower z axis to this position after reaching a leveling point.
#   Unit: [position in mm]
#   Value range: [min: 0, max: 2000]
level_z_pos:0.2

## Leveling Z Raise (Manual and Mesh Leveling)
# Raise Z this much before moving to another point during leveling/probing procedures.
#   Unit: [distance in mm]
#   Value range: [min: 0, max: 2000]
level_z_raise:10

## Leveling Feed Rate (Manual and Mesh Leveling)
# Feedrate to use when moving an axis during leveling/probing procedures.
#   Format: [level_feedrate: XY<feedrate> Z<feedrate>]
#   Unit: [feedrate in mm/min]
#   Value range: [min: 10, max: 12000]
level_feedrate:XY6000 Z6000

#### XY Offset Probing Support (Probe Offset)
# Used by the Probe Offset menu for the Z offset tuning process.
# It allows to move the nozzle to the defined (on Marlin firmware) XY probing point set for homing.
# The nozzle is moved applying the XY probe offset configured on Marlin firmware.
#
# NOTE: Disable it in case the XY probing point set for homing is not reacheable by the nozzle
#       (e.g. due to HW limitations/constraints or printer specific configuration).
#
#   Options: [enable: 1, disable: 0]
xy_offset_probing:1

#### Z Raise Probing Support (Probe Offset, Mesh Editor)
# Used by the Probe Offset / Mesh Editor menu for the Z offset / Z height tuning process.
# Z height to raise / drop after homing (G28) before starting to probe a point.
#
# NOTE: It MUST BE a value >= 0 (e.g. 20) for a Cartesian printer to avoid crashing into the bed.
#       It MUST BE a value <= 0 (e.g. -50) for a Delta printer to avoid crashing into the top of the tower.
#
#   Unit: [distance in mm]
#   Value range: [min: -2000, max: 2000]
z_raise_probing:20

#### Z Steppers Auto-Alignment
# It allows to align multiple Z stepper motors using a bed probe by probing one position per stepper.
# Enable this setting to show icon on ABL menu which allows to run G34 command (it requires
# Z_STEPPER_AUTO_ALIGN enabled in Configuration_adv.h in Marlin firmware).
#
# NOTE: Only for Marlin printers with one stepper driver per Z stepper motor and no Z timing belt. Also requires a BLTouch.
#
#   Options: [enable: 1, disable: 0]
z_steppers_alignment:0

#### Preheat Temperatures
#   Format: [preheat_nameX:<name>]
#           [preheat_tempX:T<hotend temp> B<bed temp>]
#   Unit: [temperature in °C]
#   Value range: name:        [min: 3, max: 75 characters]
#                hotend temp: [min: 20, max: 1000]
#                bed temp:    [min: 20, max: 200]
preheat_name1:PLA
preheat_temp1:T200 B60

preheat_name2:PETG
preheat_temp2:T240 B70

preheat_name3:ABS
preheat_temp3:T230 B90

preheat_name4:WOOD
preheat_temp4:T170 B50

preheat_name5:TPU
preheat_temp5:T220 B50

preheat_name6:NYLON
preheat_temp6:T250 B90


#--------------------------------------------------------------------
# Power Supply Settings (if connected to TFT controller)
#--------------------------------------------------------------------

#### Default Power Supply Mode
# Enable auto shutdown when hot-end temperature becomes below target value.
#   Options: [enable: 1, disable: 0, auto-detect: 2]
ps_on:0

#### Power Supply Active HIGH
# Enable the logic of the mode on HIGH signal.
#   Options: [enable: 1, disable: 0]
ps_on_active_high:1

#### Power Supply Auto Shutdown Temperature
# Maximum hot-end temperature of automatic shut down after printing (only if auto power is enabled).
# Wait for the hot-end temperature to be lower than this value, then turn off the power automatically.
#   Unit: [temperature in °C]
#   Value range: [min: 20, max: 1000]
auto_shutdown_temp:50


#--------------------------------------------------------------------
# Filament Runout Settings (if connected to TFT controller)
#--------------------------------------------------------------------

#### Default Filament Runout Sensor
# Enable filament runout sensor.
#   Options: [enable: 1, disable: 0, smart: 2]
fil_runout:0

#### Inverted Filament Runout Logic
# Invert the logic of the sensor.
#   Options: [true: 1, false: 0]
fil_runout_inverting:1

#### Filament Noise Threshold
# Pause print when filament runout is detected for this time period.
#   Unit: [time in miliseconds]
#   Value range: [min: 10, max: 1800]
fil_noise_threshold:100

#### Smart Filament Runout Detection
# For use with an encoder disc that toggles runout pin as filament moves.
#   Unit: [distance in mm]
#   Value range: [min: 1, max: 50]
fil_runout_distance:7


#--------------------------------------------------------------------
# Power Loss Recovery & BTT UPS Settings (if connected to TFT controller)
#--------------------------------------------------------------------

#### Default Power Loss Recovery Mode
# Enable power loss recovery.
# Disable to reduce the loss of SD card or U disk.
#   Options: [enable: 1, disable: 0]
pl_recovery_en:1

#### Power Loss Recovery Homing
# Home before power loss recovery.
#   Options: [enable: 1, disable: 0]
pl_recovery_home:0

#### Power Loss Z Raise
# Raise Z axis on resume (on power loss with UPS).
#   Unit: [distance in mm]
#   Value range: [min: 0, max: 2000]
pl_z_raise:10

#### BTT UPS Support
# Enable BTT UPS.
#   Options: [enable: 1, disable: 0]
btt_mini_ups:0


#--------------------------------------------------------------------
# Other Device-Specific Settings
#--------------------------------------------------------------------

#### Sounds / Buzzer
# Set sound ON or OFF.
#
# NOTE: Error messages from printer will always play the error sound.
#
# Parameters:
#   touch_sound:  Enable/disable this to control touch feedback sound.
#   toast_sound:  Enable/disable this to control all toast notification sounds.
#   alert_sound:  Enable/disable this to control all popup and alert sounds
#                 like print finish alert, dialog sound etc.
#   heater_sound: Enable/disable this to control acoustic feedback when temperature
#                 has reached the desired value on heaters (nozzle, bed, chamber).
#
#   Options: [enable: 1, disable: 0]
touch_sound:1
toast_sound:1
alert_sound:1
heater_sound:1

#### Knob LED Color (only for TFT28 V3.0, TFT35 E3.0, TFT43 V3.0, TFT50 V3.0 & TFT70 V3.0)
#   Options: [OFF: 0, WHITE: 1, RED: 2, ORANGE: 3, YELLOW: 4, GREEN: 5, BLUE: 6, INDIGO: 7, VIOLET: 8]
knob_led_color:0

#### Knob Idle State (only for TFT28 V3.0, TFT35 E3.0, TFT43 V3.0, TFT50 V3.0 & TFT70 V3.0)
#   Options: [true: 1, false: 0]
knob_led_idle:1

#### Default LCD Brightness Levels (only for TFT28 V3.0, TFT35 E3.0, TFT43 V3.0, TFT50 V3.0 & TFT70 V3.0)
# Default brightness values for LCD.

## Default display brightness
#   Options: [(off) 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 (full)]
lcd_brightness:11

## Display brightness when device is idle
#   Options: [(off) 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 (full)]
lcd_idle_brightness:5

#### Default LCD Idle Time (only for TFT28 V3.0, TFT35 E3.0, TFT43 V3.0, TFT50 V3.0 & TFT70 V3.0)
#   Options: [Off: 0, 5sec: 1, 10sec: 2, 30sec: 3, 1min: 4, 2min: 5, 5min: 6, 10min: 7]
lcd_idle_delay:4


#--------------------------------------------------------------------
# Custom Gcode Commands
#--------------------------------------------------------------------

#### Custom Gcode Commands
# Up to 15 custom gcode commands that will be available in the Custom menu.
#
# Usage:
#   To enable a custom command, remove '#' at the begining of custom commands label & gcode.
#   To disable a custom command, add '#' at the begining of custom commands label & gcode.
#
# NOTE: If the values are left blank then default name and gcode will be used.
#
#   Value range: label: [min: 3, max: 75 characters]
#                gcode: [min: 3, max: 75 characters]
custom_label_1:Disable steppers
custom_gcode_1:M84\n
custom_label_2:Init sd card
custom_gcode_2:M21\n
custom_label_3:Release sd card
custom_gcode_3:M22\n
custom_label_4:Restore leveling
custom_gcode_4:M420 S1\n
custom_label_5:Save to EEPROM
custom_gcode_5:M500\n
custom_label_6:Restore from EEPROM
custom_gcode_6:M501\n
custom_label_7:EEPROM defaults
custom_gcode_7:M502\n
#custom_label_8:custom8
#custom_gcode_8:M105\n
#custom_label_9:custom9
#custom_gcode_9:M105\n
#custom_label_10:custom10
#custom_gcode_10:M105\n
#custom_label_11:custom11
#custom_gcode_11:M105\n
#custom_label_12:custom12
#custom_gcode_12:M105\n
#custom_label_13:custom13
#custom_gcode_13:M105\n
#custom_label_14:custom14
#custom_gcode_14:M105\n
#custom_label_15:custom15
#custom_gcode_15:M105\n


#--------------------------------------------------------------------
# Start, End & Cancel Gcode Commands
#--------------------------------------------------------------------

#### Default Start Gcode Status
#   Options: [enable: 1, disable: 0]
start_gcode_enabled:0

#### Default End Gcode Status
#   Options: [enable: 1, disable: 0]
end_gcode_enabled:0

#### Default Cancel Gcode Status
#   Options: [enable: 1, disable: 0]
cancel_gcode_enabled:0

#### Start Gcode
# This gcode will runs before starting a print if `start_gcode_enabled` is enabled.
#   Value range: [min: 3, max: 75 characters]
start_gcode:G28 XY R20\n

#### End Gcode
# This gcode will runs after a print is completed if `end_gcode_enabled` is enabled.
#   Value range: [min: 3, max: 75 characters]
end_gcode:M104 S0\nM140 S0\nM107\nM18\n

#### Cancel Gcode
# This gcode will runs when a print is canceled if `cancel_gcode_enabled` is enabled.
#   Value range: [min: 3, max: 75 characters]
cancel_gcode:M104 S0\nM140 S0\nG28 XY R10\nM107\nM18\n

**Comment by digant73** [comment]
@EnzoCastellaneta if all the features reported at the beginning of the config.ini file are enabled in Marlin it could be a problem in Marlin. I add a problem with the pause when I enabled UBL in Marlin. Basically the pause was not working as expected (the nozzle was moved on the park area but then it was moved on top of the print, printing just for few seconds before pausing). Also the M600 was not working (when the dialog asking to "purge more " or "continue" was displayed the print was alsways automatically resumed without waiting for the choice from the user).
If you are using UBL in Marlin try to switch to Bilinear BL. Less resources will be used. I suspect the problems using UBL are due to the resource limit reached in Marlin (on my printer it was 93% and 90% for mem and flash)

**Comment by oldman4U** [comment]
Any news? Would be nice if you could answer digant or me.

Otherwise, please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by EnzoCastellaneta** [comment]
tried just yesterday but not able to compile something went wrong with classes.Could you compile one with the fix suggested? E3Pro skr mini 2.0 bltouch used for z axis endpoint + tft 35 e3 last fw uploaded.let me know.EInviato dal mio Galaxy
-------- Messaggio originale --------Da: oldman4U ***@***.***> Data: 10/04/21  08:35  (GMT+01:00) A: bigtreetech/BIGTREETECH-TouchScreenFirmware ***@***.***> Cc: EnzoCastellaneta ***@***.***>, Mention ***@***.***> Oggetto: Re: [bigtreetech/BIGTREETECH-TouchScreenFirmware] [BUG] tft 35 for ender fw blocking issue on pause/restart (#1766) 
Any news? Would be nice if you could answer digant or me.
Otherwise, please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please. This is neither a Marlin nor a VSC support page and also not a user group. This repository is about the firmware of TFT displays from BTT only. Your problem is not related to the TFT firmware, so please help the community and close this ticket. Thank you

**Comment by oldman4U** [comment]
@Msq001 Please see my last comment and close this ticket. Thank you
