### ISSUE TITLE
TFT24-v1.1

### ISSUE THREAD

**Issue by Ramzedo** [bigtreetech/BIGTREETECH-TouchScreenFirmware#177]
Hi,
after i upload BIGTREE_TFT24_V1.1.24.2.bin and folder TFT24 on my sd cart to update firmer on my new display he dont power up anymore. I just see bigtreetech logo. I tray re-upload 
several times and its same. Any one can help ???
![slika1](https://user-images.githubusercontent.com/58051631/69377421-8c8a3f00-0cac-11ea-9466-15239df0603c.jpg)

**Comment by Pixel-Soup** [comment]
I had the same issue as well.  The "fix" is to build the code yourself.  Be sure to edit platformio.ini to build for the tft24.  For those who don't know how, here's the binary I built. 

[BIGTREE_TFT24_V1.1.24.2.bin.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/3881386/BIGTREE_TFT24_V1.1.24.2.bin.zip)
