### ISSUE TITLE
Translation Swedish[FR] (feature request title)

### ISSUE THREAD

**Issue by ShRTee** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1771]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ShRTee** [comment]
I have translated the Swedish language file and wonder if there is any requests for this ?
[language_se.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/6210472/language_se.zip)

**Comment by oldman4U** [comment]
Make a PR in case everything is translated and you are willing to maintain it.

**Comment by radek8** [comment]
@ShRTee will you be willing to keep your own language up to date if you don't even respond to the ticket you created?
Probably not.

**Comment by oldman4U** [comment]
@Msq001

Please close this ticket. Thank you
