### ISSUE TITLE
TFT 34V2 manual move screen units

### ISSUE THREAD

**Issue by RocksaltX** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1772]
### Description

On the manual move screen, 10mm is selected for distance travel. Move axis 10mm. Change screens and come back to manual move screen. Increment is changed on screen, but 10mm is still selected. Go to press move button .1mm and it moves 10mm.

### Steps to reproduce

See above

**Expected behavior**
Increment to  update when changing screens

**Actual behavior**
previous increment loaded but icon not changed.

### Hardware Variant
TFT35V2
### TFT Firmware Version & Main Board Firmware details
<BIQU_TFT35_APP1_V2.0.26.x>

### Additional Information
* Include a ZIP file containing your `Configuration.h` or use [Pastebin](https://pastebin.com/) and paste a link in this issue.
* Provide pictures or links to videos that clearly demonstrate the issue.

**Comment by oldman4U** [comment]
Could you please attach a movie showing the issue. 

Thank you

**Comment by kisslorand** [comment]
Fixed: PR #1774

**Comment by RocksaltX** [comment]
I applied the changes in PR #1774 and is working. Thank you for the link.

**Comment by oldman4U** [comment]
Kisslorand faster than light 👍🏻

@RocksaltX
Please help the community and close the ticket once you do not need it anymore. Thank you
