### ISSUE TITLE
[Feature request] Add portrait orientation TFT24

### ISSUE THREAD

**Issue by technoo10201** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1779]
Hello guys !

I would like to know if you can implement a parameter to let the screen orientation in portrait ?
This is the design i will use with my printer and i would like to use the screen as it is presented on this design :

https://www.thingiverse.com/thing:4809101

Regards
Technoo'

**Comment by oldman4U** [comment]
#524 #602 #1160 #1381

Hope it is ok for you to be the fifth asking for the same feature.

**Comment by technoo10201** [comment]
> #524 #602 #1160 #1381
> 
> Hope it is ok for you to be the fifth asking for the same feature.

No i should guess it is a well asked request ;)
I close the ticket then..

Thanks for the fast reply.

**Comment by oldman4U** [comment]
Yes it is and I hope there will be something like this available soon.

Thank you and happy printing
