### ISSUE TITLE
[Q] TFT50 on Ender 3v2?

### ISSUE THREAD

**Issue by tome9111991** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1780]
Hello does anyone know whether the ender 3 v2 with 4.2.2 board is compatible with a BTT tft50 display?

**Comment by radek8** [comment]
According to discussions on the Internet, boards 4.2.2 are supplied in two versions.
With A4988 or TMC2208 drivers.
If you have A4988 Drivers, be sure to buy a new board.

**Comment by oldman4U** [comment]
Thank you radek8 for your help.

This ticket is a bit off topic of this repository so  please help the community and close the ticket once you do not need it anymore. Thank you
