### ISSUE TITLE
[BUG] MKS TFT28 doesn't boot into firmware after bootloader, displays glitches

### ISSUE THREAD

**Issue by drewler** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1792]
### Description

After flashing the firmware to a MKS TFT28 V3.0 board, it displays some glitches but doesn't boot, as shown in the following video.

https://www.youtube.com/watch?v=XtiFZHMdNLs

I'd like to help and prepare a PR to fix it. It looks like it's not starting the main program after the booloader. Only the main binary is renamed to `.CUR` after the update, so seems like it's not reaching the point where fonts, icons or configuration are applied.

Any hint about what could be wrong?

### Steps to reproduce

1. Add `MKSTFT28.bin`, `config.ini` and `TFT28` folder (renamed to `MKS`) to the root of the SD card
2. Turn on. Update happens
3. Display gets stuck as shown on video

After that, I used an STLink V2 to erase the device and flashed `Bootloader MKS_TFT28.bin` to `0x00000000`. After that, I've flashed `MKSTFT28.bin` using the SD card, but it still doesn't work. Flashing the stock firmware through the SD card still works.

**Expected behavior**
IT should boot into BIGTREETECHS's TFT firmware.

**Actual behavior**

![image](https://user-images.githubusercontent.com/1395606/113492722-de1a1f00-94d9-11eb-998a-259a26d59283.png)

Also, only the main update is executed (fonts or config are not applied)

![image](https://user-images.githubusercontent.com/1395606/113492881-4289ae00-94db-11eb-896c-80e382203a0c.png)

### Hardware Variant
MKS TFT28 V3.0 (3.0.6 official firmware)
### TFT Firmware Version & Main Board Firmware details
3.0.6 - official firmware
master branch - BIGTREETECH's firmware

### Additional Information
* https://www.youtube.com/watch?v=XtiFZHMdNLs

**Comment by digant73** [comment]
Try with a different sd card not bigger than 32GB. That fw perfectly works on my MKS TFT

**Comment by digant73** [comment]
The fw is compatible with MKS 1.4

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by drewler** [comment]
@digant73 @oldman4U any hints about where in the code I could look? I wasn't looking for a solution but trying to figure out what is not working so I could help.

Like: does this glitch look like it's running some data as code? Could it be some wrong offset? Or maybe it's beacuse the LCD driver is the wrong one?

Please, let me know if you have any hints. If you think it's not worth it, then I'll quickly close the issue.

**Comment by digant73** [comment]
the main settings for the currently supported MKS TFT v1.4 are in file pin_MKS_TFT32_V1_4.h. The used LCD driver is HX8558. I don't know what LCD driver is used by MKS TFT v3.0. Probably platformio.ini and other features in the fw need to be changed in order to support that TFT

**Comment by drewler** [comment]
Awesome! Thanks @digant73

![image](https://user-images.githubusercontent.com/1395606/113568079-1de32280-9610-11eb-9fe5-e6275d4a46f3.png)

I just had to compile `MKS_TFT32_V1_3` and it works now! In my case, I also had to change a line in [TFT/src/User/Variants/pin_MKS_TFT32_V1_3.h](https://github.com/Uz45/BIGTREETECH-TouchScreenFirmware/blob/5634f771210a7593b89dba4601c6933c1f2c7c0c/TFT/src/User/Variants/pin_MKS_TFT32_V1_3.h#L24) to prevent mirroring, as the comment suggested.

Thanks again. Closing this issue now.

**Comment by oldman4U** [comment]
Maybe you want to contribute with a PR?
