### ISSUE TITLE
[BUG] No model preview on print screen with lastest build

### ISSUE THREAD

**Issue by GregSKR** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1793]
I'm using model preview in my STL files, and printing from the SD card of my TFT.

With lastest build v0.0.27, model preview are ok when exploring the SD card, but not in the print screen (was working before).
The babystep button always as the babystep icon, no more model preview...

It's just me or anyone else?

**Comment by radek8** [comment]
Yes, this is a mistake.
in point
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/commit/9e5a9a5f32b58ec74d92487429a314ba28dff3c2#diff-c625e283a40da9ab01e83c66cab47ca45199095a1b51d627e21
the preview is OK.
After merging PR https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/1785
print previews are no longer displayed.
@digant73 can you check your PR?

Thank you

**Comment by bigtreetech** [comment]
Hello. #1795 should fix this problem, Please check, Thank you very much for your feedback and test.

**Comment by GregSKR** [comment]
So fast! 👍🏻 
Yes, just checked, problem fixed in #1795, thanks!
