### ISSUE TITLE
Please add Z axis !

### ISSUE THREAD

**Issue by Aleks-MO** [bigtreetech/BIGTREETECH-TouchScreenFirmware#180]
Please add Z axis. Printing on the screen lacks Z axis readings. It is very helpful sometimes when you know which layer is printed.
![WP_20191122_21_48_03_Pro22](https://user-images.githubusercontent.com/22274265/69491899-2ec04780-0ea4-11ea-95c9-804325aaa0b6.jpg)

**Comment by bigtreetech** [comment]
ok, This will be added, Thank you for your advice.

**Comment by kkaleta** [comment]
And (maybe) we don't need this "T" before time? 
![20191202_193359](https://user-images.githubusercontent.com/4312668/69985881-68482100-153c-11ea-872c-579c6225d2d0.jpg)

**Comment by Aleks-MO** [comment]
@kkaleta  Class!     Many wanted to know the print layer. 
I do not understand what the letter "T" is?

**Comment by kkaleta** [comment]
Actually this one look even better. With GRAY font and time and Z on top.
![20191202_211641](https://user-images.githubusercontent.com/4312668/69994008-3f7c5780-154d-11ea-96bd-48b4183082c6.jpg)

**Comment by Aleks-MO** [comment]
I don’t know, I need to work a week .... the first option is all the data in one revenge and immediately perceived as a single whole ..) In general, the habit of the MKS screen remained.

**Comment by Aleks-MO** [comment]
Can you put the firmware + icons, where is the Lyme firmware? The more people try, the more they think the best.

**Comment by Aleks-MO** [comment]
@kkaleta Oh, oh, oh, oh, I just saw you - Relay-controlled-by-phone-call-Advanced! How does it work? Doesn't hang? I got a "monster" ..)))))    http://avrproject.ru/forum/13-123-1
