### ISSUE TITLE
[Q] (Your Question?)

### ISSUE THREAD

**Issue by GrahamJB** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1803]
Is there a reccomended marlin version for the x.x.27 release?

**Comment by kisslorand** [comment]
Yes, latest bugfix 2.0.x

**Comment by oldman4U** [comment]
Min. 2.0.5.4
Most of us tested with 2.0.7.2
STM32 boards - latest Marlin bugfix (Un)Load crash fixed.
