### ISSUE TITLE
Levelcorner.bmp missing

### ISSUE THREAD

**Issue by Cheo7811** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1812]
### Description

levelcorner.bmp is missing for all displays except TTF35 in The Round Miracle theme

**Comment by oldman4U** [comment]
Hi Cheo7811.

Please use the Unified Menu Theme at the moment.

@Acenotass
@AntoszHUN
@bepstein111

Could you please check your Themes. Guess there is more than one template wrong, because there should be 141 where there are 139 bmp's in your Themes.

Thank you!

**Comment by AntoszHUN** [comment]
> 
> 
> Hi Cheo7811.
> 
> Please use the Unified Menu Theme at the moment.
> 
> @Acenotass
> @AntoszHUN
> @bepstein111
> 
> Could you please check your Themes. Guess there is more than one template wrong, because there should be 141 where there are 139 bmp's in your Themes.
> 
> Thank you!

Thank you for reporting!

I uploaded everything.

By: AntoszHUN

**Comment by oldman4U** [comment]
Hungary - 100 points;-) Thank you

**Comment by oldman4U** [comment]
Please use level_corner.bmp as filename and not level corner.bmp

Thank you

**Comment by radek8** [comment]
Icons are added.

**Comment by oldman4U** [comment]
@bepstein111

Hi Ben. Will you be able to provide the two missing icons this weekend?

Please let us know

Thank you

**Comment by oldman4U** [comment]
Seems bepsetin111 is mot available anymore. So would someone else take over his theme or should we remove it? I am writing the new ReadMe right now, so I can remove it tonight with the PR.

Just let me know in case someone takes it over.

Thank you

**Comment by bepstein111** [comment]
Sorry guys, just been super busy lately. Should be able to get to this tonight hopefully.

**Comment by oldman4U** [comment]
Cool. Thank you!

**Comment by oldman4U** [comment]
Thank you bepstein111;-)
