### ISSUE TITLE
[BUG] RRF macro menu broken

### ISSUE THREAD

**Issue by bttguy** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1814]
### Steps to reproduce

1. Update to one of the fw versions after the stable release
2. Go to the macro menu
3. Try to execute a macro or go back from the macro menu

**Expected behavior**
It was working as expected before the stable, macros worked, so the back button.

**Actual behavior**
Since the stable update, the macro menu for RRF users is broken. It lists the macros, but the back button does not work, only a reset takes back to the status screen. Also the macros dont work

**Comment by oldman4U** [comment]
Can you try to find out which PR finally broke it.

**Comment by bttguy** [comment]
Looks like #1769

**Comment by oldman4U** [comment]
Have you tested the release before and after?

**Comment by bttguy** [comment]
An another user reported in #1791 that it might be it. But I tested it right before and after that commit, but it worked for me. 
I will try to test it further, but there are a lot of commits to check.

**Comment by PaulG4H** [comment]
@bttguy 
in this commit from 23th of March the macros menu still works:
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/commit/318c98d7a4360cef0cf1696b51d95fadcf87a198

and the next build on April 1th it's not working anymore:
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/commit/201cd68e399c8788c23edefd61749d80ce0e6b72

**Comment by oldman4U** [comment]
And when you use 1d601b6091847645ea51e0ccf038b4a4258d83c7 ?

**Comment by oldman4U** [comment]
@guruathwal Seems your PR broke this. Could you please check.

c4439452cf3e5857fac66fe7812787eed4094667

Thank you

**Comment by guruathwal** [comment]
ok I will look into it.

**Comment by guruathwal** [comment]
@bttguy  Can you provide the response from RRF firmware for `M20 S2 P"/macros"`?

**Comment by PaulG4H** [comment]
@guruathwal 


10.4.2021, 09:41:44 | M20 S2 P"/macros"{    "dir": "/macros",    "first": 0,    "files": [        "deployprobe",        "resetprobe",        "retractprobe",        "selftestprobe",        "True Bed Leveling",        "calibrate z offset with bltouch step 01",        "calibrate z offset with bltouch step 02"    ],    "next": 0,    "err": 0}
-- | --

**Comment by bigtreetech** [comment]
Hello, https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/1825 should fix. Please test,  Thank you very much for your time!

**Comment by bigtreetech** [comment]
> @bttguy Can you provide the response from RRF firmware for `M20 S2 P"/macros"`?

Hello, Please review #1825

**Comment by bttguy** [comment]
I will check it in the evening, than close the ticket accordingly :) Thank you the quick fix!

**Comment by bttguy** [comment]
I will check it in the evening, than close the ticket accordingly :) Thank you the quick fix!

**Comment by guruathwal** [comment]
@bttguy @PaulG4H can you check if #1825 works?

**Comment by PaulG4H** [comment]
@guruathwal @Msq001 
Macro menu work again!

Thank's for fixing this!

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by bttguy** [comment]
Thanks for the fix, closing ;)
