### ISSUE TITLE
[BUG] (LevelCorner.bmp is missing in Hybrid Red Menu. Firmware wont update past this missing bmp)

### ISSUE THREAD

**Issue by ShaneZampire** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1817]
### Steps to reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior**

**Actual behavior**

### Additional Information
* Include a ZIP file containing your `Configuration.h` or use [Pastebin](https://pastebin.com/) and paste a link in this issue.
* Provide pictures or links to videos that clearly demonstrate the issue.

**Comment by oldman4U** [comment]
Please. We are aware and there is already another ticket related to the same issue. The buttons are missing for ALL themes not only for the Hybrid Red, except for the Unified Menu Theme. Please use this Theme for now until we fixed the issue and close this ticket.

Thank you

**Comment by radek8** [comment]
Icons are added.

**Comment by radek8** [comment]
Please close the ticket

**Comment by digant73** [comment]
@bigtreetech you could close this ticket. All the icons for the Red theme are present

**Comment by oldman4U** [comment]
Use @Msq001 instead of bigtreetech
