### ISSUE TITLE
Fade height error

### ISSUE THREAD

**Issue by Sh8tan** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1818]
Hi, 

On a tft 35 with ABL on, when i turn fade height at 0 the pop up mentionned fade height off.

From marlin sources when abl is on and and fade height at 0 it means that the mesh compensation are for all the print from bottom to top so fade height are not off when putting 0 in setting.

Expected behaviour :

Putting 0 in fade height and stopping message that say that fade height are off.

I saw that already mentionned on the known bug but information displayed are incorrect, fade height are still active for all the print.

After testing with fade height 0 then printing, mesh compensation are doing the job so delivred information from pop up are flase

**Comment by digant73** [comment]
that information is provided by Marlin and displayed by TFT. So the bug is on Marlin
