### ISSUE TITLE
[Q] (Why the Nozzle and bed temperatures are not updating in touch mode of TFT35 ?)

### ISSUE THREAD

**Issue by marouane86** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1822]
Recently I configured TFT35 with skr 1.4 turbo, everything works fine exept the tempertures of the nozzle and bed are not refreshed to follow the targets in touch mode. Any idea please ?

**Comment by oldman4U** [comment]
Using TFT firmware v27? Before and during print?

**Comment by radek8** [comment]
uncomment
AUTO_REPORT_TEMPERATURES (in Configuration_adv.h)

**Comment by manurafal** [comment]
I have the same problem.
I have uncommented the option AUTO_REPORT_TEMPERATURES (in Configuration_adv.h) but I still have the same problem.

I have SKR E3 TURBO and TFT35 v3 E3

**Comment by marouane86** [comment]
Yes I use V27, and I uncomment AUTO_REPORT_TEMPERATURES (in Configuration_adv.h) but still the same issue

**Comment by oldman4U** [comment]
Before or during print?

Printing from?

**Comment by marouane86** [comment]
Thank you for your replies,
I fixed the issue by comment AUTO_REPORT_TEMPERATURES (in Configuration_adv.h)

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you and happy printing
