### ISSUE TITLE
[Q] What if I have no heated bed, where is the code to take out the icons and options of the heated bed

### ISSUE THREAD

**Issue by nobaj** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1831]
I have no heated bed on my custom printer, is there a way to disappear the heated bed icons/menus on the lcd?

**Comment by radek8** [comment]
Icons and functions on the heated bed in the current FW can not be hidden.
They just won't have any function for you.
PS: does anyone else use a printer without a heated bed today? :-)

**Comment by radek8** [comment]
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/1053

**Comment by oldman4U** [comment]
On my printer I never used the part cooling fan and there is no LED. But I have a heated nozzle and bed.

😁

**Comment by oldman4U** [comment]
To answer the question the user finally asked.

This software is open source so you can download it from this page.

Question. Are you a developer who could improve the code the way that it is easier to take away unneeded elements, even it looks like switzerland cheese at the end?

Or even better - to make a user interface designer which allows each user to build his own interface very easy?

Please let me know

Thank you

**Comment by oldman4U** [comment]
Hello nobaj.

Would be great if you could answer your own ticket or close it in case you do not need it anymore.

Thank you

**Comment by nobaj** [comment]
Hi, thanks, I will make some options on the configuration to deactivate the icon and put another like "no heatbed" so the ui does not get all messed up, when I finish i can make a pull request if you guys want to incorporate that feature
