### ISSUE TITLE
[Q] What should be shown on the Notification screen?

### ISSUE THREAD

**Issue by hapklaar** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1833]
I use M117 notifications from the Octoprint-DetailedProgress plugin to push progress info to my TFT35 screen. This works fine in recent releases. I was also expecting to find a log of these messages in the 'Notifications' screen after clicking this area on the status screen. However this screen is always empty for me.

Is this a configurable option I can enable somewhere, or a bug or maybe by design?

**Comment by bigtreetech** [comment]
The `Notification` menu only disply `"Error:"`  message and `"echo:"` (only when `ACK notification style` is set to `POPUP` in `Feature` menu) message from Marlin

**Comment by hapklaar** [comment]
Can I change this somewhere to also include the M117 (and possibly other) messages?

**Comment by oldman4U** [comment]
Maybe you missed this and many other tickets the time you searched for M117 before you started this ticket: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/1050

**Comment by hapklaar** [comment]
@oldman4U This is not relevant. M117 messages already show correctly in the notification area, this is not my complaint. They are just not shown in the separate notification menu.

**Comment by oldman4U** [comment]
My fault. Than btt gave you the answer already.

**Comment by hapklaar** [comment]
My question remains if I can change this in code to allow M117 notifications to also be kept there. This filtering can hopefully be configured somewhere.

**Comment by oldman4U** [comment]
It is open source so you can change it the way you want it. But there is no on/off option for this.

Are you a software developer?

**Comment by hapklaar** [comment]
No I'm not, that's why I ask the devs of this software. Your additions don't really help here....

**Comment by bigtreetech** [comment]
@hapklaar Hello, Can you send me a picture of what M117 is currently displayed on the screen. So that I can quickly find the location to be modified.

**Comment by hapklaar** [comment]
Hello @bigtreetech,

For example I type the following in OctoPrint terminal: "M117 This is an M117 message"
Terminal output is:
![image](https://user-images.githubusercontent.com/7703320/114859524-2b0bc880-9deb-11eb-913d-fe66751ed99c.png)

I see this on the TFT35:
![image](https://user-images.githubusercontent.com/7703320/114859809-863dbb00-9deb-11eb-916b-2a1886d4848c.png)

Then I press the notification area to open the notification screen, where I would like to keep a (short) log of recent M117 notifications:
![image](https://user-images.githubusercontent.com/7703320/114859966-b5ecc300-9deb-11eb-9e4b-f526abdb7fb6.png)

**Comment by bigtreetech** [comment]
@hapklaar Hello. You can temporarily change line 232 in `parseACK.c` from
 `addToast(DIALOG_TYPE_INFO, dmaL2Cache + index);` 
to
 `addNotification(DIALOG_TYPE_INFO, (char*)echomagic, (char*)dmaL2Cache + index, true);`
 so that you can achieve the effect you want.
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/blob/6968e53ad3e99eda523dcac57e86bb0d301395e1/TFT/src/User/API/parseACK.c#L232

![image](https://user-images.githubusercontent.com/38851044/114961973-7631e400-9e9c-11eb-9436-ac0350350a0a.png)

I will sort out the code in this part, because the general response protocol and host action protocol are divided into two parts, and I will try to integrate them

**Comment by hapklaar** [comment]
Thanks. I made the change and recompiled. Now M117 notifications do appear in the notifications screen, but only when I'm on that screen when the M117 notification comes in.

When I'm on the status screen, the message is not added to the notification screen. Can we make it so M117 messages are always added to the notification screen, regardless of what screen is active at that moment?

**Comment by hapklaar** [comment]
I think I found a way to do it: I added this line just below line 225, before the status screen check: 

`addNotification(DIALOG_TYPE_INFO, (char*)echomagic, (char*)dmaL2Cache + ack_index, false);`

This seems to add all messages starting with ':notification' to both the status area and the notification screen, and doesn't give a popup for each message.

As I'm not a dev or programmer, I hope this is the right way to do it. ;)

**Comment by radek8** [comment]
> I think I found a way to do it: I added this line just below line 225, before the status screen check:
> 
> `addNotification(DIALOG_TYPE_INFO, (char*)echomagic, (char*)dmaL2Cache + ack_index, false);`
> 


Great. it works for me.

**Comment by radek8** [comment]
If PR #1864  is merged,
you can enable the display of M117 notifications on the notification screen in the cofig.ini file
notification_m117: 1
