### ISSUE TITLE
Bed temperature not reading correct.

### ISSUE THREAD

**Issue by carl1961** [bigtreetech/BIGTREETECH-TouchScreenFirmware#186]
just installed BIGTREE_TFT35_V3.0.25.bin, display TFT 3.5 3.0 (first version that came out). not a problem with printing, just a Let You know.  bounces from 60960 to -099
![IMG_20191125_065322](https://user-images.githubusercontent.com/3056821/69542835-d6e01a00-0f51-11ea-8c49-d108a7ae4cfb.jpg)
![IMG_20191125_065342](https://user-images.githubusercontent.com/3056821/69542836-d6e01a00-0f51-11ea-9810-d61659bb9095.jpg)

**Comment by carl1961** [comment]
Might be mad at what I'm printing LOL

**Comment by guruathwal** [comment]
Is it displayed corectly on the printer lcd?

**Comment by carl1961** [comment]
Glad you ask, Yes it shows correctly, and when your in print screen it shows correctly, but soon as it homes and starts printing  it shows the random numbers like in first picture. the homing is issued from the print gcode file, it may be something in my startup. I will check
![IMG_20191125_233602](https://user-images.githubusercontent.com/3056821/69602529-844c3f80-0fdd-11ea-9e12-a53cc71db5ec.jpg)
![Uploading IMG_20191125_233715.jpg…]()

**Comment by carl1961** [comment]
My startup g code, shows nothing temp related
G28 ; home all axes
G92 E0.0
G1 Z5;
G1 X10 Y10 Z0 F6000;
G1 X60.0 E9.0  F1000.0 ; intro line
G1 X100.0 E12.5  F1000.0 ; intro line
G92 E0.0

**Comment by guruathwal** [comment]
Did you set the bed temperature at 60 both times?

**Comment by carl1961** [comment]
No the first was preheat, the 60 came from the Gcode

**Comment by carl1961** [comment]
Simplify3D

G90
M82
M106 S0
M140 S60
M190 S60
M104 S200 T0
M109 S200 T0
G28 ; home all axes
G92 E0.0
G1 Z5;
G1 X10 Y10 Z0 F6000;
G1 X60.0 E9.0  F1000.0 ; intro line
G1 X100.0 E12.5  F1000.0 ; intro line
G92 E0.0
; process Process1
; layer 1, Z = 0.294
T0
G92 E0.0000
G1 E-4.0000 F1800
G4 P1

**Comment by guruathwal** [comment]
ok.. it looks like the `/` in bed temperature text is replaced by `9`.

**Comment by carl1961** [comment]
tried with Cura, and same thing. If no body else has this issue it most likely on my end.

**Comment by guruathwal** [comment]
I checked and found that the `/` between the current temp and target temp is drawn only once when the printing page loaded.
its been overdrawn by other value.
Try opening the percentage menu or heat menu when this happens then go back and check if it fixes.

**Comment by carl1961** [comment]
Yes guruathwal that fixed it for about 20 or 30 seconds and you have to do it again then again it goes with the odd numbers

**Comment by guruathwal** [comment]
ok.. will fix it in next PR.

**Comment by carl1961** [comment]
No hurry, printing works fine.

**Comment by carl1961** [comment]
Oh while I am thinking about it, what is that yellow dot at top right that pulses on and off like every 10 or so seconds.

**Comment by guruathwal** [comment]
thats busy icon, when the printer sends busy signal.

**Comment by bigtreetech** [comment]
The bug of temperature display is fixed here.https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/commit/6ae27e59a5e489cd79b78577d9bae566a060ca3e 
The precompiled file will be updated later
