### ISSUE TITLE
TFT and RasbPI shows gcode file names short (8.3) from SD

### ISSUE THREAD

**Issue by macasero** [bigtreetech/BIGTREETECH-TouchScreenFirmware#187]
I have a setup with FullGraphics, TFT35 and raspbPI octoprint, and SD files are shown in short format and truncated.

Files on Fullgraphics are shown on long format mode.

If I command M20 from pronterface, I get a short name format list. 
Then copy one of them and do a M33 and get the long format name

Send: M20
[...]
Recv: Begin file list
Recv: PLADEL~1.GCO 393031

Send: M33 PLADEL~1.GCO
Recv: /PLA Delta_Test_Cube.gcode

Is it there anyway to show on TFT35 display and/or Octoprint the long version display?

**Comment by bigtreetech** [comment]
Hello, This function has been implemented in #235, so close here.
