### ISSUE TITLE
[Q] Can I use the power loss recovery

### ISSUE THREAD

**Issue by nobaj** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1870]
Is there a way to use marlin power loss recovery without using the marlin display??? I only have my display connected via tft.

**Comment by oldman4U** [comment]
Does the PLR of the TFT not work!?

**Comment by nobaj** [comment]
omg the tft has a plr?

**Comment by oldman4U** [comment]
There is even a setting for this, where you can turn it off. Default on, so it is very likely activated already.

Please close the ticket once you do not need it anymore.

Thank you

**Comment by oldman4U** [comment]
Are you still looking for it, or do you have a problem with it?

**Comment by oldman4U** [comment]
@Msq001 This ticket is unrelated to the firmware and the user does not reply.

Please check and close the ticket. Thank you
