### ISSUE TITLE
Filament Runout / Filament Change Problem

### ISSUE THREAD

**Issue by fiveorders** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1882]
**Your question or details you need. Please describe.**
When I use marlin mode, the filament run-out sensor does its job and parks the nozzle, unloads and resumes fine and starts printing where it left (there is a filament blob but I will look into that later) On TFT mode, the same procedure applies, however after loading the filament I click resume and it goes where it was, however, unloads the filament again on that position

I tried turning off the M600 emulation, this time, after the resume button, it goes where it was but instead of printing stays there and creates a big blob, after 2 seconds of pausing there, it goes to XY0 position and comes back to that last location again but this time scratching the bed. 

**specify the device variant related to your question.**
BTT TFT70(v26) + FLY407ZG(marlin nightly build bug fix 2.0)

**Comment by oldman4U** [comment]
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/1829
