### ISSUE TITLE
[BUG] Errore continuo in stampa: Printer Halted TFT35 E3 V3

### ISSUE THREAD

**Issue by SteULM** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1886]
### Description

Installed the new firmware vers. 27 I continue to have the problem in the object that disappears putting back the vers. 26

### Steps to reproduce

1. [Preheat]
2. [Print start]
3. [After a while it freezes reporting the error]

### Hardware Variant
TFT35 V3 E3 - SKR 1.4 Turbo - TMC2009
### TFT Firmware Version & Main Board Firmware details
TFT Firmware version number v27 & Marlin firmware version number 2.0 bugfix

**Comment by kisslorand** [comment]
Sajnálom de nem értem mi a gond. Próbáld angolul írni, több az esély, hogy választ kapjál.

**Comment by bigtreetech** [comment]
You mean that the firmware version v.27 will have a "Printer Halted" error during printing? And you can print it normally with the firmware of v.26?

Please click "OK" in the "Printer Halted" error pop-up window, and then click the title bar to enter the `Notifications` menu and send me the detailed information displayed in the `Notifications` menu

**Comment by SteULM** [comment]
Yes, during the first printing stages, the error appears. With version 26, however, no problem. Attached is the video where you can see the crazy temperatures in version 27 and stable in version 26.

https://user-images.githubusercontent.com/83312403/116388193-d79e6f00-a81b-11eb-9ccb-42292425b7ba.mp4

![20210428_111356](https://user-images.githubusercontent.com/83312403/116388222-e1c06d80-a81b-11eb-875f-34d92088843b.jpg)
![20210428_110230](https://user-images.githubusercontent.com/83312403/116388234-e5ec8b00-a81b-11eb-9f60-249550ff4050.jpg)

https://user-images.githubusercontent.com/83312403/116388255-ebe26c00-a81b-11eb-9169-51ffc0b22f87.mp4

**Comment by oldman4U** [comment]
What kind of thermistor are you using and how many?

One for extruder and one for bed?

**Comment by SteULM** [comment]
Yes, 100k (Creality CR10) and 100k for the bed.
I confirm that it is with the firmware vers. 26 that by reassembling the RepRapDiscount Full Graphic Smart Controller everything works correctly without any type of error, the problems are only with the firmware vers. 27 installed correctly following the guide.

**Comment by SteULM** [comment]
Thanks for the help

**Comment by SteULM** [comment]
With the vers. 27 the extruder cannot reach the set temperature while with vers. 26 reaches it.

**Comment by oldman4U** [comment]
Please provide the Notification like requested by Bigtreetech 22h ago.

**Comment by SteULM** [comment]
What is reported in the notification menu is displayed in the photos I attached to previous posts, however the strange thing is that the problem only occurs with version 27 of the firmware.
The errors reported are:
Thermal Runaway, System stopped! Heater_ID: 0
Printer Halted. kill() called!

**Comment by oldman4U** [comment]
I do not believe that you provided the required information.

The error is shown in case the heater does not heat properly or the thermistor has a problem. I had this once because of a broken cable. But I do not have this problem using v27 and it seems other users do not have it too. 

Hope BTT can help you.

**Comment by SteULM** [comment]
Thanks for the help, I can only say that I have double checked all the wiring and there are no problems, as I said before, the problem occurs only with the v27 and I have no problem even if I put the graphic display I used before. I hope they can help me because the tft is excellent and well done and I would like to continue using it with version 27 because I find it very complete compared to the previous one.

**Comment by bigtreetech** [comment]
It is very strange that according to the video you provide. the reason for Printer Halted is that the temperature of Marlin motherboard can not be stabilized. In fact, TFT only receives and displays the temperature. Marlin is responsible for PID temperature control. In principle, no matter which version of TFT firmware is likely to cause this problem. Unless the TFT modifies the PID parameter somewhere?

The only difference between your two videos is the firmware version of TFT (One is V.x.x26, the other is Vx.x27)  and everything else is exactly the same (Including the hardware environment, and Marlin firmware is exactly the same)?

**Comment by SteULM** [comment]
Yes hardware itself. In fact, trying to replace the SKR 1.4 board with one with the same Marlin the problem disappears. In this case the TFT has no problems. Thanks for the support and I congratulate you on a great product.

**Comment by oldman4U** [comment]
This leaves the question left, how the older TFT firmware could "repair" the broken SKR.

Good to hear you found the problem, please close the ticket once you do not need it anymore.

Happy printing

**Comment by SteULM** [comment]
No after more time but it also crashed with the old firmware. Thanks anyway to everyone for the support.
