### ISSUE TITLE
error in parseACK.c for infoSettings.machine_size_max ?

### ISSUE THREAD

**Issue by Petch62** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1889]
//----------------------------------------
      // Tuning parsed responses
      //----------------------------------------

      // parse and store build volume size
      else if (ack_seen("work:"))
      {
        if (ack_seen("min:"))
        {
          if (ack_seen("X:")) infoSettings.machine_size_min[X_AXIS] = ack_value();
          if (ack_seen("Y:")) infoSettings.machine_size_min[Y_AXIS] = ack_value();
          if (ack_seen("Z:")) infoSettings.machine_size_min[Z_AXIS] = ack_value();
        }
        if (ack_seen("max:"))
        {
          if (ack_seen("X:")) infoSettings.machine_size_min[X_AXIS] = ack_value();     <--- is not infoSettings.machine_size_max
          if (ack_seen("Y:")) infoSettings.machine_size_min[Y_AXIS] = ack_value();     <--- is not infoSettings.machine_size_max
          if (ack_seen("Z:")) infoSettings.machine_size_min[Z_AXIS] = ack_value();     <--- is not infoSettings.machine_size_max
        }
      }

**Comment by digant73** [comment]
yes it's a bug
