### ISSUE TITLE
[BUG] after loading new firmware on tft 35 the led green is with wite color!and the others with the white color ((( if i switch to the old version everything is good)

### ISSUE THREAD

**Issue by mitofun** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1895]
### Steps to reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior**

**Actual behavior**

### Additional Information
* Include a ZIP file containing your `Configuration.h` or use [Pastebin](https://pastebin.com/) and paste a link in this issue.
* Provide pictures or links to videos that clearly demonstrate the issue.

**Comment by oldman4U** [comment]
The exact type of TFT and the exact firmware version are a secret?

**Comment by radek8** [comment]
The whole description of the problem is one big secret.

**Comment by oldman4U** [comment]
Maybe it is a Samsung TFT35...?

;-)

**Comment by oldman4U** [comment]
Just tested the firmware from April 28th on my TFT35 E3 v3 and the colours are working fine.

**Comment by mitofun** [comment]
> Just tested the firmware from April 28th on my TFT35 E3 v3 and the colours are working fine.

https://youtu.be/i1zXh8DkLsI

**Comment by mitofun** [comment]
> The whole description of the problem is one big secret.

https://youtu.be/i1zXh8DkLsI

**Comment by oldman4U** [comment]
So this is a TFT with neopixel connector and you have neopixel or RGB leds connected there?

**Comment by mitofun** [comment]
> So this is a TFT with neopixel connector and you have neopixel or RGB leds connected there?

neopixel - also if i send m150 u200 or other color command works good) also if i install the previous version of tft firmware - everything works good! but the new one does not works properly*(

**Comment by oldman4U** [comment]
And you have seen the new neopixel function in confi.ini and setup it right?

**Comment by mitofun** [comment]
Need to check it ;) > And you have seen the new neopixel function in confi.ini and setup it right?

**Comment by mitofun** [comment]
> And you have seen the new neopixel function in confi.ini and setup it right?

the neopixels connects to the board) also if i print with gcomand in cura works good- only from tft does not works properly)

**Comment by mitofun** [comment]
> neopixel

the neopixel function only for the terminal from tft) i have got connection to the bard ) also if i send command m150 u200 works good! also if i switch of from the tft the led and try to send command again nothing works! but once i press green from the tft the rgbw is green and white) and if want it light green go to commands and send m150 u200 works again good) so the problem might be in the congif ) the previous version works good)

**Comment by mitofun** [comment]
> And you have seen the new neopixel function in confi.ini and setup it right?

3 May 2021 https://youtu.be/8agzcoLhu-E

**Comment by digant73** [comment]
@mitofun it seems you have and RGBW. from the LED custom menu move to second page and set the white component to 0. Previous TFT fw was working because the white component was never sent to Marlin (only RGB components were sent)

**Comment by mitofun** [comment]
Ok thank will try it;)))> @mitofun it seems you have and RGBW. from the LED custom menu move to second page and set the white component (W) to 0. Previous TFT fw was working because the white component was never sent to Marlin (only RGB components were sent)

**Comment by mitofun** [comment]
Yep did it on custome and set the white to 0 works - but still do not sorted why I press the green from the tft and it is green and white ;)

**Comment by digant73** [comment]
yes I know that. For standard colors, the withe componet is always set in this moment. The LED Color menu is general and it was preferred to provide also W component
