### ISSUE TITLE
 how to create dot matrix font?

### ISSUE THREAD

**Issue by dineshvyas** [bigtreetech/BIGTREETECH-TouchScreenFirmware#191]
![Capture](https://user-images.githubusercontent.com/55104840/69641024-6f2aeb80-1085-11ea-9ae7-e59ebe0bd97f.JPG)
this is amazingly easy..."at least it made to sound like this" But my question is, how to create  dot matrix font. which application to use or online webpage?

**Comment by rndsum** [comment]
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/327 Wrote that up lemme know if I can improve it.
