### ISSUE TITLE
[FR] M154 - automatic position reporting

### ISSUE THREAD

**Issue by radek8** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1921]
Permanent problems with incorrect layer height could be solved with the new command 
M154 - automatic position reporting

https://github.com/MarlinFirmware/Marlin/pull/18427

**Comment by kisslorand** [comment]
There are no more problems with incorrect layer height. It's been reworked by PR #1894 (which is already merged).

**Comment by oldman4U** [comment]
Maybe it could help to reduce the traffic.

**Comment by sarvenn** [comment]
> Maybe it could help to reduce the traffic.

https://reprap.org/wiki/G-code#M154:_Auto_Report_Position
Yeah, it says that it reduces serial comm traffic.

**Comment by oldman4U** [comment]
PR1924 my friend

**Comment by radek8** [comment]
Thanks, that's great.
