### ISSUE TITLE
Invert Z Axis for Baby Steps[FR] (feature request title)

### ISSUE THREAD

**Issue by sinus19** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1926]
It is a bit confusing having to think "upside down" when adjusting the Z while using Baby Steps on a Core XY machine. The Z Axis can be inverted for normal Z travel moves but it is not an option for Baby Step editing.

It would be nice to have the Baby Steps menu also reflect the proper inverted Z Axis.

**Comment by digant73** [comment]
Is your problem the same as #1918?
