### ISSUE TITLE
[FR] M575 - Serial baud rate

### ISSUE THREAD

**Issue by Guilouz** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1939]
Maybe add this option can be a good addition to choose baud rate for each serial port.

https://marlinfw.org/docs/gcode/M575.html

Related to Marlin PR https://github.com/MarlinFirmware/Marlin/pull/21949

#define BAUD_RATE_GCODE     // Enable G-code M575 to set the baud rate

Must be enabled in Configuration.h

**Comment by oldman4U** [comment]
This command will interrupt serial communication to the host and may reset the firmware when the host reconnects at the new baud rate.

**Comment by oldman4U** [comment]
And what would be a good use case for this?

In case one of the developers spent his valuable time implementing new code, the result should provide improved stability, and/or extended functionality and/or better usability.

Please let me know

Thank you

**Comment by oldman4U** [comment]
Could you please provide a practical use case or close this ticket. 

Thank you

**Comment by oldman4U** [comment]
@Msq001

Could you please check if this gCode could be used for something useful and close this ticket afterwards.

Thank you
