### ISSUE TITLE
Screen shifts to right in Marlin mode.

### ISSUE THREAD

**Issue by dexter323i** [bigtreetech/BIGTREETECH-TouchScreenFirmware#194]
I have a TFT35 V3.0, latest FW. Main board is SKR Mini E3 V1.2.

Sometimes I run into a strange issue when I use the display in Marlin mode (when rotary encoder is used). If I rotate the knob too quickly or I don't know how, but suddenly the screen slides a bit into the right, and the left part is filles with the right part, a bit shifted. Hard to describe... I successfully recorded a video where I could reproduce the problem:
https://youtu.be/x85rvSQO4Z8
(Not listed video)

**Comment by Hukuma1** [comment]
Can confirm I have been getting this same bug since even firmware TFT v23.

**Comment by brushby** [comment]
i get exactly the same problem

**Comment by davehardy20** [comment]
I get this issue also on a regular basis

**Comment by billydragon** [comment]
The same happen for me. Also some time it look like picture. Printer still running.

![2020-01-05 09 16 13 HDR-1](https://user-images.githubusercontent.com/51144107/72424574-cc573980-37b8-11ea-924a-f440f0795296.jpg)

**Comment by dexter323i** [comment]
Okay. It seems I have found a solution. (Maybe workaround?) Changed the baud rate to 250000, and solved the issue for me. With this setting, only some caharcters goes crazy, but after more rotation on the knob, it repairs itsfelf.
My settings in Marlin:
- platformio.ini ln 45: monitor_speed = 250000 (In [env] section)
- platformio.ini ln 336: monitor_speed = 250000 (in [env:STM32F103RC_bigtree_512K] section)
- Configuration.h ln 106: #define SERIAL_PORT 2
- Configuration.h ln 115: #define SERIAL_PORT_2 -1
- Configuration.h ln 126: #define BAUDRATE 250000

Then in the settins menu of the TFT screen in Touch mode, and done!
