### ISSUE TITLE
Bigtreetech E3 RRF V1.1 and TFT35 not working

### ISSUE THREAD

**Issue by Zoli-user** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1946]
Bigtreetech E3 RRF V1.1 and TFT35 Ender 3 V2 issue
### Steps to reproduce

1. BTT-E3 RRF V1.1 have only the 2.0.7.x firmware and the TFT35 have the 2.0.8.x firmware.
2. Install the latest firmware version for the motherboard and the TFT35 but the printer is not working. 
3. Install the 2.0.7 firmware version for the motherboard and install the 2.0.8 the tft35 but the printer is not working.
4. Install the RepRap firmware the motherboard and the TFT35 and the printer is not working
5. Use the original Ender 3 V2 display and the new BTT-E3 RRF V1.1 and the display have a blank screen and beep continuously.
6. I try to install the older 2.0.7 firmware for the TFT35 and the actual 2.0.7 for the Motherboard the error is same. The printer not working normally. BLTouch is off, the Z axis zero point out of range.

**Expected behavior**

I would like to see the new Marlin 2.0.8.x firmware by the BTT-E3 RRF V1.1. The original BTT-E3 RRF V1.1 motherboard and the BTT TFT35 is a same product, but the software is different. Why?

**Actual behavior**

The printer is on and every system is ready. The TFT communicated the motherboard. After power on I have a several error notification. Bed level error, BLTouch not working, the Z axis zero point is out of the printer range.

Inside the TFT35 config.ini file:
#--------------------------------------------------------------------
# Supported Marlin Firmware Versions
#--------------------------------------------------------------------
#
# Minimum Marlin firmware version: 2.0.8.1
# Distribution date: 2021-05-15

Super. :-( the BTT-E3 RRF Github page have only the 2.0.7.x motherboard firmware.... ????????????????

What works: 
1. Communication between the TFT and the motherboard
2. Moving the axis step by step
3. Touch screen
4. Every menu item

What doesn't work:
1. BLTouch
2. Axis reference run
3. Bed leveling
4. Print :-)
5. Wi-FI connection
 

### Hardware Variant

BTT TFT35 E3 V3.0 ZZB000378
BTT-E3 RRF V1.1 ZZB000521
### TFT Firmware Version & Main Board Firmware details

BTT TFT35 E3 V3.0 ZZB000378 Use the 2.0.8.x. Download this site: BIGTREETECH-TouchScreenFirmware
BTT-E3 RRF V1.1 ZZB000521 Use the 2.0.7.x Download this site: bigtreetech / BTT-E3-RRF

### Additional Information
* Include a ZIP file containing your `Configuration.h` or use [Pastebin](https://pastebin.com/) and paste a link in this issue.
* Provide pictures or links to videos that clearly demonstrate the issue.

**Comment by bigtreetech** [comment]
Hello, what is the specific phenomenon of not working?  “No printer attached!” on TFT ?

**Comment by oldman4U** [comment]
And please verify the version number of the TFT firmware. 2.0.8.1 is Marlin and not TFT.

**Comment by Zoli-user** [comment]
Hello. First of all, I am grateful you are answering.
No, after power on the system the connection is establised. 
Step by step:
1. Power on :-)
2. The display established the connection for the printer
3. Apparently everything is ready.

But the printer can’t run the reference “Z-homing” for some reason the printer zero point is up to 60mm. I press the home run icon the printer go to the X axis end switch and I have an error notification. 
Another things after power on the printer I have some notification. Ca… bed level error…..etc.
I go inside the menu and try to turn on the BLTouch…. But I can’t.
I try to move manualy the axis and its work. I using the small steps and its moving.

First of all, please tell me which firmware should I try to the TFT and the Motherboard. Tonight I try to install again the display and the motherboard and send some picture fot You the issues. 
I’m only the simple user. I can’t handle the VisualStudio. Just find the firmware.bin files copy the SD card and install.
I know the display have more than one file I see Your user manual. And I see the Marlin have a 2.0.8 firmware but only the source code. I try to create the bin file but I have a many error. This method is doesn’t work for me. 

A solution might be to send me what to install on the machine
and I can test and give feedback on it. My Ender 3 V2 is a good printer and I see the Bigtreetech tools are also quality products. I'm sure I'm ruining something. I’m just an avid amateur who loves these things.

Interesting thing I change back the original hardware and the printer is working fine…

**Comment by radek8** [comment]
You knit the Marlin RRF and TFT together.
they are 3 different FWs.

Learn to control VS. Custom compilation of Marlin is a must.

**Comment by jaysuk** [comment]
or use RRF where no compilation is required
Thanks,

Jay

**Comment by radek8** [comment]
the new Marlin is here.
https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x

**Comment by jaysuk** [comment]
and the latest RRF is here
https://github.com/gloomyandy/RepRapFirmware/releases/tag/v3.3-RC2%2B1_1
Thanks,

Jay

**Comment by radek8** [comment]
unfortunately TFT is not yet fully compatible with RRF

**Comment by radek8** [comment]
FW for TFT is here:
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/tree/master/Copy%20to%20SD%20Card%20root%20directory%20to%20update

**Comment by jaysuk** [comment]
it's mostly there and can handle the majority of the jobs needed when
you're stood at your machine and for everything else there are macros.
Thanks,

Jay

**Comment by oldman4U** [comment]
@bttguy

Could you please help 

Thank you

**Comment by Zoli-user** [comment]
![9D6D0E6F-06EB-4D9D-94E2-F486496D585F](https://user-images.githubusercontent.com/84640882/119336920-848ad100-bc8e-11eb-835d-9b12fa8f2046.jpeg)

When I installed the firmware and start the system this is a first notification what I have…

**Comment by radek8** [comment]
> ![9D6D0E6F-06EB-4D9D-94E2-F486496D585F](https://user-images.githubusercontent.com/84640882/119336920-848ad100-bc8e-11eb-835d-9b12fa8f2046.jpeg)
> 
> When I installed the firmware and start the system this is a first notification what I have…

Install the latest Marlin with bug fixes.
Uncomment option:
AUTO_REPORT_POSITION (in Configuration_adv.h)

**Comment by radek8** [comment]
> ![9D6D0E6F-06EB-4D9D-94E2-F486496D585F](https://user-images.githubusercontent.com/84640882/119336920-848ad100-bc8e-11eb-835d-9b12fa8f2046.jpeg)
> 
> When I installed the firmware and start the system this is a first notification what I have…

@guruathwal, if I'm not mistaken, this error should not occur.
if Marlin does not support the M154 command, the TFT should not use it.

**Comment by guruathwal** [comment]
The M154 error is already fixed after #1940

**Comment by radek8** [comment]
@guruathwal, Thank you.
@Zoli-user , Then you don't have the latest FW on TFT

**Comment by bttguy** [comment]
I can also help you in case you would like to try RRF, I am not that familiar with Marlin since I switched. As Jay said, most of the essential features work, and the rest is handeled by RRF and its web interface from you PC/phone :)

**Comment by oldman4U** [comment]
@Zoli-user seems to use rrf and I believe you can expect some new rrf related stuff soon. So maybe you can help to fix the 3 outstanding rrf tickets by testing possible fixes.

**Comment by bttguy** [comment]
I would be glad to test new features/bugfixes, and also can quide new users in setting up their screen. I checked the RRF related tickets, but they are known limitations, more like FR-s than bugs.
Sadly I cant code either, and the most I can do is that I can send resources to the developers to see what and how the gcode is different in Marlin and RRF.
Until that I also included these "bugs" to the RRF enhancement ticket I made. I want to add that the support is already awesome for RRF users compared what we had before, I dont complain here, I try to do my best to help :)

**Comment by Zoli-user** [comment]
Hello,

Today 8:00pm I start the new installation for the TFT and the Motherboard by RRF latest firmware.
If You have time please follow me and "help". I show You by pictures the process.

Let us see what firmware ready for install:
TFT35 E3 V3 display
1. Bigtree_TFT35_V3.0_E3.27.x.bin
2. config_rrf.ini
3. TFT35 folder

Motherboard BTT-E3 RRF v1.1
1. firmware-stm32f4-esp8266wifi-3.3rc2+1_1.bin
2. firmware sub folder inside this file: DuetWiFiServer-stm32f4.bin

**Comment by bttguy** [comment]
@Zoli-user How is it going? Just a quick question, did you renamed the firmware.bins and the config.ini + did you included the required folder structures with the sys files and the example configs from the online configurator? + you need a board.txt with some lines.

**Comment by Zoli-user** [comment]
Of course. Every file name renamed the correct words. And every subfolder with correct file are ready. Meanwhile I try to build a 2.0.8.1 Marlin alternate version. If the RRF is not working I try to install the Marlin if I know and success the firmware build...

**Comment by jaysuk** [comment]
why not join our discord channel? we'll support you with any RRF issues
https://discord.gg/uS97Qs7

Thanks,

Jay

**Comment by Zoli-user** [comment]
I try to create my own firmware. Not working :-(

![D102D4E6-C0AA-4D08-BA23-6DF06708B150](https://user-images.githubusercontent.com/84640882/119489995-95a21380-bd5c-11eb-93c9-0ef0f6a3a1dc.jpeg)
![69A7E292-9A56-4B43-B81E-241B57AEA483](https://user-images.githubusercontent.com/84640882/119490000-976bd700-bd5c-11eb-9038-cc0c9f987821.jpeg)

**Comment by Zoli-user** [comment]
Hello. Now I start the BTT E3 RRF V1.1 motherboard install
![Uploading 2A89EFF0-5765-4956-8563-46CB476F8242.jpeg…]()

**Comment by Zoli-user** [comment]
Now the new MB is installed and next the TFT
![Uploading 2F84250D-28DF-4399-BDEC-47518D8A2735.jpeg…]()

**Comment by Zoli-user** [comment]
![4197EDEA-3040-4F12-99DB-A50939CD5FD8](https://user-images.githubusercontent.com/84640882/119534775-93a17a00-bd87-11eb-8cef-b59c4c95dc91.jpeg)

**Comment by Zoli-user** [comment]
![Uploading C99CB4B4-904C-4DF9-B18D-497D03E7B98B.jpeg…]()

**Comment by Zoli-user** [comment]
![DC2C4130-6541-40F8-B6FF-81476BFF204B](https://user-images.githubusercontent.com/84640882/119534889-b5026600-bd87-11eb-9537-ccf9fb53c7f2.jpeg)

**Comment by Zoli-user** [comment]
Now first off all the TFT install. Follow by ruiraptor YouTube video
![69BF00F1-8A15-459E-88D9-24AB7329E33C](https://user-images.githubusercontent.com/84640882/119537762-ad908c00-bd8a-11eb-99f6-4e68b665ea0d.jpeg)

**Comment by Zoli-user** [comment]
Now after the MB firmware installed I have this screen
![F94F4B9C-CF88-4DE1-8787-3A8BB4E0475C](https://user-images.githubusercontent.com/84640882/119539894-09f4ab00-bd8d-11eb-93c6-b0f54a104ef1.jpeg)

**Comment by Zoli-user** [comment]
After this process, restart the printer and I have a connection the TFT and the MB

![C3A491D6-EDA0-4588-A192-60080FDB069B](https://user-images.githubusercontent.com/84640882/119540690-0150a480-bd8e-11eb-86cf-715a0e468232.jpeg)

**Comment by bttguy** [comment]
Did you connected to your WiFi yet? You should see your IP for DWC(web interface)?

**Comment by Zoli-user** [comment]
At this moment the printer axis are not moving. The next step the wi-fi settings. Use an USB cable and run the Pronterface software.

![736F16C0-6B46-4C6F-B46E-C6DF332CF7BC](https://user-images.githubusercontent.com/84640882/119541045-6b694980-bd8e-11eb-8864-3292d7d0d2aa.jpeg)

**Comment by Zoli-user** [comment]
The printer is online.

![6152A871-7942-4448-A7A0-58708A076FBE](https://user-images.githubusercontent.com/84640882/119541227-a8cdd700-bd8e-11eb-94b3-4f2d4c93014a.jpeg)

**Comment by Zoli-user** [comment]
After connecting type M115. I see the printer online and see the version number.

![11D95A9D-EE07-4184-8953-147F7BA6F387](https://user-images.githubusercontent.com/84640882/119541736-0e21c800-bd8f-11eb-9655-02f4f42feb04.jpeg)

**Comment by Zoli-user** [comment]
Next type M997 S1. The system update the modul.

![CBB7BF74-A6E2-4246-AFAE-800EDDC52E94](https://user-images.githubusercontent.com/84640882/119541865-34476800-bd8f-11eb-8e23-8a0997619721.jpeg)
![DEC05BFC-AF18-4127-98FC-AE2FDF48E89E](https://user-images.githubusercontent.com/84640882/119541884-37daef00-bd8f-11eb-9268-2e8b648eeaf3.jpeg)

**Comment by Zoli-user** [comment]
Type a correct command and the printer have an IP.

![8B41DDEF-3966-46B1-BB59-F940D1D8F5E9](https://user-images.githubusercontent.com/84640882/119545094-b6855b80-bd92-11eb-9165-2ceae9617936.jpeg)

**Comment by jaysuk** [comment]
I'm not quite sure what you're trying to document here

**Comment by Zoli-user** [comment]
@jaysuk You can find here to the wifi settings code. See 14:32
https://www.youtube.com/watch?v=2ytFdP2_Myo&t=5s

**Comment by jaysuk** [comment]
But again, what are you trying to do? Or what are you trying to show? Or
what are you trying to document?
We already have the whole process documented here
https://teamgloomy.github.io/ that at least 2.5k users have accessed and
followed

**Comment by Zoli-user** [comment]
Finally type IP the browser and You see the printer menu.
After entering the SSD and pass I had to wait 5 min for the IP to appear.

![33641E35-B89C-4DD2-93D7-2C3F4846877C](https://user-images.githubusercontent.com/84640882/119546957-c9992b00-bd94-11eb-8260-fdf3b61be9e0.jpeg)

**Comment by Zoli-user** [comment]
And last how to use the software. User manual is here:
https://duet3d.dozuki.com/Wiki/Duet_Web_Control_v2_and_v3_%28DWC%29_Manual

**Comment by jaysuk** [comment]
Ok, this thread obviously is nothing to do with the TFT firmware and should
be closed

**Comment by Zoli-user** [comment]
And finally this is the first error. 

![06A2A200-20FC-42F1-A973-F6D2B5CEFB85](https://user-images.githubusercontent.com/84640882/119550634-f0596080-bd98-11eb-8adb-e7aca0864208.jpeg)

**Comment by Zoli-user** [comment]
Touch this icons and nothing happened. The BLTouch not “moving”


![F6C2FE23-B426-40C7-B350-103BC13FCA40](https://user-images.githubusercontent.com/84640882/119550891-3c0c0a00-bd99-11eb-89a3-3a62af6d50cf.jpeg)

**Comment by Zoli-user** [comment]
In the website G29 error Z probe 0 not found.
![09A4134B-9D0F-49AC-9F69-07228D254D0E](https://user-images.githubusercontent.com/84640882/119551013-6c53a880-bd99-11eb-9d5b-c8da1c358a35.jpeg)

**Comment by Zoli-user** [comment]
For some reason it considers this height as zero point. 

![E3271992-5F7B-45E0-98C9-EB9A85B3E35E](https://user-images.githubusercontent.com/84640882/119551283-bdfc3300-bd99-11eb-8042-fde495993a65.jpeg)

**Comment by Zoli-user** [comment]
How to setup a real Z null point and the BLTouch? This is a question today. :-)

**Comment by Zoli-user** [comment]
And what is the PLA Filament config.g code.

![C311DF76-6C1E-4B29-86CB-E93017482C8E](https://user-images.githubusercontent.com/84640882/119551797-51356880-bd9a-11eb-9805-dacb24fc0e78.jpeg)

**Comment by Zoli-user** [comment]
My settings is correct every file I use find the Bigtreetech page and I follow the instructions. Copy all Ender 3 V2 config file to the right place.

**Comment by Zoli-user** [comment]
And I use only the latest release.

**Comment by Zoli-user** [comment]
This is the config.g file inside the sys folder:

; Axis Limits
M208 X0 Y0 Z0 S1                               ; set axis minima
M208 X230 Y230 Z250 S0                         ; set axis maxima

; Endstops
M574 X1 S1 P"xstop"                            ; configure active-high endstop for low end on X via pin xstop
M574 Y1 S1 P"ystop"                            ; configure active-high endstop for low end on Y via pin ystop
M574 Z1 S1 P"zstop"                            ; configure active-high endstop for low end on Z via pin zstop
;M591 D0 P7 C"e0stop" S1  R50:130 L7.0 E10     ; BTT Smart Filament Sensor
;M591 D0 P1 S1                                 ; Filament runout Sensor

; Z-Probe  Bltouch
;M950 S0 C"servo0"                              ; create servo pin 0 for BLTouch
;M558 P9 C"^probe" H5 F120 T6000                ; set Z probe type to bltouch and the dive height + speeds
;G31 P500 X-40 Y-10 Z2.95                      ; set Z probe trigger value, offset and trigger height
;M557 X10:180 Y10:210 S40                       ; define mesh grid

**Comment by Zoli-user** [comment]
I found something. Maybe this is not good.
The BLTouch code is grey.

![D1A334AF-730D-43F3-A49B-F7153214FFCB](https://user-images.githubusercontent.com/84640882/119553541-fdc41a00-bd9b-11eb-8c7e-c0548f38ad70.jpeg)

**Comment by jaysuk** [comment]
Those settings are incorrect as you have commented out the settings.
This is the last time I will say this. This is the incorrect place to be
raising your issues as they are not related to the TFT firmware. You need
to seek support elsewhere. I have given you the link to the STM RRF support
channel on discord. If you are unwilling to use that then I suggest either
the duet forum or one of the RRF Facebook groups.

Again, can an admin close this issue as it is unrelated to the TFT firmware

**Comment by Zoli-user** [comment]
Ok

**Comment by oldman4U** [comment]
@Msq001

Please close this ticket as it is unrelated to the TFT firmware.

Thank you

**Comment by oldman4U** [comment]
Thank you @jaysuk
