### ISSUE TITLE
TFT35 v3 Unknown Gcode Command

### ISSUE THREAD

**Issue by Jingsun-Young** [bigtreetech/BIGTREETECH-TouchScreenFirmware#195]
First I print with end gcode that work well in marlin mode. but when print in touch mode, it stuck & shown error notification
![Capture1](https://user-images.githubusercontent.com/58245343/69696897-a7790b00-1113-11ea-84b8-2434c4fda2a9.PNG)
![118179](https://user-images.githubusercontent.com/58245343/69697654-9df0a280-1115-11ea-9e46-40c2c54ab29a.jpg)

After I skip some gcode line, it work well until shutdown. 
![Capture2](https://user-images.githubusercontent.com/58245343/69697310-b14f3e00-1114-11ea-9bf1-8cf5acb07b6d.PNG)
![118180](https://user-images.githubusercontent.com/58245343/69697662-a5b04700-1115-11ea-9a10-86eedfe709ff.jpg)

I'm not sure this is the issue or I miss understand for something. Please help.

**Comment by bigtreetech** [comment]
On the first issue: Can you send me your gcode so that I can reproduce the question? 
about the second issue:  When you enable the AutoPower in Feature menu(Settings->Feature or Printing->More->Feature),  After printing, The screen will wait until the temperature of the nozzle is lower than 50 ℃ (for safety) and automatically add "M81" command to shut down. You can choose force to shut down immediately or cancel the  shutdown.

**Comment by Jingsun-Young** [comment]
Thanks for your advice. I'd send you gcode file attached. The second was not issue but I show you the notification that pass through the end process. The question is every print job I would choose the proper gcode for each mode (marlin & touch mode).  

[gcode opt1.txt](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/3895652/gcode.opt1.txt)

**Comment by bigtreetech** [comment]
Hi. I have confirmed this problem. This is a bug. The screen is not compatible with parameters such as ‘B’ ‘F’ ‘R’ of “M104” “M140” “M109” “M190”. I will fix it as soon as possible

**Comment by bigtreetech** [comment]
very thanks for you feedback

**Comment by Interplain** [comment]
This issue is same as i am getting with current TFT 35 v2.0.25 with SKR 1.3

**Comment by deebeo-blip** [comment]
Me as well. Can you tell, when a new Version will be released. I am currently on 2.0.25.1 with SKR v1.3 and I am experiencing "command unknown" Error messages on the display resulting in Y Layer Shifts while printing. Thank you,

**Comment by bigtreetech** [comment]
It should be fixed in #402, so I close here
