### ISSUE TITLE
[Q] documentation error

### ISSUE THREAD

**Issue by radek8** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1954]
@oldman4U 
You have an error in the table
SKT V1.3 cannot be connected via the AUX1 connector on the EXP3 display!

![image](https://user-images.githubusercontent.com/46979052/120063093-c1c3da00-c065-11eb-8889-e72498c3bf28.png)

**Comment by radek8** [comment]
The same applies to SKR V1.1

![image](https://user-images.githubusercontent.com/46979052/120063176-34cd5080-c066-11eb-879a-67a22f1754c5.png)

**Comment by radek8** [comment]
The AUX1 connector is for serial connection to the MKS display

**Comment by oldman4U** [comment]
Hi radek8

Thank you. This would be correct then, right? Because CR-10 is also wrong.

![118848226-d74f3c00-b8ce-11eb-8210-d9e61a8f5650](https://user-images.githubusercontent.com/54359396/120073936-cbb40000-c09a-11eb-8f12-b13b6c6c7a7b.png)

**Comment by radek8** [comment]
Yes, that's right, but why are the lines duplicated?

**Comment by oldman4U** [comment]
🤪

**Comment by oldman4U** [comment]
Hi radek8.

Thomas White replied this: Not dupes, those boards have connectors that can use either setup just not both.

I do not have such a board to verify so I will finally trust him.

**Comment by radek8** [comment]
Oldman4U, you returned that error to the spreadsheet.
I looked at the layout of the PINs.
Yes, these boards can be connected via one 10-pin connector with the CR10_STOCKDISPLAY driver.
But then it must be connected via the EXP1 connector, but not via the AUX1 connector. The AUX1 connector on the SKR board is not compatible with the EXP3 connector on the TFT. If someone could connect it (EXP3 has 10 pins, but AUX1 only 8 pins) it could have fatal consequences.

If the CR10_STOCKDISPLAY driver is selected, then it would be possible to connect EXP1 in the SKR, with the EXP3 connector in  the TFT.
The same would apply to SKR V1.4 and SKR V1.4Turbo
