### ISSUE TITLE
[BUG] Damaged txt during M48 Repeability Test

### ISSUE THREAD

**Issue by radek8** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1991]
The pop-up window with the M48 test result has corrupted text

![image](https://user-images.githubusercontent.com/46979052/121746976-f70d0500-cb06-11eb-8413-c9fc1d3e6def.png)

These are two texts on top of each other
Standard Deviation: 0.00548
and
Mean: 0.000538

This is how Marlin's response looks like

![image](https://user-images.githubusercontent.com/46979052/121750272-5d485680-cb0c-11eb-8c02-7315d4cc53ba.png)

It looks like there are 2 pop-up windows on top of each other.

![image](https://user-images.githubusercontent.com/46979052/121754240-5cb3be00-cb14-11eb-9805-2e545debc6d7.png)

**Comment by guruathwal** [comment]
@radek8 which TFT variant are you using? I fixed this issue with TFT43/TFT50.

**Comment by radek8** [comment]
TFT 35 E3 V3. 0

**Comment by oldman4U** [comment]
I saw such an issue after bed leveling. Same TFT.

**Comment by digant73** [comment]
on a 320x240 resolution (TFT28) it works properly
