### ISSUE TITLE
Main screen and printing screen language

### ISSUE THREAD

**Issue by AntoszHUN** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1998]
Hi! Is it possible to integrate the Hungarian translation of the values ​​of the main screen and the print screen into the language file? I mean (flow, layer, speed ... Etc.)

Made by: AntoszHUN
![Screenshot_20210616-110935~3](https://user-images.githubusercontent.com/45710979/122192540-0b992680-ce94-11eb-9e6b-baedd2af773c.png)

**Comment by kisslorand** [comment]
Yes, possible.

**Comment by AntoszHUN** [comment]
> Yes, possible.

This is good news. If I have time, I'll try.
