### ISSUE TITLE
TFT35 MZ V3.0 knob led

### ISSUE THREAD

**Issue by Dapox11** [bigtreetech/BIGTREETECH-TouchScreenFirmware#1999]
Hello!

I want to make an encoder backlight on the board. (knob led) (Like TFT35 E3 V3.0)
Is it possible? Need to add missing LEDs and line driver (already done)
And modify the firmware. 
If you add the following lines to the pin_TFT35_V3_0.h file:

#define LED_COLOR_PIN PC7
#define WS2812_FAST_WRITE_HIGH() GPIOC->BSRRL = 1<<7
#define WS2812_FAST_WRITE_LOW()  GPIOC->BSRRH = 1<<7
#ifndef NEOPIXEL_PIXELS
  #define NEOPIXEL_PIXELS 4
#endif

then the display stops working.

What am I doing wrong? Entering the wrong pin?

**Comment by bigtreetech** [comment]
You can update the firmware of TFT35 E3 V3.0 directly. TFT35 MZ V3.0 and TFT35 E3 V3.0 are the same in software.

**Comment by oldman4U** [comment]
Any news @Dapox11?

**Comment by Dapox11** [comment]
The firmware is installed (TFT35 E3 V3.0 ), tft display works fine, but knob backlight still doesn't work(

**Comment by oldman4U** [comment]
I have a E3 version so I can not help. Sorry. 

What is the MZ version?

**Comment by Dapox11** [comment]
It’s tft35 v3.0 for anycubic mega zero
https://www.amazon.com/BIGTREETECH-Graphic-Display-Dual-Mode-Printer/dp/B08L9FBPMS

**Comment by oldman4U** [comment]
According to the pictures I found at the link, this TFT does not have LEDs like the E3 version. ![image](https://user-images.githubusercontent.com/54359396/123535888-6437b180-d727-11eb-9ba3-c5a5c34b0a7a.jpeg)

This is missing and I do not believe that they are somewhere else.

![image](https://user-images.githubusercontent.com/54359396/123535903-816c8000-d727-11eb-94de-e81089afc64e.jpeg)

Maybe it would be best to contact a printer related user group.

Happy printing

Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by Dapox11** [comment]
In the first post I indicated that I installed the missing items (LEDs and line driver). Maybe something else is missing.

**Comment by oldman4U** [comment]
@radek8

Do you know if it is possible to add leds like this? As far as I know this code only works with BTT TFT43 and bigger.

**Comment by radek8** [comment]
Can you take a detailed photo of the  TFT35 V3.0 MZ display  board from both sides?

**Comment by oldman4U** [comment]
The link above provides a good overview of the hardware. As far as I know even the E3 variant does not provide external neopixel support.

**Comment by radek8** [comment]
This is not the support of an external neopixel, but the illumination of the knob, which in the TFT35 E3 V3 variant is made by a neopixel

**Comment by oldman4U** [comment]
This TFT has no on board led and the user installed external hardware for this and want to control it via pc7.

**Comment by Dapox11** [comment]
Detailed photo of the TFT35 V3.0 MZ display board from both sides i will do it later, the printer is in operation now.

The following components are installed:
U7: 74LVC1G125 SOT23-5
LED4 LED6 LED8 LED10: WS2812-2020

![image](https://user-images.githubusercontent.com/86003215/123765566-aad40a00-d8e7-11eb-889f-14ac3113787f.png)
![image](https://user-images.githubusercontent.com/86003215/123765772-dd7e0280-d8e7-11eb-891a-e9484173ac19.png)

Also installed short the red sides of switch S2:

![image](https://user-images.githubusercontent.com/86003215/123765838-ed95e200-d8e7-11eb-9a88-b160e898edd9.png)

**Comment by Dapox11** [comment]
Owners of TFT35-E3 V3.0, please take a detailed close-up photo of the marked area? Thanks!

![image](https://user-images.githubusercontent.com/86003215/123766381-7876dc80-d8e8-11eb-8a35-d4f65522898c.png)

**Comment by oldman4U** [comment]
![image](https://user-images.githubusercontent.com/54359396/123835249-9d7b4780-d908-11eb-8450-d876c83dfce1.jpeg)

![image](https://user-images.githubusercontent.com/54359396/123835299-a835dc80-d908-11eb-958d-720af88f04d0.jpeg)

**Comment by Dapox11** [comment]
At the moment, the behavior is that one LED flashes green when turned on:

https://user-images.githubusercontent.com/86003215/123900268-95fc8280-d98a-11eb-991d-6dff93a06c3e.MOV

![image](https://user-images.githubusercontent.com/86003215/123900443-e70c7680-d98a-11eb-9ff9-b834c7ebd164.png)

**Comment by Dapox11** [comment]
Thank you all, I figured it out! The main error was in the wrong setting of the S2 jumper. Special thanks for the photo of the board. Problem solved, everything works!

![123765838-ed95e200-d8e7-11eb-9a88-b160e898edd9](https://user-images.githubusercontent.com/86003215/124459134-a60fca00-ddaf-11eb-9b39-a12e58042c83.png)
![Vq3n2jQ9GS8](https://user-images.githubusercontent.com/86003215/124459292-d48da500-ddaf-11eb-9e57-d44ffb971c37.jpg)
![4iDoPL7uMQI](https://user-images.githubusercontent.com/86003215/124459309-d8b9c280-ddaf-11eb-8eaa-8f3de16ddf46.jpg)
