### ISSUE TITLE
 Purge more resets board (BIGTREE_TFT35_V3.0_E3.27.x.bin)

### ISSUE THREAD

**Issue by JosemiZubi** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2001]
When loading in new filament and a request is made to purge more the board resets.

This problem happens since I have updated to firmware BIGTREE_TFT35_V3.0_E3.27.x.bin.

Is it possible that this new firmware is the cause of this behavior?

Thanks in advance.

**Comment by kisslorand** [comment]
Update your Marlin.

**Comment by oldman4U** [comment]
If you have a STM32 based mainboard, this is related to the old Marlin firmware you use. 2.0.8.1 is the minimum Marlin version mentioned in config.ini and ReadMe and it would be important to read the information provided before opening a ticket. Like mentioned in the Read me before posting a New Issue! also on the front page of this repository.

Please close this ticket

**Comment by JosemiZubi** [comment]
O.K.
Thank you for your answers. Checking yesterday on the web I drew that conclusion and now it is confirmed.
Thanks a lot!!!
