### ISSUE TITLE
No manual levelling after updating,

### ISSUE THREAD

**Issue by tonymrchip** [bigtreetech/BIGTREETECH-TouchScreenFirmware#201]
I can only see the bt touch icons, no manual levelling icons, is this a bug..

**Comment by oldman4U** [comment]
Hi tonymrchip.

To get the 4 manual levelling buttons, you have to disable BLTouch support in the firmware of the TFT. At least this is how it works with the TFT28.

Hope this helps

Georg

**Comment by guruathwal** [comment]
@tonymrchip you need to enable Unified Menu to see both Manual leveling and ABL.

**Comment by guruathwal** [comment]
@tonymrchip if your problem is solved. Please close the issue.

**Comment by tonymrchip** [comment]
Enabled Unified menu and problem solved, thank you...
