### ISSUE TITLE
[Q] Marlin UI with TFT35? 

### ISSUE THREAD

**Issue by JohnnyTheOne** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2025]
Is it possible to use Marlin UI with TFT35?

**Comment by oldman4U** [comment]
A TFT35 with or without encoder wheel?

**Comment by JohnnyTheOne** [comment]
With v3

**Comment by oldman4U** [comment]
TFT35 v3 has an encoder wheel and supports Marlin emulation mode.

How is this related to the TFT firmware?

**Comment by JohnnyTheOne** [comment]
it's more about hardware that support MarlinUI touch mode.

**Comment by oldman4U** [comment]
BTT TFT's support Marlin through encoder knob.

**Comment by radek8** [comment]
> it's more about hardware that support MarlinUI touch mode.

does not support

**Comment by JohnnyTheOne** [comment]
will it be in the future?

**Comment by oldman4U** [comment]
In case a user is willing to spend his time developing it - yes.

What would be the benefit compared to the current interface?

**Comment by JohnnyTheOne** [comment]
Most important configuration in one place

**Comment by oldman4U** [comment]
So to be able to change a configuration in one place you need a Marlin interface with touch screen and not using an encoder knob?

Which settings and how often do you change them?

**Comment by oldman4U** [comment]
Would you please be so kind and answer my questions above. Thank you

**Comment by JohnnyTheOne** [comment]
In general it is better that the config is in one place. Marlin and BTT firmware are constantly updated, if my printer info changes every now and then I have to update firmware on both. if I change something a value I have to do it in two places that should not be necessary.
If BTT gets info from marlin without double config that would be nice. in marlin simulator and marlinUI it is.


`Would you please be so kind and answer my questions above. Thank you`
It was weekend

**Comment by radek8** [comment]
But TFT is not stored by marlin parameters.
TFT reads Marlin parameters when turned on.

**Comment by oldman4U** [comment]
Marlin is for the mainboard and this firmware is for the TFT. There are already some commands in use where the TFT reads parameters from Marlin and I am sure there will be more in the future.

The TFT firmware allows to configure all parameters in a single file using a simple text editor without the need to compile any software. Not sure there is an easier way to handle this. Have you asked for the same in the Marlin repository?

**Comment by JohnnyTheOne** [comment]
I keep using marlin simulator with BTT TFT V3.0 without touch mode.

Thanks for your time and explanation.

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by JohnnyTheOne** [comment]
It concerns the same parameter in two different files

**Comment by radek8** [comment]
which parameter specifically?

**Comment by radek8** [comment]
All printer parameters are stored on the Marlin board in EEPROM.
The TFT display reads them when the printer is turned on and can edit them.
When the printer is turned off, the TFT is forgotten. It does not have its own EEPROM for storing MARLIN parameters.
TFT only stores its own display parameters.
If you are missing an important parameter on the TFT, a programmer may try to make this parameter available in touch mode.

**Comment by radek8** [comment]
If you edit a parameter in the simulated Marlin environment, the parameter also automatically changes in the touch mode display.
And vice versa.

**Comment by JohnnyTheOne** [comment]
@radek8 I will ask my question differently. is it possible to use MarlinUI with BTT TFT V3 hardware? in addition to marlin simulator and BTT TFT firmware or instead. answer to this is no or maybe later. 

`which parameter specifically?`
All parameters
`If you are missing an important parameter on the TFT, a programmer may try to make this parameter available in touch mode.` 
I appreciate that

**Comment by radek8** [comment]
The TFT display with this firmware does not support MarlinUI.
You would have to create a new FW with MarlinUI support
