### ISSUE TITLE
[FR] Version Revision Management

### ISSUE THREAD

**Issue by Wombat37** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2033]
I recently seem to have got involved in the reporting and testing of a few issues with this firmware - and I am pleased to help.

However, now my PC is filling up with different versions of this firmware, some released some in development - all with the same file name!

Can we somehow identify these different versions? I suggest we include the commit number in the file names. Or is there some other way the developers are able to tell the version of a particular firmware build by looking at it?

**Comment by radek8** [comment]
https://docs.github.com/en/desktop/installing-and-configuring-github-desktop/installing-and-authenticating-to-github-desktop
Use GitHub desktop.

**Comment by radek8** [comment]
You'll only have one copy. You always see what PR it contains.

**Comment by Wombat37** [comment]
OK - thanks for this.

I thought there must be a way!

I'll close this issue.

**Comment by radek8** [comment]
https://desktop.github.com/
