### ISSUE TITLE
[BUG] TFT35 V3.0 Calibration

### ISSUE THREAD

**Issue by ShiJuuRoku** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2051]
### Description

After performing the screen calibration, it seems that there is a problem with the Y axis in the lower left part of the screen

### Steps to reproduce

1. Update TFT Firmware to 0.27
2. Calibrate the screen
3. Touch the 'Menu' icon, at lower left part of the screen

**Expected behavior**
Go to menu

**Actual behavior**
When touching at the top of the icon > go to "Heat' panel
When touching at the middle of the icon > nothing
When touching at the  bottom of the icon, at the edge of the screen> go to the 'Menu' panel

### Hardware Variant
BTT TFT35 V3.0
### TFT Firmware Version & Main Board Firmware details
BIGTREE_TFT35_V3.0.27.x.bin

### Additional Information
* Include a ZIP file containing your `Configuration.h` or use [Pastebin](https://pastebin.com/) and paste a link in this issue.
* Provide pictures or links to videos that clearly demonstrate the issue.

**Comment by radek8** [comment]
Try a new calibration using the stylus

**Comment by ShiJuuRoku** [comment]
Trying multiple times, it's not better.

Again, the issue append only with the bottom left part of the screen.
The right part working perfectly.

It's weird, maybe the problem comes from the calculation of the coordinates ?

The calibration need only 3 points : top-left , top-right, bottom-right (then center to check consistency)

**Comment by radek8** [comment]
Did it work well with the older version of FW?

**Comment by ShiJuuRoku** [comment]
Not working with  0.25 version : BIGTREE_TFT35_V3.0.25.bin

**Comment by radek8** [comment]
Then there is the HW problem with the touch layer. Return the display to the seller for a complaint.
The display FW is OK.

**Comment by radek8** [comment]
Have you tried the reset file.txt?

**Comment by ShiJuuRoku** [comment]
Yes i tried with the reset.txt file, and with the calibration option into the menu.

The screen worked with the stock FW when i bought it.

**Comment by radek8** [comment]
Did you use the correct HW FW versions?

**Comment by ShiJuuRoku** [comment]
Yes, I was taking this file : BIGTREE_TFT35_V3.0.27.x.bin

**Comment by radek8** [comment]
And what's your display?

**Comment by ShiJuuRoku** [comment]
![IMG_20210709_192604__01](https://user-images.githubusercontent.com/3122358/125115543-c0b5ac00-e0eb-11eb-9493-66cc6aa225dd.jpg)

**Comment by oldman4U** [comment]
This is the correct firmware for this TFT. Have you been able to solve the problem? What was the original firmware version and have you tried that version?

**Comment by ShiJuuRoku** [comment]
Ok, maybe it an HW issue ..
I don't know what is the original firmware, a bought the screen 2 years ago.

**Comment by oldman4U** [comment]
Looks like a hardware issue. Retry what is written in the Readme with external power. If this does not help the hardware is likely broken.

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
