### ISSUE TITLE
TFT 24 V1.1 In Touchscreen Mode not interactable?

### ISSUE THREAD

**Issue by kazuimis** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2053]
Good day to all, I have recently added BTT TFT24 V1.1 to my Artillery Sidewinder X1 which uses MKS GENL as I would like to have the dual features that BTT TFT has. I have sucessfully updated the firmware and able to do adjustments to get into Marlin mode. However when I want to use the Touch Display mode, for some odd reason I can interact with the UI.

Anyone could share with me is there a portion I should check to allow the interaction with the UI? I thought maybe my TFT touch display may have issue, but I allowed the interface to idle where the screen turns dim and when I interacted it brightens back. What is happening?

[Firmware used.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/6796824/Firmware.used.zip)

**Comment by radek8** [comment]
Send photos of the involvement. Send the Marlin configuration.

**Comment by oldman4U** [comment]
Read the Readme and there especially the trouble shoot section.

**Comment by kazuimis** [comment]
![IMG_3031](https://user-images.githubusercontent.com/29127126/125231661-c094f680-e30d-11eb-823b-8a5b35fabe51.JPG)

![IMG_3032](https://user-images.githubusercontent.com/29127126/125231652-bb37ac00-e30d-11eb-91e8-f2859bdbce55.JPG)
![IMG_3033](https://user-images.githubusercontent.com/29127126/125231619-afe48080-e30d-11eb-8973-41662b746315.JPG)

[Marlin Configuration used.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/6798594/Marlin.Configuration.used.zip)

I went to look at the Readme section as well but not too sure if I have missed an info or not, @oldman4U mind if you could share which poertion you are reffering to?

@radek8 I have uploaded som images as well as the Marlin config I'm using!

**Comment by radek8** [comment]
The display says Ready. So it's connected. What's your problem?

**Comment by radek8** [comment]
Did you use the Reset file.txt?

**Comment by oldman4U** [comment]
Like I wrote above. Troubleshooting.

But what is your problem? What happens when you press a button?

**Comment by kazuimis** [comment]
@oldman4U When I pressed it, it does not respond to bring me to menu etc in touch screen mode.

@radek8 I just name an empty .txt file as Reset right?

**Comment by oldman4U** [comment]
Do what is written in the ReadMe under Troubleshooting.

**Comment by kazuimis** [comment]
Hi @oldman4U I have tried again on the Rese.txt and some how it worked 👍 not guessed like you mentioned keep trouble shoot! And thanks @radek8 I have fixed it.
