### ISSUE TITLE
What could go wrong with the TFT70 display?

### ISSUE THREAD

**Issue by AntoszHUN** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2072]
I recently got a TFT70 display from you.

The displayed image is not good. Confused.
I have another TFT70 display. I also took a picture of it. The worse pictures were taken from the newer display.
What makes the display so confusing? It is visible in all areas. Gray, red, green, blue. The color doesn't matter. If I look a lot my eyes get confused too.
Could it be a software or hardware failure?

![NEW_TFT70_03](https://user-images.githubusercontent.com/45710979/126890804-dac8423a-5a22-4013-9e80-cf3770cb0716.JPG)
NEW_TFT70_03

![OLD_TFT70_02](https://user-images.githubusercontent.com/45710979/126890805-965d0515-d64e-4490-bd54-4cf5c5fc7b34.JPG)
NEW_TFT70_04

![NEW_TFT70_02](https://user-images.githubusercontent.com/45710979/126890806-db60eff7-51f2-40fd-ace5-4de83b43406e.JPG)
NEW_TFT70_02

![OLD_TFT70_00](https://user-images.githubusercontent.com/45710979/126890810-c3217b32-25c5-46a1-9684-861d91b8933f.JPG)
OLD_TFT70_00

![NEW_TFT70_00](https://user-images.githubusercontent.com/45710979/126890812-00f1292e-6d2c-4bc3-b6a0-3ce9bb574d4e.JPG)
NEW_TFT70_00

![NEW_TFT70_01](https://user-images.githubusercontent.com/45710979/126890814-9ad465aa-2214-4e92-90f3-abae57e59da8.JPG)
NEW_TFT70_01

![OLD_TFT70_01](https://user-images.githubusercontent.com/45710979/126890816-b302e563-2bce-47d2-8591-2baf85fa58e8.JPG)
OLD_TFT70_01

Made by: AntoszHUN

**Comment by oldman4U** [comment]
How can this be firmware related when you use the same firmware with different results on 2 pieces of hardware?

Try standard Icon theme to see if you get different results also.

**Comment by AntoszHUN** [comment]
> 
> 
> How can this be firmware related when you use the same firmware with different results on 2 pieces of hardware?
> 
> Try standard Icon theme to see if you get different results also.

It doesn't matter which icon theme I use. The image on the display is so bad. I hope you can see the difference. The last two pictures are well reproduced. Is the error not software?

**Comment by digant73** [comment]
Try to unplug the display flat cable, clean the contact part of the cable and the connector and plug the cable

**Comment by AntoszHUN** [comment]
> Try to unplug the display flat cable, clean the contact part of the cable and the connector and plug the cable

I'm beyond that. I've tried everything. I also looked at the solderings. :(

**Comment by oldman4U** [comment]
You have 2 displays. Replace the one which looks good with the faulty one and make sure both use the same firmware.

**Comment by AntoszHUN** [comment]
> You have 2 displays. Replace the one which looks good with the faulty one and make sure both use the same firmware.

They both have the same firmware.

**Comment by oldman4U** [comment]
Which brings me back to my very first question...

**Comment by AntoszHUN** [comment]
> 
> 
> Which brings me back to my very first question...

I was just wondering if anyone else had encountered the error.

**Comment by radek8** [comment]
It seems that BTT has more component suppliers, including LCD panels, and the quality is different. It looks like a poor quality LCD panel.
It was also visible in the trouble they had with SKR V2. In the event of a MOSFET supply failure, they used other types and then it burned ...

**Comment by AntoszHUN** [comment]
> 
> 
> It seems that BTT has more component suppliers, including LCD panels, and the quality is different. It looks like a poor quality LCD panel.
> It was also visible in the trouble they had with SKR V2. In the event of a MOSFET supply failure, they used other types and then it burned ...

Yes. And that's a big problem. Many will buy elsewhere because of such mistakes. I do not. Because I want to solve problems. The only problem here is the lack of detailed testing.
