### ISSUE TITLE
[FR] hide/remove file extension (.gcode)

### ISSUE THREAD

**Issue by discip** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2074]
**Is your feature request related to a problem? Please describe.**
Since most screens are relatively small, the file names can get very long.
I do not see any benefit of displaying the file type/extension.

**Describe the solution you'd like**
I think it would look even cleaner, if the extention **`.gcode`** was hidden.

file name before   |   |  file name after
-|-|-
*example.gcode*|**=>**|*example*

**Comment by oldman4U** [comment]
Is there any disadvantage by showing the file extension?

**Comment by discip** [comment]
What kind of disadvantage do you have in mind?
I do not know, if I am the only one, but I prefer it to have clean and concise UIs. 😁
Does anyone use files that do have extensions other than **`.gcode`**. 🤷‍♂️
If that is not the case, why should precious space be cluttered with useless *'information'*?
I hope, I made my point clear this time. 😅

**Comment by kisslorand** [comment]
What if there are users who use different extensions? "NylonClip.1mm", "NylonClip.5mm", "NylonClip.12mm", etc
There are millions of users, you never know what filenames do they use.

**Comment by discip** [comment]
@kisslorand
That's exactly what I asked about in the last post. 🤭

The least I want, is to box someone in.

I am sure there is a way to only remove the **`.gcode`** extension.
And furthermore one more option in the **`config.ini `** could make this feature optional. 😁

regards

**Comment by Hukuma1** [comment]
+1 for the option to hide in `config.ini`. "Hide known extensions"

**Comment by kisslorand** [comment]
What would those extensions be?

**Comment by Hukuma1** [comment]
hide.extension="gcode,1mm,5mm,12mm"

Let users fill it in?

**Comment by kisslorand** [comment]
I meant what would be those _**known**_ file extensions?

**Comment by Hukuma1** [comment]
Just stick in `gcode` and the ability to add more manually please.

**Comment by kisslorand** [comment]
I guess `gco` could be in that list as well.

**Comment by discip** [comment]
@kisslorand
Good evening Sir,
are we allowed to expect a PR on this one any time soon? 😁
No offense.

kind regards

**Comment by kisslorand** [comment]
I spent two hours on this and actually the work needed for this outweighs its benefit. If needed, I can explain it why but that will not change the fact that it is not as easy at it seems.
So I will leave this to other developer to implement it if he/she has some spare time to spend on this.

**Comment by discip** [comment]
@kisslorand
Good evening Sir,
thank you very much having tried getting this done. 👍
Maybe someone else has a simpler (not as time consuming) solution for this.

**Comment by kisslorand** [comment]
> Maybe someone else has a simpler (not as time consuming) solution for this.
 That is quite possible!

**Comment by discip** [comment]
@digant73
## Thanks a ton! 👍🥇

kind regards
