### ISSUE TITLE
[BUG] (short description)level corners fails after new update

### ISSUE THREAD

**Issue by BobCraig10** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2077]
### Description
I just updated the tft35v3 firmware, after updating, and trying to level the corners in the ABL menu, the BL Touch fails on the 3rd probe. it says probe failed. When the bed id being probed the pin doesnt stow with the new firmware. On the 3rd corner probe, the BL touch stays red, even after the probe touches the bed. 

### Steps to reproduce

1. [First Step]go to abl menu
2. [Second Step] click on L Corner
3. [and so on...] Click start

**Expected behavior**
I expect it to successfully probe 4 corners

**Actual behavior**
when it gets to the right rear corner, the bl touch stays red when the probe touches the bed, and gives an error on screen "probe failed"

### Hardware Variant
tft35 v3
### Additional Information
* Include a ZIP file containing your `Configuration.h` or use [Pastebin](https://pastebin.com/) and paste a link in this issue.
* Provide pictures or links to videos that clearly demonstrate the issue.

I went back to the previous firmware for the tft35 v3, and the issue is gone

**Comment by oldman4U** [comment]
Previous and new means exactly what?

**Comment by BobCraig10** [comment]
> Previous and new means exactly what?

The firmware for the tft35v3 is showing here that it was updated 3 days ago.  Which is new to me.   Previous is the one before that which I had saved on my harddrive. from a month ago.  bin, config, and language/icon pack

**Comment by oldman4U** [comment]
It would be important to know the exact PR which broke it.

**Comment by radek8** [comment]
I have the last compilation, and this feature works without errors.

**Comment by radek8** [comment]
Can you send a video?

**Comment by digant73** [comment]
the bug was introduced by some changes in LevelCorner in #2047. Those changes were also the origin of Radek's PR #2066.
The bug is fixed in PR #2073 (the old code not affected by the bug is restored)

**Comment by BobCraig10** [comment]
> Can you send a video?

I can reload the version with the issue back on my machine if you need later tonight. I have some prints going right now that I can't disturb, but I could do it in a couple hours if needed.

**Comment by BobCraig10** [comment]
> the bug was introduced by some changes in LevelCorner in #2047. Those changes were also the origin of Radek's PR #2066.
> The bug is fixed in PR #2073 (the old code not affected by the bug is restored)

This means you found the issue and I don't need to re load that version to get a video? Thanks.

**Comment by BobCraig10** [comment]
Thank you everyone. It was great to see how the issue was jumped on right away. I'm sorry I wasn't more clear about which versions I was using.   I only saw the dates, and the main firmware numbers, not the bugfix? numbers.
