### ISSUE TITLE
[BUG] [ABL] Bad display for negative values 

### ISSUE THREAD

**Issue by GregSKR** [bigtreetech/BIGTREETECH-TouchScreenFirmware#208]
In Unified Menu, when going in ABL menu then [Offset] or [Babystep], negatives values are not displayed correctly.
eg: -1.26 is displayed  .260 (no negative sign, no value before the point)

**Comment by Hukuma1** [comment]
![zbug](https://user-images.githubusercontent.com/54511555/69923102-e7632980-1456-11ea-85bd-fb9130b6cbcd.jpg)

Got the same thing. -1.75 shows up as .750

TFT35 V3 with latest firmware. Was not brave enough to test a print to see if it's just cosmetic bug. :P

**Comment by guruathwal** [comment]
Its just a glitch.. it will not affect your print..

**Comment by GregSKR** [comment]
Yes, just a glitch for sure. But very confusing when using those functions!
I hope a programmer will give a look at it...

**Comment by billydragon** [comment]
I fixed this by edit  ProbeOffset.c :

#define PROBE_OFFSET_MAX_VALUE 20.0f             //My Chiron Probe Offset large then 16mm
#define PROBE_OFFSET_MIN_VALUE -20.0f           //

void showProbeOffset(void)
{
  GUI_DispFloat(CENTER_X - 5 * BYTE_WIDTH / 2, CENTER_Y, probe_offset_value, 3, 2, RIGHT);
}
void probeOffsetReDraw(void)
{
  GUI_DispFloat(CENTER_X - 5 * BYTE_WIDTH / 2, CENTER_Y, probe_offset_value, 3, 2, RIGHT);
}


and Babystep.c:

#define BABYSTEP_MAX_VALUE 5.0f
#define BABYSTEP_MIN_VALUE -5.0f

void showBabyStep(void)
{
  GUI_DispFloat(CENTER_X - 5*BYTE_WIDTH/2, CENTER_Y, baby_step_value, 3, 2, RIGHT);
}
void babyStepReDraw(void)
{
  GUI_DispFloat(CENTER_X - 5*BYTE_WIDTH/2, CENTER_Y, baby_step_value, 3, 2, RIGHT);
}

re- compile firmware then this gone, display correct negative value.

**Comment by extesy** [comment]
@billydragon can you send a pull request for this fix?

**Comment by billydragon** [comment]
I'm new in github, i don't know how to pull request do

**Comment by extesy** [comment]
@billydragon https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by billydragon** [comment]
Pull request done

**Comment by GregSKR** [comment]
Great, thanks guys!
