### ISSUE TITLE
   [Q] (Your Question?)

### ISSUE THREAD

**Issue by Medjeberabdou** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2083]
hi
can i used servomotor panasonic with bigtreetech skr e3 v2.0 !? and how !!

**Comment by oldman4U** [comment]
This is the BTT TFT firmware repository and not a SKR user group.

Please help the community and close this ticket. Thank you

**Comment by oldman4U** [comment]
@Msq001

Please close this ticket. 

Thank you
