### ISSUE TITLE
[Q] (Is there a way to show the chamber temp on tft50 in touch mode. Using the latest version of firmware

### ISSUE THREAD

**Issue by Tezzatron81** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2085]
**Your question or details you need. Please describe.**
Is there a way to show the chamber temps and heating from the main info screen on tft50. I can only see it in marlin mode

**specify the device variant related to your question.** btt tft50v3

**Additional context**
Add any other context or screenshots about the question here.

**Comment by radek8** [comment]
actual temperature and target temperature of CHAMBER will be displayed on the top title bar.
It has once been a demand to change the display with the temperature of the bed. It has not been implemented yet.
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/1182

**Comment by Tezzatron81** [comment]
Do u mean while its printing it shows?

**Comment by radek8** [comment]
no

**Comment by oldman4U** [comment]
PR #2084

Please test and let us know.
