### ISSUE TITLE
[BUG] v27 Flashing Screen SKR2

### ISSUE THREAD

**Issue by somejavadev** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2086]
### Description

On the SKR2 rev B board connecting the TFT35 E3 version works fine on the v26 release https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/releases/tag/Vx.x.26 but upgrading to the latest master or v27 release causes the screen to flash black and white after a successful upgrade. After adding the `reset.txt` file the printer boots up and shows the calibration screen, after completing the calibration the screen goes back to flashing, this time the controller/dial light is on which wasn't on before. Having a look at the SD card the files have all been renamed to `.CUR`

### Steps to reproduce

1. Connect the TFT35 E3 v3.0 to the SKR2 (EXP1,EXP2 and TFT)
2. Add the the content of the attached zip (folder: sd-card-content-for-upgrade) to a SD card and perform the upgrade of the TFT
3. Wait for the upgrade to be complete.
4. The screen will start flashing. The flashing is almost like the backlight turning on and off constantly.
5. Turn off the printer and add a `reset.txt` file to the SD card
6. Turn on the printer and notice the calibration screen without any flickering.
7. Complete the calibration and notice the flicker/flashing starts again. 

**Expected behavior**

There shouldn't be any flickering and the display should be usable on the latest version of the firmware.

**Actual behavior**

The display flickers/flashes and is unusable.

### Hardware Variant

TFT35 E3 v3.0

### TFT Firmware Version & Main Board Firmware details

Working version: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/releases/tag/Vx.x.26
Not working version: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/releases/tag/Vx.x.27 or current master branch

Mainboard: SKR2 Rev B

Marlin 2.0.8.2

### Additional Information
* Include a ZIP file containing your `Configuration.h` or use [Pastebin](https://pastebin.com/) and paste a link in this issue.
* Provide pictures or links to videos that clearly demonstrate the issue.

I have both EXP1 and EXP2 cables as well as the TFT cable connected as per SKR2 documentation.    
I am trying the Unified Theme.    

[debug.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/6911769/debug.zip)

SD Card After upgrade:

![image](https://user-images.githubusercontent.com/6507120/127751862-78860ea1-c10e-406f-9bb0-882e6ffa1562.png)
  
Video of Firmware Upgrade:   

https://user-images.githubusercontent.com/6507120/127752290-f8a606fa-f2bd-4fd3-a1a6-8e490a2c2674.mp4
  
Video of `reset.txt` boot up:
 
https://user-images.githubusercontent.com/6507120/127752182-1303b8f3-06c3-4cef-8cb9-a448790f6616.mp4

**Comment by oldman4U** [comment]
Disconnect the currently connected cables and connect external power, like described in the Troubleshooting section of the ReadMe: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware#troubleshooting

**Comment by somejavadev** [comment]
@oldman4U I can fix this by uploading the older firmware to the SD Card and "upgrading" it back to v26, how do I get the latest firmware to work, the v26 on the releases page is nearly 1 year old and there has been a number of improvements since then.

**Comment by somejavadev** [comment]
@oldman4U closing this issue the EXP1 and EXP2 cables were swapped around causing this. Only strange thing is the display was working fine on v26.
