### ISSUE TITLE
[BUG] TFT35 GD firmware update error

### ISSUE THREAD

**Issue by poumsoon** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2090]
There was a bug in the tft35 GD v2 version firmware, so I tried to update it.
However, it does not proceed in the "Deleting old ROOT_DIR...." step.
![image](https://user-images.githubusercontent.com/3367969/127801616-f7b8bbac-9959-4501-a38b-a50c545c7cef.png)

**Comment by radek8** [comment]
How is the GD version different from standard vefze 2.0?
You may need to upload a new bootloader.

**Comment by bigtreetech** [comment]
Hello, Please try to create a file named “reset.txt” in the SD card root directory to reset all the parameter settings.

**Comment by oldman4U** [comment]
@bigtreetech I am sure a user reads the ReadMe before he opens a ticket here...;-) What is the difference to the standard TFT35 v2?

**Comment by poumsoon** [comment]
Yes, the firmware update was successful.
thanks for the quick fix
In the future, we hope that new product buyers will not become bug testers.

**Comment by radek8** [comment]
> Yes, the firmware update was successful.
> thanks for the quick fix
> In the future, we hope that new product buyers will not become bug testers.

What bug fix do you mean?
