### ISSUE TITLE
[BUG] print file selection doesn't work

### ISSUE THREAD

**Issue by alfrankgit** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2103]
### Description

In the Print Menu on the TFT35 I can't select any file on any SD card. 
They are all properly listed but when I tap one nothing happens.

### Steps to reproduce

1. Using mainboard SKR-V1.4 and TFT35 (V1.2 or V3.0 or B1 V3.0, doesn't matter)
2. Fresh Marlin (2.0.9.1 or 2.0.8.2, doesn't matter) built from scratch.
3. With all options activated as listed here in your Marlin dependencies.
4. Flashed firmware.bin, BIQU_TFT35_V1.2.27.x, TFT35 folder, config.ini on board and display.
5. Display states "3DPrinter Ready".
6. Tap "Print" icon.
7. Tap "TFT SD" or "OnboardSD", doesn't matter.
8. Files on the SD are properly listed.
9. Tap one of the filenames.

**Expected behavior**
Print of the selected file starts or requester comes up to confirm that.

**Actual behavior**
Nothing visible at all.
In fact, if I tap a filename more than once it seems to just compose a path out of it.
Then I have to tap the "Back" icon several times to actually got back in the menu.

### Hardware Variant
1. TFT35 (V1.2 or V3.0 or B1 V3.0, doesn't matter)
### TFT Firmware Version & Main Board Firmware details
TFT V27.x, Marlin 2.0.8.2 or 2.0.9.1

### Additional Information
![IMG_3641](https://user-images.githubusercontent.com/54467840/128495507-ba21c68d-0da6-4dc1-911a-49d2d4f022ac.jpg)
![IMG_3640](https://user-images.githubusercontent.com/54467840/128495518-eb50c2c4-bb78-4cd1-b98d-0437da02a285.jpg)
[Archiv.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/6944831/Archiv.zip)
[config.ini.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/6944835/config.ini.zip)

**Comment by radek8** [comment]
Use today's updated FW.
It should be fixed.

**Comment by alfrankgit** [comment]
Wow! That was fast!

The problem is actually fixed. Thanks a lot!
