### ISSUE TITLE
[BUG] Compilation fails when UNIFORM_LIVE_TEXT_BG_COLOR is defined

### ISSUE THREAD

**Issue by Guilouz** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2104]
Impossible to compile when **#define UNIFORM_LIVE_TEXT_BG_COLOR** is defined in Configuration.h since recent PR.

![Capture d’écran 2021-08-06 à 13 22 30](https://user-images.githubusercontent.com/12702322/128503300-3dbee967-d928-41ff-9001-e9636d0cf618.jpg)

![Capture d’écran 2021-08-06 à 13 22 41](https://user-images.githubusercontent.com/12702322/128503310-b22bc346-e0f7-49fe-88f5-2737a5fe167f.jpg)

@digant73 @guruathwal

**Comment by digant73** [comment]
I fixed that issue in my incoming PR

**Comment by Guilouz** [comment]
> I fixed that issue in my incoming PR

Do you confirm it's just missing : 

const GUI_POINT printinfo_points[6] = {
  {START_X + PICON_LG_WIDTH * 0 + PICON_SPACE_X * 0, PICON_START_Y + PICON_HEIGHT * 0 + PICON_SPACE_Y * 0},
  {START_X + PICON_LG_WIDTH * 1 + PICON_SPACE_X * 1, PICON_START_Y + PICON_HEIGHT * 0 + PICON_SPACE_Y * 0},
  {START_X + PICON_LG_WIDTH * 2 + PICON_SPACE_X * 2, PICON_START_Y + PICON_HEIGHT * 0 + PICON_SPACE_Y * 0},
  {START_X + PICON_LG_WIDTH * 0 + PICON_SPACE_X * 0, PICON_START_Y + PICON_HEIGHT * 1 + PICON_SPACE_Y * 1},
  {START_X + PICON_LG_WIDTH * 1 + PICON_SPACE_X * 1, PICON_START_Y + PICON_HEIGHT * 1 + PICON_SPACE_Y * 1},
  {START_X + PICON_LG_WIDTH * 2 + PICON_SPACE_X * 2, PICON_START_Y + PICON_HEIGHT * 1 + PICON_SPACE_Y * 1},
};

**Comment by digant73** [comment]
it was renamed. I will test the fix in my PR this night
