### ISSUE TITLE
TFT35-E3 V3.0 freeze after update at selection screen

### ISSUE THREAD

**Issue by Flipsand** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2120]
![freeze_at_selection](https://user-images.githubusercontent.com/82671253/129031078-faca4a84-4746-43dc-ac0e-73aaacf2ccf7.JPG)
Hi,
i have updated my TFT35-E3 V3.0 from version BIGTREE_TFT35_V3.0_E3.26.x.bin to BIGTREE_TFT35_V3.0_E3.27.x.bin at my Ender 3. After update and restart the screen only shows the selection between Marlin mode and Touch mode. I can't use the knob or use the touch future. It seems to be frozen at this state and only shows the icons for Marlin or Touch Mode. 

What i did so far:
- Update from BIGTREE_TFT35_V3.0_E3.26.x.bin to BIGTREE_TFT35_V3.0_E3.27.x.bin (after restart screen was frozen showing Marlin and Touch Mode icon)
- Update again to BIGTREE_TFT35_V3.0_E3.27.x.bin to see if any changes happened
- Changed the config for the Default Mode with following results: [Marlin Mode: 0 - not working, Touch Mode: 1 - not working, Blocked Marlin Mode: 2 - not working, Blocked Touch Mode: 3 - working]
- So the only chance to get not frozen when starting is to select the Blocked Touch Mode in the config while it direct starts the Touch Mode, any other selections causes freeze at Marlin Mode or at selection between Marlin Mode and Touch Mode
- I also did as described here in the Troubleshooting powering the TFT with external 5V without any connection to the printer doing the update again with the same result.
- Also using a reset.txt on an empty SD Card wasn't able to help. It only recalibrates the screen without any success using the TFT Display as normal.
Any files i used for update or reset get the CUR ending or with the reset.txt the DONE ending. 

It would be very nice if anyone can guide me to get the display working again or link me to helping files that would work for the update. Or maybe it's a bug?
 
THX in advance
Flip

**Comment by abecaw** [comment]
I'm having the same problem. I'm going to compile the 27 version and flash with that. We will see what happens.

**Comment by abecaw** [comment]
Hey Flipsand..  you have to compile the firmware. That will fix the problem your having.

**Comment by Flipsand** [comment]
Hi abecaw. THX for info but i wasn't succesfull with that. Here is what i did:
 - Downloaded BIGTREETECH-TouchScreenFirmware-master.zip for use
 - in VS Code (platformio) edited in platformio.ini entry default_envs to: default_envs = BIGTREE_TFT35_E3_V3_0 and compiled
 - copied from extracted ZIP the config.ini to SD / the folder TFT35 from path "THEME_Unified Menu Material theme" to SD
   and finaly copied the compiled BIN from path ...\.pio\build\BIGTREE_TFT35_E3_V3_0\BIGTREE_TFT35_V3.0_E3.27.x.bin to SD
 - Ender 3 was off and i put my SD card into the SD slot from the TFT and started up. After TFT Update i can do calibration but after restart i still stay at the two icons to select marlin or touch with any reaction by touching the display or using the knob.

Maybe is there any way to get it fixed? Write new Bootloader or something like that to get the TFT full clear and set all new up ...i don't know....When i connect the old display the Marlin mode works without any problems.

**Comment by oldman4U** [comment]
Try another SD card <=8GB FAT formatted.

**Comment by radek8** [comment]
Perform a reset again using the reset.txt file and complete the screen calibration by clicking 4 points.

**Comment by Flipsand** [comment]
THX for info so far. 

Current Status:
-> TFT still freeze/hang at selection screen -
     no matter which combination Marlin/TFT i try (old Marlin FW and old TFT FW and so on)
-> As a bonus the TFT screen buzzer also ticks continuesly after powering up the printer

Here is what i did so far respectively did further:
- Used different SD Cards with FAT and FAT32 with different sizes all under 8GB (all could be read by the SD Slot from the TFT)
- Did reset after FW update and completed screen calibration
- Did reset after reset and so on also used for different tries the reset button at the TFT35 screen
- Did reset and uploaded after this again the config.ini
- Did upload again the full update with TFT Folder, BIN File and config File and so on
- Did this with external 5v or connected to the printer
- Used different precompiled firmware from here (26x/27x) and so on
- Used Bugfix Marlin version 2.0.8 and the up to date Marlin version 2.0.9.1 with last Fiwmare for TFT (27x)
- As last chance i went down to the formerly working combination of my Marlin vers. 2.0.6.1 and the precompiled TFT Firmware (27.08.2020 09:26 vers. BIGTREE_TFT35_V3.0_E3.26.x.bin)

The result is still and maybe finaly: I still hang in the selection screen with no reaction with touch or knob. The only thing i can use is with the 27x Firmware when i select in the INI the Blocked Touch Mode, because this is the only Mode i can boot up and use the screen. 

But badly also after power up the screen on the 3D printer after a few seconds a steady clicking (ticking) sound appears from the screen buzzer and didn't stop. That is only happening when the screen is connected to the printer. All cables were as before and also checked again to prevent a mistake. Also as a plus a message "Failed to enable Bed Leveling" is sometimes seen after Update Firmware or sometimes when power up the printer. This is only happening when using the TFT35 after i tried to update the FW to v. 27x.

So sadly even if i go back to the further working combination of my Marlin firmware and the TFT35 firmware it's not working anymore. 

Used Hardware:
Ender-3
BL Touch from Creality
Filament Sensor
Bigtreetech SKR Mini E3 TMC2209 V2.0 Ender-3 Upgrade Mainboard
BIGTREETECH TFT35-E3 V3.0 

Maybe someone still got another idea to try.
THX 
Flip

**Comment by oldman4U** [comment]
Disconnect everything from the TFT. Use a prepared USB cable to provide 5V.

Repeat with v27 precompiled FW, unchanged config.ini and TFT35 folder from unified menu and make a movie while updating the TFT until u reach the point of the reported issue. Upload the movie here.

**Comment by Flipsand** [comment]
![crimped_cable_TFT](https://user-images.githubusercontent.com/82671253/129475041-86694bb5-3dd9-4a69-bb19-a2cb688c7fb8.jpg)
![crimped_cable_TFT_connect](https://user-images.githubusercontent.com/82671253/129475045-14efb7f7-cfd8-4162-86bc-32e521dd5aa5.jpg)

Next try was successfull...yeah!!!
I made a new crimped USB cable and connected it to 5V and already had the precompiled FW with v27 uploaded before. Without any problems slections was working as there were no fault before. Connected it to the printer again without changing anything and it worked as expected. No freeze or whatever. The ticking sound was also away. It was the ticking sound when you puch the knob down for change the mode. Maybe and whyever it was stucked and to connect it to 5V again and only was the rescue for my TFT!

Thinking backwards maybe the Dupont cables wasn't enough to get the TFT connected at 5V although it powered up and also updated the FW.

I am happy again :)
Thank you all very much helped me getting my TFT back to live!
Yours
Flip

**Comment by oldman4U** [comment]
Happy printing
