### ISSUE TITLE
problem is in the compilation of the firmware

### ISSUE THREAD

**Issue by alekseylich** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2123]
![Снимок](https://user-images.githubusercontent.com/56843717/129458338-b297570c-eddb-4a77-93b1-4d43f880ac63.JPG)

**Comment by oldman4U** [comment]
No.

Your problem is PIO or (most likely) VSC related.

Please close this ticket, thank you

![Screenshot 2021-08-14 at 22 24 52](https://user-images.githubusercontent.com/54359396/129459232-e079fd63-27f1-4bb7-b2b5-b4e9c5bd1999.png)

**Comment by alekseylich** [comment]
thanks
