### ISSUE TITLE
Lot of error. [BUG] (short description)

### ISSUE THREAD

**Issue by Talha909** [bigtreetech/BIGTREETECH-TouchScreenFirmware#214]
### Description
When ever i try to compile the code its gives me lot of error message. I successfully compile the code for skr 1.3 board. But when i compile code for the tft it gives me lot of error. 
![error](https://user-images.githubusercontent.com/29024390/70148530-2d72f400-16c8-11ea-95f7-68db7a62fba8.PNG)

### Steps to reproduce
I only open the file and compile it its gave me the 42 error.

**Comment by guruathwal** [comment]
did you changed any part of the code in TFT firmware?

**Comment by arminth** [comment]
Even though you get the errors of missing braces, the code compiles fine and you find it in the .pio build folder.

**Comment by guruathwal** [comment]
@Talha909  please close the issue.
