### ISSUE TITLE
[FR] RRF Macro menu icon view support

### ISSUE THREAD

**Issue by bttguy** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2141]
In RRF the macro menu can be used like a proper ”file explorer” since we have access to unlimited macros/subfolders. With a lot of macros and folders, mainly on smaller screens the icon/grid view help with the navigation a lot. Also the option itself is welcomed.

**Describe the solution you'd like**
Enable/make possible icon mode for RRF users in the Macros menu.

@pfn Do you have any feedback on this one, is it something easy like with the print menu, or does it need some work?

**Comment by pfn** [comment]
Thought this would be easy, it isn't quite a one-liner. This is gonna sit for a while  :D

**Comment by bttguy** [comment]
@pfn Sure thing. The other FR-s of mine also sit for a while and than you came :) I am patient with these quality of life improvements. Also @bigtreetech/@Msq001  could take a look on these, since this is just an UI feature, and dont require any special testing/knowledge about RRF, at least as far as I know.

**Comment by bttguy** [comment]
@digant73 can you help us to implement this feature? With the newely added encoder scrolling it wolud be more useful.

**Comment by bttguy** [comment]
@bigtreetech @digant73 can you help us to implement this feature? With the newely added encoder scrolling it wolud be more useful

**Comment by bttguy** [comment]
Any update or plan on this FR @bigtreetech @digant73? :)

**Comment by oldman4U** [comment]
But you understand that not BTT writes the firmware but users like you and me spending their spare time to improve this project?

Maybe you could help and improve the ReadMe by adding helpful information.

**Comment by bttguy** [comment]
@digant73 or @pfn Could you help sort this FR out? It sat for a while now ;) Pretty please, lets reduce the open issue count :)

**Comment by HaasNL2** [comment]
I amde an excel file to add my custom macro's would be way more handy if i could just put it in a folder.
Also the fact I have custom macro's in the configuration.h and in the config.ini is confusing.
