### ISSUE TITLE
Shadow characters in Layer-field

### ISSUE THREAD

**Issue by brutzler** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2144]
![TFT](https://user-images.githubusercontent.com/8457600/131242285-98a4b696-5430-44dc-9f5e-9675ec9ff701.jpg)

### Description

When you printed a part with layer hight more than 10mm, and after this you start a new print, then the field where the actual layer ist displayed, still has the last (longer string) in background.

Its no such big bug. See it as feedback to enhance your software :-) 

### Hardware Variant

BIGTREETECH_TFT35_V3.0
### TFT Firmware Version & Main Board Firmware details

TFT35_V3.0.27.x Aug 22 2021
Marlin 2.0.9.1

**Comment by kisslorand** [comment]
@brutzler
Check please PR #2152?

**Comment by brutzler** [comment]
Still on vacation for 2 more weeks....
Will test after back home again.
Silly question: Is there somewhere the file with the changes from you? Or do I have to change my sources?
