### ISSUE TITLE
2 day old upload nothing works

### ISSUE THREAD

**Issue by Kelliamandahoward** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2157]
went to update firmware on new screen get found outdated data error 

fonts :update required
config: update required
language: ok (its literally the only thing showing ok)
icons: update required

these files are only 2 days old whats wrong im super new but i tried ever  tft35 v3 file to see if that was the error and every theme to see if just the fonts and icons hadnt been updated on the one i wanted but nothing works

**Comment by kisslorand** [comment]
Did you try updating the fonts, config.ini and the icons?

**Comment by oldman4U** [comment]
Have you read the ReadMe on the first page?

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
@Msq001

Please close this ticket 

Thank you
