### ISSUE TITLE
[Q] Screenshot for documentation

### ISSUE THREAD

**Issue by xPew** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2165]
Hello there!

Thank you for accepting my theme :) I would like to ask some help how I can make a sreenshot like found in the readme for the other themes, so I can edit the readme too to include my theme.

**Comment by oldman4U** [comment]
Hi

I will update the readme soon and add your theme.

oldman

**Comment by xPew** [comment]
Oh, thank you @oldman4U!

**Comment by oldman4U** [comment]
👍🏻
