### ISSUE TITLE
[FR] (Can we get IDEX support in the TFT firmware)

### ISSUE THREAD

**Issue by muttstang** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2173]
**Is your feature request related to a problem? Please describe.**
It appears that there is no IDEX support with the TFT firmware.

**Describe the solution you'd like**
Can we get a solution for duplication, mirror, dual extrusion along with moving the extruder head, moving filament in E1, and adjusting offsets for the 2 print heads.

**Describe alternatives you've considered**

**Additional context**

**Comment by thisiskeithb** [comment]
It has already been requested: #2020

**Comment by digant73** [comment]
@muttstang as said by @thisiskeithb, your FR is a duplication of #2020. Please close this ticket and eventually post on #2020
