### ISSUE TITLE
tft50 v2.0 drivers/firmware

### ISSUE THREAD

**Issue by ac200** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2178]
i am currently trying to install a pi tft 50 v2.0 touch screen to my octoprint setup but i cannot get the screen to show anything and the pi will not boot without an external hdmi display plugged in 

i also cannot find the drivers/firmware for this screen

**Comment by oldman4U** [comment]
Hi.

This is the repository related to your hardware: https://github.com/bigtreetech/OctoBTT

The firmware in this repository is NOT compatible with your hardware!

Please close this ticket here, thank you

Happy printing

**Comment by oldman4U** [comment]
@Msq001

Please close this ticket. Thank you

**Comment by oldman4U** [comment]
@Msq001

**Comment by fridayshoes** [comment]
Where can get the drivers?
