### ISSUE TITLE
[Q] Layer Number

### ISSUE THREAD

**Issue by ramosglauco** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2184]
Hi. I have an Artillery Genius (TFT28). I'm not able to show the layer number on the print screen, only the height is shown. Do I need to use some specific gcode between layers? PS: I'm using PrusaSlicer. Tks!

**Comment by oldman4U** [comment]
Which version of the TFT firmware from this side are you using?

**Comment by ramosglauco** [comment]
> Which version of the TFT firmware from this side are you using?

@digant73 version (1.27.x Patch 4)

**Comment by oldman4U** [comment]
@digant73 

Does your repo include the code to show the layer?

**Comment by digant73** [comment]
@oldman4U yes

**Comment by oldman4U** [comment]
Ok. Can you reproduce the reported issue?

**Comment by kisslorand** [comment]
Go to:
_PrusaSlicer -> Printer Settings -> Custom G-code -> After layer change G-code_
There insert the following:
`;LAYER:[layer_z]`

**Comment by ramosglauco** [comment]
@oldman4U @kisslorand @digant73 
Got the layer number to be displayed on TFT. The correct code for PS is: 
; LAYER:[layer_num]
However two "-" are placed beside to the layer number if it is below 10. Example: "-3-". From the layer number 10 this does not happen. Is this a bug or is it correct?

**Comment by kisslorand** [comment]
> However two "-" are placed beside to the layer number if it is below 10. Example: "-3-". From the layer number 10 this does not happen. Is this a bug or is it correct?

It's a bug, I will try to correct it ASAP.

**Comment by ramosglauco** [comment]
> Also you can insert in PrusaSlicer at _Printer Settings -> Custom G-code -> Start G-code_ the following:
> `;LAYER_COUNT:[total_layer_count]` or `;LAYER COUNT:[total_layer_count]`

What are these commands in the start gcode supposed to show in the TFT? I tried here and nothing happened.

**Comment by kisslorand** [comment]
With this comment you should also see the total number of layers of that gCode file.
You should see the layer number in format xxx/yyy, where xxx is the actual layer that is printed and yyy is the total layer number.
