### ISSUE TITLE
[Q] Gcode Filename

### ISSUE THREAD

**Issue by ramosglauco** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2198]
Hi devs! Is there any way to abbreviate the gcode filename the same way prusaslicer does the parts list? Exemple: Prefix...+...Suffix. This would help me a lot to better identify my files when printing, as the TFT (28) character limit causes the filenames to be cut off at the end. Thanks and sorry for my bad english...

![Captura de tela 2021-09-24 190108](https://user-images.githubusercontent.com/88552877/134744433-d97ef18a-4147-42f3-88c8-72e61cb1b8ff.png)

**Comment by oldman4U** [comment]
You never used DOS and the 8.3 filename limitation. 

😁

**Comment by kisslorand** [comment]
@ramosglauco 
Isn't it just easier to manage yourself the file names upon saving them? Don't be that lazy! :)
