### ISSUE TITLE
[FR] UBL Grid probe

### ISSUE THREAD

**Issue by Chicos123** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2200]
**Is your feature request related to a problem? Please describe.**
UBL usually uses a 10x10 grid, so it takes a long time to probe when using the `G29 P1`.
Because of that i mainly use `G29 J5`. but TFT has no option to change `G29 P1` to `G29 J%i`

**Describe the solution you'd like**
Plase add an option to switch`G29 P1`, `G29 J{1~GRID_MAX_POINTS}`commands
And an option to set the value of`{1~GRID_MAX_POINTS}`

**Comment by oldman4U** [comment]
Whats about using a custom gCode for this?

**Comment by Chicos123** [comment]
> Whats about using a custom gCode for this?

I usually set it up like this. 
```
G28    ; Home | XYZ
G29 L0 ; Bed Leveling | Load Mesh Slot | "0"
G29 P0 ; Bed Leveling | Phase 0 | Zero Mesh Data
G29 J5 ; Bed Leveling | Grid Probing | "5x5"
G29 P3 ; Bed Leveling | Phase 3 | Fill Unpopulated
G29 S0 ; Bed Leveling | Save Mesh Slot | "0"
G29 A  ; Bed Leveling | Activate UBL
```

**Comment by oldman4U** [comment]
So 7 custom gCodes. Why not..
