### ISSUE TITLE
[BUG] Marlin emulation mode not working

### ISSUE THREAD

**Issue by rubencm** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2210]
### Description

When I go to the Marlin emulation mode, it shows only a black screen with the text "Marlin mode"

When I connect a LCD12864 to the EXP1 and EXP2 pins, the LCD works correctly, but when I connect the cables to the TFT24 no.

### Hardware & Software
TFT24 GD with last version 1.1.27.x
Skr 1.4 turbo with DCDC module
Marlin version: 2.0.9.2 but wasn't working neither in 2.0.x-bugfix
My Marlin custom build [here](https://github.com/rubencm/Marlin/pull/2/files)

**Comment by radek8** [comment]
What's your marlin record?

**Comment by rubencm** [comment]
Skr 1.4 turbo

**Comment by radek8** [comment]
Ok

**Comment by radek8** [comment]
Can you take a picture of the wiring?

**Comment by rubencm** [comment]
![](https://i.imgur.com/6yslxyk.jpg)
![](https://i.imgur.com/gjRFEgC.jpg)

**Comment by radek8** [comment]
The connection looks fine.
send the config.ini file

**Comment by rubencm** [comment]
I think this is the config.ini i flashed the last time (before flashing it didn't work neither)

https://pastebin.com/WrpanmJp

**Comment by radek8** [comment]
The parameters in the config ini are also fine.
if you used this configuration, it should work.
Try new uploads files, bin, font, icons and config.ini.

**Comment by rubencm** [comment]
I aleady did that, but I will do again in a few minutes

**Comment by rubencm** [comment]
I reflashed everything again (TFT24 folder, language_es.ini, config.ini and firmware file), and then did the reset.txt and still nothing

**Comment by radek8** [comment]
If you disconnect the cable from the RS232 connector
Will the display remain powered on (will it remain lit)?

**Comment by rubencm** [comment]
yes, and I can move the wheel and push buttons, I hear the click sounds, but I get no image

![](https://i.imgur.com/XUCeSeD.jpg)

**Comment by radek8** [comment]
Do you use the same cables you connect the TFT to connect the original 12864 display?

**Comment by rubencm** [comment]
yes

**Comment by radek8** [comment]
Since no one else who has the same display does not complain about the same problem, it will not be a FW TFT problem, but it looks like the HW problem of your display.

**Comment by rubencm** [comment]
Thank you, I will try to contact the seller

**Comment by wisetiger1701** [comment]
I'm having this exact issue with the same hardware. Did you resolve it?

**Comment by rubencm** [comment]
No, I just got a refund

**Comment by wisetiger1701** [comment]
Thanks for the quick response. Darn, I was really hoping there was a
software fix.
