### ISSUE TITLE
[FR] MULTI_VOLUME for onboard SD & onboard USB Support

### ISSUE THREAD

**Issue by Guilouz** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2215]
It will be interesting to add support for multi volume to choose which volume (SD or USB) to mount.

Usefull for new boards like SKR 2, GTR, Octopus etc

It added to Marlin menu with this PR : https://github.com/MarlinFirmware/Marlin/pull/22004

Multi volume are working in Marlin mode but not on TFT mode.
In Marlin mode print menu gives access to the ability to browse onboard SD storage and onboard USB storage on the motherboard.
In TFT mode we have only access to the onboard USB storage with OnboardSD icon but not to SD storage when MULTI_VOLUME is enabled in Marlin.

**Comment by kisslorand** [comment]
How is this different from FR #2005?

**Comment by kisslorand** [comment]
Multivolume is available only in Marlin mode. In touch mode there is no other way to communicate with Marlin than with gcodes. For the moment there is no gcode in Marlin for switching from onboard SD to onboard USB.

**Comment by Guilouz** [comment]
> Multivolume is available only in Marlin mode. In touch mode there is no other way to communicate with Marlin than with gcodes. For the moment there is no gcode in Marlin for switching between onboard SD and onboard USB.

I understand, but there is some issue when USB Support is enabled, TFT always reports that there is no SD card.

**Comment by kisslorand** [comment]
I just tested it today. By default USB is used, you have to switch to SD to access it.

**Comment by Guilouz** [comment]
Yes USB is working but there is always "no Sd card" notification which repeats in TFT mode but not in Marlin mode. It's quite boring.

**Comment by kisslorand** [comment]
I didn't have that "No SD card" when I tested today onboard USB.

**Comment by kisslorand** [comment]
@Guilouz 
I started working on this. For the moment I implemented M19 in Marlin and with that gcode I can switch between SD and USB on the motherboard.
M19 S - switch to SD card
M19 U - switch to USB

**Comment by Guilouz** [comment]
Ah good news ! I think a 2nd icon onboardUSB would be good, to keep the continuity of the screen ports.
Yes I think an option in config.ini to enable it because I think there is no option to parce if MULTI_VOLUME is enabled or not.

**Comment by kisslorand** [comment]
You just gave me an idea, to make Marlin report its MULTI_VOLUME capability in case SDCARD is enabled.

**Comment by kisslorand** [comment]
https://github.com/MarlinFirmware/Marlin/pull/23780

I already have also the TFT FW ready for this.

**Comment by Guilouz** [comment]
Oh nice! Do you have source code on your github to try ?

**Comment by kisslorand** [comment]
Yes: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/2418
