### ISSUE TITLE
[FR] RRF M150 support 

### ISSUE THREAD

**Issue by xPew** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2216]
**Is your feature request related to a problem? Please describe.**
Seems like the firmware as is, can't handle RBG LED settings on RRF.

**Describe the solution you'd like**
Please modify the current code to be compatible with RRF.

**Additional context**
None of the button's works for now (r, g, b, w, on, off or the colour mixer)
https://marlinfw.org/docs/gcode/M150.html
https://duet3d.dozuki.com/Wiki/M150
If you have a solution, I have configured NeoPixels to test with on RRF 3.3

**Comment by xPew** [comment]
Any plan to implement this @bigtreetech , @digant73, @Msq001?
I can help with testing if needed.

**Comment by bigtreetech** [comment]
> Any plan to implement this @bigtreetech , @digant73, @Msq001? I can help with testing if needed.

Hello, So adding an `X2` parameter to `M150` for RRF can solve this problem?

**Comment by xPew** [comment]
> > Any plan to implement this @bigtreetech , @digant73, @Msq001? I can help with testing if needed.
> 
> Hello, So adding an `X2` parameter to `M150` for RRF can solve this problem?

Sadly no. I configured based on the reccomendatipn to the RRF port, but seems like there is a syntax difference or something. The standalone commands from terminal works, but the predefined buttons in the LED menu dont.

**Comment by xPew** [comment]
> Can you help test whether `M150 X2 R255 U255 B255 W0 P255 I255` command can control the color of neopixel to white?

I can test it when I get home to my printer, but as far as I remember these commands worked from terminal perfectly. In fact I was only able to use the terminal, so these should work.
In RRF config.g I configured M150 X2 T300:800:1250:250, as mentioned here: https://teamgloomy.github.io/neopixels.html
So M150 R U B … should be enough from terminal.

**Comment by bigtreetech** [comment]
Hello, I just conducted a test. In fact, the TFT firmware can normally control the color of neopixel now. Is your TFT firmware the latest version

**Comment by digant73** [comment]
@xPew as reported by bigtreetech, it seems you are using an old TFT fw version (you also mentioned that from the LED menu you changed only r, g, b, w). Since some months now, the TFT fw also supports Neopixel. The LED menu gives you the possibility to set R, G, B, W, P, I.

**Comment by xPew** [comment]
Thanks, I will check it at the weekend than again. I last tried it a few weeks back with the latest at the time, but the menu didn't worked, just manual command's.
@bigtreetech which RRF version did you run your test?

**Comment by digant73** [comment]
@xPew
The LED menu currently uses the gcode "M150 R<r> U<u> B<b> W<w> P<p> I<i>".
Simply provide the working gcode you send from the terminal

**Comment by xPew** [comment]
@digant73 @bigtreetech Sorry for the delay, had a busy week, but now I did the testing...

The following format is working: M150 (X2) Rr Uu Bb Pp where:
Rnnn Red component, 0-255
Unnn Green component, 0-255
Bnnn Blue component, 0-255
Pnnn Brightness, 0-255

When I send a command like M150 R255 U0 B0 P255 with the web interface, the led turns red as expected. But when I press the red led button in the menu nothing happens. Oddly the terminal on the TFT cant change the color... The other features of the TFT works, so it communicates with the mainboard/fw, also I am using the latest firmware. Other commands from the TFT's terminal works fine, like M122.

If you can change the code send by the TFT to this in case of RRF I can test it prior merging.

**Comment by digant73** [comment]
@xPew please test PR #2241 and let me know if it works

**Comment by xPew** [comment]
@digant73 It's working as I'd expect it to work. Huge thanks for the fix. Predef colors, on, off and custom colors works perfectly now.
Any chance that you have some hotfixes for #1979 or #2141? :)

**Comment by digant73** [comment]
good it fixed the issue. For the requested FRs, I think there is already someone else that could implement them (I don't have RRF, so I could not test it at all)

**Comment by xPew** [comment]
@digant73 #2141 is just a general UI change to let to use the grid view along with the list mode. Isn’t that possible?
