### ISSUE TITLE
SKR MINI E3 V2 AND BIGTREE TFT E3 V3

### ISSUE THREAD

**Issue by Talha909** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2217]
I have fallowing hard ware

SKR MINI E3V2
BIGTRE TFT 35 V3
RASPBERY PI ZERO 

My lcd is not working. There is garbage on the screen. I have done pi zero with spi . There is any solution for that.

**Comment by radek8** [comment]
Please send Maelin configuration, TFT configuration.
Send some photos with TFT connection with SKR.
As Oldman4U writes, the problem is not in the FW of the display, but in the configuration or connection.

**Comment by Talha909** [comment]
I tried these but did not work. Can you please check again. I have skr mini e3 with with tft 3e v3 and rapi zero with spi connections.
