### ISSUE TITLE
[BUG] (Size of the Bed not taken into account

### ISSUE THREAD

**Issue by magnificu** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2221]
### Description
Size of the Bed (300mm x 300mm) not taken into account in:
1) Menu > Movement > Leveling
2) Menu > Movement > Bed Level > ABL > L corner

### Steps to reproduce

1. [First Step]
Set the Bed size in Marlin 2.0.9.2, Configuration.h
// The size of the printable area
#define X_BED_SIZE 300
#define Y_BED_SIZE 300

2. [Second Step]
BIGTREETECH-TouchScreenFirmware_x.x.27, Configuration.h
#define X_MAX_POS 300
#define Y_MAX_POS 300
#define Z_MAX_POS 300

3. [Third Step]
Flash the boards (SKR2, TFT50 v3.0)

4. [Fourth Step]
reset EEPROM

5. [Fifth Step]
go to:
Menu > Movement > Leveling
or
Menu > Movement > Bed Level > ABL > L corner

and select the Hotend to move to the corners

**Expected behavior**
The Hotend should move to the corners of the bed - LEVELING_EDGE_DISTANCE

**Actual behavior**
The printer seems to consider a 200mm x 200mm bed size

My workaround in file Leveling.c
/*
  int16_t pointPosition[5][2] = {
    // Left lower corner
    {x_left_point,  y_lower_point},
    // Right lower corner
    {x_right_point, y_lower_point},
    // Right upper corner
    {x_right_point, y_upper_point},
    // Left upper corner
    {x_left_point,  y_upper_point},
    // Center point
    {(x_left_point + x_right_point) / 2, (y_lower_point + y_upper_point) / 2},
  };
*/
  int16_t pointPosition[5][2] = {
    {infoSettings.level_edge, infoSettings.level_edge},
    {300 - infoSettings.level_edge, infoSettings.level_edge},
    {300 - infoSettings.level_edge, 300 - infoSettings.level_edge},
    {infoSettings.level_edge, 300 - infoSettings.level_edge},
    {150, 150},
  };

My workaround in file LevelCorner.c
/*
  uint16_t pointPosition[4][2] = {
    {infoSettings.machine_size_min[X_AXIS] + infoSettings.level_edge, infoSettings.machine_size_min[Y_AXIS] + infoSettings.level_edge},
    {infoSettings.machine_size_max[X_AXIS] - infoSettings.level_edge, infoSettings.machine_size_min[Y_AXIS] + infoSettings.level_edge},
    {infoSettings.machine_size_max[X_AXIS] - infoSettings.level_edge, infoSettings.machine_size_max[Y_AXIS] - infoSettings.level_edge},
    {infoSettings.machine_size_min[X_AXIS] + infoSettings.level_edge, infoSettings.machine_size_max[Y_AXIS] - infoSettings.level_edge},
  };
*/
  uint16_t pointPosition[4][2] = {
    {infoSettings.level_edge, infoSettings.level_edge},
    {300 - infoSettings.level_edge, infoSettings.level_edge},
    {300 - infoSettings.level_edge, 300 - infoSettings.level_edge},
    {infoSettings.level_edge, 300 - infoSettings.level_edge},
  };  

### Hardware Variant
TFT50 v3.0

### TFT Firmware Version & Main Board Firmware details
BIGTREETECH-TouchScreenFirmware_x.x.27

### Additional Information
* Include a ZIP file containing your `Configuration.h` or use [Pastebin](https://pastebin.com/) and paste a link in this issue.
* Provide pictures or links to videos that clearly demonstrate the issue.

**Comment by sarvenn** [comment]
Why don't we fix the source code? Is there any PR related to this bug report? Or isn't it necessary to fix?

**Comment by kisslorand** [comment]
Check the message just above yours.
