### ISSUE TITLE
[FR] Smart detection value in the setting menu

### ISSUE THREAD

**Issue by GenaUser** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2225]
Would it be possible to add the possibility to modify the value of "FIL_RUNOUT_DISTANCE" in the screen menu settings ?
Changing the detection value according to the specifics of the printing is important to have a good balance between sensitivity and loss of material.
Being able to adjust the detection while printing would be a big advantage.
Having to reload the firmware with every value change before printing is really annoying.

**Comment by radek8** [comment]
@guruathwal , @digant73 
you could add parameters
FIL_RUNOUT_DISTANCE
FIL_RUNOUT_NOISE_THRESHOLD
to the printer menu?

**Comment by digant73** [comment]
I don't think those settings need to be frequently changed (e.g. I set them only once)

**Comment by GenaUser** [comment]
During printing, if you have false alarms, the only choice we have at the moment is to stop the detection, with the risk of losing all our work.
It is important to be able to adjust the settings according to the type of printing being carried out to find the right balance between avoiding unwanted detections and holes in the part when clogging is detected.

**Comment by kisslorand** [comment]
I was never a big fan of SW solutions for HW problems...

**Comment by GenaUser** [comment]
Hardware problems?
Ex: In certain parts with thin zones, the overlapping of the walls often results in an excess of material which can hamper the extrusion and generate "false" detections.
