### ISSUE TITLE
[BUG] Configuration parameter discrepancy/missing - Configuration.h vs config.ini

### ISSUE THREAD

**Issue by rubienr** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2232]
### Description

Discrepancy in between `Configuration.h` and `config.ini`.

### Steps to reproduce
Search for `neopixel_pixels` in `config.ini` and `NEOPIXEL_PIXELS` in `Configuration.h`.

**Expected behavior**
1. All arguments that are present in `config.ini` must be present in `Configuration.h`.
2. All arguments that are present in `Configuration.h` may be optionally configurable by `config.ini`.

**Actual behavior**

|  Configuration.h | config.ini |
|-|-|
| - | neopixel_pixels |
| - | z_stepper_alignment | 
| - | emulated_m600 |
| - | emulated_m109_m190 |
| - | rotated_ui |
| - | language (primary or 2ndary) |
| LISTVIEW_BORDER_COLOR | border_color (naming, low prio) |
| - | files_sort_by |
| - | files_list_mode |
| - | persistent_info |
| - | terminal_ack |
| - | prog_disp_type |
| - | layer_disp_type |
| - | marlin_type |
| - | heated_bed |
| - | heated_chamber |
| - | size_min |
| - | size_max |
| - | onboard_sd |
| - | long_filename |
| - | inverted_axis |
| - | probing_z_offset |
| - | ps_auto_shutdown |
| - | pl_recovery |
| - |  touch_sound |
| - | toast_sound |
| - | alert_sound |
| - | heater_sound |
| - | lcd_lock_on_idle |
| - | knob_led_idle |
| - | start_gcode_enabled |
| - | end_gcode_enabled |
| - | cancel_gcode_enabled |
| HOTEND_NUM hotend_count |
| EXTRUDER_NUM ext_count |
| FAN_NUM fan_count |
| ENABLE_CTRL_FAN controller_fan |
| NOZZLE_PAUSE_* pause_* |
| LEVELING_EDGE_DISTANCE_* level_edge_distance* || | |
| TOOL_CHANGE | - |
| EXTRUDER_ID | - |
| FAN_CMD | - |
| [XYZ]_(MIN\|MAX)_POS | - |
| ... | ... |

### Hardware Variant
All variants.

### Additional Information
That may be applicable for other arguments too. I did not verify them all.

**Comment by radek8** [comment]
You can set some less frequently edited parameters only in configurstion.h
You can change most parameters in c config ini, without having to recompile the BIN file.
What's wrong with that?

**Comment by rubienr** [comment]
Technically it is not wrong but that decision is interesting and cumbersome since everything that is in `.ini` must be parsed and depicted in code nonetheless. However, the point of truth shall be the `Configuration.h` whilst `config.ini` should be optional. 

Imagine following use-case: 
1. flash the display with `firmware.bin` + `config.ini` on CF card
2. remove the CF card
3. do a "Reset default settings"
4. now all settings that cannot be set in `Configuration.h` must be manually resurrected in Settigns -> Feature menu or by providing the `config.ini` again

Point 4. is feasible if the argument can be parametrized in Settigns -> Feature (for example: enable `z_steppers_alignment`), but what about `neopixel_pixels` which is not in the menue?

Off-topic:
To keep that consistent the least painful way would be to auto-generate the `.ini` file out of `Configuration.h` every time `#defines` are added/modified/removed.

**Comment by oldman4U** [comment]
This is open source software. So please provide a PR which includes fixes for the things which you believe are a bug. 

Thank you

**Comment by radek8** [comment]
You are right in your own way. But wouldn't the INI file be useless then?

FW was created to be easy to use for BFU as well. Just take the already generated BIN and then upload the INI file and the display is configured and ready. If something goes wrong or I change the printer configuration, just reload the INI file. This is at the cost of more flash memory consumption.
Unlike Marlin, where the emphasis is on the smallest possible FW size, but you always have to recompile the BIN file.
You wouldn't believe how many people eat there is a problem compiling the BIN file yourself.
If you have a problem, create a PR, as Oldman4U advises you.

**Comment by radek8** [comment]
The fact that Configuration.h contains only some parameters and most of the configuration is in the INI file has a historical reason.
Originally, the configuration was only in Configuration.h, but as the number of parameters increased, the display would not be customizable without compiling.
Therefore, Cnfig.ini was created and the parameters that need to be set are transferred to it and it is further used for new variables.
Therefore, Configuration.h contains the original parameters and new parameters, which for some reason should not have been available in the INI file. Of course, if a new parameter was added to the INI file, it was no longer necessary to add it to Configuration.h.

Just to explain.

**Comment by radek8** [comment]
![image](https://user-images.githubusercontent.com/46979052/140604094-78a409cb-2e8a-4e7c-a3a2-5c44c97ce0df.png)
