### ISSUE TITLE
Why after update btt tft35v3.0 to 0.27 the touch isnt working? 

### ISSUE THREAD

**Issue by obionekenewbie** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2234]
Hi i recently update the btt tft 35 v3.0 from .26 to .27 but after the update the touch doesn't work and marlin mode has some screen bugs.
Thanks for attentions.

**Comment by kisslorand** [comment]
You most probably have to recalibrate your touchscreen. Put an empty "reset.txt" on your SDCard, insert it in your TFT's SDCard reader and reboot your TFT.

**Comment by obionekenewbie** [comment]
Ok that worked thanks

**Comment by oldman4U** [comment]
Please read the ReadMe at the front page of this repository where you would have got the same answer and close this ticket.

Thank you
