### ISSUE TITLE
What's the best config option on marlin for BTT tft35v3.0 and BTT E3 RFF v1.1?

### ISSUE THREAD

**Issue by obionekenewbie** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2235]
Hi, i recently bought the BTT E3 RFF v1.1 to try the idex mode and the TFT35 V3.0 touchscreen updated to 0.27 but when i compile in VS code i cant choose REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER beacouse if i do i get this error:Only CR10_STOCKDISPLAY, ZONESTAR_LCD, ENDER2_STOCKDISPLAY, MKS_MINI_12864, and TFTGLCD_PANEL_(SPI|I2C) are currently supported on the BTT_E3_RRF. So can you tell me if this board and tft are compatible and in wich way i should set them to work fine? beacouse if i choose CR10_STOCKDISPLAY it "works" only in marlin mode but with a lot of screen bugs and in touch mode the tft says printer not attacked even if try changing the baudrate ( current settings: SERIAL_PORT 3, SERIAL_PORT_2 -1, BAUDRATE 115200.)
Thanks for attention.
Kind regards.

**Comment by oldman4U** [comment]
Dear user.

This is not a user group but the firmware repository related to the BTT TFT displays.

Please help the community and close the ticket once you do not need it anymore. Thank you
