### ISSUE TITLE
TFT70 icons

### ISSUE THREAD

**Issue by mikerocklewitz** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2237]
### Description
TFT70 latest firmware from github fails stating out of date icons.  They install fine.

### Steps to reproduce

1. Downloaded the repo from 11/9
2. Flashed tft70 with included themes (I tried unified material and hybrid red - both had same issue)

**Expected behavior**
Icon/theme to work

**Actual behavior**
Display says icons are out of date and need to be updated....even when updated

### Hardware Variant
TFT70

**Comment by radek8** [comment]
Do you have icons on the SD card in the TFT70 folder, BMP subfolder?

**Comment by mikerocklewitz** [comment]
> Do you have icons on the SD card in the TFT70 folder, BMP subfolder?

Yes of course.  I reverted to my download from 3 days ago and it works fine.

Simply reporting an issue with newest repo change.

**Comment by oldman4U** [comment]
@digant73 

Can you see a possible reason why your PR causes the reported problem?

**Comment by cooldude204** [comment]
the tft35 v3.0 also has this issue tried multiple icon packs and seems its trying to find 0.bmp and 2.bmp but can't find them.

**Comment by digant73** [comment]
I also have a TFT35 v3 and no issue at all

**Comment by cooldude204** [comment]
yes I'm using the precompiled version

**Comment by digant73** [comment]
if you are familiar to compile the code, try to compile it. It's not currently possible for me to compile it for you

**Comment by cooldude204** [comment]
I'm familiar with compiling marlin so I should be able to figure it out, I will compile my own .bin and let you know

**Comment by digant73** [comment]
> I'm familiar with compiling marlin so I should be able to figure it out, I will compile my own .bin and let you know

You only need to set "default_envs = BIGTREE_TFT70_V3_0" in platformio.ini and compile

**Comment by cooldude204** [comment]
Compiled the firmware uploaded it with icons on the SD card and its still getting the error icons: update required

**Comment by mikerocklewitz** [comment]
I can try building it myself tomorrow but it looks like someone else found the issue as well.

**Comment by digant73** [comment]
@cooldude204 

try if this works

[BIGTREE_TFT35_V3.0.27.x.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/7516232/BIGTREE_TFT35_V3.0.27.x.zip)

**Comment by cooldude204** [comment]
@digant73 unfortunately it didn't work. still says Icons: update required

**Comment by cooldude204** [comment]
I changed branches to the release-Vx.x.27 branch and it works. and no failed 0.bmp and 2.bmp.

**Comment by jeffeb3** [comment]
I'm not an expert at this codebase. So I hope I'm not causing problems here. But I suspect that one of the names of the icons has been chosen as a macro, and it is being resolved to 0 or 2 and then X_ICON ( 0 ) and X_ICON ( 2 ) is being called.

**Comment by jeffeb3** [comment]
Aha!

LANGUAGE is defined in the Configuration.h and it is set to 0 by default
ONBOARD_SD is set in the Configuration.h and it is set to 2 by default.

PR incoming. I don't have a fresh screen to test on. Mine already have the 0.bmp and 2.bmp. How can I remove all of the icons already loaded, so I can test this?

**Comment by bigtreetech** [comment]
fixed in #2239
