### ISSUE TITLE
[BUG] Switching Marlin mode to touch mode

### ISSUE THREAD

**Issue by NOVAXIM** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2263]
### Description
The problem refers to switching from Marlin mode to touch mode.

### Steps to reproduce

1. If TFT is touch mode I set Marlin mode.
2. I back to touch mode.
3. TFT beeps intermittently and displays it:
<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/Hnzd65tC/IMG-20211123-190227.jpg' border='0' alt='IMG-20211123-190227'/></a>
Note: First time displaying '7' instead '5'.

**Expected behavior**
Please write if your TFT works the same (don't forget to mention information about hardware, firmware, and configuration). I am asking for any information that will help me to a quick solution.

**Actual behavior**
When I use "BIGTREE_TFT35_V3.0.27.x.bin" dated 25 Oct then switching work well (with old images: "marlin.bmp", "bigtreetech.bmp").

### Hardware Variant
SKR-mini-MZ V3.0 with TFT35-MZ V3.0

### TFT Firmware Version & Main Board Firmware details
Problem was found on the last compilation of November 21st and earlier (with new images: "Marlin_mode.bmp", "touch_mode.bmp").

### Additional Information
Refers to the standard configuration.

**Comment by aldaw** [comment]
We had the same problem solved it with using a older version.
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/2255

**Comment by bigtreetech** [comment]
fixed in #2241. Please confirm, Thank you very much!

**Comment by NOVAXIM** [comment]
Yes, it is fixed. Thank you!
