### ISSUE TITLE
[FR] Minor UI changes

### ISSUE THREAD

**Issue by xPew** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2272]
To better suit my theme, I would like to ask for some minor UI changes but would be a nice touch.
Here, I would like to change the status screen text color to white. Can it be added as an option to the config.ini? My theme has a color scheme due to how our web interface looks, so I don't want to change it to a lighter background if it's possible to change the text color.
I guess nobody wants to use fancy colors here, so only a black and white option is enough, not to consume a lot of memory.
![image](https://user-images.githubusercontent.com/81440138/143775887-f3626ad7-8a9d-42cb-8a46-ea62852bca4d.png)

My other request is to @kisslorand . I really like your PR's, especially the status bar you added back then. May I ask you about the possibilities of its customization? I am not a programmer, and I guess it all comes down to memory issues, but I would like to also tweak this part of the UI to better suit my theme.  Could some color choices be added for this part of the UI too? Better in config.ini, but if it's not possible maybe some guidance about what to change in case of self-compiling to be able to customize this.

Thank you in advance! :)

**Comment by radek8** [comment]
All you need is an adjustment

![image](https://user-images.githubusercontent.com/46979052/143781558-0adde1ed-7fba-45c2-9d61-3d6b202951e8.png)

**Comment by kisslorand** [comment]
> My other request is to @kisslorand . I really like your PR's, especially the status bar you added back then. May I ask you about the possibilities of its customization? I am not a programmer, and I guess it all comes down to memory issues, but I would like to also tweak this part of the UI to better suit my theme. Could some color choices be added for this part of the UI too? Better in config.ini, but if it's not possible maybe some guidance about what to change in case of self-compiling to be able to customize this.
> 
> Thank you in advance! :)

Thank you for your appreciation but the status bar/icon is not my work. Anyhow What customization do you have in mind? What color choices and where do you have in mind?

**Comment by xPew** [comment]
> > My other request is to @kisslorand . I really like your PR's, especially the status bar you added back then. May I ask you about the possibilities of its customization? I am not a programmer, and I guess it all comes down to memory issues, but I would like to also tweak this part of the UI to better suit my theme. Could some color choices be added for this part of the UI too? Better in config.ini, but if it's not possible maybe some guidance about what to change in case of self-compiling to be able to customize this.
> > Thank you in advance! :)
> 
> Thank you for your appreciation but the status bar/icon is not my work. Anyhow What customization do you have in mind? What color choices and where do you have in mind?

Oh, sorry I ment the progress bar during printing. I would like to be able to modify the color of if. In my case blue, but I guess if a few basic color would be added others could benefit from it too.

**Comment by kisslorand** [comment]
OK, I got it now.
I will try to come up with something to be able to select between variants and/or customize the progress bar color.

**Comment by radek8** [comment]
@kisslorand 
it is not a matter of changing the color of the progress bar but of changing the color of the digits (temperature of the nozle, bed, fan ...) on the status screen.
See image above.

**Comment by radek8** [comment]
The current black is not visible on a gray background.
@xPew  Can't you make the gray one lighter so that the black font is visible?

**Comment by kisslorand** [comment]
> @kisslorand it is not a matter of changing the color of the progress bar but of changing the color of the digits (temperature of the nozle, bed, fan ...) on the status screen. See image above.


I beg to differ, see the comment of @xPew above.

"Oh, sorry I ment the progress bar during printing. I would like to be able to modify the color of if. In my case blue, but I guess if a few basic color would be added others could benefit from it too."

**Comment by radek8** [comment]
Personally, I see no reason to use a gray theme on a color display.
I like colors :-)

**Comment by radek8** [comment]
@kisslorand  Probably lost in translation

**Comment by xPew** [comment]
@kisslorand and @radek8 I requested both thing. The status screen font color and the progress bar color.
Thank you kissroland if you could see what you can do.
Also, radek, I copied the theme from our web interface (Duet Web Control), that's why it's so monochromatic. While I partly agree that it could be more colourful but I imagined this theme to be as close as possible, so I would like to ask for white fonts in the first place.

**Comment by radek8** [comment]
@xPew  did you try the edit I posted in my first comment? You will have white digits

**Comment by xPew** [comment]
> @xPew did you try the edit I posted in my first comment? You will have white digits

I need to copy the exact line? I am not a programmer and I don't see and white in that.
If yes I will try it, but I would like a more permanent/comfortable solution.
Thankfully this firmware is updating daily, so modifing it every time is a bit of a hassle.

**Comment by kisslorand** [comment]
Well... Doing firmware changes on requests is also a hassle.... :)

**Comment by radek8** [comment]
> > @xPew did you try the edit I posted in my first comment? You will have white digits
> 
> I need to copy the exact line? I am not a programmer and I don't see any white in that. :D If yes I will try it, but I would like a more permanent/comfortable solution. Thankfully this firmware is updating daily, so modifing it every time is a bit of a hassle.

Yes
the red line is the original and is replaced by the green one.
Then you just compile. and will be white.

**Comment by radek8** [comment]
Use GutHub Desktop.
Working with new versions and custom adjustments is then very simple ...

**Comment by kisslorand** [comment]
I kind of finished adding Orange, Yellow, Red, Green, Blue, Gray colors to the progress bar but it is too late here (over midnight) so I will test it tomorrow and make changes if needed.
It is not configurable in "config.ini", it will be rather configurable at compile time ("Configuration.h"). This way it adds 0 (zero) to the compiled program size.

**Comment by radek8** [comment]
Likewise, the white numbers in the live icons could be added during compilation

**Comment by radek8** [comment]
Purple Nooo

**Comment by kisslorand** [comment]
> Purple Nooo

Maybe Pink? LOL

**Comment by radek8** [comment]
Good night

**Comment by xPew** [comment]
Thank you guys! Gn!

**Comment by xPew** [comment]
Is there any reason why the status screen fonts are fixed black? In config.g ## Menu font color - menu_font_color:0 can be customised, but it dont change the status screen fonts. Can it be combined to prevent workarounds, and also make this setting more sense? This was my first attempt when I wanted to change the color and dont understood why it stayed black…

**Comment by thisiskeithb** [comment]
I’d like to see a “standard” set of colors like what’s used elsewhere in code:

- WHITE
- BLACK
- RED
- ORANGE
- YELLOW
- GREEN
- BLUE
- INDIGO
- VIOLET
 
Users will be familiar with those options and can match their UI colors to whatever LEDs or icon scheme they desire.

**Comment by kisslorand** [comment]
I do not see anywhere INDOGO and VIOLET in the code for TFT pixel colors.. Maybe it is just me but I have hard times imagine a BLACK progress bar.

**Comment by kisslorand** [comment]
@xPew 
Check PR #2272.

**Comment by bttguy** [comment]
Wow, nice! Check it when I next to my printer. Out of curiosity how much memory would it take if a config.ini was used to set this?

**Comment by kisslorand** [comment]
> Wow, nice! Check it when I next to my printer. Out of curiosity how much memory would it take if a config.ini was used to set this?

I don't know until I make it that way.

**Comment by xPew** [comment]
> @xPew Check PR #2272.

Seems fine to me. Its blue now :)

**Comment by xPew** [comment]
I saw the PR is merged. Thank you!
May I ask for a config.ini implementation of both the status screen font color and the progress bar color? At least to know wether it can fit or not.
Not urgent, but I would like to keep this FR open a bit more :)

**Comment by radek8** [comment]
check #2276
