### ISSUE TITLE
"illegal flash app" caused by Bad  SD card

### ISSUE THREAD

**Issue by jel111** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2283]
### Description
"illegal flash"
When updating firmware a micro SD adapter doesn't work. Have to use a Full size SD card.

### Steps to reproduce
Tried using a micro SD card with adapter and kept getting Illegal flash. Most times it doesn't work but every so often it does. It seems like the first time it worked but then didn't after that.

**Expected behavior**
Use any SD card especially a micro SD since that's pretty much what everyone has nowadays. At least people I know.

**Actual behavior**
Can only use a full size SD card when not using this you get the "illegal flash"

### Hardware Variant
TFT35 V3.0 E3
### TFT Firmware Version & Main Board Firmware details
/BIGTREE_TFT35_V3.0_E3.27.x.bin

### Additional Information
Just wanted to put this here as I searched for quite awhile until I found a subReddit that discussed this.

**Comment by radek8** [comment]
I have the same HW as you. I use a micro SD card with an adapter and no problem.
The problem will most likely be in your card.
What card do you use and what format?
You should use a card up to 8GB or smaller formatted as FAT32
If you use a larger card or a format other than FAT32, you may have problems, and it doesn't matter if you use an SD card or a micro SD adapter.

**Comment by oldman4U** [comment]
Please update the title of this ticket and close it after that. Your problem is not firmware related. Thank you

**Comment by gordo3di** [comment]
@jel111 

> I have the same HW as you. I use a micro SD card with an adapter and no problem. The problem will most likely be in your card. What card do you use and what format? You should use a card up to 8GB or smaller formatted as FAT32 If you use a larger card or a format other than FAT32, you may have problems, and it doesn't matter if you use an SD card or a micro SD adapter.

I have a handful of bad adapters so if I've had any issue it was either the adapter, card formatting or simply a bad board (we've had 8 bad boards and counting thanks bigtreetech...)

**Comment by radry** [comment]
Seems more like a hardware problem, not something software can fix. A micro SD adapter only routes the pins from the smaller card to a larger card, there is no circuit inside.  

![](https://modifieit.files.wordpress.com/2012/03/inside_microsd_adapter_pieces.jpg)

Try a different adapter.

**Comment by xPew** [comment]
I also only used micro sd cards with an adapter, and I updated the TFT pretty much every week in the past half or one year as new features added, and never had any issues with them.
I even 16GB ones, and maybe 32 as well since I have these around on my desk to work with randomly…

**Comment by oldman4U** [comment]
@Msq001

Please close this ticket.

**Comment by jel111** [comment]
I've had cards fail before so I tried a few different ones with different adapters. I usually try to keep the adapter with the particular card it came with. 
I also tried an 8 gb card as I had seen someone post about that as well.
The only thing that worked was a full size card that was 32gb I could be wrong but maybe there is a hardware issue with some units and not others?

**Comment by oldman4U** [comment]
And you understand that this is a firmware repository and not a hardware related user group? And that the title of the ticket is not related at all.

**Comment by digant73** [comment]
@jel111 clean the SD slot in the TFT with a brush and alcohol. Also do not push too much the SD adapter in the TFT. Try to pull a little bit the adapter after it was inserted in the TFT

**Comment by jel111** [comment]
> And you understand that this is a firmware repository and not a hardware related user group? And that the title of the ticket is not related at all.

It is related in a second cousin type of way. If you are trying to get it working you would think it a firmware issue. I posted it because I had a hard time finding an answer and only luckily stumbled upon a post. If it's wrong then remove it.

**Comment by oldman4U** [comment]
Only the owner of the ticket and the repository can change the title and the status.
