### ISSUE TITLE
TFT35 E3 V3 - No response at all to any FW?

### ISSUE THREAD

**Issue by TheGadge** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2301]
BTT TFT35 E3 V3
- I can't seem to update in any way (or even get a response from screen) that sd or USB has a bin file in. (FAT32)
- (Yet I can see in touch screen mode that U disk is inserted etc)
- I wanted to try the noscreentouch firmware also (klipper machine) , but can't even read prev fw releases from BTT.

I've noticed there are bootloader 'fixes' but with zero notes or instructions in a true engineer style lol.

Any ideas, please? 
Many thanks
William
(Skr mini v2 on Klipper, Ender 3 Pro)

**Comment by sarvenn** [comment]
Would you please try the latest marlin bugfix 2.
Yesterday I had a similar issue after uploadinh fw.
Today, I uploaded the latest bugfix and issue is solved.

**Comment by TheGadge** [comment]
> Would you please try the latest marlin bugfix 2.
> Yesterday I had a similar issue after uploadinh fw.
> Today, I uploaded the latest bugfix and issue is solved.

Small problem. I’m on klipper. I don’t think it’s that lol. Thanks for trying for me!

**Comment by radek8** [comment]
What update do you have a problem with?
SKR or TFT?
The description of your problem is difficult for me to understand.

**Comment by TheGadge** [comment]
> What update do you have a problem with? SKR or TFT? The description of your problem is difficult for me to understand.

Oh ok sorry, but the Title is "TFT35 E3 V3 - No response at all to any FW"
No matter what bin file I add to a fat32 sd or USB, the TFT35 gives no response whatsoever, yet detects the card/usb being in.

**Comment by radek8** [comment]
So you can't update TFT?
The SD card, not USB, is used for the update.
Cards larger than 32GB may not work well.
Use an 8GB or smaller SD card, formatted to FAT32.
Copy BIGTREE_TFT35_V3.0_E3.27.x.bin, config.ini and folder TFT35 to the card.
After a successful update, the BIN file is renamed to CUR.

**Comment by TheGadge** [comment]
> So you can't update TFT? The SD card, not USB, is used for the update. Cards larger than 32GB may not work well. Use an 8GB or smaller SD card, formatted to FAT32. Copy BIGTREE_TFT35_V3.0_E3.27.x.bin, config.ini and folder TFT35 to the card. After a successful update, the BIN file is renamed to CUR.
> 
> Sometimes it helps to reformat the SD Card.

Sandisk extreme 16GB SD card used. 
done all the above. It’s as if the port isn’t even there.

**Comment by radek8** [comment]
Format it again.
If that doesn't work, use another card.

**Comment by TheGadge** [comment]
> Format it again. If that doesn't work, use another card.

Well, I'm on my 3rd SD card, very strange, but we have action! Many thanks! :)

**Comment by TheGadge** [comment]
> Format it again. If that doesn't work, use another card.

Sorted! Many many thanks, I can't believe I've got cards that seem fine in Windows, checked in camera etc, BTT only likes one of them, all between 8-16GB. Oh well!

I've just also update notouch firmware for klipper, and it works a treat after config changes.
I owe you a beer for taking me back to the basics.

**Comment by radek8** [comment]
I also have experience with this strange behavior.
I use 2 SD cards, both work and update the FW.
Suddenly, one SD card stops updating the FW.
It can be used to update again in a week. I didn't figure out what it was, but if one doesn't work I'll take the other ...

**Comment by radek8** [comment]
Close the ticket if the problem is solved.

**Comment by oldman4U** [comment]
Gadge

Please help the community and close the ticket. Thank you
