### ISSUE TITLE
[Q] Bin file for Biqu B1?

### ISSUE THREAD

**Issue by ramosglauco** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2309]
Hi. Sorry if my question seems silly. I have a Biqu B1 with Marlin 2.0.7.2 installed. I have a question about which bin file I need to upload exactly:

BIGTREE_TFT35_V3.0.27.x.bin
BIGTREE_TFT35_V3.0_B1.27.x.bin
BIGTREE_TFT35_V3.0_E3.27.x.bin

I'm attaching a TFT photo. Please, can you help me?

![20220103_234053](https://user-images.githubusercontent.com/88552877/148003733-2bfd17c4-11fd-452a-9ec0-4a40d388f1fd.jpg)

**Comment by rondlh** [comment]
BIGTREE_TFT35_V3.0_B1.27.x.bin should be the correct firmware.
The TFT will only flash if it finds the correct firmware filename, so don't rename the file!
Either way, you will not damage or brick the TFT if you flash the wrong firmware...

**Comment by oldman4U** [comment]
ReadMe has all the information.

Please help the community and close the ticket once you do not need it anymore. Thank you
