### ISSUE TITLE
Does command M605 S3 (mirror mode) fail?

### ISSUE THREAD

**Issue by angeldrug** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2311]
Hello. Can you tell me why the M605 S3 (mirror mode) command is not executed in TFT mode?
Printer with two extruders. Created four commands in the custom menu:
M605 S0 (Full control mode)
M605 S1 (AUTO_PARK mode)
M605 S2 (DUPLICATION mode)
M605 S3 (MIRRORED mode)

The commands M605 S0, M605 S1, M605 S2-work and switch modes.
Command M605 S3 - does not work and mirror mode does not turn on.
If you send the M605 S3 command through the terminal, it also does not work and the mirror mode does not turn on.
In marlin mode, through the IDEX menu, all commands are executed and work

**Comment by radek8** [comment]
I don't see the S3 switch for Marlin documented anywhere for the M605

https://marlinfw.org/docs/gcode/M605.html

https://reprap.org/wiki/G-code#M605:_Set_dual_x-carriage_movement_mode

**Comment by angeldrug** [comment]
radek8 Marlin \ src \ gcode \ control \ M605.cpp - you can read here

**Comment by rondlh** [comment]
The TFT does not modify the M605 command in any way, it just forwards the command to the motherboard. This does not seem to be an TFT issue.

**Comment by angeldrug** [comment]
Yes, I think so too. I sent a command from Repetier-Host and it doesn’t work either. I’ll ask someone in the marlin section. Thank you.

**Comment by radek8** [comment]
File: Marlin/blob/bugfix-2.0.x/Marlin/src/gcode/control/M605.cpp
Incidentally, line break is missing on line 103; ?

![image](https://user-images.githubusercontent.com/46979052/148549489-7a2fd7c7-862d-4392-a6d4-e591835ba6a0.png)

**Comment by angeldrug** [comment]
I am not a programmer either. That is why I am asking here. The printer had a board from MKS and I replaced it with SKR PRO. And now I cannot understand which command the mirror mode is turned on.

**Comment by radek8** [comment]
I sent a question to Marlin

**Comment by angeldrug** [comment]
Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
@rondlh Please check #2304
