### ISSUE TITLE
[FR] Equal length cables on the TFT35 E3 V3

### ISSUE THREAD

**Issue by V1EngineeringInc** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2312]
![PXL_20220107_202224048](https://user-images.githubusercontent.com/55478432/148603148-5d47b8de-51c8-45e8-aaf8-5a2a2d9caf1c.jpg)

Hi Team, I have asked my contact at your company, Mike, about this and he said it makes no sense. So I am making this post to try and clarify.

The cables go to the same place, the screen, when you have ribbon cables of different lengths it makes cable management very difficult. On top of that the shorter cables do not allow for the screen to be very far away from the printer or other machine. So if you mount the control board on the side or back, you can not access the screen. Ideally It would be nice to have them a bit longer as well

I hope this is an inexpensive way to vastly improve the usability of your product! Sure to benefit customer satisfaction. If you search for "TFT35 Extension Cables" you will see we are not the only user base looking for this feature.

Thanks for your time.

**Comment by oldman4U** [comment]
Please close this ticket and post your request in a hardware related repository. This repository is ONLY for BTT TFT FIRMWARE related issues and feature requests.

Thank you
