### ISSUE TITLE
[BUG] Case light panel in touch mode is not working correct

### ISSUE THREAD

**Issue by Vertorek** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2317]
### Description

Case light panel for touch mode working in not the best way. To accept changes it is necessary to press the return arrow sometimes and enter to the control menu for case light again. In order to turn off the light after turning on also you need to play a bit with opening the menu with control of the light case, go out, press twice to turn off/on icon. Sometimes is working sometimes not.

Is it possible to make a 1% step not a 10% step for changing the light intensity? Or enter a value like for Hot End or Bed?

For Marlin mode, everything is fine 1% change, when you accept the value let say 55% that value is simply set. 

### Steps to reproduce

1. Enter the case light menu 
2. try to turn on and off the light a few times and observe how it is working 
3. change % value and try to turn off and turn on light

**Expected behavior**
Turning off/on the light when the icon is pressed 
Setting the % value with 1% step instead of 10% step 
when % value is set light should fluently adjust the intensity according to the wanted value

**Actual behavior**
hard to control case light in touch mode
changing of the % is difficult 
turning off/on is difficult 

### Hardware Variant
TFT35 e3 v3.0.27 x DEC 30.2021 & Marlin 02000801
### TFT Firmware Version & Main Board Firmware details
TFT35 e3 v3.0.27 x DEC 30.2021 & Marlin 02000801 & SKR 1.4 Turbo

**Comment by digant73** [comment]
let the PR close this issue when merged
