### ISSUE TITLE
[BUG] Strange behavior when setting the fan.

### ISSUE THREAD

**Issue by radek8** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2319]
I am using fan controllers (M710)
The fan is set to 66%.
If I open the fan menu, the fan (CtA) displays the speed 66/00. It does not respond when you click to lower the values. By clicking on the values increase, the values are set to 1/1. And the fan stops

If I edit the value (F0) before editing the value of the controller fan (CtA), then I go to the value (CtA) it still behaves badly.
if I leave the menu and return again, values (CtA) 66/66 is displayed and editing works normally.

The fan setting (F0) also does not work properly.
If I set the fan speed via Gkod (M106 S128)
The value (F0) 50/0 is displayed in the fan menu.
The value cannot be decreased and when increased, it is calculated from the beginning of 1/1. And the fan stops.

For clarity, I enclose a link to the video.

https://youtu.be/qP6O3oVJ3eM
https://youtu.be/cs8mnnaL1KQ

PS:
The print speed menu works as expected.
After opening the menu, the speed 100/100 is displayed and can be increased or decreased

**Comment by rondlh** [comment]
It will be very difficult to help you if you do not provide basic required information. Please have a look at the bug report template and add the requested information.

**Comment by radek8** [comment]
I don't think there's a problem with my configuration. The problem will be in the fan menu logic. The problem is easily reproducible.
For completeness, I will add the information you require in the evening when I am at the printer.

**Comment by kisslorand** [comment]
@radek8 
I am on it, will have a fix most probably today.

**Comment by kisslorand** [comment]
Check https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/2291/commits/a011780e6d6741989fa8916297a77e0beed194e6

**Comment by radek8** [comment]
@kisslorand 
Your patch works great.
You're a great programmer.
Thank you.

**Comment by radek8** [comment]
@kisslorand 
If you write in the description of your PR:
resolves #2319
This ticket will be tied to your PR. The ticket will be marked with an icon that a fix exists. Your PR will have an icon that solves the problem. After merging, the ticket with the problem will be closed automatically.

**Comment by kisslorand** [comment]
There's a new PR (#2349) that fixes this bug.
