### ISSUE TITLE
[BUG] Incorrect spelling in config.ini and config_rrf.ini

### ISSUE THREAD

**Issue by rondlh** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2323]
### Description
Not really a bug, but something that could be improved. The spelling of the following words in config.ini and config_rrf.ini is incorrect.
Note that some of these words are used in keyword, so if they would be updated then this will have consequences elsewhere. At least updating the comments would make sense in my view.
Here the list of words I found:
baudrate --> baud rate
english --> English
fullname --> full name
speeed --> speed
encorder --> encoder
etc --> etc.
Backgroud --> Background
minimun --> minimum
Fullscreen --> Full screen
fullscreen --> full screen
characthers --> characters
invertion --> inversion
usefull --> useful
reacheable --> reachable 
miliseconds --> milliseconds
conjuction --> conjunction
Filamanent --> Filament
begining --> beginning
Feedrate --> Feed rate
feedrate --> feed rate

**Comment by digant73** [comment]
Thanks for the checks. Fixed on my PR.
I didn't changed the following words. They should be ok also as they are (commonly used).
baudrate
english
fullname
fullscreen
feedrate
