### ISSUE TITLE
[BUG] Marlin K-Factor calibration broken

### ISSUE THREAD

**Issue by Hukuma1** [bigtreetech/BIGTREETECH-TouchScreenFirmware#233]
Using standard Marlin code generator to tune k-factor settings. The bed temp shows it trying to be set to 115, instead of 60.

### Steps to reproduce

1. http://marlinfw.org/tools/lin_advance/k-factor.html
2. Generate code for your machine settings.
3. Print it.

**Expected behavior**
Bed temp raises to 60 and starts print.

**Actual behavior**
Bed tries to raise temp to 115.

### Additional Information
https://pastebin.com/12LhRcfA

**Comment by guruathwal** [comment]
That's strange. Did you set preheat before it?

**Comment by Hukuma1** [comment]
Nope. And definitely never to a weird number like 115.

If you run it, does it work fine? :/

**Comment by guruathwal** [comment]
Not tried it yet.. I just saw this issue now..😊

**Comment by Hukuma1** [comment]
Just tried running same code in Marlin mode and it worked as expected. So it's definitely an issue with Touch Mode/firmware.
