### ISSUE TITLE
[BUG] Portrait Mode print summary broken

### ISSUE THREAD

**Issue by radry** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2337]
The Print Summary screen when using Portrait Mode is broken.
Also, the "back" button doesn't work (the touch field is invisible and above the back button in the same location the Babystep icon is during the print).

I think it's this part in PrintingMenu.c that causes it:
Line 492 ff

```
void drawPrintInfo(void)
{
  GUI_SetTextMode(GUI_TEXTMODE_TRANS);

  IMAGE_ReadDisplay(rect_of_keySS[KEY_INFOBOX].x0, rect_of_keySS[KEY_INFOBOX].y0, INFOBOX_ADDR);

  GUI_SetColor(INFOMSG_BG_COLOR);
  GUI_DispString(rect_of_keySS[KEY_INFOBOX].x0 + STATUS_MSG_ICON_XOFFSET, rect_of_keySS[KEY_INFOBOX].y0 + STATUS_MSG_ICON_YOFFSET,
                 IconCharSelect(CHARICON_INFO));
  GUI_DispStringInRectEOL(rect_of_keySS[KEY_INFOBOX].x0 + BYTE_HEIGHT + STATUS_MSG_TITLE_XOFFSET,
                          rect_of_keySS[KEY_INFOBOX].y0 + STATUS_MSG_ICON_YOFFSET,
                          rect_of_keySS[KEY_INFOBOX].x1 - STATUS_MSG_TITLE_XOFFSET,
                          rect_of_keySS[KEY_INFOBOX].y1 - STATUS_MSG_ICON_YOFFSET,
                          (uint8_t *)textSelect(LABEL_PRINT_FINISHED));

  GUI_SetColor(INFOMSG_FONT_COLOR);
  GUI_SetBkColor(INFOMSG_BG_COLOR);
  GUI_DispStringInPrect(&msgRect, LABEL_CLICK_FOR_MORE);
  GUI_RestoreColorDefault();
}
```

The problem is it uses the same box as the status screen. But this doesn't work with the portrait printing menu.
I would fix it myself but I don't have a good solution how it should look like, since it's a unique Layout for portrait mode.
The easiest solution is probably to supress this status box in the print summary when using portrait mode. Instead show nothing or a popup box.

### Steps to reproduce

1. Be in Portrait Mode
2. Finish a print

**Actual behavior**
![DSC_1155](https://user-images.githubusercontent.com/8878118/150401857-a7e4d3ad-caf8-434c-83d5-2fffecac225e.JPG)

### Hardware Variant
TFT24
### TFT Firmware Version & Main Board Firmware details
Current master

**Comment by digant73** [comment]
assuming there is no space enough to display the box on the right of the fan icon, it seems the box must be suppressed

**Comment by radry** [comment]
@digant73 
The info box is as wide as two normal icons. As you can see compared to the bottom row, there isn't enough space next to the fan icon for that.

**Comment by digant73** [comment]
yes I see. Unfortunately it seems the only viable option is to remove that info

**Comment by radek8** [comment]
If the "Main" icon moves up over the "Back" icon, there is enough space in the information field to the left of the "Back" icon

**Comment by digant73** [comment]
@radek8 yes thanks. that should be the better choice. Currently I'm focused to fix some other issues. If this issue is not fixed by someone else I will see it in the future

**Comment by radry** [comment]
@radek8 
Yes but it would require a separate "layout" just for this one screen and a lot of code rewrite. I don't see much benefit in this infobox anyway. I think it would be easier to call a "popup" window that says "print finished".
