### ISSUE TITLE
strength looking icons TFT35 v3.0

### ISSUE THREAD

**Issue by andrzej1974** [bigtreetech/BIGTREETECH-TouchScreenFirmware#236]
Hello.  
![20191212_203942](https://user-images.githubusercontent.com/58828260/70746729-b0c6c200-1d26-11ea-9dab-779ace271610.jpg)
After compilation in VSC.   - Tft35 v3.0, bigtreetech software and uploading to Display i have in the Print menu  in the file selection list strange squares  on the icons with arrows.   if i upload firmware to the display  i putt ofcourse TFT35 catalog with BMP and fonts  on sd card.  I use  unified firmware. Somebody tell how delete this squares?

**Comment by carl1961** [comment]
have you tried the already compiled bin files? to test

**Comment by andrzej1974** [comment]
i try and is ok but I have to make modification in firmware, because dont
see long filename from onboard sd card. But if I compile original without
modification also is the same issue.

czw., 12 gru 2019, 23:20 użytkownik carl1961 <notifications@github.com>
napisał:

**Comment by carl1961** [comment]
to me it looks like pictures on top of the other

**Comment by guruathwal** [comment]
> i try and is ok but I have to make modification in firmware, because dont see long filename from onboard sd card. But if I compile original without modification also is the same issue. 

@andrzej1974  what code did you modified? 
**There are some variable that do not need to be changed in any case!!** 
Can you share the changes you made?

**Comment by andrzej1974** [comment]
This one
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/235
But before modification i allready have this issue, from first compilation
without touching  anything. Just fresh compilation and upload directly to
TFT this square was visible

pt., 13 gru 2019 o 11:36 guruathwal <notifications@github.com> napisał(a):

**Comment by guruathwal** [comment]
> This one #235 But before modification i allready have this issue, from first compilation without touching anything. Just fresh compilation and upload directly to TFT this square was visible

ok... looks like it got messed up after #205

**Comment by andrzej1974** [comment]
I have already implemented it drom (#236)

pt., 13 gru 2019, 18:44 użytkownik guruathwal <notifications@github.com>
napisał:

**Comment by andrzej1974** [comment]
sorry this one (#205)

pt., 13 gru 2019, 20:22 użytkownik Andrzej <andacz6@gmail.com> napisał:

**Comment by guruathwal** [comment]
> I have already implemented (#205) 

@andrzej1974  #205 messed up the list view. you need to use the source before this commit for now.

**Comment by guruathwal** [comment]
Fixed via PR #246

**Comment by guruathwal** [comment]
@andrzej1974  please close the issue
