### ISSUE TITLE
Bug change filament

### ISSUE THREAD

**Issue by valerox84** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2366]
### Description

you heat to make the change of filament, you give it to load and does not give you option to download filament, all the time gives the user to paused

### Steps to reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior**

**Actual behavior**

### Additional Information
* Include a ZIP file containing your `Configuration.h` or use [Pastebin](https://pastebin.com/) and paste a link in this issue.
* Provide pictures or links to videos that clearly demonstrate the issue.

**Comment by digant73** [comment]
In Marlin, enable all the settings reported at the beginning of TFT's config.ini file

**Comment by valerox84** [comment]
If I have everything enabled in configuration.adv, instead in marlin mode it does it perfectly, instead in tft mode that error happens.
my board is skr e3 dip

**Comment by digant73** [comment]
What's the version of Marlin?

**Comment by valerox84** [comment]
version 2.0.7.2 btt e3 dip,I always used the marlin mode version, but lately the screen gets strange symbols, instead in tft mode it works fine, but the change of filament is what does not work.

**Comment by radek8** [comment]
Version 2.0.7.2 is more than a year old.
Update to new versions.
Attach the Marlin configuration files.

**Comment by digant73** [comment]
The minimum Marlin version required by the TFT fw is 2.0.8.1. I suggest to move to latest Marlin fw (e.g. 2.0.9.3 or even 2.0.9.1)

**Comment by oldman4U** [comment]
@valerox84

Usually the owner of a ticket answers so that those trying to help know what's going on. 

Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
@Msq001 Please close this ticket.

Thank you
