### ISSUE TITLE
Updated Firmware on TFT35 E3 V3.0 : Now No Printer Attached

### ISSUE THREAD

**Issue by QuestionDevelopment** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2370]
Hello everyone, I had a SKR TFT35 E3 V3 connected to an SKR Mini E3 V2. Was working perfect. I updated the firmware and now it only says "No Printer Attached". What I've done so far

Double checked all cables

Updated motherboard to newest stable release of marlin

Via octoprint (after update above) and ran M502 + M500

I also have this exact same TFT35 firmware running without issue on with an TFT35 E3 V3 attached to a SKR v2. I looked through the config and didn't see any specific options that should be different but maybe that is introducing errors somehow?

#define SERIAL_PORT 1#define BAUDRATE 115200

#define SERIAL_PORT_2 3#define BAUDRATE_2 115200

I've tried other values too

Also...on the SKR V2 I had what tutorials said to use

#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER

However if I try that on the newest version of firmware I get the fatal error

Only CR10_STOCKDISPLAY, ZONESTAR_LCD, ENDER2_STOCKDISPLAY, MKS_MINI_12864, and TFTGLCD_PANEL_(SPI|I2C) are currently supported on the BIGTREE_SKR_MINI_E3

So I am running CR10_STOCKDISPLAY which people have said works but this very well could be the issue??

Thanks for any help

**Comment by radek8** [comment]
You cannot use the same configuration on SKR 2 and SKR mini E3 V2
SKR 2 uses serial port 1
SKR mini E3V2 uses serial port 2
The CR10_STOCKDISPLAY option is OK. It affects the display of the simulated Marlin mode

**Comment by shafr** [comment]
I had issue on TFT24 just now - had to go to configuration on TFT display & manually change it to 250 000. Marlinfw2.0 experimental.

**Comment by QuestionDevelopment** [comment]
I tried many different configurations for my serial ports.    My original marlin firmware was working fine for over a year.  On the newest version I tried the same settings with no connection. Can you please tell me the marlin settings I need for TFT35 E3 V3 and using an octopi. If there are firmware settings for the screen what are they?  Thank you.

**Comment by QuestionDevelopment** [comment]
I all the combinations of serial_port / serial_port_2 that I could think of with no help.  I made sure both TFT35 were running at 115200 and it did not work.  I made sure both were running at 250000 and it did not work.

**Comment by radek8** [comment]
What kind of HW do you have?
In the first post you write that you have a SKR mini E3 V2.
Then you wrote about SKR 2.
In the last post, you have an octopus.
First they figured out what kind of HW you have. Then copy the Marlin configuration files here, and the ini file from TFT.

**Comment by radek8** [comment]
All necessary settings are described here:

https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware

**Comment by QuestionDevelopment** [comment]
Everything I stated above was correct.  I am having issues with my SKR MINI E3 V2 connecting to my TFT35 E3 V3.  It was working fine prior to updating the firmware.  I have a SKR 2 working perfectly with a TFT35 E3 V3.  Both have octopi running on them but they are not part of this equation.  I am able to send commands to both boards without issue.  

All firmware settings in the link provided are setup.

**Comment by radek8** [comment]
Send configuration files to SKR mini E3 V2 and TFT

**Comment by QuestionDevelopment** [comment]
**platform.ini**
(I tried both STM32F103RE_btt + STM32F103RE_btt_maple)
[https://pastebin.com/6N2Pun6q](https://pastebin.com/6N2Pun6q)

Configuration.h
(I tried all combinations of serial_ports and baudrates)
[https://pastebin.com/uhDUzNM1](https://pastebin.com/uhDUzNM1)

Configuration_adv.h
[https://pastebin.com/yEq4v3Ck](https://pastebin.com/yEq4v3Ck)

**Comment by QuestionDevelopment** [comment]
Here is the TFT config.ini
https://pastebin.com/SvSke1EJ

**Comment by radek8** [comment]
In Marli you have defined serial port 2 at 250000
On the TFT, the port speed is defined at 115200
The port number (2) is fine, but the speeds are not the same.
Set the same port speed on the TFT

**Comment by radek8** [comment]
If you have set up and TFT reports the printer is not connected, check the cables.
Send a photo of the connection

**Comment by radek8** [comment]
If you connect this TFT to the SKR 2 printer and set the same speed, will it also work with SKR2?

**Comment by QuestionDevelopment** [comment]
So much of a mess here...I'm not clear what fixed things..

Here are the serial port settings that worked for me : 

#define SERIAL_PORT 2
#define SERIAL_PORT_2 -1

I had baudrate @ 250000 for board firmware + in the GUI of the display.  When I switched the board firmware to 115200 it started communicating.  This leads me to believe either this setup can't run at 250000 or the TFT GUI is not properly updating the baudrate.

So my "No Printer Attached" message went away but nothing worked...I basically got lucky and found that the system is 100% unresponsive unless you have a sdcard in the board.  I have no idea why.

After that when I was trying to figure out how invert my z axis via the gui (which I couldn't find the settings) I "restored defaults" on the TFT...this caused me to lose connection again.  The fix for that was to flash the firmware again with a serial_port setting of P1:5 (11520).  The settings in the system would do nothing.  The strange thing about this one is...it didn't work for a few minutes despite multiple restart/power up and down.  I got frustrated...didn't touch it for maybe 3 minutes or so and then it started working properly. 

So I flashed the TFT firmware again with inverted axis and it did a similar thing...didn't work after restarting / power cycling....Settings -> Features -> Restore Defaults -> Power cycle....connect to machine right away.   Z axis still wasn't inverted....flashed again.  Same exact thing...with the not connection AND the working after restore defaults AND the not inverted axis.  Tried again...same exact thing.

There doesn't seem to be an option in the GUI so I have no way to invert the Z axis...another thing broken in the firmware I assume.

**Comment by QuestionDevelopment** [comment]
I'm going to close this I guess.  I opened another for the z axis issue

https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/2373

**Comment by digant73** [comment]
@QuestionDevelopment You should first know that all the settings in config.ini have an equivalent (hard coded) in TFT's Configuration.h file (used at compile time). If you install the TFT fw not providing any config.ini file or if you reset the settings, the hard coded settings will be used. That explain why you have different behaviors when resetting the settings. Your hard coded values differ from the values configured in config.ini.
"inverted_axis" setting can not be set by GUI (as many other settings) because it is a settings that you configure once and never again in the future.
If you configured a baudrate of 115200 in mainboard, do the same in the TFT (you can change it also from the GUI)

**Comment by QuestionDevelopment** [comment]
@digant73 : Thank for the explanation.  Unfortunately the config settings are getting ignore/not utilized.  It is clear there are many bugs in this firmware.

**Comment by radek8** [comment]
Currently, FW is functional and without serious errors that would prevent their use.
A few minor bugs that were recently discovered already have rights in PR.
None of the known bugs are related to your issue.
So far, this looks like a bug in your configuration.
Why are you insulting people who work on this project selflessly and for free.

**Comment by QuestionDevelopment** [comment]
My apologizes if I came off as insulting.  That was not my intention.  The fact remains that there is many bugs in this firmware.  It is very clearly not loading settings properly. 

I'm shocked to hear that Bigtreetech is not paying for firmware.  I don't think I will be supporting them as a company any longer.

**Comment by radek8** [comment]
> 
> After that when I was trying to figure out how invert my z axis via the gui (which I couldn't find the settings) I "restored defaults" on the TFT...this caused me to lose connection again. The fix for that was to flash the firmware again with a serial_port setting of P1:5 (11520). The settings in the system would do nothing. The strange thing about this one is...it didn't work for a few minutes despite multiple restart/power up and down. I got frustrated...didn't touch it for maybe 3 minutes or so and then it started working properly.
> 

Settings
P1: 5
does not set speed 115200 but sets speed 57600.
read the explanations carefully
P1: 6 sets speed 115200

**Comment by radek8** [comment]
FW loads the settings correctly, but you are inattentive to the configuration.

**Comment by QuestionDevelopment** [comment]
Oh my...that was it all along?  My apologizes... I did not realize.
