### ISSUE TITLE
[FR] (Allow for recovery flash using serial / platformio)

### ISSUE THREAD

**Issue by shafr** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2371]
**Is your feature request related to a problem? Please describe.**
After latest update .29 my TFT24_v1.1 stopped working - no touch & white screen

**Describe the solution you'd like**
IT would be nice if there was an instruction how to do emergency recovery / flash using Serial adatper using PC & Platformio

**Describe alternatives you've considered**

**Additional context**

**Comment by radek8** [comment]
Did you use reset with the reset.txt file?

**Comment by radek8** [comment]
What version of .29?
The current version is TFT24_V1.1.27

**Comment by shafr** [comment]
@radek8 - sorry, yes version is .27.
Also - what is the difference between:
* BIGTREE_GD_TFT24_V1.1.27.x.bin
* BIGTREE_TFT24_V1.1.27.x.bin

What's GD? 

MY main concern now - that touch had stopped working with .27, like UI buttons do not react, but the physical touch is working (backlight dims & lights up again)

**Comment by radek8** [comment]
GD is a different HW.
You must use the correct version.
perform a reset after the update.
Copy the empty reset.txt file to the card, paste it into the TFT and turn on the display.

**Comment by shafr** [comment]
Copying `reset.txt` helped. Thank you.

**Comment by shafr** [comment]
Copying `reset.txt` helped. Thank you.
