### ISSUE TITLE
Can't invert Z axis on TFT35

### ISSUE THREAD

**Issue by QuestionDevelopment** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2373]
Tried both 

`inverted_axis:X0 Y0 Z0 LY0`

and

`inverted_axis:X0 Y0 Z1 LY0`

in config.ini  No difference. I am forced to go into features "restore defaults" for my screen to connect to the board.  I don't know if this introducing errors but I have no choice.  There is no ability to make the change via the GUI that I can find.  Using a SKR Mini E3 V2 if that matters...both screen + board have the most recent firmware.

**Comment by oldman4U** [comment]
See #2368 and post there and close this ticket as it is a duplicate. 

Thank you
