### ISSUE TITLE
[BUG] Artillery Genius filament sensor not working after update

### ISSUE THREAD

**Issue by Alpacad** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2374]
### Description
I'm working on my friend's Artillery Genius, after flashing the bigtreetech tft firmware the filamente runout sensor has stopped working. This was months ago and we simply decided to wait some bug fixes. After reading about #2007 and the fix #2018 we decided to retry.
But the problem is still there. The sensor is red during flashing, then turns green even when the filament is not inserted.

### Steps to reproduce

1. Download the latest firmware
2. Customized config.ini to match Artillery Genius values
3. Flash firmware

**Expected behavior**
Filament sensor should work without problems.

**Actual behavior**
Filament sensor led is constantly green and a print cannot be started unless deactivated from the menu.

### Hardware Variant
MKSTFT28
### TFT Firmware Version & Main Board Firmware details
MKS_TFT28_NEW_GENIUS.27.x.bin
Marlin 2.0.9.3 on MKS Gen L 1.0

### Additional Information
Attached files:
- config.ini
- Configuration.h

[GeniusFiles.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/7989682/GeniusFiles.zip)

**Comment by kisslorand** [comment]
> Filament sensor led is constantly green...

Is it like this regardless of filament being present or not?

**Comment by kisslorand** [comment]
Try with MKS_TFT28_V4.0.27.x.bin.

**Comment by Alpacad** [comment]
Already tried, without success. Used the same config file and firmware version.

**Comment by kisslorand** [comment]
The printer is a Genius Pro (with BlTouch like leveling sensor)?

**Comment by Alpacad** [comment]
No, it's not mine, but I'm pretty sure it's not a Pro. No bltouch-like sensor or 32 bit mainboard. It has the  dedicated expansion port on the side and MKS Gen L 1.0 (atmega2560 based) board.

**Comment by kisslorand** [comment]
The things you described is the result of the filament runout detection sensor being connected to other pins than the MCU on the TFT expects it.
I see two possible fixes:
1. make a FW patch to reflect the actual connection
2. reconnect the filament runout sensor to other pins on the TFT

I can help with either of then but I recommend to rewire the sensor so it will work with every future FW release.

I made two test files for you to try, they are meant to test if the sensor is connected to other pin than expected on the TFT.
These files are based on the master version so it's safe to use any of them.
Here's the link: https://mega.nz/folder/vthEHaBa#Ql5oXvKNm34Ji3mJrs3DpA

**Comment by Alpacad** [comment]
I've passed the files to my friend. He said he'll try them this weekend, I'll let you know.

**Comment by Alpacad** [comment]
Sorry, @kisslorand, my friend didn't try to flash the files yet. 
Please, accept my apologies. As I said, I'll let you know as soon as he texts me the results.

**Comment by Alpacad** [comment]
Here we are. He says that none of the files worked for him, and the sensor remains green all the time.
Just to be sure, these .bin files had to be flashed alone or included with the other .ini and folders?

**Comment by kisslorand** [comment]
They not need newer or other files that are already used for the master branch. So, yes, it's enough to flash the bin files alone.
As for the persistence of the issue... I would need a picture of the TFT's back side as clear as possible in the region where the filament sensor is connected. 

Something jus caught my eyes... The LED is constantly green? Isn't green supposed to mean that there IS filament? Yet the TFT sees trigger for no filament?

**Comment by oldman4U** [comment]
What is the status of this ticket?

Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by Alpacad** [comment]
I'm still waiting a response, my friend is a bit lazy when it comes to test something or fix problems. I have to remind him daily.
It's funny because yesterday he was printing holders and asking me for a custom firmware with bltouch and auto bed levelling.

**Comment by kisslorand** [comment]
> I'm still waiting a response, my friend is a bit lazy when it comes to test something or fix problems.

Than I guess it will be no problem if we'll get lazy fixing his problems...

**Comment by Alpacad** [comment]
These are the photos that he sent to me. As for the parameter, he said that it does not let him print.

![IMG-20220221-WA0030](https://user-images.githubusercontent.com/82800736/154920552-836a776b-692c-43e3-bcb0-db5668ec585c.jpg)
![IMG-20220221-WA0031](https://user-images.githubusercontent.com/82800736/154920559-4a8510fc-8b1b-4d16-a611-8d4b87178efd.jpg)
![IMG-20220221-WA0032](https://user-images.githubusercontent.com/82800736/154920565-3439fd06-b900-4a6d-8792-134a9bf0f0d3.jpg)

**Comment by kisslorand** [comment]
From the pictures it is a newer Genius it must work with NEW_GENIUS FW. Maybe it worth a try and move the filament sensor connector to the next row of pins (B0) and try with regular Genius FW.
As for the printer not working with neither settings for the  "fil_runout_inverted" parameter, something is fishy. It's just simply not possible. Something else also must happened, not just a simple FW update. 
What happens if the connector is unplugged from the sensor and  "fil_runout_inverted" is tested with both values (0 and 1)?

**Comment by Alpacad** [comment]
@kisslorand we may have discovered a bad connection between the tft the jst-xh connector. I'll make him do some more tests and let you know.
If if that's it, we may consider rewiring the connector (maybe with a dupont one) and putting a drop of hot glue.

**Comment by oldman4U** [comment]
So the title of this ticket is wrong and the ticket is not related to the update, or kisslorand's code is now even able to break cables;-)

May the force be with you

**Comment by Alpacad** [comment]
Could be something my friend did while upating the firmware, like pulling the cable. So seeing this after the update, first thing was thinking about a possible bug.

Anyway, it seems that now it changes color to green when the filament is inserted and red when removed. But it doesn't seem to stop when trimming it. We'll do some other tests.

**Comment by Alpacad** [comment]
Update:
Filament sensor color works as expetced, but it doesn't trigger filament runout script. If fil_runout_inverted is set to 1, it triggers immediatly with or without filament.

**Comment by kisslorand** [comment]
Where is it the sensor connected now (B0 or B1) and what FW was used?

**Comment by kisslorand** [comment]
@bigtreetech 
I think this can be closed. The user (or his friend) is not interested in resolving his own issue.

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
@Msq001

Please close this ticket

Thank you

**Comment by Alpacad** [comment]
Closing due to lack of interest by the user.

**Comment by jamarju** [comment]
I had this same problem. The fix was setting the sensor pin to B0 instead of B1. On `pin_MKS_TFT32_V1_4.h` replace this:

```C
    #define FIL_RUNOUT_PIN PB1
```

with this:

```C
    #define FIL_RUNOUT_PIN PB0
```

**That's in spite of the connector being connected to B1 according to the board's silkscreen**. See photos below. Perhaps the PCB silkscreen is wrong, in retrospect I should have traced the header back to the actual MCU pin but now I'm too lazy to take the printer apart. Anyway, B0 works, yay!

![IMG_6585](https://user-images.githubusercontent.com/1566645/208908771-231c7392-53a7-40bf-9730-612b6504f223.jpg)
![IMG_6586](https://user-images.githubusercontent.com/1566645/208908774-64013a30-cda9-47bb-9227-ad4b2bd97d87.jpg)
![IMG_6587](https://user-images.githubusercontent.com/1566645/208908779-df9ec0f4-9f79-419b-8b50-d5898d774891.jpg)
![IMG_6759](https://user-images.githubusercontent.com/1566645/208908794-f198a242-b470-4a1d-a85d-868cc1b98fbd.jpg)
