### ISSUE TITLE
[BUG] failed to enable bed leveling after setting deafult

### ISSUE THREAD

**Issue by jnslnk** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2378]
Hey there,
after i set my Printer settings to deafult the display shows: "failed to enable bed leveling"
I've got a BIQU B1 (SKR V1.3) with no probe, so i don't under stand why it's trying to ABL anyway ?!
Anything i can do in Marlin Firmware or by sending the Printer some G-Code, to tell it it doesn't need to probe?
Thx 4 helping!

**Comment by radek8** [comment]
You probably have some kind of bed leveling set up in the Marlin configuration.
Please correct the Marlin configuration and you will not receive an error.

**Comment by radek8** [comment]
If you do not want to level the bed, you must comment on all these parameters

_//#define AUTO_BED_LEVELING_3POINT
//#define AUTO_BED_LEVELING_LINEAR
//#define AUTO_BED_LEVELING_BILINEAR
//#define AUTO_BED_LEVELING_UBL
//#define MESH_BED_LEVELING_

**Comment by radek8** [comment]
Set the parameter in the TFT configuration file _config.ini_
auto_load_leveling: 0

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
@Msq001 

Please close this ticket.

Thank you
