### ISSUE TITLE
Bigtreetech TFT43 Install fehler

### ISSUE THREAD

**Issue by boehm23** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2386]
Hallo,
 Ich bekomme keine Updates auf das Bigtreetech TFT43 V3.0 installiert Er bleibt immer hängen 
Mainboard ist Das SKR CR6 
wäre über hilfe Dankbar 
### diese Dateien habe ich verwendet
(BIGTREE_TFT43_V3.0.27.x-(THEME_Unified Menu Material theme/TFT43),config,language_de

PS sry ich bin ein kompletter Neuling in diesem Bereich
vielen Dank
![IMG_1683](https://user-images.githubusercontent.com/99364250/153295027-90b1952f-0a1e-466e-932a-f22b19423129.JPG)
![IMG_1684](https://user-images.githubusercontent.com/99364250/153295033-0fd157e5-2ab7-4727-93d8-a2d0e6dfc386.JPG)
![IMG_1685](https://user-images.githubusercontent.com/99364250/153295038-a3758bb7-beda-47f5-be08-04d6f3d7d095.JPG)

**Comment by kisslorand** [comment]
If you would have taken the curtesy to read the rules you would have found out that the spoken language around here is English.
Please play by the rules.

**Comment by oldman4U** [comment]
And please read the ReadMe and the text on the screen before starting a ticket here.

This is not a user group but the BTT TFT FIRMWARE REPOSITORY. 

Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by rondlh** [comment]
The Icons and fonts need an update, copy the required files to your SD card, insert into TFT and restart the display... 
Please close this ticket asap.
