### ISSUE TITLE
[Q] FYSETC SD-WIFI

### ISSUE THREAD

**Issue by xhejtman** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2387]
Is there anyone that manage FYSETC SD-WIFI card to get working with TFT35? I have one and I got mostly sd card init failed. It seems there is an issue maybe with timing or something. Not sure it is quite TFT35 related. I managed to fix fw of SD-WIFI so that WebDav interface works but it works only if it is not inserted into TFT35 card slot. It appears that TFT blocks somehow the card, so ESP is unable to read anything from the real card. Any ideas?

**Comment by oldman4U** [comment]
BTT does not work either: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/1343 Error working with BTT SD Cloud after a print

**Comment by xhejtman** [comment]
It is a bit pitty that BTT SD Cloud does not work with BTT TFT35 E3 V3.0 ;)

**Comment by oldman4U** [comment]
It does not work at all. ;-(

xhejtman ***@***.***> schrieb am Do. 10. Feb. 2022 um 12:36:

**Comment by oldman4U** [comment]
Upload over WIFI would be great. I guess such a TFT would cost a bit more. 

Please help the community and close the ticket once you do not need it anymore. Thank you
