### ISSUE TITLE
[QUESTION] Who has TFT24 or TFT28? need to check new UI.

### ISSUE THREAD

**Issue by guruathwal** [bigtreetech/BIGTREETECH-TouchScreenFirmware#239]
Who has TFT24/28 and can test the firmware for checking the UI? need to check the new toggle interface before I create the PR?
here: https://github.com/guruathwal/BIGTREETECH-TouchScreenFirmware-MOD

post photo or video if possible.

**Comment by oldman4U** [comment]
Hello guruathwal.

I have an SKR Pro v1.1 with a TFT28 running the latest firmware and this combination is not in production but only for testing. How can i help you? Is there a particular area i should check or just upload and see if everything seems to work?

Would be a pleasure for me to give back a little bit;-)

Georg

**Comment by guruathwal** [comment]
@oldman4U  thanks.. all I need to test is the UI for TFT in the `setting menu->feature settings` & `setting menu->printer settings>custom menu`.
you can download the firmware for your variant from here: https://github.com/guruathwal/BIGTREETECH-TouchScreenFirmware-MOD

**Comment by oldman4U** [comment]
I will do so and let you know in approximately 10h from now.

Kind regards

**Comment by oldman4U** [comment]
Hi again.

So I downloaded the files from the link above, copied the BIQU_TFT28_V1.0.25.1.bin and the TFT 28 folder onto an SD card, inserted the card into the reader of the display and turned everything on. It uploaded the firmware, then the font and the bitmaps. I got the Ready in the upper left corner so this looks ok for me. Attached are some screenshots for verification that what I see is really the expected result. I can press the items in the list and get gCodes back, even it says unknown command when I try to release the SD card. Pressing "Hide Terminal ACK" modes the red button and makes it green and vice versa. "Auto Power" stays red (guess something in Marlin is missing;-))

Hope this helps. Please let me know if you need anything else

Thank you
![IMG_6698](https://user-images.githubusercontent.com/54359396/70930172-d6104480-2034-11ea-8102-5944af783ce3.JPG)
![IMG_6699](https://user-images.githubusercontent.com/54359396/70930192-ddcfe900-2034-11ea-9bba-e92a71fded03.JPG)
![IMG_6700](https://user-images.githubusercontent.com/54359396/70930199-e1fc0680-2034-11ea-9f4f-81ce8a014b34.JPG)

**Comment by guruathwal** [comment]
@oldman4U  thanks for the review..
>Pressing "Hide Terminal ACK" modes the red button and makes it green and vice versa. "Auto Power" stays red (guess something in Marlin is missing;-))

its not in marlin, some variant of the TFT does not support runout sensor Pins and auto shutdown pins, it need to be fixed in TFT firmware..

**Comment by oldman4U** [comment]
OK, understand.

Please let me know if there is anything else i can help with.

;-)

**Comment by oldman4U** [comment]
Hello guruathwal.

May I ask you 3 questions please?

1. Is it always like this, that you ask for help but not a single user is there to help you?
2. Would it be useful for you, if I would buy a TFT24, so I can test it in the future?
3. Maybe you have seen the other ticket #243. Has this part of the firmware something to do with it and if yes, how can I activate this and what's needed for it?

 * Enable gocde files list mode
 * It is friendly to display long file name, but the model preview feature is not available
 * Disable this if you want to use the model preview feature

Thank you

**Comment by guruathwal** [comment]
@oldman4U  Thanks
1. Most of the time. I try to help wherever I know anything about the issue. 
2. That would be nice. But the tft24 and 28 have the same screen resolution so testing on one of them would be enough.
3. Displaying the preview while printing is not yet implemented. You can disable list view if you want to display model preview in file viewer, but you will have to manually create preview bmp file for each gcode file with application provided by BTT. As far as I have seen yet in almost all the display available, the model preview is to be created manually. I don't think its worth to do all those procedure just to preview the image on the icon which will be visible Only for 5 seconds, and deleted after printing.

**Comment by Hukuma1** [comment]
BTT needs to write a Cura plugin that will export a snapshot of model on save of file. Creating the previews right now is too cumbersome.

**Comment by oldman4U** [comment]
Good morning.

Ok, so i will spend my money for something else;-)

Thank you for the answer, also to you Hukuma1.

Happy holidays

**Comment by ETE-Design** [comment]
@guruathwal Would it be possible to "Clone" MKS Cura Plugin? It can do preview pictures also.

**Comment by oldman4U** [comment]
@guruathwal 

Sorry to bother you. Would you or another "senior" engineer so kind to have a look at this ticket. Could be a Marlin issue, eventually.

Thank you

https://github.com/bigtreetech/BIGTREETECH-SKR-PRO-V1.1/issues/103

**Comment by guruathwal** [comment]
@oldman4U I don not even know the E of an engineer. I graduated in Finance Major :)
To me, it looks like a Marlin related issue if there is no hardware issue.

**Comment by guruathwal** [comment]
Hi @oldman4U 
Need to test some changes to the firmware. can you help?

**Comment by oldman4U** [comment]
Hi Guru. It would be a pleasure for me to help you. I have a TFT28 and a
TFT35 E3 v3. Please let me know how i can help you.

Georg

Gurmeet Athwal <notifications@github.com> schrieb am Mi. 3. Juni 2020 um
16:38:

**Comment by guruathwal** [comment]
Great.. can we continue through email? My email is on my GitHub profile.

**Comment by oldman4U** [comment]
Ahhh. Top secret. 😁I will contact you in about one hour.

Gurmeet Athwal <notifications@github.com> schrieb am Mi. 3. Juni 2020 um
18:01:
