### ISSUE TITLE
Errors on TFT35

### ISSUE THREAD

**Issue by jspring88** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2394]
I installed a new TFT35 connected to an SKR 2.0 using the EXP1 and EXP2 cables and the TFT cable.  I got it mostly working in both touch screen and Marlin mode.  I've encountered the following problems when trying to print in touch screen mode:

Error #1
When I start to print, the bed and nozzle heat up OK then it shows an error "Homing Failed", then the error "Printer Halted, Kill() Called" quickly follows.  I then have to press the reset button.  Once I reset, I reheat then try to print again and it successfully starts the print.

Error #2
The display shows the following errors before the print starts:
Unknown Command: "//G4 S1"
Unknown Command: "//Nozzle Wipe"
Unknown Command: "//M42 P6 S255"

There are other commented lines in my start/end Gcode that don't generate errors.  I know I can remove them but I'd like to know why the TFT35 is showing them rather than ignoring them.

Error #3
When I change filament and click the "Unload" button, It works properly but when I click the "Load" button it loads then displays:
"Pause by User"
I click OK but then quickly it again displays
"Pause by User"
this happens repeatedly and I am forced to reset the printer and reheat and load manually.

I've used this Gcode on a different display (Viki2) and board (Rambo 1.3) with none of the above problems.  It seems like these bugs are with the TFT35, not with the SKR 2.0 but I'm not sure.

Thanks for looking at this,
Jim

**Comment by kisslorand** [comment]
Is your Marlin configured as described in the Readme?

**Comment by jspring88** [comment]
Thank you for your responses.  I went through the Readme and uncommented the items listed.  It made no difference, same problems.  In my Gcode there are other commented lines that don't generate errors.  I'm wondering why the new board doesn't ignore commented out lines.

Also, as i said the first attempt at printing fails at 
"Printer Halted, Kill() Called"
But after I reset and start the print again it doesn't stop itself.  Do you think it might have something to do with saving a previous leveling mesh?

Thanks,
Jim


Below is my start & End Gcode:

;FLAVOR:Marlin
;TIME:21592
;Filament used: 7.83691m
;Layer height: 0.15
;MINX:98.712
;MINY:15.492
;MINZ:0.3
;MAXX:223.301
;MAXY:154.4
;MAXZ:39
;Generated with Cura_SteamEngine 4.13.0
M140 S55
M105
M190 S55
M104 S260
M105
M109 S260
M82 ;absolute extrusion mode
//M42 P6 S255 ; turn lights on
M106 P2 S255  ; turn Extruder lights on

G21 ; metric values

G90 ; absolute positioning

M82 ; set extruder to absolute mode

G92 E0 ; set extruder position to 0

G1 E-20 F125 ; Retract 20mm Filament

G28 F200 ; home all

G1 Z2 F1200 ; move bed up to the top

G28 X0 Y0 ; AutoHome X & Y

M204 S600 ; set accel for probing

M203 Z15; set z max speed for probing

G29 ; Bed Leveling

M204 S3500 ; set accel back to normal

M203 Z20 ; set z max speed back to limit

;G1 Z5 ; raise nozzle up 5mm

//M851 z-1.75 ; Moves the nozzle down to the right clearance above the bed for printing

//G1 E1 F100 ; extrude filament back into nozzle and 7mm more

//Nozzle Wipe
G1 X10 Y0 F4000 ; Move Nozzle to start point for wipe
G1 E1 F100 ; extrude filament back into nozzle and 7mm more
G1 Z0 ; Lower the Nozzle
G1 X60 E9 F200 ; Wipe Right extruding Filament
G1 Z5

G92 E0 ; zero extruder

M400 ; clear buffer

//G4 S1 ; pause

M117 AXIOM Printing... ;Put printing message on LCDE screen

End Gcode  

;EndCode

M400

G1 z5 ;Lower Bed 5mm

G1 x0 Y0 ;Move X & Y to Front Left

M104 T0 S0 ; switch off first nozzle

M104 T1 S0 ; switch off second nozzle

M140 S0 ; heated bed heater off

M107 ; fans off

T0

G92 E0 ; set first extruder to 0

G1 E-3 F300 ; retract a bit to relieve pressure

G28

M851 z0 ; Zeros out the nozzle clearance

M84 ; steppers off

G90 ; absolute positioning

M106 P2 S0  ; turn Extruder lights off
//M42 P6 S0 ; lights off--

M82 ;absolute extrusion mode
M104 S0

;End of Gcode0
M82 ;absolute extrusion mode
M104 S0
;End of Gcode

**Comment by kisslorand** [comment]
Comments should be marked with ";", not "//", that's for Error #2.

"G28 F200", "G28 X0 Y0" - wrong parameters for G28

Do you really have "G28" in your end code??? Very, very, very bad idea!

"T0" ??? What gcode is that???

For Error #3, are you sure the followings are all set?
```
HOST_ACTION_COMMANDS (in Configuration_adv.h)

HOST_PROMPT_SUPPORT (in Configuration_adv.h)

NOZZLE_PARK_FEATURE (in Configuration.h)

ADVANCED_PAUSE_FEATURE (in Configuration_adv.h)

PARK_HEAD_ON_PAUSE (in Configuration_adv.h)

FILAMENT_LOAD_UNLOAD_GCODES (in Configuration_adv.h)

```

**Comment by jspring88** [comment]
I cleaned up the start/End code:
I got rid of the commented lines
Changed "G28 F200" to "G28"
Changed "G28 X0 Y0" to "G28 X Y"  (I did this to Home X and Y)
"T0"  I don't know where that came from, it's gone now. Sorry about that
I have G28 in my End Code to home the printer so the bed lowers to the bottom (0) (it's a CoreXY) and the nozzle moves to the front, left corner.  I could replace that line with "G1 X0 Y0 Z0" if that's safer but it seems to work just fine.  Why is it a "very,very,very bad idea?"

For Error #3
I believe everything you listed is enabled.

Below are portions from my Configuration.h file. 
#define NOZZLE_PARK_FEATURE

#if ENABLED(NOZZLE_PARK_FEATURE)
  // Specify a park position as { X, Y, Z_raise }
  #define NOZZLE_PARK_POINT { (X_MIN_POS + 10), (Y_MAX_POS - 10), 20 }
  //#define NOZZLE_PARK_X_ONLY          // X move only is required to park
  //#define NOZZLE_PARK_Y_ONLY          // Y move only is required to park
  #define NOZZLE_PARK_Z_RAISE_MIN   2   // (mm) Always raise Z by at least this distance
  #define NOZZLE_PARK_XY_FEEDRATE 100   // (mm/s) X and Y axes feedrate (also used for delta Z axis)
  #define NOZZLE_PARK_Z_FEEDRATE    5   // (mm/s) Z axis feedrate (not used for delta printers)
#endif

Below are portions from my Configuration_adv.h file.   

#define HOST_ACTION_COMMANDS
#if ENABLED(HOST_ACTION_COMMANDS)
  //#define HOST_PAUSE_M76
  #define HOST_PROMPT_SUPPORT
  //#define HOST_START_MENU_ITEM      // Add a menu item that tells the host to start
  //#define HOST_SHUTDOWN_MENU_ITEM   // Add a menu item that tells the host to shut down
#endif


* Requirements:
 *  - For Filament Change parking enable and configure NOZZLE_PARK_FEATURE.
 *  - For user interaction enable an LCD display, HOST_PROMPT_SUPPORT, or EMERGENCY_PARSER.
 *
 * Enable PARK_HEAD_ON_PAUSE to add the G-code M125 Pause and Park.
 */
#define ADVANCED_PAUSE_FEATURE
#if ENABLED(ADVANCED_PAUSE_FEATURE)
  #define PAUSE_PARK_RETRACT_FEEDRATE         60  // (mm/s) Initial retract feedrate.
  #define PAUSE_PARK_RETRACT_LENGTH            2  // (mm) Initial retract.
                                                  // This short retract is done immediately, before parking the nozzle.
  #define FILAMENT_CHANGE_UNLOAD_FEEDRATE     20  // (mm/s) Unload filament feedrate. This can be pretty fast.
  #define FILAMENT_CHANGE_UNLOAD_ACCEL        25  // (mm/s^2) Lower acceleration may allow a faster feedrate.
  #define FILAMENT_CHANGE_UNLOAD_LENGTH      150  // (mm) The length of filament for a complete unload.
                                                  //   For Bowden, the full length of the tube and nozzle.
                                                  //   For direct drive, the full length of the nozzle.
                                                  //   Set to 0 for manual unloading.
  #define FILAMENT_CHANGE_SLOW_LOAD_FEEDRATE   5  // (mm/s) Slow move when starting load.
  #define FILAMENT_CHANGE_SLOW_LOAD_LENGTH     20  // (mm) Slow length, to allow time to insert material.
                                                  // 0 to disable start loading and skip to fast load only
  #define FILAMENT_CHANGE_FAST_LOAD_FEEDRATE   50  // (mm/s) Load filament feedrate. This can be pretty fast.
  #define FILAMENT_CHANGE_FAST_LOAD_ACCEL     25  // (mm/s^2) Lower acceleration may allow a faster feedrate.
  #define FILAMENT_CHANGE_FAST_LOAD_LENGTH     150  // (mm) Load length of filament, from extruder gear to nozzle.
                                                  //   For Bowden, the full length of the tube and nozzle.
                                                  //   For direct drive, the full length of the nozzle.
  //#define ADVANCED_PAUSE_CONTINUOUS_PURGE       // Purge continuously up to the purge length until interrupted.
  #define ADVANCED_PAUSE_PURGE_FEEDRATE        3  // (mm/s) Extrude feedrate (after loading). Should be slower than load feedrate.
  #define ADVANCED_PAUSE_PURGE_LENGTH         25  // (mm) Length to extrude after loading.
                                                  //   Set to 0 for manual extrusion.
                                                  //   Filament can be extruded repeatedly from the Filament Change menu
                                                  //   until extrusion is consistent, and to purge old filament.
  #define ADVANCED_PAUSE_RESUME_PRIME          0  // (mm) Extra distance to prime nozzle after returning from park.
  //#define ADVANCED_PAUSE_FANS_PAUSE             // Turn off print-cooling fans while the machine is paused.

                                                  // Filament Unload does a Retract, Delay, and Purge first:
  #define FILAMENT_UNLOAD_PURGE_RETRACT       3  // (mm) Unload initial retract length.
  #define FILAMENT_UNLOAD_PURGE_DELAY       5000  // (ms) Delay for the filament to cool after retract.
  #define FILAMENT_UNLOAD_PURGE_LENGTH         8  // (mm) An unretract is done, then this length is purged.
  #define FILAMENT_UNLOAD_PURGE_FEEDRATE      25  // (mm/s) feedrate to purge before unload

  #define PAUSE_PARK_NOZZLE_TIMEOUT           45  // (seconds) Time limit before the nozzle is turned off for safety.
  #define FILAMENT_CHANGE_ALERT_BEEPS         10  // Number of alert beeps to play when a response is needed.
  #define PAUSE_PARK_NO_STEPPER_TIMEOUT           // Enable for XYZ steppers to stay powered on during filament change.
  //#define FILAMENT_CHANGE_RESUME_ON_INSERT      // Automatically continue / load filament when runout sensor is triggered again.
  //#define PAUSE_REHEAT_FAST_RESUME              // Reduce number of waits by not prompting again post-timeout before continuing.

  #define PARK_HEAD_ON_PAUSE                    // Park the nozzle during pause and filament change.
  //#define HOME_BEFORE_FILAMENT_CHANGE           // If needed, home before parking for filament change

  #define FILAMENT_LOAD_UNLOAD_GCODES           // Add M701/M702 Load/Unload G-codes, plus Load/Unload in the LCD Prepare menu.
  //#define FILAMENT_UNLOAD_ALL_EXTRUDERS         // Allow M702 to unload all extruders above a minimum target temp (as set by M302)
#endif

**Comment by kisslorand** [comment]
> I have G28 in my End Code to home the printer so the bed lowers to the bottom (0) (it's a CoreXY) and the nozzle moves to the front, left corner. I could replace that line with "G1 X0 Y0 Z0" if that's safer but it seems to work just fine. Why is it a "very,very,very bad idea?"

I was thinking about a regular core XY printer, G28 after a print would make the X gantry and/or nozzle to hit the printed parts.

**Comment by scott-pett** [comment]
G-code T0 selects the first nozzle/extruder on a multi extruder machine. A perfectly valid code on a multi nozzle machine.

On my IDEX printer I find it useful to switch back to T0 in the end code so T1 parks itself rather than moving to X0 as part of the home of routine.

**Comment by kisslorand** [comment]
Yup, just tested it and you're right.

**Comment by mehmetsutas** [comment]
I think error 3 is related with Marlin's LCD setup. Pause for user makes me think that Marlin is expecting a button press feedback from 12864 LCD or extensible ui lcd.

If enabled you may try disabling Reprap Discount LCD on Marlin configuration.
