### ISSUE TITLE
WARNING FOR MKS TFT

### ISSUE THREAD

**Issue by digant73** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2407]
Just to avoid any bug report.
In order to update icons/fonts, MKS TFT users don't need to rename TFT* folder (e.g. TFT28, TFT35) to MKS anymore. Now you simply need to copy the TFT* folder (as already done for BTT TFTs). The only exception is for MKS TFT32. In this case you need to rename TFT28 to TFT32 (just because no TFT32 is present in the material theme folders). README.md was also updated with the new update logic

**Comment by Sonicboom247** [comment]
tried to update my Sidewinder, was getting Icons: Update Required but Fonts: OK, do we still need to rename bpm to Icons??

**Comment by BetulSBoyali** [comment]
Hey @rondlh, I have MKS TFT35 and SKR 2 motherboard. Can't make it work. I have AUX-1 Socket on TFT (8 pins), but on the other side motherboard has only TFT socket (5pins). Is there any sheet or source I can use? Any help would be appreciated.
