### ISSUE TITLE
Problem Inverted Letters Help:((

### ISSUE THREAD

**Issue by sokolek155** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2411]
I have problem my BTT TFT 35 v3.0 i have inverted letters.

**Comment by oldman4U** [comment]
ReadMe from front page - Troubleshooting section.

Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by sokolek155** [comment]
![20220219_125311](https://user-images.githubusercontent.com/84595174/154804110-08e78a45-23cf-4c0e-b4a8-6941776133c2.jpg

**Comment by digant73** [comment]
put a blank file named **reset.txt** in the SD card and restart the TFT with the SD card in the TFT's slot. The screen calibration will start. At the end of the calibration process, the issue should be solved

**Comment by sokolek155** [comment]
I did so. Screen calibrations as well. unfortunately it did not help :(

**Comment by sokolek155** [comment]
The problem is that the letters are opposite not the screen.

**Comment by digant73** [comment]
you have an horizontally mirrored screen. Try to install again the firmware, fonts, icon, config.ini. Are you sure you used the proper firmware? For BTT TFT35 V3, you must use BIGTREE_TFT35_V3.0.27.x.bin

**Comment by radek8** [comment]
Are you sure with the display version?
Can you take a TFT picture without a cover on both sides?

**Comment by sokolek155** [comment]
Exactly as you write, I have a mirror image screen. Software exactly as you wrote. Tried flashing a few times on with no results.

**Comment by digant73** [comment]
As suggested by Radek, verify you have a TFT35 V3. It seems you have another version and you are installing the wrong firmware

**Comment by radek8** [comment]
you send photos of the circuit board

**Comment by sokolek155** [comment]
![Uploading 20220219_165450.jpg…]()
![Uploading 20220219_165500.jpg…]()
![Uploading 20220219_165509.jpg…]()

**Comment by radek8** [comment]
again and do not rush

**Comment by sokolek155** [comment]
![20220219_165450](https://user-images.githubusercontent.com/84595174/154808428-87745110-6c17-430a-a17e-faaf22b326da.jpg)

**Comment by sokolek155** [comment]
![20220219_165500](https://user-images.githubusercontent.com/84595174/154808448-b05d08ae-2a0e-4b3b-b2d3-277941058d78.jpg)

**Comment by sokolek155** [comment]
![20220219_165509](https://user-images.githubusercontent.com/84595174/154808461-25196890-4a58-4a93-a833-42f020105ea6.jpg)

**Comment by digant73** [comment]
try to install this

[BIGTREE_TFT35_V3.0.27.x.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/8102552/BIGTREE_TFT35_V3.0.27.x.zip)

**Comment by radek8** [comment]
It looks like some modification on the BTT side.
The STM32F207 processor was originally used
the photo shows the STM32F205 processor

**Comment by sokolek155** [comment]
Working thanks you :):) Could you please write me in which line he changed the name of the processor?

**Comment by radek8** [comment]
LCD is also different

![image](https://user-images.githubusercontent.com/46979052/154808852-ca5468e5-be70-42e7-93e9-eef3f9c8c4b5.png)


![image](https://user-images.githubusercontent.com/46979052/154808863-d64a7cca-69de-4c6a-a827-f04df19049d0.png)

**Comment by sokolek155** [comment]
![20220219_170953](https://user-images.githubusercontent.com/84595174/154808977-21737597-d165-457a-837f-3bd530c6157e.jpg)

**Comment by digant73** [comment]
> Working thanks you :):) Could you please write me in which line he changed the name of the processor?

I didn't change anything. I simply provided my compiled firmware. Maybe the precompiled firmware you used was wrongly created

**Comment by digant73** [comment]
use this config.ini file

[config.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/8102567/config.zip)

However I think you are using wrong source files (or old files)

**Comment by sokolek155** [comment]
I need to upload bmp files and config files, could you send them to me so that I can add them?

**Comment by digant73** [comment]
[TFT35.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/8102573/TFT35.zip)

**Comment by sokolek155** [comment]
I recently downloaded the files from github bigtreetech I do not know why version 27 is probably the last one available.

**Comment by sokolek155** [comment]
![20220219_172327](https://user-images.githubusercontent.com/84595174/154809450-675dd223-478d-49f3-9b50-0d6ded583c06.jpg)

**Comment by sokolek155** [comment]
Everything works fine, thank you very much for your help. A closed topic may be useful to someone. Regards and thank you.

**Comment by digant73** [comment]
good you solved your issue. Please close this ticket

**Comment by radek8** [comment]
You miss download version 0.27
You have to download Master

**Comment by sokolek155** [comment]
Where can i find?

**Comment by radek8** [comment]
![image](https://user-images.githubusercontent.com/46979052/154810067-04b876a3-8959-4e6d-8a69-aa980af5cc37.png)

**Comment by sokolek155** [comment]
I found my problem was flashing issue 27.Sorry amateur me.

**Comment by radek8** [comment]
@oldman4U 

Can you write on the title page of the manual that it should be updated from the master?

**Comment by digant73** [comment]
@radek8 In my current PR I made also other changes in README.md. So I can also add this info at the beginning of the document
