### ISSUE TITLE
[BUG] Wrong file list navigating on onboard SD

### ISSUE THREAD

**Issue by digant73** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2414]
With the introduction of support to long folder name the file list is sometime wrongly displayed.

Here a wrong list:

![IMG_20220218_130542](https://user-images.githubusercontent.com/64427768/154856892-b2edfc91-a46f-4f02-a6e4-76061e8fcc79.jpg)

Here the correct list:

![IMG_20220218_130613](https://user-images.githubusercontent.com/64427768/154856909-51f1f50c-fcb9-453e-9aaa-14a8a2d4c185.jpg)

All the content of the SD card to replicate the issue is attached below (split in more zip files):

**NOTES:**
* The same content was properly displayed in the past
* Tested on MKS TFT28 with 64KB RAM

**Comment by kisslorand** [comment]
> Attached all the content of the SD card to replicate the issue.

Nothing attached.

Are there any specific steps to reproduce the issue?

**Comment by digant73** [comment]
[sd_card_1.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/8104661/sd_card_1.zip)
[sd_card_2.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/8104662/sd_card_2.zip)
[sd_card_3.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/8104663/sd_card_3.zip)

**Comment by digant73** [comment]
[sd_card_4.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/8104664/sd_card_4.zip)
[sd_card_5.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/8104669/sd_card_5.zip)
[sd_card_6.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/8104673/sd_card_6.zip)
[sd_card_7.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/8104678/sd_card_7.zip)

**Comment by digant73** [comment]
[sd_card_8.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/8104680/sd_card_8.zip)
[sd_card_9.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/8104681/sd_card_9.zip)

**Comment by digant73** [comment]
put all the content of the zip files in the root of the SD card

**Comment by digant73** [comment]
> > Attached all the content of the SD card to replicate the issue.
> 
> Nothing attached.
> 
> Are there any specific steps to reproduce the issue?

navigate in the list menu. Sometimes I got the issue entering in the list menu. Other times, simply selecting one file and pressing "cancel" to return to the list menu etc...

**Comment by kisslorand** [comment]
I am clicking here for 30 minutes and cannot reproduce it. Tested on MKS TFT28 v4 (clone) and BTT TFT35 v3.
I have a hunch... Delete a few files and see if it still happens to you.
Does it happen also from the TFT's SD Card?

**Comment by digant73** [comment]
It happened only on onboard sd. I removed files (less than 40 in the root folder) and I got the the same issue. However, for the moment it's not a big problem for me. Maybe it could be the SD card not properly read by the onboard SD.

**Comment by kisslorand** [comment]
I do not think it is an SD Card issue, in the first picture the first folder is a part of the  temperature autoreport:
` T:105.08 /0.00 B:27.00 /0.00 @:0 B@:0`.
It seems to be an overflow somewhere.

**Comment by digant73** [comment]
Yes thanks. it fixed the issue. I also applied your changes in my vfs.c just be already aligned

**Comment by kisslorand** [comment]
> Yes thanks, that fixed the issue. I also applied your changes in my vfs.c just be already aligned.

Thanks for the feedback.
