### ISSUE TITLE
[BUG] Rounding of parameter values

### ISSUE THREAD

**Issue by Guilouz** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2423]
In machine settings the 3rd digit after the decimal point is always rounded up or down.

For some parameters (like diagonal rod, diagonal rod trim, etc) we need to have precise values to 4 digits after the decimal point.

In example here we need to adjust settings with precise values (in red background).

![Capture d’écran 2022-02-23 à 16 21 25](https://user-images.githubusercontent.com/12702322/155349545-6510aa09-0eff-4978-9d8a-50678cdbaa88.jpg)
 
Currently if I enter the value 314.8381, the result saved by TFT is 314.84 and they are saved in the EEPROM as is.

**Comment by guruathwal** [comment]
I will look into it.

**Comment by Guilouz** [comment]
@guruathwal Do you have checked this ?

**Comment by guruathwal** [comment]
Yes, I have identified the Issue. I Will add a patch in a few days.

**Comment by digant73** [comment]
@Guilouz 
To fix your issue it should be enough to apply the following changes in MachineParameters.c:

```
  {"H%.4f\n",            "S%.4f\n",       "R%.4f\n",       "L%.4f\n",      NULL,           NULL,           NULL,           NULL,           NULL,           NULL},           // Delta Configuration (Height, Segment per sec, Radius, Diagonal Rod)
  {"X%.4f\n",            "Y%.4f\n",       "Z%.4f\n",       NULL,           NULL,           NULL,           NULL,           NULL,           NULL,           NULL},           // Delta Tower Angle (Tx, Ty, Tz)
  {"A%.4f\n",            "B%.4f\n",       "C%.4f\n",       NULL,           NULL,           NULL,           NULL,           NULL,           NULL,           NULL},           // Delta Diagonal Rod Trim (Dx, Dy, Dz)
  {"X%.4f\n",            "Y%.4f\n",       "Z%.4f\n",       NULL,           NULL,           NULL,           NULL,           NULL,           NULL,           NULL},           // Delta Endstop Adjustments (Ex, Ey, Ez)

```

It is used **.4** instead of **.2**.

**Comment by Guilouz** [comment]
I will try. Can you insert this in your actual PR ?

**Comment by digant73** [comment]
It is better you try it and let me know if it solves your issue. Then I will add it on my PR

**Comment by Guilouz** [comment]
Ok I will try tonight after work.

**Comment by Guilouz** [comment]
@digant73 with 0.4, value are correctly registered in EEPROM but TFT always displays only 3 digits after the decimal point (although I can enter 4 then validate).

**Comment by kisslorand** [comment]
Dear bot, the lack of activity is coming from @bigtreetech. We can't do much more than wait for @bigtreetech to merge the relevant bugfix.
