### ISSUE TITLE
[BUG] media notification not removed when printing

### ISSUE THREAD

**Issue by traffic-light** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2433]
When printing the media notification is not removed but overwritten with the filename. (noticeable with long file names)
![IMG_20220306_194718](https://user-images.githubusercontent.com/37051137/156937581-833ffadb-e8a7-479d-a5e5-9ec5a911930e.jpg)

**Comment by rondlh** [comment]
I've seen this issue too sometimes, but not with recent builds, which build are you using?
And please, provide all information requested in the bug report template when posting a bug report.

**Comment by traffic-light** [comment]
I know how it works. And always running the latest version ;-)

**Comment by traffic-light** [comment]
Ah cool! Thanks for fixing it!
