### ISSUE TITLE
[BUG] Minor correction needed in README.md

### ISSUE THREAD

**Issue by Sporque** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2450]
### Description

Noticed a very minor formatting error in README.md to be corrected.
Under "Options to fully support Bed Leveling menu:" the line for g26_Mesh_Validation says (in configuration.h) twice.
First as part of the variable, with the gray background (this one needs to be removed as redundant) and then again afterwards as with the rest of the list of options.

### Steps to reproduce

1. look at the README.md on the main github page for the repository.
2. Notice the formatting error.

**Comment by oldman4U** [comment]
Sporque

This is open source, so feel free to make the changes needed to make it perfect.

Thank you
