### ISSUE TITLE
on start-up Z axis raises and BL-Touch  probe deploys

### ISSUE THREAD

**Issue by discip** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2452]
### Description
After the latest update (see below) on power-up the **Z axis raises** and the **BL-Touch probe deploys**. 

### Steps to reproduce

1. Update to latest build (https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/commit/ac3c2afd136f1e4e4e68ad46a808acf2e0f709a0).
2. Switch off your printer.
3. Switch your printer back on.
4. Observe the printer to raise the **Z axis** about **`12mm`** and **deploying the BL-Touch probe**.

**Expected behavior**

After turning on the the printer nothing should move without user interaction.

**Actual behavior**

See **`Steps to reproduce`**.

### Hardware Variant

MKS TFT28

### TFT Firmware Version & Main Board Firmware details

(https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/commit/ac3c2afd136f1e4e4e68ad46a808acf2e0f709a0)

### Additional Information
[Configuration.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/8318915/Configuration.zip)

**Comment by kisslorand** [comment]
Update to latest Marlin bugfix and it won't do that.
Upon startup the TFT makes a new check about a new Marlin's capability, the BLTouch High Speed mode.

**Comment by discip** [comment]
## Thanks!
Yep, that worked! 👍
Should have checked before posting. 😓

kind regards

**Comment by kisslorand** [comment]
#2459
