### ISSUE TITLE
TFT50 v3.0 No touch since Firmware update

### ISSUE THREAD

**Issue by imrdnck1** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2456]
I updated my Bigtree TFT50 v3.0 to the latest firmware BIGTREE_TFT50_V3.0.27.X and now I have no touch function can any one help?
Thanks.

**Comment by rondlh** [comment]
Put a file called "reset.txt" on a sdcard, insert the card into you display and restart the display. This should trigger a touchscreen calibration.

**Comment by oldman4U** [comment]
Especially for new users it is important to read the provided information before starting a ticket. Please read the ReadMe, follow the instructions there and close this ticket.

Thank you

**Comment by imrdnck1** [comment]
> Put a file called "reset.txt" on a sdcard, insert the card into you display and restart the display. This should trigger a touchscreen calibration.

Thank you.
