### ISSUE TITLE
[BUG] Strange symbols since recent PRs

### ISSUE THREAD

**Issue by Guilouz** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2460]
Since recent merged PRs, I have strange symbols at startup when screen is not already connected.

TFT70 v3.0

![IMG_3114](https://user-images.githubusercontent.com/12702322/160103055-d8c66751-e33c-45c3-b2cf-984eca8fbc04.jpeg)

I think PR #2447 cause this.

**Comment by digant73** [comment]
probably yes. I also had some freezes with some popups when pressing on the buttons to close the window.
I didn't have that kind of issue before.

**Comment by Guilouz** [comment]
Yes there is something wrong with language pack, language file have same name, if I switch to English two languages are named English, if I switch to French two language are names Français.

My french language file is up to date without error.

After switched to English and go back to French strange symbols persist.

![IMG_3117](https://user-images.githubusercontent.com/12702322/160173141-2fcd321e-7295-4c00-acde-8bb21efd25c3.jpeg)
![IMG_3118](https://user-images.githubusercontent.com/12702322/160173162-b0d0c852-c098-4c6e-8e95-88a5b82c44e0.jpeg)
![IMG_3119](https://user-images.githubusercontent.com/12702322/160173187-42d5f7c7-8a20-472d-ae68-dc681cf03e0f.jpeg)

**Comment by Guilouz** [comment]
I will try your new PR.

**Comment by Guilouz** [comment]
Your PR fixes issue with language file name but not for strange symbols.

**Comment by Guilouz** [comment]
@guruathwal I printed using the M600 function (not emulated) and during the heating popup in the background we see strange symbols scrolling but also all the parameter strings at the top left.

**Comment by Msq001** [comment]
Hello, Please check here https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/2466/commits/e58233db1220eb49203da461d4f7207d962b3bf7 in #2466
This problem should be solved
