### ISSUE TITLE
[BUG] Glitch on screen

### ISSUE THREAD

**Issue by Guilouz** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2468]
Since many PR merged there is several issues, another one, when I click on Heating menu and can do nothing : 

![IMG_3124](https://user-images.githubusercontent.com/12702322/160244870-f32d53e8-d96b-4d3a-80ec-d638d05a5494.jpeg)

Maybe PR #2448 which affects the display of icons.

Here a video of this issue : https://www.youtube.com/watch?v=9Dz6TilvMLk

And I have also a warning for unknown command M5 at reboot.

And the return of prints that stops for no reason when printing from TFT ports, screen frozen without message, the hotend and the bed still heating. It was fixed but it's back again... No issue with motherboard ports.

**Comment by guruathwal** [comment]
@Guilouz thanks for update. fixed in #2470. Please check if this is solved.

**Comment by Guilouz** [comment]
Confirmed. It's fixed.
