### ISSUE TITLE
RRF and TFT35_V3.0_E3.27 load\unload filament not work

### ISSUE THREAD

**Issue by tribunskiysm** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2469]
Hi,

SKR 1.4 turbo, RepRapFirmware for LPC176x based Boards 3.3.0_16 (2022-02-13  and TFT35_V3.0_E3 button load\unload filament not work in menu;
No color settings in encoder backlight menu;
The encoder in the print file selection menu, does not work; 
in firmware - https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/releases/tag/Vx.x.27.

On the firmware from here - https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/tree/master/Copy%20to%20SD%20Card%20root%20directory%20to%20update  
encoder, load \ unload filament works.

Help please what am I doing wrong?

**Comment by radek8** [comment]
FW TFT has full support for Marlin.
RepRap support is added by some users, but is not 100% implemented.
Do not use old versions of FW. Use a master

**Comment by tribunskiysm** [comment]
Latest firmware with RRF support - https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/tree/master/Copy%20to%20SD%20Card%20root%20directory%20to%20update

**Comment by tribunskiysm** [comment]
Последняя прошивка с поддержкой RRF - https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/tree/master/Copy%20to%20SD%20Card%20root%20directory%20to%20update

**Comment by radek8** [comment]
Я не заметил, что ты из России.
Я не помогаю оккупантам.

**Comment by kisslorand** [comment]
@radek8 
It's not a good idea to bring politics here but I just cannot help myself to let you know I am 100% on the same page as you.

**Comment by radek8** [comment]
I'm sorry, but the people of Russia should know that their country is occupying and threatening nuclear war. They won't tell them on TV.
Russia also occupied my country in 1968, and the occupation lasted 20 years.

**Comment by kisslorand** [comment]
I know all this and as I said I am with you as most of the world is.
If we open Pandora's box it will be no good. I could write pages of rage every day about what's happening.
It's inhuman, unethical, outrageous, criminal.
BTW, they had in plan to do the same to the country I live in, it was luck it didn't happen.

**Comment by radek8** [comment]
ok
