### ISSUE TITLE
popup status window

### ISSUE THREAD

**Issue by andrzej1974** [bigtreetech/BIGTREETECH-TouchScreenFirmware#247]
Hello
I have question. How change or disable popup status screen  in during printing popup. Because every layer this windows show information about with layer now is printing and cover main printing menu. Also we have this status screen in main menu ( not a popup ) before start print, but if we start printing, menu is change and still we have popup status screen.  The main unified menu is grate with lot information about xyz position, status screen etc, but if we start printing menu is change and we dont have this information.
![20191212_221936](https://user-images.githubusercontent.com/58828260/71228187-c5d0c180-22e1-11ea-89bd-61669444bc30.jpg)

**Comment by guruathwal** [comment]
you have to change setting in your slicing software to stop the messages on layer change.

**Comment by andrzej1974** [comment]
I'm using Cura. Do you know where that can change?

sob., 21 gru 2019, 07:05 użytkownik guruathwal <notifications@github.com>
napisał:

**Comment by PGrave** [comment]
@andrzej1974 Check your Gcode files for M117 and remove. This is the Set LCD command, which forces a popup on the TFT. If you want a more permanent solution, edit your slicer preferences. In Cura there's a setting in (Menu)-Extensions-Post Processing-Modify G-Code. If script "Display Layer and Filename on LCD" is active and enabled, deactivate.

**Comment by andrzej1974** [comment]
Thanx. This was help.
