### ISSUE TITLE
[BUG] Unwanted characters

### ISSUE THREAD

**Issue by Guilouz** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2472]
Unwanted characters appears on layers case. And also wrong string on temperature case.

I think PR #2465 cause this.

![IMG_3127](https://user-images.githubusercontent.com/12702322/160259750-aaf6aade-6726-4bf1-8f74-b22f712feca8.jpeg)

NB: Print from onboard USB and I just see screen completely freezing but print continue.

**Comment by bigtreetech** [comment]
Please check https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/2473, it should fix this problem, Thanks!

**Comment by Guilouz** [comment]
@bigtreetech Yes it's fixed this but another on is introduced, see https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/2476
