### ISSUE TITLE
[BUG] No continous communications with DUET 2 WIFI board

### ISSUE THREAD

**Issue by dariusz737** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2475]
### Description

No continous communications with DUET 2 WIFI.

### Steps to reproduce

1. Connect display to DUET 2 WIFI

**Expected behavior**
Continuous two way communication, update between display and board

**Actual behavior**
Single data exchange on power up, or pressing "disconnect" button on Connection Menu, or after chose "Touch Mode" on mode control screen (Marlin vs Touch Mode). 
No auto update on temperature, progres etc. except error messages which appears instantly on display. 

### Hardware Variant
TFT24 - V1.1
### TFT Firmware Version & Main Board Firmware details
TFT 27.x , DUET 3D v 3.4

**Comment by digant73** [comment]
is the baudrate selected for the Wifi port on TFT (Menu->Settings->Connection->S. Ports) the same as the one configured in the Wifi module?

**Comment by dariusz737** [comment]
WiFI ? 
Anyway, yes its the same. But there is communication on power up, reset, and when select again „touch” mode. Also warning messages from printer board comes normalny on time.

**Comment by digant73** [comment]
so basically you have the issue only in Marlin Mode? If so, you have to set "serial_always_on" to 1 in config.ini or change it from the Feature menu

**Comment by dariusz737** [comment]
Załącznik dostępny do 02.05.2022
No, I don’t use Marlin Mode at all. 

Please see attached wideo 
Kliknij, aby pobrać
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAW_dPSSqKXWCECyJz9J0ytky6jDQAdTpy-IAKCWr3ZpbQj82cAmq9S6U%2F%24%7Bf%7D%3Fo%3DArsRR0L7f3QgK6XiKoNyUlQNh5z74tfThXvOnW7SmcZP%26v%3D1%26x%3D3%26a%3DCAog0BhoOYIailmbo5_WpFkhCsJJBO4DaDkPZ6PwSLvXaZoSdhCJtpvR_i8YicaWpYgwIgEAKgkC6AMA_2pTkchSBDLqMNBaBKr1LpRqJYRUeMeOdXzAQMebG0tzekeBOE66I754_FXOuoKhezj5Raf2z1FyJR5exmQvoCZoanODAOuhe0v83nOXv8NqZraExzDetug6AVOOYDk%26e%3D1651492889%26fl%3D%26r%3D2FB8213D-A260-4F41-B778-B54B7C1167FA-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3D928F0214-9E1C-4125-B372-DCDAF23C4C48%26p%3D105%26s%3DJIkf5pzUAnj8hTDF8QLgvz9mHdc&uk=65lZEhhm22zhljsSXcas-w&f=IMG_3146.MOV&sz=39792747>IMG_3146.MOV
39,8 MB

**Comment by dariusz737** [comment]
I have connected display with DUET 2 WIFI board with cable.

**Comment by digant73** [comment]
Ok, understood now. It is the first time I see such kind of issue but it seems to me a problem in Marlin. The TFT will connect to mainboard and probably sends the messages but it is like the mainboard is expecting something more before executing the commands received. From the TFT's Terminal menu try to send some commands and verify if you also receive the answer from Marlin (e.g. send M900, M503 etc...)

**Comment by dariusz737** [comment]
It's not Marlin, its Duet 3D software.

**Comment by digant73** [comment]
ok. simply try to send some commands from TFT's Terminal and verify if you receive the answer (e.g. OK)

**Comment by dariusz737** [comment]
Nothing, no response to commands.

**Comment by digant73** [comment]
Ok, I was expecting that. You should ask support to duet sw repo. As far as I read on Internet, the Duet sw can be configured to be compatible with Marlin.

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by dariusz737** [comment]
I need it. Problem still exist. No changes.

**Comment by oldman4U** [comment]
But your problem seems not to be BTT TFT related. And this is the repository of the firmware related to this hardware and not a user group. Like digant73 already wrote, maybe someone from the duet repo or a user group related to that hw can help.

**Comment by dariusz737** [comment]
I don't understand why are you 100% sure its NOT related do display firmware. But if you say so. Thank you for help.

**Comment by oldman4U** [comment]
Hi.

I am not sure that it is not the firmware but is there a hint that it is the firmware?

Please reopen it if it is so!

**Comment by digant73** [comment]
@dariusz737 see also https://teamgloomy.github.io/tft.html
