### ISSUE TITLE
[BUG] TFT freeze after print finish

### ISSUE THREAD

**Issue by Guilouz** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2476]
Another issue... TFT freeze after print is finishing with strange symbols on title bar.

![IMG_3134](https://user-images.githubusercontent.com/12702322/160289763-0b04e85c-b70f-4fb6-87ff-50b8bc8b44cd.jpeg)

Why would you want to change something that was working well? Many people report me many issues since recent PRs, freezes, prints that stop for no reason etc...

**Comment by guruathwal** [comment]
Hi, please check and see if #2479 fixes it.
