### ISSUE TITLE
[BUG] Issue with progress bar and %

### ISSUE THREAD

**Issue by Guilouz** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2480]
Another issue... When print is done, progress bar and percentage are not to 100%. As you can see here they are blocked to 11% on resume page. It's also blocked when printing.

![IMG_3136](https://user-images.githubusercontent.com/12702322/160358537-6e18a0a0-c7b1-43f1-a3bf-ef9400a582a4.jpeg)

**Comment by guruathwal** [comment]
@Guilouz I have added some changes regarding this. please check and see if #2479 solves it.

**Comment by kisslorand** [comment]
@Guilouz 
Does it happen with every print? Can you upload a gcode file?

**Comment by Guilouz** [comment]
@kisslorand In test but PR #2479 seem to be fix this.

**Comment by kisslorand** [comment]
Even thou I would still like to have the answers because I couldn't reproduce the issue.

**Comment by kisslorand** [comment]
@Guilouz 
You might want to reopen this as it is not fixed (https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/2457#issuecomment-1092289974) and maybe you give more details.

**Comment by kisslorand** [comment]
Check PR #2491.
