### ISSUE TITLE
[BUG] Start/Resume Icon not updated

### ISSUE THREAD

**Issue by Guilouz** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2481]
After a M600 (popup to purge and continue) or filament runout and print restarted, resume button is not updated, it's always in resume status.

On this photo machine is actually in printing mode.

![IMG_3146](https://user-images.githubusercontent.com/12702322/160715233-35871512-814e-474f-ab0d-f1a7b295a24c.jpeg)

I have also notified after print is finished, LED Event go to green but after exiting resume menu Event LED turns off instead of white.

**Comment by digant73** [comment]
LED is switched off (also in PID menu) if "led_always_on" is set to 0. Otherwise, the LED color at boot is restored

**Comment by digant73** [comment]
Maybe at boot your LED is set by Marlin while in config.ini "led_color" is set to black. "led_color" is the color set by the TFT at boot and the one that will be restored
