### ISSUE TITLE
TFT35 E3 V3.0 Knob LED Control / Functionality

### ISSUE THREAD

**Issue by uvhalo** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2482]
I'm not sure if this is a case of my unfamiliarity with V.x.x.27 or, a firmware problem so, I'm calling this a question.

I know in previous versions of the firmware, under  Settings-> Feature, there was an option for the knob LED.  In the current (Vx.x.27) version, it is no longer there.  In this version, there is a menu (Settings-> Machine-> LED Color) but, it doesn't appear to do anything (I suspect it may be for controlling neopixels attached to the mainboard?).

In config.ini, changing nob_led_color to a given color will cause it to turn on with that color but that is it.  Also, the event_led functionality doesn't appear to do anything,

Is there something I'm missing IRT operating the knob LED?  Baring that, is this a bug?

To be clear, I'm using the BIGTREE_TFT35_V3.0_E3.27.x firmware.
![PXL_20220329_042735562 MP](https://user-images.githubusercontent.com/102571844/160724171-b71a9ebf-9096-458c-be74-8305e9f6af92.jpg)
![PXL_20220329_232830152 MP](https://user-images.githubusercontent.com/102571844/160724174-93736d6b-c8b2-47f4-b1b3-b5feada03f56.jpg)

**Comment by guruathwal** [comment]
The knob colour settings are moved to settings > Screen > UI

**Comment by uvhalo** [comment]
Thanks!!
