### ISSUE TITLE
Layer number and progress bar issue

### ISSUE THREAD

**Issue by iamacell** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2486]
Hello All!

SKR1.4T
Marlin 2.0.9.3

BTT TFT35 E3 V3.0
Fw.: V27.x Apr. 02. 2022.

I've enabled all the needed options in Marlin.

I have the following issue:
While printing from Octoprint the progress bar stays empty and no layer numbers shown on the display.
![2](https://user-images.githubusercontent.com/54331920/161428149-272ec263-e19b-4f88-bd67-b7f8b2a91dc0.PNG)

Is it possible to get the layer number and progress on this screen if printing from octoprint?

The progress bar is working in marlin mode.

**Comment by digant73** [comment]
for data progress bar see section "Printing from Remote Host" in README.MD.

**Comment by iamacell** [comment]
I've done that already. 
Those make no difference in (not) displaying the layer or progress %, just add a message to the notification area on the top of the screen.

**Comment by kisslorand** [comment]
Layer number is displayed only if printing from TFT USB or TFT SD. The info about layer number is taken from the gcode file if the slicer provided that info. Unfortunately Octoprint doesn't send any info about the layer number.

**Comment by iamacell** [comment]
I have layer number indicators in my gcodes. Do you mean Octoprint eats these info and not providing to the printer?

**Comment by kisslorand** [comment]
Those layer number indicators are marked as comments and yes, Octoprint doesn't analyze comments, it skips them.
The comment parsing is a very new feature of the TFT FW, I do not think anyone else (Octoprint, ESP3D, Marlin, etc.) implemented it yet.

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by digant73** [comment]
> I've done that already. Those make no difference in (not) displaying the layer or progress %, just add a message to the notification area on the top of the screen.

As reported in README.MD file, the data progress (printing from remote host) is set with:

```
M118 A1 P0 action:notification Data Left <XXXX>/<YYYY>
or
M117 Data Left <XXXX>/<YYYY>

Examples:
M118 A1 P0 action:notification Data Left 123/12345
M117 Data Left 123/12345

```

**Comment by iamacell** [comment]
Hello!

I could make the progress bar and elapsed time working with a modified DLP plugin:
![kép](https://user-images.githubusercontent.com/54331920/162573141-9e9194e4-3aa3-417e-8538-550fd69d587e.png)

Still no layer number info. Any idea how to tell it to the printer with M118?

**Comment by kisslorand** [comment]
It's not implemented in the TFT's FW to parse layer number from anywhere else but as comments from gcode file itself.
However it could be implemented...

**Comment by iamacell** [comment]
It would be very nice to have this feature.
Thank you for the info.

**Comment by iamacell** [comment]
Thank you for your work!
