### ISSUE TITLE
[FR] Round Miracle live icons not aligned

### ISSUE THREAD

**Issue by digant73** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2488]
The TFT28 live icons are not all aligned. The speed icon is not aligned with the flow (and the other live icons on the left).
Below a video reporting the issue.

https://user-images.githubusercontent.com/64427768/161960790-98aa87f1-109c-498b-a070-ef58759d3999.mp4

**Comment by kisslorand** [comment]
Check please #2489

**Comment by digant73** [comment]
it is ok now. The fix should also be applied to TFT24 (same set of icons)

**Comment by kisslorand** [comment]
TFT24 icon set is not affected.
