### ISSUE TITLE
dont  heating after start printing.

### ISSUE THREAD

**Issue by andrzej1974** [bigtreetech/BIGTREETECH-TouchScreenFirmware#250]
Hello 
In  New feature https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/246 after start printing, on tft35 v3.0 temperature from bed and hotend dont start automatically only give me a message cold extrusion prevented.
![20191221_043644](https://user-images.githubusercontent.com/58828260/71308345-9a41fa00-23fb-11ea-9a75-a5e3cae4ab37.jpg)

**Comment by andrzej1974** [comment]
Problem, with file.

**Comment by dtserkanozkan** [comment]
I have the same problem:

https://www.youtube.com/watch?v=YD8ZsFmqS_Q

and I copied the gcode file to sd card and printed it without any problem.

https://www.youtube.com/watch?v=nU251ta5mjA

Is there any idea pls?
