### ISSUE TITLE
Power port on TFT screen

### ISSUE THREAD

**Issue by sinole1987** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2508]
Is the power plug marked in image below a 5v in or out? 
in other words, can I power The screen with a 5v power supply with this port and control the rest of the print with ps_on using the screen?
![TFT43-50-70--01_04](https://user-images.githubusercontent.com/44652024/165409242-d20ef702-07c3-4e00-92f2-b6e008c49c79.gif)

**Comment by rondlh** [comment]
These are outputs, but they might be suitable for input too, just use a multimeter to check if the +5V pin is directly connected to the +5V off the RS232 port (+ pin in the right side). Please note, the TFT is powered via the RS232 plug connecting the TFT to the motherboard.

**Comment by oldman4U** [comment]
Sinole. Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by sinole1987** [comment]
> Sinole. Please help the community and close the ticket once you do not need it anymore. Thank you

I was hoping for more info, I don't really wana mess with board and short it. I already bought 2 of these cause I killed one playing around LOL.

**Comment by digant73** [comment]
@sinole1987 +5V pins are all connected to the 3.3V regulator. You can apply 5V on RS232 or on Power connector

**Comment by sinole1987** [comment]
> @sinole1987 +5V pins are all connected to the 3.3V regulator. You can apply 5V on RS232, on Power connector, on USB port etc...

so I'm good to go? thank you.

**Comment by digant73** [comment]
yes

**Comment by NeoMatrixJR** [comment]
If these are output...what's the Amperage they support?  Can I use them to power a raspberry pi 4?
