### ISSUE TITLE
TFT35 V3.0 Freezing In Portrait Mode

### ISSUE THREAD

**Issue by beebenutz** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2509]
I have found that the TFT35 V3.0 with 27.x firmware has a freezing issue when placed in portrait mode. 
To reproduce:

- Load firmware 27.x with portrait mode enabled
- Press - >Menu>Movement>Home>Home
- Wait for homimg to complete
- Press - >Back>Move>0.1 Button (increment adjustment button)
- Experience system now unresponsive. Reset required to operate again.

This also happens eventually when pressing buttons in different orders. Always freezes after pressing the "incriment adjustment button", sometimes after pressing the button many times. 

Please advise what may be causing this issue. 

Here is a video of the issue:
https://drive.google.com/file/d/1Cd3iKMIpsw0ySSaQ3BPIXt4MKsLZhbAu/view?usp=sharing

Thanks 
-Mat

**Comment by digant73** [comment]
It is fixed in #2503. If you can, try that PR.
