### ISSUE TITLE
long file name support for onboard sdcard

### ISSUE THREAD

**Issue by andrzej1974** [bigtreetech/BIGTREETECH-TouchScreenFirmware#251]
Can You add long file name support for onboard sdcard to the https://github.com/guruathwal/BIGTREETECH-TouchScreenFirmware. Because is now little bit confuse add https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/235, the files is different then oryginal from btt. The rest is ok.

**Comment by guruathwal** [comment]
Long file name support is working fine now in this repository.. you can close this issue now.
