### ISSUE TITLE
font issues with newest firmware on BIGTREETECH TFT35 MZ V3.0

### ISSUE THREAD

**Issue by pcclan** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2510]
been trying to fix this using all the different firmware and nothing is working? is there something i am doing wrong ?i am currently using [BIGTREE_TFT35_V3.0_E3.27.x.bin
![20220427_121349](https://user-images.githubusercontent.com/1440987/165662781-f6a116d5-2ae2-4e75-90bb-1ff87f9453e1.jpg)

**Comment by digant73** [comment]
For MZ version it seems you have to use **BIGTREE_TFT35_V3.0.27.x.bin** (not **BIGTREE_TFT35_V3.0_E3.27.x.bin**).

**Comment by pcclan** [comment]
> For MZ version it is possible you have to use **BIGTREE_TFT35_V3.0.27.x.bin** (not **BIGTREE_TFT35_V3.0_E3.27.x.bin**).

i have tried that and it didn't work but if i use BIGTREE_TFT35_V3.0_E3.26.bin the fonts work perfectly

**Comment by digant73** [comment]
@pcclan do you have the issue only on that Heat menu or in any menu?

**Comment by pcclan** [comment]
> @pcclan do you have the issue only on that Heat menu or in any menu?

any menu that has the centre with temperature or speed of the fans also the terminal with all the keys

**Comment by digant73** [comment]
You have to update both the firmware (with BIGTREE_TFT35_V3.0_E3.27.x.bin) and the icon/fonts.

**Comment by pcclan** [comment]
> You have to update both the firmware (with BIGTREE_TFT35_V3.0_E3.27.x.bin) and the icon/fonts.

you mean the ones that are in the themes ? because I have tired all the themes

**Comment by digant73** [comment]
yes, for example the `TFT35` under folder `THEME_Unified Menu Material theme`. Try to use another SD card

**Comment by digant73** [comment]
Try to install this .bin, .ini and icons/fonts

[TFT35_E3.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/8639252/TFT35_E3.zip)

**Comment by pcclan** [comment]
still the same here are the screens is happening on even with what you sent
![PXL_20220506_204312782 MP](https://user-images.githubusercontent.com/1440987/167214481-ef3f5be9-138f-47b1-896a-67bc6252c1cf.jpg)
![PXL_20220506_204326397 MP](https://user-images.githubusercontent.com/1440987/167214486-0fd22a51-6653-4fd2-9eb1-b41811c00b89.jpg)
![PXL_20220506_204333268](https://user-images.githubusercontent.com/1440987/167214488-676ef40a-8d5e-46ae-9c52-1f2a7c6b229e.jpg)
![PXL_20220506_204337872](https://user-images.githubusercontent.com/1440987/167214490-079a423d-4e4e-4f14-b8c2-2f80b3d4eb31.jpg)

**Comment by pcclan** [comment]
fixed when i was able to find a proper sd card just weird it was working with 26 perfectly but didn't like it when it was doing 27
