### ISSUE TITLE
[Q] (Rotary button LED)

### ISSUE THREAD

**Issue by BelSD** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2527]
I just upgraded from version v26 to v27 and the rotary button LED is no longer lit and in the menus I no longer have the possibility of activating it or even changing its color. The options in the menu have disappeared. Is this normal or a BUG?

![20220526_114735](https://user-images.githubusercontent.com/45131244/170466978-dafbbeef-7357-4cf4-bf80-638b87779d80.jpg)
![20220526_114741](https://user-images.githubusercontent.com/45131244/170466991-7a19c7bd-9e83-4bf4-b911-d94537d1606f.jpg)
![20220526_115206](https://user-images.githubusercontent.com/45131244/170467022-52092e44-6399-4eb4-bcee-9040339f2f5e.jpg)

**Comment by radek8** [comment]
You used the wrong update file

**Comment by oldman4U** [comment]
BelSD

Please answer or close this ticket.

Thank you

**Comment by BelSD** [comment]
What wrong update file?
I downloaded the source code (https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware) and compiled

**Comment by radek8** [comment]
If you compiled your own FW, then you compiled the wrong versions.
According to the photos, your display is a variant of the TFT35 E3 V3.
You have compiled versions of TFT35 V3.0

The difference is that the variant without the E3 index does not have an illuminated knob.

**Comment by radek8** [comment]
Variant E3 has a knob at the bottom.
The version without E3 has a knob on the side

**Comment by BelSD** [comment]
Thanks for Help
