### ISSUE TITLE
[Q] Not alle parameters loaded? (Edit: Marlin related)

### ISSUE THREAD

**Issue by traffic-light** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2531]
When I'm in machine parameters, not all parameters are loaded.
For example in the E-STEP menu, only the X-STEPS are loaded.

I'm running a new compiled bugfix version of marlin and the latest version the touchscreen firmware.
(I build it self and used the pre-compiled version. Both not working like it should) 

Any one else having this?

**Comment by kisslorand** [comment]
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/2529

**Comment by traffic-light** [comment]
Ah. Thank you. Didn't take a look into the pull requests.

**Comment by kisslorand** [comment]
https://github.com/MarlinFirmware/Marlin/pull/24259 was merged so it's all good now.

**Comment by traffic-light** [comment]
Thank you for fixing this. 
It works like it should now!
