### ISSUE TITLE
TFT70 Vertical GUI

### ISSUE THREAD

**Issue by Akds4877** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2535]
Hey, i want to place my TFT on vertical point and there is no space in my Printer body for horizontal, so i did the configuration in portrait mode but it does not look well as the orientation is not so cool so please help me to make my TFT70 on Vertical Mode.
![IMG_20220527_161846909](https://user-images.githubusercontent.com/105791259/171326334-84a14503-d9ab-4ae7-8e45-03d586b1f763.jpg)

**Comment by Guilouz** [comment]
TFT43/TFT50 and TFT70 are not compatible with portrait mode at this time.
