### ISSUE TITLE
[BUG] BIQU_TFT35_V1.2.27.x Unable to use TFT SD card，no sdcard detected

### ISSUE THREAD

**Issue by langyaWang22** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2539]
BIQU_TFT35_V1.2.27.x Unable to use TFT SD card，no sdcard detected.
BIQU_TFT35_V1.2.26  Can be used normally.

**Comment by radek8** [comment]
You probably used an old FW, or an FW that's not for your display.
Use the master branch.

![image](https://user-images.githubusercontent.com/46979052/173255326-0769716c-c447-4dad-87af-68830f2205d8.png)

**Comment by langyaWang22** [comment]
> 您可能使用了旧固件或不适合您的显示器的固件。 使用主分支。
> 
> ![图片](https://user-images.githubusercontent.com/46979052/173255326-0769716c-c447-4dad-87af-68830f2205d8.png)



> You probably used an old FW, or an FW that's not for your display. Use the master branch.
> 
> ![image](https://user-images.githubusercontent.com/46979052/173255326-0769716c-c447-4dad-87af-68830f2205d8.png)

Tried "master" or failed to use SD card

**Comment by langyaWang22** [comment]
> 



> You probably used an old FW, or an FW that's not for your display. Use the master branch.
> 
> ![image](https://user-images.githubusercontent.com/46979052/173255326-0769716c-c447-4dad-87af-68830f2205d8.png)

Tried "master" or failed to use SD card

**Comment by radek8** [comment]
> > @langyaWang22 , @adambrejniak
> > 
> > * What HW variant of the display do you have?
> > * Which WF file did you use?
> > * The problem is that the SD card is not detected or is the card detected but not read?
> > * If the previous FW card worked, do you remember from which date the last functional FW was?
> > * Did you also use the config.ini file and the folder with icons and fonts when updating? Did the update take place without error messages?
> 
> Now I have TFT35_V1.2.26 Apr 11 2020 - It is working. If I use latest TFT35_V1.2.27 - SD not working. But, firmware was uploading. Mayby this version use to much RAM?


So your display version is TFT35 V1.2?
Does that mean 3.5 "without EXP1 and EXP2 connectors?

**Comment by adambrejniak** [comment]
> So your display version is TFT35 V1.2? Does that mean 3.5 "without EXP1 and EXP2 connectors? Currently, TFT35 has about 11 HW versions and you need to use the correct FW.

Yes, 3.5" without EXP1 and EXP2. I use BIQU_TFT35_V1.2.27.x.bin. This should be correct FW

**Comment by langyaWang22** [comment]
[](url)> > > @langyaWang22,@adambrejniak
> > > 
> > > * 你有什么显示器的硬件变体？
> > > * 你用的是哪个WF文件？
> > > * 问题是未检测到SD卡还是检测到卡但未读取？
> > > * 如果之前的 FW 卡有效，您还记得上一个功能性 FW 是从哪一天开始的吗？
> > > * 更新时是否还使用了 config.ini 文件和带有图标和字体的文件夹？是否在没有错误消息的情况下进行了更新？
> > 
> > 
> > 现在我有 TFT35_V1.2.26 Apr 11 2020 - 它正在工作。如果我使用最新的 TFT35_V1.2.27 - SD 不工作。但是，固件正在上传。Mayby 这个版本使用了很多内存？
> 
> 所以你的显示版本是TFT35 V1.2？ 这是否意味着 3.5" 没有 EXP1 和 EXP2 连接器？ 目前，TFT35 大约有 11 个 HW 版本，您需要使用正确的 FW。



> @langyaWang22 , @adambrejniak
> 
> * What HW variant of the display do you have?
> * Which WF file did you use?
> * The problem is that the SD card is not detected or is the card detected but not read?
> * If the previous FW card worked, do you remember from which date the last functional FW was?
> * Did you also use the config.ini file and the folder with icons and fonts when updating? Did the update take place without error [messages?]([url]([url]([url]([url]([url](url))))))



> @langyaWang22 , @adambrejniak
> 
> * What HW variant of the display do you have?
> * Which WF file did you use?
> * The problem is that the SD card is not detected or is the card detected but not read?
> * If the previous FW card worked, do you remember from which date the last functional FW was?
> * Did you also use the config.ini file and the folder with icons and fonts when updating? Did the update take place without error messages?



> @langyaWang22 , @adambrejniak
> 
> * What HW variant of the display do you have?
> * Which WF file did you use?
> * The problem is that the SD card is not detected or is the card detected but not read?
> * If the previous FW card worked, do you remember from which date the last functional FW was?
> * Did you also use the config.ini file and the folder with icons and fonts when updating? Did the update take place without error messages?

**Comment by langyaWang22** [comment]
> @langyaWang22 , @adambrejniak
> 
> * What HW variant of the display do you have?
> * Which WF file did you use?
> * The problem is that the SD card is not detected or is the card detected but not read?
> * If the previous FW card worked, do you remember from which date the last functional FW was?
> * Did you also use the config.ini file and the folder with icons and fonts when updating? Did the update take place without error messages?
![IMG_20220614_010923](https://user-images.githubusercontent.com/16213052/173409517-6a4ad399-9d59-4fcd-94d7-eca710746129.jpg)
![IMG_20220614_010952](https://user-images.githubusercontent.com/16213052/173409542-c513c24a-89b7-4b0c-b99a-cc4c6fd6dd11.jpg)
![IMG_20220614_011005](https://user-images.githubusercontent.com/16213052/173409591-f9e356bf-a400-4299-9dba-e3b924def3aa.jpg)

It can be upgraded and downgraded normally. There is no error when writing firmware.

**Comment by radek8** [comment]
here is the vere of August 2, 2021
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/tree/5fd8a7bea797d893ae339a499c8c90b1ffa72486/Copy%20to%20SD%20Card%20root%20directory%20to%20update

**Comment by langyaWang22** [comment]
> Can you try to upload older versions of FW V1.2.27 to find out when it got damaged? For example, here is the version from December 4. Can you test? https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/tree/484ffc2d1cdbe4ba6fa970ee9b6d2953c27a6194/Copy%20to%20SD%20Card%20root%20directory%20to%20update


TFT SD card can be used

**Comment by radek8** [comment]
It is well
Can you try another FW between December 4 and the current FW to find out when it broke?

**Comment by langyaWang22** [comment]
> February 14? https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/tree/0df78c5c52ac570e8c8eda2d78e2731f8a2e3873

no sd card detected.

**Comment by radek8** [comment]
January 18?
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/tree/5cb1201e6ed159c8bbb747f5741136e7a9f7f58e/Copy%20to%20SD%20Card%20root%20directory%20to%20update

**Comment by langyaWang22** [comment]
> January 18? https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/tree/5cb1201e6ed159c8bbb747f5741136e7a9f7f58e/Copy%20to%20SD%20Card%20root%20directory%20to%20update

TFT SD card can be used

**Comment by radek8** [comment]
Maybe I found it.
Try on January 25 and then January 26

January 25
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/tree/41afaf40249e1fb31d14e227678145ed594de91f/Copy%20to%20SD%20Card%20root%20directory%20to%20update

January 26
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/tree/186eb548e617dba5f5ff9817cd3e0cb15e8bc017

**Comment by kisslorand** [comment]
@langyaWang22 
Please check PR #2540

**Comment by adambrejniak** [comment]
> > February 14? https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/tree/0df78c5c52ac570e8c8eda2d78e2731f8a2e3873
> 
> no sd card detected.

Thank You, it's working :)

**Comment by langyaWang22** [comment]
> @langyaWang22 @adambrejniak Please check PR #2540
> 
> Thx @radek for narrowing down the search.

Neither the firmware using "2315" nor the firmware recompiled by changing the "master" code can use the SD card.
no sd card detected.

**Comment by langyaWang22** [comment]
> @langyaWang22 @adambrejniak Please check PR #2540
> 
> Thx @radek for narrowing down the search.
"2315" recompiled firmware can use SD card.
