### ISSUE TITLE
TFT50 V3.  Cannot get firmware to update.  Cannot get Portrait Mode.  Please Help 🥺

### ISSUE THREAD

**Issue by k4blammo** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2542]
Hoping someone can help with this, I've tried all I can think of.

Attempting to update firmware on TFT50 V3 (ultimately to enable Portrait Mode).  Cannot get firmware to update even to a pre-compiled .bin.  Not sure what I'm doing wrong.

I have attached the files that I have currently saved in root directory on SD card.  (.bin file, config.ini, TFT50 folder (from the "copy-to-SD" folder of the repository), reset.txt (per Portrait mode instructions to trigger screen calibration) )

Procedure:

- Insert SD card into TFT50 V3 SD-card slot
- power on SKR3+TFT50 V3 via 24v PSU

When i boot up the TFT50 (connected to SKR 3), fonts update, icons update, config updates...but for some reason the firmware does not, and remains ".bin" rather than ".CUR"

Any ideas?  Thanks!

[TFT50.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/8914416/TFT50.zip)

**Comment by k4blammo** [comment]
additional detail.  8 gb SD card used.  Sd card was low level formated FAT32 (not quick format).  Card is otherwise blank other than the files included in the zip file in first post.

**Comment by radek8** [comment]
What is the model of your TFT?
Don't happen to have a GD variant?

**Comment by radek8** [comment]
Do not put the reset.txt file on the SD card along with the bin file. 
Use the reset.txt file only in the second step.

**Comment by k4blammo** [comment]
I do not believe it is a GD variant.  See attached.

Also, same result without the reset.txt.  fonts, logo, icons, config updates...but firmware does not.  😔

![20220616_171730](https://user-images.githubusercontent.com/42353341/174166973-5b870d14-d490-4690-b291-c95846ca7777.jpg)

**Comment by radek8** [comment]
Yes it's a GD version!

![image](https://user-images.githubusercontent.com/46979052/174168540-a53b3682-42d4-4762-a3fe-9a35cca45c67.png)

**Comment by radek8** [comment]
Bigtreetech signage is pathetic

**Comment by k4blammo** [comment]
Well I'll be damned!  Will recompile and give it another go.  Fingers crossed 🤞

**Comment by k4blammo** [comment]
@radek8 ... I owe you a beer. 🍻
