### ISSUE TITLE
[Q] (Your Question?TFT35 V2 Flashed touch screen mode, but nothing but black screen with Marlin Mode ?)

### ISSUE THREAD

**Issue by Wick3dJack** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2548]
I flashed my TFT35 V2 with the touch screen option am I supposed to use Blocked Marlin mode or something because all I have is a black screen with Marlin Mode in white at the top center screen.
This has never happened before and how would I remedy this ?
Thank You

**Comment by rondlh** [comment]
Did Marlin mode work before you flashed the firmware? Did you add the required wiring? (2x 10pin flat cables)

**Comment by oldman4U** [comment]
What is the status of this ticket?

Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by radek8** [comment]
@rondlh ,
TFT35 V2 does not have EXP1,2 connectors and Marlin mode.

**Comment by Wick3dJack** [comment]
No the tft35 v2 doesnt even support marlin mode which is why I'm asking how did it get installed ? I never enabled it in the config file

**Comment by radek8** [comment]
Did you use the correct FW?
Didn't you use the bin file for a different model?

**Comment by radek8** [comment]
Save the empty reset.txt file on the SD card, insert it into the TFT and reset the display.

**Comment by Wick3dJack** [comment]
No I used correct bin I always double check & tried the reset.txt already but I think that just resets the Marlin config.ini settings

**Comment by Wick3dJack** [comment]
Well I just tried using FlyMcu to flash the BIQU_TFT35_V2.0_bootloader.hex from 2019-11-07 and now getting illegal user app on the screen =\
