### ISSUE TITLE
[Q] Can the screen support Start Host print?

### ISSUE THREAD

**Issue by blueeagle69** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2558]
Hi.

Does the screen in TFT mode support Start Host Print to start a highlighted job in Octoprint?

Or is it possible to add?

Thanks.

**Comment by rondlh** [comment]
If Marlin supports this, then the TFT can do it.
Do you know the Gcode needed to realize this?

**Comment by blueeagle69** [comment]
Sadly,  I'm not sure how Marlin pulls it off once it's enabled in the firmware.  I will have to see if I can find out.
I'm not a coder sadly, but hopefully I can find something  😀

**Comment by rondlh** [comment]
I just came across some information that might be useful for you, check:
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware
Look for "Printing from Remote Host".

**Comment by blueeagle69** [comment]
Awesome, thank you.
