### ISSUE TITLE
BTT SKR Mini E3 V3-  Ender6 example incorrect drivers

### ISSUE THREAD

**Issue by nicwilson58** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2559]
### Description

BTT SKR Mini E3 V3-  Ender6 example incorrect drivers,  they are listed as TMC2208_STANDALONE which is not correct

### Steps to reproduce

See Configuration, h for above example

**Expected behavior**
Drivers should be configured for listed board in the config not creality board. Expected TMC2209

**Actual behavior**
Wrong Drivers listed in configuration.h

### Hardware Variant
N/a
### TFT Firmware Version & Main Board Firmware details
N/a

### Additional Information
N/A

**Comment by oldman4U** [comment]
Sure, you have been posting this using the correct repository?

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by nicwilson58** [comment]
you have have not fixed the issue I checked today and it's still wrongSent from my Galaxy
-------- Original message --------From: oldman4U ***@***.***> Date: 21/7/22  4:36 pm  (GMT+10:00) To: bigtreetech/BIGTREETECH-TouchScreenFirmware ***@***.***> Cc: nicwilson58 ***@***.***>, Author ***@***.***> Subject: Re: [bigtreetech/BIGTREETECH-TouchScreenFirmware] BTT SKR Mini E3 V3-  Ender6 example incorrect drivers (Issue #2559) 
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
This is open source, so all users including YOU can change it. Furthermore, your issue does not belong to the Touchscreen firmware, but to the mainboard. So this is the wrong repository and you have to post the issue using the correct repository.

**Comment by nicwilson58** [comment]
hi,ok I will fix it   in future if you do not want motherboard  config files in the TFT repository then do not put them there.  I shall fix. delete and move them to the correct place.Sent from my Galaxy
-------- Original message --------From: oldman4U ***@***.***> Date: 21/7/22  6:49 pm  (GMT+10:00) To: bigtreetech/BIGTREETECH-TouchScreenFirmware ***@***.***> Cc: nicwilson58 ***@***.***>, Author ***@***.***> Subject: Re: [bigtreetech/BIGTREETECH-TouchScreenFirmware] BTT SKR Mini E3 V3-  Ender6 example incorrect drivers (Issue #2559) 
This is open source, so all users including YOU can change it. Furthermore, your issue does not belong to the Touchscreen firmware, but to the mainboard. So this is the wrong repository and you have to post the issue using the correct repository.

**Comment by oldman4U** [comment]
Please do so. Thank you

**Comment by nicwilson58** [comment]
completed.

**Comment by nicwilson58** [comment]
the examples are in this repository just look its under ender6Sent from my Galaxy
-------- Original message --------From: oldman4U ***@***.***> Date: 18/7/22  11:45 pm  (GMT+10:00) To: bigtreetech/BIGTREETECH-TouchScreenFirmware ***@***.***> Cc: nicwilson58 ***@***.***>, Author ***@***.***> Subject: Re: [bigtreetech/BIGTREETECH-TouchScreenFirmware] BTT SKR Mini E3 V3-  Ender6 example incorrect drivers (Issue #2559) 
Sure, you have been posting this using the correct repository?
