### ISSUE TITLE
[BUG] Icons: update required

### ISSUE THREAD

**Issue by mlaci001** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2562]
TFT35 V3.0_E3

 After a firmware update, I always get the message "Icons: update required". The font update runs fine, but the icons (bmp) are not updated. Tried with all themes but same situation. After the faulty update, the "TFT35" folder is renamed to "TFT35.CUR", but the "Language Packs" folder is not touched.  I tried with 3 different SD cards and 2 types of USB pen drives. 
My display is currently unusable.
Please help me.
Thanks in advance.

**Comment by kisslorand** [comment]
You should read again more carefully the readme section from here: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware. It is explained in great detail which file is needed and each of them goes where on the SD Card.

**Comment by mlaci001** [comment]
> You should read again more carefully the readme section from here: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware. It is explained in great detail which file is needed and each of them goes where on the SD Card.

Thanks.
I finally found the solution.
I formatted the SD card with a block size of 2048 instead of the default one, and so not only the firmware and fonts were updated, but also the icons.
The content on the card has not changed (folder structure, contents of folders, etc.)

**Comment by oldman4U** [comment]
Perfect. Please help the community and close the ticket once you do not need it anymore. Thank you
