### ISSUE TITLE
Echo - No SD Card

### ISSUE THREAD

**Issue by Nbrooks639** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2563]
i have a tft 35 3.0 connected to skr e3 v3 and after marlin 2.1 flash it will not stop flashing "echo-no sd card". has anyone else had a problem?

**Comment by kisslorand** [comment]
It's a message from Marlin so you should search the solution there.

**Comment by Nbrooks639** [comment]
so your saying BTT knows nothing about their products as far as trouble shooting

**Comment by kisslorand** [comment]
Marlin is not a product of BTT.

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by radek8** [comment]
Do you have it set up in Marlin?
#define SDCARD_CONNECTION ONBOARD

**Comment by oldman4U** [comment]
@Msq001 you may want to close this ticket.
