### ISSUE TITLE
[FR] Terminal enhancements, enable editing

### ISSUE THREAD

**Issue by rondlh** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2565]
Here some ideas to enhance the capabilities of the terminal:
1. Remember the last command, this makes repeating the same command easy.
2. Allow editing of the command (backspace support only), so you can easily go from M500 to M502 for example.
3. Erase the whole command by pressing the box that shows the command (top left), this is useful so you don't have to backspace the whole command.
4. Show the digits in a different color (yellow)., this makes the terminal keypad look much nicer and easier to use
![Terminal](https://user-images.githubusercontent.com/77279634/180643479-7c64f66b-9f49-448f-96d6-0fdfc7a4a877.jpg)
.

**Comment by kisslorand** [comment]
> 2. Allow editing of the command (backspace support only), so you can easily go from M500 to M502 for example.

"Del" button does that.

**Comment by rondlh** [comment]
You are right, unfortunately it can only be used to correct a typo, not to change a previous command
