### ISSUE TITLE
How use this LCD with klipper?

### ISSUE THREAD

**Issue by lucasromeiro** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2568]
HI
How use this LCD with klipper?
I cant do this.
HELP

**Comment by lucasromeiro** [comment]
I have onde BIQU B1

tft35 v3.0

**Comment by oldman4U** [comment]
Hi.

Have you checked user groups and YouTube videos? This is the software repository of the BTT Touchscreen firmware and not a user group.

Thank you

**Comment by radek8** [comment]
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/1905

**Comment by radek8** [comment]
https://github.com/teeminus/NoTouchScreenFirmware
