### ISSUE TITLE
[Q] Use USB to communicate with printer

### ISSUE THREAD

**Issue by xhejtman** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2574]
**Your question or details you need. Please describe.**

Is it possible to use USB cable for communication with printer instead of serial cable?

**Comment by kisslorand** [comment]
If you mean to connect the USB of the TFT to the USB of the mainboard, than no, it will not work.

**Comment by xhejtman** [comment]
OK. To explain: I have SKR 3 controll board and TFT display, I used Marlin, however, there are some serious issues with UARS. TMC2209 drivers cannot connect and print over serial from the TFT freezed many times (not in the case of print from internal SD card from controll board). So I was hoping that connecting via USB would solve freezes. But in the end, I moved to klipper and everything works now.

**Comment by kisslorand** [comment]
Good to hear you found a way! Happy printing!
