### ISSUE TITLE
[Q] BIGTREETEH TFT24 not flushed with custom firmware.

### ISSUE THREAD

**Issue by ZeriAD** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2588]
Question.

Hello.
I used a translation program because I am not good at English. It is difficult to deliver information, but I will tell you the current situation.

The BIGTREE_GD_TFT24_V1.1.27.x.bin Firmware file provided after purchasing BTTT TFT24.

After adding code from the provided open source to add the required features, I tried to compile and upload normally, but it did not flash.

Previously, in the case of BTT TFT35, it was flushed in all situations.

What more information should I provide to solve this problem?

Device Variant
Device : BIGTREETECH TFT24-V1.1
MCU : GD32F105 RCT6

**Comment by radek8** [comment]
Use an SD card that is 8GB or less.
Format the card again to FAT32
If it doesn't help, try another card...

**Comment by oldman4U** [comment]
Sure GD MCU is supported?

**Comment by radek8** [comment]
Yes. Must use GD versions

**Comment by oldman4U** [comment]
What is the status of the ticket? Please help the community and close the ticket once you do not need it anymore. Thank you
