### ISSUE TITLE
G-code thumbnails

### ISSUE THREAD

**Issue by wigw** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2598]
Hello group.
My hardware is BIGTREE_TFT70_V3_0.
I am trying to enable inline G-code thumbnails #define THUMBNAIL_PARSER 2 then compile.
For some reason, thumbnails are not displayed on TFT, but in OctoPi they are displayed.
Maybe I'm doing it wrong.
Please point me to the right path.**Your question or details you need. Please describe.**
A clear and concise question or detail you would like to ask. Like Hardware related or firmware related.

**Comment by sarvenn** [comment]
I'm still using this tool with latest PrusaSlicer without any issues.
I couldn't use thumbnail parser as well.
Even prusaslicer or superslicer has also added different thumbnail options as I had a previous FR for it, but I still like to use the standalone python script.
I'm using pre-compiled TFT firmware for my TFT35

**Comment by wigw** [comment]
Many thanks to everyone, your advice helped me a lot.

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by wigw** [comment]
Huge thanks to everyone who helped
