### ISSUE TITLE
filament runout sensor settings UI

### ISSUE THREAD

**Issue by Thijsvanzwam** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2600]
Hi, on previous firmware versions I could use the UI to setup the filament runout sensor. There where three options: OFF, ON, SMART.
Now there is only the option ON or OFF. SMART seems to be missing.
Is this a feature and did I just miss this being announced or is this an error?

There is an updated way of setting up the sensor type in the config file but i used to use the UI to set it up.

**Comment by kisslorand** [comment]
It's bug but I fixed it by PR https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/2601

**Comment by Thijsvanzwam** [comment]
great, thanks!
