### ISSUE TITLE
[Q] Does it work with ELEGOO Neptune 2S?

### ISSUE THREAD

**Issue by Johnnii360** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2604]
Does this firmware also work with the ELEGOO Neptune 2(S)?

My model has a MKS board clone the ZNP Robin Nano v1.3 and MKS display clone ZNP Robin TFT35 v1.0. In the description is MKS TFT35 v1.0 listed but I don't know if this is also the case fpr ZNP TFT35 v1.0? I don't want to kill my board again. :)

**Comment by rondlh** [comment]
Can you send some detailed pictures of the front and back of the display?

**Comment by Johnnii360** [comment]
Sure. These pictures are not made by me but it's the same.

![IMG_1543](https://user-images.githubusercontent.com/15824634/191953779-86b7b233-ee91-435c-bf59-01e4a482626e.jpg)
![IMG_1555-scaled](https://user-images.githubusercontent.com/15824634/191953786-71337dcd-a627-433d-be76-c9baa0e2e223.jpg)

**Comment by rondlh** [comment]
Thanks, looks like an SPI TFT to me, which is fully controlled by Marlin, I found the printer firmware source here:
https://github.com/manniefesto/neptune-2-firmware
Which configures the display is a: MKS_ROBIN_TFT35

This means this display is NOT supported by the firmware here, but it's fully supported by Marlin.
