### ISSUE TITLE
BTT TFT35 V3.0.1 at BTT SKR2_RevB but the TFT shows "No printer attached"

### ISSUE THREAD

**Issue by MattenMax** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2619]
I am struggeling during upgrading my UM-Clone with the above mentioned board and display.
The Marlin firmware is 2.1.1, the TFT firmware is uptodate (BIGTREE_GD_TFT35_V3.0.27.x.bin). The board is correct connected to the TFT.
I have spent several days with reading in communities and watched several videos on the internet. But nothing helped so far...
Could anyone have a look into my settings, maybe there is somethin I missed...

Thank you so much!
Matten

Addes files: configuration.h, configuration_adv.h and config.ini for display

**Comment by MattenMax** [comment]
[configs.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/9872769/configs.zip)

**Comment by kisslorand** [comment]
Test in "Configuration.h" with "#define SERIAL_PORT_2 1".

**Comment by MattenMax** [comment]
Thanks for replying. I have tested these ports combinations:
-1/0, -1/1, -1/2, 0/1, 0/2.
Nothing worked.

**Comment by gordo3di** [comment]
Make sure you followed everything here:

https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/blob/master/README.md#marlin-dependencies

**Comment by kisslorand** [comment]
> Thanks for replying. I have tested these ports combinations: -1/0, -1/1, -1/2, 0/1, 0/2. Baud : 115200 Nothing worked.

Than check if RX & TX wires are swapped.

**Comment by MattenMax** [comment]
Thanks a lot! 
I will definitely test it all out tomorrow.

**Comment by MattenMax** [comment]
> Make sure you followed everything here:
> 
> https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/blob/master/README.md#marlin-dependencies

I just followed the instructions.... nothing has changed.

**Comment by MattenMax** [comment]
> > Thanks for replying. I have tested these ports combinations: -1/0, -1/1, -1/2, 0/1, 0/2. Baud : 115200 Nothing worked.
> 
> Than check if RX & TX wires are swapped.

RX and TX? 
RX is connected to PA9 
TX is connected to PA10
is this correct?

**Comment by kisslorand** [comment]
Yes, correct.
The correct wiring, configuring the serial ports and their baud rates are the only prerequisites to have a communication. You must have a hardware fault (TFT on mainboard).

**Comment by MattenMax** [comment]
Good and clear summary. Thanks a lot. First I will check the wiring itself, after that I will send back the TFT...

**Comment by radek8** [comment]
You have EEPROM disabled in your configuration
#define EEPROM_SETTINGS
Why?

**Comment by radek8** [comment]
> > Make sure you followed everything here:
> > https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/blob/master/README.md#marlin-dependencies
> 
> I just followed the instructions.... nothing has changed.

You searched wrong

**Comment by radek8** [comment]
Send photos of wiring and current configuration.

**Comment by radek8** [comment]
If you have defective HW and you have the option to return the defective piece to the seller, then do it.
But you have to know if it is suitable for SKR or TFT.
If you can't return the defective piece, you can try to remap the defective others on the TX and RX pins.
It has already been addressed in several discussions here.

**Comment by MattenMax** [comment]
I have just posted the current configuration after adjusting.
[configs.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/9880628/configs.zip)
here are some photos, I hope you can see the relevant things
![IMG_20221027_165733_263](https://user-images.githubusercontent.com/13543014/198326928-6c10e284-0f5b-4e93-8ddd-8999d6259109.jpg)
![IMG_20221027_165241_316](https://user-images.githubusercontent.com/13543014/198327046-39f46b96-938a-4e0e-bf79-f6d5bcfe13d5.jpg)

**Comment by kisslorand** [comment]
> The board is correct connected to the TFT.

> RX is connected to PA9
> TX is connected to PA10

We were giving you hints based on wrong information provided. Anyway, glad you find the issue. Happy printing!

**Comment by MattenMax** [comment]
Yeah I am very sorry. I did really double check it before posting here... But for some reason...

**Comment by radek8** [comment]
You are not the first to confuse the SWD and TFT connectors :-)
