### ISSUE TITLE
Switching back to touch mode

### ISSUE THREAD

**Issue by tom-321** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2629]
**Your question or details you need. Please describe.**
I taped on Marlin mode by mistake and can't get back. 
Display is black with orange title Marlin mode 
Tap and hold 2 sec does nothing 
Restart or reset -> nothing 

**specify the device variant related to your question.**
BIGTREETECH TFT35 V2.0
https://www.amazon.de/gp/product/B07SYPHYFB/ref=ppx_yo_dt_b_asin_title_o00_s01?ie=UTF8&psc=1

**Additional context**
Printer Board is btt skr 2 rev b 
Marlin 2.1.1
I've flashed the firmware in BIGTREETECH-TouchScreenFirmware-master/TFT/src/User compiled via VS Code
with almost no changes in Configuration.h

**Comment by radek8** [comment]
Check if you have the original versions of the display or the GD versions. Choose the right FW accordingly
Upload this FW to the display together with the icons and the config.ini file
Reset the display using the empty reset.txt file.

You cannot start Merlin mode on this display. TFT35 V2 display does not support dual mode.

**Comment by radek8** [comment]
The original versions of the displays had ST processors
New versions have GD processor and require custom FW versions

**Comment by tom-321** [comment]
I've uploaded a picture
I don't know if it's the GD version
![IMG_20221110_110321~2](https://user-images.githubusercontent.com/72745297/201208206-1a529778-3ef1-4b1b-831c-f7c8f7c03754.jpg)
![IMG_20221110_110018~2](https://user-images.githubusercontent.com/72745297/201208216-a04c6839-29b3-4435-ae0c-6dabdeb3b9b3.jpg)

**Comment by tom-321** [comment]
> You cannot start Merlin mode on this display. TFT35 V2 display does not support dual mode.

I did not want to 
I just do not come back 🙈

**Comment by radek8** [comment]
You have the original ST version of the display

**Comment by radek8** [comment]
> > You cannot start Merlin mode on this display. TFT35 V2 display does not support dual mode.
> 
> I did not want to I just do not come back 🙈

Set the parameters of the config.ini file
default_mode:3
Copy the config.ini file to the SD card
Put the SD card in the display and restart the display

**Comment by tom-321** [comment]
Does what I think it does ?
Locks changing the mode?

I tried that, but I thought blocked means the named mode could not be used.
So I changed it to 2 instead of 3.

**Comment by tom-321** [comment]
Yeah it worked
Thanks 👍
