### ISSUE TITLE
[FR] Input shaping setting under Machine settings.

### ISSUE THREAD

**Issue by MLiv79** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2632]
Marlin is adding input shaping (finally 👍 ) in their latest bugfix 2.1.x versions. Could you add the item in the machine settings? Thanks

**Comment by radek8** [comment]
What is input shaping?

**Comment by kisslorand** [comment]
https://github.com/MarlinFirmware/Marlin/pull/24797

**Comment by kisslorand** [comment]
I wanted to add this to the TFT firmware but this feature is still infantile, it's in a very early stage. For me it's not even working at all so it might go over major overhauls until it will be a solid working one.
If others don't get ahead of me I will surely include it in the firmware of the TFT once it will be solid.

**Comment by thisiskeithb** [comment]
Input Shaping / `M593` parameters aren't likely to change in the near future, but you can follow https://github.com/MarlinFirmware/Marlin/pull/24951 for updates until Marlin `2.1.2` is tagged & released.

### Current Parameters:
 *  `D<factor>`: Set the zeta/damping factor. If axes (X, Y, etc.) are not specified, set for all axes.
 *  `F<frequency>`: Set the frequency. If axes (X, Y, etc.) are not specified, set for all axes.
 *  `X<1>`: Set the given parameters only for the X axis.
 *  `Y<1>`: Set the given parameters only for the Y axis.

### Not implemented yet / ZV is the default:
 *  `T[map]`: Input Shaping type, 0:ZV, 1:EI, 2:2H EI

**Comment by gumanachile** [comment]
The Input Shaping is official now, are you reconsidering to add it to the tft firmware? We will really appreciate it! I have a Sidewinder X2 and its very annoying to input data from terminal having this awesome tft firmware!

**Comment by arminth** [comment]
I second that!

**Comment by kisslorand** [comment]
I started working on it...

**Comment by gumanachile** [comment]
But if it is in machine/settings it doesn’t need icons 👍🏽

**Comment by kisslorand** [comment]
Great idea, thank you!

**Comment by kisslorand** [comment]
Done #2689

**Comment by maniac75** [comment]
> Done #2689

Great!! Can't wait until the release of the .bin!!
Thank you!

**Comment by kisslorand** [comment]
No need to wait, I can compile it for you, just let me know what TFT do you have.

**Comment by maniac75** [comment]
> No need to wait, I can compile it for you, just let me know what TFT do you have.

Thank you!! I have the tft28 for the artillery sidewinder x2 🙏🏽

**Comment by kisslorand** [comment]
What bin have you used before to update your TFT? I am asking because I am not sure ASWX2's TFT is with STM32F107xx MCU, like the ASWX1's TFT.

**Comment by maniac75** [comment]
> What bin have you used before to update your TFT? I am asking because I am not sure ASWX2's TFT is with STM32F107xx MCU, like the ASWX1's TFT.

![image](https://user-images.githubusercontent.com/94304227/215357089-d0afa568-20dc-40d3-882f-d134b8008409.jpeg)

**Comment by maniac75** [comment]
> What bin have you used before to update your TFT? I am asking because I am not sure ASWX2's TFT is with STM32F107xx MCU, like the ASWX1's TFT.

Yes. Its stm32, the same like the x1

**Comment by kisslorand** [comment]
Here it is: https://www.dropbox.com/t/pmJX1jtfN7E5yMV1

**Comment by maniac75** [comment]
> Here it is: https://www.dropbox.com/t/pmJX1jtfN7E5yMV1

Thank you!! I will try it asap!!

**Comment by LTSpenny** [comment]
any chance at getting it compiled for a TFT 43, using TFT43V3.0.27 APR10 2021?

**Comment by kisslorand** [comment]
Sure, here you have it: https://www.dropbox.com/t/DeIqmdNXo1qq945h

**Comment by maniac75** [comment]
![image](https://user-images.githubusercontent.com/94304227/215588605-4c9e1314-2ace-4993-ad44-863807a004d8.jpeg)
![image](https://user-images.githubusercontent.com/94304227/215588661-07ce2f87-5ba7-48be-91c5-463f4ef78410.jpeg)

Works great!! Thanks @kisslorand !!!

**Comment by LTSpenny** [comment]
> Sure, here you have it: https://www.dropbox.com/t/DeIqmdNXo1qq945h

That file says its for tft28. Thatll work on a tft43? ![image](https://user-images.githubusercontent.com/86140833/215937670-07a4ce53-f24d-4bc8-9f61-90a1006cfe48.jpeg)

**Comment by kisslorand** [comment]
Sorry, my mistake, here's the file for TFT43: https://www.dropbox.com/t/SOnXahZwtHl0VykN

**Comment by LTSpenny** [comment]
> Sorry, my mistake, here's the file for TFT43: https://www.dropbox.com/t/SOnXahZwtHl0VykN

Thank you so much!

**Comment by Djungelman** [comment]
Hello. Is It possible to have a compilation for BIGTREE_GD_TFT35_V3.0_E3.27? Thank you

**Comment by kisslorand** [comment]
Sure: https://www.dropbox.com/t/8aGmFFugYFM17xHq

**Comment by Djungelman** [comment]
Thank you very much. I have Input Shaping X and Y also Shaping_Meny enabled in Marlin and had no problem to install the files you sent. But there is no Input Shaping meny in Settings. Reg// Djungelman

**Comment by kisslorand** [comment]
Did you install the language file also?

**Comment by Djungelman** [comment]
Yes. Your .BIN and Laguage files, From Github: TFT 35 Unified, Config.ini. No problem to update the TFT what I can see.

**Comment by kisslorand** [comment]
Update please with the language file from the archive. I included them for a reason.

**Comment by Djungelman** [comment]
I Take a clean sd card, copy the folder TFT35 and Config.ini from latest Github file. Then I copy your .bin and the Language Pack I got from you. The TFT seems to update with no errors but no meny for Input Shaping will appear. If I goes to Terminal and type M593 it respond with: M593 X F40.00 D0.15 and M593 Y F40.00 D0.15.

**Comment by kisslorand** [comment]
See above

**Comment by Djungelman** [comment]
Yes, I am in the Menu->Setting->Machine->Settings. But no Input Shaping. I a couple printers with the newest Marlin with Input Shaping but with the BIGTREE_TFT35_V3.0_E3.27.x.bin. If you have the time to compile that .Bin I will try on the other printers. //Thank you for the time and help.

**Comment by Djungelman** [comment]
I take  another TFT screen: TFT28 and tried to update with the files you sent to maniac75 . Same problem. No Input Shaping on that eighter. I must be an idiot. Cant figure out what I am doing wrong. Sorry for your time..

**Comment by kisslorand** [comment]
Here are the bin files for all the TFT variants: https://www.dropbox.com/t/y5NMFrGTVkpSNUXL

**Comment by maniac75** [comment]
> I take  another TFT screen: TFT28 and tried to update with the files you sent to maniac75 . Same problem. No Input Shaping on that eighter. I must be an idiot. Cant figure out what I am doing wrong. Sorry for your time..

Try to reset the tft with an empty file named reset.txt and copy it in a blank sd and reboot
