### ISSUE TITLE
TFT shows the wrong temperature on Head0 when selected Head1

### ISSUE THREAD

**Issue by selvakumaran2016** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2637]
Hi all,

We use 'Marlin-2.1.1' with BTT Octopus Pro board and BTT TFT 5.0.

500x500 machine with Dual extruder. Both nozzles are having an offset of 66mm. PID value is given separately for both hotends.

When heating T0 (Left), only T0 is heating.

But when heating T1, both T1 (RIght) and T0 (Left) also get heated. It is physically heating.

Actually, out of 10 times, 2-3 times only this issue is happening. Or sometimes randomly happening.

We checked with Pronterface. At that time the issue didn't happen. 

Someone has already raised it in Marlin and it seems they have updated the firmware by Jan-22 itself.
https://github.com/MarlinFirmware/Marlin/issues/23649

Maybe the issue with BTT TFT?

Any help is much appreciated. Thanks in advance.

**Comment by kisslorand** [comment]
Please check if PR #2647 fixes your issue.
