### ISSUE TITLE
BTT TFT 50 don´t show layer number and height 

### ISSUE THREAD

**Issue by Mastalirsky1** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2639]
Hi,
I have question, I installed a new BTT SKR mini E3 V3 and BTT TFT 50 V3 on my Ender 3, built and modified firmware for mainboard and config file for the TFT with all needed settings which you have here, but it still not show current layer number and height when printing, do you have any advice how to make it work? Thank you very much.

**Comment by kisslorand** [comment]
Where do you print from?



> it still not show current layer number and height when printing

What does it show?

**Comment by Mastalirsky1** [comment]
I print from mainboard SD, status bar with percenetege, remaining time and all other info works fine, only in layer column is just ---

**Comment by kisslorand** [comment]
What if you click/touch/press on the layer icon during print?

**Comment by Mastalirsky1** [comment]
It only switch between layer number and layer height and under both it is showing only ---

**Comment by rondlh** [comment]
Are the number of layers and current layer actually in the gcode you are printing?
Look for:
LAYER_COUNT:
LAYER:
What did you find?

**Comment by kisslorand** [comment]
File comment parsing is not available when printing from mainboard SD.

**Comment by rondlh** [comment]
> File comment parsing is not available when printing from mainboard SD.
Of course, so to get this to work you would need Marlin to parse the comments, and send the information to the TFT. You could use ExtUI(Marlin) for that, and pick up the info in parseAck.c(BTT TSFW). I use a similar approach to play M300 sounds on the TFT instead of via Marlin.

**Comment by Mastalirsky1** [comment]
In gcode I have LAYER_COUNT: and LAYER:
So I have to print from TFT USB or what I have to do to make it work for mainboard SD too?

**Comment by kisslorand** [comment]
>what I have to do to make it work for mainboard SD too?
 You would need to modify Marlin source code to parse those information and send it to the TFT

**Comment by kisslorand** [comment]
@Mastalirsky1 
Do you have AUTO_REPORT_POSITION and EXTENDED_CAPABILITIES_REPORT enabled in Marlin (Configuration_adv.h)?

**Comment by Mastalirsky1** [comment]
@kisslorand
Yes I do

**Comment by kisslorand** [comment]
I am out of guess what could be the cause of your issue, I cannot replicate this on my machines.
