### ISSUE TITLE
[BUG] The "chamber" temperature is not updated in "RRF" mode.

### ISSUE THREAD

**Issue by langyaWang22** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2659]
The "chamber" temperature is not updated in "RRF" mode.The "chamber" will be updated only when the screen is turned on or restarted.
TFT Firmware Version: Dec-30-2022 master - BIQU_TFT35_V1.2.27.x.bin

**Comment by radek8** [comment]
This will probably be a communication problem with RRF.
This is the query for @Subcircuit , @pfn , @bttguy,

**Comment by KirkBigelow** [comment]
Have an Octopus Pro 1.0.1 and GD TFT50 V3.0.1.  Have similar issue with display not updating with RRF config.  Have run through all the possible serial mode with modes S0 S2 showing the printer is connected at baud rate of 57600.  RRF firmware 3.4.5_102 and TFT firmware V3.0.27.x.  It seems to communicate only after a reset and then gets lost.  The TFT terminal will not do anything either.   The Octopus Pro seems to be work fine with the limited test done so far.  Octopus Wifi interface and Duet Web page dashboard is as expected as well as the Octupus command USB interface.
