### ISSUE TITLE
[Q] Is it possible to show extruder position during print

### ISSUE THREAD

**Issue by alxsfrm** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2666]
Hello,
I build the firmware by myself.
I have latest Marlin on SKR mini E3 + TFT35 V3 E3.
I have following issue: before printing i can see in the middle of the screen the status line with extruder XYZ values, but when i'm starting to print from the onboard SD, the status line disappear, and instead of it there is progress bar.
Also the layer number/height is not shown, just ------ during all the printing process.
How can i make the extruder position and the layer height to be visible during printing ?
Thank you.

**Comment by kisslorand** [comment]
For the layer number height issue:  - do you have the necessary options enabled in Marlin?
For the extrusion position during print issue: - there's no such option implemented in the current TFT FW, you would need to modify the source code to fulfill your needs

**Comment by alxsfrm** [comment]
> For the layer number height issue: - do you have the necessary options enabled in Marlin?

May be i missed something. Can you please point me to the specific option needed to enable this ?

**Comment by kisslorand** [comment]
Check if you have enabled AUTO_REPORT_POSITION (in Configuration_adv.h)

**Comment by radek8** [comment]
Why do we need to know the position of the extruder when printing when it is constantly changing during printing?
Isn't that useless information?

**Comment by alxsfrm** [comment]
Actually you are right. I just used to look on it in order to see the layer height.

**Comment by alxsfrm** [comment]
> Check if you have enabled AUTO_REPORT_POSITION (in Configuration_adv.h)

Yes, it is defined. Still no layer number/height.

**Comment by kisslorand** [comment]
Also check if you have enabled EXTENDED_CAPABILITIES_REPORT  (in Configuration_adv.h)

**Comment by LTSpenny** [comment]
@alxsfrm i solved this by adding a gcode report after layer change. 

Mine is 
;BEFORE_LAYER_CHANGE
;LAYER:[layer_num]

Hope that helps.

**Comment by oldman4U** [comment]
What is the status of this ticket?

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
