### ISSUE TITLE
F0 shows 0 on Unified 3.0.25 TFT35 even it is set to other values via GCODE

### ISSUE THREAD

**Issue by broxinagil** [bigtreetech/BIGTREETECH-TouchScreenFirmware#267]
My TFT35 shows F0 as 0 on Info-Screen when I print via USB, even the Filament Cooling Fan is running. Other Values, like Hotbed and Hotend temperature are displayed correctly.

Printer: Creality Ender 3 Pro with SKR Mini E3 1.2

**Comment by broxinagil** [comment]
As well (Maybe this can be seen as another Issue) the Value on F0 is shown as values from 0 to 255, instead 0-100%

**Comment by oldman4U** [comment]
Hello broxinagil.

Have you activated:
#define SHOW_FAN_PERCENTAGE // enable to show fan speed as a percentage instead of a value
in the firmware?

**Comment by broxinagil** [comment]
No. I've just installed the bin. Will take a look into sources. Bust this still will not solve the main issue I guess?

**Comment by guruathwal** [comment]
@broxinagil  please close the issue if it has been solved.

**Comment by Taomyn** [comment]
Mine is the same, compiled version of 3.0.26, the fan says 0% even though it is running - in Marlin mode it shows 100%.

**Comment by xrunner** [comment]
Also mine does same (v. 3.0.26 installed yesterday Apr 30, 2020). Always shows 0% (F0 part cooling fan) during prints on main menu (always has). If you go into the fan control menu and control F0 (not while printing), it will then show the percent on the main menu indicator.

**Comment by kkosa1** [comment]
Any new insights on this? Same for me since day one currently using V3.0.26.1 (may 8, 2020)

**Comment by guruathwal** [comment]
This is a marlin issue as it does not report the current fan speed. If the Fan speed is changed through any method other than the TFT, then the TFT will not know the current fan speed.

I have pushed a PR in Marlin firmware to address the issue: https://github.com/MarlinFirmware/Marlin/pull/18013
