### ISSUE TITLE
[BUG] TFT70 + SKR PRO 1.2 (no printer attached)

### ISSUE THREAD

**Issue by syszone** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2681]
I am upgrading my printer with SKR Pro 1.2 with TFT70. Earlier it was working then i have upgraded the configuration as per TouchScreen suggestion on : "General options which MUST be always activated" since then i see "No printer attached"  even i have reverted back the the changes with no luck. 

I am attaching configuration.h, configuration_adv.h and config.ini. Hopefully someone can look at the file and suggest the solution.

Thanks

[Configuration.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/10466241/Configuration.zip)
![70688b8f-d086-4045-ab82-1478094a20b1](https://user-images.githubusercontent.com/4724758/213694963-20cbadb1-eaa1-4c6a-b3ea-6bdcaff63437.jpg)
![91371945-5dc4-403f-a53b-06938760c6fa](https://user-images.githubusercontent.com/4724758/213694975-03afdda1-5071-49d9-a90c-1fbeddcc7433.jpg)

**Comment by digant73** [comment]
check and eventually set the TFT baudrate (Menu->Settings->Connection->S. Ports menu) so it matches the baudrate you configured in Marlin.

**Comment by syszone** [comment]
in Marlin my serial port is 1 
#define SERIAL_PORT 1
TFT baud rate is set to 250000

**Comment by radek8** [comment]
> in Marlin my serial port is 1 #define SERIAL_PORT 1 TFT baud rate is set to 250000

Yes, Marlin is set to 250000, but on TFT you set 115000 in the .ini file

**Comment by syszone** [comment]
I have changed to port 7 in config.ini, still same
serial_port:P1:7 P2:0 P3:0 P4:0 
![1790d97c-8251-4223-bc43-ef5a8c04a164](https://user-images.githubusercontent.com/4724758/213840408-38f1536c-123c-41d5-b72a-86e2520aded7.jpg)

**Comment by radek8** [comment]
Check if you have the serial cable between SKR and TFT plugged into the correct connector and if it is oriented correctly.

**Comment by syszone** [comment]
serial cable connected correctly, it was working before I update the marlin with suggested changes by TFT main page, even i try to revert them I do not know what I am missing.

**Comment by kisslorand** [comment]
Try with the following settings in "Configuration.h":
```
#define SERIAL_PORT -1
#define SERIAL_PORT_2 1
```

**Comment by syszone** [comment]
@kisslorand it did not work

**Comment by kisslorand** [comment]
Is there any chance you flipped the TFT cable? Do you have another TFT to test with? Can you access the mainboard via USB (Octoprint, Printerface, etc)?

**Comment by syszone** [comment]
Flipping cable wont start TFT it will be blank screen, and Marlin mode shows only blank screen. I am trying to connect USB but on my computer it shows Unknown USB Device (Device descriptor request failed) i am using windows 11 if that helps.

**Comment by kisslorand** [comment]
You might have a broken mainboard...

**Comment by oldman4U** [comment]
Any news regarding the reported issue?

Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by syszone** [comment]
@kisslorand i guess you are correct. I will investigate my own on fuse maybe or order new board. Closing this thread. Thank you everyone for try to helping out - cheers
