### ISSUE TITLE
I cannot level my printer in marlin mode  without bltouch!

### ISSUE THREAD

**Issue by DavidFFerreira** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2684]
I cannot level my printer in marlin mode  without bltouch!

**Comment by radek8** [comment]
How does working in Marlin mode relate to FW TFT display?

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by DavidFFerreira** [comment]
marlin configuration is in your board firmware...and that firmware have bltouch enabled....since you have it enabled, i cant level my bed on marlin because it require bltouch

**Comment by radek8** [comment]
Yes, if you have BL-Touch enabled in the Marlin, but it is not physically connected, you cannot level the bed.
So you have to compile a new Marlin.
I ask again, how does this relate to the FW TFT display?
You can deactivate the automatic bed leveling in the display configuration, but this will not solve your problem in Marlin.

**Comment by oldman4U** [comment]
David. Radek8 asks how this is related to the FW because this is the BTT TFT firmware repository but not a user group.

**Comment by oldman4U** [comment]
@Msq001 Could you please check and close.  Thank you
