### ISSUE TITLE
I cant load the config file[BUG] (short description)

### ISSUE THREAD

**Issue by changwang31** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2688]
### Steps to reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior**

**Actual behavior**

### Additional Information
* Include a ZIP file containing your `Configuration.h` or use [Pastebin](https://pastebin.com/) and paste a link in this issue.
* Provide pictures or links to videos that clearly demonstrate the issue.

**Comment by radek8** [comment]
Can you provide more information on your problem?

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
@Msq001 could you please check and close

**Comment by changwang31** [comment]
I fixed it 
in the readme it said to load the file as config.ini
but my model (tft35 e3 V3.0)
wouldn't read it
so i just tried something new and loaded it without the suffix and it worked

**Comment by changwang31** [comment]
and sorry for not closing it 
im new to this community
