### ISSUE TITLE
[BUG] Filament run out sensor not working with tft mode 

### ISSUE THREAD

**Issue by labotecno** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2698]
Filament run out sensor conected to the mainboard doesnt want working to tft mode , but in marlin mode its working well ! 

i put gcod M75 and M77 to the start /end gcod 
`NOTES for users having a filament sensor connected to the mainboard:
#   1) Enable the start/end G-code below.
#   2) Add the following commands to the start/end G-code:
#      - start_gcode: M75\n
#      - end_gcode: M77\n`
filament runout seem dont working , 

`EEPROM_SETTINGS (in Configuration.h)
BABYSTEPPING (in Configuration_adv.h)
AUTO_REPORT_TEMPERATURES (in Configuration_adv.h)
AUTO_REPORT_POSITION (in Configuration_adv.h)
M115_GEOMETRY_REPORT (in Configuration_adv.h)
M114_DETAIL (in Configuration_adv.h)
REPORT_FAN_CHANGE (in Configuration_adv.h)

Options to support printing from onboard media:

SDSUPPORT (in Configuration.h)
LONG_FILENAME_HOST_SUPPORT (in Configuration_adv.h)
AUTO_REPORT_SD_STATUS (in Configuration_adv.h)
SDCARD_CONNECTION ONBOARD (in Configuration_adv.h)

Options to support dialog with host:

EMERGENCY_PARSER (in Configuration_adv.h)
SERIAL_FLOAT_PRECISION 4 (in Configuration_adv.h)
HOST_ACTION_COMMANDS (in Configuration_adv.h)
HOST_PROMPT_SUPPORT (in Configuration_adv.h)
HOST_STATUS_NOTIFICATIONS (in Configuration_adv.h)

Options to support M600 with host & (Un)Load menu:

Options to support dialog with host (as pre requisite)
NOZZLE_PARK_FEATURE (in Configuration.h)
ADVANCED_PAUSE_FEATURE (in Configuration_adv.h)
PARK_HEAD_ON_PAUSE (in Configuration_adv.h)
FILAMENT_LOAD_UNLOAD_GCODES (in Configuration_adv.h)

Options to fully support Bed Leveling menu:

Z_MIN_PROBE_REPEATABILITY_TEST (in Configuration.h)
G26_MESH_VALIDATION (in Configuration.h)
Z_STEPPER_AUTO_ALIGN (in Configuration_adv.h)`

i need some help

**Comment by LTSpenny** [comment]
i don't think this is enough information. The tft has it's own input for the filament run out sensor that you can plug directly into it and set up. When you enable filament runout sensor on the tft settings it's referencing that sensor and setup. If you have your filament runout sensor set up to the main board, then those settings activate regardless of what your tft display mode is in. Have you ensured the correct settings are enabled in marlin? also information useful for this is expected behavior and what you are experiencing. hard to assume what is happening with given information.

**Comment by labotecno** [comment]
> 
my mainboard is skr e3 turbo .
i have no option runout filament sensor  enable from tft . runout filament sensor is connected to the mainboard , my config is Working with marlin mode 
i try to put the gcod M75 and M77 start /end gcod on the slicer and on the tft option too . may be mean serial don't recognize it . i know i can to connecting sensor directly to the tft , but i want to make it working from mainboard . thank you to help me

**Comment by LTSpenny** [comment]
What release are you using. What tft do you have. Im running a tft35 and 43 and i do not use those gcodes in my start and the filament runout sensor works fine. If my filament runs out it triggers an advance pause/filament change. Please tell is what is happening. What happens. What you expect to happen and what it is doing that is not expected.

**Comment by labotecno** [comment]
> What release are you using. What tft do you have. Im running a tft35 and 43 and i do not use those gcodes in my start and the

its make nothing , when the filament is cut it dont stop or make pause just printing  . i use the last release of the firmware from here i have tft35 E3 . do you have your runout filament connected to the  mainboard ? and i have the last marlin firmware bugfix

**Comment by LTSpenny** [comment]
Can you post your config file for your marlin bugfix. How are you printing files? Inserting them into tft or mainboard?

**Comment by labotecno** [comment]
configuration.h 
[Configuration_adv.txt](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/10670741/Configuration_adv.txt)
[Configuration.txt](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/10670742/Configuration.txt)
i print from main board sd card , and i try  too from tft lcd too

**Comment by labotecno** [comment]
someone have a idea ?

**Comment by LTSpenny** [comment]
I looked through your code and it all seem’s good. I highly doubt it is an issue with the tft as the tft just displays what the main board is providing unless you have a runout sensor plugged directly into it. I also do not include those gcodes in my sliced files and dont have issues on my two machines with the tfts. Are you using the master files or older release?

**Comment by purplewazard** [comment]
im also having the same problem i cant get it to work in tft mode when connected to the board or the tft

**Comment by oldman4U** [comment]
Labotecno. Could you please take care of your ticket and answer the replies. Thank you

**Comment by labotecno** [comment]
> I looked through your code and it all seem’s good. I highly doubt it is an issue with the tft as the tft just displays what the main board is providing unless you have a runout sensor plugged directly into it. I also do not include those gcodes in my sliced files and dont have issues on my two machines with the tfts. Are you using the master files or older release?

I m with bugfix last version .
