### ISSUE TITLE
[FR] display alternate filetypes *.g, *.gco, ... in the filelist

### ISSUE THREAD

**Issue by AnHardt** [bigtreetech/BIGTREETECH-TouchScreenFirmware#270]
In the current versions only filetype "\*.gcode* is displayed and selectable.
Other frequently used types "\*.g" and "\*.gco" are not. The content is not different from "\*.gcode" but both are better suitable for a short filename 8.3 file system. For that i have lots of cards with "\*.g" files. Renaming all of them is not that funny.

**Comment by arut16** [comment]
Maybe not a real solution for you but you can use batch renaming function of Total Commander...

**Comment by AnHardt** [comment]
Marlin lists all directories and all files following the "\*.g\*" pattern.

**Comment by bigtreetech** [comment]
Hello, add it in #426, so close here
