### ISSUE TITLE
UBL BL Touch Request

### ISSUE THREAD

**Issue by vMeph** [bigtreetech/BIGTREETECH-TouchScreenFirmware#271]
would it be possible to add UBL BL Touch Options to LCD?
thanks

**Comment by dineshvyas** [comment]
Only crazy icon and useless menu can be added. no real functionality, add one more setting and total firmware becomes jumbled, mismatched icons, none responsive touch.

**Comment by gordo3di** [comment]
@vMeph Can you please close this ticket. Thanks.
