### ISSUE TITLE
[BUG] (update stuck)

### ISSUE THREAD

**Issue by El-kady** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2725]
I'm using TFT24 1.1, when i'm trying to update the firmware
it loading to 55% then it stops

**Comment by raihei** [comment]
Did you try to copy the firmware file to the SD-Card again, reformat the SD-Card or to use another SD-Card?
Which file did you use?

**Comment by El-kady** [comment]
it works only when i keep clicking rest button in ardiuno
is that logical?
also when i connect it using the power supply it keep restarting

**Comment by digant73** [comment]
it seems related to #2726 that you already fixed.
If so, please close also this ticket

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
