### ISSUE TITLE
TFT 2.4 v1.1 with Marlin keep restarting

### ISSUE THREAD

**Issue by El-kady** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2726]
Hello,

I'm using TFT 2.4 v1.1 with Arduino mega and ramps 1.4 (1.6 too)
it works fine on USB power only
when i connect it to power supply it keeps restarting forever
i disconnected the TFT and connected normal  Reprap full screen and it works fine
what is that mean? is that software issue or a hardware issue
how can i debug?

**Comment by El-kady** [comment]
i found the solution, it's all about the power,
arduino default 5v regulator can't handle the screen
i removed it and added a bigger one
solved

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
