### ISSUE TITLE
[Q] raspberry pi os not work with touch pitft50 v1.0

### ISSUE THREAD

**Issue by Andrysky** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2727]
hi please tell me i have bigtreetech pitft50 v1.0
I installed raspberry pi os and connected pitft50 - the display worked out of the box, but the touch sensor does not work / bugs.
I installed the build from https://github.com/bigtreetech/OctoBTT - the sensor works fine.
What do I need to do on the stock firmware to make the touch sensor work?

**Comment by oldman4U** [comment]
Hi. This is the wrong repository for the pitft. Please close this ticket here and open a new one in the related repository or a user group. Thank you

**Comment by Andrysky** [comment]
@oldman4U 
HI, can you tell me where the required repository or user group is?
I can’t create a issue in [bigtreetech/OctoBTT](https://github.com/bigtreetech/OctoBTT) because the repository is in the archive.

p.s. i don't want to search for the company's contacts and write a private letter - as it may be useful to someone else.

**Comment by oldman4U** [comment]
Sorry but I don't own this display.

**Comment by Andrysky** [comment]
up
