### ISSUE TITLE
Position not shown in Unified Menu

### ISSUE THREAD

**Issue by dkoenig42** [bigtreetech/BIGTREETECH-TouchScreenFirmware#273]
The current position for X, Y and Z is always shown as 0.00 in the unified menu.
Temperatures and Fan speed are updated fine.
Hardware Version is V3.0.

**Comment by AnHardt** [comment]
Try to provoke with M114.

**Comment by dkoenig42** [comment]
I tried it, Marlin seems to send correct response "X:-22.00 Y:91.52 Z:31.70 E:0.00 Count A:5562 B:9082 Z:57068"
But still no update of the values on the main page.

**Comment by dkoenig42** [comment]
Short update: If I send "M114 D", the position is updated once. How do I activate an automatic update?

**Comment by dkoenig42** [comment]
I found a solution for me.
I commented out "stepper.report_positions()" in the function report_current_position() in "motion.cpp" in Marlin 2.0. Works fine now.
Looks like the additional stepper information is disturbing the display.

**Comment by dkoenig42** [comment]
Sorry to roll back, but my patch leaves me with Octoprint not working any longer.
Taking a look at parseACK.c of the display, it seems to be waiting for a stepper position of the extruder. But current Marlin 2.0 does not output it (any longer?).
So currently I have no solution.

**Comment by guruathwal** [comment]
which firmware version are you using? can you share the actual data sent by the printer after M114 command?

**Comment by dkoenig42** [comment]
Marlin 2.0.1. 
I made some progress: If I activate "M114_DETAIL" in Marlin, I get updates of the position on the display.
But during printing, the number jump between the correct ones and numbers ways to high. It looks like the display is parsing the move commands from Octoprint and interprets them as positions (maybe because they also contain the strings "X:", "Y:" and "Z.").

**Comment by guruathwal** [comment]
@dkoenig42  firmware version of your TFT?

**Comment by dkoenig42** [comment]
3.0.25, self compiled with Platform i.o.

**Comment by guruathwal** [comment]
can you try the pre-compiled firmware to check if it works. also the position will not update correctly when printing through other host sources as the TFT relies on gcode for position update.

**Comment by dkoenig42** [comment]
I tried the precompiled firmware, same result: positions are not updated correctly when printing from OctoPrint. But if I understand you aswer correctly, thats caused by the design of the firmware, right?

**Comment by guruathwal** [comment]
@dkoenig42  while printing from octoprint the position cannot be updated correctly as the printer will be printing too fast.
