### ISSUE TITLE
[Q] Artillery X2 and TFT35 problems with the filament sensor and other things

### ISSUE THREAD

**Issue by HaYaToSkAn** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2734]
**Your question or details you need. Please describe.**
Hello everyone
I have installed in my Artillery X2 with its original board (Artillery Ruby) a TFT 35 V3.0.1
I have updated Marlin to version 2.1.2
And the TFT with the file "BIGTREE_GD_TFT35_V3.0.27.x"
I have everything connected and working, but I have found some problems that I can't solve.

**Specify the device variant related to your question.**
Motherboard Artillery Ruby (Artillery X2)
BTT TFT35 V.3.0.1
TFT Firmware Version GD_TFT35_V3.0.27.x
Marlin firmware version number 2.1.2

I leave my Marlin and TFT files, as well as photos and videos.
I hope someone can help me
Thank you so much
PS: I have used the google translator, I hope you understand me well

**Additional context**
1. The filament sensor doesn't work, I've tried switching between the options in the TFT config file but nothing happens.
![Filament](https://user-images.githubusercontent.com/101666231/220963305-cbca3266-eb06-42d6-ad73-ee383659cb5e.jpg)
![bigtreetech-tft35](https://user-images.githubusercontent.com/101666231/220963476-b8896523-f2f9-4bf4-94a8-b4789f9af969.jpg)
https://www.youtube.com/watch?v=ashsVZcDBPI

2. When I'm in TOUCH MODE printing and I want to switch to MARLIN MODE it doesn't allow me, it just doesn't give me the option.
On the other hand, when I print from MARLIN MODE and I want to go to TOUCH MODE it lets me.
In the TFT config file I have this option like this:
"serial_always_on:0"
https://www.youtube.com/watch?v=nbrtmp-bWVw

3. When I am printing from the MARLIN MODE option and I go to TOUCH MODE I only see the temperature status and something else, it does not give me the option to pause or cancel the print, to see how long it has been printing, the layer height and others... as if it were printing in TOUCH MODE
I don't know if this is normal or some configuration error.
![marlin to touch](https://user-images.githubusercontent.com/101666231/220965338-e501fc29-7cd4-4bc2-bf3f-a59d080b37fa.jpg)
https://www.youtube.com/watch?v=jL7amO7VS5w

Marlin and TFT Files 

https://drive.google.com/file/d/1UhWS3bAbs4pMcQXgoOs5CO9GaSROTp8n/view?usp=share_link

**Comment by kisslorand** [comment]
1. As far as I know the filament runout sensor on the ASWX2 is an optical sensor which requires 5V to operate. As seen on the picture provided the TFT feeds only 3.3V to the sensor. Do you have the LED lit up? Does it change from green to red as you move in and out filament to/from it?

**Comment by kisslorand** [comment]
As far as I know on the ASWX2 the [filament runout sensor](https://cdn11.bigcommerce.com/s-1vohxdh8gj/images/stencil/1280x1280/products/2444/7565/ART_Lswitch_02__34692.1657037545.jpg?c=2?imbypass=on) is an optical one which requires 5V to operate. In the picture you provided it can be seen that the TFT provides only 3.3V.
Does the LED on the sensor lights up? Does it change color from green to red as you move in and out filament to/from it?

**Comment by HaYaToSkAn** [comment]
> 1. As far as I know the [filament runout sensor](https://cdn11.bigcommerce.com/s-1vohxdh8gj/images/stencil/1280x1280/products/2444/7565/ART_Lswitch_02__34692.1657037545.jpg?c=2?imbypass=on) on the ASWX2 is an optical sensor which requires 5V to operate. As seen on the picture provided the TFT feeds only 3.3V to the sensor. Do you have the LED lit up? Does it change from green to red as you move in and out filament to/from it?


This is the Original TFT that I removed
As can be seen the connector indicates 3.3V
The color it shows is always green, it never changes to red, I suppose it is because the sensor is not working correctly, due to some bad configuration in Marlin or in the TFT firmware.
Thanks for your help

![TFT](https://user-images.githubusercontent.com/101666231/223478873-e4387b3a-6038-418e-b93b-f0f6de19d3d8.jpg)
![TFT1](https://user-images.githubusercontent.com/101666231/223479047-444c6c23-c2bb-48e4-99c1-ccc195b1fb24.jpg)

**Comment by kisslorand** [comment]
> As can be seen the connector indicates 3.3V

Mea culpa, I remembered it wrong.

**Comment by freakydude** [comment]
The filament sensor works with 3.3V and 5V

**Comment by Avatarsia** [comment]
i use the firmware on a stock tft and can confirm that it wont change anything in filament sensor logic when you change it in the config.txt
but it need to be changed

**Comment by kisslorand** [comment]
@HaYaToSkAn

Check if the runout sensor works if you switch the two outside pins in one of the runout sensor cable connector or just try to insert the connector rotated 180°.
