### ISSUE TITLE
Beeping sound while installing on MKS Gen L V2.1 board [Q] (Your Question?)

### ISSUE THREAD

**Issue by dreed47** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2738]
**Your question or details you need. Please describe.**
I'm attempting to install the TFT35-E3 V3.01 on the MKS GEN L V2.1 controller board (w/ Marlin FW).  When I connect the EXP 1 and EXP 2 cables then the RS232 cable to the AUX connectors on the controller board I see the LCD first screen and a constant beeping tone and the touch screen doesn't appear to be working.  

**specify the device variant related to your question.**
TFT35-E3 V3.01
MKS GEN L V2.1 controller board
Marlin  with REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER set on config

**Additional context**

**Comment by radek8** [comment]
They sent a photo of the wiring.
Send configuration files.
Send a video with the problem.

**Comment by oldman4U** [comment]
What is the status of the reported issue?

**Comment by dreed47** [comment]
I will attempt installing this LCD one more time today and provide info.

**Comment by oldman4U** [comment]
Follow the troubleshooting section of the Readme.

**Comment by oldman4U** [comment]
Whats the status of the reported problem?

**Comment by dreed47** [comment]
Unfortunately I have no further details. I was unable to get this unit to work and I needed to return the printer to its owner as I was only repairing it for them.

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
