### ISSUE TITLE
Mixing extruder 

### ISSUE THREAD

**Issue by IoakeimSogiakas** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2740]
I have a weird issue. I have set up marlin correctly with a mixing extruder. In marlin mode, on the load/unload section, I have access to both extruders. However on tft mode I only have access to one. I have build my own firmware and I have defined 2 extruders and I have enabled the mixing extruder option however I still don't have access to the second one. 
Am I missing something? 

![IMG_20230305_220129](https://user-images.githubusercontent.com/74249861/223104086-6e80d372-fd5e-4160-a7d8-4b65e7af21a7.jpg)

**Comment by oldman4U** [comment]
When you press Nozzle?

**Comment by IoakeimSogiakas** [comment]
Sorry I don't remember I will sent an update in about 2h (I am not home). From what I remember it didn't do anything but I might be mistaken

**Comment by IoakeimSogiakas** [comment]
[Update]:it does nothing

**Comment by kisslorand** [comment]
```
#### Hotend Count
#   Value range: [min: 0, max: 6]
hotend_count:1
```

What's the value set to in the "config.ini"?

**Comment by IoakeimSogiakas** [comment]
It is set to 2

**Comment by kisslorand** [comment]
Ah! I just realized you have one nozzle but two extruders. In this case I am afraid the TFT cannot handle more than one extruder per nozzle.

**Comment by IoakeimSogiakas** [comment]
OK I will check it out thanks.

**Comment by radek8** [comment]
In the configuration.h file, set:
#define EXTRUDER_COUNT 2
#define MIXING_EXTRUDER 1
compile your own FW for TFT

in the config.ini file set:
ext_count:2
upload configuration to TFT

**Comment by IoakeimSogiakas** [comment]
The issue is fixed the extruder wasn't a mixing one so it didn't need the mixing functionality
