### ISSUE TITLE
Unknown command: "M420"

### ISSUE THREAD

**Issue by tuono1k** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2747]
Hi, 
my ender 3 pro in driven by an skr mini e3 v2.0 with a TFT35 V3.0 E3. installed as they arrived a couple of years ago. 
last month I upgrade firmware on mainboard with the latest available here (standard one, no bltouch). 
couple of days ago I decided to upgrade also the TFT. on board there was a v27 (not v27.x) dated Apr 28 2021
everything completed correctly (now is V27,x Feb 15 2023) except for one thing....

On any attempt to perform a homing, all or single axes. I got an [Unknown command: "M420"]   error
It seems happened only to me, no information found and I'm pretty sure is related to TFT board upgrade (never seen before).

M420 is related to bed leveling and parsing the config file I found nothing about any M420 attempt and leveling looks disabled
auto_load_leveling:0

the other M420 found is that one but should not used automatically 
custom_gcode_4:M420 S1\n

Printer show the error, then proceed, it works but it is annoying
did not found any V27 dated apr 28 2021 to try to get back
I'm not sure if the hard reset will restore what on board before.

anyone have suggestion on what to try?
by the way, about SD size, I had only the original 128MB and a 16GB one.
No way to upgrade using the 128MB and no problem with the 16GB

thanks

**Comment by radek8** [comment]
The problem was solved here
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/2751

**Comment by tuono1k** [comment]
Thanks, i'll follow there.
