### ISSUE TITLE
[BUG] Popup Message "Unknown Command: M420" when homing

### ISSUE THREAD

**Issue by raihei** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2751]
### Description

When starting a print from the display SD card or homing the axes from the display, the popup message "Unknown Command: M420" is shown on the screen. According to Marlin docs, it is the command to get the bed leveling state.
I have no auto-leveling and it is not enabled in Marlin. "auto_load_leveling" is set to "0" in my config.ini

### Steps to reproduce

 Start print from SD card in display or home axis from the display menu

**Expected behavior**
Message should not be shown

**Actual behavior**
Message is shown and must be confirmed with "OK" to close.

### Hardware Variant
BIGTREE_GD_TFT35_E3_V3_0
### TFT Firmware Version & Main Board Firmware details
Current version compiled from github master branch
Mainboard: Marlin 2.1.2

**Comment by V1EngineeringInc** [comment]
I would like to add to this. It is also a problem for us CNC user. It looks like this was changed in Feb and now we get a warning anytime we home the machine.

One of our users has dug in and found some more info.
The change in Feb, https://forum.v1e.com/t/new-tft-release/37179/16?u=vicious1

And a quick band aid to hide the error, https://forum.v1e.com/t/new-tft-release/37179/25?u=vicious1

I don't think hiding the error is the right choice long term. Ideally, we would love some sort of CNC option to disable things like this, in the config file. 

I am not a skilled enough programmer for this but I can offer testing and a lot of it.

**Comment by V1EngineeringInc** [comment]
Thinking about this some more, a CNC (non-printer) switch/option in the config file would be amazing. Not only could we fix issues like this, we could also disable a few buttons we do not need. That would be a great gateway to a non-printer menu. All the CNC, Laser, Sand table users would really benefit from that.

**Comment by kisslorand** [comment]
If you're building yourself the FW replace `storeCmd("M420\n");  // check bed leveling state` in "interfaceCmd.c" line 1438 with
``` 
if (infoMachineSettings.leveling != BL_DISABLED)
  storeCmd("M420\n");  // check bed leveling state
```

otherwise wait for the fix to be merged.

**Comment by V1EngineeringInc** [comment]
So there is an open PR, or should one of use make one?

**Comment by kisslorand** [comment]
I am pushing a PR right now...

**Comment by V1EngineeringInc** [comment]
You have helped on so many things. I really appreciate what you do!

**Comment by kisslorand** [comment]
Thank you for the appreciation, this "M420" bug was introduced by me so please accept my apologies. I had to fix it if I created it.

**Comment by V1EngineeringInc** [comment]
No big deal. Just glad it should get sorted soon.
