### ISSUE TITLE
BTT TFT35 E3 V3.0 Mixing hotend issue???

### ISSUE THREAD

**Issue by Services8810** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2754]
Hi all,

I have a SKR 1.4 T with two extruders and Mixing hotend. I have compiled my mainboard firmware with these settings.

In the Configuration.h file
set the parameter
#define MIXING_EXTRUDER 1
#define EXTRUDER_NUM 2

At the TFT firmware, I have changed the config.ini file in order to include my 2 extruders, excatly as  "Mixing Extruder" #1055 issue describes. 

set a parameter in the config.ini file
ext_count: 2

I had the same problem, and I could not exchnage extruders in order to feed the filament, so I followed the same article and commected the following lines

![εικόνα](https://user-images.githubusercontent.com/128382823/226340217-167343a2-b16c-418d-89da-e265fd8055d0.png)

The only change is that my parseACK.c files is newer and the lines that I commented were not at 584-588 but at 1164 - 1170.
After that changes I could exchange extruders and prime the filament but as  Option for Mixing_extruder #1123 arcticle describes at the printer name I have an unecessary line with the following

EXTRUDER_COUNT: 1 UUID: cede2a2f-41a2-4748-9b12-c55c62f367ff

I tried to use the file radek8 created by it seams very outdated as it is way smaller than the new file I have.

Can anybody fix this? 

Thanks, 
John

**Comment by radek8** [comment]
Yes

**Comment by Services8810** [comment]
Thank you very much. Should I change also #define Extruder_Count 2 ??? Default was 1

**Comment by radek8** [comment]
Yes you can, it becomes the default value when resetting to factory settings. But the value that will be in the Config.ini file will overwrite this value.
It is important to define the number of ectruders in the Config.ini file and upload this configuration to the TFT.

**Comment by Services8810** [comment]
Thank you once again! I will try these tomorrow.

**Comment by Services8810** [comment]
It is working great. Thanks radek!

**Comment by taraxias** [comment]
please someone tell me what i am doing wrong.. i am going to brake it...
i have made a custom printer with 3 steppers and a mixing hotend.. everything works fine,it prints fine exept that in touch mode i cant change between steppers to change filament. it only "reads" 1 stepper. i follow almost everything i have found in here and nothing,5 days now i cant fix it.. pleaseeeeee help. my motherboard is octopus v1.1 and tft35 e3 v3

![Screenshot_13](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/132169158/4e6edfa6-5380-42bd-a41b-940bfc5420ba)


![Screenshot_14](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/132169158/c2158ee0-417e-421c-b4ae-a0b6989e72ec)


![Screenshot_15](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/132169158/57bbd24f-38f5-4fc2-af5d-2b1902f80476)


![Screenshot_16](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/132169158/317d34c4-8167-4b9d-ace7-e8fd9d992533)


![Screenshot_17](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/132169158/84049bea-78ff-4eb1-a616-e7c1d37bd19e)
