### ISSUE TITLE
BTT SKR 3 EZ / TFT35 V3 no Printer Attached problem

### ISSUE THREAD

**Issue by Tomzrk** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2757]
I Recently changed the board on my ender 5 plus and got SKR 3 EZ with TFT35 v3 , I got the No Printer Attached and when i switch to marlin mode i got a black screen with nothing on it , I changed the Serial port on Marlin few times but nothing helped , i connected that screen to a different 3d printer and it was working fine so i swapped the connector between the 2 machines but its still the same , swapped the RX and TX nothing changed so i was wondering if i ![image](https://user-![image](![image](https://user-images.githubusercontent.com/113375679/227921531-98c77985-6bac-43ba-abd9-944cdf3f4a4c.jpeg)https://user-images.githubusercontent.com/113375679/227921510-71e1c8b6-3cdc-4b13-ad66-3f0f2fb1dd67.jpeg)images.githubusercontent.com/![image](https://user-images.githubusercontent.com/113375679/227921492-d9e6d5c9-ef05-4edc-9cc3-2b9fb4838f16.jpeg)113375679/227921461-492e57fb-d312-4d48-88fc-336b59039642.jpeg)missed something or its a faulty board![image](https://user-images.githubusercontent.com/113375679/227921423-382f88dc-659a-49af-a306-57169026568f.jpeg)

**Comment by Tomzrk** [comment]
[Marlin FW.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/11077860/Marlin.FW
[BIGTREE_GD_TFT35_V3.0.27.x.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/11077876/BIGTREE_GD_TFT35_V3.0.27.x.zip)
.zip)

**Comment by Tomzrk** [comment]
![image](https://user-images.githubusercontent.com/113375679/227926499-27cdc2d7-0898-4caf-84b4-a6539860fb82.jpeg)

**Comment by Tomzrk** [comment]
![image](https://user-images.githubusercontent.com/113375679/227926556-4ae871c1-7e5f-47d3-a0d2-44c29b947768.jpeg)

**Comment by Tomzrk** [comment]
![image](https://user-images.githubusercontent.com/113375679/227926608-ae2dfe24-6647-48f5-abbb-8f5e9c195cdb.jpeg)

**Comment by Tomzrk** [comment]
![image](https://user-images.githubusercontent.com/113375679/227926706-0cbc200f-f7ec-4261-a72f-96100b746c7c.jpeg)

**Comment by Tomzrk** [comment]
@radek8 hey Radek ,any more informations needed ?

**Comment by Tomzrk** [comment]
@radek8 I had them both connected while testing but I took them off after i was done

**Comment by radek8** [comment]
If the display works on another printer, then the problem will be on the SKR.
When uploading FW to SKR, will the file extension be renamed to CUR?
If you connect the SKR to a PC via USB, does the PC communicate with the printer?

**Comment by Tomzrk** [comment]
I found the issue in the marlin firmware , i had the wrong envs selected 

[platformio]
src_dir      = Marlin
boards_dir   = buildroot/share/PlatformIO/boards
default_envs = STM32H743Vx_btt
include_dir  = Marlin 

Instead it should be 

[platformio]
src_dir      = Marlin
boards_dir   = buildroot/share/PlatformIO/boards
default_envs = STM32H723Vx_btt
include_dir  = Marlin

But now I'm having an issue with Z stepper not working when connected to Zam and Zbm

**Comment by Tomzrk** [comment]
That's another issue I'm facing too , when I connect the board to Pc through USB nothing happens
