### ISSUE TITLE
babysteps unified menu 

### ISSUE THREAD

**Issue by vMeph** [bigtreetech/BIGTREETECH-TouchScreenFirmware#276]
would it be possible add option for babysteps in unified menu

**Comment by guruathwal** [comment]
it is already under ABL menu

**Comment by vMeph** [comment]
@guruathwal yes i have seen that but i use UBL and that babysteps not doing nothing
i want the babysteps in realtime adjust while is printing the same way you do with the double click with enconder

**Comment by guruathwal** [comment]
real-time babystepping is only possible through printer lcd. Babystepping through these TFTs is done through GCode, which have to wait in for the printer's gcode buffer to clear.

**Comment by vMeph** [comment]
ya i understand, hopefully there will be away for someone to implement, right now thats the only function that is stoping me to go 100% into use the touch screen mode

**Comment by guruathwal** [comment]
it will only be possible if Marlin firmware supports it. till then you can close the issue.
