### ISSUE TITLE
[FR] Three Point Leveling Support

### ISSUE THREAD

**Issue by thurask** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2762]
**Is your feature request related to a problem? Please describe.**
The stock Ender 3 style hotbed (in all its warped-ness) and carriage only supports four point leveling, but [some third party hotbed upgrades](https://gulfcoast-robotics.com/collections/heated-beds/products/aluminum-build-plate-and-24v-200w-silicone-heater-for-heated-bed-creality-ender-3) are flat enough to allow for three point leveling, i.e. two corners of the same side and the center of the opposite side. I have set up my Ender 3 Pro this way, and as such my leveling points are front left corner, back left corner, and right center, the last of which is missing in the options in the leveling menu for the TFT35 firmware.

**Describe the solution you'd like**
Extend the set of points in the leveling menu to add the centers of the four sides to accomodate 3 point leveling setups.

**Describe alternatives you've considered**
It's possible to [configure Marlin's tramming wizard for three point leveling](https://github.com/MarlinFirmware/Configurations/blob/bugfix-2.1.x/config/default/Configuration.h#L2177), that's what I've been using but it requires me to dip into Marlin mode.

**Additional context**
https://drmrehorst.blogspot.com/2017/07/3-point-print-bed-leveling-vs-4-point.html
https://www.youtube.com/watch?v=W_EWiMIa45s

**Comment by radek8** [comment]
But bolt alignment is not related to your three-point alignment after all.
If you align the corners, the center must be aligned as well.
I would even the corners of the bed.
