### ISSUE TITLE
when i update the firmware i faced this problem - fonts and icons update required

### ISSUE THREAD

**Issue by AliImrangang** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2763]
### Hardware Variant
My Hardware is TFT43 v3.0
### Additional Information
![Marlin_Error](https://user-images.githubusercontent.com/32512084/230757726-b6e7bb51-7fd4-4d3f-ad13-94caedcc8e95.jpg)

**Comment by kisslorand** [comment]
It would have been easier to just read the readme [here](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware#readme), especially [this](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware#installation) section.

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
