### ISSUE TITLE
Display TFT 70 v3.0 not work

### ISSUE THREAD

**Issue by salvioni13** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2774]
I buy new touch panel, but, is not working.... 
I don't know, if the back-light or other problem, the panel not turn on 
![WhatsApp Image 2023-04-17 at 19 54 47](https://user-images.githubusercontent.com/32195601/232627773-e93d95a6-6931-4f39-8bfe-a7f407454870.jpeg)
![WhatsApp Image 2023-04-17 at 19 54 46](https://user-images.githubusercontent.com/32195601/232627778-8f590553-a07f-4b4e-8ede-37059160fa0e.jpeg)
![WhatsApp Image 2023-04-17 at 19 54 46 (1)](https://user-images.githubusercontent.com/32195601/232627780-769e7074-2a17-4376-b023-1cbe279d8a02.jpeg)

**Comment by salvioni13** [comment]
anyone can help me?

**Comment by radek8** [comment]
What doesn't work?
Describe your problem exactly.

**Comment by salvioni13** [comment]
The panel won't turn on

**Comment by kisslorand** [comment]
Can you feed power to it from an external source? I would try to power it on without any connection to the motherboard just to rule out the possibility of  wrong ribbon cable config/connection.

**Comment by salvioni13** [comment]
![IMG_20230418_083757.jpg](https://user-images.githubusercontent.com/32195601/232765612-85ca648d-c256-4d2e-9125-cb900b47d56d.jpg)

![IMG_20230418_083808.jpg](https://user-images.githubusercontent.com/32195601/232765613-0f4fcfe7-8d39-4944-8087-1dc278b2bc4a.jpg)

I try with charger of my smartphone (5v), not again

**Comment by oldman4U** [comment]
Have we removed all the related information from the troubleshooting section!!??

**Comment by radek8** [comment]
Save to SD card the FW for your display along with the icon and font folder.
Put the card in the slot on the display and connect the power.
The FW should be uploaded to the display.

If this does not fix the display, you should return the display to the dealer.

There can be several reasons for the error.
- corrupted bootloader,
- damaged LCD panel,
- damaged flexi tape between the LCD and the board,
- defective 3.3V power supply on the board,
- or anything else,

**Comment by salvioni13** [comment]
thanks  guys... but not work, i think the screen is damaged :(
