### ISSUE TITLE
Getting "Invalid Mesh" popup every time any axis homes itself.

### ISSUE THREAD

**Issue by slwise** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2780]
### Description

I am running Marlin 2.1.2 on a SKR Mini E3 V3 with a TFT35 E3 V3. I am using a glass bed and don't use ABL or MBL. I just use the 5 point bed leveling on the TFT35. Nothing on the printer has changed and everything worked fine until the last update. Now every time any axis homes, it pops up Invalid Mesh. I have went into the TFT35 MBL and saved a mesh but it still pops up. I have tried the RESET.TXT and it brings up the screen calibration when done but the firmware is still at the latest release. The TFT35 will not let me go back to an older version of the firmware that worked. It skips the firmware and goes to loading the fonts and bitmaps. The TFT35 folder and config.ini both get the .CUR extension added the .bin file does not. Saying OK removes the popup and everything prints fine just a real nag. My wife nags me enough that I don't need my printer nagging me also. What am I missing? Someone suggested doing the mesh bed leveling in Marlin mode but haven't tried it yet. The printer is printing great and I don't want to do anything to screw that up. Any suggestions and why won't the TFT35 let me load an older firmware version?

### Steps to reproduce

1. Home any axis, start any print or try the MBL on the TFT35.

**Expected behavior**

No popup!

**Actual behavior**

Invalid Mesh pops up every time an axis homes.

**Comment by slwise** [comment]
Update: I finally did a MBL in Marlin mode and saved it. This appears to have solved the problem. It’s odd this was never required before.

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
