### ISSUE TITLE
[FR] Soft endstop enable/disable button Request

### ISSUE THREAD

**Issue by sarvenn** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2785]
In Marlin mode, I can enable and disable soft endstops. It would be nice to have it under movement menu also, nearby disable steppers.

**Comment by kisslorand** [comment]
You can always have them with custom commands.

**Comment by sarvenn** [comment]
Hi @kisslorand. Yeah, I know. I can also use terminal to send M211 S0/1 commands manually. This is what I do currently.
But I would like to recommend this as a new functional button in TFT mode just like Marlin mode (under move menu).
I'm not a developer but I think hardest part to implement this suggestion is to create a new icon for this button. Doesn't it worth to keep this in the backlog? Usage frequency might not be high, I'm also aware of that. Just wanted to suggest a feature to fill the gap between marlin and tft modes.

**Comment by kisslorand** [comment]
> Hi @kisslorand. Yeah, I know. I can also use terminal to send M211 S0/1 commands manually. This is what I do currently. But I would like to recommend this as a new functional button in TFT mode just like Marlin mode (under move menu). I'm not a developer but I think hardest part to implement this suggestion is to create a new icon for this button. Doesn't it worth to keep this in the backlog? Usage frequency might not be high, I'm also aware of that. 

The SPI flash of the TFT is almost full, it's at 96.78% of its capacity. I know that not used memory is wasted memory, but I still suggest to keep a little headroom. I also use custom commands for not so frequent tasks.
Of course this is only my opinion, I am not entitled to impose anything.

> Just wanted to suggest a feature to fill the gap between marlin and tft modes.

Was this ever a goal?

**Comment by sarvenn** [comment]
Flash size probably would be needed for another important feature. So it is better to go with custom menu.
