### ISSUE TITLE
[BUG] BTT GD TFT35 and SKR mini e3 v3 on Ender3 v2 freezes while printing

### ISSUE THREAD

**Issue by jesseab** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2796]
I saw this thread :  
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/2530

I have the same problem. When printing from usb (and maybe sd too) from the TFT, it randomly stops printing, and the TFT freezes. The motherboard still respond to serial commands if I plug the usb.

Was it ever solved ? I updated the firmware of the TFT to the latest version as well.
I am using a TFT35 V3.0 E3

**Comment by jesseab** [comment]
Thanks for the answer, my printer doesn't hesitate tho, the screen completely freezes and the print stops, however the motherboard still communicate so it's really a TFT problem, however I will try to increase the buffer sizes as suggested !

**Comment by rondlh** [comment]
Do a disk check on your USB drive, make sure it doesn't have errors. You can also try another USB drive.
