### ISSUE TITLE
[BUG] UBL L Corner probing refuses to probe back corners.

### ISSUE THREAD

**Issue by fraserreilly** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2797]
### Description

Probing corners using UBL "L Corner" won't probe the back corners of the bed. Believes the Z probe is past the bed.

### Steps to reproduce

1. Update TFT35 Firmware with bin.
2. Go to L corners via Movement -> Bed Level -> UBL -> L Corner.
3. Select a back corner.
4. Error message of "Z Probe Past Bed"

**Expected behavior**

Should probe the back left and right corners when selected.

**Actual behavior**

Prompts user with error "Z Probe Past Bed".

### Hardware Variant

`BTT TFT35 V3.0`
### TFT Firmware Version & Main Board Firmware details

`BTT TFT35 V3.0 B1.27.x` and `Marlin 2.1.2.1`

### Additional Information

Probing corners will correctly move to the back corners if manually probing (Movement -> Leveling -> Point 3 or Point 4).

[configuration.h paste](https://pastebin.com/qBWcVH9K)

I have indented changes to configuration.h with "// CHANGED".

**Comment by kisslorand** [comment]
Are you on the latest build of the TFT firmware?

**Comment by fraserreilly** [comment]
@oldman4U Although this is not resolved as it seems to be a calculation error (otherwise front should not work either)
