### ISSUE TITLE
Filament Runout Error.

### ISSUE THREAD

**Issue by YpsilonTM** [bigtreetech/BIGTREETECH-TouchScreenFirmware#28]
When i start a print i get this error(filament runout). 
But I dont have a filament sensor.
Dont see in the settings a way to turn it off.

In the printerfirmware its disabled but it looks like its a TFT firmware thing.

![GImage of error](https://i.imgur.com/WCZNKnx.jpg)

**Comment by steveski21** [comment]
Did you find a solution for this cause I'm having the same issue

**Comment by guruathwal** [comment]
The option to disable filament sensor was added in latest updates.. please close the issue
