### ISSUE TITLE
[FR] Printing screen with bar and fan

### ISSUE THREAD

**Issue by Hans007a** [bigtreetech/BIGTREETECH-TouchScreenFirmware#280]
Hello,

I like the 'old' printing screen, but I missed the fan value.
I change the printing.c to this:
![IMG_20200104_185008_3_s](https://user-images.githubusercontent.com/32525735/71771100-2ee94380-2f36-11ea-8f3e-0e05a2c48e19.jpg)

Here is the source code : [https://github.com/Hans007a/BIGTREETECH-TouchScreenFirmware](https://github.com/Hans007a/BIGTREETECH-TouchScreenFirmware)

**Comment by el-quique** [comment]
Hi. Which file do I edit to make it look like that?

**Comment by oldman4U** [comment]
Hi.



Could you please be so kind and close this ticket. Your feature request is covered in the pinned Feature Request ticket #1177 via ticket #732

Thank you
