### ISSUE TITLE
Icons not updating

### ISSUE THREAD

**Issue by ryguyy46** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2803]
I followed the instructions multiple times to update. I made sure the SD card is formatted in FAT32, its not bigger than 8GB. all the icons are in the bmp file. the TFT file has the .CUR at the end after I put it in the machine and turn it on, everything updates except the icons. not sure what else to try or what's going on.

**Comment by ryguyy46** [comment]
![image_67184897](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/135563476/96462f71-fee8-4833-8865-c2e0445b84c2)

**Comment by ryguyy46** [comment]
![image](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/135563476/cd62d70d-8348-4c38-8c89-4b6dca11f282)

**Comment by kisslorand** [comment]
Rename "TFT35.CUR" folder to "TFT35" and make sure you have the latest set of icons in there.
