### ISSUE TITLE
[FR] (feature request title) help is needed

### ISSUE THREAD

**Issue by Andrysky** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2806]
I created an issue - no answer
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/2727

I tried to create a support ticket through the site - the system does not work

I wrote an email to
service001@biqu3d.com,
service004@biqu3d.com,
service005@biqu3d.com,
support01@bigtree-tech.com
no answer

the problem https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/2727 is still relevant

![image](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/5894390/b6b3a36b-328b-4a38-ac09-e49bd6c016fc)

**Comment by radek8** [comment]
oldman4Udne has already written to you that this repository is not for your display and you will not find any of your display here.
Try writing here:
https://github.com/bigtreetech/BIGTREETECH-TouchScreenHardware/issues
