### ISSUE TITLE
Marlin mode glitching out 

### ISSUE THREAD

**Issue by IoakeimSogiakas** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2808]
I am using a normal tft 35(gd version) the issue is this when doing filament load /unload it does this https://youtube.com/shorts/qAIealqtr9k?feature=share
Also in marlin mode it does this for some reason https://youtube.com/shorts/IROpqpYHfAc?feature=share
Everything is connected correctly (the board used is an skr ez. And flashing also is functional (the files are getting renamed)

**Comment by rondlh** [comment]
You will need to provide much more information to be able to answer this question, have a look at the template...

**Comment by IoakeimSogiakas** [comment]
Sorry my bad the issue fixed it self. I was just trying to find a way to delete this issue

**Comment by rondlh** [comment]
Great, then please close the issue

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by IoakeimSogiakas** [comment]
Sorry I thought I closed it
