### ISSUE TITLE
TFT43 installing firmware stm32f4 board not working z axis stepper motors 

### ISSUE THREAD

**Issue by AliImrangang** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2813]
Description
After installing the display firmware on my TFT43, the Z-axis is not functioning properly.

Steps to reproduce
Installed the new display firmware on the TFT43.
After installation, testing the printer's movement.
Noticed that the Z-axis was not responding.
Expected behavior

The Z-axis should have responded to commands and moved as per instructions.

Actual behavior

The Z-axis is not moving at all. All other axes (X and Y) are working as expected.

Hardware Variant
TFT43 V3

https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/32512084/ba50c347-505d-4553-818a-baee9b014388
[Configuration.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/12061769/Configuration.zip)

**Comment by rondlh** [comment]
Are you using the move menu? Does it work when you use the TFT terminal? (G0 Z1)

**Comment by AliImrangang** [comment]
Yes I am using move menu , ok now I am using g code then I will let you
know if any problem
Thanks

**Comment by AliImrangang** [comment]
yes now I run above command in the terminal my z movement is working
through movement manu can I configure by default when tft43 is on and i go
to movement menu z is automatically working.
