### ISSUE TITLE
esp-01 integration failure

### ISSUE THREAD

**Issue by NiKoLo2002** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2814]
hi i have some problem with esp-01. i have programmed it with nodemcu programmaer. all work okey but when i plug in the tft35 e3 v3.0.1 dont show the IP i tryed to short circuit the VCC to EN pin but nothing

**Comment by JLiraEJ8** [comment]
I have the same problem. flash with esp3d.bin, everything ok, I put it on the tft35 e3 v3.0.1 but it doesn't appear on the wifi network or the IP.

**Comment by digant73** [comment]
the esp-01 communicates with the TFT with serial port. The esp-01's IP you configured is just to reach the esp-01 from the WiFi network.
On TFT side you only need to set the serial port where you plugged in the esp-01 with the baudrate you configured on esp-01. E.g . from `Menu->Settings->Connection->S. Port` menu set the WiFi port to 250000 if your esp-01 was configured to 250000
