### ISSUE TITLE
[Q] BTT Mini 1.2 on Ender 3 Pro with TFT35 V3 homing Issues

### ISSUE THREAD

**Issue by nopicklez** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2821]
I just got an ender 3 pro from a friend, with a lot of uninstalled upgrades. 
It was working fine as a vanilla machine.

Then, I installed the BTT TFT35 V3, a BL Touch, the BTT E3 Mini 1.2 board and an all metal extruder. 
I think I did the firmware upgrade correctly. It does not say "no printer found"
at the top. It says "ready".

Once I put the TFT35 in it lets me move the Ender 3 around.
However, if I press the Home buttons
it goes up and then it goes the wrong way to the right and starts ramming against the side. 

If I press the move button it will move correctly. 

If I go to leveling and press ABL it does the same thing. 
If I long press and choose Marlin it just says  LCD12864 Simulator.
It will let me deploy and stow the BL Touch. 
It seems like a lot is working otherwise.

For the board info it says 
BIGTREETECH_TFT35_V.3.0
Firmwares says
TFT35_V3.0.24.2 Nov 15 2019

Not sure where I went wrong, any ideas?
Thank you

**Comment by rondlh** [comment]
I suggest to update the TFT firmware first, also send a G28 (home printer) command to the printer to see what happens.
If movements are going in the right direction when controlled by the TFT, but homing is not, then the homing direction of the printer might be setup incorrectly, either way, this is not controlled by the TFT, it's set in the printer firmware.
