### ISSUE TITLE
tft35 e3 v3 mixing hotend issue?

### ISSUE THREAD

**Issue by taraxias** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2829]
please someone tell me what i am doing wrong.. i am going to brake it...
i have made a custom printer with 3 steppers and a mixing hotend.. everything works fine,it prints fine exept that in touch mode i cant change between steppers to change filament. it only "reads" 1 stepper. i follow almost everything i have found in here and nothing,5 days now i cant fix it.. pleaseeeeee help. my motherboard is octopus v1.1 and tft35 e3 v3

![Screenshot_13](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/132169158/6c96940c-598a-4526-924a-ca54d77aa83e)

![Screenshot_14](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/132169158/696de4d0-da15-4b50-8002-091281e1fa94)

![Screenshot_15](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/132169158/53320dc8-e319-4504-8ad0-e0f53d9882b9)

![Screenshot_16](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/132169158/0a5c4492-d5ca-4a5f-813b-18e2adcfb648)

![Screenshot_17](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/132169158/7519a338-6467-4fde-9515-f13dae16be38)

>>> M503
SENDING:M503
echo:; Linear Units:
echo:  G21 ; (mm)
echo:; Temperature Units:
echo:  M149 C ; Units in Celsius
echo:; Filament settings (Disabled):
echo:  M200 S0 D1.75
echo:; Steps per unit:
echo:  M92 X80.00 Y80.00 Z400.00 E93.00
echo:; Max feedrates (units/s):
echo:  M203 X500.00 Y500.00 Z20.00 E25.00
echo:; Max Acceleration (units/s2):
echo:  M201 X3000.00 Y3000.00 Z100.00 E10000.00
echo:; Acceleration (units/s2) (P<print-accel> R<retract-accel> T<travel-accel>):
echo:  M204 P1000.00 R500.00 T1000.00
echo:; Advanced (B<min_segment_time_us> S<min_feedrate> T<min_travel_feedrate> J<junc_dev>):
echo:  M205 B20000.00 S0.00 T0.00 J0.01
echo:; Home offset:
echo:  M206 X0.00 Y0.00 Z0.00
echo:; Auto Bed Leveling:
echo:  M420 S0 ; Leveling OFF
echo:; Material heatup parameters:
echo:  M145 S0 H210.00 B65.00 F0
echo:  M145 S1 H250.00 B110.00 F0
echo:; Hotend PID:
echo:  M301 P45.80 I3.61 D145.39 C100.00 L20 F10.00
echo:; Bed PID:
echo:  M304 P369.61 I54.13 D602.87
echo:; Power-loss recovery:
echo:  M413 S0 ; OFF
echo:; Stepper driver current:
echo:  M906 X800 Y800 Z800
echo:  M906 I1 Z800
echo:  M906 T0 E800
echo:  M906 T1 E800
echo:  M906 T2 E800
echo:; Driver stepping mode:
echo:  M569 S1 X Y Z
echo:  M569 S1 I1 Z
echo:  M569 S1 T0 E
echo:  M569 S1 T1 E
echo:  M569 S1 T2 E
echo:; Linear Advance:
echo:  M900 K0.00
echo:; Filament load/unload:
echo:  M603 L300.00 U450.00 ; (mm)
echo:; Filament runout sensor:
echo:  M412 S1 ; Sensor ON
ok P15 B3

M115
FIRMWARE_NAME:Marlin bugfix-2.1.x (Aug 23 2023 21:46:53) SOURCE_CODE_URL:github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:foteini is EXTRUDER_COUNT:1 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff
Cap:SERIAL_XON_XOFF:0
Cap:BINARY_FILE_TRANSFER:0
Cap:EEPROM:1
Cap:VOLUMETRIC:1
Cap:AUTOREPORT_POS:1
Cap:AUTOREPORT_TEMP:1
Cap:PROGRESS:0
Cap:PRINT_JOB:1
Cap:AUTOLEVEL:0
Cap:RUNOUT:1
Cap:Z_PROBE:0
Cap:LEVELING_DATA:1
Cap:BUILD_PERCENT:1
Cap:SOFTWARE_POWER:0
Cap:TOGGLE_LIGHTS:0
Cap:CASE_LIGHT_BRIGHTNESS:0
Cap:EMERGENCY_PARSER:1
Cap:HOST_ACTION_COMMANDS:1
Cap:PROMPT_SUPPORT:1
Cap:SDCARD:1
Cap:MULTI_VOLUME:0
Cap:REPEAT:0
Cap:SD_WRITE:1
Cap:AUTOREPORT_SD_STATUS:1
Cap:LONG_FILENAME:1
Cap:LFN_WRITE:1
Cap:CUSTOM_FIRMWARE_UPLOAD:0
Cap:EXTENDED_M20:1
Cap:THERMAL_PROTECTION:1
Cap:MOTION_MODES:0
Cap:ARCS:1
Cap:BABYSTEPPING:1
Cap:EP_BABYSTEP:1
Cap:CHAMBER_TEMPERATURE:0
Cap:COOLER_TEMPERATURE:0
Cap:MEATPACK:0
Cap:CONFIG_EXPORT:0
ok P15 B3

**Comment by Services8810** [comment]
Hi,

From your nickname I asuume you are Greek like me!

Have you compiled the touchscreen firmware? What you are asking has to do only with the touchscreen firmware and not the mainboard firmware.

**Comment by Services8810** [comment]
Hi, I am Giannis also.

You have to compile the tft firmware by editing the configuration files like what you did for the mainboard. The files you uploaded are pre-compiled and have specific settings. Your setup (lile mine) is custom and do not match with the precompiled settings

**Comment by taraxias** [comment]
ok..now i am despert.. i have try it and something i am definitely doing wrong...the bin file i create after the compile, i ender it on the tft screen and it doesnt read it. same thing and when i ender it on the octopus moatherboard

**Comment by Services8810** [comment]
You need to find the master file for the tft firmware. It is a totally different firmware than the mainboard.
You need to change the settings at the config file according to your setup and compile the new firmware. Then upload it to the tft

**Comment by Services8810** [comment]
I will try to find some guidelines to send you...

**Comment by Services8810** [comment]
Read this...

https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/2754#issuecomment-1476614875

**Comment by taraxias** [comment]
ok.. i recompile it, i run it and once again it "runs" the other 2 files but doesnt read the bin file i have create after compile


![Screenshot_18](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/132169158/ddb09d6f-e2a8-498a-9091-cc1fbe20a4cf)

**Comment by Services8810** [comment]
Tft will not read .cur folders and files. It adds .cur the 1st time it reads them

**Comment by taraxias** [comment]
i know. i just send you the photo after i "run" them so you can see that it reads the other 2 files and not the bin one


thats thew original files 
![Screenshot_19](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/132169158/6c5caf40-efa4-4341-80cc-b57fe114bce5)

**Comment by Services8810** [comment]
The .bin file is the one you compiled?

**Comment by taraxias** [comment]
yes

**Comment by Services8810** [comment]
If it does not add .cur I believe it means that it is exactly the same the one in the tft

**Comment by Services8810** [comment]
Can you share the config file of the tft firmware?

**Comment by taraxias** [comment]
[Configuration.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/12432758/Configuration.zip)

**Comment by Services8810** [comment]
The config looks ok. If you compiled the firmware and upload it to the tft you should be able to change Nozzles at the extrude screen. By changing from nozzle 0 to 1 to 2 it will push filament from different extruder to the mixing hotend

**Comment by taraxias** [comment]
thats exactly my problem..  it doesnt changing nozzles.. it stacks to 1.. thats what i am trying to solve 5 days now and i cant

**Comment by Services8810** [comment]
Have you followed this instructions for compiling?

https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/blob/master/README.md#firmware

Under Customization, Firmware click View Full Instructions

**Comment by taraxias** [comment]
i ll check it tomorrow. to tired atm... thanks anyway..

**Comment by Services8810** [comment]
Just  curious... what hotend are you using?

**Comment by taraxias** [comment]
https://biqu.equipment/products/bigtreetech-3-in-1-out-hotend-bowden-extruder-3d-printer-parts-three-colors-switching-multi-color-12-24v-j-head-filament-nozzle?variant=31864589090914&currency=USD&gclid=CjwKCAjwoqGnBhAcEiwAwK-OkScO3TX6Ok4UWguxQWJadoYWuRN8SfHXLUFCtqoJsM0hqVbnEFsexhoCO4YQAvD_BwE

**Comment by Services8810** [comment]
Just for info... it is not mixing hotend, meaning it cannot push two or three filaments at the same time. It is switching, so you have to fully retract the one filament before pushing the other

**Comment by taraxias** [comment]
yea,i know.. i am working to change it with this one atm


![368505329_838662797697842_8068753479887504960_n](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/132169158/c273a667-2772-4432-91e1-4170fceddfcc)


![368451334_268398829305707_5379533722768569159_n](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/132169158/3c76a2f8-cf83-45ca-b19c-5aa3920fc448)

**Comment by Services8810** [comment]
Nice!!! What is the manufacturer of this?

**Comment by taraxias** [comment]
not been sure because they give it to me,but i thing is this one 

[https://www.geeetech.com/a10t-a20t-a30t-3-in-1-out-hotend-kit-p-1126.html](https://l.facebook.com/l.php?u=https%3A%2F%2Fwww.geeetech.com%2Fa10t-a20t-a30t-3-in-1-out-hotend-kit-p-1126.html%3Ffbclid%3DIwAR3fUsGgKfbUSUlFBX_ZByVEfJYeastNgpDOqNCQlc_Q7VVT_0OqTzEYEzg&h=AT33LClcAy6a2K82UOt6i7byQD28WzDkKfF1vFL6QXzwdz2iH41K0vNCMF7ksbCzyFpoFMpr6kIAySTW6iZLukfCJqFALASPedv-6Xy4ENgUjQQJxXTSt1oVokTU-PAggHtFOqVPm0bmhOHoqBhs3w)

**Comment by taraxias** [comment]
i am really ready to smash it.. i made it all right.. i compile it,it changes colors,icons and others setings but no. doesnt want to accept that i have 3 extruders.. i am really despert

**Comment by Services8810** [comment]
Check that you have set both configuration.h and config.ini with the extruder values

**Comment by Services8810** [comment]
Just for check...when you are compiling does it create a .bin and a .elf file?

**Comment by taraxias** [comment]
![Screenshot_20](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/132169158/66976961-f7d1-4414-a1f4-00e075220a6a)

**Comment by Services8810** [comment]
Can you send a pic of your tft?

**Comment by taraxias** [comment]
![368516724_317977190626971_5757006419346056900_n](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/132169158/9b6ad2e4-14ec-470a-934f-000b7eabe4de)

**Comment by Services8810** [comment]
Are you sure it is a GD version???

**Comment by Services8810** [comment]
I had the same and used the bigtree_tft35_v3.0_e3.27 firmware

**Comment by taraxias** [comment]
i have try it before (the bigtree_tft35_v3.0_e3.27) but it doesnt read it at all. i will try it again

**Comment by taraxias** [comment]
nop..nothing change

**Comment by Services8810** [comment]
I will try to send you one...

**Comment by taraxias** [comment]
the thing is that this problem is only at touch screen mode,not at marlin mode 

![371488987_1112635053030209_7397148093216528819_n](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/132169158/e71362a8-6361-4bf0-8e94-17ef2c8d4f13)

**Comment by Services8810** [comment]
Send a pic of your extrude page

**Comment by taraxias** [comment]
what you mean?

**Comment by Services8810** [comment]
Menu -> move -> extrude

**Comment by taraxias** [comment]
![368518157_815744520342514_679682444700582180_n](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/132169158/04748d4f-1fdf-4d06-a8f1-7c7eebf42818)

**Comment by Services8810** [comment]
Press nozzle once and send pic again

**Comment by taraxias** [comment]
nothing change

**Comment by Services8810** [comment]
E0 didn't change to E1?????

**Comment by taraxias** [comment]
nop

**Comment by Services8810** [comment]
Very strange...

**Comment by taraxias** [comment]
dont worry....i will give up..for now...  i will use it with marlin mode for now and when i take care of  all the other problems that comes up, i will find my way and or that.. i hope.. ty for all

**Comment by Services8810** [comment]
I am trying to find how to send you a bin file from the comments, from my phone...

**Comment by Services8810** [comment]
[BIGTREE_TFT35_V3.0_E3.27.x.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/12438821/BIGTREE_TFT35_V3.0_E3.27.x.zip)

**Comment by Services8810** [comment]
Try this one with your config.ini file

**Comment by Services8810** [comment]
Hope it works

**Comment by taraxias** [comment]
salvation....tyyyyyyyyyyy

![371461062_827219529056155_5540826630694052047_n](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/132169158/81242f19-788b-4e4f-b2f7-269ea93682d0)


![368506640_198183499748066_2665112474230879194_n](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/132169158/5d9381d9-e046-45d0-a468-1b41b2e360ce)


![371466257_850441493162680_5859669507024008500_n](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/132169158/be2c70a7-f637-4cb0-9953-bf90298fc232)

**Comment by Services8810** [comment]
Xaxaxaxaxxaa

**Comment by Services8810** [comment]
Glad it worked!!!

**Comment by Services8810** [comment]
It is the 1st time I help someone in github. Usually someone helps me !

**Comment by taraxias** [comment]
thanks a lot for everything. i dont know what you have done better than me(i mean i have almost try everything) but thanks god you did it.. the next step was to use this screen to the voron i am making and just add a simple lcd dislay 12864 and no cat,no harm.. κανε με αν θες add στο φατσοβιβλιο. αν γραψεις γιαννης ταραξιας κυρατσης με ελληνικα θα μεμ βρεις. σε ευχαριστω και παλι για ολα

**Comment by Services8810** [comment]
Χαρηκα που βοηθησα. Δεν εχω fb...
Και εγω δεν ξερω τι δεν δουλεψε σωστα στο δικο σου setup. Σου εστειλα ο,τι ηξερα και ειχα δοκιμασει εγω. Τελος καλο, ολα καλα. Ελπιζω να φτιαξεις πολλα ωραια πραγματα.
Mixing can be quite complicated though. Try SuperslicerMX, it may help a lot
