### ISSUE TITLE
Error after cancel printing 

### ISSUE THREAD

**Issue by andrzej1974** [bigtreetech/BIGTREETECH-TouchScreenFirmware#283]
Hello
In new compilation TFT35 V3.0.25.1 after push stop printing I get this message 
![20200107_220134](https://user-images.githubusercontent.com/58828260/71929410-d619e500-3199-11ea-8f0f-85a41ed220a8.jpg)

but language in menu I have english and few weeks ago in previous soft v3.0.25.1 I dont get this message

**Comment by guruathwal** [comment]
which was the last commit where it was working without error?

**Comment by andrzej1974** [comment]
I'm not sure but I have files from beginning January end working good.

śr., 8 sty 2020, 07:12 użytkownik guruathwal <notifications@github.com>
napisał:

**Comment by andrzej1974** [comment]
this was after
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/266

śr., 8 sty 2020, 07:25 użytkownik Andrzej <andacz6@gmail.com> napisał:

**Comment by guruathwal** [comment]
> this was after #266

did you used the source before this commit or after it?

**Comment by andrzej1974** [comment]
after this and was good

**Comment by guruathwal** [comment]
are you sure? #266 was never merged.

**Comment by andrzej1974** [comment]
this was after remove blue progres percentage bar and apply long filename onboard files. I think is after last changes. But I don't remember exactly.

**Comment by guruathwal** [comment]
can you send/upload the last source code you have which does not gave this error?

**Comment by andrzej1974** [comment]
no problem, but today afternoon

**Comment by andrzej1974** [comment]
this is a last good compilation what i have.
https://drive.google.com/file/d/1orb_UP5fUdR-TcEd7Em4Bq4ENQ-UAABy/view?usp=sharing

**Comment by guruathwal** [comment]
can you share the gcode file you tried to print?

**Comment by andrzej1974** [comment]
https://drive.google.com/open?id=1pAU6V5WBt1x4qPxn1hJdLkohNP23UA3C

there is few, but i try all files.

**Comment by oldman4U** [comment]
Hi.

What is the status of the reported issue?

@andrzej1974 Have you been able to fix the issue in the meantime?

Please let us know

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
