### ISSUE TITLE
[FR] UBL - Shift Mesh by Mesh Mean

### ISSUE THREAD

**Issue by rubienr** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2837]
**FR**
With a Ruby nozzle i want it to not touch the bed at X/Y homing position. Once height is set up correctly (i.e. fine-tuning via Baby Steps), the Z-height may be different after UBL and bed leveling enabled.

**Finding**
With [`#define BED_LEVELING_TYPE 4` in Configuation.h](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/blob/master/TFT/src/User/Configuration.h#L514)  when running bed leveling (see [`void ablStart()` in ABL.c](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/blob/master/TFT/src/User/Menu/ABL.c#L68)) i found to obtain better results when appending [`G29 P5 C`](https://marlinfw.org/docs/gcode/G029-ubl.html) which will compute the mean and shift the mesh by that value:

_It’s useful to be able to adjust the height of a mesh. It can be used to compensate for a poorly-calibrated probe or other errors. Ideally, you should have the Mesh adjusted for a Mean Height of 0.00 and the Z-Probe measuring 0.0 at the Z homing position._
 

**Solution**
Append the G29 G-Code in [ABL.c](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/blob/master/TFT/src/User/Menu/ABL.c#L68):
```
    case BL_UBL:  // if Unified Bed Leveling
      storeCmd("G29 P1\n");
      storeCmd("G29 P3\n");  // run this multiple times since it only fills some missing points, not all
      storeCmd("G29 P3\n");
      storeCmd("G29 P3\n");
      // Find Mean Mesh Height. With C this will automatically execute a G29 P6 C[mean height].
      // Ideally the Mesh is adjusted for a Mean Height of 0.00 and the Z-Probe measuring 0.0 at the Z homing position.
      storeCmd("G29 P5 C\n");
      break;
```

**Comment by digant73** [comment]
please, close this ticket due your PR has been merged
