### ISSUE TITLE
[BUG] Non-functional corner leveling using a probe

### ISSUE THREAD

**Issue by radek8** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2849]
After four months I updated Marlin, and found I had the same problem as shown here:
https://github.com/MarlinFirmware/Marlin/issues/26171

The SERIAL_FLOAT_PRECISION option no longer works in Marlin.
The TFT display is no longer able to analyze the values from the leveling probe due to the format of the value sent by the Marlin.
When leveling and straightening corners with a probe, the measured values are not displayed.
Would someone look into this and fix the problem?
Thank you

### Hardware Variant
TFT 35 E3 V3.0
### TFT Firmware Version & Main Board Firmware details
current TFT Firmware 
current version Marlin 2.1 bugfix

**Comment by kisslorand** [comment]
I already made several PRs in Marlin repository but they haven't merged any PRs since 26th of August 2023.

**Comment by radek8** [comment]
Thank you @kisslorand 
I'll test your fix tomorrow.

**Comment by radek8** [comment]
PR https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/2825
did not solve this problem.

**Comment by kisslorand** [comment]
BTW, this bug is not because of the "SERIAL_FLOAT_PRECISION" not being applied but because the syntax of the response of `G30` has changed and as a result of it the TFT cannot recognize it.
It's one of the fixes in PR #2825.

**Comment by radek8** [comment]
Thank you for the explanation.
After editing, your PR is functional.

**Comment by kisslorand** [comment]
BTW, my PRs regarding the "SERIAL_FLOAT_PRECISION" and G30 response precision has been merged into Marlin.

**Comment by rondlh** [comment]
@radek8 Be careful with Kisslorand, he is not a reliable player and has done several attempts to sabotage this software repository. I'm not sure what his target is, perhaps ransomware, so be sure to **not install any firmware from other sources**. Be warned!
