### ISSUE TITLE
[BUG] TFT35 freezes on mesh edit mode

### ISSUE THREAD

**Issue by FrozenIceman01** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2853]
TFT35 is completely unuseable in mesh edit mode in UBL mesh leveling 9x9.

This is similar to the initial error in prior report before it was corrected.  The TFT display is unresponsive when adjusting mesh position in mesh edit mode. 

Re: [bigtreetech/BIGTREETECH-TouchScreenFirmware] [BUG] TFT35 Mesh Edit throws M14 and unable to adjust Mesh (Issue #2786)

### Steps to reproduce

1. Heat up hot end and build plate to PETG temp 
2. Auto UBL probe 9x9 with bl touch
3. Set probe offset
4. Select mesh edit
5. Select a mesh point
6. Attempt to adjust mesh offset with wheel or touch button
7.  Mesh doesn't adjust, tft freezes, can't switch to Marlin mode
8. Hard reset

Work around
9.  Build mesh on tft 35 side
10. Save mesh
11. Switch to marlin mode
12. Load mesh
13. Adjust mesh in marlin
14. Switch back and forth to tft35 periodically mesh edit , without adjustment, to visually see adjustment points

**Expected behavior**
Tft35 is able to mesh adjust

**Actual behavior**
Tft35 froze and couldn't change mesh offset point

### Hardware Variant
TFT 35 GD E3
Latest, from week of September 28th
SKR mini e3 v3
Marlin 2.1.2

### Additional Information
See prior open issue with images of process.

**Comment by digant73** [comment]
Do you have always the same issue (e.g. when you move to Tuner menu and press on UP/DOWN buttons) or it is a random issue (sometime you get M14, other times a freeze here or there) or you have the issue when closing the Tuner menu (after pressing on the OK button after you adjusted the mesh height) and coming back to Mesh Edit menu?
If you get the issue only when moving back to Mesh Edit menu, from Pronterface, OctopPrint etc. try to use the command:

`M421 I<index I> J<index J> Z<feedrate>`

and verify if you get the same issue or not

**Comment by FrozenIceman01** [comment]
All the time this time

Any time an adjustment is made in mesh edit ot freazes before the change.

**Comment by digant73** [comment]
Sorry your english is not so much clear to me.
So, do you mean that you have a freeze when you press on UP/DOWN buttons in the `Tuner` menu to adjust mesh height? Is that enough for the TFT freeze? do you always get the M14 error message before the freeze?

**Comment by FrozenIceman01** [comment]
Failure mode 1

1.  Enter mesh edit mode.
2.  Select point to edit
3.  Adjust tft35 adjustment knob -> no response and it freezes
4.  Reset.

Failure mode 2
1.  Enter mesh edit mode.
2.  Select point to edit
3.  Adjust tft35 with on screen up or down hutton -> no response and it
freezes
4.  Reset.

**Comment by FrozenIceman01** [comment]
No, the position of the nozzle does not change.  Nor does the display
indicate the position has changed.

**Comment by digant73** [comment]
ok. Are you using the pre-compiled TFT fw from master branch? if possible always try to compile the fw by yourself

**Comment by FrozenIceman01** [comment]
Yes, I was using the precompiled branch on the Master that was released
last week.

I'll work on compiling my own and testing it for late next week.

**Comment by digant73** [comment]
which is your TFT variant? I will compile it for you

**Comment by FrozenIceman01** [comment]
Thank you!

I use the following tft display, it has the GD processor on it.

BIGTREETECH TFT35 E3 V3.0.1

Note, I won't be able to test it until at least Tuesday

**Comment by FrozenIceman01** [comment]
BIGTREE_TFT35_V3.0_E3.27.x.bin

Is the firmware file I used

**Comment by digant73** [comment]
if you have the GD E3 vsersion, shouldn't you use BIGTREE_GD_TFT35_V3.0_E3.27.x.bin?

**Comment by FrozenIceman01** [comment]
Woops, yes you are right, that is the one I used.

Sorry currently looking through github on my phone.

**Comment by digant73** [comment]
try this fw. It includes my PRs. However the `Mesh Edit` is the same as the current official BTT fw. You have to provide the `config.ini` file (even the current one you are using) due I added two new baudrate values on parameter `serial_port`. Eventually, after the fw installation move on `Connection/S Ports` menu and change baudrate for mainboard if it has been changed

[BIGTREE_GD_TFT35_V3.0_E3.27.x.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/12820233/BIGTREE_GD_TFT35_V3.0_E3.27.x.zip)

**Comment by FrozenIceman01** [comment]
Thank you and appreciated.

When I get back to the printer I will try your build.

Thank you!
