### ISSUE TITLE
[FR] Add mechanical gantry Z align to display

### ISSUE THREAD

**Issue by FrozenIceman01** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2854]
Add a G34 mechanical gantry button to display

**Describe the solution you'd like**
Add G34 button to calibration menu

**Describe alternatives you've considered**
Manually send g34 command on tft35 side or select z align button in marlin 

**Additional context**
Convenience improvement for dual z rod printers.

**Comment by digant73** [comment]
As reported in `config.ini`:
- `Z_STEPPER_ALIGNEMENT` enabled in Marlin's `Configuration.h`
- `z_steppers_alignment` enabled (set to 1) in `config.ini`
the G34 button will be available in `ABL/UBL` menu

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
