### ISSUE TITLE
White screen with garbage after uploading firmware

### ISSUE THREAD

**Issue by jimhiggs** [bigtreetech/BIGTREETECH-TouchScreenFirmware#286]
I received tft3.5 v2.0 today and plugged it into my SKR Pro v1.1 worked a treat. I perhaps wrongly assumed the software on it was just a demo so I followed the instructions to update the firmware.
It ticked through the percentage complete then white screen with just a mess. Touch screen seems to do something. I then downloaded  BIQU_TFT35_APP1_V2.0.25.bin from here and put that on the sd card and reset.... Same thing happened. So is it junk now?

**Comment by jimhiggs** [comment]
![IMG_20200107_231318562](https://user-images.githubusercontent.com/33665935/71947539-99eb8200-31a3-11ea-99e8-c50cc4c9dcf5.jpg)

**Comment by Hukuma1** [comment]
You need to copy the TFT35 folder to your SD card as well, not just the .bin firmware. The folder contains the fonts and images (your font is clearly the issue in the photo).

**Comment by jimhiggs** [comment]
Thanks Hukuman1. You are my saviour. I did that and I now have functioning icons but some of them eg Heat/Fan are empty ie no picture?

**Comment by Hukuma1** [comment]
Can you post an updated photo?

**Comment by jimhiggs** [comment]
![IMG_20200108_001524499](https://user-images.githubusercontent.com/33665935/71950004-171af500-31ac-11ea-9e3c-c067d23e1021.jpg)

**Comment by Hukuma1** [comment]
Check your TFT35\bmp folder. Do you have Heat.bmp and Move.bmp? If so, try to do a fresh copy of it to your SD card and overwrite the bmp files. (Simply rename TFT35CUR back to TFT35)

**Comment by jimhiggs** [comment]
Ok did that and yes the files were on the the sdcard and I viewed them ok on pc and when it was updating the icons i watched an none were missing. Just missing in the display. There are others missing too.
![IMG_20200108_002826044](https://user-images.githubusercontent.com/33665935/71950580-2c911e80-31ae-11ea-8462-c4c606592acb.jpg)

**Comment by Hukuma1** [comment]
Oh you are using unified material menu. Those require the other icon set.

Delete your current TFT35 (or TFT35CUR) folder off your SD card and copy fresh TFT35 from this folder: Copy to SD Card root directory to update - Unified Menu Material theme

**Comment by jimhiggs** [comment]
Ok Thanks for your help. Will try that tomorrow now that you have explained the problem. I will have to find out what the difference is between the different menus.

**Comment by Hukuma1** [comment]
You can see the difference on the main Github. Shows the 2 photos: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware

Good luck!

**Comment by jimhiggs** [comment]
Thanks for all the help

**Comment by guruathwal** [comment]
@jimhiggs  please close the issue if it is solved
