### ISSUE TITLE
[BUG] Can't get thumbnails to work properly

### ISSUE THREAD

**Issue by gitmacer** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2864]
### Description

Using the https://github.com/effgarces/Biqu-Thumbnail-Generator exe in combination with super slicer showed thumbnails using the build in fucntion doesn't. Now I wanted to switch to orca slicer. But there build in thumbnail version also isn't showing the thumbnail.
### Steps to reproduce

1. Select BTT TFT thumbnail option
2. save gcode
3. open print menu

**Expected behavior**
Showing the thumbnail

**Actual behavior**
the thumbnail isn't showing
I tried to find out why it isn't working but even removing one of the 70x70, 95x80 and 95x95 thumbnails will break thumbnails.
Or putting the thumbanils inside a THUMBNAIL_BLOCK_START gcode comment.

### Hardware Variant
BIGTREETECH_TFT35_V3.0
### TFT Firmware Version & Main Board Firmware details
TFT Firmware: V27.x Sep 26 2023 in 120Mhz
System: Marlin 2.1.2.1 (Nov 10 2023 15:26:15)

### Additional Information
* Include a ZIP file containing 
[example gcode thumbnails.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/13325303/example.gcode.thumbnails.zip) + config file
* Only the files with works in the filename are showing thumbnails.

**Comment by Rsoft1976** [comment]
use orcaslaser, everything works there, selects the BBT extension and shows everything on the screen
