### ISSUE TITLE
[BUG] BLTouch REPEAT crashes machine

### ISSUE THREAD

**Issue by Tannoo** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2875]
When trying to do the repeatability test from the Touch display, it homes X and Y then tries to home Z but ignores the Zmin limit (not the probe), hence, crashes the nozzle into the bed.

I should add that I have a separate Zmin home sensor (switch) and the BLTouch is a probe only.

### Steps to reproduce

1. Power on the machine or kill the steppers.
2. Select REPEAT icon.
3. Watch it crash.

**Expected behavior**
Home and return to a safe location before testing the probe (ex: X100 Y100) and not crash.

**Actual behavior**
Homes X and Y and crashes while trying to home Z.
G28 works fine in all other instances.
M48 will not execute while X and Y are at home. Errors with probe out of bounds.
M48 will not execute if machine is not homed first.

I can manually execute G28. All fine.
Then execute G1 X100 Y100 and it moves the probe to a probable location.
Then execute M48 and the repeatability test executes as it should.

### Hardware Variant

Board: BIGTREETECH_GD_TFT35_E3_V3.0

Firmware: V27.x Dec 20 2023 in 120Mhz
SPIFlash: Used 96.83% (7.75MB/8MB)

System: Marlin bugfix-2.1.x (Dec 21 2023 12:52:56)

### Additional Information
* Include a ZIP file containing your `Configuration.h` or use [Pastebin](https://pastebin.com/) and paste a link in this issue.
* Provide pictures or links to videos that clearly demonstrate the issue.

[Configuration.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/13746128/Configuration.zip)

**Comment by Tannoo** [comment]
Enabling Z_SAFE_HOMING in Marlin should get around this.

**Comment by rondlh** [comment]
I assume that both the BLTouch and the Z-min endstop are wired to the motherboard?
If so, then this is Marlin issue, not a TFT issue.
A potential solution would be to also use the BLTouch for homing.

**Comment by Tannoo** [comment]
G28 homes just fine from the TFT terminal or the Home icon.

It is not a homing issue aside from the M48 trying to home.

Being that M48 ezecutes just fine from the Marlin mode screen says that Marlin is just fine.

**Comment by Tannoo** [comment]
M48 does not home.

If M48 is issued without being homed.
 From the TFT term or from a serial connection, it just says, "Home XYZ first."

**Comment by Tannoo** [comment]
If I home XYZ from the TFT, or TFT terminal, or from PC, or from Octoprint, all homes just fine.

I do have a separate Zmin ans BLTouch is only for probing...  not homing.

**Comment by Tannoo** [comment]
Once it is homed (Commanded from any source), it runs M48 probing test from TFT terminal, PC, and Octoprint just fine.

**Comment by Tannoo** [comment]
Those sources do not re-home for an M48 command.

**Comment by Tannoo** [comment]
BUT

**Comment by Tannoo** [comment]
The TFT BLTouch Repeat icon DOES re-home all axis and fails homing Z by crashing the nozzle into the bed.

EVERY SINGLE TIME!

Now... HOW IN THE $&#*@^$&@&@ IS THIS A MARLIN ISSUE?

**Comment by Tannoo** [comment]
Btw.... Deviation has been calculated at .000806

**Comment by kisslorand** [comment]
The "Repeat" command on the TFT issues a `G28` and than an `M48` command, nothing more, nothing less.
I do not see it as a bug, it just doesn't fit your printer. I do not see it being an issue of the TFT if your printer crashes the nozzle into the bed when either G28 or M48 is called.

What happens if you issue a `G28` and a `M48' one after the other in your Octoprint/terminal/etc?

**Comment by Tannoo** [comment]
I did disable the G28 command to make this consistenat with all other sources.

**Comment by kisslorand** [comment]
It's great that you found the solution that fits your needs.

**Comment by Tannoo** [comment]
Now, with the machine un-homed, the BLTouch Reset Icon produces the `Home XYZ first`.

So, go back to the Home all icon and it homes X and Y, then crashes Z.

**Comment by Tannoo** [comment]
Okay. I am going to take this up with the marlin team.

The same crash will happen if M48 is issued first and then G28. Then it is expecting to home with the probe and it is not deployed, not used for homing.

Thanks for letting me vent this out!

**Comment by Tannoo** [comment]
> It's great that you found the solution that fits your needs.
> 
> BTW, is your probe offset properly set up in Marlin?

Yes it is and it does perfor the repeatability test just fine.

I am unsure why the repeat icon will crash but run the G28 and M48 back to back from the terminal works just fine.

**Comment by Tannoo** [comment]
Probe setup... well, it homes just fine all the time when not trying to run M48.

**Comment by Tannoo** [comment]
Issued from all sources, G28 fails by failing to home Z using the Zmin switch but ONLY after getting the M48 failed message, "Home XYZ first".

Why does the BLTouch Icon have the same issue but issuing G28 then M48?

I can issue G28 and M48 with no issues from other sources.

**Comment by MrKuskov** [comment]
В прошивке Марлин сделай замену
#define RESTORE_LEVELING_AFTER_G28
//#define ENABLE_LEVELING_AFTER_G28
на
//#define RESTORE_LEVELING_AFTER_G28
#define ENABLE_LEVELING_AFTER_G28

**Comment by Tannoo** [comment]
I have moved on. No longer using Marlin on this machine.
