### ISSUE TITLE
[Q] "Connecting the TFT to the Mainboard" for Manta boards (M5P, M8P)

### ISSUE THREAD

**Issue by petaflot** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2878]
There is a nice[^nice] table that shows how to wire the TFT to a number of motherboards, but there are none of the Manta boards.

If someone has this info, can you please add it?

[^nice]: unfortunately it's not searchable

**Comment by radek8** [comment]
The manufacturer does not expect that you will want to connect this display to the Manta boards via the Uart port.
Manta is designed for Raspberry Pi, and the BTT Pi TFT70 display.
![image](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/46979052/0aa1dc87-1b50-4169-8f43-a1987247ff5a)
