### ISSUE TITLE
[FR] Ability to edit bed-leveling mesh grid in touch mode

### ISSUE THREAD

**Issue by Hukuma1** [bigtreetech/BIGTREETECH-TouchScreenFirmware#288]
**Is your feature request related to a problem? Please describe.**
![ubl](https://user-images.githubusercontent.com/54511555/72014393-9f34e500-3214-11ea-8cfe-4c0c64f6a920.jpg)
Taken from: https://youtu.be/RudXmCgobso?t=224

Would love for BTT to incorporate a way to edit the mesh data that ABL creates in Marlin. UBL has this feature for Marlin mode where you can switch between the points using the knob, which definitely can be improved with touch mode I think. Ideally this would work for bilinear bed leveling, not just UBL. Would love to quickly adjust a specific mesh point with a visual guide (e.g. my left quadrant of the bed needs to be slightly lower Z offset than the rest of the bed).

**Describe the solution you'd like**
ABL/UBL manual editing of mesh z-data points after probing. But I guess if you add this code, you can also add the ability to just add the manual bed leveling mesh creation too?

**Comment by guruathwal** [comment]
that looks like a 5 inch screen...

**Comment by Hukuma1** [comment]
Harder to implement, for sure.

Marlin does have ULB with a similar grid layout though. That would fit:
https://youtu.be/ONpKxkil16Q?t=914

**Comment by traffic-light** [comment]
I decided to make this. I hope that bigtreetech will awnsers my email about a replacement unit soon. And that I would receive one as soon as possible.

Then I can test it when building ;-)

When there is a version that's, in my opinion, good enough to be checked by others I will create a draft.

**Comment by oldman4U** [comment]
Hello Hukuma1.

Your requested feature is available through PR #819 

Please help the community and close this ticket.

Thank you

**Comment by Hukuma1** [comment]
Great work! Thank you all! Closing. :)
