### ISSUE TITLE
[BUG] Display menu names

### ISSUE THREAD

**Issue by radek8** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2881]
I found a problem in displaying the menu names.
I will choose a secondary language (tested in CZ and DE)
Enter the menu. The name of the menu should appear in the upper left corner. Instead of the name, there is a 10% sign.
if i select the language english the menu name is displayed correctly.

DE

![image](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/46979052/05e1fdb3-275f-49af-94ec-2270e9b01945)

![image](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/46979052/e0550fbc-ba75-4eaf-bec9-046127f81a37)

EN

![image](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/46979052/60bf4d08-08b6-4c76-9239-19d125f797e7)

![image](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/46979052/a6ea0aa4-b44f-4a9a-971d-c39565ca0aba)

**Comment by kisslorand** [comment]
This is a very old bug, I knew about it. Actually it was already fixed in the FW in [my repository](https://github.com/kisslorand/BTT-TFT-FW).
I am sick and tired of making bugfixes not to be merged and than copied by others in their PRs.

**Comment by rondlh** [comment]
@radek8 Thanks for the bug report, I will look into it.

@kisslorand Your bugfixed do not get merged because you (force)push buggy, slow and faulty code and don't do peer review resulting in your repository becoming a buggy unsupported mess, making your repository closed source cannot hide that.

**Comment by digant73** [comment]
@rondlh the bug has been identified and it will be fixed on the existing PR plus other bug fixes found on the same piece of code. The major bug was in `drawTemperatureStatus` function that was calling a useless code `GUI_StrPixelWidth(LABEL_10_PERCENT); `

**Comment by rondlh** [comment]
> @rondlh the bug has been identified and it will be fixed on the existing PR plus other bug fixes found on the same piece of code. The major bug was in `drawTemperatureStatus` function that was calling a useless code `GUI_StrPixelWidth(LABEL_10_PERCENT);

@digant73 Right, I also found it and was just about to ask you to delete the line, thanks!

@radek8 For a quick fix just delete the line "GUI_StrPixelWidth(LABEL_10_PERCENT);" at the end of PersistentInfo.c, the problem also doesn't occur if you disable persistent info.

**Comment by kisslorand** [comment]
Sparky and Il Duce... inseparable...
