### ISSUE TITLE
[BUG] BTT TFT35 E3 v3.0.1

### ISSUE THREAD

**Issue by ant0nyk1ng** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2884]
Trying to update the firmware for the BigTreeTech TFT35 E3 v3.0.1 with the GD32F205 chip using the precompiled BIGTREE_GD_TFT35_V3.0_E3.27.x.bin has left me with a black screen and after the initial firmware load.

I have tried 3 different SD card all working and re formatted.

It starts and you can see the firmware writing... it gets to 100% and then the screen goes black. Nothing else happens.
When I remove the SD card and put it back into my computer the .bin file has not changed to .cur nor has the Config.ini and TFT32 Folder.

The screen is at this point unusable and rebooting the screen just results in black screen. It is still able to read the SD card and will do the same as above and nothing more... I wonder if there is an older version of the GD firmware I could try but googling seems to end up back at the Github and the one version available.

I have used it with the config.ini both modified and then the original unmodified. Every time it stop with black screen after firmware writing shown on the screen.

**Comment by thurask** [comment]
Same issue here.

**Comment by ant0nyk1ng** [comment]
Ok after finding version history... I was able to get it working with I think the previous version. 

Here: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/tree/6d49c6e16f03dc561ecf3b02c6a45a22976b40a7

Now if you run this you will find the Listening Mode warning. You just turn it off in the menu it seems.

https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/2202

**Comment by digant73** [comment]
did you try to compile the code by yourself? Also try to reset the TFT (punt the `reset.txt` file on the SD's root folder)

**Comment by ant0nyk1ng** [comment]
@digant73 Yes it loads and does connect to the printer seems to be fine. 

It does also have the TFT Listening Mode warning that has to be set from menu.

**Comment by digant73** [comment]
@ant0nyk1ng ok thanks for the check. The bug is present on all GD versions and is going to be fixed on a new PR

**Comment by baikal** [comment]
Tried to update the TFT on a Biqu B1 (an old one with STM32 chip on TFT), using BIGTREE_TFT35_V3.0_B1.27.x.bin and config.ini from 2023-DEC-15. Update worked fine, but the Display was in 'TFT Listening Mode!' from the immediately after the update - no clicking so far. Must still be some bug that triggers as 'disconnect' after an update?

**Comment by kisslorand** [comment]
Guys, there's a mature FW [here](https://github.com/kisslorand/BTT-TFT-FW).

**Comment by digant73** [comment]
> Tried to update the TFT on a Biqu B1 (an old one with STM32 chip on TFT), using BIGTREE_TFT35_V3.0_B1.27.x.bin and config.ini from 2023-DEC-15. Update worked fine, but the Display was in 'TFT Listening Mode!' from the immediately after the update - no clicking so far. Must still be some bug that triggers as 'disconnect' after an update?

this is ok. `Listening Mode` flag has not been made configurable in `config.ini` but only from TFT GUI. Simply enable/disable `Listening Mode` from TFT (it will be also saved on flash) when needed

**Comment by baikal** [comment]
@digant73 Thank you. That is why I wrote this comment, as I was not sure if that glitch would only be fixed for GD-Variantes by #2885 or all of them (mine was a STM32). Yes, I did enable the connection in the menu and that 'sticks'.

**Comment by digant73** [comment]
> @digant73 Thank you. That is why I wrote this comment, as I was not sure if that glitch would only be fixed for GD-Variantes by #2885 or all of them (mine was a STM32). Yes, I did enable the connection in the menu and that 'sticks'.

it was a minor bug for all TFT variants (STM and GD). It is now fixed on #2885
