### ISSUE TITLE
z auto align G34 not compensate[BUG] (short description)

### ISSUE THREAD

**Issue by demetan71** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2896]
I run a SKR 1.4 Turbo with TFT35 E3 V3
Since I probe for Z G34 sequence do all what he had to do, but doesn't compensate.  Just do movemnet, probe and report...

When I use endstop for Z everything work's fine....

Any idea??

**Comment by rondlh** [comment]
It's very difficult to judge the situation from the provided info, but it sounds like a problem with the flux capacitor.

**Comment by demetan71** [comment]
Thank's everybody, but, I don't understand....  It's worst, I can't print from sd card, bed heating, after said colling bed, screen freeze...  I'm discourage....  Maybe I'm too noob.....

**Comment by digant73** [comment]
TFT fw provides only a button on Menu->Movement->Bed Level->ABL/UBL->Z Align to send a G34 gcode to the printer. To enable this button on the TFT fw you need to set to 1 `z_steppers_alignment` setting on `config.ini` file. To enable the Z auto align on Marlin fw, on Marlin's `Configuration_adv.h` you need to enable `Z_STEPPER_AUTO_ALIGN` setting.

**Comment by demetan71** [comment]
https://github.com/digant73

I realized that I maybe post it on the wrong forum.  Yes I know for the button.  But it was working when I used to home with endstop.  Now I probe z for homing, since that, do the move but doesn't correct anything.

And yes everything is enable in marlin firmware

**Comment by demetan71** [comment]
https://github.com/digant73

Humm...  this issue was closed, but not resolved..... where can I put it???  Do I miss something??

**Comment by digant73** [comment]
it is a possible bug on Marlin so it should be reported here https://github.com/MarlinFirmware/Marlin/issues
