### ISSUE TITLE
[BUG] unknown G17 command

### ISSUE THREAD

**Issue by MrKuskov** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2907]
### Description

in the attached file, when printing through the screen, the message "Unknown G17 command" is written and after the first layer, the hotend moves along the isi Y until it stops. when printing via Marlin Mode, it prints correctly.
[Uploading ring_PLA_22m1s.zip…]()

**Comment by digant73** [comment]
the attachment cannot be downloaded. However, the error message means that the G17 (CNC gcode) command present on the gcode file has to be enabled on Marlin side. If not enabled, Marlin will skip the command (it will not process it) and sends back to TFT that error message. It is not an issue at all on TFT fw

**Comment by MrKuskov** [comment]
Thank you very much. This parameter is disabled, I'll try to turn it on.

**Comment by MrKuskov** [comment]
turned on - the error is gone. thanks
