### ISSUE TITLE
MKS TFT28 Issue with Font file word_unicode.fon

### ISSUE THREAD

**Issue by SpankyDevil** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2929]
MKS TFT28
Firmware MKS_TFT28_V3.0.27.x.bin
config.ini (Only changed Serial Port 1 baudrate to 250000)
Tried all the TFT28 Themes

When updating Fonts SD:/TFT28/font/word_unicode.fon gets to 25% and then changes to unreadable characters.
Once the update is complete the Dashboard is unreadable.

See the post below for images.

**Comment by rondlh** [comment]
**My recommendations:**

1. Download the latest build: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/archive/refs/heads/master.zip
2. Inside the archive select the firmware you need (MKS_TFT28_V3.0.27.x.bin)
3. Select the language pack you want (language_en.ini).
4. The default language is English as defined in config.ini (should be: "language:0")
5. Flash these 3 files, and you should be greeted in English.

**Comment by SpankyDevil** [comment]
> **My recommendations:**
> 
> 1. Download the latest build: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/archive/refs/heads/master.zip
> 2. Inside the archive select the firmware you need (MKS_TFT28_V3.0.27.x.bin)
> 3. Select the language pack you want (language_en.ini).
> 4. The default language is English as defined in config.ini (should be: "language:0")
> 5. Flash these 3 files, and you should be greeted in English.

Its like the language files are corrupted, I tried different ones and none are the language they are meant to be.

**Comment by SpankyDevil** [comment]
![20240515_173215](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/75092373/7c92deec-d1d2-4c93-a131-a3d31189eb4c)
![20240514_185629](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/75092373/0d2c1a7c-4998-443c-8c2f-00efe97db021)
![20240514_185647](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/75092373/62d6d41b-0eec-4196-bdaf-ed5d36ad6771)

**Comment by SpankyDevil** [comment]
I deleted the word_unicode.fon file from within the TFT28\Font\ Folder and created a blank file with the same name.
Reflashed and now everything is working in English.
![20240517_092738](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/75092373/467ae7f5-b6e1-42d7-8e5a-bfa69bbf312b)
![20240517_092809](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/75092373/6b6e6e2c-d75b-46b8-ace6-bca5d548e6c0)
![20240517_092921](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/assets/75092373/1d059c58-8455-4fc6-94c1-f9ca4feef5f5)
