### ISSUE TITLE
Replace STM32F105RCT6 from BTT TFT24 v1.1

### ISSUE THREAD

**Issue by gazikcorp** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2931]
Hello friends, I need help, with the voltage bracket the percentage in the display died, I replaced it with a new one, but I can’t flash it... As I understand it, I need to program the bootloader? If so, how to do it, I would be very grateful for your help

**Comment by rondlh** [comment]
You will need to do much better to give anybody a chance to help you

**Comment by gazikcorp** [comment]
We managed to find out that to revive you need a dump taken using the ST-Link programmer from the working display
