### ISSUE TITLE
BTT TFT70-BX-V3.0 

### ISSUE THREAD

**Issue by Cracoukas** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2932]
Is there a way change parameters to get a working solution for the BTT TFT70-BX-V3.0  (running with the SKR SE-BX V3.0) ?

**Comment by digant73** [comment]
if you are referring to the se-bx printer, no that TFT has no MCU (it is completely controlled by the mainboard).

**Comment by Cracoukas** [comment]
Too bad, BigtreeTech is rewally a pain.
