### ISSUE TITLE
[BUG] Message not shown for M0/M1

### ISSUE THREAD

**Issue by alvv-z** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2939]
### Description

When executing `M0` or `M1`, the display only shows a dialog reading 'Pause' instead of the message.
### Steps to reproduce

1. Execute `M0 Test`

**Expected behavior**

The message is displayed.
**Actual behavior**

The message isn't displayed.
### Hardware Variant

TFT35-E3 V3.0 with SKR Pro 1.2
### TFT Firmware Version & Main Board Firmware details

TFT: BIGTREE_TFT35_V3.0_E3.27.bin
Marlin: 2.1.1

**Comment by rondlh** [comment]
How do you "execute" the M0/1 command?

When send the command in the TFT terminal you stay in the terminal screen, and the message comes once you leave the terminal screen.
If you send the command via ESP3D connected to the TFT, then the message comes immediately.

**Comment by alvv-z** [comment]
Yes, when I send it from the terminal. When it comes up in the gcode file however, no message is displayed.
