### ISSUE TITLE
[BUG] (short description) TFT35 display no longer updates temperatures from printer

### ISSUE THREAD

**Issue by dmarnel** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2949]
### Description

TFT35 display no longer updates the hot end or bed temperatures from the printer until the print begins.

Machine: Creality Ender 3 Pro

Printer board: BTT SKR Mini E3 V2.0
	chip: STM32F103 RCT6

Display board: BTT TFT35 E3 V3.0
	chip: STM32F207 VCT6

Marlin bugfix-2.1.x (as of 8-19-2024)

BIGTREE_TFT35_V3.0_E3.27.x.bin (as of 8-19-2024)

### Steps to reproduce

1. Initiate print

**Expected behavior**

Hot end and bed temperatures should update on the display while the printer is heating up.

**Actual behavior**

Hot end and bed temperatures do not change until the print begins.

### Hardware Variant

TFT35 E3 V3.0
### TFT Firmware Version & Main Board Firmware details

BIGTREE_TFT35_V3.0_E3.27.x.bin (as of 8-19-2024)
Marlin bugfix-2.1.x (as of 8-19-2024)

### Additional Information
* Include a ZIP file containing your `Configuration.h` or use [Pastebin](https://pastebin.com/) and paste a link in this issue.
* Provide pictures or links to videos that clearly demonstrate the issue.
[Configuration.h.zip](https://github.com/user-attachments/files/16676586/Configuration.h.zip)

**Comment by radek8** [comment]
Set Parameter
emulated_m109_m190:1

**Comment by dmarnel** [comment]
Thanks, but that is already set.

**Comment by radek8** [comment]
How old is your FW in the display?

**Comment by radek8** [comment]
Send both Marlin configuration files and ini TFT file

**Comment by dmarnel** [comment]
Thank you, I Appreciate the help. Here are the files.

[Archive.zip](https://github.com/user-attachments/files/16821213/Archive.zip)

**Comment by radek8** [comment]
The configuration is fine.
The display should update the temperature as soon as you start printing.

**Comment by radek8** [comment]
In the display menu, do you have the M109, M190 (green dot) emulation option enabled in the settings?

**Comment by dmarnel** [comment]
Yes, M109 is enabled. Here are my settings:

![IMG_6777](https://github.com/user-attachments/assets/3f320071-06f2-418e-8db2-30d58b761c2b)
![IMG_6778](https://github.com/user-attachments/assets/25505eaf-b481-40f8-9ceb-52642cbfd713)
![IMG_6779](https://github.com/user-attachments/assets/553ca4af-b17f-44d3-b14d-bf0639bb39d6)
![IMG_6780](https://github.com/user-attachments/assets/08b8565c-4c28-4265-9f36-7c1330a0dea1)
![IMG_6781](https://github.com/user-attachments/assets/6f770533-6a02-438c-8257-7f67b5a13aac)

**Comment by MontanaCA** [comment]
Has a fix for this issue been identified?

**Comment by dmarnel** [comment]
Not that I am aware of, but I haven’t updated the firmware since then.
