### ISSUE TITLE
[BUG] UI don't accept IP-adresses like xxx.xxx.xxx.xxx

### ISSUE THREAD

**Issue by LordMM74** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2954]
I try to add a printer ... but the ui is totally buggy.
IP adresses could not be entered.

This is a very stupid bug ... why developer do this? 
Why there a no tests before publishing?

Each stupid unittest can find such a bug.
Please fix it immediately ... the device is not usable in my case.

If there will be no fix in near future i will refund my device.

**Comment by rondlh** [comment]
What are you talking about? Please clarify immediately
