### ISSUE TITLE
[Q] (Need help after Updateing the TFT, touch is not working)

### ISSUE THREAD

**Issue by DJ-78** [bigtreetech/BIGTREETECH-TouchScreenFirmware#2957]
Hello, I have the problem that the touch no longer works after the update. 
The update itself works fine, no errors.
I can see the new frontend but the touch doesn't work.
At the end of the update I expected to see the touch calibration but it didn't start.
Even if I try with the “reset.txt” file on an empty SD card, the calibration does not start!

I have the GD32F305 chip. 
Sidewinder X2

When I upload the stock firmware the touch works again.
Any ideas on how I can get the TFT to work with the new firmware?

**Comment by rondlh** [comment]
> Any ideas on how I can get the TFT to work with the new firmware?

Sure, many ideas, but nothing much to go on here if you are this vague.
