### ISSUE TITLE
Add UBL

### ISSUE THREAD

**Issue by ETE-Design** [bigtreetech/BIGTREETECH-TouchScreenFirmware#298]
Could you pls. add UBL to the screen like the Creality CR-10S Pro have... Would be a really nice feature.

**Comment by guruathwal** [comment]
the same request has already been submitted by @vMeph #271

**Comment by ETE-Design** [comment]
Pls. Add this, and for all sensors like Enductive Sensors also...

**Comment by dineshvyas** [comment]
crazy for icon and menu... no real functionality. after every update firmware goes haywire, totally broken.
