### ISSUE TITLE
Firmware version history

### ISSUE THREAD

**Issue by kattivik76** [bigtreetech/BIGTREETECH-TouchScreenFirmware#3]
please can you add a firmware version history to BIGTREETECH-TouchScreenFirmware repository?

from **BIQU_TFT35_V1.2.12.bin** to **BIQU_TFT35_V1.2.20.bin** what are the changes made?

thx! :)

**Comment by bigtreetech** [comment]
Okay, I'll do that. In fact, there's no difference between v1.2.12 and v1.2.20, except that compatible codes for TFT28 and TFT24 have been added to this project.

**Comment by bigtreetech** [comment]
One more thing, boot code of “bmp” folder  icons and “font” folder font file added

**Comment by guruathwal** [comment]
@kattivik76  you can close the issue now..
