### ISSUE TITLE
Menus disappear after compiling

### ISSUE THREAD

**Issue by Canoivan** [bigtreetech/BIGTREETECH-TouchScreenFirmware#300]
Hi, it seems that I have a problem that I cannot solve, I have the tft24 v1.1 screen and I am compiling the firmware to put the size of my hot bed in #define X_MAX_POS 300
#define Y_MAX_POS 300 and when I compile it on the screen the 4-point calibration menu and some other things disappear, but when I load the predefined firmwre if these menus appear but with a hot bed size of 235.

How can i fix this?

Thanks in advance.

**Comment by guruathwal** [comment]
you need to enable UNIFIED_MENU in configuration.h
