### ISSUE TITLE
[FR] (Mix menu)

### ISSUE THREAD

**Issue by dineshvyas** [bigtreetech/BIGTREETECH-TouchScreenFirmware#301]
color mixing menu as in the simulator mode. it will be really nice feature to have in touch mode.

**Comment by oldman4U** [comment]
Could you please be so kind and close this ticket. Your feature request is covered in the pinned Feature Request ticket #1177 

Thank you

**Comment by oldman4U** [comment]
Hi.

I do not know the color mix menu in Marlin, so could you please install the current master firmware to see if the recently added led functions solve your FR.

Thank you

**Comment by oldman4U** [comment]
Unfortunately the user who asked for this feature does not answer anymore. So I expect it to be solved with #1853 and remove it from the FR list.
