### ISSUE TITLE
[FIX] TOUCH SCREEN miss calibrated (reset and calibrate new)

### ISSUE THREAD

**Issue by ORGATHM** [bigtreetech/BIGTREETECH-TouchScreenFirmware#308]
After flashing new firmware, i saw only pixel blocks, no characters.
so i touched not the red dots and miss configured the touchscreen.
it was not possible to enter the right menus. flashing all versions of firmware does not 
got me the option to calibrate again.

FIX:
after reading the source code i found a hint, that i have to create a new file 
named: **reset.txt**
**copied to the sd card, restarting(reset) display.** 
now i was able to do a new calibration.

maybe you have to insert this info into your manual. not everybody can read and understand c++ source code.

**Comment by ddggrr** [comment]
I have the same problem.  No menu on startup after flashing firmware. Only this screen. 
![FullSizeRender](https://user-images.githubusercontent.com/65795208/82717847-7edb6380-9ca7-11ea-87d8-8748179932f6.jpg)
Help me please.

**Comment by jotavcd** [comment]
im having the same problem. what did you put inside the reset.txt?
