### ISSUE TITLE
[Issue] TFT35 Previews not showing up correctly.

### ISSUE THREAD

**Issue by bkzspam** [bigtreetech/BIGTREETECH-TouchScreenFirmware#313]
Hi all,
I have a TFT35 V2 with latest firmware configured by self. My problem is previews not showing up or just a "static" picture. This is happening when printing files. 
For preview I'm creating a picture 95x95 with this name format: file_95.bmp

Pictures:
https://pasteboard.co/IREDyOU.jpg
https://pasteboard.co/IREE3hJ.jpg

**Comment by Hukuma1** [comment]
Are you able to create custom icon just fine? Could be an issue of how you're saving the BMP file.

**Comment by bkzspam** [comment]
> Are you able to create custom a icon just fine? Could be an issue of how you're saving the BMP file.
> 
> https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/blob/master/readme/English/How%20to%20custom%20icon%202019-11-11.pdf

I already made some icons, they are working fine. Only preview not works.

**Comment by rndsum** [comment]
Copy it to the SD card again and let it refresh, if that doesn't fix it re-export it so it rewrites the main image. 

It's a sign that the file was corrupted during one of the processes either writing to the SD card on the computer/display being dirty, or the file from whatever photo editor your using.  I've had the issue with several things best to write the images one at a time to the firmware if you can.

Might also want to wipe down your card with some alcohol & let it dry to ensure there's no oils on it.

**Comment by alagerqvist** [comment]
I took one of the bmp files provided in the github for firmware and renamed it to reflect the <file>.gcode => <file>_95.bmp and it worked just fine when started print.
I have a TFT35 V3 but that should not make any difference in this case.
I think you have the wrong format of the bmp file, there are many different ways to make a bmp and the firmware is somewhat restricted.

**Comment by bkzspam** [comment]
I used modelbuilder but nothing changed. Just once it worked out well. I still don't know why this is happening.

**Comment by oldman4U** [comment]
Hi. BTT released a great way to get this function today. Could you please check and close this ticket afterwards. Thank you
