### ISSUE TITLE
[Q] How to disable top status line

### ISSUE THREAD

**Issue by billydragon** [bigtreetech/BIGTREETECH-TouchScreenFirmware#316]
Can anybody can tell me how to disabled this status line? I don't need it show overlap the printing screen.

![SharedScreenshot](https://user-images.githubusercontent.com/51144107/73157958-217a4000-4115-11ea-8ab0-bdfef1db63fc.jpg)

**Comment by guruathwal** [comment]
There is an option to disable in settings. Goto Setting>Feature settings

**Comment by emtrax-ltd** [comment]
i think the visibility while "printstatus" is a bug.

**Comment by billydragon** [comment]
Yes, don't need when printing because printing screen have all information. This display is helpfull when not printing only

**Comment by bkzspam** [comment]
> There is an option to disable in settings. Goto Setting>Feature settings

I can't find that option. Where is it?

**Comment by emtrax-ltd** [comment]
hide globalInfo while menuPrinting is active -> https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/commit/499e6f3533db9d9bde24d4c1dae92ef7b4268889

**Comment by guruathwal** [comment]
@bkzspam  yes there is an option named: `Persistent Status Info` in `settings > Feature Settings` try clicking the page down button.

**Comment by billydragon** [comment]
> hide globalInfo while menuPrinting is active -> [499e6f3](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/commit/499e6f3533db9d9bde24d4c1dae92ef7b4268889)

Yes. Now it disappeared when printing and in main status screen. Thank you.

**Comment by bkzspam** [comment]
> hide globalInfo while menuPrinting is active -> [499e6f3](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/commit/499e6f3533db9d9bde24d4c1dae92ef7b4268889)

Thank you so much.

**Comment by bkzspam** [comment]
> @bkzspam yes there is an option named: `Persistent Status Info` in `settings > Feature Settings` try clicking the page down button.

I suppose my firmware is different from you supposed. 
![1580193763167](https://user-images.githubusercontent.com/60302005/73241316-57b5cf00-41aa-11ea-9429-a81c57a040a8.jpg) (Features setting menu)

**Comment by guruathwal** [comment]
@bkzspam The option is in List Mode. you are using the Icon Mode.

**Comment by bkzspam** [comment]
> @bkzspam The option is in List Mode. you are using the Icon Mode.

You are correct. Then I can add it for the Icon mode.

**Comment by mikefromups** [comment]
For version TFT Firmware version 3.0.25.1.

Remove Global Extruder and Bed temp from "Printing" Screen so it doesn't cover up your filename.  It is not needed on this screen since it is already in the center.

There is a new file in 3.0.25.1

TFT\src\User\Menu\Parametersetting.c

Change this line 
if(infoMenu.menu[infoMenu.cur] == menuMove || infoMenu.menu[infoMenu.cur] == menuStatus) return;

To This
if(infoMenu.menu[infoMenu.cur] == menuMove || infoMenu.menu[infoMenu.cur] == menuStatus || infoMenu.menu[infoMenu.cur] == menuPrinting) return;
