### ISSUE TITLE
Turn the screen on and off in Marlin mode

### ISSUE THREAD

**Issue by JRMSBr** [bigtreetech/BIGTREETECH-TouchScreenFirmware#318]
I modified the code a little to test a very interesting function, especially for those who have a printer in the room and the LCD keeps lighting

I think it could be an interesting feature to include in the next update 😄 

Below is a short video of how it looks:
https://youtu.be/wlFI2IMuc7I

Thanks :)

**Comment by oldman4U** [comment]
Like!

;-)

**Comment by guruathwal** [comment]
Nice. you can push a PR to merge your changes.

**Comment by JRMSBr** [comment]
I'm new here, I don't know how it works right here

I have a link to my firmware

https://www.dropbox.com/sh/8uoo9a4pz2mooac/AABbuD8Mhzrj5T4hb-LOZL9Ca?dl=0

**Comment by oldman4U** [comment]
Hi JRMSBr.

This feature will be part of a future release. So stay tuned;-)
