### ISSUE TITLE
TFT35 E3 V3.0 Icons and Fonts not updating

### ISSUE THREAD

**Issue by Blootsch** [bigtreetech/BIGTREETECH-TouchScreenFirmware#323]
My SD card structure is as described (TFT35 directory with bmp and font sub-directories, BIGTREE_TFT35_V3.0.25.1.bin file).
When I try to update the firmware of my TFT35 E3 V3.0, bin file is being processed but not the icons and fonts. I end up with an updated firmware with only part of the icons (some are left blank / white).
What is going wrong, please ?

**Comment by guruathwal** [comment]
take a look at these issues:
they also had same problem but different causes:
#286  & #123

**Comment by Blootsch** [comment]
@guruathwal Thanks a lot!
As in case #123 my SD card was in exFAT. After formatting with FAT32, update process is now working smoothly.
