### ISSUE TITLE
[BUG] Material theme TFT24 & TFT28 Logo.bmp are the wrong files

### ISSUE THREAD

**Issue by appideasDOTcom** [bigtreetech/BIGTREETECH-TouchScreenFirmware#334]
### Description
The Logo.bmp files that are currently in the repository for the Material Theme for the TFT24 and TFT28 icons are 70x47 pixels. Probably got the wrong files uploaded. The file for TFT35 and those in the other theme look correct.

https://raw.githubusercontent.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/master/Copy%20to%20SD%20Card%20root%20directory%20to%20update%20-%20Unified%20Menu%20Material%20theme/TFT24/bmp/Logo.bmp

https://raw.githubusercontent.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/master/Copy%20to%20SD%20Card%20root%20directory%20to%20update%20-%20Unified%20Menu%20Material%20theme/TFT28/bmp/Logo.bmp

### Steps to reproduce
Open the Logo.bmp files from /Copy to SD Card root directory to update - Unified Menu Material theme/TFT24/bmp/ or /Copy to SD Card root directory to update - Unified Menu Material theme/TFT28/bmp/

**Expected behavior**
Files are supposed to be 320x240, according to the documentation

**Actual behavior**
Files are 70x47

**Comment by guruathwal** [comment]
thanks for notifying.. will update in next PR
