### ISSUE TITLE
[FR] Rename firmware file after successful update

### ISSUE THREAD

**Issue by appideasDOTcom** [bigtreetech/BIGTREETECH-TouchScreenFirmware#340]
**Description**
It would be nice if the firmware file were renamed from `BIGTREE_[hardware-version].[software-version].bin` to `BIGTREE_[hardware-version].[software-version].CUR` after successful update of the firmware.

**Describe alternatives you've considered**
None. Leaving it as-is doesn't really harm anything - it's just a minor annoyance from time to time.

**Additional context**
Three advantages:
1. It would make the firmware update process consistent with both Marlin and icon/font updates for the TFT
2. It provides confirmation that the new firmware was uploaded/updated
3. You won't inadvertently re-upload the same firmware when you reset the printer or screen and have forgotten to remove the SD card after an update.

Obviously, this is a minor detail, but it's probably not that difficult to pull off, and it would make the firmware update process a little nicer.

**Comment by bigtreetech** [comment]
merged in #425,  so close here.
