### ISSUE TITLE
[Q] Possible issues with M43 or M503 commands over routed serial 

### ISSUE THREAD

**Issue by gilliands** [bigtreetech/BIGTREETECH-TouchScreenFirmware#343]
Using the current firmware (today's update) and I'm finding that issuing any command that generates lots of response such as the M43 or M503 commands will cause the TFT to stop responding to serial commands routed though it.  On occasion, it will return a "communication error".

I was using the gcode console on both an ESP-01S and ESP-12E running recent (Jan) ESP3D with 4MB FLASH.
Most commands work as expected.  M commands that return a lot of data invariably fail.  Has anyone else seen this behaviour? I'm getting it on a TFT24 V1.1 and TFT35 E3 V3.

**Comment by bigtreetech** [comment]
it should be fixed in lastest version, please confirm
I will close here.
