### ISSUE TITLE
ABL error

### ISSUE THREAD

**Issue by clumsyzombie** [bigtreetech/BIGTREETECH-TouchScreenFirmware#346]
![image](https://user-images.githubusercontent.com/15150210/75129159-584c6300-568d-11ea-9a45-111a3ee27636.png)

Question i have never had auto bed leveling but ever since just loading the default firmware for the TfTT 3.5 I have gotten then error how do I disable it?

**Comment by clumsyzombie** [comment]
Found https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/342  now wow didn't see it before when i searched

**Comment by FoxtrottPL** [comment]
Switch to Marlin mode , then prepare mesh bed leveling , after store mesh, switch again to touch mode.
