### ISSUE TITLE
On my TFT24 1.1 picture is mirrored. How can I fix it?[Q] (Your Question?)

### ISSUE THREAD

**Issue by menahov** [bigtreetech/BIGTREETECH-TouchScreenFirmware#347]
12864 emulator and touch mode are mirrored. Where in firmware I can fix it?

**Comment by bigtreetech** [comment]
Hello， Can you solve it in "Settings->Screen->Rotate UI" ?

**Comment by menahov** [comment]
No, its just rotate upside down, screen still mirrored. Information shows from right to left

**Comment by dineshvyas** [comment]
It may sound silly but I suggest you use a different ribbon cable. I faced
screen flikring, shifting and mirroring. Made new cables and probles
solved.
