### ISSUE TITLE
TFT24 with software supporting long filenames freezes when browsing SD card

### ISSUE THREAD

**Issue by Enderos** [bigtreetech/BIGTREETECH-TouchScreenFirmware#350]
### Description

TFT24 v1.1 after upgrade to SW version Vx.x.25 (supporting long filenames) freezes when trying to print anything from SD card (whatever from TFT card reader or connected SKR mini E3 v1.2) with message: _Unknow command: "M33 ECCENT~1.GCO" ok_. I assume _ECCENTRIC NUT.GCO_ is the first file with long name it tries to get path to.

### Steps to reproduce

1. Upload SW supporting long filenames
2. Try to print from file with long name

### Hardware Variant

TFT24 v1.1 connected to SKR mini E3 V1.2
### TFT Firmware Version & Main Board Firmware details

Vx.x.25
### Additional Information

![DSC_0183](https://user-images.githubusercontent.com/61541391/75434831-6d0d4d00-5952-11ea-889e-92741f2502e0.JPG)

**Comment by Pixel-Soup** [comment]
To fix the problem, compile the Marlin with long names enabled.
In configuration_adv.h, un-comment this line.
#define LONG_FILENAME_HOST_SUPPORT
The touchscreen firmware has so many bugs which crashes.  Marlin mode is far more dependable.
