### ISSUE TITLE
[BUG] Encoder knob not working 

### ISSUE THREAD

**Issue by 2BWorks** [bigtreetech/BIGTREETECH-TouchScreenFirmware#354]
I have bought TFT 35 E3 version. The encoder knob doesnt work. It does not register when im rotating. What can i do to fix?

**Comment by GeminiServer** [comment]
In simulation mode e.g. with marlin or?

**Comment by 2BWorks** [comment]
It doesn't work at allOn Feb 29, 2020 18:28, Erkan Colak <notifications@github.com> wrote:In simulation mode e.g. with marlin or?

**Comment by fishwhisperer83** [comment]
Has this issue been resolved? I'm having the same issue, doesn't work in marlin simulation or changing between the 2 modes. This has happened with 2 boards, one I replaced because i thought it had a bad sensor. Using a TFT35_E3_V3.0 running TFT35_E3_V3.0.26.x Jun 15 2020

**Comment by oldman4U** [comment]
@2BWorks 

What is the status of the reported issue.

Please close this ticket if you do not need it anymore

Thank you

**Comment by oldman4U** [comment]
@2BWorks 

Close this ticket

**Comment by oldman4U** [comment]
@bigtreetech 

Please close this ticket because a possible reason is described in the ReadMe and the user does not reply anymore.

Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by npmomchev** [comment]
I have the same problem. Works only for choosing between simulation or touch. In Marlin simulation mode does not work

**Comment by npmomchev** [comment]
**Solved**

Detached EXP2 cable.
