### ISSUE TITLE
Unified Menu First Page stays on update to classic TFT 3.5 V3

### ISSUE THREAD

**Issue by jaymcd** [bigtreetech/BIGTREETECH-TouchScreenFirmware#356]
When trying to go back to classic menu after updating to the Unified Menu theme, the first page displayed stays as the Unified Menu. When you click on menu you then get the classic view icons but with the print icon missing ( it is on the first page). For the time being I have gone back to the Unified Menu, but would like to get the classic option eventually.

**Comment by UnderXirox** [comment]
[FR]
bonjour j'ai le meme souci avec le TFT 3.5 E3

[EN]
hello I have the same problem with the TFT 3.5 E3

pardon my English

**Comment by thisiskeithb** [comment]
I’m seeing the same issue on one of my TFT35s.

**Comment by thisiskeithb** [comment]
The "Classic UI" was restored in https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/390, so pull down a fresh copy, compile, & flash again.
