### ISSUE TITLE
[FR] IDEA: use #pragma once

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [bigtreetech/BIGTREETECH-TouchScreenFirmware#358]
@guruathwal

some code cluttering can be reduced by using `#pragma once`
https://en.wikipedia.org/wiki/Pragma_once

for example: [v-user-1/TFT/src/User/API/boot.h](https://github.com/random-builder/bigtree-tft-code/blob/v-user-1/TFT/src/User/API/boot.h)

**Comment by oldman4U** [comment]
Could you please be so kind and close this ticket. Your feature request is covered in the pinned Feature Request ticket #1177 

Thank you
