### ISSUE TITLE
tft 35 v2 with skr v1.4

### ISSUE THREAD

**Issue by Johan-van-dongen** [bigtreetech/BIGTREETECH-TouchScreenFirmware#363]
why couldn't I connect my tft v2 with the skr v1.4 ?

**Comment by CRCinAU** [comment]
I'd ask this on the Facebook group - it probably isn't a software issue / bug...

**Comment by bkzspam** [comment]
Mine is connecting. Check your marlin config and tft's baudrate.

**Comment by MeisterMio** [comment]
I know it's a 1.3 but it did work for me 
https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/issues/60#issuecomment-550077120

**Comment by oldman4U** [comment]
@Johan-van-dongen 

What is the status of this issue.

Please let us know or close this ticket if the problem has been solved in the meantime.

Thank you
