### ISSUE TITLE
[FR] Some sort of auto sleep for touch mode

### ISSUE THREAD

**Issue by ReubenBTalbott** [bigtreetech/BIGTREETECH-TouchScreenFirmware#366]
I don't know if this is possible to do, but could the screen when in touch mode after a set amount of  time turn off the backlight until touched? 
I use a relay to shutdown my printer's main board after printing, but keep the screen powered with a  buck converter, and when I want to print again I can power the mainboard back on with the screen, so when the printer is off the screen is still on and doing nothing.

**Comment by dziabi3** [comment]
Apparently this feature is to be added in the next update. I read it once here.

**Comment by bkzspam** [comment]
I agree, this can be great feature. There's a should be an option called as "Screen auto off time"

**Comment by bigtreetech** [comment]
Hello, it's done in #474, you can download the lastest version firmware to test

**Comment by ReubenBTalbott** [comment]
Awesome!
