### ISSUE TITLE
[BUG] Stuck after cancel the print

### ISSUE THREAD

**Issue by bkzspam** [bigtreetech/BIGTREETECH-TouchScreenFirmware#367]
### Descriptionn

When print some files from the sd card connected to board, if I cancel it screen get stucked in screen that says "Loading..."

### Steps to reproduce

Print, select onboadsd, select the file, stop, confirm, here is the issue.

TFT 35 V2 connected to SKR V1.4 @ Marlin latest build

**Comment by oldman4U** [comment]
What is the status of the reported issue?

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
