### ISSUE TITLE
[BUG] Screen stuck at file browser

### ISSUE THREAD

**Issue by bkzspam** [bigtreetech/BIGTREETECH-TouchScreenFirmware#369]
If I try to browse sd card for selecting a file sometimes screen get stucked with a screen that says: Loading...

Steps to produce it:
Print, TFT SD

**Comment by bigtreetech** [comment]
hello, It sounds like SD card is in poor contact, Please remove the SD card to see if the screen will go to the next interface when the screen is stucked in "loading".
