### ISSUE TITLE
Skr 1.4 with tft35 v3.0

### ISSUE THREAD

**Issue by chronowerxs** [bigtreetech/BIGTREETECH-TouchScreenFirmware#370]
Hi all. I have a bigtreetech v1.4 turbo connected to a tft35 v3.0. The tft35 v3.0 has been updated to the latest version. I have been using marlin mode for a week now. Now suddenly the marlin mode isn't working anymore. I only get a  black screen, when I chose the marlin mode. I havent changed any settings in marlin 2.0. Does anyone have had a similar problem?

**Comment by ReverendS3rvo** [comment]
Did you get a fix? I'm having the same issues.

**Comment by rebel1** [comment]
Switch to Marlin mode and move the encoder a little bit. ;)

**Comment by ReverendS3rvo** [comment]
Yeah, that's what i found. Didnt work.
