### ISSUE TITLE
Hungarian language

### ISSUE THREAD

**Issue by AntoszHUN** [bigtreetech/BIGTREETECH-TouchScreenFirmware#371]
**The problem**
Hi! I use the SKR TFT35 V3.0 display. I have no problem with it. The only problem is that there is no Hungarian language on it. As it contains 11 languages, Hungarian would fit in.

**Solution**
I made the Hungarian language. they could install it in the next update, which would be very good for many Hungarian users.

**Alternative**
Here is the menu system in Hungarian. https://www.youtube.com/watch?v=_sTpq-FcNio

![hun](https://user-images.githubusercontent.com/45710979/76185871-d00fa700-61d0-11ea-9ca6-12dcb6116a37.jpg)

**Comment by Acenotass** [comment]
Hi!
To implement the Hungarian language you need to make a Pull Requests.

**Comment by AntoszHUN** [comment]
All right. :)

Acenotass <notifications@github.com> ezt írta (időpont: 2020. márc. 17., K
10:35):

**Comment by AntoszHUN** [comment]
I can't create a Pull Request. :(

**Comment by AntoszHUN** [comment]
![Új bitkép](https://user-images.githubusercontent.com/45710979/76891035-a0276a00-6888-11ea-922b-99fbe65ad4eb.jpg)

What is it? I can't create a Pull Request. :(

**Comment by Acenotass** [comment]
Please attach all your translate files.
Or do it himself.
https://www.youtube.com/watch?v=8lGpZkjnkt4

**Comment by AntoszHUN** [comment]
Hi!

I uploaded it to Drive. Here is the sharing link. I couldn't compress the folder. This is all firmware because there is not just a language_hu.h file but I have translated everything. There is a (Read_el) file in the folder. I wrote everything down there. If you have any questions, do not hesitate to contact me.

Thanks for the videos. Unfortunately, I don't really understand what they're doing in it. But once we can solve it ...

In any case, I've attached the entire firmware sharing link.

Sincerely!
AntoszHUN

https://drive.google.com/drive/folders/14sPiJP6DvAy8s0EAWiZDwkouchvXqPnu?usp=sharing

**Comment by bigtreetech** [comment]
merged in #424 ， thank you!

**Comment by AntoszHUN** [comment]
Thank you very much!

**Comment by AntoszHUN** [comment]
Is only the language_hu.h file inserted? Or will the others be included? Maybe I can find out which files I have translated?

**Comment by AntoszHUN** [comment]
Hi! English cannot be selected in the display menu. Integration successful?
![90036947_1286228741766278_7559016718677311488_o](https://user-images.githubusercontent.com/45710979/77191888-f0e2d100-6adb-11ea-8519-5a62e2451453.jpg)

**Comment by Acenotass** [comment]
Yes, everything works well, the Hungarian language has appeared.
Download the latest firmware, fonts, and Icons.

**Comment by AntoszHUN** [comment]
All right. Works with minor modifications left out of configuration.h. Please make the following correction!
I supplemented it with HUNGARY.

/ **
  * Default LANGUAGE
  *
  * Select the language to display on the LCD. These languages are available:
  * ENGLISH, CHINESE, RUSSIAN, JAPANESE, ARMENIAN, GERMAN, HUNGARY, CZECH, SPAIN, FRENCH, PORTUGUESE, ITALIAN, POLISH, SLOVAK, DUTCH
  * /

Thank! Sincerely!
Antosz
