### ISSUE TITLE
[BUG] “Classic UI" menu style broken

### ISSUE THREAD

**Issue by thisiskeithb** [bigtreetech/BIGTREETECH-TouchScreenFirmware#372]
### Description

Commenting out `UNIFIED_MENU` (to use "Classic UI" mode) & icons from the non-unified menu folder results in a broken menu as if `UNIFIED_MENU` is still being used.

### Steps to reproduce

1. Use the [config](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/blob/b7d736eeab490563358726870fb945bc8ce49939/TFT/src/User/Configuration.h) from b7d736e, and comment out `UNIFIED_MENU`.

**Expected behavior**
Working Classic UI:
![image](https://user-images.githubusercontent.com/13375512/76322326-7d9dbb80-62a0-11ea-968c-97626ee17438.png)

**Actual behavior**
Broken Classic UI main screen:
![IMG_6080](https://user-images.githubusercontent.com/13375512/76269267-26f79980-622e-11ea-8d32-660977d8e0cc.jpg)

All the sub-menus look fine (here's just one example):
![IMG_6081](https://user-images.githubusercontent.com/13375512/76269271-2eb73e00-622e-11ea-9fa4-29e5d112966b.jpg)
_@guruathwal: It looks like some additional icons need to be copied out of the unified menu icons folder if the temperature feature is intended to be available in both modes._

### Hardware Variant
TFT35 3.0 and TFT35 E3 3.0

### TFT Firmware Version & Main Board Firmware details
b7d736e, TFT_35_V3.0.25.2 Mar 9 2020

**Comment by guruathwal** [comment]
It is the Status Screen. BTT has added the Status Screen to the Classis Menu also. You will have to use the status screen icons from the Unified menu folder.

**Comment by thisiskeithb** [comment]
@bigtreetech Was this intentional? If the classic menu is going away, more cleanup is required.

**Comment by thisiskeithb** [comment]
Closing since PR https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/390 reverted the status screen for "Classic UI".
