### ISSUE TITLE
[BUG] Since new printing screen was implemented, icons are not correctly shown

### ISSUE THREAD

**Issue by javicarrera** [bigtreetech/BIGTREETECH-TouchScreenFirmware#377]
### Description

Since I updated yesterday my TFT24 v1.1 and TFT35 V3.0, the printing screen is a mess, the icons are not properly shown, looks like corrupted data.

### Steps to reproduce

1. Update to newest firmware - Unified style.
2. Print, get to the printing screen.

**Actual behavior**
The icons look corrupted.
It seems all icons starting with the name "printing" and "global" are corrupted.

### Hardware Variant
TFT 24 v1.1 and TFT35 v3.0
### TFT Firmware Version & Main Board Firmware details
25.2 (from yesterday 09/03/2020

**Comment by mikefromups** [comment]
Not knowing your level of expertise, so just a suggestion/comment.  Did you also copy the fonts and icons, included with the update, to your flash drive?  Some updates require new icons or fonts to be reloaded.

**Comment by JWolfJr** [comment]
Thank you for bringing this to my attention @mikefromups. I've been irritated why my icons were messed up and or missing. Just had to reload my folder with the bmp images. So simple, I feel extra dumb! Thank you for posting this.

**Comment by javicarrera** [comment]
Hello thank you all. Reloading the folder with the images didn't solve the problem. I had to compile myself the firmware to make it work, now it works! So I assume it is something wrong with the bin file.
