### ISSUE TITLE
[FR] IDEA: report flash used

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [bigtreetech/BIGTREETECH-TouchScreenFirmware#381]
since `spi flash` is currently a limited resource:
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/364
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/365

then it would make sense to track its usage

code in prototype
[v-user-2/TFT/src/User/API/boot.c](https://github.com/random-builder/bigtree-tft-code/blob/v-user-2/TFT/src/User/API/boot.c)

example boot progress report:

* during font copy

![IMG_20200306_085833](https://user-images.githubusercontent.com/1622151/76430802-bca23e80-637e-11ea-84eb-c7982241825f.jpg)

* during icon copy

![IMG_20200306_085941](https://user-images.githubusercontent.com/1622151/76430803-bd3ad500-637e-11ea-8bf6-080a65174768.jpg)

**Comment by Andrei-Pozolotin** [comment]
also, post-boot report:

*code

[v-user-3/TFT/src/User/Menu/SystemDebug.c](https://github.com/random-builder/bigtree-tft-code/blob/v-user-3/TFT/src/User/Menu/SystemDebug.c#L64)

* report screen

![IMG_20200311_142213](https://user-images.githubusercontent.com/1622151/76455709-f46fad00-63a3-11ea-990d-42c12b7fd138.jpg)

**Comment by thisiskeithb** [comment]
This would be handy for developers 🙂
