### ISSUE TITLE
 [BUG] (TFT35_V3 Extremely long update and booting time)

### ISSUE THREAD

**Issue by dineshvyas** [bigtreetech/BIGTREETECH-TouchScreenFirmware#383]
### Steps to reproduce

1. [First Step] update TFT35V3. it will take 10+ minutes to update after 99%
2. [Second Step] reset it takes 10+ minutes after every reset.
3. [and so on...]

**Expected behavior**

**Actual behavior**

### Additional Information
* Include a ZIP file containing your `Configuration.h` or use [Pastebin](https://pastebin.com/) and paste a link in this issue.
* Provide pictures or links to videos that clearly demonstrate the issue.

video or gif not uploading!

[Capture0](https://user-images.githubusercontent.com/55104840/76445485-7b944380-63eb-11ea-9453-3318098dc6e0.JPG)

[Configuration.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4319789/Configuration.zip)
![20200311_203827_1](https://user-images.githubusercontent.com/55104840/76446313-e2662c80-63ec-11ea-9345-687aa2802371.gif)

**Comment by carl1961** [comment]
No issue with update on mine. 2 minutes max. I installed using sdcard.

**Comment by guruathwal** [comment]
that does not look like a standard update screen. are you using any other modded firmware??

**Comment by dineshvyas** [comment]
accidental uncommented debug msg.
removed and installed latest release.
