### ISSUE TITLE
[Q] Code License

### ISSUE THREAD

**Issue by thisiskeithb** [bigtreetech/BIGTREETECH-TouchScreenFirmware#387]
Which license is this code released under? It would be helpful to add one to this repo.

**Comment by guruathwal** [comment]
looks like an unlicensed code.

**Comment by bigtreetech** [comment]
hello, We added the license in https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/commit/2e83dc384936ae8faa86a4be9bc5b33eaee98728
It's published under the [GPL license](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/blob/master/LICENSE)

**Comment by thisiskeithb** [comment]
Thank you!
