### ISSUE TITLE
[FR] Preview models on Unified Menu

### ISSUE THREAD

**Issue by Bankinghelp** [bigtreetech/BIGTREETECH-TouchScreenFirmware#395]
Hi, would it be possible to add the preview model and view the model while printing with the unified menu? I would really appreciate that feature and will make my printer modern and nice! I know its in the classic menu but I really like the unified one! Thank you for considerating this!
Cheers!

**Comment by guruathwal** [comment]
the feature is already in unified menu... you need to update to the latest firmware

**Comment by Bankinghelp** [comment]
@guruathwal thanks I will check

**Comment by Bankinghelp** [comment]
@guruathwal I seaid it because of this: "Gcode file under unified menu is in list mode, unable to preview the model, but more friendly for long filename"

**Comment by guruathwal** [comment]
@Bankinghelp Unified menu has both Icon mode and List mode:
there is an option to enable icon mode in Feature Settings Menu.

**Comment by Bankinghelp** [comment]
@guruathwal Ok it works, but I can't make the photo to the model. The tool is in Chinese and when I  load the model nothing happens just a Chinese message... what can I do?

**Comment by Bankinghelp** [comment]
@guruathwal do u know how to use it, been 3 days trying with no success Help please.

**Comment by guruathwal** [comment]
you can find the usage instructions here: https://github.com/bigtreetech/BiQU_Tool

**Comment by Bankinghelp** [comment]
@guruathwal yeah I know but still the same issue, it's strange... And still, no way I can change de language...

**Comment by Hukuma1** [comment]
Just take a photo of the model in your favorite slicing program (e.g. Cura) and place that image in same place on SD card where your model is.

**Comment by Bankinghelp** [comment]
With the same name as the model? and which kind of extension (jpg, png, bmp...)?

**Comment by Hukuma1** [comment]
For TFT35 it would be:
benchy_95.bmp (dimensions of file 95x95)
benchy.gcode

**Comment by Hukuma1** [comment]
Did you get it work? If so please close the two issues. :)

**Comment by dp250f** [comment]
It would be nice if there were a Cura plugin which would automatically generate these bmp preview files. The MKS one embeds png files into the G-Code, which doesn't work on BTT screens.

**Comment by oldman4U** [comment]
@Bankinghelp 

Please close this ticket because this is available now. Thank you
