### ISSUE TITLE
Error updating firmware TFT35 V3.0

### ISSUE THREAD

**Issue by leanlibutti** [bigtreetech/BIGTREETECH-TouchScreenFirmware#397]
Hello,

I have a problem that the screen appears as follows after updating the firmware to version 0.25.2: 

![image](https://user-images.githubusercontent.com/14183141/76669842-36e3e600-656c-11ea-9c7b-d5edb1f54520.png)

I would appreciate if you help me to solve this.

Regards, Leandro.

**Comment by Bankinghelp** [comment]
uuum check all cables ar connected properlly and in the right side. and in marlin u have defined ports 0 and -1.

**Comment by leanlibutti** [comment]
with the previous version (0.25) that did not happen. So I think it's not Marlin's problem

**Comment by leanlibutti** [comment]
also do not know why it appears in Chinese if I have it configured with English

**Comment by bigtreetech** [comment]
hello, maybe you need also to update the fonts and icons in [here]( https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/tree/master/Copy%20to%20SD%20Card%20root%20directory%20to%20update%20-%20Unified%20Menu%20Material%20theme/TFT35)

**Comment by leanlibutti** [comment]
that was the problem !! thank you very much for your help

regards
