### ISSUE TITLE
Use the beeper for its intended purpose!

### ISSUE THREAD

**Issue by Aleks-MO** [bigtreetech/BIGTREETECH-TouchScreenFirmware#404]
**Use the beeper for its intended purpose!**
![84460321_201735407811598_7486293520672620544_n](https://user-images.githubusercontent.com/22274265/76682766-6b58b000-6607-11ea-968e-2d88d8530bbf.jpg)
**Start of printing and end of printing I have a beeper on LSD . Can someone write it in the program?**
![212121](https://user-images.githubusercontent.com/22274265/76682861-0f425b80-6608-11ea-97bc-251b05dfc2de.jpg)

**Comment by Msq001** [comment]
OK, Has been added to the my work plan and will be implemented tomorrow

**Comment by Aleks-MO** [comment]
@Msq001  
Put the implementation in the program here.

**Comment by Msq001** [comment]
hello, has be implemented in #415 , you can test it

**Comment by Aleks-MO** [comment]
@Msq001   
Thank you very much, I will check.
