### ISSUE TITLE
[Q] How to use model preview.

### ISSUE THREAD

**Issue by Bankinghelp** [bigtreetech/BIGTREETECH-TouchScreenFirmware#407]
first is in Chinese and there is no way to translate it and secondly, it gives me an error message when uploading gcode and nothing happens. Also, I don't know where to save it (where gcode is or SD card root...). Any help?

**Comment by Bankinghelp** [comment]
Any help, please? Still not working

**Comment by rozenrod** [comment]
You need to choose an STL model. Save the .bmp files (I save them to the desktop), then drop these .bmp files to the memory card (Do not use the biqu_tool generated by gcode)

**Comment by oldman4U** [comment]
Hi.

Today there has been a new method released which allows to get the functionality without bmp directly from Cura export. Please try and close this ticket in case this solves your problem. Thank you

**Comment by bigtreetech** [comment]
Hello, Please refer to [here](https://github.com/bigtreetech/Bigtree3DPlugin)
