### ISSUE TITLE
Changing mode affect the printer 

### ISSUE THREAD

**Issue by spilz87** [bigtreetech/BIGTREETECH-TouchScreenFirmware#41]
The way to change the mode (touchscreen / lcd12864) by holding and turning the rotary encoder is a bad idea : 

Rotary encoder is directly connected to printer, so when we change the mode, we go into menu in printer without knowing it, and sometime that change configuration or something else. 

An other approche could be : 
- touchscreen -> lcd12864 : clic on a specific icon in settings for exemple 
- lcd12864 -> touchscreen : hold a long press on the touchscreen as it’s not used in this mode 

What do you think about that ?

Regards

**Comment by Mistergrow** [comment]
I think this is better:
touchscreen -> lcd : touch Settings / Advanced / switch to LCD
lcd -> touch : Go to settings / Advanced / switch to TFT (with encoder)

**Comment by spilz87** [comment]
I don’t understand the way lcd -> touch : it suppose you add menu in marlin ?
The point for me is to don’t use encoder which is share with marlin

**Comment by Mistergrow** [comment]
Yes, my Idea was Marlin Menu and switch it from there but the unused touchscreen idea from you is a better way.

**Comment by spilz87** [comment]
One of my goals is to don’t touch to marlin

**Comment by guruathwal** [comment]
@spilz87 can you close this issue.. I think the required option have been added.
