### ISSUE TITLE
[FR] IDEA: TFT35 Iconset by Peter Mann and Acenotass

### ISSUE THREAD

**Issue by Acenotass** [bigtreetech/BIGTREETECH-TouchScreenFirmware#412]
I want to share with you a beautiful set of iconset created by Peter Mann. I took its set as a basis and created the missing icons, redrew the existing icons a bit.

![IMG_20200317_142353](https://user-images.githubusercontent.com/44540957/76836686-6db34800-685b-11ea-8849-47dddf39a337.jpg)

![IMG_20200317_032754](https://user-images.githubusercontent.com/44540957/76803728-b855a580-6804-11ea-8b73-310884035039.jpg)

![IMG_20200317_144335](https://user-images.githubusercontent.com/44540957/76838281-34300c00-685e-11ea-94e9-1273c8001976.jpg)

[TFT35 Iconset by Peter Mann and Acenotass.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4342745/TFT35.Iconset.by.Peter.Mann.and.Acenotass.zip)

**Comment by sc44** [comment]
This icon set is really great. I've been using it since this afternoon and think it's great.
Thanks alot

**Comment by Acenotass** [comment]
Thank you, I tried to make everyone enjoy my work.

**Comment by Hukuma1** [comment]
Looks great! Should be listed as an option for people to know it's out there. Do we even have a section listing custom icon packs? Maybe we could add it to the front page readme that @thisiskeithb just recently awesomified?

**Comment by jthomeo** [comment]
This icon set is great. Thanks for sharing. To be perfect, only 4 icons are missing.
e_1_percent, e_5_percent, e_10_percent and screen_info.
I've replaced global_nozzle for a copy of Nozzle and global_bed for a copy of Hotbed and it's better yet.

**Comment by sc44** [comment]
Hello,
updated Version for the Vx.x.26 release. e_1_percent, e_5_percent, e_10_percent.bmp is included.

[TFT35.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4711905/TFT35.zip)

**Comment by jthomeo** [comment]
That's a great addition. Tks!

**Comment by bpivk** [comment]
I have a problem with the first three status icons. They show the default ones. I downloaded and Installed both packs separately and together and same issue.

**Comment by sonny-c** [comment]
What firmware is recommended to flash with this icon pack?  I flashed BIGTREE_TFT35_V3.0_E3.26.1.bin and over 50+ icon failed to load.

**Comment by jthomeo** [comment]
@sonny-c, I've corrected all file names in mine. Try this one.
[TFT35.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4789839/TFT35.zip)

**Comment by sonny-c** [comment]
> @bpivk and @sonny-c, I've corrected all file names in mine. Try this one.
> [TFT35.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4789839/TFT35.zip)

Thank you!

**Comment by DrumClock** [comment]
Hi @Acenotass 
do you have icone also for model TFT 5 V3.0?
There is another dimension of bmp.

Thanks
