### ISSUE TITLE
[BUG] Parameter Settings Incorrectly Displays Estep Value after Change

### ISSUE THREAD

**Issue by FSUwelder1212** [bigtreetech/BIGTREETECH-TouchScreenFirmware#420]
### Description

Parameter Settings Display, Esteps menu only displays whole number (no decimal value) after change.

### Steps to reproduce

If I change my Estep value from current 80.0 to new 79.3 the value will only display as 79.0 until I back out of the Esteps menu and re-enter the E steps menu then it will display the correct value (79.3 in this example)

**Expected behavior**
Estep value should display entire value after change

**Actual behavior**
new Estep value appears to truncate the decimal value

### Hardware Variant
TFT35 E3 V3,0 Display

SKR Mini E3 V1.2 Mainboard

### TFT Firmware Version & Main Board Firmware details
TFT Firmware version:   BIGTREE_TFT35_V3.0.25.2

Mainboard Firmware:  most recent vanilla Marlin 2.0 Bugfix

**Comment by bigtreetech** [comment]
It should be fixed in lastest version， so close here
