### ISSUE TITLE
[Q] (Your Question?)bigtreetech tft35 v2.0

### ISSUE THREAD

**Issue by Hxspider** [bigtreetech/BIGTREETECH-TouchScreenFirmware#423]
**hi.
 I am trying to update my bigtreetech tft35 v2.0 to version .25 an it succeeds,  kind of...it loads and apparently updates but the icons aren't showing correctly. 
They are only blank.
I tried the .24 update as well and then I got one Icon, the print icon showed correctly. 
What is wrong?* 

**bigtreetech tft35 v2.0**

**
![20200320_011052](https://user-images.githubusercontent.com/62303233/77126512-9bf67a80-6a49-11ea-9508-d4d99d2f72f4.jpg)
**

**Comment by thisiskeithb** [comment]
Did you follow the [Update TFT Firmware](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/blob/master/README.md#update-tft-firmware) section in the readme?

**Comment by Hxspider** [comment]
Oh…never mind..works fine now…

Fra: thisiskeithb <notifications@github.com>
Sendt: fredag 20. mars 2020 02:06
Til: bigtreetech/BIGTREETECH-TouchScreenFirmware <BIGTREETECH-TouchScreenFirmware@noreply.github.com>
Kopi: Hxspider <fjellvang@hotmail.com>; Author <author@noreply.github.com>
Emne: Re: [bigtreetech/BIGTREETECH-TouchScreenFirmware] [Q] (Your Question?)bigtreetech tft35 v2.0 (#423)


Did you follow the Update TFT Firmware<https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/blob/master/README.md#update-tft-firmware> section in the readme?

**Comment by Hxspider** [comment]
Except the print screen icons are distorted..



Sendt fra min Samsung Galaxy-smarttelefon.



-------- Opprinnelig melding --------
Fra: thisiskeithb <notifications@github.com>
Dato: 20.03.2020 02:06 (GMT+01:00)
Til: bigtreetech/BIGTREETECH-TouchScreenFirmware <BIGTREETECH-TouchScreenFirmware@noreply.github.com>
Ko: Hxspider <fjellvang@hotmail.com>, Author <author@noreply.github.com>
Emne: Re: [bigtreetech/BIGTREETECH-TouchScreenFirmware] [Q] (Your Question?)bigtreetech tft35 v2.0 (#423)


Did you follow the Update TFT Firmware<https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/blob/master/README.md#update-tft-firmware> section in the readme?

**Comment by Kyosuke33** [comment]
I have a similar problem, i try to upload new. 25.2 firmware on my TFT35 V3, it load great but after that i have weird icône. With the .24 i have the problem only on the surveillance screen, the menu is good.
![IMG_20200320_105111](https://user-images.githubusercontent.com/44751932/77183652-f5ed5380-6ace-11ea-8b43-f0dcc9c16fb1.jpg)
![IMG_20200320_105146](https://user-images.githubusercontent.com/44751932/77183684-03a2d900-6acf-11ea-842c-6795f41fa4c3.jpg)

**Comment by Hxspider** [comment]
Anyone? 
My print icons are still distorted...

![20200320_105923](https://user-images.githubusercontent.com/62303233/77255614-0802f980-6c69-11ea-8ec6-ce566589e711.jpg)

**Comment by Kyosuke33** [comment]
Same problem for me, i have to use Acetonass icon to make it work. https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/428

**Comment by Clowntrigger** [comment]
See my response to [Issue 430](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/430#issuecomment-604664793).

**Comment by oldman4U** [comment]
@Hxspider 

Please close this unused old ticket

Thank you
