### ISSUE TITLE
SKR1.3 + TFT35 v2.0 + WiFi

### ISSUE THREAD

**Issue by grego1981** [bigtreetech/BIGTREETECH-TouchScreenFirmware#43]
Hi,

I have received my order of an SKR 1.3 with 2209 v1.3 drivers along with a TFT v2.0 and a WiFi expansion from Aliexpress. I'm searching through the repository and internet in general to find some instructions as to make this combination functional, especially for the screen and the WiFi interface. Can someone help me or point me to the right direction?

Thank and best regards.

Gregoris

**Comment by Mistergrow** [comment]
Wifi is currently not implemented yet. Bigtree Member said they will publish new source (or Wifi Firmware) Tuesday or Wednesday. (10 or 11.09.2019).

**Comment by grego1981** [comment]
So it is going to be implemented on this release (If you have the inside info that is)?

**Comment by Mistergrow** [comment]
Look here: 
https://github.com/bigtreetech/BIGTREETECH-TFT35-V3.0/issues/2#issuecomment-529096010

**Comment by grego1981** [comment]
Let's hope it will! The screen has a lot of potential if it can be used to its full extent!

**Comment by bigtreetech** [comment]
we will implement it this week. ^_^

**Comment by sergeyfk05** [comment]
@bigtreetech , are you implement it(WiFi support) yet?

**Comment by grego1981** [comment]
No news still, please give a timeframe. Thank you
