### ISSUE TITLE
Bug screen update 25.2

### ISSUE THREAD

**Issue by Kyosuke33** [bigtreetech/BIGTREETECH-TouchScreenFirmware#430]
Hello, i receive my TFT35 v3 yesterday, and when i try to update it to the 25.2 firmware (i put 25.2 firmware and Tft folder with bump and fonts on my sdcard), the update work great but my screen icône are weird. When i try with the 24.2 firmware, the same thing happen but only on the surveillance screen, the menu screen work great. Thank you. 
![IMG_20200320_105111](https://user-images.githubusercontent.com/44751932/77184396-123dc000-6ad0-11ea-94b4-f3eabc3dde39.jpg)
![IMG_20200320_105146](https://user-images.githubusercontent.com/44751932/77184407-179b0a80-6ad0-11ea-8201-cdfa3d8e471c.jpg)
![IMG_20200320_105055](https://user-images.githubusercontent.com/44751932/77184446-284b8080-6ad0-11ea-9a31-894034cb3e5c.jpg)

**Comment by Kyosuke33** [comment]
MAJ, it work with the pack of icon by Acenotass, but not with the classic icon.

**Comment by guruathwal** [comment]
@Kyosuke33 you need to update both fonts and icons from unified theme folder

**Comment by Kyosuke33** [comment]
I try the Classic Firmware 25.2 with the TFT35 Folder (bump/fonts) and I try the Unified Firmware 25.2 with the TFT35 Folder (bump/fonts) but both won't work.
I try both Classic and Unified firmware with the TFT35 Folder (only fonts) and the bumps folder from Acenotass and it work.
Weird^^

**Comment by guruathwal** [comment]
you need to copy the full TFT35 folder to your SD card. after copying it should look like this:
if your SD card is on F drive:
the BMP folder F:\TFT35\bmp
the font folder F:\TFT35\font
make sure you reformat your sdcard to fat32

**Comment by Kyosuke33** [comment]
My sd card is fat32 and i do that for the folder, but won't work until i change the bump folder by the one of Acetonass.

**Comment by Kyosuke33** [comment]
The sd card
![IMG_20200320_204718](https://user-images.githubusercontent.com/44751932/77201030-0cee6e80-6aec-11ea-9651-79d96ab609b5.jpg)
Inside the tft35 folder
![IMG_20200320_204729](https://user-images.githubusercontent.com/44751932/77201054-1a0b5d80-6aec-11ea-8cab-4e3421f0546a.jpg)

**Comment by dziabi3** [comment]
I have the same problem but when I use the bin file the problem disappears.

**Comment by jmdog98** [comment]
bump because I have the same exact problem

**Comment by guruathwal** [comment]
@Kyosuke33 Did you compiled the firmware or used the precompiled bin file?

**Comment by jmdog98** [comment]
@guruathwal I'm on the precompiled bin. using Acetonass icons also as a fix for now

**Comment by guruathwal** [comment]
some time the Firmware does not update the BMP files on reset. This is because of bad SD card formatting or a currupted file on SDcard. Try full formatting the card to both FAT and FAT32. and try resetting the screen again a few times if it does not update the icons.

**Comment by jmdog98** [comment]
I'm currently in a print that is finishing soon but after I'll try what you suggested, but when updating I can still see the icons being flashed over but it looks as if its trying to force the unified menu. by reset do you mean pressing the reset directly on the screen or power cycling the whole printer?

**Comment by guruathwal** [comment]
you can see the original unified menu icon being updated or not?
What do mean by:
> its trying to force the unified menu.

Are you not using the unified menu BIN file?
yes, by reset I mean just pressing the reset button on the screen.

**Comment by jmdog98** [comment]
What I ment was that when I updated it using the classic files it looks like a messed up version of the unified theme (because it shows the xyz coordinates down the center like the unified theme does) not the classic almost as if it was thinking it was suppose to load the unified theme.

**Comment by guruathwal** [comment]
@jmdog98 It is not messed up. BigTreeTech added the status screen to the classic menu also. it was in the recent update that they removed the status screen from the classic menu. The precompiled BIN files are not yet updated with the change.
for the current precompiled BIN files for the classic menu, you need to use the unified menu icons also.

**Comment by jmdog98** [comment]
I just reread your first comment where you stated to do that and realized I misread it the first time and I'm assuming that is probably what it is. My print has 5 minutes left so Ill be doing that next. I appreciate the help

**Comment by Kyosuke33** [comment]
I'm not a spécialist, don't know what kind i used xD I just put on the SD card the files i show you below. Try Classic and Unified, on two différents SD Card, but not working until i change the bmp folder by the Acetonass folder.
![Sans titre](https://user-images.githubusercontent.com/44751932/77224538-1668ec80-6b67-11ea-88e0-a1e608f82923.png)

**Comment by jmdog98** [comment]
@Kyosuke33 You have to use the bmp files that are for the unified theme when trying to use classic because of a layout change with the newest update so instead of using Acetonass icons just copy in the icons from the unified theme files

**Comment by Kyosuke33** [comment]
Ok, i only try Classic firmware with classic bmp and Unified firmware with unified bmp. I did not try to mix both. I try that later, for the moment i keep the Acetonass because i like the screen xD

**Comment by Clowntrigger** [comment]
I ran into the same issue with the Unified Menu icons.

Looking at [https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/blob/master/readme/English/How%20to%20custom%20icon%202019-11-11.pdf] there is a hard coded list of icons. I was able to rename onboad_sd.bmp to OnBoardSD.bmp and the icon would show up. I pulled the repository down and the boot.c file does not have the hardcoded list, it scans the directory for a list found in icon_list.inc. The file icon_list.inc has the correct bmp listed as ONBOARD_SD. Compiling this firmware and installing with the TFT35 directory from the repository restored my icons. 

So, there is a disconnect with the compiled firmware at [https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/blob/master/Copy%20to%20SD%20Card%20root%20directory%20to%20update/BIGTREE_TFT35_V3.0.25.2.bin] and the expected filenames in the bmp directory.

**Comment by reQu1em00** [comment]
> I ran into the same issue with the Unified Menu icons.
> Looking at How to custom icon 2019-11-11.pdf there is a hard coded list of icons. I was able to rename onboad_sd.bmp to OnBoardSD.bmp and the icon would show up. I pulled the repository down and the boot.c file does not have the hardcoded list, it scans the directory for a list found in icon_list.inc. The file icon_list.inc has the correct bmp listed as ONBOARD_SD. Compiling this firmware and installing with the TFT35 directory from the repository restored my icons.
> So, there is a disconnect with the compiled firmware at Copy to SD Card root directory to update - Unified Menu Material theme and the expected filenames in the bmp directory.
> edit: sorry, i have no idea how to insert correct links/urls. *Figured it out.

This worked for me.  The BMP have been updated but a new version of the firmware has not been uploaded.  If you compile the firmware yourself from the source files it creates BIGTREE_TFT35_V3.0.25.3.bin which then works.

**Comment by cyberaxcess** [comment]
Compiling and using the BIGTREE_TFT35_V3.0.25.3.bin fixed this problem for me.

**Comment by oldman4U** [comment]
Hi.

Please close this old unused ticket

Thank you

**Comment by oldman4U** [comment]
@Kyosuke33 

Close this ticket

**Comment by oldman4U** [comment]
@bigtreetech 

Please close this ticket

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by Kyosuke33** [comment]
Sorry i forget
