### ISSUE TITLE
Add TPU preheat

### ISSUE THREAD

**Issue by Wallaal06** [bigtreetech/BIGTREETECH-TouchScreenFirmware#431]
I have added a TPU preheat button to the preheat menu. Looking at all the other preheat buttons, I have everything set up right but when I click on it, it does nothing.

**Comment by carl1961** [comment]
Wallaal06 I'm trying to learn this too, I think there or other files also that tie too.  Like PreheatMenu.o   How do you edit that?

**Comment by Wallaal06** [comment]
I don't know... I can't even get the file to open right.

**Comment by carl1961** [comment]
I found out the PreheatMenu.o or files that where compiled by platformio, so there not from the source files.

**Comment by Wallaal06** [comment]
Can i get some help on adding another preheat button to the preheat menu. I copied all the settings i could find from the ABS button but when I click on the TPU button it does nothing.

**Comment by bigtreetech** [comment]
The Preheat menu can be configured by config.ini  file, and added TPU button in Preheat menu. so close here,
