### ISSUE TITLE
Additional settings in parameters menu?

### ISSUE THREAD

**Issue by FSUwelder1212** [bigtreetech/BIGTREETECH-TouchScreenFirmware#432]
Would it be possible to add additional items to the parameters menu? Specifically Jerk and Acceleration. I tried to do this on my own and got everything added but my values  all keep showing 0. I program industrial equipment so I have little to no knowledge of C language and am at a dead end. I think this could be a useful addition for a number of users.

**Comment by guruathwal** [comment]
work in progress..👍
