### ISSUE TITLE
Set up baby stepping on TFT35 V2

### ISSUE THREAD

**Issue by Zuru1** [bigtreetech/BIGTREETECH-TouchScreenFirmware#45]
Hi,

How do I setup baby stepping on TFT35 V2?
Also how do I enable 12864 mode?

PS: I'm using this display with skr v1.3.

Thank you.

**Comment by MangaValk** [comment]
12864 only works on tft35 v3.0
Baby stepping can be used when printing from the tft

**Comment by vMeph** [comment]
would love to see babysteps option for the unified menu version grrr....

**Comment by Interplain** [comment]
I used this to setup Baby Step on TFT35 V2.0 in Unified mode. Hope it helps
https://youtu.be/iwhbeD2AduA
