### ISSUE TITLE
[FR] IDEA:  External Configuration.h File

### ISSUE THREAD

**Issue by Acenotass** [bigtreetech/BIGTREETECH-TouchScreenFirmware#470]
Communication on Facebook for many users is very difficult to independently assemble the firmware. I suggest the configuration.h configuration file be removed outside the firmware.

**Comment by thisiskeithb** [comment]
How would you compile firmware if it was moved?

It’s easy enough to link/reference directly: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/blob/master/TFT/src/User/Configuration.h

**Comment by Acenotass** [comment]
Use all configuration values ​​from EEProm

**Comment by thisiskeithb** [comment]
I see. Is this request different than https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/360?

**Comment by Acenotass** [comment]
Sounds like the same idea.

**Comment by thisiskeithb** [comment]
Since it's a duplicate request, mind closing & discussing in #360?
