### ISSUE TITLE
[Q] Icon pack for a for tough times?

### ISSUE THREAD

**Issue by kkaleta** [bigtreetech/BIGTREETECH-TouchScreenFirmware#476]
I wonder how you find my sense of humor. 
I've made a `virus` theme for a TFT35 family. 

![](https://theveel.com/wp-content/uploads/2020/03/20200318_215143-scaled-e1584567759284.jpg)
![](https://theveel.com/wp-content/uploads/2020/03/theveelCom_20200328_125253.jpg)

[repo](https://github.com/kkaleta/-stayTheFuckHome-Icon-Pack-for-BIQU-TFT)

**Comment by Hans007a** [comment]
nice, post it here :)

**Comment by Acenotass** [comment]
https://github.com/kkaleta/-stayTheFuckHome-Icon-Pack-for-BIQU-TFT

**Comment by guruathwal** [comment]
You forgot to add Mask. btw I like the green color.

**Comment by kkaleta** [comment]
That green its actually yellow :) I wanted something happy, optimistic. That's why I choose those colours.
