### ISSUE TITLE
What,s the difference bewteen  driver of tft 35[Q] (Your Question?)

### ISSUE THREAD

**Issue by kingontheroad** [bigtreetech/BIGTREETECH-TouchScreenFirmware#490]
I have a tft35 e3 v3 when i do std firmware flash i get the 3.0 fw or the 3.0 e3 version ?

If i compile the fw i (can) choose for  E3 3.0 fw the issue what i have and haven,t a find fix for it is.
When i turn off my ender 3 , and the next day want to print he,s forgotten everything all settings !

Very annouing , how can i fix his memory ?

**Comment by bigtreetech** [comment]
hello, TFT35 E3 V3.0 has a neopixel RGB in TFT board, TFT35 V3.0 has not, this is the only difference between TFT35 E3 V3.0 and TFT35 V3.0.

https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/blob/5002284c5453d2826c123754be0cf0c235c3edba/TFT/src/User/API/flashStore.c#L6
here will be modified  If a new setting function is added to the screen to reset the settings area, so this may be why you lost your settings
