### ISSUE TITLE
TFT35 V3.0 Bad assignment motherboard.

### ISSUE THREAD

**Issue by AntoszHUN** [bigtreetech/BIGTREETECH-TouchScreenFirmware#491]
Description of the problem.

The problem is with the TFT35 V3.0 display. As far as I know, this display has a STM32F207VC chip. However, the firmware uses the STM32F103VC chip translation. That's not good, I think. I'll tell you why.

- STM32F103VC: 72 MHz maximum frequency, up to 64 Kbytes of SRAM, 256 Kbytes of Flash memory

in contrast, the STM32F207VC is better.

- STM32F207VC: 120 MHz maximum frequency, Up to 128 + 4 Kbytes of SRAM, Up to 1 Mbytes of Flash memory

Is it possible to fix this? The display would probably work more reliably, accurately, and faster.

Look forward to your answers!

Sincerely!
AntoszHUN

![STM](https://user-images.githubusercontent.com/45710979/78053309-b3563180-7380-11ea-8f55-0e124a1a67d1.jpg)

![bot](https://user-images.githubusercontent.com/45710979/78054420-55c2e480-7382-11ea-85eb-56bfbe8a5f5c.jpg)

**Comment by thisiskeithb** [comment]
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/355 Has more info on this.

**Comment by AntoszHUN** [comment]
Ohh thank you!
