### ISSUE TITLE
[BUG]Compiling actual version rotates display but not the input! TFT 2.4

### ISSUE THREAD

**Issue by arminth** [bigtreetech/BIGTREETECH-TouchScreenFirmware#493]
### Description

Compiling the latest version, after updating the firmware the display rotates 180°, then updates the icons, then starts with display still rotated 180°. Inputs on the other hand are not matching. Looks like inputs are unrotated as they were before and only display is rotated.
### Steps to reproduce

1. Compile latest Firmware for 2.4" version
2. Update
3. Don't enjoy!

**Expected behavior**
No rotated display!

**Actual behavior**
Rotated display, unrotated input.

**Workaround**

in /src/user/Variants/pin_TFT24_V1_1.h flip the values in line 25 and 26 to

```
  #define TFTLCD_0_DEGREE_REG_VALUE   0X68
  #define TFTLCD_180_DEGREE_REG_VALUE 0XA8
```

### Hardware Variant
TFT 2.4" 1.1
### TFT Firmware Version & Main Board Firmware details
1.35.3  Mar 31. 2020
Marlin bugfix 2.0.x Mar 28. 2020
BTT SKR Pro 1.1

**Comment by bigtreetech** [comment]
fixed in #495, very thanks for your feedback !
