### ISSUE TITLE
[BUG] Broken fonts & discolored icons after #489

### ISSUE THREAD

**Issue by thisiskeithb** [bigtreetech/BIGTREETECH-TouchScreenFirmware#497]
### Description

#489 breaks fonts & icons are discolored on the TFT35 V3 & E3 (and possibly others, but this is all I can test with)

### Steps to reproduce

1. Update TFT35 V3 / E3 to 4e6d6f101ad5c9a34c4a6e8bcf01d18c99996408 or newer.
2. Observe broken fonts & discolored icons

**Expected behavior**
Non-broken fonts & icons:
![image](https://user-images.githubusercontent.com/13375512/78103362-a3027e80-73a1-11ea-9736-9f71e4aa8e2f.png)

**Actual behavior**
Fonts are broken & icons are discolored:
![image](https://user-images.githubusercontent.com/13375512/78103506-02608e80-73a2-11ea-97c8-75fc466c030d.png)

### Hardware Variant
TFT35 V3 & E3

### TFT Firmware Version & Main Board Firmware details
25.3, self-compiled with default settings

I know the usual culprit of similar issues are due to not updating fonts & icons, but I did that just in case despite those not changing in a while and it didn't fix the issue.

**Comment by Acenotass** [comment]
Also on my screen TFT3.5 v1.2

**Comment by thisiskeithb** [comment]
Fixed in https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/502.
