### ISSUE TITLE
Another mistake!

### ISSUE THREAD

**Issue by AntoszHUN** [bigtreetech/BIGTREETECH-TouchScreenFirmware#504]
During my continuous analysis, another error occurred. I just downloaded the firmware from here and after build and update the display. I see this after installation. Anyone else do something wrong again?

![IMG_20200401_103035449](https://user-images.githubusercontent.com/45710979/78117177-9d3e8480-7405-11ea-9cc5-4313cad345bb.jpg)

**Comment by thisiskeithb** [comment]
Dupe of https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/497 and it was fixed in https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/502.

**Comment by AntoszHUN** [comment]
Thanks. Then close it.

**Comment by thisiskeithb** [comment]
I can't close issues, but thank you for closing this one 🙂
