### ISSUE TITLE
[BUG] Z-Offset shows 0.00

### ISSUE THREAD

**Issue by Hans007a** [bigtreetech/BIGTREETECH-TouchScreenFirmware#507]
Hello,

in TFT Mode the Z-offset setting is shown a wrong value, it shows 0.00
In Marlin Mode the value is correct (I know Marlin mode has nothing to do with TFT Mode)

### Steps to reproduce

1. go into z-offset menu and look
2. do reset
3. go into z-offset menu and look again

**Expected behavior**
shown the right z-offset value

**Actual behavior**
shows 0,00

### Hardware Variant
TFT35 v3.0 with the last firmware, BTT SKR Pro v1.1 with the last Marlin bugfix

Regards

Hans

**Comment by kingontheroad** [comment]
I had that yesterday, tested them all yesterday. And the fw of last March 12 still works best and also remember;)
fw 25.2 in the firmware archive folder

**Comment by Hans007a** [comment]
I don't use the compiled images

**Comment by kingontheroad** [comment]
the 25.2 that i mention is original and not compiled

**Comment by bigtreetech** [comment]
hello, have fixed in #516

**Comment by Hans007a** [comment]
Thank You! :-)
