### ISSUE TITLE
when entering new values in the Z offset the full value is not displayed.  If the value is 7.3, the displayed value is .3[BUG] (short description)

### ISSUE THREAD

**Issue by 6988isgr8** [bigtreetech/BIGTREETECH-TouchScreenFirmware#508]
### Steps to reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior**

**Actual behavior**

### Additional Information
* Include a ZIP file containing your `Configuration.h` or use [Pastebin](https://pastebin.com/) and paste a link in this issue.
* Provide pictures or links to videos that clearly demonstrate the issue.

**Comment by Interplain** [comment]
I have also found this to be the case. An it also doesn't let you put input the minus sign before the number. You have to put a number in first and delete the number and the minus will enter.

**Comment by oldman4U** [comment]
This should work using a recent firmware

Please close this ticket
