### ISSUE TITLE
Illuminated button no longer works after recompiling with new files?

### ISSUE THREAD

**Issue by BelSD** [bigtreetech/BIGTREETECH-TouchScreenFirmware#512]
Good evening,
When I compile with the latest files, I no longer have the option to light the command button. in the Option menu there is no longer the possibility to choose this color and actually turn it on.
Is this normal?

**Comment by thisiskeithb** [comment]
Are you using `default_envs = BIGTREE_TFT35_E3_V3_0` in [`platformio.ini`](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/blob/master/platformio.ini)?

**Comment by BelSD** [comment]
Ok I was wrong, thank you!
But now I have these 2 messages during compilation ...
![Capture1](https://user-images.githubusercontent.com/45131244/78209806-5d7ca900-74a8-11ea-9a0b-fd6cce1a3027.PNG)
![Capture2](https://user-images.githubusercontent.com/45131244/78209807-5e153f80-74a8-11ea-9576-fe4b4323a3cd.PNG)

**Comment by thisiskeithb** [comment]
Those are just warnings and can be ignored. As long as you see the "SUCCESS" message, your build completed fine:

```prolog
==================== [SUCCESS] Took 2.42 seconds ====================

Environment            Status    Duration
---------------------  --------  ------------
BIGTREE_TFT35_V1_0     IGNORED
BIGTREE_TFT35_V1_1     IGNORED
BIGTREE_TFT35_V1_2     IGNORED
BIGTREE_TFT35_V2_0     IGNORED
BIGTREE_TFT35_V3_0     IGNORED
BIGTREE_TFT35_E3_V3_0  SUCCESS   00:00:02.416
BIGTREE_TFT28_V1_0     IGNORED
BIGTREE_TFT28_V3_0     IGNORED
BIGTREE_TFT24_V1_1     IGNORED
MKS_32_V1_4            IGNORED
MKS_32_V1_4_NOBL       IGNORED
==================== 1 succeeded in 00:00:02.416 ====================

Terminal will be reused by tasks, press any key to close it.
```

**Comment by BelSD** [comment]
Thanks for your help, it works now ...
