### ISSUE TITLE
switching mode desable com port receiver

### ISSUE THREAD

**Issue by spilz87** [bigtreetech/BIGTREETECH-TouchScreenFirmware#54]
tested on : 
TFT35 V3.0.23
TFT35 V3.0.21

to reproduce : 
- start in TFT mode
- go to temperature menu
- change hotend's temperature
- check you see temperature increase
 -> TFT serial com port receiver works well
- switch to LCD12864 mode
- change bed's temperature 
- switch back to TFT mode
- go to temperature menu
- températures don't change
 -> TFT serial com port receiver doesn't work anymore

do you have the same issue ?

**Comment by spilz87** [comment]
Sending data from TFT to Printer seems to work

**Comment by spilz87** [comment]
After tests, I think : 
in file "Mode.c"
in function void Serial_ReSourceInit(void)

> Serial_DMAReEnable(SERIAL_PORT);

 is missing

so when go back to TFT mode, in 

> void USART_IRQHandler(uint8_t port)

dma_mem_buf is no more feeled, so 

> infoHost.rx_ok[port]

 never become TRUE again, and void 

> parseACK(void)

 does nothing.

Do I understand well @bigtreetech ?

**Comment by guruathwal** [comment]
@spilz87 can you close the issue if it was solved?
