### ISSUE TITLE
[BUG] TFT not reading filmament detector when connected to SKR

### ISSUE THREAD

**Issue by planecrazy29** [bigtreetech/BIGTREETECH-TouchScreenFirmware#540]
With the Smart filament detector connected to the SKR it will work in Marlin mode but not touch screen mode.
With the 12v UPS connected to the SKR it will work in Marlin mode but not touch screen mode.  Is there a way to get the screen to read these pin states?

### Steps to reproduce

1. Print something
2. Run out of filament
3. Works in Marlin mode but not in Touch Screen mode

**Expected behavior**

**Actual behavior**

### Hardware Variant
TFT35 v3.0
### TFT Firmware Version & Main Board Firmware details
TFT FWV 1.2.25.2
SKR 1.4 turbo
Marlin 2.1.5.2

**Comment by bigtreetech** [comment]
hello,
 * you need connect Smart Filament Sendor to TFT "FIL_DET" port not SKR board if you print from TFT SD in touch mode, according to here https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/312#issuecomment-609520483
* 12v UPS: you need only insert in SKR board and it will raise z axis when power failed,  TFT will always save the printed data in real time

**Comment by oldman4U** [comment]
Please try the following:

Send M75 to Marlin when print begins. Marlin doesn't know that the print is started so no filament runout warnings. It's not a bug.
You can put M75 in your Start-Gcode and you're set. That's what I did.
