### ISSUE TITLE
[Q] RGB <> BGR on TFT24

### ISSUE THREAD

**Issue by dchauran** [bigtreetech/BIGTREETECH-TouchScreenFirmware#541]
Hello - I am changing to a different screen on my tft24 board, and everything works, except that red and blue are inverted. Looking at the code and the data sheet for ILI9341, it seems like I need to change the value of register 0x36, however no matter what I put in for the data value for 0x36 nothing changes.

I'm looking at line 274 of LCD_init.c and the relevant section from the datasheet is attached.

Any idea what I should change to switch between RGB and BGR?

![image](https://user-images.githubusercontent.com/17055079/78620781-c3b15500-7835-11ea-9d2d-cdd86536265b.png)

**Comment by bigtreetech** [comment]
Hello, try to change the value of register 0x36 in here https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/blob/cff1164003c26deabbf1d747a2ec354a21e3b671/TFT/src/User/Hal/LCD_Init.c#L531
here will refresh the value of registe  0x36 that has setted in `void LCD_init_RGB(void)`

**Comment by dchauran** [comment]
Thank you! I missed that one. It's working perfectly now.
