### ISSUE TITLE
Cannot change Marlin Mode text and background color

### ISSUE THREAD

**Issue by blair9095** [bigtreetech/BIGTREETECH-TouchScreenFirmware#546]
I am unable to change the background or text color when in the Marlin Mode.  I have changed the color of the touch screen (in firmware) but the desired changes to the Marlin screen  don't work

**Comment by blair9095** [comment]
Clarification:  all changes made to latest firmware using latest version of BIGTREETECH-TouchScreenFirmware-master downloaded on 4/7.

**Comment by bigtreetech** [comment]
Hello, Which TFT do you use? I just tested and it works normally. The last two button in the "Settings - > Screen" menu is the background color and font color in Marlin(LCD 12864) mode

**Comment by blair9095** [comment]
I can change the Marlin colors using 
Touch>Menu>Setting>Screen>Foreground or Background
#define ST7920_BKCOLOR GRAY
#define ST7920_FNCOLOR BLACK
but it still comes up Black on Yellow.
