### ISSUE TITLE
[FR] Calling the M48 command from the menu

### ISSUE THREAD

**Issue by radek8** [bigtreetech/BIGTREETECH-TouchScreenFirmware#549]
Hello,
When calling M48, the message - first homing XYZ is displayed.
Solution:
add another line with the G28 command to the "leveling.c" file before the M48 command G28.

For example:
case KEY_ICON_4:
   storeCmd ("G28 \ n");
   storeCmd ("M48 \ n");
break;

![M48](https://user-images.githubusercontent.com/46979052/78826413-bcc74580-79e1-11ea-8874-b8eb4c9ac974.JPG)

**Comment by thisiskeithb** [comment]
Thanks for the report!

See the fix in https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/553.
