### ISSUE TITLE
[FR] Added command M420 T0 V1

### ISSUE THREAD

**Issue by radek8** [bigtreetech/BIGTREETECH-TouchScreenFirmware#551]
Please complete command M420 T0 V1
For example, under an empty button in a terminal

See picture
![SendGcode c1](https://user-images.githubusercontent.com/46979052/78834948-a58f5480-79ef-11ea-9b0d-23f9d2ab8928.JPG)
![SendGcode c2](https://user-images.githubusercontent.com/46979052/78834954-a7f1ae80-79ef-11ea-8eea-03ceba83276b.JPG)
![SendGcode h](https://user-images.githubusercontent.com/46979052/78834962-a9bb7200-79ef-11ea-9d33-7755eb91f245.JPG)
[SendGcode.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4452888/SendGcode.zip)
![IMG_20200408_232214_resized_20200408_112254305](https://user-images.githubusercontent.com/46979052/78835146-f606b200-79ef-11ea-8978-4b906cf96de9.jpg)
![IMG_20200408_232222_resized_20200408_112254116](https://user-images.githubusercontent.com/46979052/78835154-f737df00-79ef-11ea-8c05-ed9371663541.jpg)

**Comment by guruathwal** [comment]
These types of g-code are added in custom g-codes menu.

**Comment by radek8** [comment]
does not appear in custom G-codes
full screen, only last line
