### ISSUE TITLE
[BUG]  extruder parameters do not display correctly

### ISSUE THREAD

**Issue by radek8** [bigtreetech/BIGTREETECH-TouchScreenFirmware#556]
Some extruder parameters do not display correctly - Steps per mm, Max Acceleration, Max Feed Rate.
When displayed in Marlin mode, the values are OK

My configuration
Bigtreetech TFT35 E V3.0.25.3
Bigtreetech SKR 1.4 - Marlin 2.0.5.2 - 2x extruder

![IMG_20200409_214900_resized_20200409_095034678](https://user-images.githubusercontent.com/46979052/78937928-94a71780-7ab1-11ea-81c7-0ef38ce8e9ea.jpg)
![IMG_20200409_214915_resized_20200409_095034520](https://user-images.githubusercontent.com/46979052/78937954-a092d980-7ab1-11ea-82fe-d351c7cf467c.jpg)
![IMG_20200409_214927_resized_20200409_095034255](https://user-images.githubusercontent.com/46979052/78937957-a1c40680-7ab1-11ea-9850-6f042ecf7f0b.jpg)

**Comment by radek8** [comment]
I found out where the problem is.
The FW displays do not load parameters if 2 Extruders are defined.
I suggest editing the ParseACK.c file.
please check and process.

Files:
[parseACK.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4465203/parseACK.zip)

preview edit

![step](https://user-images.githubusercontent.com/46979052/79052519-550a3800-7c37-11ea-910a-feaafe9b6e39.JPG)
![MaxFedRate](https://user-images.githubusercontent.com/46979052/79052526-64898100-7c37-11ea-8679-976363ba41bd.JPG)
![MaxAcceleration](https://user-images.githubusercontent.com/46979052/79052529-66ebdb00-7c37-11ea-9cd4-dc83af1f61bc.JPG)

**Comment by jimhiggs** [comment]
I have 3 extruders, it wont show 3 I see, although I do have all three set the same in marlin conf.

**Comment by radek8** [comment]
However, it is possible to configure more extruders and hotends in Configuration.h. The firmware code is not adapted to this. Must be programmed
Before it is fixed, if you have 1 tool and 3 extruders, add additional lines to each item in the ParseACK.c file. As I do.
