### ISSUE TITLE
[BUG] Print stop/abort not turn off heaters & not realese stepp. motors / USB TFT problem

### ISSUE THREAD

**Issue by DanielSan1000** [bigtreetech/BIGTREETECH-TouchScreenFirmware#561]
### Description

1. Print abourt not stopping heaters & not realese stepp. motors also 
2. It is not pissible to use USB on TFT35 for printing
Not possible to start printinf from usb. Exit from manu after click on gcode

### Steps to reproduce

1. During the print stop printing.
2. Trying to start printing from TFT USB

**Expected behavior**

1. Should stop prinitng and turn off heaters & elsese all stepper motor

**Actual behavior**

1. Print abourt not stopping heaters & not realese stepp. motors also 
2. It is not pissible to use USB on TFT35 for printing
Not possible to start printinf from usb. Exit from manu after click on gcode

### Hardware Variant

Bigtreetech TFT35 & skr e3 mini v1.2 (Ender 3 setup)

### TFT Firmware Version & Main Board Firmware details

BIGTREETECH-TouchScreenFirmware V3.0.25.3

**Comment by bigtreetech** [comment]
Hello, it should be fixed in #480 , please download the lastest version firmware and test it

**Comment by DanielSan1000** [comment]
Ok. Thanks
