### ISSUE TITLE
[BUG] Can not change extruder number in Extrude menu

### ISSUE THREAD

**Issue by jimhiggs** [bigtreetech/BIGTREETECH-TouchScreenFirmware#568]
Just updated to .26 and now  can not change extruder number by pressing nozzle button. It is stuck at E0 I have 3 extruders.

**Comment by jimhiggs** [comment]
I reverted to 25 and still can't change extruder. Strange I could before changing to 26.

**Comment by bigtreetech** [comment]
Hello, Firmware defaults to only one extruder， you need to set to number of extruder to 3 in here
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/blob/3e7503113e956dd99f71bfd00596541ed0281727/TFT/src/User/Configuration.h#L142

**Comment by jimhiggs** [comment]
Thanks. i must have done that when I installed 25 back in November. Sorry for the time waste.

**Comment by radek8** [comment]
Version 26 also does not correctly support multiple extruders
look at
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/556

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
