### ISSUE TITLE
[BUG] TFT35 3.0 E3 - #define ST7920_FNCOLOR don't work

### ISSUE THREAD

**Issue by Skybeat** [bigtreetech/BIGTREETECH-TouchScreenFirmware#570]
### Description
If you change #define ST7920_FNCOLOR  in source code, compile and update the TFT, it won't effect on the TFT in Marline mode.

### Steps to reproduce

- change platformio.ini to default_envs = BIGTREE_TFT35_E3_V3_0
- change #define ST7920_FNCOLOR to e.g. GRAY
- compile
- update the TFT35 3.0 E3 with the new compiled firmware
- switch to Marline mode

**Expected behavior**
the font color changes to gray

**Actual behavior**
the font color is still yellow

### Hardware Variant
TFT 35 3.0 E3
TFT35 3.0 E3 Firmare V.x.x.26
Board Firmaware: Marline 2.0.1

### Additional Information
If you change the font color for Marline mode via TFT settings it works very well.

**Comment by bigtreetech** [comment]
Hello,  `#define ST7920_FNCOLOR` is the default value, you need goto "Settings->Feature->Settings Reset" to reset it. and #569 for the same reason
