### ISSUE TITLE
No LCD option on TFT35 v2.0 and .26 firmware

### ISSUE THREAD

**Issue by electricJP** [bigtreetech/BIGTREETECH-TouchScreenFirmware#572]
### Description

No LCD backlight control, auto sleep function in Settings->Feature->LCD Brightness on TFT35 v2.0 with Unified Menu Material theme

### Steps to reproduce

1. flash BIQU_TFT35_APP1_V2.0.26.bin
2. go to Settings->Feature->LCD Brightness
3. No LCD option

**Expected behavior**

According to readme : Settings->Feature->LCD Brightness

### Hardware Variant
TFT35 v2.0

**Comment by ssombra** [comment]
I have the same problem.

**Comment by bigtreetech** [comment]
Hello  TFT35 V2.0 backlight is directly wiring to the power supply instead of MCU's IO, so the backlight cannot be controlled, only TFT24 V1.1 TFT35 V3.0 TFT35 E3 V3.0 support this function

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
