### ISSUE TITLE
[Q] Popup in Touchscreen mode

### ISSUE THREAD

**Issue by Markus1970** [bigtreetech/BIGTREETECH-TouchScreenFirmware#573]
Hi All,
Firmware version TFT35_V3.0.25.3 is installed in my TFT35-E3 V3 Display. Its working fine so far but when i send a M0 (Pause) command to the printer i get only a yellow dot in the upright corner of the display. There is no message like" press button to resume" . The echo box in the middle of the main screen shows only the last message. If the display is running in marlin mode, I get the notification that i need to press the button to resume the print.

Any idea on this?

Thanks

markus

**Comment by oldman4U** [comment]
Hi Markus.

There have been many improvements in this area. Could you please check the latest firmware and close this ticket if the problem is solved. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
