### ISSUE TITLE
[FR] ('Optional' Enhancements )

### ISSUE THREAD

**Issue by KCGreg** [bigtreetech/BIGTREETECH-TouchScreenFirmware#574]
**Is your feature request related to a problem? Please describe.**
I use this firmware for a controlling a CNC.  The manner in which changes are being made to the firmware is making the TFT more difficult to use for this purpose do to assumptions being made about how features are used. 

**Describe the solution you'd like**
1)  Firmwares such as Marlin allow extruders and fans to now be optional.  It would be nice if this firmware included '0-6' as a selection set instead of 1-6 as in the below example.

     #define TOOL_NUM     1    // set in 1-6
     #define EXTRUDER_NUM 1    // set in 1-6
     #define FAN_NUM      1    // set in 1-6

2) It is difficult to turn off all gcode that is being appended by this firmware.  There are features controlled by buttons on the UI that should send specific gcodes and are nice to see in this firmware.  However, I don't need added gcode that turns off motors or heaters that is automatically appended to gcode that I run.  It would be really nice if these were features that could be turned on/off in the config files.

3) Overall, please consider that 3D printer firmwares are changing, and please consider any 'features' added to this TFT firmware as optional.  I realize I am using this for controlling a device that is not a 3D printer that most purchasers of a TFT would use this for.  However, as printers evolve, a firmware that assumes a particular setup becomes less useable.  Consider that there are now 3D printers on the market with interchangeable toolheads such as extruder, CNC mill, or laser engraver.  Can the 'assumed' features of this firmware support those types of changes?
 
**Describe alternatives you've considered**
At this time, I have reverted back to the .25 release as it was far easier for me to delete the start and end gcode.

**Additional context**

**Comment by oldman4U** [comment]
Could you please be so kind and close this ticket. Your feature request is covered in the pinned Feature Request ticket #1177 

Thank you
