### ISSUE TITLE
[BUG] Print confirmation issue on TFT35 3.0

### ISSUE THREAD

**Issue by mouse100** [bigtreetech/BIGTREETECH-TouchScreenFirmware#579]
Flashed the TFT35 E3 3.0 to latest official firmware but after I launch a print from SD/USB I have the print confirmation dialog behind the other TFT icons.

![Screenshot_20200417-120628](https://user-images.githubusercontent.com/35471262/79558097-eea47000-80a3-11ea-90ba-40ac8f861025.jpg)

**Comment by bigtreetech** [comment]
Hello， This display is indeed a bug. The root reason may be that you enabled the “Filament runout” feature but did not insert the “Filament runout sensor”. Please check your setting in "Settings->Feature->Filament runout”?

**Comment by mouse100** [comment]
> Hello， This display is indeed a bug. The root reason may be that you enabled the “Filament runout” feature but did not insert the “Filament runout sensor”. Please check your setting in "Settings->Feature->Filament runout”?

@bigtreetech I have the feature disabled but the bug is still there.

![IMG_20200419_104914](https://user-images.githubusercontent.com/35471262/79683668-dfe8c500-822b-11ea-96dc-f1f426388fa4.jpg)

**Comment by rjacobs1969** [comment]
I've seen this on my TFT35 V3 as well (using 26 release) moreover when a popup  happens  in the file selection screen you can't see it nor dismiss (press ok) it. leaving you with no working touch until you reboot.
I've not had time to dive in the source code yet but it seems the pop-ups are painted with a lower priority (=below) than other screens but are blocking touch input until you press OK (which is not possible if other elements are drawn over the button)
Popups should be aways be drawn on top, also it would be nice if you can ok these by pressing the encoder.

**Comment by oldman4U** [comment]
Hi.

What is the status of this issue?

Should be fixed in the meantime.

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
