### ISSUE TITLE
[BUG] LCD idle timer, option 4 twice

### ISSUE THREAD

**Issue by Tillema** [bigtreetech/BIGTREETECH-TouchScreenFirmware#580]
### Description
LCD idle timer, option 4 twice in list.

### Steps to reproduce
Not really hard, just open configuration.h and look in line 43.
Couldn't test, because don't have the TFT35 E3.

**Comment by thisiskeithb** [comment]
Thanks for the heads up! I've submitted a PR to update the options/comment: #581
