### ISSUE TITLE
[Q] (can this get working with MKS TFT 35 v1.0?

### ISSUE THREAD

**Issue by rightawy** [bigtreetech/BIGTREETECH-TouchScreenFirmware#589]
i see this firmware working with MKS TFT32. I s this possible to work with MKS TFT35?  how can I get that printing screen?

**Comment by thisiskeithb** [comment]
Of the MKS TFTs, only the MKS TFT32 1.4 is supported at this time.

**Comment by rightawy** [comment]
cant you add it also?

**Comment by thisiskeithb** [comment]
It can be done, yes. Someone will have to port code to the different hardware variants.

**Comment by darkspr1te** [comment]
firmware for 3.5" screen (with stm32f407) is almost complete, am still awiaing my 3.5 screen to test the firmware on but it should work, i wrote a new bootloader for the 407 model without even having one. so am confident it will be usable

**Comment by extremeshok** [comment]
if you can post it, i can test it for you

**Comment by oldman4U** [comment]
Hello.

Any update on this topic?

**Comment by darkspr1te** [comment]
For those wanting to try out this build, open source bootloader here https://github.com/darkspr1te/mkstft35_V1_open_bootloader/blob/master/buildroot/SDCARD/firmware.bin
binary of BTT for MKSTFT35V1_0 here https://github.com/darkspr1te/mkstft35_V1_open_bootloader/files/5210339/mkslcd.zip
fonts/bmp files for sdcard here 
https://github.com/darkspr1te/mkstft35_V1_open_bootloader/files/5210445/MKS.zip
and to revert to factory bootloader avilable here 
https://github.com/makerbase-mks/MKS-TFT/files/5156616/mkstft35_v1.0.3_bootloader.zip

**Comment by oldman4U** [comment]
And now this is merged into master branch. Could you please test it and close the ticket afterwards. Thank you

**Comment by chrisdaloa** [comment]
I can not see this options in platformio.ini, Is it possible to install it and try? Thanks

**Comment by chrisdaloa** [comment]
how can I load the bootloader on this display? It's a mks-tft35 rebranded. There are no TX e RX pins..

![immagine](https://user-images.githubusercontent.com/44293834/97864973-bd228780-1d09-11eb-9d93-a3b1516dbf18.png)

**Comment by darkspr1te** [comment]
can you confirm if this is a flying bear reborn board and lcd ? if so its using the stm32f103 cpu on the main board/tft35 lcd and the mkstft35 uses stm32f407+tft 35 which means the tft35/2.8/3.2 firmwares are not compatible (they uses stm32f107/407 )  , are there any links to manufacture pages/schematics ?
