### ISSUE TITLE
Background Colour (RGB / HEX) / Image + Change Fonts

### ISSUE THREAD

**Issue by E-Studios** [bigtreetech/BIGTREETECH-TouchScreenFirmware#59]
How can we change the Background Colour with RGB or # Colours? or even with a BMP Image?

And there is no information about the FONT and how to change it and how to create a new font and add / replace it...

Can we please get some more information about this stuff? The Thunder has a GUI with images and more information on it and it uses a TFT35?

If you want to sell more of your kits to the DIY community go add more guides / tutorials how to create custom GUI's and FONT's

**Comment by dineshvyas** [comment]
It will be really nice to publish GUI documentation.

**Comment by dineshvyas** [comment]
i want to add a page. any suggestion?

**Comment by dineshvyas** [comment]
I made a new GUI layout. smaller icons and a status bar at bottom to display printer status and kinematics.

**Comment by thisiskeithb** [comment]
> I made a new GUI layout. smaller icons and a status bar at bottom to display printer status and kinematics.

Do you have a link?
