### ISSUE TITLE
Filament runout not working

### ISSUE THREAD

**Issue by Neme77** [bigtreetech/BIGTREETECH-TouchScreenFirmware#593]
### Description

 the filament sensor is correctly detected I checked its status with m119, during printing if active the sensor by setting smart or on in TFT mode the printing stops even if the filament is present and the message filament finished appears on the display.
In lcd emulation mode printing starts and after a few seconds the m600 command is performed.

### Hardware Variant
TFT35 V3_0
### Additional Information
* Include a ZIP file containing your `Configuration.h` or use [Pastebin](https://pastebin.com/) and paste a link in this issue.
* Provide pictures or links to videos that clearly demonstrate the issue.

**Comment by poumsoon** [comment]
I also have the same problem.
When printing through MKS MINI 12864, the filament sensor works well, but it does not work when connected to TFT28 or TFT35 V2.
Testing with the May 26 firmware has the same problem.

**Comment by poumsoon** [comment]
> I also have the same problem.
> When printing through MKS MINI 12864, the filament sensor works well, but it does not work when connected to TFT28 or TFT35 V2.
> Testing with the May 26 firmware has the same problem.

I knew the cause of the problem. In the case of touch LCD, the filament sensor must be connected to the port of the LCD. Refer to the TFT LCD manual.
  I didn't expect anything at all, and I think I've been looking for this and that for three days.

**Comment by oldman4U** [comment]
kisslorand recommends to do the following:
Send M75 to Marlin when print begins. Marlin doesn't know that the print is started so no filament runout warnings. It's not a bug.
You can put M75 in your Start-Gcode and you're set. That's what I did.

Please let us know if this solves your problem

Thank you
