### ISSUE TITLE
Feature: Add button for Marlin Manual Mesh Bed Leveling

### ISSUE THREAD

**Issue by RidgebackZulu** [bigtreetech/BIGTREETECH-TouchScreenFirmware#594]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
In the original Marlin LCD display is the option for bed leveling using the 9 point mesh. This works extremely well on the Ender 3 Pro. I would like to have a button added for this feature please.

**Describe alternatives you've considered**
I can long hold on the LCD until it switches back to the original Marlin LCD, perform mesh bed leveling, then long hold to go back.

**Additional context**
None.

**Comment by rebel1** [comment]
Hi,
you can test this branch https://github.com/rebel1/BIGTREETECH-TouchScreenFirmware/tree/MBL

**Comment by RidgebackZulu** [comment]
Hi, I installed this, (BIGTREE_TFT35_V3.0_E3.26.bin and /TFT35) but do not see a button for mesh level. I still only see the four point manual. I tried both Unified Menu and traditional.

**Comment by rebel1** [comment]
Hi, here is an precompiled binary for you.
[BIGTREE_TFT35_V3.0_E3.26.bin.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4543623/BIGTREE_TFT35_V3.0_E3.26.bin.zip)

**Comment by RidgebackZulu** [comment]
Thank you! I see the MBL now! Onto testing!

**Comment by RidgebackZulu** [comment]
Tested well! I ran a calibration cube, and the mesh leveling worked well! I appreciate your efforts on this and hope it gets mainlined soon. Great work!

**Comment by sonny-c** [comment]
> Hi, here is a precompiled binary for you.
> [BIGTREE_TFT35_V3.0_E3.26.bin.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4543623/BIGTREE_TFT35_V3.0_E3.26.bin.zip)

I was going to create a new post asking about Manual Mesh Bed Leveling, but instead, I will follow up here.

Does this .bin file put Manual Mesh Bed Leveling in Touch mode?
If so, does it allow you to edit a specific mesh point, as you can in LCD mode?
I am currently using the Unified MenuMaterial theme.  If I flash this .bin file, do new icons need to be created for the MBL options?

**Comment by charakaSamawry** [comment]
Hi rebel1, i use MANUAL_PROBE to do UBL would tht be a good branch for me to use??  (Also running skr mini v2 and tft34 e3 v3)

**Comment by islonina** [comment]
> Hi, here is an precompiled binary for you.
> [BIGTREE_TFT35_V3.0_E3.26.bin.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4543623/BIGTREE_TFT35_V3.0_E3.26.bin.zip)

Hi

This doesn't work for me, i have half english half german menu and a lot of missing icon

**Comment by oldman4U** [comment]
Could you please be so kind and close this ticket. Your feature request is covered in the pinned Feature Request ticket #1177 

Thank you

**Comment by oldman4U** [comment]
@rebel1 

Hi. Have you ever made a PR for this? If not, why not?

**Comment by oldman4U** [comment]
digant73 added Mesh bed levelling, so I remove it from the FR list
