### ISSUE TITLE
[BUG] Screen Warning on bottom

### ISSUE THREAD

**Issue by el-quique** [bigtreetech/BIGTREETECH-TouchScreenFirmware#596]
### Description

I am seeing that when missing filament the warning of Filament "Runout" is at the bottom of the print screen.

![IMG_2583](https://user-images.githubusercontent.com/5359805/80363150-2eb0e300-885a-11ea-9519-9bc67e260a21.JPG)

### Steps to reproduce

1. No filament on sensor connect to TFT
2. Start Printing
3. Warning Filament Runout, see on the bottom
4. Clic on button "Confirm"

**Expected behavior**
Warning Filament Runout, see on the top

### Hardware Variant
MKS TFT 32 v1.4
### TFT Firmware Version & Main Board Firmware details
TFT Firmware BigTreeTech v x.x.26
Marlin 2.0.4.4

### Additional Information
[TFT_Configuration.h.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4513133/Configuration.h.zip)
[Marlin.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4536476/Marlin.zip)

**Comment by el-quique** [comment]
any idea

**Comment by oldman4U** [comment]
Hi.

Is this still a problem, please let us know?

If not, please close this ticket

Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
