### ISSUE TITLE
[FR] Implement "LittlevGL"

### ISSUE THREAD

**Issue by GeckoSys3D** [bigtreetech/BIGTREETECH-TouchScreenFirmware#598]
It seems wonderful GUI's are made with lvgl (https://github.com/littlevgl/lvgl).
MKS implemented this now. It would be awesome, if someone is able to implement this GUI library for the display.

Link: https://github.com/makerbase-mks/Mks-Robin-Nano-Marlin2.0-Firmware

**Comment by oldman4U** [comment]
Is this somehow related?

https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/1067

**Comment by oldman4U** [comment]
Could you please be so kind and close this ticket. Your feature request is covered in the pinned Feature Request ticket #1177 

Thank you

**Comment by Domush** [comment]
Why are unfinished feature requests being closed?

Having a consolidated list doesn't fulfill a feature request, it only makes them easier to find.

This needs to be reopened, as do ALL of the feature requests which have not been fulfilled.
