### ISSUE TITLE
Charset encoding language file.

### ISSUE THREAD

**Issue by kkaleta** [bigtreetech/BIGTREETECH-TouchScreenFirmware#60]
![20190929_170110](https://user-images.githubusercontent.com/4312668/65899988-363c0680-e3b5-11e9-837c-2cb3da1bdb15.jpg)
Every time I edit a language file, I have a problem with the character encoding.  For example, a degree symbol.  How should these files be encoded?

**Comment by dineshvyas** [comment]
recompile and flash it should work or see if it shows something like this in source file.
![deg](https://user-images.githubusercontent.com/55104840/66591904-a0248f00-ebb1-11e9-8d58-e3374da0747d.PNG)
you may change these to simple text. for me recompiling and flashing worked.

**Comment by spilz87** [comment]
I have the same issue and tried several way but when I change something in langage file in an other #define, °C become Chinese characters :(

**Comment by spilz87** [comment]
Where did you find this skin ? I like the icons :)

**Comment by kkaleta** [comment]
@spilz87 I've made them.

**Comment by spilz87** [comment]
@kkaleta good job 👍
