### ISSUE TITLE
Invert filelist

### ISSUE THREAD

**Issue by ManiacCreality** [bigtreetech/BIGTREETECH-TouchScreenFirmware#601]
Would be nice to invert the filelist that newer copied files on the SD Card would be in top position like its standard in Marlin.

**Comment by zonalimitatore** [comment]
Allright. But how choose how sort the files?

**Comment by oldman4U** [comment]
Could you please be so kind and close this ticket. Your feature request is covered in the pinned Feature Request ticket #1177 

Thank you

**Comment by oldman4U** [comment]
Please test PR #1908 to see if it solves the FR.
