### ISSUE TITLE
[FR] A vertical portrait mode to use with prusa mini clone

### ISSUE THREAD

**Issue by hazeyjay77** [bigtreetech/BIGTREETECH-TouchScreenFirmware#602]
A portait mode would be awesome for use with a prusa mini clone I have looked everywhere for this feature and no screen as it as far as I'm aware

**Comment by thisiskeithb** [comment]
This is a duplicate request of https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/524.

**Comment by oldman4U** [comment]
Please close this ticket.

Thank you
