### ISSUE TITLE
[BUG] Z offset not saving

### ISSUE THREAD

**Issue by frankt2012** [bigtreetech/BIGTREETECH-TouchScreenFirmware#603]
### Description

When going into ABL menu and setting z offset and babbysteps it will not save. I lose the settings once the printer is turned off and back on. 

### Steps to reproduce

1. Go to ABL menu
2. Z offset and set it.
3. Hit save.
4. Turn off printer and then back on

**Expected behavior**
Z offset setting should say 1.10 which I set it to.

**Actual behavior**
Z offset says zero on fresh start up.

### Hardware Variant
TFT35

### TFT Firmware Version & Main Board Firmware details
TFT firmware is x.x.26
Marlin is 2.0.5.3

### Additional Information
* Include a ZIP file containing your `Configuration.h` or use [Pastebin](https://pastebin.com/) and paste a link in this issue.
* Provide pictures or links to videos that clearly demonstrate the issue.

**Comment by junkerpat** [comment]
Same for me !!!!!!!

**Comment by roomme13** [comment]
I believe that save button not call M500 for EEPROM  save.

I don't know it bug or not, same behavior if you using 128x64 lcd.

It would be nice if it can save automatically to EEPROM.

Maybe I would like to add this. 

-For baby stepping, even you configure babystepping_probe in marlin. It show independent value in TFT. 
-If you edit z offset value in machine parameter, it cannot be minus at first, you need to enter any value  then delet, after that you can have minus value.

**Comment by radek8** [comment]
I have the same problem.
The problem is in the file
Menu \ ProbeOffset.c
and
Menu \ BabyStep.c
comment out these dba lines and save will work

viz:
 https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/554

![save](https://user-images.githubusercontent.com/46979052/80153124-4455ac80-85bd-11ea-80ec-081102544915.JPG)

**Comment by roomme13** [comment]
> 
> 
> I have the same problem.
> The problem is in the file
> Menu \ ProbeOffset.c
> and
> Menu \ BabyStep.c
> comment out these dba lines and save will work
> 
> viz:
> #554
> 
> ![save](https://user-images.githubusercontent.com/46979052/80153124-4455ac80-85bd-11ea-80ec-081102544915.JPG)

if you clone latest, this is already commentout. but i cannot find parser for that EEPROM status.

you can put this on  parseACK.c and it will work.
![image](https://user-images.githubusercontent.com/1905950/80154602-20f52680-85ea-11ea-9923-c23a7d28a635.png)

**Comment by junkerpat** [comment]
Working thanks

Le jeu. 23 avr. 2020 5 h 53 p.m., radek8 <notifications@github.com> a
écrit :

**Comment by frankt2012** [comment]
> if you clone latest, this is already commentout. but i cannot find parser for that EEPROM status.
> 
> you can put this on parseACK.c and it will work.
> ![image](https://user-images.githubusercontent.com/1905950/80154602-20f52680-85ea-11ea-9923-c23a7d28a635.png)

I have to try that. I did just recently find out that if I set it and go to Save EEPROM it then saves.

**Comment by radek8** [comment]
The addition of passeACK.c works
Thank you
