### ISSUE TITLE
Including MKS TFT70

### ISSUE THREAD

**Issue by afkfurby** [bigtreetech/BIGTREETECH-TouchScreenFirmware#609]
Would it be hard to include the MKS TFT70 in the buildtree?
I'm asking because sadly BTT does not have an 7 inch screen and that's what I need.

**Comment by thisiskeithb** [comment]
Anything is possible if someone writes the code for it 🙂

Larger TFTs from BigTreeTech are in the works.

**Comment by bigtreetech** [comment]
Hello, our TFT43/TFT50/TFT70 will be released soon!

**Comment by afkfurby** [comment]
I'm just curious because the mks tft32 is already in the buildtree. What need to be done to port this to the tft70?

**Comment by thisiskeithb** [comment]
> What need to be done to port this to the tft70?

`STM32F4` support, so it won’t be a quick port.
