### ISSUE TITLE
connecting TFT 35 V1.2 to Raspberry

### ISSUE THREAD

**Issue by Heikoho** [bigtreetech/BIGTREETECH-TouchScreenFirmware#61]
Hello,
how can I connect the TFT 35 V1.2 to a Raspberry PI as an normal TFT?
I want to run Octoprint on the PI.
Thank you for answering

Heikoho

**Comment by drphil3d** [comment]
Buy the correct hardware

**Comment by Heikoho** [comment]
Hello,
what a clever and nice answer.
I like People, who put on there brain before answering.
thanks 
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 04.10.19, 02:54, Philip Mally <notifications@github.com> schrieb:
Buy the correct hardware

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/61?email_source=notifications\u0026email_token=ANLLSCI3S5FFCZ5NYG474Y3QM2H57A5CNFSM4I4EUZF2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAKA2CQ#issuecomment-538184970",
"url": "https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/61?email_source=notifications\u0026email_token=ANLLSCI3S5FFCZ5NYG474Y3QM2H57A5CNFSM4I4EUZF2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAKA2CQ#issuecomment-538184970",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by MangaValk** [comment]
you can't, wrong hardware

**Comment by drphil3d** [comment]
that's all I was saying. I didn't mean to come off as being rude.

**Comment by bagobor** [comment]
@Heikoho it's not possible due to lack of 'normal' TFT interfaces. LCD screen is controlled by the onboard STM32 controller.
But you may create your own firmware and use UART interface .... it's definitely not a 'normal' TFT but can be a good and cheap touch controller.  :)
