### ISSUE TITLE
Print From OnboardSD "Echo Unknown Command M33" then crash [BUG]

### ISSUE THREAD

**Issue by BritNoob** [bigtreetech/BIGTREETECH-TouchScreenFirmware#614]
When going into the Print Menu then selecting OnboardSD using the Unified BIGTREE_TFT35_V3.0_E3.26.bin firmware + TFT35 directory.
Print From OnboardSD will cause a..... 
"Echo , Unknown Command M33 *filename.gcode* " then crash and the display will become unresponsive. 

I have included a zip with the gcode. From looking at it i cannot see any M33...
Thanks!

[CFFFP_Test 2.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4531411/CFFFP_Test.2.zip)

**Comment by thisiskeithb** [comment]
You need to enable `LONG_FILENAME_HOST_SUPPORT` in Marlin.

**Comment by fibaq** [comment]
Hi I have same problem I ‘am new of this
Where I can find  
Please point me direction (folder) 
Thank you

**Comment by bigtreetech** [comment]
https://github.com/MarlinFirmware/Marlin/blob/0518dec60d0931745efa2812fa388f33d68cfa29/Marlin/Configuration_adv.h#L1122

you need to enable `LONG_FILENAME_HOST_SUPPORT` in your Marlin `Configuration_adv.h` file

**Comment by fibaq** [comment]
Hi Thank u for information but unfortunately 
Same error 
After enabled  This happened after update software to screen 
Any advice ? 
![image](https://user-images.githubusercontent.com/64303993/80283566-5d22a700-8710-11ea-90f8-c6c1da74bc35.jpg)
![BB44ADC6-3671-4D65-A7FC-BEE9608600B2](https://user-images.githubusercontent.com/64303993/80283575-6ad82c80-8710-11ea-9cdb-e1b42419e050.jpeg)

**Comment by thisiskeithb** [comment]
Did you actually update your motherboard firmware? Marlin will return "Unknown command" when that particular G/M code(`M33` in this case) is not enabled.

**Comment by xoniq** [comment]
> You need to enable `LONG_FILENAME_HOST_SUPPORT` in Marlin.

I got this issue too. This helped. Turned it on, compiled, and now it's working properly.

**Comment by fibaq** [comment]
Hi yes working now but not printing from on board Sd

**Comment by Leurie02** [comment]
> You need to enable `LONG_FILENAME_HOST_SUPPORT` in Marlin.

Hello... just don't use _ or any special characters on your file name :)

**Comment by Leurie02** [comment]
> When going into the Print Menu then selecting OnboardSD using the Unified BIGTREE_TFT35_V3.0_E3.26.bin firmware + TFT35 directory.
> Print From OnboardSD will cause a.....
> "Echo , Unknown Command M33 _filename.gcode_ " then crash and the display will become unresponsive.
> 
> I have included a zip with the gcode. From looking at it i cannot see any M33...
> Thanks!
> 
> [CFFFP_Test 2.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4531411/CFFFP_Test.2.zip)

Hello... just don't use _ or any special characters on your file name :)
