### ISSUE TITLE
 I have to switch to marlin mode to boot

### ISSUE THREAD

**Issue by junkerpat** [bigtreetech/BIGTREETECH-TouchScreenFirmware#618]
I put the power on and nothing happens ..... I switch to marlin mode it starts to boot come back in touch mode and everything is correct?

**Comment by bigtreetech** [comment]
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/709#issuecomment-634381742
It should be the same reason as this issue and has been resolved now, so close here
