### ISSUE TITLE
[BUG] Change bmp name for Fix #583

### ISSUE THREAD

**Issue by el-quique** [bigtreetech/BIGTREETECH-TouchScreenFirmware#623]
Hi. change the name bmp file:
StatusBed.bmp -> Status_Bed.bmp
StatusFan.bmp -> Status_Fan.bmp
StatusNozzle.bmp -> Status_Nozzle.bmp

### Steps to reproduce

1. Update TFT FW 
2. Icon Status Screen is missing for Nozzle, Bed, Fan

**Expected behavior**
Missing Icons

**Actual behavior**
Change bmp files and now visible icons

### Hardware Variant
TFT 32 v1.4

### TFT Firmware Version & Main Board Firmware details
TFT vxx.26 & Marlin 2.0.4.4

**Comment by thisiskeithb** [comment]
See PR https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/619

**Comment by el-quique** [comment]
but in the "Copy to SD...", this change is not done
