### ISSUE TITLE
Filament motion sensor TFT display is not interested in...

### ISSUE THREAD

**Issue by AntoszHUN** [bigtreetech/BIGTREETECH-TouchScreenFirmware#629]
An interesting mistake. I have a filament motion sensor built from an optical switch. Marlin mode works great as it should. SKR V1.4 Turbo motherboard is connected to the E0DET connector. Flawless. He senses everything well. If it gets stuck, it gets stuck, the thread breaks it too. But. But when printing in touchscreen mode, the display firmware also ignores the sensor connected to the SKR V1.4 Turbo motherboard. I tried every possible option. It does not work when connected to the display. Only in one mode. There is filament, there is no filament. That's it. Is there a way to make the motion sensor work with the firmware of the TFT displays?

**Comment by oldman4U** [comment]
Jonapot Antosz.

Is this still an issue?

**Comment by AntoszHUN** [comment]
I do not know. I haven't dealt with it since. I'll check in tonight.

**Comment by oldman4U** [comment]
Any news?

**Comment by oldman4U** [comment]
Hi.

According to kisslorand this issue can be solved by adding M75 to the start gcode. This allows Marlin and therefore the mainboard to recognise that the print started which also makes the filament sensor work.

Please check and let me know

Jonapot

**Comment by AntoszHUN** [comment]
> Hi.
> 
> According to kisslorand this issue can be solved by adding M75 to the start gcode. This allows Marlin and therefore the mainboard to recognise that the print started which also makes the filament sensor work.
> 
> Please check and let me know
> 
> Jonapot

I have not tried. My printer is currently being rebuilt. Maybe if you are interested check out my youtube channel. :D

**Comment by oldman4U** [comment]
I checked your YouTube but my hungarian is not that good, sorry;-(

**Comment by AntoszHUN** [comment]
> I checked your YouTube but my hungarian is not that good, sorry;-(

The English subtitle is already being prepared. Most videos are ready. Is it somewhat understandable?

**Comment by oldman4U** [comment]
I checked the smart filament and NeoPixel movie but could not see the subtitles.

Btw, you are using the standard UI and not yours...

**Comment by AntoszHUN** [comment]
> I checked the smart filament and NeoPixel movie but could not see the subtitles.
> 
> Btw, you are using the standard UI and not yours...

Those videos are not yet captioned. I'm moving a little slow with it. But I try.

**Comment by oldman4U** [comment]
;-)

Zs.Antal <notifications@github.com> schrieb am Do. 14. Jän. 2021 um 15:11:
