### ISSUE TITLE
after updating my tft35 v3 to the latest firmware it complained about a parser problem and after going back to firmware that was working the tft35 is not working at all propperly[BUG] (short description)

### ISSUE THREAD

**Issue by davetech** [bigtreetech/BIGTREETECH-TouchScreenFirmware#636]
### Steps to reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior**

**Actual behavior**

### Additional Information
* Include a ZIP file containing your `Configuration.h` or use [Pastebin](https://pastebin.com/) and paste a link in this issue.
* Provide pictures or links to videos that clearly demonstrate the issue.

**Comment by oldman4U** [comment]
Hi Dave

What is the status of this issue?

**Comment by davetech** [comment]
Hi,

The problem has been sorted.

**Comment by oldman4U** [comment]
Good to hear. Please close this ticket then. Thank you
