### ISSUE TITLE
USB disks are not loaded - for guruathwal

### ISSUE THREAD

**Issue by radek8** [bigtreetech/BIGTREETECH-TouchScreenFirmware#639]
for @guruathwal :
In bigtreetech/BIGTREETECH-TouchScreenFirmware#627
You have an error.
USB disks are not loaded after editing
U_DISK_SUPPROT is not U_DISK_SUPPORT

After overwriting to U_DISK_SUPPROT it is functional.
I also stopped reading SD on the board. I did not find an error.
Can you check it?
Thank you
![chyba USB1](https://user-images.githubusercontent.com/46979052/80766301-6ca55400-8b45-11ea-866e-2a41c0c924f2.JPG)
![chyba USB2](https://user-images.githubusercontent.com/46979052/80766305-6dd68100-8b45-11ea-943f-fc5af51b0d4f.JPG)
![chyba USB3](https://user-images.githubusercontent.com/46979052/80766309-70d17180-8b45-11ea-9f0f-75872bf1e629.JPG)

**Comment by radek8** [comment]
File Print.c

**Comment by Balzac40** [comment]
I confirm !

**Comment by guruathwal** [comment]
@radek8 thanks for Identifying. I think `U_DISK_SUPPROT` was misspelt by someone at the time of adding it and I unknowingly used used the correct spelling which resulted in the bug.

**Comment by radek8** [comment]
@guruathwal 
Thank you
You are doing a good job
