### ISSUE TITLE
[Q] (Can i add BiQU_Tool program as a plugin for CURA. Is it possible to do the automatic creation of .BMP?)

### ISSUE THREAD

**Issue by rozenrod** [bigtreetech/BIGTREETECH-TouchScreenFirmware#640]
Can i add BiQU_Tool program as a plugin for CURA. Is it possible to do the automatic creation of .BMP?

**Comment by oldman4U** [comment]
Hi.

This is available now. Could you please check and close this ticket after that.

Thank you
