### ISSUE TITLE
Communication timeout - reset send buffer block

### ISSUE THREAD

**Issue by QuitButton** [bigtreetech/BIGTREETECH-TouchScreenFirmware#642]
### Description

Just recently I'm seeing lots of "Communication timeout - reset send buffer block" errors from Repetier Host when printing using USB and having the TFT in Touch mode. This error doesn't happen with the TFT in Marlin mode.

I also notice there's lots of visual stuttering and pausing with Repetier as it visualises the printout while printing, suggesting there's buffer blocking happening more often that just when the error message shows.

I've tried changing baud rate, increasing various serial buffer sizes in Marlin, but so far these changes haven't made an obvious difference.

### Steps to reproduce

1. Print something using Repetier host via USB 

**Expected behavior**
No errors.

**Actual behavior**
"Communication timeout - reset send buffer block" on a regular but unpredictable regularity 

### Hardware Variant
TFT24 V1.1

**Comment by zonalimitatore** [comment]
Do you solved? I've a random communication errors with Marlin's mode too

**Comment by QuitButton** [comment]
Nope. It happens randomly - the hardware seems to get into a mess and will result in errors and failed prints at times. Powering off and on again and it'll fix itself and be fine for days until it gets in a mess again. For me it will occasionally do this in Marlin mode on the TFT, but its quite a regular thing when in touch screen mode.

I've tried playing with the buffer sizes etc. in Marlin and it made no obvious difference.

There's obviously some timing issue with the USB, I'm guessing its similar to a lot of the USB-Serial issues that where the bane of some 8Bit 3D printer boards, but I've got no way of diagnosing exactly where the issue lays.

**Comment by zonalimitatore** [comment]
Tomorrow i try to print in touch mode.my baud is 115200

**Comment by zonalimitatore** [comment]
Ok...I've print all day in touch mode,using usb cable and repetier.No message about connection errors or resend.
I've do a change in buffer (config_adv) and activate serial xon xoff

**Comment by oldman4U** [comment]
What is the status of the ticket?

**Comment by QuitButton** [comment]
> 
> 
> What is the status of the ticket?

Ignored?

**Comment by oldman4U** [comment]
Ok. 

Have you tried the changes @zonalimitatore has suggested? Or anything else?

**Comment by oldman4U** [comment]
Hi.

With the latest TFT firmware, some buffers have been changed. Could you please check if this solves the problem you reported and let us know.

Thank you

**Comment by QuitButton** [comment]
"latest" firmware being released on 11 Apr 2020?

**Comment by oldman4U** [comment]
Latest firmware being released today.

QuitButton <notifications@github.com> schrieb am Di. 12. Jän. 2021 um 18:14:

**Comment by oldman4U** [comment]
Have you found the firmware and uploaded it to your TFT?

**Comment by QuitButton** [comment]
No, where is this "latest release"? The latest I can see is Vx.x.26 Latest on 11 Apr 2020

**Comment by JerksonS** [comment]
I too have this problem on a biquB1. Flashed with the latest screen firmware from here 2 days ago. Printing from usb/sd card is fine, but repetier ends up with this same error randomly (usually within the first 1 hour of a print)

**Comment by oldman4U** [comment]
You can find the firmware from today here: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware.git

**Comment by oldman4U** [comment]
@ghost @JerksonS

Could you please let me know the status of the reported issue.

Thank you

**Comment by oldman4U** [comment]
Seems the user does not exist anymore. So it is about you @JerksonS. Have you been able to download the latest firmware and upload it to your TFT?

**Comment by JerksonS** [comment]
The issue seems to have self-resolved. I cant recall if I flashed since I last reported the issue. Let's consider it resolved :)

**Comment by oldman4U** [comment]
Thank you

Happy printing

JerksonS ***@***.***> schrieb am Fr. 26. März 2021 um 12:31:
