### ISSUE TITLE
[BUG] unable to revert z motor direction

### ISSUE THREAD

**Issue by Cadaxe20000** [bigtreetech/BIGTREETECH-TouchScreenFirmware#645]
After installing new trt firmware I am unable to revert z direction under the machine configuration. That function change the order of the buttons and nothing else

**Comment by oldman4U** [comment]
Hello Cadaxe20000.

I believe what you describe as a bug works exactly as intended. You will have to invert the movement of the axis in the firmware of your mainboard in Configuarion.h:

// Invert the stepper direction. Change (or reverse the motor connector) if an axis goes the wrong way.
#define INVERT_X_DIR false or true
#define INVERT_Y_DIR false or true
#define INVERT_Z_DIR false or true

Hope this helps

**Comment by oldman4U** [comment]
Hi.

Have you had time to check your firmware in the meantime?

Please let me know.

**Comment by oldman4U** [comment]
hi.

what is the status of the reported issue. It would be great, if you could close the ticket in case the issue is solved.

Thank you
