### ISSUE TITLE
[Q] Filament detector to TFT24

### ISSUE THREAD

**Issue by manukieli** [bigtreetech/BIGTREETECH-TouchScreenFirmware#646]
It's possible to mount a filament detector de the TFT24 model??
If yes, where it's posible to connect it??
Thank you.

**Comment by bigtreetech** [comment]
Hello, Because there is no extra GPIO, so cannot install any extensions on the TFT24.
If you do not use EXP-1 and EXP-2 (Marlin mode), you can install filament detector in here, but you need jumper and set IO used by filament detector in firmware
