### ISSUE TITLE
Second extruder and second Hot-End not displayed

### ISSUE THREAD

**Issue by evandene** [bigtreetech/BIGTREETECH-TouchScreenFirmware#65]
My TFT35 v2.0 doesn't show second extruder neither second Hot-End
My SKR Pro V1.1 is setup with two extruders and two hot ends but the second extruder neither the second hot-end do show up in the menu. (There are also no BMP ICONS for extruder 2 and hot-end 2)
If anyone could help me that would be great.
![TFT 35 configuration file](https://user-images.githubusercontent.com/8578321/66381160-0eeac800-e9b9-11e9-8885-ab64123b6297.JPG)

**Comment by evandene** [comment]
Help is need from @bigtreetech 
TFT35 2.0 is useless for printers with dual extruders / dual nozzles.
The touchscreen doesn't show any second tool or extruder

**Comment by dineshvyas** [comment]
it is worrking. try 
![teb](https://user-images.githubusercontent.com/55104840/66591194-06a8ad80-ebb0-11e9-9aae-359cadd7fa93.PNG)
number of icons may be fixed. i made new icon and uploaded but it messed up whole menu.

**Comment by evandene** [comment]
It is not working. See my picture in my comment above.
The touch screen does not allow me to operate the second extruder neither the second heater.

**Comment by evandene** [comment]
It's not possible to toggle to the second heater neither extruder. #bigtree is not capable for helping.
Is there someone who can help? See my pictures above.

**Comment by dineshvyas** [comment]
> It's not possible to toggle to the second heater , fans neither extruder with the existing firmware 2.0.23.
> @bigtreetech is not capable or not willing to help.
> Is there someone who can help? See my pictures above.

Would you like to compile my respiratory and try?

**Comment by evandene** [comment]
yeah would be great

**Comment by dineshvyas** [comment]
[BIGTREETECH-TouchScreen.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/3721531/BIGTREETECH-TouchScreen.zip)
compiled firmware name will be "BIQU_TFT35_APP1_V2.0.24.bin" I changed it to keep track of my changes.

**Comment by evandene** [comment]
Thanks for the firmware.
Next Tuesday, around noon I will be ready with my tests and will inform you

**Comment by evandene** [comment]
Test results beta firmware V2.0.24
Firmware virsion not updated in info screen
Only 1 Extruder is shown. Toggling to other extruder is not possible
Only 1 fan is shown.  Toggling to other fan is not possible
Only 1 Heater is shown.  Toggling to other heater is not possible
I stopped the test because of the results. see pictures and movie
Youtube link: https://youtu.be/h8i0jG3dw4k

![20191015_090521](https://user-images.githubusercontent.com/8578321/66810020-bb372c00-ef2e-11e9-9743-fc97c2f8f8fd.jpg)
![20191015_090645](https://user-images.githubusercontent.com/8578321/66810021-bbcfc280-ef2e-11e9-8cd3-6e9057105165.jpg)

**Comment by dineshvyas** [comment]
[BIQU_TFT35_APP1_V2.0.24.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/3729261/BIQU_TFT35_APP1_V2.0.24.zip)
it should work 100%

**Comment by evandene** [comment]
New test results
Sorry but I can only come up with exact the same results.
Not even the info screen is okay
I will not test anymore and will scrap the board

**Comment by evandene** [comment]
I close the comment

**Comment by dineshvyas** [comment]
I think firmware is not updated. you need to flash your TFT35 with bootloader with ST-Link.
this is the bootloader.
[BIQU_TFT35_V2.0_bootloader.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/3730813/BIQU_TFT35_V2.0_bootloader.zip)
This is the only working solution.
i am doing a video will upload within a day. stay tuned don't loose hope.

**Comment by evandene** [comment]
Do you have instructions how I need to flash the boot loader? I have a ST-link adapter

**Comment by oschwieger** [comment]
try to update the TFT using a really small SD Card. Like 2GB.
This worked for me, i updated 3.5 V2.0 and V3.0 and 2.4 V1.1 using an old SD Card that small and had immediate success on updating the firmware. Make sure its FAT formated.

**Comment by dineshvyas** [comment]
https://www.st.com/content/ccc/resource/technical/software/utility/51/c4/6a/b0/e2/0f/47/e5/stsw-link004.zip/files/stsw-link004.zip/_jcr_content/translations/en.stsw-link004.zip
download st-link utility and connect TFT35 v2.0 as in photographs
![20191023_001759](https://user-images.githubusercontent.com/55104840/67323622-5bddab00-f530-11e9-995a-35e8f00c3b66.jpg)
![20191023_001649](https://user-images.githubusercontent.com/55104840/67323651-68fa9a00-f530-11e9-83c1-f5e180ca0ce8.jpg)
![20191023_001846_LI](https://user-images.githubusercontent.com/55104840/67323676-70ba3e80-f530-11e9-8f46-e67d3ef33a18.jpg)
install st-link utility and click Target
![20191023_002643](https://user-images.githubusercontent.com/55104840/67323912-b2e38000-f530-11e9-87b5-5de35536d587.jpg)
click connect
![20191023_002204](https://user-images.githubusercontent.com/55104840/67324108-ec1bf000-f530-11e9-9045-990d3b3f77ee.jpg)
then
Again click target then click Erase Chip
click Ok
click flie 
open file
browse BIQU_TFT35_V2.0_bootloader.zip
click Traget
then Click Program & Verify
do not change anything on prompt and click Start
within few second bootloader will be flashed.
![20191023_003540](https://user-images.githubusercontent.com/55104840/67325045-2043e080-f532-11e9-8d1d-43f25f0598ec.jpg)
and your TFT35 V2.0 screen will look like this.
![Annotation 2019-10-23 011252](https://user-images.githubusercontent.com/55104840/67325183-600ac800-f532-11e9-8248-abcd652843ff.png)
then flash firmware by SDCARD.
it should work 100%

**Comment by guruathwal** [comment]
The TFT35 v2 does not update through sd card.
It can only be updated through flashing via serial TTL or StLink utility. If you don not have STLINK you can flash firmware through Serial with any USB to TTL Converter using STM32 FLASHER here: https://www.st.com/en/development-tools/flasher-stm32.html
Put the board in bootloader mode and then flash the firmware at address: 8003000

**Comment by evandene** [comment]
Done

**Comment by carlray5522** [comment]
> My TFT35 v2.0 doesn't show second extruder neither second Hot-End
> My SKR Pro V1.1 is setup with two extruders and two hot ends but the second extruder neither the second hot-end do show up in the menu. (There are also no BMP ICONS for extruder 2 and hot-end 2)
> If anyone could help me that would be great.
> ![TFT 35 configuration file](https://user-images.githubusercontent.com/8578321/66381160-0eeac800-e9b9-11e9-8885-ab64123b6297.JPG)

Hello can you please tell me if you ever got the tft35 v2.0 working with dual extrusion?

**Comment by Charly333** [comment]
got the same issue with GTR and M5 board. Won´t swap extruders nor fans. but does accept updates, for many new features could be implemented and uploaded.

Anyone solved the problem meanwhile?

**Comment by przepka1985** [comment]
> [BIGTREETECH-TouchScreen.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/3721531/BIGTREETECH-TouchScreen.zip)
> compiled firmware name will be "BIQU_TFT35_APP1_V2.0.24.bin" I changed it to keep track of my changes.
> i am trying to add ICON amd LABEL for 2nd Extruder.

Hi. Can i get one for 1 mixing extruder with 3 steppers?
