### ISSUE TITLE
Onboard Sd print not working even after enabling it in settings

### ISSUE THREAD

**Issue by tanellaanemagi** [bigtreetech/BIGTREETECH-TouchScreenFirmware#655]
Onboard Sd print not showing up even after enabling it in settings. also send cancel g code not working.

**Comment by radek8** [comment]
91/5000
You need to download the latest Marlin 2.0 with bug fixes, to support printing from SD oboard

**Comment by tanellaanemagi** [comment]
i have skr mini 1.2 with marlin 2.0 and it worked with previous firmware because there was no   "infoMachineSettings.onboard_sd_support"  it seems like this code doesent read this value or something with that, same problem is with   "infoSettings.send_cancel_gcode "
in previous version this also worked.

**Comment by radek8** [comment]
Yes you're right.
It used to work, now you have to upload a new MARLIN

Look at CONFIGURATION.H, line 240 :-)

Starting from Marlin Bugfix 2.0.x Distribution Date: 2020-04-27 & above, The TFT will auto detect

**Comment by rozenrod** [comment]
I downloaded the version of marlin on 05/03/20, in the Configuration_adv.h on line 1209 I registered #define SDCARD_CONNECTION ONBOARD, I reshooted it, but the screen displays an error M21

**Comment by tanellaanemagi** [comment]
i´m using marlin 2.0.5.3

**Comment by tanellaanemagi** [comment]
![image](https://user-images.githubusercontent.com/64858396/81110997-0b0a2e80-8f25-11ea-9560-cc813f6c63de.png)
 this seemed to me to be in wrong place

**Comment by radek8** [comment]
> Verze marlin jsem stáhl dne 05/03/2012, v Configuration_adv.h na lince 1209 jsem zaregistroval #define SDCARD_CONNECTION ONBOARD, změnil jsem to, ale na obrazovce se objeví chyba M21

2012 :-) 
You downloaded Marlin - Latest release, or Marlin 2.0 with bug fixes?
You have to download Marlin 2.0 with bug fixes

**Comment by tanellaanemagi** [comment]
I downloaded latest from bigtreetech for skr mini 1.2 e3.

**Comment by radek8** [comment]
> ![obraz](https://user-images.githubusercontent.com/64858396/81110997-0b0a2e80-8f25-11ea-9560-cc813f6c63de.png)
> zdálo se mi, že je na špatném místě, komentoval jsem to a dal tam, kde si myslím, že by to mělo být.
> pak jsem dostal toto místo, kde by měl být tisk sd, ale žádná ikona tam,

download new Marlin 2.0 with bug fixes

**Comment by rozenrod** [comment]
> > Verze marlin jsem stáhl dne 05/03/2012, v Configuration_adv.h na lince 1209 jsem zaregistroval #define SDCARD_CONNECTION ONBOARD, změnil jsem to, ale na obrazovce se objeví chyba M21
> 
> 2012 :-)
> Вы скачали Marlin - Последний выпуск или Marlin 2.0 с исправлениями ошибок?
> Вы должны скачать Marlin 2.0 с исправлениями ошибок

![Аннотация 2020-05-06 001611](https://user-images.githubusercontent.com/13519959/81116963-f763c580-8f2e-11ea-8bf3-763d71380724.png)

I downloaded the latest Marlin Bugfix 2.0.x, it was updated 13 hours ago

**Comment by radek8** [comment]
You need to enable LONG_FILENAME_HOST_SUPPORT in Marlin. 
Configuration_adv.h file

**Comment by rozenrod** [comment]
> Вам необходимо включить LONG_FILENAME_HOST_SUPPORT в Марлине.
> Файл config_adv.h

Did not help

**Comment by radek8** [comment]
You have enable  #define AUTO_REPORT_SD_STATUS ?

**Comment by rozenrod** [comment]
> Вы включили #define AUTO_REPORT_SD_STATUS?
Yes.
I used to turn on #define SD CARD CONNECTOR ONBOARD and my SD card didn’t open on my PC, I had to enter the M22 command, but now I get an error with the M21 and M22 commands

**Comment by rozenrod** [comment]
Here are my configurations
[Marlin.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4583759/Marlin.zip)

**Comment by radek8** [comment]
Stupid question, but I'll ask.
Do you have #define SDSUPPORT enabled in Configuration.h? :-)

![sd](https://user-images.githubusercontent.com/46979052/81119639-7951ef80-8f2b-11ea-95b5-53f15492361a.JPG)

**Comment by rozenrod** [comment]
it's just awful, with the new Marlin configuration, I forgot to uncomment #define SDSUPPORT!
Thanks a lot, now everything works)

**Comment by rozenrod** [comment]
Is there a way to upload files to an SD screen or board via Wi-Fi?

**Comment by tanellaanemagi** [comment]
i got this working also, i had latest regular build not bugfix.

**Comment by radek8** [comment]
> Is there a way to upload files to an SD screen or board via Wi-Fi?

It should work
I can try it tonight

**Comment by radek8** [comment]
> Existuje způsob, jak nahrávat soubory na obrazovku SD nebo na kartu přes Wi-Fi?

Copy ended in error, wait for merge
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/648

**Comment by oldman4U** [comment]
648 has been added 4 months ago. What is the status of the reported issue?

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
