### ISSUE TITLE
M109 / M190 workaround when using  TFT SD

### ISSUE THREAD

**Issue by FSUwelder1212** [bigtreetech/BIGTREETECH-TouchScreenFirmware#658]
I'm fairly certain the M109 / M190 when printing from TFT SD issue is a pretty well known bug with the firmware. However, I am wondering if anyone has found a workaround for this that I could implement in my start G code? I have tried numerous things including changing the sequencing of the start G code, adding M400 commands, adding G4 commands of various durations to no avail. Unfortunately, It makes printing from the TFT SD useless for me until I can find a fix.

**Comment by radek8** [comment]
should be corrected in
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/670
