### ISSUE TITLE
Print is done, I press "OK", the head rapidly.....

### ISSUE THREAD

**Issue by REDxFROG** [bigtreetech/BIGTREETECH-TouchScreenFirmware#66]
So when a print is done, the printer does the end-gcode. Just like normal.

But the TFT asks to press OK. I think it says "waiting for M31" "OK"  ?

So when I press "OK", the printer rapidly starts to move close to 0, 0 , 10 (?). But it's not homing.
The Z axis moved down very quickly (over 100mm down), I was afraid it would crash down but it stopped early enough. Not by Z endstop but somewhere in mid air.

I guess the stepper motors do not deactive ? How would it know to stop?

And why does it do this anyways? If you forget to remove the printed massive object and press Ok: say goodbye to your object and maybe even printer.

**Comment by Juju-Dudu** [comment]
Hello !

Have you check your gcode file ? Perhaps, at the end, there's some unnecessary commands...
