### ISSUE TITLE
[BUG] Wrong labels for preheat buttons

### ISSUE THREAD

**Issue by creamywhite** [bigtreetech/BIGTREETECH-TouchScreenFirmware#664]
The labels for preheat buttons (under Menu - Heat/Fan - Preheat) are wrong. Instead of displaying proper values from PREHEAT_LABELS in Configuration.h, wrong text is displayed. For PLA and PETG buttons it looks like PRINT_END_GCODE and PRINT_CANCEL_GCODE values, and for ABS it's ST7920_BANNER_TEXT.

**Comment by guruathwal** [comment]
Try recompiling the firmware and reloading the config file.

**Comment by creamywhite** [comment]
Huh, that helped. Thanks.
