### ISSUE TITLE
I found two bugs in the new firmware

### ISSUE THREAD

**Issue by AntoszHUN** [bigtreetech/BIGTREETECH-TouchScreenFirmware#668]
One major error is turning on the ST7920_SHOW_BANNER option, typing ST7920_BANNER_TEXT instead of displaying "AnRap 8 alpha", PRINT_START_GCODE is displayed showing G28 XY R10. So something was really spoiled here.
![IMG_20200509_112534](https://user-images.githubusercontent.com/45710979/81470125-4b013800-91e9-11ea-971f-39876ecbad63.jpg)

The next mistake is a mystery to me. In the menu shown in the picture, the option for 2 options is incomprehensible. LCD brightness and LCD dimming are incomprehensible.
![IMG_20200509_112613](https://user-images.githubusercontent.com/45710979/81470145-797f1300-91e9-11ea-8e67-a73c2fb693a5.jpg)
![IMG_20200509_112632](https://user-images.githubusercontent.com/45710979/81470201-d975b980-91e9-11ea-8798-5616d9d21061.jpg)
![IMG_20200509_112640](https://user-images.githubusercontent.com/45710979/81470224-f6aa8800-91e9-11ea-8894-ceaad194d400.jpg)
![IMG_20200509_112657](https://user-images.githubusercontent.com/45710979/81470237-01651d00-91ea-11ea-98dc-1445553ea16d.jpg)

I discovered another bug. That's very annoying.
![IMG_20200509_133805](https://user-images.githubusercontent.com/45710979/81472849-bbfd1b80-91fa-11ea-8f63-19c83950869a.jpg)

Thanks for the reply and correction as soon as possible!

**Comment by Talha909** [comment]
i have the same issue

**Comment by AntoszHUN** [comment]
Are these mistakes for you too?

**Comment by Mistigris18** [comment]
Moi aussi 😞

**Comment by guruathwal** [comment]
Similar to issue #664 . Try recompiling and flashing the firmware and reloading the config file.

**Comment by AntoszHUN** [comment]
I'm already over it. Nothing has changed. I'd rather put the old firmware back.

**Comment by guruathwal** [comment]
did you flashed the icons and fonts also?? the address of icons and fonts was changed after this firmware update.

**Comment by guruathwal** [comment]
I have encountered the preheat name error. after re-uploading the config file it was fixed.

**Comment by AntoszHUN** [comment]
I updated everything. All files are in place and up to date. If I don't update and only translate the downloaded version, that's the problem.

**Comment by guruathwal** [comment]
ok .. let me check

**Comment by AntoszHUN** [comment]
All right.

**Comment by guruathwal** [comment]
I checked but I  was unable to replicate the ST7920_BANNER_TEXT error. 
you should re-load the config file. you should see update progress if the config file is detected by the TFT.

**Comment by AntoszHUN** [comment]
I just don't understand. I downloaded the firmware. I didn't change anything in it. I translated it to TFT35 V3.0 display. I installed. This is a mistake. Could Marlin 2.0.5.3 bother you?

**Comment by iMike78** [comment]
We agreed that on fb, couldn't be the Marlin, as I have the same version, but the TFT35_E3_v3, and everything is working just perfect here.

**Comment by guruathwal** [comment]
Because the new TFT firmware detects onboard SDcard if it receives `Cap:SDCARD:1` from Marlin firmware.
which is currently only available in the Marlin bugfix branch. it is yet to be merged in Marlin Release branch

**Comment by guruathwal** [comment]
@AntoszHUN  can you try re-uploading the config file? 
TFT35_V3 and TFT35_E3_v3 are both the same. the TFT35_E3_v3 only have an extra knob light.

**Comment by iMike78** [comment]
Here are the pics to prove that the TFT35_E3_v3 is working fine with Marlin 2.0.5.3
![IMG_20200509_154213 1](https://user-images.githubusercontent.com/48806033/81478198-a9dba700-9213-11ea-8448-273683aa079b.jpg)
![IMG_20200509_164036 1](https://user-images.githubusercontent.com/48806033/81478229-e27b8080-9213-11ea-9748-7531975cc4d0.jpg)
![IMG_20200509_164046 1](https://user-images.githubusercontent.com/48806033/81478245-ead3bb80-9213-11ea-9d8c-8a8fbe03bcb4.jpg)
![IMG_20200509_164259 1](https://user-images.githubusercontent.com/48806033/81478299-4736db00-9214-11ea-870a-f18ad166bd7a.jpg)

**Comment by AntoszHUN** [comment]
Okay. I don't have time for that. Then next time if the bug is fixed I will use it. Obviously, I’m not the unlucky one if more people have this mistake.

**Comment by rebel1** [comment]
> One major error is turning on the ST7920_SHOW_BANNER option, typing ST7920_BANNER_TEXT instead of displaying "AnRap 8 alpha", PRINT_START_GCODE is displayed showing G28 XY R10. So something was really spoiled here.
> ![IMG_20200509_112534](https://user-images.githubusercontent.com/45710979/81470125-4b013800-91e9-11ea-971f-39876ecbad63.jpg)
> 
> The next mistake is a mystery to me. In the menu shown in the picture, the option for 2 options is incomprehensible. LCD brightness and LCD dimming are incomprehensible.
> ![IMG_20200509_112613](https://user-images.githubusercontent.com/45710979/81470145-797f1300-91e9-11ea-8e67-a73c2fb693a5.jpg)
> ![IMG_20200509_112632](https://user-images.githubusercontent.com/45710979/81470201-d975b980-91e9-11ea-8798-5616d9d21061.jpg)
> ![IMG_20200509_112640](https://user-images.githubusercontent.com/45710979/81470224-f6aa8800-91e9-11ea-8894-ceaad194d400.jpg)
> ![IMG_20200509_112657](https://user-images.githubusercontent.com/45710979/81470237-01651d00-91ea-11ea-98dc-1445553ea16d.jpg)
> 
> I discovered another bug. That's very annoying.
> ![IMG_20200509_133805](https://user-images.githubusercontent.com/45710979/81472849-bbfd1b80-91fa-11ea-8f63-19c83950869a.jpg)
> 
> Thanks for the reply and correction as soon as possible!

I have absolutely the same bugs on my TFT35_V3.0 as you. I reflashed everthing and loaded a config.ini on the display, but these two bugs does never change here.

**Comment by AntoszHUN** [comment]
I hope it will be remedied soon. I've tried everything. No changes.

**Comment by rightawy** [comment]
Reloading the config.ini on TFT fixes it.

**Comment by guruathwal** [comment]
Last night I pushed some changes in PR #663 . Can you check if it helps?

**Comment by AntoszHUN** [comment]
How can I download it?

**Comment by SonBroku** [comment]
> 
> 
> Last night I pushed some changes in PR #663 . Can you check if it helps?

I installed your branch, and there's still the bug where the lcd dim settings are unreadable. Other than that, I can't find any other issues. The bug with the LCD simulator mode banner seems to be fixed. I am getting the firmware yelling at me about no bed leveling data stored, but I think I just need to run a bed level routine.

**Comment by guruathwal** [comment]
@SonBroku 
>and there's still the bug where the lcd dim settings are unreadable.

can you give more detail?

**Comment by SonBroku** [comment]
> 
> 
> @SonBroku
> 
> > and there's still the bug where the lcd dim settings are unreadable.
> 
> can you give more detail?

Yeah, in the "Feature" settings menu, the settings "LCD brightness," and "LCD Brightness Dim," are both showing nonsense characters. They start out as a 4 with a box next to them, and once changed they just become an empty character with no way to know that the setting is currently set to without counting the amount you click them. In the OP message he has a picture of exactly what I'm talking about. It does this no matter how many times I re-flash or reload the config.ini and I can't seem to find a configuration where this doesn't happen.  I am using the most current marlin bugfix branch. I can't speak to if this is happening on the stable branch, although this seems like a bug with the touchscreen firmware and not marlin.

**Comment by guruathwal** [comment]
@SonBroku try reset settings

**Comment by AntoszHUN** [comment]
I realized it had nothing to do with Marlin. I removed the connectors from the motherboard. I reinstalled the firmware on the display. I just gave him electricity. Even so, this is a mistake.

@SonBroku
It doesn't belong here.
What is your version of Marlin? Because I am using version 2.0.5.3. But can bugfix 2.0.x be fresher?

**Comment by AntoszHUN** [comment]
@guruathwal 
I've already restored everything. It wasn't good either.

**Comment by guruathwal** [comment]
@AntoszHUN  did you tried the #663 ?
@SonBroku  reported that it fixed the issue you are facing.

**Comment by SonBroku** [comment]
@guruathwal 
Resetting the settings does nothing, It still shows the same gibbirish. This bug doesn't occur with the pre-compiled 26.1 binary.

@AntoszHUN 
I'm using the most current version of the bugfix branch. I wouldn't recommend using the bugfix branch unless you're ok with having potential issues with marlin itself. I'm almost 100% sure this weird menu bug has nothing to do with marlin though. Try downloading and compiling his branch to fix the weird issue with the LCD simulator though, it DOES fix that bug.

**Comment by AntoszHUN** [comment]
@guruathwal How do I try it? Not in the firmware.

**Comment by AntoszHUN** [comment]
Oh, of course, I can copy it. I'm stupid.

**Comment by AntoszHUN** [comment]
@SonBroku I understand. Thanks. Then I drop version 2.0.5.3. I'm reverting to bugfix 2.0.x.

**Comment by SonBroku** [comment]
@AntoszHUN Clone his branch of the tft firmware here and compile/flash it:
 https://github.com/guruathwal/BIGTREETECH-TouchScreenFirmware/tree/Mainstream

That will fix the bug with the LCD simulator banner text, at the very least. The LCD Dim settings issue seems to be still there. It has yet to be merged into the master branch, but it DOES fix that bug.

**Comment by AntoszHUN** [comment]
@guruathwal An error was resolved thanks to # 663.
![IMG_20200510_084952](https://user-images.githubusercontent.com/45710979/81492856-b0156600-929b-11ea-80ae-932d91681691.jpg)

De a fényerő és a halványítás még mindig nem jó.
![IMG_20200510_085013](https://user-images.githubusercontent.com/45710979/81492875-ece15d00-929b-11ea-9e07-f01a7afea3c2.jpg)
![IMG_20200510_085020](https://user-images.githubusercontent.com/45710979/81492880-f79bf200-929b-11ea-96e4-3609b111fdf8.jpg)

**Comment by guruathwal** [comment]
Pushed another commit to resolve the issue. please check and revert.

**Comment by SonBroku** [comment]
@guruathwal Yep, that fixed it. Cool

**Comment by AntoszHUN** [comment]
Thank you Master! This error has also been fixed! Thanks! Thanks! Very good!

Can I close the topic?
![IMG_20200510_110138 1](https://user-images.githubusercontent.com/45710979/81495066-cf1cf380-92ad-11ea-974a-ee6fa649e81d.jpg)
