### ISSUE TITLE
no onboardsd

### ISSUE THREAD

**Issue by Mellux** [bigtreetech/BIGTREETECH-TouchScreenFirmware#669]
**Your question or details you need. Please describe.**
A clear and concise question or detail you would like to ask. Like Hardware related or firmware related.

**specify the device variant related to your question.**

**Additional context**
Add any other context or screenshots about the question here.
hi, because when I compile the fw of my tft35 e3 v3 I don't see the icon of the sd card onboard, what do I have to activate in the firmware to have
![nooboardsd](https://user-images.githubusercontent.com/7335658/81474878-92e38780-9208-11ea-8ec8-dfdd4e00994e.jpg)

**Comment by guruathwal** [comment]
you need to enable SD card in Marlin firmware

**Comment by Mellux** [comment]
on the firmware of the mainboard is enabled, if I put the fw stock of the display the sd onboard appears but if I compile it I am not there

**Comment by AntoszHUN** [comment]
It's on with me. Still, this is a mistake. I don't see the motherboard SD card either.

**Comment by guruathwal** [comment]
you also need to update marlin firmware to latest bugfix 2.0x

**Comment by AntoszHUN** [comment]
It's not up to me. I am using version 2.0.5.3 Marlin.

**Comment by guruathwal** [comment]
SDCard reporting in the Marlin firmware is currently not yet merged in the release branch https://github.com/MarlinFirmware/Marlin/pull/17208
You will have to use the Marlin bugfix branch [here](https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x) until it is merged or you can use the Release branch of TFT firmware [here](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/tree/release-xx.26.1).

**Comment by AntoszHUN** [comment]
Is it better to use bugfix 2.0.x? Don't use version 2.0.5.3?

**Comment by guruathwal** [comment]
The new TFT firmware detects onboard SDcard if it receives Cap:SDCARD:1 from Marlin firmware.
which is currently only available in the Marlin bugfix branch. it is yet to be merged in Marlin Release branch.

It is up to you to decide which is better.

**Comment by AntoszHUN** [comment]
I understand. Obviously, based on version number, one thinks version 2.0.5.3 is fresher. But it looks like bugfix 2.0.x is much fresher. Then we'll get back to that. I don't even understand why you have to put up the semi-finished version. I need a fix pack and a bugfix. I would only skip the version number if I was sure the firmware was good. So the version numbers are now a bit misleading.

**Comment by Mellux** [comment]
thank you very much, I put the bugfix version and the sdonboard is back

**Comment by AntoszHUN** [comment]
This proves that 2.0.5.3 is not newer than bugfix 2.0.x. So the bigger version number is meaningless! Pls closed. Solved for me too!

**Comment by guruathwal** [comment]
@AntoszHUN 
To be clear you are currently using the bugfix/dev branch of the TFT firmware, it is just named `master` as BTT has not renamed it. 
bugfix branches are always unfinished.
If you want a finished version, then use the release branch.

@Msq001 I recommend renaming the `master` branch to `dev` or `bugfix` branch to remove the confusion.

**Comment by AntoszHUN** [comment]
I understand.

**Comment by cwizard** [comment]
Can Confirm using Marlin Bugfix branch with TFT "Master" branch gives me print from onboard SD functionality again.

**Comment by oldman4U** [comment]
Hi.

For me the versioning system is unclear too, but you can see for every version how many commits each version is behind or ahead of another release and you can see which functions the commits are related to.

This means more for me than a release number and allows to download a specific release.

![Screenshot 2020-05-09 at 23 36 30](https://user-images.githubusercontent.com/54359396/81485523-fa6ff600-924d-11ea-858a-3c6ed7a331e0.png)
![Screenshot 2020-05-09 at 23 36 16](https://user-images.githubusercontent.com/54359396/81485527-fc39b980-924d-11ea-8cc7-d91274358536.png)
![Screenshot 2020-05-09 at 23 35 54](https://user-images.githubusercontent.com/54359396/81485529-fcd25000-924d-11ea-8ac2-3aa60ae2059e.png)

**Comment by AntoszHUN** [comment]
I always update the Master branch. The Hungarian language and what I do. Everything goes to the Master branch.

**Comment by oldman4U** [comment]
Hello Mellux.

Could you please close this ticket.

Thank you
