### ISSUE TITLE
[FR] Separation between banner and 12864 info

### ISSUE THREAD

**Issue by zillarob** [bigtreetech/BIGTREETECH-TouchScreenFirmware#671]
The banner sits right on top of the 12864 display with the adjacent pixels touching.

Kinda looked funny so added this to give them a little separation.
I dont know enough about this stuff to know if this is a good or bad way of going about it, but seems to work.

Moving YSTART for the 12864 info down a lil might be better, but I havent found that yet.

![ysep](https://user-images.githubusercontent.com/42916376/81480693-3cbb1800-91f9-11ea-84c5-331c63607d37.JPG)

Changed
SIMULATOR_YSTART ((LCD_HEIGHT - PIXEL_YSIZE*LCD_YROWS) / 2)

To
SIMULATOR_YSTART ((LCD_HEIGHT - PIXEL_YSIZE*LCD_YROWS) / 2 - 2)

**Comment by zillarob** [comment]
Found the one for y start on the 12864 part and like it better.
Adding +8 to it gets it down to the bottom more and away from the banner.

A conditional might be nice, like
ifdef ST7920_BANNER_TEXT
+8 to shift it down toward the bottom more
else
+0 to have the screen centered like normal

![ycord](https://user-images.githubusercontent.com/42916376/81514278-36fa2b00-92fc-11ea-8155-bbf213cc393b.JPG)

**Comment by zillarob** [comment]
Here is a pic. Normally the banner would be sitting right on top of the temp, and touching it.

![20200510_203527](https://user-images.githubusercontent.com/42916376/81514636-31054980-92fe-11ea-9ef5-411b856a8920.jpg)

**Comment by oldman4U** [comment]
Seems like this problem is solved. 

Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
@zillarob 

Please close this ticket.
