### ISSUE TITLE
When encoder used in touch mode to adjust values, feed rate changes as well.

### ISSUE THREAD

**Issue by SonBroku** [bigtreetech/BIGTREETECH-TouchScreenFirmware#680]
As the title says. I have noticed that If I use the encoder knob to adjust values such as the fan speed in menus in the touch screen mode, it's also cranking the feed rate up and down. So say I crank my fan up from 0 to 100% in the touch menu, if I then go back to LCD mode, the FR will show as something like 175%. It seems like the encoder is being passed to marlin regardless of which mode the screen is in.

EDIT: In fact, it adjusts the feed rate in touch mode too, regardless of what menu I'm in. If I turn the encoder on any menu, then back out to the main touch screen menu, the feed rate has been cranked up, regardless of what I was using it for. I like to use the encoder to move the axis quickly so this is annoying.

**Comment by guruathwal** [comment]
This is because the encoder wheel is hard wired to the EXP ports and the mainboard is also reading the encoder status all the time.
With those clicking and rotating of the encoder wheel in touch mode, the mainboard might end up in serious damage to the machine, like heating being enabled, increase temperature, or accidentally moving any axis.

**Comment by creamywhite** [comment]
Then it seems like a major hardware design oversight to me. I guess MOSFETs should've been used on encoder's VCC or GND lines to disable its operation when the TFT is used in Touch mode.

**Comment by SonBroku** [comment]
Okay so using the encoder to adjust values in touch mode is a no go because it's got a direct connection to the printer through the EXP connection. That does seem like a bit of an oversight, but using the encoder to change values in touch mode isn't exactly necessary, I'm just used to it coming from the stock ender 3 LCD. I find myself using LCD simulation more than the touch mode because I'm so used to It.

**Comment by SonBroku** [comment]
I guess I'll close the issue as it seems to be an inherent hardware limitation of the board. Oh well.

**Comment by radek8** [comment]
Hi
I found a solution to this problem
add a line wherever the encoder is used and where I do not want it to change the feed rate

sendEncoder (2);

![image](https://user-images.githubusercontent.com/46979052/81864443-ef2e0a80-956c-11ea-85ad-d52cc9476138.png)
