### ISSUE TITLE
[FR] IDEA: Iconpack 'The Round Miracle' - Update for SW v26.1

### ISSUE THREAD

**Issue by Acenotass** [bigtreetech/BIGTREETECH-TouchScreenFirmware#681]
Updated, already liked by you the iconpack 'The Round Miracle'!

![26 1](https://user-images.githubusercontent.com/44540957/81536401-4c6b6580-938d-11ea-9da5-ce8b65c72c5f.png)

[TFT24 Iconpack 'The Round Miracle' by Acenotass for v26.1.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4608152/TFT24.Iconpack.The.Round.Miracle.by.Acenotass.for.v26.1.zip)
[TFT28 Iconpack 'The Round Miracle' by Acenotass for v26.1.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4608153/TFT28.Iconpack.The.Round.Miracle.by.Acenotass.for.v26.1.zip)
[TFT35 Iconpack 'The Round Miracle' by Acenotass for v26.1.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4608154/TFT35.Iconpack.The.Round.Miracle.by.Acenotass.for.v26.1.zip)

**Comment by Kyosuke33** [comment]
Hello, i have an error with the TFT24 pack. It tell me than files are missing, and on the screen, the 3 first icone are missing.

**Comment by Kyosuke33** [comment]
![IMG_20200524_131218](https://user-images.githubusercontent.com/44751932/82752842-3a43eb00-9dc1-11ea-8cb1-56714e41b098.jpg)
![IMG_20200524_131216](https://user-images.githubusercontent.com/44751932/82752845-3d3edb80-9dc1-11ea-9701-9accca3b9e0b.jpg)

**Comment by Kyosuke33** [comment]
Statut bed too butni miss the picture.

**Comment by Kyosuke33** [comment]
Edit : i try with original firmware, same problem, so this is not about your pack. Thank you.

**Comment by Kyosuke33** [comment]
Edit : It's ok, it's because on the firmware they made a mistake on the name.

Status_Fan -> StatusFan
 Status_Bed -> StatusBed
 Status_Nozzle -> StatusNozzle

**Comment by oldman4U** [comment]
Hello acenotass.

I am using your theme on my printers and I really like what you did. It seems that there will be an extra bmp needed very soon, which shows the temp of the Nozzle and the Bed at the same time. Maybe you already know this - if not, attached is the standard bmp.

Thank you
[preheat.bmp.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4732456/preheat.bmp.zip)

**Comment by oldman4U** [comment]
Hi acenotass. 

The new software is out. It would be great if you could provide the missing preheat.bmp. Thank you

**Comment by Acenotass** [comment]
@oldman4U https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/832

**Comment by oldman4U** [comment]
Thank you!!!👍

**Comment by Acenotass** [comment]
New version
