### ISSUE TITLE
[BUG] LIGHTWEIGHT_UI not working correctly

### ISSUE THREAD

**Issue by tsndr** [bigtreetech/BIGTREETECH-TouchScreenFirmware#683]
### Description

I got my **BTT TFT3.5 E3 V3.0** today and i really like it, but in **Marlin Mode** it completely glitches out. After some tinkering i figured out that it happenes because of the `LIGHTWEIGHT_UI`, which I had enabled in my Marlin Firmware.

Can you please add support for `LIGHTWEIGHT_UI`? :)

### Steps to reproduce

1. Enable `LIGHTWEIGHT_UI` in `Configuration_Adv.h`
2. Plug in Display to Motherboard
3. Turn on Printer
4. Switch to Marlin Mode

**Expected behavior**
A readable UI

**Actual behavior**
Glitched out UI

### Hardware Variant
BTT TFT3.5 E3 V3.0
### TFT Firmware Version & Main Board Firmware details
- Creality Silent Board @ 2.5.0.2
- SKR Mini E3 V1.2 @ 2.5.0.2

#### Display
![IMG_0566](https://user-images.githubusercontent.com/2940127/81578481-281e8180-93ab-11ea-997e-1d3d2612a87e.jpg)

#### Creality Silent Board
[Configuration.h](https://pastebin.com/kcJEQgJM)
[Configuration_Adv.h](https://pastebin.com/MVm884bL)

#### SKR Mini E3 V1.2
[Configuration.h](https://pastebin.com/8KfksHQS)
[Configuration_Adv.h](https://pastebin.com/pJwWBNC0)

**Comment by bigtreetech** [comment]
LIGHTWEIGHT_UI use the same feature of ST7920 in #290. TFT has worked after #705, but not perfect
