### ISSUE TITLE
[FR] Set TMC hybrid treshold from the touch mode

### ISSUE THREAD

**Issue by DominikPalo** [bigtreetech/BIGTREETECH-TouchScreenFirmware#697]
**Is your feature request related to a problem? Please describe.**
When I want to adjust the hybrid threshold settings of my TMC drivers, I have to switch to the Marlin mode to achieve that. It would be great to have such an option also in the touch mode.

**Describe the solution you'd like**
Add a Hybrid Threshold submenu to touch UI (similar to the currents settings menu)

**Additional context**
How it looks in Marlin menu: https://youtu.be/3islPKDqcmw?t=21

**Comment by oldman4U** [comment]
Hello DominikPalo.

The TFT has a Terminal which allows to send gcode commands to the mainboard. As far as i know, this should also allow you to change the hybrid treshold.

Change the FW after that and save to EEPROM.

Please let me know if this works for you
