### ISSUE TITLE
Bed Size only support positive dimensions. 

### ISSUE THREAD

**Issue by delwinbest** [bigtreetech/BIGTREETECH-TouchScreenFirmware#698]
Hi Team,

Previously in Configuration.h, one could specify negative X and Y min values. For example, on my BIBO2, location 0;0 is in the middle of the bed, and my X and Y min is -100. This is what I needed to use for the touch screen bed leveling to work. 

The config.ini doesn't support negative values. Is this by design? How would I handle a bed which has -100 X-min and +100 X-max? 

Thank you!

https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/blob/56f904000f16f972a5a5ed3b5bfb121fac739023/TFT/src/User/config.ini#L144

**Comment by oldman4U** [comment]
Hello Guru.

I believe delwinbest only gets a notification in case someone writes an answer.

@delwinbest We have a real Guru here, fixing bugs faster than the wind and even new functions only take a second longer. Could you please try guruathwals mainstream brunch to see if it solves your problem: https://github.com/guruathwal/BIGTREETECH-TouchScreenFirmware/commits/Mainstream

Thank you Guru
