### ISSUE TITLE
Bigtreetech SKR E3-DIP v1.1 and Bigtreetech TFT24-v.1.1

### ISSUE THREAD

**Issue by YapCK45** [bigtreetech/BIGTREETECH-TouchScreenFirmware#700]
I bought a Bigtreetech SKR E3-DIP v1.1 and Bigtreetech TFT24-v.1.1. According to the documentation it should be fairly straight forward to get them to work. I connected them as in the photo below:
![IMG_5218](https://user-images.githubusercontent.com/64215797/82535933-3a05de80-9b7a-11ea-90cc-26fa6e45c472.jpg)
 
After powering up it shows the both marlin and touch mode:
![IMG_5219](https://user-images.githubusercontent.com/64215797/82536025-69b4e680-9b7a-11ea-8398-15cac81a6c7e.jpg)

But it does not respond to the rotary switch. I am new in this and would appreciate any advice and troubleshooting tips.

**Comment by YapCK45** [comment]
Checked with Creality 3D® 12864 LCD Display Screen and it works:
![IMG_5220](https://user-images.githubusercontent.com/64215797/82542547-c74e3080-9b84-11ea-9c04-7b0cab229ce4.jpg)

**Comment by radek8** [comment]
I assume you have a connector configured as EXP3 on the SKR-E3 board, but you are connected to the EXP1 connector on the TFT.
The connectors do not have the same pin layout. The encoder pins are in the EXP2 connector

**Comment by radek8** [comment]
Wrong display selection.
The TFT35-V3.0-E is a direct replacement for the Ender3 display

**Comment by YapCK45** [comment]
Would you be able to provide the pin connection for EXP1 connector on the TFT to the SKR-E3 board. I think that's what I need.
