### ISSUE TITLE
Button locations are incorrect after flashing

### ISSUE THREAD

**Issue by xxKeoxx** [bigtreetech/BIGTREETECH-TouchScreenFirmware#702]
I was running my Bigtree Tech TFT35 V3 with the screen flipped and flashed the newest firmware.  After flashing the newest firmware all of the icons appear to be in the correct place but the result of the icon press seems to be reversed.  For instance, the back function responds when I press the upper left icon when the actual back icon is located in the lower right.  I've tried to re-flash the previous version and it still has the same problem now.  I've tried to use the reset.txt file in the SD card root, but when I attempt to calibrate the touch screen it keeps saying failed please try again.

I am out of ideas on how to fix this.  Is there anyway to just reset everything on the screen so no firmware exists?

Or better yet, does anyone know how to fix this issue?

**Comment by oldman4U** [comment]
Hi.

I am running a TFT28 with flipped screen and it works, even the screen is flipped while upgrading the FW. Have you seen the flip option in the config.ini which has to be turned on (1).

Hope this helps

**Comment by oldman4U** [comment]
Hi @xxKeoxx.

What is the current status of the reported issue?

Please let us know

**Comment by xxKeoxx** [comment]
I am so sorry.  I thought I responded to this.  I am still having the issue but I was able to work around it.  So after I flashed the firmware all of the icons were correct but the actual button placement was upside down.  I had to try to navigate the menus upside down from memory.  Once I got to the menu I rotated the screen back to the original origin and then switched it back to the flipped origin.  After that it functioned as expected.

However, when I flashed the firmware again I still had the same problem that I initially reported.  If I flash the firmware with the screen in the upright orientation, everything works as expected.

**Comment by oldman4U** [comment]
I use a TFT28 flipped, so i can only speak for this kind of display. Updating the firmware, the screen is flipped during the update, but is correct after that. Have you tried to use Master Branch instead of v25.x and have you tried to edit the config.ini file, where you can activate the upside-down screen:

#### Rotate UI 180 degrees
# Options: [enable: 1, disable: 0]
rotate_ui:1

**Comment by oldman4U** [comment]
Hi.

Could you please close this ticket in case you do not need it anymore.

Thank you
