### ISSUE TITLE
TFT24 USB as COM port

### ISSUE THREAD

**Issue by edcasati** [bigtreetech/BIGTREETECH-TouchScreenFirmware#703]
Is there any easy way to get the TFT-24V1.1 to use the USB port as a COM port? I would like the display to output commands to the COM port instead of the cable connector, so the display can be used stand alone as an interface to a CNC machine that is driven by a Raspberry PI.
Basically the TFT24 would act like a remote keyboard, sending text strings out through the USB port when a screen key is pressed.

**Comment by bigtreetech** [comment]
Hello, this requires TFT24 as a USB host to communicate with the motherboard, but STM32F103 USB of TFT24 can only be used as a slave, so this is impossible.
