### ISSUE TITLE
[FR] (feature request title)

### ISSUE THREAD

**Issue by Lino77** [bigtreetech/BIGTREETECH-TouchScreenFirmware#707]
it is possible to display the camper temp and pinda temp on the tft

**Comment by oldman4U** [comment]
Hi lino77. 

I believe it would be good to edit the title of this ticket. The current one is useless. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
