### ISSUE TITLE
Window "Processing" with confirmation

### ISSUE THREAD

**Issue by GenaUser** [bigtreetech/BIGTREETECH-TouchScreenFirmware#72]
I use a TFT35 V3
Is it possible to deactivate the processing window during the printing process?
It's activated at the homing process, but also with every head change.
In multi-material printing, this window permanently hides printing information.

Another request : is it possible to display the temperature of the 2 heads during printing and Z position?

Thanks,

(Good job for the V0.24 improvements)

**Comment by bigtreetech** [comment]
These are achieved in the last version, so close here
