### ISSUE TITLE
[BUG] Config.ini for TFT35_V3.0.26.1 not able to update

### ISSUE THREAD

**Issue by winnainglin** [bigtreetech/BIGTREETECH-TouchScreenFirmware#722]
### Description
config.ini has no response to version 26.1

### Hardware Variant
TFT35_V3.0

### TFT Firmware Version & Main Board Firmware details
V26.1, Marlin 2.0.x

**Comment by oldman4U** [comment]
Hello winnainglin.

Like the Tiger already wrote, Config.INI is supported with the Master branch, but not with v26.1. It would be great if you could test Master and CLOSE this ticket.

Thank you
