### ISSUE TITLE
Update with config.ini

### ISSUE THREAD

**Issue by Kyosuke33** [bigtreetech/BIGTREETECH-TouchScreenFirmware#724]
Hello, i try to update my tft24 with the config.mini file, but nothing happen.
I open config.ini with Visual Studio Code, i change what i need ( printer size and probe points), i copy the config.ini on my SD carte formated with FAT32, put the SD card in the printer, plu in and nothing happen, i got the statut screen but the config doesn't change.
I use the latest firmware.
Any idea ? Thank you.

**Comment by Tygrys-1** [comment]
What software version on TFT?
Which slot you put SD card in?

**Comment by Kyosuke33** [comment]
TFT24 1.1 with 26.1 firmware.
I put the SD card on the SD card port of the screen.
I just see one other guy with this problem two message below mine.

**Comment by Tygrys-1** [comment]
Initial release of 26.1 (the one you can find in the "Copy to SD folder") does not have ability to use config.ini, so you must build your own firmware from the master branch.

**Comment by Kyosuke33** [comment]
OK :'(

**Comment by oldman4U** [comment]
Hi Kyosuke33.

Could you please close this ticket as it is not needed any more.

Thank you
