### ISSUE TITLE
[FR] (Simplified Status Screen while Printing)

### ISSUE THREAD

**Issue by gordo3di** [bigtreetech/BIGTREETECH-TouchScreenFirmware#732]
So far we love the Unified Menu status screen while printing, however would it be possible to implement a very simple screen that appears after "x" seconds. Basically just showing name of file, percentage complete and maybe time all with very big text on a black screen. This way you can see basic info from far away. This would be super useful for people with multiple printers. Also the persistent hotend and bed temp could still be on top.

Things like FR, Fan, Temp, Layer height, Pause, Babystep, More and Stop aren't really important while printing unless something goes wrong.

Then if you touch the screen it would immediately go back to the normal status screen and wait for the new countdown...

Just a thought. I'd love to program it however I think you would spend more time fixing my code than anything... How can I help?

![status-screen_idea_200530](https://user-images.githubusercontent.com/11464057/83334415-63a6c000-a274-11ea-9d63-14abbe909542.jpg)

**Comment by oldman4U** [comment]
Hello gordo3di.

I believe this would be a good idea, but based on the current font used for the UI this could look ugly: But you would like to see the attributes shown in your screenshot, where the Progress is available twice and therefore is redundant.
![Font](https://user-images.githubusercontent.com/54359396/84637482-08243580-aef6-11ea-9d43-6369b7594ce5.png)

**Comment by gordo3di** [comment]
That makes sense. We were just looking for something we could easily see from far away and take away stuff that doesn't matter for general printing. I take it scaling fonts doesn't really work?

**Comment by oldman4U** [comment]
What if it would be possible to improve the readability of the whole UI?

Such a simple status screen, how would you activate it? Automatically after xsec the print started or manually by pressing a button on the interface?

**Comment by oldman4U** [comment]
Sorry....

As far as i know you need an additional, bigger font. And space is limited - as usual.

**Comment by gordo3di** [comment]
> What if it would be possible to improve the readability of the whole UI?
> 
> Such a simple status screen, how would you activate it? Automatically after xsec the print started or manually by pressing a button on the interface?

Our thought was to have it appear after x seconds kind of like a screen saver. Currently our printing screen looks like the attached image.

![IMG_20200617_114654](https://user-images.githubusercontent.com/11464057/84946489-d0b0b700-b0b6-11ea-908a-811a7f56f008.jpg)

It works but sometimes it hard to see the progress at a fast glance especially if you have many printers running.

Thanks for the input

**Comment by oldman4U** [comment]
I completely understand the function and readability is an issue with the current screen. Hope we will see such a WhilePrinting screen in firmware soon.

**Comment by oldman4U** [comment]
Hello gordo3di.

Could you please be so kind and close this ticket. Your feature request is covered in the pinned Feature Request ticket #1177 

Thank you

**Comment by gordo3di** [comment]
@oldman4U whoops forgot it was open. I made some headway on it but not enough to be useful.

**Comment by oldman4U** [comment]
My design for your requested feature. Hope you like it😁

gordo3di <notifications@github.com> schrieb am Di. 20. Okt. 2020 um 23:12:

**Comment by oldman4U** [comment]
Just saw that there was no attachment.... Sorry


[Gordo.pdf](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5497916/Gordo.pdf)

**Comment by gordo3di** [comment]
Ooohhhh!!! I like it.

**Comment by oldman4U** [comment]
[Gordo.pdf](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5497961/Gordo.pdf)

And this is with the correct lower bar...

**Comment by oldman4U** [comment]
It will come, but before there will be a VERY VERY cool Print Confirmation screen coming.

**Comment by gordo3di** [comment]
Awesome! I'm even more excited now... I'll try to figure out github
desktop. I want to help contribute too.

**Comment by oldman4U** [comment]
Hehe👍🏻

gordo3di <notifications@github.com> schrieb am Fr. 6. Nov. 2020 um 02:32:

> Awesome! I'm even more excited now... I'll try to figure out github
> desktop. I want to help contribute too.
>
