### ISSUE TITLE
[FR] (support HOST_ACTION_COMMANDS for Marlin)

### ISSUE THREAD

**Issue by dp250f** [bigtreetech/BIGTREETECH-TouchScreenFirmware#736]
In order to use Host mode instead of Marlin mode, HOST_ACTION_COMMANDS support is needed to accomplish filament change and other actions which require prompting.

If TouchScreenFirmware could support HOST_ACTION_COMMANDS, it would be much more functional.

Currently if you attempt an M600 (filament change) it unloads, then gets stuck in an echo: loop and never loads or continues printing. If you switch to Marlin mode at this point, you can see it's waiting for you to press the button to tell it you've loaded the new filament.

Thanks.

**Comment by dp250f** [comment]
This would also allow filament runout functionality without running filament runout wires to the screen.

**Comment by ETE-Design** [comment]
@dp250f  Seems to be possible with the right code.... https://www.youtube.com/watch?v=HJpfO8XifqI

**Comment by radek8** [comment]
https://github.com/PrintEngineering/MKSTFT28_Clone_Artillery-Sidewinder/tree/master/TFT/src/User

**Comment by bigtreetech** [comment]
Hello HOST_ACTION_COMMANDS  should be worked after https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/984
