### ISSUE TITLE
After reset calibration not working

### ISSUE THREAD

**Issue by tommygunn212** [bigtreetech/BIGTREETECH-TouchScreenFirmware#737]
After I load reset.txt the calibration screen comes up.
And asks please click on the red do it work for the first 3 dots.
The 4th a black dot com in the center.  Then I get adjustment failure. 

I can not get pas this no matter where I click. 

Tft 3.0

![79F487D4-54FF-470B-A957-AB7356714F39](https://user-images.githubusercontent.com/27671625/83364304-5c63dd00-a36e-11ea-96c6-2f76979f4445.jpeg)

Thanks!

**Comment by carl1961** [comment]
You try using a small pointed object to click with, if you're using your
finger and not pressing within the correct range , that could cause fail.

**Comment by tommygunn212** [comment]
14th try was the charm!
