### ISSUE TITLE
[BUG] TFT35 temper icon missing

### ISSUE THREAD

**Issue by poumsoon** [bigtreetech/BIGTREETECH-TouchScreenFirmware#741]
On the initial screen of tft35 V1.2.26.x, the temperature display icon is displayed in white. 
tft28 has been updated and revised on May 30th. But tft35 is still the same.
![KakaoTalk_20200601_203233994](https://user-images.githubusercontent.com/3367969/83406054-c9e43c00-a448-11ea-8c34-c5eabd43c33a.jpg)

**Comment by oldman4U** [comment]
Hi. Please use Master instead of 26.1.  to solve the known problem.

**Comment by oldman4U** [comment]
Hello poumsoon.

Any news regarding the reported issue? Please let us know.

Thank you

**Comment by poumsoon** [comment]
It works well.
Thank you.
