### ISSUE TITLE
Where i can find previous firmware.

### ISSUE THREAD

**Issue by Kyosuke33** [bigtreetech/BIGTREETECH-TouchScreenFirmware#742]
Hello, i just upgrade the firmware of my TFT35 from 26.1 to 26.x.
That corrects the problem of the wrong name icons and the config.ini problem to update new configuration.
But now when i turn on the printer, i have an error "Fade height OFF".
So i search for the 26.1 firmware to open it with VSC and compare it with the 26.X and find the error.
There is a place where the old firmware are saved ?
Thank you.

**Comment by Tygrys-1** [comment]
There is a branch named release_xx_26.1. you will find the files from 26.1, build about month ago.

You may also click on "commits" to see the history of changes and trace to the release 26.1 point.

Also, selecting a file from the repository and clicking a "History" button will show changes for that file.

When browsing commits you may use the "<>" button to view the repository at that stage.

**Comment by Kyosuke33** [comment]
Great Thank you !
