### ISSUE TITLE
BIGTREE_TFT24_V1.1.26. Touch screen not working after update. Marlin Mode also did not work.

### ISSUE THREAD

**Issue by Talha909** [bigtreetech/BIGTREETECH-TouchScreenFirmware#745]
I have SKR 1.4 Turbo with TFT 24 Touch Screen. I have updated the new software BIGTREE_TFT24_V1.1.26.x. I put the memeory card in the tft memory card slot after that. Update begin. After update touch screen alignment comes.  Accidentally i switch off the printer on that screen and did not perform the touch screen alignment. Now screen reboot and classics menu comes in-front of me.  Now the touch is not not working and printer not attached errors comes.  I press the nob and try to go marlin screen. But i put the on marlin screen and press the switch button but it do noting. Its on the marlin and classis menu screen. I cant able to to do nothing. Any suggestions please.

**Comment by oldman4U** [comment]
Hi.

Have you tried to flash the firmware again?

**Comment by Talha909** [comment]
I will check it todsay

**Comment by radek8** [comment]
Insert the reset.txt file on the SD card and restart the display. The display touch calibration is performed.

**Comment by Talha909** [comment]
OK THANKS

**Comment by oldman4U** [comment]
Hi. Any news?

**Comment by Talha909** [comment]
i go back to the old firmware.

**Comment by oldman4U** [comment]
So it works with an older version of the firmware?

Have you tried to use MASTER Branch?

**Comment by oldman4U** [comment]
Hello Talha909.

It would help us and also other users like you, if unneeded tickets would be closed by the owner.

@bigtreetech Please close this unneeded ticket. Thank you

**Comment by dieund** [comment]
thanks. it work.
