### ISSUE TITLE
How to change or add font

### ISSUE THREAD

**Issue by mooner1022** [bigtreetech/BIGTREETECH-TouchScreenFirmware#75]
Is there any manual about changing or adding font files for any other languages? I'm trying to add korean to the firmware, but the font doesn't print korean.

**Comment by dmiart** [comment]
A while ago someone posted links to modified fonts for Cyrillic, but this program can probably be used for any bitmap type as it's universal.  

http://corosan.ru/sgfed/

https://github.com/Acenotass/BIGTREETECH-TFT35-V1.2/tree/master/firmware/Copy%20to%20SD%20Card%20root%20directory%20to%20update/TFT35/font

**Comment by mooner1022** [comment]
> A while ago someone posted links to modified fonts for Cyrillic, but this program can probably be used for any bitmap type as it's universal.
> 
> http://corosan.ru/sgfed/
> 
> https://github.com/Acenotass/BIGTREETECH-TFT35-V1.2/tree/master/firmware/Copy%20to%20SD%20Card%20root%20directory%20to%20update/TFT35/font

Thx for the reply, but I wasn't able to open files with this program.

**Comment by thisiskeithb** [comment]
> Thx for the reply, but I wasn't able to open files with this program.

The app works and can edit fonts in a Windows XP VM, but I also found that it couldn’t read any of the TFT font files.

**Comment by dmiart** [comment]
https://github.com/bigtreetech/BIGTREETECH-TFT35-V1.2/issues/41

This is the original post. I assumed it worked for creating fonts for the display.  There is an export function in this program and there is way to export as binary.

**Comment by guruathwal** [comment]
You can check out word_unicode.fon file. It contains the fonts for oher languages. You may check it in SG Font editor.  Try these instructions
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/103#issuecomment-550180539
You will need to change doc properties size 24x24 and total count to a very high number to view all the characters.

**Comment by mooner1022** [comment]
I'll try it when I get back from the trip. Thx guys!

**Comment by mooner1022** [comment]
> You can check out word_unicode.fon file. It contains the fonts for oher languages. You may check it in SG Font editor. Try these instructions
> [#103 (comment)](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/103#issuecomment-550180539)
> You will need to change doc properties size 24x24 and total count to a very high number to view all the characters.

I've applied the fonts and firmware, but korean still does not show and white boxes are showing instead. At least it isn't cracking like the original font, so I think it's showing some hope.

**Comment by guruathwal** [comment]
> > You can check out word_unicode.fon file. It contains the fonts for oher languages. You may check it in SG Font editor. Try these instructions
> > [#103 (comment)](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/103#issuecomment-550180539)
> > You will need to change doc properties size 24x24 and total count to a very high number to view all the characters.
> 
> I've applied the fonts and firmware, but korean still does not show and white boxes are showing instead. At least it isn't cracking like the original font, so I think it's showing some hope.

What Screen size do you have?
**for TFT35**
you need to import the `word_unicode.fon` with these settings
- Doc Properties
![Annotation 2019-11-09 203301](https://user-images.githubusercontent.com/22422544/68530642-25759d80-0330-11ea-9e4b-bd6821306cac.png)


  Symbols count: 8192 ( this is the maximum count allowed in SG font Editor )

- Import Setting
  ![Annotation 2019-11-09 202932](https://user-images.githubusercontent.com/22422544/68530609-bd26bc00-032f-11ea-8dcd-92464db4ba77.png)

**For TFT24/28**
- Doc Properties
  - Change Symbol width & height to 16

- Import Setting
  - Change Byte per line 2

Export Setting will be same as import setting.

you need to check the unicode character address of the language you want to add.

**Comment by mooner1022** [comment]
> > > You can check out word_unicode.fon file. It contains the fonts for oher languages. You may check it in SG Font editor. Try these instructions
> > > [#103 (comment)](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/103#issuecomment-550180539)
> > > You will need to change doc properties size 24x24 and total count to a very high number to view all the characters.
> > 
> > 
> > I've applied the fonts and firmware, but korean still does not show and white boxes are showing instead. At least it isn't cracking like the original font, so I think it's showing some hope.
> 
> What Screen size do you have?
> **for TFT35**
> you need to import the `word_unicode.fon` with these settings
> 
> * Doc Properties
>   ![Annotation 2019-11-09 203301](https://user-images.githubusercontent.com/22422544/68530642-25759d80-0330-11ea-9e4b-bd6821306cac.png)
>   Symbols count: 8192 ( this is the maximum count allowed in SG font Editor )
> * Import Setting
>   ![Annotation 2019-11-09 202932](https://user-images.githubusercontent.com/22422544/68530609-bd26bc00-032f-11ea-8dcd-92464db4ba77.png)
> 
> **For TFT24/28**
> 
> * Doc Properties
>   
>   * Change Symbol width & height to 16
> * Import Setting
>   
>   * Change Byte per line 2
> 
> Export Setting will be same as import setting.
> 
> you need to check the unicode character address of the language you want to add.

The screen I have is TFT35 V2. I'll try to modify the file, thanks!

**Comment by mooner1022** [comment]
> > > You can check out word_unicode.fon file. It contains the fonts for oher languages. You may check it in SG Font editor. Try these instructions
> > > [#103 (comment)](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/103#issuecomment-550180539)
> > > You will need to change doc properties size 24x24 and total count to a very high number to view all the characters.
> > 
> > 
> > I've applied the fonts and firmware, but korean still does not show and white boxes are showing instead. At least it isn't cracking like the original font, so I think it's showing some hope.
> 
> What Screen size do you have?
> **for TFT35**
> you need to import the `word_unicode.fon` with these settings
> 
> * Doc Properties
>   ![Annotation 2019-11-09 203301](https://user-images.githubusercontent.com/22422544/68530642-25759d80-0330-11ea-9e4b-bd6821306cac.png)
>   Symbols count: 8192 ( this is the maximum count allowed in SG font Editor )
> * Import Setting
>   ![Annotation 2019-11-09 202932](https://user-images.githubusercontent.com/22422544/68530609-bd26bc00-032f-11ea-8dcd-92464db4ba77.png)
> 
> **For TFT24/28**
> 
> * Doc Properties
>   
>   * Change Symbol width & height to 16
> * Import Setting
>   
>   * Change Byte per line 2
> 
> Export Setting will be same as import setting.
> 
> you need to check the unicode character address of the language you want to add.

I'm trying to edit the file, but I'm facing a problem. Korean decimal starts from 12593, but the bitmap editor's limit is 8192. How can I solve this?

**Comment by guruathwal** [comment]
> I'm trying to edit the file, but I'm facing a problem. Korean decimal starts from 12593, but the bitmap editor's limit is 8192. How can I solve this?

till now we did not find any free software to work over that.
also can't confirm if the TFT supports characters over 8192, this will require deep digging into the code, or if @bigtreetech could confirm that it would be nice.

**Comment by mooner1022** [comment]
> > I'm trying to edit the file, but I'm facing a problem. Korean decimal starts from 12593, but the bitmap editor's limit is 8192. How can I solve this?
> 
> till now we did not find any free software to work over that.
> also can't confirm if the TFT supports characters over 8192, this will require deep digging into the code, or if @bigtreetech could confirm that it would be nice.

Then is there any way to add language on unused spaces in font file and specify the position in firmware to read it korean?
