### ISSUE TITLE
Fade height OFF

### ISSUE THREAD

**Issue by Kyosuke33** [bigtreetech/BIGTREETECH-TouchScreenFirmware#750]
Hello, after update my TFT35 screen with config.ini, i have a message "Fade height off"
At first i think that i change something on config.ini who made this error; so i try to update with the config.ini without changing anything and i have also this error.
So there is something in the config.ini file who is not existing in the firmware.
Someone have this problem or an idea what made this error ?
Thank you.

**Comment by bigtreetech** [comment]
hello, it‘s because of here https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/blob/1f7bf8d92d644016a0f2fc7cc29886932383f296/Copy%20to%20SD%20Card%20root%20directory%20to%20update%20-%20Unified%20Menu%20Material%20theme/config.ini#L172
the default config is enabled `auto_load_leveling`, it's for auto load leveling grid data after startup,  if you don't use auto leveling,  please set it from 1 to 0 to disable it

**Comment by Kyosuke33** [comment]
I use auto leveling with a Bltouch.

**Comment by radek8** [comment]
If you perform auto-leveling and save the grid data, the error disappears

**Comment by Kyosuke33** [comment]
Already try but Fade Height off always here.
At first i have "Failed to enable Bed Leveling echo:Bed Leveling OFF echo:Fade Height OFF ok"
After doing the leveling, the other error are gone but not Fade height off error.

**Comment by Kyosuke33** [comment]
I change auto_load_leveling from 1 to 0 and the error disappears.
This option auto load grid data after power up the printer it's true ?
This option is for people who won't use auto leveling before every print and so use the same grid data who are stored and load at power up ?
If i use G29 before every print, i don't need this ?
Thank you !

**Comment by MontyFlange** [comment]
> If you perform auto-leveling and save the grid data, the error disappears

How do you do that ?

**Comment by Kyosuke33** [comment]
After doing auto leveling directly to the screen, the data will save auyomatically, there is a message on the screen. But for me the error still here after that

**Comment by radek8** [comment]
you have the Marlin option enabled
   #define ENABLE_LEVELING_FADE_HEIGHT

**Comment by Kyosuke33** [comment]
Yes maybe, i look at this after work. But i don't know why, when i install the 26.x firmware, i have no error, all is good, and if i just update 1 thing with the config.ini (for exemple just change preheat temps), after update i have the Fade Height error.

**Comment by radek8** [comment]
Maybe auto-leveling was turned off after the update was uploaded. And you turned it on with an ini file?

**Comment by Kyosuke33** [comment]
Maybe, i search but no luck for now. Fortunately this does not prevent the printer from working

**Comment by M-Beltramo** [comment]
I have the same issue as Kyosuke33. The same error "Fade height off" wihout any reason. I had the 0.25.1 firmware version and the ABL (BLTouch) was working fine after a G29 M500, but now this error prevent if from working fine. Will there be a fix someday ? Thanks (I just returned of the old version which was working fine for the ABL)

**Comment by MontyFlange** [comment]
I disabled it in Marlin

**Comment by M-Beltramo** [comment]
@MontyFlange you disabled what ?

**Comment by M-Beltramo** [comment]
@Kyosuke33 I tried using the commit 87d46371f3b6d96c8362f495d0ed7fac8b27ecfc and it's working fine even by modifying the preheat temperatures and then compiling. I'm using it right now.

**Comment by Kyosuke33** [comment]
Ok thank you !

**Comment by q32103940** [comment]
This is a really annoying feature to be turned on by default where it will definitely throw a "fade height off" popup for the user on startup. I have a mesh stored in EEPROM and I keep getting the annoying pop up.

**Comment by Chukozor** [comment]
@Kyosuke33  Unfortunately the fade height is still off by doing what I said. I printed a benchmark of bed levelling, and the result was bad, so it is still off even by doing this. I'm gonna open another issue, maybe They'll fix it. I'm back at version 0.25.1 but it's not as good looking and efficient as the last version, but at least Fade height is still working.

**Comment by Chukozor** [comment]
I opened a bug ticket [here](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/799).

**Comment by MrAntonka** [comment]
try this:
G29 F 10.0      ; Set Fade Height for correction at 10.0 mm.

**Comment by MontyFlange** [comment]
Why not just turn it off in Marlin ? Is it needed ?

**Comment by Chukozor** [comment]
@MrAntonka j'utilise 1AUTO_BED_LEVELING_BILINEAR1 and the `F` option is only available for AUTO_BED_LEVELING_UBL.
The piece of code of my marlin firmware :

` * - AUTO_BED_LEVELING_BILINEAR
 *   Probe several points in a grid.
 *   You specify the rectangle and the density of sample points.
 *   The result is a mesh, best for large or uneven beds.
 *
 * - AUTO_BED_LEVELING_UBL (Unified Bed Leveling)
 *   A comprehensive bed leveling system combining the features and benefits
 *   of other systems. UBL also includes integrated Mesh Generation, Mesh
 *   Validation and Mesh Editing systems.
 *
 * - MESH_BED_LEVELING
 *   Probe a grid manually
 *   The result is a mesh, suitable for large or uneven beds. (See BILINEAR.)
 *   For machines without a probe, Mesh Bed Leveling provides a method to perform
 *   leveling in steps so you can manually adjust the Z height at each grid-point.
 *   With an LCD controller the process is guided step-by-step.
 */
//#define AUTO_BED_LEVELING_3POINT
//#define AUTO_BED_LEVELING_LINEAR
#define AUTO_BED_LEVELING_BILINEAR
//#define AUTO_BED_LEVELING_UBL
//#define MESH_BED_LEVELING`

**Comment by MrAntonka** [comment]
@Chukozor yes let's switch it to UBL :)

**Comment by MontyFlange** [comment]
Any chance they could get it so Octoprint connects ? With the TFT connected

**Comment by dlynch01** [comment]
Pretty much the same problem (I think) Updated my Ender 3 Pro with SKR mini E3 V2.0 and TFT35 E3 V3.0 worked great! I then installed a 3D touch and updated the firmware "firmware-bltouch.bin" from this site. Now I am getting "echo Fade Height off" error. I do not have a clue what to do. I have spent hours reading but I can not find the answer.

**Comment by MontyFlange** [comment]
> Pretty much the same problem (I think) Updated my Ender 3 Pro with SKR mini E3 V2.0 and TFT35 E3 V3.0 worked great! I then installed a 3D touch and updated the firmware "firmware-bltouch.bin" from this site. Now I am getting "echo Fade Height off" error. I do not have a clue what to do. I have spent hours reading but I can not find the answer.

Think most ppl have just uncommented it

**Comment by dlynch01** [comment]
> > Pretty much the same problem (I think) Updated my Ender 3 Pro with SKR mini E3 V2.0 and TFT35 E3 V3.0 worked great! I then installed a 3D touch and updated the firmware "firmware-bltouch.bin" from this site. Now I am getting "echo Fade Height off" error. I do not have a clue what to do. I have spent hours reading but I can not find the answer.
> 
> Think most ppl have just uncommented it

I see where you had a problem with Octoprint and the TFT. I can connect fine with Octoprint with the TFT also hooked up and working.
I hope someone can help me get this working using the 3D touch.

**Comment by MontyFlange** [comment]
Gave up on getting a Pi to connect. Couldn't do it

**Comment by MontyFlange** [comment]
I'm getting a Wifi Unit and going down the DUET route now

**Comment by grantlesueur** [comment]
Regarding the message Echo Fade hight off.  this message is a status message that reflects the state of  
#define ENABLE_LEVELING_FADE_HEIGHT (In the Configuration.h file)
It means that bed leveling is applied for the entire z height of you print. to switch on the feature issue  do the following
Send: M420 Z10
Recv: echo:Bed Leveling ON
Recv: echo:Fade Height 10.00

Now the message on the TFT35 reads "echo Fade Height 10.00".

Its not really an error message rather just an indicator if the feature is on and what it is set to.
Here is the Marlin CGODE reference  [https://marlinfw.org/docs/gcode/M420.html]

A better question is why is it necessary for the SKR to echo this state, the behavior of the TFT seems to be correct and setting the ### Auto Save Load Leveling Data seems to make sense if you wish to initiate ABL from the TFT display.

**Comment by Lumute** [comment]
This is what is happening:

Whenever ALB is enabled, it will give you the status of both ABL an Fade Height.

If you have never calculated your mesh or also whenever the EEPROM is cleared and you lose your mesh, enabling ABL either in the menu, by command or by the TFT with the config.ini auto_load_leveling:1 at startup, it will give you an error because you can't have ABL without a mesh and immediately re-disables ABL, which in turn also disables Fade Height.

Now, when you go and calculate your Mesh and save the settings, you are not only saving the Mesh but also that ABL and Fade Hight are disabled. These now saved settings override whatever you had in your configuration.h when you compiled Marlin.

Now, you restart and the TFT enables ABL (and only ABL), it echoes saying ABL is ON an Fade Hight is OFF. Tada!

@grantlesueur is correct, enable it with M420 Z10 or setting a value between 0 and 20 using the TFT (Menu / Movement / ABL / Z Fade) and save your settings again...

**Comment by MontyFlange** [comment]
Do you manually M500 to save the mesh ?

**Comment by Lumute** [comment]
You can do it that way but I normally use TFT touch GUI (Menu/ Movement / ABL / Start), when it finishes it asks you if you want to save the settings to EPROM and then I click yes, which is the same as running an M500.

**Comment by MontyFlange** [comment]
Mmmm not sure I ever see the save option

**Comment by thatsumoguy** [comment]
> Mmmm not sure I ever see the save option

It doesn't come up for me either. What I do is on my gcode I have it run a G29 and then M500 on every print. Also I use bed level visualizer for octoprint and have it save the mesh also.
