### ISSUE TITLE
TFT35 Touch not working after update

### ISSUE THREAD

**Issue by MontyFlange** [bigtreetech/BIGTREETECH-TouchScreenFirmware#754]
I can use the screen now. is there any way to force a calibration for the screen after an update ?

**Comment by oldman4U** [comment]
Hi.

As far as i know there is a calibration function in the user interface itself under Screen.

**Comment by radek8** [comment]
Insert the reset.txt file on the SD card and restart the display. The display touch calibration is performed.

**Comment by MontyFlange** [comment]
Where does one find this 'reset.txt file then ? It's not in the bundle I downloaded

**Comment by oldman4U** [comment]
And does not work means in detail?

Black screen
Does not react when touching
Executes the wrong function
Only touchscreen but no marlin
Or
Or
Or
?

MontyFlange <notifications@github.com> schrieb am Do. 4. Juni 2020 um 18:37:

**Comment by MontyFlange** [comment]
> And does not work means in detail? Black screen Does not react when touching Executes the wrong function Only touchscreen but no marlin Or Or Or ? MontyFlange <notifications@github.com> schrieb am Do. 4. Juni 2020 um 18:37:
> […](#)


No response to touch

**Comment by MontyFlange** [comment]
> > Where does one find this 'reset.txt file then ? It's not in the bundle I downloaded
> 
> Create an empty file with this name:
> reset.txt

LOL that simple OK :)

**Comment by MontyFlange** [comment]
OK RESET TXT worked :) Great Thanks for all the help

**Comment by oldman4U** [comment]
Hi MontyFlange.

This is great. So everything works now? I would also recommend to use Master Branch instead of 26.x firmware version. Many bug fixes and configuration can be changed using config.ini file.

Please let us know

**Comment by MontyFlange** [comment]
Master branch ? All this gargonisum is new to me :)

**Comment by oldman4U** [comment]
I totally understand what you mean!

Most important - EVERYTHING works now?

If you have not been working with Visual Studio Code before or you are not interested to spend more time by tinkering around with software - don’t start with it and forget my last reply.

But besides the official firmware, there is always firmware available which you can download and “compile” by yourself. This requires a computer, free software and some time to learn how to do it. The advantage is, that you can make changes to your software, not available I the user interface you are using today.

In your case there is the official “ready to use” firmware and a firmware which is under development. This under development version for the TFTs is called Master. Attached a screenshot which shows what I mean.

**Comment by MontyFlange** [comment]
I have played with PIO to make Marlin. Problem started when the version of Marlin given out by BIQU on the GitHub page was to old to work in the new PIO and wouldn't compile, which started this 'update' trail :)  Got Marlin working, then their 'tech' guy said update TFT, So came here and did that following their instructions , then it all went belly up :)

**Comment by MontyFlange** [comment]
But I do think that the reset.txt file and instructions should be included in the package :)   6 hours of trying to get it working, then 30 seconds with that info.

**Comment by oldman4U** [comment]
The TFT software is maybe 1/50th compared to the software for your board, maybe you want to give “Master” a try. Otherwise enjoy your TFT and happy printing;-)

I agree that documentation could be better and that a proper manual would avoid maybe half of the tickets here.

Please close this ticket if you do not need it any more and start a new one if needed

Thank you

**Comment by MontyFlange** [comment]
Will do. I think the ini file has all the changes I'm willing to risk for now :) Thanks

**Comment by radek8** [comment]
Information about the reset.txt file is on the Welcome screen. Just read to the end :-)

![image](https://user-images.githubusercontent.com/46979052/83805373-0e254580-a6b0-11ea-918b-e72e396cca7b.png)

**Comment by oldman4U** [comment]
Hi Radek.

This is very cool, thank you. I never needed it, but good to know;-)

Thank you

**Comment by MontyFlange** [comment]
> Information about the reset.txt file is on the Welcome screen. Just read to the end :-)
> 
> ![image](https://user-images.githubusercontent.com/46979052/83805373-0e254580-a6b0-11ea-918b-e72e396cca7b.png)

LOL yer saw that later Do'H :)
