### ISSUE TITLE
Why are the steps on the screen and not the distance?

### ISSUE THREAD

**Issue by Aleks-MO** [bigtreetech/BIGTREETECH-TouchScreenFirmware#761]
Why are the steps on the screen and not the distance? Explain clearly. Why isn't the fan showing?
![WP_20200526_11_04_11_Pro](https://user-images.githubusercontent.com/22274265/83774790-765f3180-a686-11ea-93cd-c3463329309d.jpg)

**Comment by guruathwal** [comment]
what marlin version are you using? it might have been caused by this issue in marlin firmware: https://github.com/MarlinFirmware/Marlin/issues/17255

Marlin firmware does not report fan speed until this PR: https://github.com/MarlinFirmware/Marlin/pull/18013

**Comment by Aleks-MO** [comment]
@guruathwal 
I have a smoothie. 
There for some reason shows these settings from smoothies
**# Arm solution configuration : Cartesian robot. Translates mm positions into stepper positions
alpha_steps_per_mm                           160              # X -Steps per mm for alpha stepper 1mm
beta_steps_per_mm                            160              # Y -Steps per mm for beta stepper
gamma_steps_per_mm                           800              # Z -Steps per mm for gamma stepper**

That now BTT screens don't work?

**Comment by guruathwal** [comment]
ok.. it is working fine with marlin firmware. Can you share the response of M114 in smoothieware using a serial monitor?

**Comment by Aleks-MO** [comment]
@guruathwal   Please, here is M114, everything is as it should be. I have another MKS TFT printer and everything is fine there ...
![WP_20200606_14_01_41_Pro 1](https://user-images.githubusercontent.com/22274265/83942743-b5ac9000-a7f6-11ea-8d0e-b99b9afc5883.jpg)

**Comment by Aleks-MO** [comment]
@guruathwal  Video-          https://youtu.be/nqUxSDT3rtk

**Comment by guruathwal** [comment]
I tried to fix the issue in this commit: 969a86f35a6edda7b0508050d0f2906461eb69ab
Can you check if it solves the issue?

**Comment by Aleks-MO** [comment]
@guruathwal Can you give me the .bin file? I can't create...(       I'll check right away.

**Comment by radek8** [comment]
[Nová složka (2).zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4740790/Nova.slozka.2.zip)

**Comment by Aleks-MO** [comment]
@radek8 I'll try it out now..

**Comment by Aleks-MO** [comment]
@radek8  No image..(( Full folder with icons please.

**Comment by radek8** [comment]
OMG

[TFT35.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4740815/TFT35.zip)

**Comment by Aleks-MO** [comment]
@radek8   Okay, everything seems fine, XYZ readings are there. Another ride... Thank you. P.S. My mistake, I forgot to put the icon in the folder...) I Apologize...)

**Comment by radek8** [comment]
Acknowledgments belong to the guruathwal :-)

**Comment by Aleks-MO** [comment]
I'll be sure to tell him.)

**Comment by Aleks-MO** [comment]
@guruathwal Thanks, everything seems to be working...  Make this change in the release in the official firmware .bin for those who use ready-made firmware on the screen. The fan still shows 0, after the M106 command from the terminal or from the GCODE. ( If you are using Smoothies )
