### ISSUE TITLE
Any way to re arrange this menu layout

### ISSUE THREAD

**Issue by MontyFlange** [bigtreetech/BIGTREETECH-TouchScreenFirmware#762]
It seems out of line to me :)

I would like it 

X  Y  Z
X  Y  Z

Not jumbled like it is ?

also add a 50mm move option ?

Thanks again

![Move menu](https://user-images.githubusercontent.com/11325160/83833296-85c09800-a6e3-11ea-99a5-5fd68fa89613.jpg)

**Comment by Tygrys-1** [comment]
I think good idea. Requires only to exchange Z- with X+.
Current layout is meant to be more "natural" to the real directions, but it is harder to memorize.

Switching 4 different lengths will be more anoying than 3, so I do not like the idea.
I'd rather like the option to move X and Y  to center/limit on long press - or use the "key repeat" on long press. 

For faster moves I use the knob, but beware side effects.

**Comment by radek8** [comment]
A long press is to move to marlin mode.

Just swap this line to swap buttons.

![image](https://user-images.githubusercontent.com/46979052/83850282-fe8a1900-a710-11ea-8236-e145ca0db0ec.png)

**Comment by Tygrys-1** [comment]
Long press to move to Marlin (from anywhere) is a waste of the interface potential funcionality. What is the reason to go to the Marlin mode from a movement sub menu?

Unless I'm missing something, it should be left for the knob long press only, or the long press on the main menu. But if we can "free" the long press from Marlin access, I see some additional potential we can have in the menus. I.e. long press on "back" can move to top menu, not only the level up.

**Comment by radek8** [comment]
And how would you like to get from Marlin back to the touch screen?

**Comment by Tygrys-1** [comment]
Like today - by long pressing the knob. And I see no reason to remove the todays ability to do this by long pressing the screen, as in Marlin mode the touch screen is not used.
Can the long press interpretation be context - sensitive? When called from screens where we use +/- buttons or back buttons or whatever we agree to use it for it will do some things, on main menu or in Marlin mode it will invoke the mode change screen.

Using the knob in touch mode to change values is a good idea, but has side effects on Marlin, so maybe we can eat a cake and still have a cake with this "long press on certain buttons" idea?

**Comment by radek8** [comment]
And how do you get from the Merlin screen to a display that doesn't have a coder?
For example, BIGTREETECH TFT28
All variants have the same FW

http://www.bigtree-tech.com/shop/product/show/id/29

You alone higher that the use of a coder in touch mode has side effects.

**Comment by radek8** [comment]
The idea is nice but there are HW limitations

**Comment by MontyFlange** [comment]
I don't have a knob. So thats out

**Comment by MontyFlange** [comment]
the previous version had them in the right order
![right way](https://user-images.githubusercontent.com/11325160/83883031-dfa07c80-a73a-11ea-8ba1-712d76d7f185.jpg)

**Comment by Tygrys-1** [comment]
> 
> 
> I don't have a knob. So thats out

This is what I suspected :-)

Will it be any problem to you to go to Marlin mode from the main menu only, not just from anywhere as it is today?

**Comment by Tygrys-1** [comment]
> 
> 
> The idea is nice but there are HW limitations

Sure they are.
Please explain.

**Comment by MontyFlange** [comment]
> > I don't have a knob. So thats out
> 
> This is what I suspected :-)
> 
> Will it be any problem to you to go to Marlin mode from the main menu only, not just from anywhere as it is today?

I want to rearrange them, Why would going into Marlin mode help ?

**Comment by Tygrys-1** [comment]
You have got an answer from Radek on rearangement.

I just asked about the need to use long press to go to the marlin mode from every menu, not just the main one. This is connected to your second question about speeding up the moves.

**Comment by MontyFlange** [comment]
> You have got an answer from Radek on rearangement.
> 
Where ? I don't see it, just mentions about going to Marlin mode

**Comment by Tygrys-1** [comment]
Radek's first post in this thread.
You have to modify the configuration.h file, comment the #define ALTERNATE_MOVE_MENU, rebuild the firmware and update it to TFT.

**Comment by MontyFlange** [comment]
Ahh OK I don't know how to compile this firmware

**Comment by radek8** [comment]
what is the display?

**Comment by MontyFlange** [comment]
TFT35 V2


![TFT35Screen](https://user-images.githubusercontent.com/11325160/83904973-c0b0e300-a758-11ea-9f66-c40d82f2b0c6.jpg)

**Comment by MontyFlange** [comment]
They are in the 'right' order with Unifi menu

**Comment by radek8** [comment]
[BIQU_TFT35_APP1_V2.0.26.x.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4737562/BIQU_TFT35_APP1_V2.0.26.x.zip)

**Comment by radek8** [comment]
Use Config.ini for configuration
Edit the config.ini file according to your own configuration, upload to the SD card, insert it into the display and restart.

**Comment by MontyFlange** [comment]
Cool with give it a try in a bit . Thanks

**Comment by oldman4U** [comment]
@MontyFlange 

Please close this ticket in case you do not need it anymore. 

Thank you
