### ISSUE TITLE
[Q] Disable "LCD12864 Simulator"

### ISSUE THREAD

**Issue by iMattmax** [bigtreetech/BIGTREETECH-TouchScreenFirmware#767]
I  use the latest firmware for the TFT35 and wanna know how I can disable the overlay "LCD12864 Simulator" on the Marlin screen. 
As I get this TFT35 I think there was no overlay, but after the update there is now an overlay and I wanna get rid of it.

**Comment by carl1961** [comment]
in config.ini around line 110  you get the settings, you can turn it off or rename it. you put this on your sdcard and reboot TTF  
#### Marlin Mode show title
# Options: [enable: 1, disable: 0]
marlin_show_title:1

# Run Marlin Mode in Fullscreen
# Options: [enable: 1, disable: 0] [Disabled. RECOMMENDED FOR TFT24]
marlin_fullscreen:0

#### Text displayed at the top of the TFT in Marlin Mode.
marlin_title:LCD12864 Simulator

**Comment by iMattmax** [comment]
Do I flash than only the ini or the whole firmware again?

**Comment by radek8** [comment]
Edit the config.ini file according to your own configuration, upload to the SD card, insert it into the display and restart.

**Comment by iMattmax** [comment]
Thanks, I will try it later

**Comment by oldman4U** [comment]
Hi. 

Please close unneeded tickets. 

Thank you
