### ISSUE TITLE
How to add a second extruder/nozzle to bigtreetech tft24-V1.1?

### ISSUE THREAD

**Issue by nitrolexa** [bigtreetech/BIGTREETECH-TouchScreenFirmware#77]
Where can I find the source code and how to compile it so that I can control the second extruder on your tft24 V1.1 monitor in serial mode
Can you give me an updated firmware for this monitor to use two extruders in serial mode?

**Comment by bigtreetech** [comment]
hello, accoding to [here](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware#how-to-compile-firmware), set the `default_envs` to `BIGTREE_TFT24_V1_1`,  and [here](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware#how-to-config-firmware), modify `TOOL_NUM` from 1 to 2 (for 2 nozzle hotends, if your printer is 2 in 1out extruder need not this modify), and `EXTRUDER_NUM` from 1 to 2.
