### ISSUE TITLE
[BUG] Onboard SD missing

### ISSUE THREAD

**Issue by DJDOUBLEG** [bigtreetech/BIGTREETECH-TouchScreenFirmware#770]
Missing this line in Configuration.h
#define ONBOARD_SD_SUPPORT
When i insert this line in config and reflash the fw. 
Not show onboard SD menu  in touch mode.
![kép](https://user-images.githubusercontent.com/48370718/84012151-6a6dbb00-a977-11ea-8e3f-8232b92213a6.png)

**Comment by oldman4U** [comment]
Hello DJDOUBLEG.

Could you please let us know which board you are using and which version of the firmware (board and TFT).

With the latest version of the firmware, the board SD support has to be enabled in the board firmware and in the TFT firmware there is an auto detect when using Marlin:

_#### Onboard / Printer SD Card Support
# On Marlin Firmware, The TFT will auto detect Onboard SD Card
# Auto-detect is not available for other firmwares like Smoothieware
#Options: [enable: 1, disable: 0, auto-detect: 2]
onboard_sd_support:2_

Hope this helps, please let us know

**Comment by DJDOUBLEG** [comment]
https://photos.app.goo.gl/am552RfGaLFBNcLS8

**Comment by DJDOUBLEG** [comment]
Work it again. Reflash/recompie/edit config.ini...

**Comment by oldman4U** [comment]
Sounds great. In case this issue has been solved for you, please close this ticket.

Thank you
