### ISSUE TITLE
[Q] (Your Question?) what is the max usb a capacity i can use on the tft 35 e3 v3.0

### ISSUE THREAD

**Issue by bramankersmit** [bigtreetech/BIGTREETECH-TouchScreenFirmware#771]
**Your question or details you need. Please describe.**
A clear and concise question or detail you would like to ask. Like Hardware related or firmware related.

**specify the device variant related to your question.**

**Additional context**
Add any other context or screenshots about the question here.

**Comment by Tygrys-1** [comment]
I have tested working 32GB, formated FAT32 working ok, and 64 and 128GB formated exFAT not working. The same applies to SD card reader. Maybe higher than 32GB, but still formated FAT32 will work, as the FAT32 can handle up to 2TB.

**Comment by bramankersmit** [comment]
> I have tested working 32GB, formated FAT32 working ok, and 64 and 128GB formated exFAT not working. The same applies to SD card reader. Maybe higher than 32GB, but still formated FAT32 will work, as the FAT32 can handle up to 2TB.

**Comment by bramankersmit** [comment]
Thank you
