### ISSUE TITLE
Can't get the encoder to work after flashing firmware

### ISSUE THREAD

**Issue by hillsh** [bigtreetech/BIGTREETECH-TouchScreenFirmware#776]
This is  a new install of TFT24 with a RAMBO board.  I flashed the TFT24 with the new version of the firmware (1.26) and it all seemed to go well.  Before, in factory test mode, I was able to use the encoder to switch between touch mode and 12864 LCD simulator, but now the encoder doesn't do anything so I am stuck in touch mode unable to enter Marllin mode. The dial does work to go the the mode switch page, but turning the dial apparently does nothing.  Is there something I need to do in the Marlin configuration.h?

**Comment by Tygrys-1** [comment]
Use the touch screen to touch the Marlin or BTT icon to choose the mode. Knob is not working on the mode selection screen anymore. I have no idea why.

**Comment by hillsh** [comment]
Thanks for the reply.  So I did that, but the Marlin software is not being displayed - all I see is the line that says" 12864 LCD Simulator". I'm pretty sure that firmware loaded properly, but when I try to reload it nothing happens, either on power up or with a reset.  Any suggestions?

**Comment by Tygrys-1** [comment]
Just turn or press the knob. Or wait some time.

**Comment by hillsh** [comment]
I now have the marlin screen up.  I was enabling the wrong controller, I needed to uncomment *define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER.  However, turning the knob does nothing - is there a specific setting for ENCODER_PULSES_PER_STEP and ENCODER_PULSES_PER_MENU_ITEM?

**Comment by radek8** [comment]
If you have the EXP2 cable properly connected, the encoder should work.

**Comment by hillsh** [comment]
I'm going to have to assume that the TFT24 is damaged, as the turning the encoder doesn't cause any changes to the menu.

**Comment by radek8** [comment]
If the encoder works in touch mode and not in Marlin.
Measure the EXP2 cable for damage

**Comment by radek8** [comment]
> Teď mám marlinovou obrazovku. Aktivoval jsem nesprávný řadič, potřeboval jsem odkomentovat * definovat REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER. Otáčením knoflíku se však nic neděje - existuje konkrétní nastavení pro ENCODER_PULSES_PER_STEP a ENCODER_PULSES_PER_MENU_ITEM?

The encoder setting is as sensitive as you want it to be. I have it set
#define ENCODER_PULSES_PER_STEP 3
#define ENCODER_STEPS_PER_MENU_ITEM 1
and works well

**Comment by hillsh** [comment]
Yeah, it's damaged I think.  I'm closing the issue.
