### ISSUE TITLE
name: Bug report 02 “Connecting …M115” Forever

### ISSUE THREAD

**Issue by B-rad888** [bigtreetech/BIGTREETECH-TouchScreenFirmware#780]
name: Bug report 02
about: Switching to marlin mode after power on TFT = “Connecting …M115” Forever
title: switching screens is not seamless
labels: 'bug'
assignees: '''BIGTREETECH”

Powering on the TFT screen works great in touch screen mode. Then switch to Marlin mode and you will see “Connecting…M115” while it never connects. Requires a reboot to connect. However, booting into Marlin mode first, then switching to touch mode and you won’t get the bug. This is not ideal as most users including myself would like to boot into touch screen mode, and have the ability to switch to marlin mode to make fine adjustments and go back to touch screen mode without having to reboot the printer. Until it is fixed seamless operation requires booting into marlin mode on startup and switching to touch mode. Using this work around will not produce the bug.

### Steps to reproduce

1. Power on TFT in touch screen mode
2. Wait for TFT to say ready
3. Switch to marlin mode either:
	Hold scroll wheel for 3 seconds and select marlin mode
	Press on screen for 3 seconds and select marlin mode
4. Turn scroll wheel to initialize screen in marlin mode
5.  Select Info screen
6. Stare at the connecting…M115 in confusion for eternity. 

**Expected behavior**
After powering on into touch mode and switching to marlin mode:

I would expect the screen to say “CoM115” and to work properly. If “serial_always_on:1” is set in config
or
I would expect the screen to say “Printer name Ready” and to work properly. If “serial_always_on:0” is set in config
**Actual behavior**
After powering on into touch mode and switching to marlin mode:
 Screen displays “connecting…M115” for eternity. Requiring a reboot. Or abandoning marlin mode and navigating back to the touchscreen.

### Hardware Variant
TFT35_V3.0_E3
### TFT Firmware Version & Main Board Firmware details
BIGTREE_TFT35_V3.0_E3.26.x 
SKR 1.4 Turbo
Marlin bugfix-2.0.x

### Additional Information
This may have to do with an error I see after updating the config file. Unknown Command “MM115”
If there is an extra M in the M115 code somewhere it might be causing issues. I haven’t seen anything like that in the code however.

**Comment by oldman4U** [comment]
do you know the distribution date of the bugfix-2.0.x version you use? Should be 2020-04-27 or later

**Comment by B-rad888** [comment]
I'm not sure where to find the date. I downloaded it like 5 days ago.

**Comment by radek8** [comment]
Is this what you downloaded?
Even today I can download the year old version. :-)

**Comment by B-rad888** [comment]
@radek8  Im not sure what you mean by "this"? I downloaded marlin from the main download page. Marlin "Nightly" Builds > Marlin 2.0 with bug fixes
Website:    https://marlinfw.org/meta/download/
Link:     https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.0.x.zip

**Comment by radek8** [comment]
Yes, this version is current

**Comment by B-rad888** [comment]
@radek8 Thanks for checking! 

I'm new to this board and screen. I made sure everything was up to date with the install and reported the problems immediately. Hopefully these issues can be fixed. I really like the setup. However, if the TFT has limitations I might have to go back to the original screen for usability. Especially if I run into more bugs after installing power loss recovery, filament sensor, and all the other stuff I have planned.

**Comment by radek8** [comment]
So touch mode works and freezes in Marlin mode?
Can you take a picture of the error?

**Comment by oldman4U** [comment]
Hi.

I believe you did everything right. But there has to be a difference because i can not see the 3 issues - but must say that i do not use onboard sd with my skr E3 DIP V1.0 board.

**Comment by B-rad888** [comment]
![error](https://user-images.githubusercontent.com/66757015/84384739-48f11700-aba3-11ea-81f6-0a26c610a1e6.jpg)

**Comment by B-rad888** [comment]
@radek8 The screen is not frozen. I can still navigate

**Comment by radek8** [comment]
Thank you.
Please attach files
Configuration.h
Configuration_adv.h
I have a similar configuration, I will match my settings.

**Comment by B-rad888** [comment]
@radek8 Thanks!
[Config H & ADV.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4764713/Config.H.ADV.zip)

**Comment by radek8** [comment]
If you make a home.
Then you switch to marlin, what will be on the display?
The display shows the last command ...

**Comment by B-rad888** [comment]
Same result, So I did the following:
1.Power on TFT in touch screen mode
2. Wait for TFT to say ready
3. Auto home
4. Switch to marlin mode
5.Turn scroll wheel to initialize screen in marlin mode
6.Select Info screen
7.Stare at the connecting…M115 in confusion for eternity.

**Comment by radek8** [comment]
Uncomment
#define M115_GEOMETRY_REPORT
and recompile Marlin

**Comment by B-rad888** [comment]
Thanks for the suggestion. However, I just re flashed firmware and same result.

**Comment by B-rad888** [comment]
do I need to also uncomment the following?

 //#define CNC_COORDINATE_SYSTEMS

**Comment by radek8** [comment]
uncomment and edit
#define SDCARD_CONNECTION ONBOARD

uncomment
#define LONG_FILENAME_HOST_SUPPORT

This is not related to this problem, but it is better to change it.

**Comment by radek8** [comment]
> do I need to also uncomment the following?
> 
> //#define CNC_COORDINATE_SYSTEMS

you leave this as it is

**Comment by oldman4U** [comment]
I tested with commented and uncommented and it does not show the M115 in both cases. So there has to be something else causing this.

We all count on Radek now;-)

**Comment by B-rad888** [comment]
I appreciate the suggestions! :) However, changing to #define SDCARD_CONNECTION ONBOARD now only allows marlin mode to access the onboard SD where before it was accessing the TFT SD. It also makes my other bug with accessing the onboard sd from the tft worse. It will freeze on the loading screen 95% of the time trying to access the onboard sd.

**Comment by radek8** [comment]
This looks like a communication problem on RS232

**Comment by B-rad888** [comment]
Hmmm.. So would that mean something is defective in the board or the screen?

**Comment by radek8** [comment]
Both variants are possible

**Comment by B-rad888** [comment]
Interesting. So I'm not sure what to do with my set up then. Is no one experiencing the bugs that I am?  Is there any way to determine the root cause? Should I as for a warranty replacement?

**Comment by radek8** [comment]
the other errors you describe point to this

**Comment by radek8** [comment]
It should be tried which board is defective, but it means reconnecting a few connectors and changing the configuration.
look here:
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/715

**Comment by radek8** [comment]
Would you be able to switch the RX and TX pins to another serial port on the display to see if the display has a faulty RS232 input?

**Comment by B-rad888** [comment]
I could swap the pins. However, I'm a little confused on how to do so at the moment. I'm still looking at the other post, trying to wrap my head around what actually needs to be done.

**Comment by B-rad888** [comment]
Yes I'm not sure. The post is a little beyond me right now. This is my first time building code and doing a rebuild of a 3d printer.

**Comment by guruathwal** [comment]
In **Marlin Mode** the TFT acts as a dumb monitor connected to a CPU (Mainboard). All the text you see in **Marlin Mode** is, in reality, happening in Marlin firmware on the Mainboard.

Have you also connected **OctoPrint** or **ESP3D** to the Mainboard? The `Connecting...` text is not coming from the TFT (unless any part of the TFT firmware is changed to do so). This message is more commonly used by other hosts controllers like (OctoPrint and ESP3D) when they try to connect to a WiFi network.

**Comment by B-rad888** [comment]
I haven't connected octoprint, and I do have a wifi module connected to the tft

**Comment by B-rad888** [comment]
@guruathwal I think you are on to something here. Removing the wifi module and doing the same steps as above actually changes the "connecting…M115" to "media inserted

1, remove wifi module
2.Power on TFT in touch screen mode
3. Wait for TFT to say ready
4. Switch to marlin mode
5.Turn scroll wheel to initialize screen in marlin mode
6.Select Info screen
7.Stare at the new display saying "Media Inserted"

![media inserted](https://user-images.githubusercontent.com/66757015/84402333-2669f880-abb9-11ea-8e21-4b98fdbe0135.jpg)

**Comment by B-rad888** [comment]
Here I was tearing everything apart. However I'm still wondering about accessing the media, how that works, and a possible hardware issue that @radek8 mentioned

**Comment by radek8** [comment]
In this case, there will be no problem with HW.
It does not have WIFI configured, which tried to connect constantly.

**Comment by guruathwal** [comment]
> I haven't connected octoprint, and I do have a wifi module connected to the tft

Ok, you did not mention any wifi module connected to the TFT controller in your issue description. Always mention full details of the hardware and software versions and variants.

The `Connecting …M115`  is displayed because the commands from the TFT and Wifi module are getting mixed up. Maybe because Wifi module is not sending EOL `\n` in `M117` Gcode while it tries to connect to a network.
You can ignore the message or you can report the issue in the Wifi module's GitHub page.

**Comment by radek8** [comment]
What does the Marlin screen write to you after disconnecting the WIFI module and resetting the printer?

**Comment by B-rad888** [comment]
Thank you all so much for all your help! The TFT really doesn't like the wifi module. After some more testing selecting onboardSD from the TFT works without freezing. It does take about 30 seconds to load but it works.  

My only other question is: In marlin Mode can I only have one media source available?  Either TFT SD or Onboard SD? I ask because I can mount media but not all three sources like in the TFT. 

@radek8  It displays media inserted like the picture above :)

**Comment by B-rad888** [comment]
Also I'm really sorry for not mentioning the Wifi module. I kind of forgot about it, since I haven't used it. I just set it up and forgot about it.

**Comment by radek8** [comment]
Yes, you only have one SD card available in merlin mode. That's why I recommended you to enable 2 parameters above.
In marlin mode you will print from onboard SD.
Onboard SD, TFT SD and USB will be available in touch mode.

**Comment by B-rad888** [comment]
Perfect! It looks like everything except the Wifi is working correctly. I'll have to trouble shoot that some more. I can close these three open issues and combine them into one wifi issue if the problem persists. Thank you again I really appreciate all your help! :)

**Comment by radek8** [comment]
I also bothered with WIFI, but if you know where to set it, it's a small thing ...

**Comment by radek8** [comment]
If you have the same Wifi module, I will advise you

**Comment by B-rad888** [comment]
Yes please. I followed the tutorial from Chri's basment on Youtube, but I think he advised to set the wrong frequency and installation method. I think that might be the issue.

**Comment by radek8** [comment]
What module do you have and where do you want to connect it?
to the Marlin board or to the display?

**Comment by oldman4U** [comment]
So Radek did all the work and Gurmeet showed us the right way;-)

I can also help with the WIFI, because I am using it in exactly this display. Unfortunately I can not help with the firmware, because I uploaded it using the SKR Pro I also have. So I can only help with the more simple part - but I can;-)))

Oldman

**Comment by B-rad888** [comment]
I would like to connect it to the display because my case doesn't have a cut out. The module is the ESP-01S WIFI Module ESP8266 

https://www.biqu.equipment/products/esp-01s-wifi-module-esp8266-for-skr-pro?_pos=2&_sid=31dd870de&_ss=r

**Comment by B-rad888** [comment]
@oldman4U  lol. Yes @guruathwal  came out of nowhere and solved it.

**Comment by radek8** [comment]
It works even without a cutout.
Each variant has its + and -
![IMG_20200611_191417_resized_20200611_071531389](https://user-images.githubusercontent.com/46979052/84418916-20573480-ac18-11ea-866e-61d268a6d3d8.jpg)
![IMG_20200611_191434_resized_20200611_071531739](https://user-images.githubusercontent.com/46979052/84418921-21886180-ac18-11ea-80f2-30e5c5f19ba7.jpg)

**Comment by B-rad888** [comment]
Interesting. I do have a spare ribbon cable from my old screen. I didnt think of that. I do have to reprint my case though so I could make a cut out. Its really whatever is most reliable I guess.

**Comment by radek8** [comment]
For starters, put it on the screen, it will be easier

**Comment by B-rad888** [comment]
That is true. I think it needs to be re-flashed though. I think the wrong setup is what cause all the issues.

**Comment by radek8** [comment]
If you wanted to put it in SKR 1.4 turbo, you would have to change the port pins for serial port3 in Visual Studio.
Also, you could not use the USB Connector

**Comment by B-rad888** [comment]
So, no octoprint then if its on the SKR 1.4 board?

**Comment by radek8** [comment]
Marlin defines only 2 serial inputs. on one you have a display and on the other a USB connector or WIFI

**Comment by B-rad888** [comment]
That makes sense

**Comment by radek8** [comment]
The display expands another 3 serial inputs, which it sends to one

**Comment by B-rad888** [comment]
So I already had this set up with the tutorial. The comment I saw on said, 

"I thought the ESP3D guys recommended running it at the 160mhz" 

and the response was... 

"i think they do, but there are so many different ones of these, I was going with the doc I found, honestly I have tried a bunch of different ways and can't see where it makes a whole lot of difference."

Would the wrong frequency be causing this? Because its all set up. I can control the printer and everything. However the TFT has all those issues when its connected.

Im logged into the web interface now and I cant see any setting to change that. Would I have to re flash the Wifi card?

**Comment by B-rad888** [comment]
This is the tutorial: https://www.youtube.com/watch?v=NGgzw-XayEo

It was all set up through VS code and not the program to flash it

**Comment by radek8** [comment]
napřed nastav Marlin dle obrázku.
SSID a pasword  nastav dle své wifi

![image](https://user-images.githubusercontent.com/46979052/84423226-6ca57300-ac1e-11ea-8a50-9a1c9b36d8f1.png)

**Comment by radek8** [comment]
connect to the AP sent by the Wifi card and open the address
192.168.0.1
upload files
401.html
favicon.ico
index.html.gz

![image](https://user-images.githubusercontent.com/46979052/84423744-3c120900-ac1f-11ea-95f4-0726a8f6cc20.png)

**Comment by B-rad888** [comment]
I'm not sure what you mean. I already have the interface operational with those files. I dont have the info in configuration_adv,h though.

**Comment by B-rad888** [comment]
Are you saying to 

1. #define ESP3D_WIFISUPPORT 
2. #define WIFI_SSID
3. #define WIFI_PWD
4. flash firmware 
5. delete or replace 404.htm, fav ico, and index.html.gz

**Comment by radek8** [comment]
delete comment
#define ESP3D_WIFISUPPORT 

add rows
#define WIFI_SSID  namewifi
#define WIFI_PWD  password

**Comment by radek8** [comment]
On the wifi tab, set the configuration of your own wifi network (same as in marlin)

![image](https://user-images.githubusercontent.com/46979052/84425400-c8253000-ac21-11ea-9109-11bc1aca6d3e.png)

**Comment by radek8** [comment]
Attention BaudRate must be the same everywhere, on Wifi, display and Marlin

**Comment by radek8** [comment]
[wifi.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4766619/wifi.zip)

**Comment by B-rad888** [comment]
OK I did all of that. However nothing changed. Everything was already configured like that and I'm still getting the same bugs that I was getting before.

**Comment by radek8** [comment]
If you map the virtual COM port to the Wifi address and port 8888, you can also connect with the Pronterface.exe software, which has more options than a web interface and replaces the USB cable.

**Comment by B-rad888** [comment]
How would I do that?

**Comment by radek8** [comment]
if you have it well set up it works like this

[VID_20200611_204557.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4766702/VID_20200611_204557.zip)

**Comment by radek8** [comment]
when you disconnect wifi and switch to the touch screen.
Does the display communicate with the printer?

**Comment by B-rad888** [comment]
when I remove wifi card everything works. When Wifi card is connected I still get all of the bugs like before

**Comment by radek8** [comment]
Wifi card communication in touch mode

[VID_20200611_205324.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4766735/VID_20200611_205324.zip)

**Comment by radek8** [comment]
Will the Wifi card connect to your network?

**Comment by radek8** [comment]
Do you have an original bin file in the wifi card or the one you edited?

**Comment by oldman4U** [comment]
B-rad888.

My advise. Define a "must have" setup and make it work. From there, add one feature after the other always with the ability to fall back to the working setup. Also, keep it simple and learn every day - like we do.

Regarding WIFI Module. You get more or less a Pronterface/Printrun like user interface over WIFI. I am not using Octoprint, but I believe that there is not a single feature the WIFI connection offers, which Octoprint does not have. I can not see the need to have WIFI in case you have Octoprint. I use the same WIFI/TFT combination you have and I never saw the issues you described. Does not matter if the WIFI module was out of the box, only with the firmware installed or working properly like today. This makes me believe that there is something wrong with this module.

The way you described your problems makes me believe that you could be a very useful part of this community. Please think about it, it would be great to have you "on board".

 Regards

**Comment by oldman4U** [comment]
Thats not exactly true. Guru is always everywhere and he knows almost everything.

;-)))

**Comment by oldman4U** [comment]
@radek8 

I believe we should let B-rad888 sleep a bit. Was a long day;-)

Greetings

**Comment by B-rad888** [comment]
lol I did fall asleep. Then I had to life. I gave up on the wifi module. I set up Octoprint instead on a raspberry pi. I works good. No problems with it.

**Comment by oldman4U** [comment]
Hi.

Good to hear.

Please close this ticket

Thank you

**Comment by B-rad888** [comment]
It was fun, not solved, but the issue was diagnosed. Closing thicket. Thanks again for all the help and support! @oldman4U  @guruathwal  and @radek8  You guys rock! 💯
