### ISSUE TITLE
[BUG]config.ini custom gcode custom_label_2:Init sd card uses incorrect gcode

### ISSUE THREAD

**Issue by q32103940** [bigtreetech/BIGTREETECH-TouchScreenFirmware#783]
### Description
config.ini file in \BIGTREETECH-TouchScreenFirmware-master\Copy to SD Card root directory to update - Unified Menu Material theme. Under custom gcode, there's a custom label to Init sd card, but the actual gcode is for home & ABL.

custom_label_2:Init sd card
custom_gcode_2:G28\nG29\nG0\n

### Steps to reproduce

Check config,ini file

**Expected behavior**
custom_gcode_2:M21

**Actual behavior**
custom_gcode_2:G28\nG29\nG0\n

### Hardware Variant
N/A

**Comment by guruathwal** [comment]
Duplicate of #779

**Comment by guruathwal** [comment]
@q32103940  this issue has been fixed. please close the issue.
