### ISSUE TITLE
wil not save ofset setting for abl

### ISSUE THREAD

**Issue by bramankersmit** [bigtreetech/BIGTREETECH-TouchScreenFirmware#792]
### Steps to reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior**

**Actual behavior**

### Additional Information
* Include a ZIP file containing your `Configuration.h` or use [Pastebin](https://pastebin.com/) and paste a link in this issue.
* Provide pictures or links to videos that clearly demonstrate the issue.

**Comment by oldman4U** [comment]
Hello bramankersmit.

Have you tried to define the offset in firmware and to save it to EEPROM after that?

**Comment by bramankersmit** [comment]
I have tried to save to the EEPROM and then it worked  thank you
