### ISSUE TITLE
TFT35 KNOB

### ISSUE THREAD

**Issue by SKOREIKO** [bigtreetech/BIGTREETECH-TouchScreenFirmware#793]
Im Pretty new with this, but i see some people with there tft35 and the knob is lit up,
can someone explain how i do this ?

**Comment by SeanLMH** [comment]
If I recall this correctly it's menu -> settings -> feature. There should be an option there to set the knob colour. If it's not there, you may need to update your firmware on the TFT35.

**Comment by SKOREIKO** [comment]
thanks for the response, when i do that i get a unknown command "m150 r255 u0 p255"

**Comment by SKOREIKO** [comment]
sorry it was m150 R0 U255 B0 P255

**Comment by Tygrys-1** [comment]
Not that setting. You are trying to set the printer's neopixel, which your printer might not have.
Do exactly as @SeanLMH said and search for the "Rotary knob LED" setting. You have to press down icon to browse the feature menu.

**Comment by SKOREIKO** [comment]
thanks @SeanLMH and @Tygrys-1 ill have a look.

**Comment by SKOREIKO** [comment]
i found a older version that works, i guess the newest doesn't , but thanks again

**Comment by oldman4U** [comment]
Hello SKOREIKO.

There is a bug in v26.x which is fixed in Master already and which will be part of the next regular release.

Please close a ticket in case you do not need it anymore.

Thank you
