### ISSUE TITLE
[Q] Firmwares for BIGTREETECH TFT43 / TFT50 / TFT70 V3.0 ?

### ISSUE THREAD

**Issue by Guilouz** [bigtreetech/BIGTREETECH-TouchScreenFirmware#798]
Hi,

Where I can find new firmwares for BIGTREETECH TFT43 / TFT50 / TFT70 V3.0 ?

![H156727191654410b9f57383c83940b76j](https://user-images.githubusercontent.com/12702322/84697464-7694e200-af4e-11ea-8cb2-4027603a0a05.jpg)

![Hbfda78369d8345e498a3ca9b095e5360W](https://user-images.githubusercontent.com/12702322/84697429-65e46c00-af4e-11ea-944b-16e9207facea.jpg)

**Comment by oldman4U** [comment]
Hi.

Do you have such a hardware?

**Comment by Guilouz** [comment]
> Hi.
> 
> Do you have such a hardware?

I have order it.

**Comment by max5962** [comment]
is preview model will be available on other screen ?

**Comment by Guilouz** [comment]
@bigtreetech Any info please ?

**Comment by whitedavil** [comment]
Good morning.
I have already buy this new TFT50 screen. Can you upload the firmware for customization? 
Thanks

**Comment by Guilouz** [comment]
No reply on GiHub, Facebook, mail and Aliexpress MP where I buy it... It's not very serious... @bigtreetech

**Comment by Tygrys-1** [comment]
I think they are working on the sale now. After the sale ends, things should get back to normal. As the software will be probably the same, you may try to use config.ini to customize. As the icons for TFT70 are already in the repository, I think that they will update the variants and the rest of the stuff here.

However, I'll not expect bells and whistles from the new boards. They seam to be just bigger LCD's in size. Just my thougts based on the pictures and advertising.

**Comment by bigtreetech** [comment]
The firmware of TFT43/50/70 will soon be merged into this repository

**Comment by max5962** [comment]
> The firmware of TFT43/50/70 will soon be merged into this repository
Thanks !! Compatible with tft35 e3 screen ?

**Comment by luc-github** [comment]
@bigtreetech any timeframe ? I need to see why ESP3D freeze the TFT when sending `M117 hi `
and why some commands like `MD SD:` `M20 U:` `M115 TFT` are ignored
Thank you

**Comment by Guilouz** [comment]
> The firmware of TFT43/50/70 will soon be merged into this repository

Soon it means everything and nothing... I receive my TFT43 in few days and I would like to be able to use it!

**Comment by bigtreetech** [comment]
@luc-github hello,  It will be uploaded after cleaning up today

**Comment by oldman4U** [comment]
@Guilouz 

This software is Open Source, so it is made by unpaid members of this community. It would be great if you could think about how YOU can help to make this work (or to improve it), until you get your new display.

Thank you

**Comment by luc-github** [comment]
@bigtreetech thank you, seems issue was with FW provided with screen - no problem with latest precompiled neither sources

**Comment by haplopeart** [comment]
I just got my TFT 70 and tried to flash the screen.  It seems to start, but ends up at iLLegal flash App.  Now I am stuck there.

I used a 8GB SD (same one I use for my TFT 3.5 E3).  To be clear I wiped out the files for the TFT3.5 first, I loaded the new files for the TFT 70.

Any assistance or way back to a working screen would be great.

**Comment by oldman4U** [comment]
Hi. Have you tried the reset.txt like described?

**Comment by haplopeart** [comment]
reset.txt is a calibration reset to my knowledge.  It has nothing to do with a failed flash.  I tried it none-the-less...No Good

**Comment by oldman4U** [comment]
Maybe you can attach a picture so we can see where you stuck.

haplopeart <notifications@github.com> schrieb am Fr. 17. Juli 2020 um 18:02:

**Comment by Vyacheslav23** [comment]
#Почему экран BigTreeTech_TFT70_V3.0 перестает работать когда в разъем WIFI на экране ставиться модуль ESP01 с  работающим на другом принтере проект WIFI ESP3D?  Затыкается, пишет нет связи. Как исправить эту проблему?

**Comment by Vyacheslav23** [comment]
Почему экран BigTreeTech_TFT70_V3.0 перестает работать когда в разъем WIFI на экране ставиться модуль ESP01 с  работающим на другом принтере проект WIFI ESP3D?  Затыкается, пишет нет связи. Как исправить эту проблему?
