### ISSUE TITLE
[FR] ( stealth mode with lcd_idle_brightness = 0)

### ISSUE THREAD

**Issue by Evg33** [bigtreetech/BIGTREETECH-TouchScreenFirmware#803]
I would like to be able to completely turn off the screen at lcd_idle_brightness = 0.
Something like stealth mode.
Now it is 5% and it can be seen.

**Comment by Tygrys-1** [comment]
Here is Q&D solution to your request:
Go to TFT\src\User\Hal\LCD_Init.h and change
 #define LCD_5_PERCENT    5
to
 #define LCD_5_PERCENT    0

Then built firmware, copy to SD card, insert in TFT, turn on the printer. Do not try to set non-idle brightness to 5%. ;-)
