### ISSUE TITLE
[BUG] TFT35 E3 V3 Knob axis is metall :O

### ISSUE THREAD

**Issue by Wesie** [bigtreetech/BIGTREETECH-TouchScreenFirmware#809]
It's not a mistake, its not Works as designed... its a bug

Today I received the TFT35 E3 V3 Display.
Surprise for me: The LED are under the knob (Plastik Cover) but the axis from the encoder is from metal *upps*

In a normal case the axis is from transparent plastic, so that the PCB can be covered without any issues... In this case I must leave (how many???) mm space for the light - if a small procent cames out of the hole and could passed the knob
It's a no go .....

**Comment by Tygrys-1** [comment]
It is called E3, because it is designed for Ender 3, where it fits and lights as it should. The Ender 3 case hole for encoder is 10 mm diameter.

**Comment by Wesie** [comment]
It's a valid argument, 
on other side, it will be much better - also for user, which want to use the Display in an own project, if the axis will be transparent and the light goes through the axis to the knob.
