### ISSUE TITLE
Changing the temp while heating up for a print is ignored

### ISSUE THREAD

**Issue by oldman4U** [bigtreetech/BIGTREETECH-TouchScreenFirmware#813]
until the Temperature has been reached

### Steps to reproduce
Start a print from TFT USB
While heating up the bed or the nozzle, change the temp of the element which is heating at that time
**Expected behavior**
I would expect that if I lower the temperature, the heating stops at that temp, like it worked in previous versions

**Actual behavior**
It heats up to the temp defined in gcode

### Hardware Variant
TFT35 E3 v3
### TFT Firmware Version & Main Board Firmware details
Latest version from today 2.7.2020

**Comment by luc-github** [comment]
@oldman4U I think it is Marlin behavior
how did you start heating ? depending of heat command :` waiting until reach temp` or `no waiting`, Marlin does not allow any command when heating 
M104 / M140  (not waiting) allow to change temp and send any gcode 
M109  / M190 (waiting until reach) does not allow any GCODE until temperature is reached - you will get `echo:busy: processing` as answer

**Comment by oldman4U** [comment]
Hi Luc.

Thank you for your answer.

I started the print by selecting the gcode on the USB Stick, so without preheat. The file is attached.

In the meantime I downgraded to a TFT version from June, and there I can not see this behaviour. There the bed stops heating at 40 for example, when I change it from 60 to 40 before the bed reaches 40 degrees.


[CE3_Spare.gcode.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4865873/CE3_Spare.gcode.zip)

**Comment by oldman4U** [comment]
Just tested the build from yesterday and there it also works correctly.

**Comment by luc-github** [comment]
so you mean no more issue?

**Comment by oldman4U** [comment]
Using a version up and including yesterday, July 1st, everything is ok.

Using the version from today, July 2nd, the reported bug exists.

This is reproducible by changing the firmware only. Everything else remains the same. Printer hard and software Marlin Version from June 26th, gcode file - everything.

So the reported issue has to be related to the version uploaded today.

**Comment by bigtreetech** [comment]
Confirm this bug, Fix it now

**Comment by oldman4U** [comment]
Thank you. The changes made by Gurmeet are great so i hope this fix comes soon. 

Thank you

**Comment by bigtreetech** [comment]
Hello,  It should be fixed in #818

**Comment by oldman4U** [comment]
Hi.

Thank you. I will download and test asap.

**Comment by oldman4U** [comment]
Hi.

Thank you, problem solve, so I will close this ticket.

@bigtreetech
A little bit off topic. I tried to close unneeded tickets in some of the repositories (repos of hardware which I also own) by asking the owners to close them. Some did it, some not. Those which are not reacting any more I made a notice to you bigtreetech and asked to close it. Unfortunately nobody closed it so far.

I believe the ticket system will become unusable soon and we saw some tickets related to the same topic, because nobody will search several pages to see if the issue has been reported before. Maybe you can take a few minutes to close those tickets.

Kind regards

**Comment by bigtreetech** [comment]
Thank you， I will review this issues  and close that unneede.

**Comment by oldman4U** [comment]
This would be great. I tried to notify you only for tickets where the user
do not react and which are not important any more because they are fixed in
the meantime or not related.

But please review and let me know in case i made a mistake

Thank you

BigTreeTech <notifications@github.com> schrieb am Sa. 4. Juli 2020 um 03:37:

**Comment by oldman4U** [comment]
Seems this bug comes back once per month. Release tested from August 2nd.

**Comment by oldman4U** [comment]
Strange. Updated to the firmware from August 3rd and it works again....

Will keep an eye on it.
