### ISSUE TITLE
Send: M420V1  Recv: echo:Invalid mesh.  Recv: echo:Bed Leveling OFF  

### ISSUE THREAD

**Issue by Yaha500** [bigtreetech/BIGTREETECH-TouchScreenFirmware#815]
### Steps to reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior**

**Actual behavior**

### Additional Information
* Include a ZIP file containing your `Configuration.h` or use [Pastebin](https://pastebin.com/) and paste a link in this issue.
* Provide pictures or links to videos that clearly demonstrate the issue.

**Comment by bigtreetech** [comment]
This means that Marlin has not detected the leveling data and needs G29 to leveling again
