### ISSUE TITLE
[BUG] (short deIn Marline alignment enabled control on the axes is not possible

### ISSUE THREAD

**Issue by Yaha500** [bigtreetech/BIGTREETECH-TouchScreenFirmware#820]
In Marline, alignment is enabled, axis control is not possible, the Z axis is raised by 10 mm then: Error:Printer halted. kill called!. When you turn on the printer or switch to Marlin and back, a message is sent. Echo: M92 X80. 00 Y80.00 Z400.00 E97. 00
Echo: invalid grid.
Mistake:bed alignment could not be enabled
Echo-leveling of the bed
Echo:The altitude of damping off

**Comment by Tygrys-1** [comment]
It will help if you describe your printer hardware, printer's software version, TFT type and TFT software version. Then, describe step by step what you do, what you expect and what is exactly wrong, in the most simple and undersandable form. Add the customizations you made to configs.  There is a form to fill up when writting an issue here, and it is for a reason. 

There is a bunch of helpful people here, but no wizzards with glass balls to see things you have not told.

As a generall rule - upgrade everything to the latest versions and check, if the problem still persists. Try to isolate problem as i.e. Marlin related or TFT related.
