### ISSUE TITLE
[FR] (feature request title)100mm move on the buttons

### ISSUE THREAD

**Issue by MontyFlange** [bigtreetech/BIGTREETECH-TouchScreenFirmware#822]
Any chance we could have movement of 100mm . Unloading a bowden at 10mm a go is boring. Also on a 400mm Z getting it to the top takes ages. 

Thanks

**Comment by NicoletoAerials** [comment]
Hi, I am new here and do not know how to post the enhancement. I made some changes in a couple of files, and I have it working for the “move” and “extrude” menus.

**Comment by MontyFlange** [comment]
Ohh nice can you send it to me ?

MontagueFlange@gmail.com

**Comment by oldman4U** [comment]
Hi.

This is implemented in the latest version of the firmware. Have you been able to install it? If not please let us know how we can help. If yes, please close this ticket.

Thank you

**Comment by oldman4U** [comment]
@MontyFlange 

Close this ticket

**Comment by MontyFlange** [comment]
Thanks
