### ISSUE TITLE
[Q] onboard SD disappeared from its printing screen

### ISSUE THREAD

**Issue by panlamb81** [bigtreetech/BIGTREETECH-TouchScreenFirmware#823]
Good evening. I recently bought the skr mini e3 v2.0 together with the TFT35 E3 screen.
After it made the official firmware upgrades, the selection of the onboard SD disappeared from its printing screen.
Do you know if this is some kind of a bug or how can it be fixed?
Thank you in advance.

**Comment by Tygrys-1** [comment]
You have to use the latest bugfix Marlin, or put this in config.ini

onboard_sd_support:1

See #775 and #770

**Comment by panlamb81** [comment]
Thank you !!!  I have lost it and the language selection is directly in English.

**Comment by panlamb81** [comment]
Thank you very much for your help, everything is fine
