### ISSUE TITLE
[Q] Max. Memory /Flash size for Icon? (TFT 35 V3)? 

### ISSUE THREAD

**Issue by Wesie** [bigtreetech/BIGTREETECH-TouchScreenFirmware#824]
What is the max memory size for the Icons in the flash? 
Background is: if I add some icons, the Logo is a little bit brocken in the first few lines. 
All other pages looks OK. 
If I update the Logo alone, the Logo during boot is ok, but on the status screen the Info menu on place for Icon 5&6 is a little broken.
This one let me think, that I've reached the max of memory for the icon. 
What is the mx. usable size for Icon on the TFT 35 V3 (in the last released FW 2.61)

**Comment by bigtreetech** [comment]
The Max Flash size is 8Mbyte.

**Comment by Wesie** [comment]
thx a lot. After reduce the icons, all things are ok
