### ISSUE TITLE
[Q] USB Stick Marlin

### ISSUE THREAD

**Issue by el-quique** [bigtreetech/BIGTREETECH-TouchScreenFirmware#825]
Hi. I wanted to know if I can access the USB Stick in Marlin Mode on a TFT 24 v1.1, for printing file

**Comment by bigtreetech** [comment]
No, because of 
  1. Marlin does not support accessing the U disk at present. 
  2. The U disk of tft24 is not connected to the motherboard running Marlin through EXP-1 & EXP-2

**Comment by el-quique** [comment]
OK. Thx Very Much
