### ISSUE TITLE
Firmware Install Issue Landing Screen Broken 

### ISSUE THREAD

**Issue by sdharvey28** [bigtreetech/BIGTREETECH-TouchScreenFirmware#831]
![image](https://user-images.githubusercontent.com/68089598/87105416-c5612f00-c20f-11ea-9522-d026ce1fc7d7.png)

After Installing the firmware multiple times I still get this screen. I'm worried that my screen is possibly broken but I do get the BIQU boot screen fine just the operating screen is broken. Any help is much appreciated. I'm using a BTT SKR 1.4 Turbo board if there is a bug between this screen and board

**Comment by oldman4U** [comment]
Hi. 

Please put the firmware, the config.ini and the TFT35 folder which includes the bmp and font folder on the sd card and flash again. 

Let us know if this solves your problem

**Comment by gordo3di** [comment]
Had the same issue a few times now with the latest firmware. I had to repload both the bmp and font folders (sometimes more than once).

**Comment by sdharvey28** [comment]
Same issue. Is there a way to take it to factory settings that way  I can retry with a blank slate.

**Comment by oldman4U** [comment]
@sdharvey28 

Make an empty file named reset.txt on the SD card and proceed like doing a firmware update. 

Which SD cards are you using for firmware update ( size and format)?

**Comment by sdharvey28** [comment]
I bought a 64GB Sd card its file format is exFAT. Is there a way to reformat it to something else? Also the reset did not help and I tried another zip file of firmware as well and did not work.

**Comment by oldman4U** [comment]
Try the SD card which came with the display as it is, or another 8 (16GB max) SD card card and format it to FAT 32 using your PC or Mac. Using such a card i was able to make 100+ firmware updates so far. In case you have the display mounted in a metal frame- remove it and try again.

Let me know

**Comment by Tygrys-1** [comment]
You have to use FAT32 formated SD. Up to 32MB tested with no problem.

**Comment by oldman4U** [comment]
MB>GB i guess😎

Tygrys-1 <notifications@github.com> schrieb am Sa. 11. Juli 2020 um 12:57:

**Comment by sdharvey28** [comment]
![3D Printer Screen Works](https://user-images.githubusercontent.com/68089598/87227843-4b858e80-c352-11ea-8d6a-7748763758a7.PNG)

Finally got this to work with a 32GB SD card with FAT32 format. Thanks for everyone's help I was starting to go crazy.

**Comment by Tygrys-1** [comment]
Your "Leveling" icon looks incorrect.

**Comment by oldman4U** [comment]
I would recommend to upload the round miracle. It looks MUCH better.

**Comment by oldman4U** [comment]
@sdharvey28 

You asked for help and we helped you.

Now i ask you to close this ticket, because it is solved.

It is very unfriendly to ignore us, where we helped you in our spare time

Close this ticket now.

**Comment by oldman4U** [comment]
@bigtreetech 

Please close this ticket

**Comment by oldman4U** [comment]
@bigtreetech 

Please close this ticket

Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
