### ISSUE TITLE
[FR] IDEA: Minor Update Iconpack 'The Round Miracle' - Update for SW v26.x

### ISSUE THREAD

**Issue by Acenotass** [bigtreetech/BIGTREETECH-TouchScreenFirmware#832]
Dedicated to all those who were waiting for the update of my iconpack ;)
Small update of just one preheat icon (3 icons removed)

![All Icons26 x](https://user-images.githubusercontent.com/44540957/87143993-dae65f80-c2c8-11ea-8e98-b387beda48f1.png)

[TFT24 Iconpack 'The Round Miracle' by Acenotass for v26.x.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4902500/TFT24.Iconpack.The.Round.Miracle.by.Acenotass.for.v26.x.zip)
[TFT28 Iconpack 'The Round Miracle' by Acenotass for v26.x.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4902498/TFT28.Iconpack.The.Round.Miracle.by.Acenotass.for.v26.x.zip)
[TFT35 Iconpack 'The Round Miracle' by Acenotass for v26.x.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4902499/TFT35.Iconpack.The.Round.Miracle.by.Acenotass.for.v26.x.zip)

**Comment by labotecno** [comment]
thank you very much for your great work ! can you give me a tip how you make your iconpack ? program ?

**Comment by Acenotass** [comment]
use any graphic editor, I used GIMP

**Comment by labotecno** [comment]
> 
> 
> use any graphic editor, I used GIMP

great ! you make icon from something ? thank you

**Comment by Acenotass** [comment]
> > use any graphic editor, I used GIMP
> 
> great ! you make icon from something ? thank you


You can see the ideas of ready-made icons, which are many on the Internet. Combine your ideas and the ideas of others to get what you want. It’s important that the general style is maintained, so that the author’s idea is visible.

**Comment by gordo3di** [comment]
This is useful too. Its a tool to easily replace icons

https://github.com/bigtreetech/BigtreeDesignAssistant

**Comment by Acenotass** [comment]
@gordo3di Very crude software, does not take into account the latest firmware. Suitable only to get a general impression of the appearance.

**Comment by radek8** [comment]
The icons are great
Thank you

**Comment by Mistigris18** [comment]
Merci,  
C'est top. Beau travail j'adore 😉👍

**Comment by radek8** [comment]
Hi @Acenotass 
Will you add new icons?
global_chamber.bmp
chamber.bmp
point_5.bmp
Thank you

**Comment by Acenotass** [comment]
Hi @radek8
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/885
