### ISSUE TITLE
[BUG] Failed to compile TFT\src\User\API\parseACK.c:429:54: error: 'breakAndContinue' undeclared (first use in this function)

### ISSUE THREAD

**Issue by q32103940** [bigtreetech/BIGTREETECH-TouchScreenFirmware#833]
### Description
TFT\src\User\API\parseACK.c: In function 'parseACK':
TFT\src\User\API\parseACK.c:429:54: error: 'breakAndContinue' undeclared (first use in this function)
                     textSelect(LABEL_CONFIRM), NULL, breakAndContinue, NULL,NULL);
                                                      ^~~~~~~~~~~~~~~~
TFT\src\User\API\parseACK.c:429:54: note: each undeclared identifier is reported only once for each function it appears in
*** [.pio\build\BIGTREE_TFT35_E3_V3_0\src\src\User\API\parseACK.o] Error 1
================================================================================= [FAILED] Took 3.37 seconds =================================================================================

### Steps to reproduce

1. Attempt to build TFT35_E3_V3_0 with vscode 

**Expected behavior**
Compiles successfully.

**Actual behavior**
Fails to compile with following output:
Processing BIGTREE_TFT35_E3_V3_0 (platform: ststm32; framework: stm32cube; board: STM32F103VC)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/ststm32/STM32F103VC.html
PLATFORM: ST STM32 6.1.0 > STM32F103VC (48k RAM. 256k Flash)
HARDWARE: STM32F103VCT6 72MHz, 48KB RAM, 256KB Flash
DEBUG: Current (blackmagic) External (blackmagic, cmsis-dap, jlink, stlink)    
PACKAGES:
 - framework-stm32cube 2.0.181130
 - toolchain-gccarmnoneeabi 1.70201.0 (7.2.1)
Warning! Cannot find a linker script for the required board! Firmware will be linked with a default linker script!
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 11 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <BSP-Common>
Building in release mode
Compiling .pio\build\BIGTREE_TFT35_E3_V3_0\src\src\User\API\parseACK.o
Compiling .pio\build\BIGTREE_TFT35_E3_V3_0\src\src\User\Fatfs\myfatfs.o
Compiling .pio\build\BIGTREE_TFT35_E3_V3_0\src\src\User\Hal\LCD_Init.o
Compiling .pio\build\BIGTREE_TFT35_E3_V3_0\src\src\User\Hal\STM32_USB_HOST_Library\Class\MSC\src\usbh_msc_bot.o
Compiling .pio\build\BIGTREE_TFT35_E3_V3_0\src\src\User\Hal\STM32_USB_HOST_Library\Class\MSC\src\usbh_msc_core.o
Compiling .pio\build\BIGTREE_TFT35_E3_V3_0\src\src\User\Hal\STM32_USB_HOST_Library\Class\MSC\src\usbh_msc_scsi.o
Compiling .pio\build\BIGTREE_TFT35_E3_V3_0\src\src\User\Hal\STM32_USB_HOST_Library\Core\src\usbh_core.o
Compiling .pio\build\BIGTREE_TFT35_E3_V3_0\src\src\User\Hal\STM32_USB_HOST_Library\Core\src\usbh_hcs.o
TFT\src\User\API\parseACK.c: In function 'parseACK':
TFT\src\User\API\parseACK.c:429:54: error: 'breakAndContinue' undeclared (first use in this function)
                     textSelect(LABEL_CONFIRM), NULL, breakAndContinue, NULL,NULL);
                                                      ^~~~~~~~~~~~~~~~
TFT\src\User\API\parseACK.c:429:54: note: each undeclared identifier is reported only once for each function it appears in
*** [.pio\build\BIGTREE_TFT35_E3_V3_0\src\src\User\API\parseACK.o] Error 1
================================================================================= [FAILED] Took 3.37 seconds =================================================================================

### Additional Information
* Include a ZIP file containing your `Configuration.h` or use [Pastebin](https://pastebin.com/) and paste a link in this issue.
* Provide pictures or links to videos that clearly demonstrate the issue.

**Comment by oldman4U** [comment]
Hi

What is the status of this issue?

Please let us know

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
