### ISSUE TITLE
[FR] Filament change buttons

### ISSUE THREAD

**Issue by bigtreeteche3** [bigtreetech/BIGTREETECH-TouchScreenFirmware#834]
To make the touch setup complete i would suggest to add the filament change option like under the normal marlin setup so that people with bowden setups can load and unload with one click. 

As an alternative would it be able to mod the aktual load and unload funktion so that instead of just 10mm at the time it feeds 400 mm and more ? I can't find these line in the code...

**Comment by oldman4U** [comment]
You are too late: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/769

**Comment by oldman4U** [comment]
Hi.

This is covered in the pinned Read me ticket and in some other tickets.

So please close this ticket

**Comment by oldman4U** [comment]
And now it is also covered in the pinned feature request ticket #1170 

PLEASE close this ticket

Thank you

**Comment by oldman4U** [comment]
This feature is available in PR #1272. 

Please check
