### ISSUE TITLE
TFT35 V3.0  and TFT24 V1.1

### ISSUE THREAD

**Issue by guenex** [bigtreetech/BIGTREETECH-TouchScreenFirmware#84]
Both TFTs  (Last Firmware) stops printing from SD and USB at random layer height !  Please fix.

**Comment by davehardy20** [comment]
I have also had this issue, with TFT24 v1.1, since a firmware update yesterday.

**Comment by Mucho79** [comment]
Same problem here. TFT24 v1.1 with V1.1.24.2. Both SD and USB stop printing in TFT-Mode. Printing from SD in Marlin Mode seems to work.

**Comment by guenex** [comment]
BTT are you ignoring us?

**Comment by Nino97** [comment]
same problem I on TFT35 V3

**Comment by lijinlin19970813** [comment]
You can  try to disable the related content of "Host Keepalive" in configuration.h. I think your problem can be solved.
