### ISSUE TITLE
TFT35_V3.0_E3 - SKR 1.4 Turbo & Klipper firmware

### ISSUE THREAD

**Issue by witte1000** [bigtreetech/BIGTREETECH-TouchScreenFirmware#849]
Hello BigTreeTech,

First of all Thank you very much for making wonderful products for the 3D community !!!
I love it very much and is very much appreciated !!!

However I do encounter some problems when setting up the TFT35_V3.0_E3 on the SKR 1.4 Turbo with klipper firmware
- First it keeps beeping when powering on ? driving me complete nuts ...
-  When updating to BIGTREE_TFT35_V3.0_E3.26.1.bin +  TFT/src improve st7920 simulator for klipper, its stuck and having 2 icon's => 1 usb mode and something else I don't remember and cannot simulate it again after flashing next point. 
- When updating to BIGTREE_TFT35_V3.0_E3.26.1.bin +  TFT/src improve st7920 simulator for klipper + TFT35 unified menu it hangs on the startup screen where I can choose between Marlin mode or Touch mode, it stuck can not touch or do anything with the knob ?
However the firmware did load like expected no error.
When pulling out the EXP1 finally the buzzer stop and I can choose between Marlin and Touch mode, however on marlin mode it's a black screen also when moving the knob, but will be normal because of the EXP1 is pull out.
- So it's very confusing me how to proper setup the TFT35 ?
               - What do I need for setting up for klipper ?
                  - BIGTREE_TFT35_V3.0_E3.26.1.bin +  TFT/src improve st7920 simulator for klipper
                    or
                  - BIGTREE_TFT35_V3.0_E3.26.1.bin +  TFT/src improve st7920 simulator for klipper + TFT35 unified menu

- My klipper config
       - commit 1c508c38aa424f914c4c9843330e0f4849e4d26f (HEAD -> master, origin/master, origin/HEAD)
         Author: Kevin O'Connor <kevin@koconnor.net>
         Date:   Thu Jul 16 12:59:17 2020 -0400

[display]
lcd_type: st7920
cs_pin: EXP1_4
sclk_pin: EXP1_5
sid_pin: EXP1_3
encoder_pins: ^EXP2_3, ^EXP2_5
click_pin: ^!EXP1_2
#kill_pin: ^!EXP2_8

[output_pin beeper]
pin: EXP1_1

########################################
# EXP1 / EXP2 (display) pins
########################################

[board_pins]
aliases:
    # EXP1 header
    EXP1_1=P1.30, EXP1_3=P1.18, EXP1_5=P1.20, EXP1_7=P1.22, EXP1_9=<GND>,
    EXP1_2=P0.28, EXP1_4=P1.19, EXP1_6=P1.21, EXP1_8=P1.23, EXP1_10=<5V>,
    # EXP2 header
    EXP2_1=P0.17, EXP2_3=P3.26, EXP2_5=P3.25, EXP2_7=P1.31, EXP2_9=<GND>,
    EXP2_2=P0.15, EXP2_4=P0.16, EXP2_6=P0.18, EXP2_8=<RST>, EXP2_10=<NC>
    # Pins EXP2_1, EXP2_6, EXP2_2 are also MISO, MOSI, SCK of bus "ssp0"

I have the EXP1 - EXP2 and the TFT connector's connected to the SKR 1.4 Turbo motherboard.

I do understand that klipper is not yet supporting Touch mode, but I do need to see something, no ?
And specially stopping the buzzer noise ....

Thank you in advance.

Kind Regards,

**Comment by damanbaird** [comment]
I cant get mine to connect, what instructions did you use? Got Marlin on it, but rather use klipper.
