### ISSUE TITLE
[BUG] The pop-up window cannot be confirmed

### ISSUE THREAD

**Issue by radek8** [bigtreetech/BIGTREETECH-TouchScreenFirmware#851]
I will insert an onboard SD card in a format that is not supported.
I will choose to print from the onboard SD card.
A popup window will appear, but cannot be confirmed.

![error](https://user-images.githubusercontent.com/46979052/83682178-d8b32600-a5e3-11ea-8a11-aa321178ad52.jpg)

_Originally posted by @radek8 in https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/733#issuecomment-638425372_

**Comment by bigtreetech** [comment]
Yes, Onboard SD needs a lot of optimization, and the pop-up window logic needs to be reorganized to separate the front and backend.
  It will be fixed later. Thank you for your feedback
