### ISSUE TITLE
[BUG] E0 never re-selected after chaning to another extruder.

### ISSUE THREAD

**Issue by VE5BNC** [bigtreetech/BIGTREETECH-TouchScreenFirmware#854]
I running a printer with two extruder.   When manually extruding,  

### Steps to reproduce

1. Choose the Extrude menu
2. Pres Extrude. E0 will extrude filament
3. Choose the second nozzle
4. Press Extrude.  E1 will extrude filament.
5. Choose the first nozzle.
6. Press Extrude.  E1 will extrude instead of E0

**Expected behavior**
The screen should send a T# GCODE each time it sends a manual extrude command.

**Actual behavior**
The screen sends a T# for all extruder except when E0 is selected.

### Hardware Variant
TFT35 V3 and TFT35 V2

### TFT Firmware Version & Main Board Firmware details
Freshly compiled version as of July 20 2020. 3.0.26 and 2.0.26

### Additional Information
I verified that it does not send a T0 by monitoring the serial communication between the board and the scren.

I was able to correct the behaviour by editing BIGTREETECH-TouchScreenFirmware-master\TFT\src\User\Menu\Extrude.c and commenting out line 133 as shown below.

129	    if(extrudeCoordinate != eTemp)
130	    {
131	      extrudeCoordinate = eTemp;
132	      extrudeCoordinateReDraw(true);
133	//      if(item_extruder_i != heatGetCurrentToolNozzle() - NOZZLE0)
134         storeCmd("%s\n", tool_change[item_extruder_i]);
135       storeCmd("G0 E%.5f F%d\n", extrudeCoordinate, infoSettings.ext_speed[item_speed_i]);
136     }

**Comment by bigtreetech** [comment]
Confirmed it's a bug of SINGLENOZZLE.  This happens when there are multiple extruders with only one hotend.  will fixed later.

**Comment by VE5BNC** [comment]
Thanks
