### ISSUE TITLE
Resume after filament runout.

### ISSUE THREAD

**Issue by Thijsvanzwam** [bigtreetech/BIGTREETECH-TouchScreenFirmware#859]
I connected the filament runout sensor (switch-type) to the TFT3,5. When filament runs out it works flawless. Nozzle moves up and out of the way, resume button appears on the screen.

When I press resume the nozzle moves back to the print, poops some filament and continues the print.

But the it moves up again, saying the filament is runout and moves out of the way again.

When I press "pause" during a print and the press resume it works just fine...

added my config files.

Can anyone have a look what I might be missing?

[Archief.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/4960283/Archief.zip)

**Comment by bigtreetech** [comment]
Hello, This is a bug and it should be fixed in #857

**Comment by gordo3di** [comment]
Confirmed, works great now.

**Comment by Thijsvanzwam** [comment]
you mean it works in the latest firmware?

**Comment by gordo3di** [comment]
Yeah they fixed it with this commit. Basically after it triggers it sets the runout back to false. That was missing.

https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/857/commits/22dfa8566d371e26d8e24c297f0da8d6e6b2c490

**Comment by Thijsvanzwam** [comment]
I agree.
tested with latest firmware and it is fixed.
I'll close the ticket.

**Comment by Thijsvanzwam** [comment]
only thing now is the big blob of filament deposited on the point it resumes...
a filament purge in a corner would be nice...

**Comment by gordo3di** [comment]
@Thijsvanzwam Agreed. I'll look into fixing that today. It's very annoying.

**Comment by Thijsvanzwam** [comment]
that would be great!
I guess that a small introline somewhere in the right corner (when facing the printer) would be nice, as the initial introline in most start code is done on the left.

**Comment by gordo3di** [comment]
@Thijsvanzwam @bigtreetech 

Lol that was easy. I would submit a commit however i'm still trying to figure out github and using it with VS code.
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/866

**Comment by drlohwk** [comment]
Which firmware version should I use? Mine still cannot resume printing and keep triggering filament runout. Also a big blob of plastic deposited on the print. Can u please point me to the right direction? Thanks.

**Comment by Thijsvanzwam** [comment]
I use the latest self compiled.

**Comment by oldman4U** [comment]
Hi. What is the status of the ticket?
