### ISSUE TITLE
Font Change?

### ISSUE THREAD

**Issue by jhnnyn** [bigtreetech/BIGTREETECH-TouchScreenFirmware#86]
I've been trying to change the font on my screen. I can't figure out what type of file the font is stored as. The readme says it's a bitmap font, but I've tried several converters and viewers for bitmap and raster fonts but can't seem to open them. Is there a special program used to view/edit the fonts?

**Comment by thisiskeithb** [comment]
Take a look at https://github.com/bigtreetech/BIGTREETECH-TFT35-V1.2/issues/41, specifically [this comment](https://github.com/bigtreetech/BIGTREETECH-TFT35-V1.2/issues/41#issuecomment-508440690) as it has a link to font templates you can open with SG Bitmap Font editor.

**Comment by thisiskeithb** [comment]
FYI: Some things have changed in recent commits related to font handling, so the fonts above no longer work. Hopefully it'll get resolved soon!
