### ISSUE TITLE
[Q] (Print finished dialog and jump back to Info Screen on TFT35)

### ISSUE THREAD

**Issue by KingBonecrusher** [bigtreetech/BIGTREETECH-TouchScreenFirmware#865]
Is there a way to get an print finished dialog and by click on OK you jump back to the Info screen.

At the moment the print is finished and you can only click BACK or PAUSE. By Click on BACK you go back on the SD Card.  PAUSE did not do anything.

BIGTREE_TFT35_V3.0.26.x

**Comment by oldman4U** [comment]
Hi KingBonecrusher.

This is a more than useful feature and i hope this will be available one day.

It would be great if you could close this ticket. Your feature request is received.

Thank you

**Comment by oldman4U** [comment]
Hi. Could you please change the label to feature request.

Thank you
