### ISSUE TITLE
[BUG]Process display errors

### ISSUE THREAD

**Issue by DrumClock** [bigtreetech/BIGTREETECH-TouchScreenFirmware#868]
### Fan speed is not displayed when printing.

![IMG_20200725_193716](https://user-images.githubusercontent.com/64655979/88463984-4c243600-ceb7-11ea-988c-ad51049aa0b6.jpg)

### No other extruders are shown.

![IMG_20200725_193822](https://user-images.githubusercontent.com/64655979/88463988-521a1700-ceb7-11ea-83d4-e0df7b86d7ab.jpg)

**Comment by KingBonecrusher** [comment]
You need to patch your Marlin firmware, take a look at:

https://github.com/vgadreau/Marlin/commit/67d436515315301bb855aeb96b314dbf383a1b31?diff=unified

**Comment by radek8** [comment]
Compile the new FW to display the fan speed.
Compiled BIN files do not contain patch #869 847

**Comment by DrumClock** [comment]
OK, it already works
