### ISSUE TITLE
Unknown command setting LED colour.

### ISSUE THREAD

**Issue by sam01508** [bigtreetech/BIGTREETECH-TouchScreenFirmware#870]
When trying to change the colour of the led for the rotary encoder you get an unknown error M150 RO UO B255 P255. Any menu item in the led section gives you this error. You can activate from the machine menu? and change the colour but not in the actual led colour section.

** Assuming this is to control that and not other lighting as I’m unsure at this point in time.**

**You also can't toggle between Marlin mode and Bigtreetech mode using the rotary encoder.**
     **Again unless it doesn’t I have seen it used for this**

Led should change colour or be turned on and off.

Error as above.

TFT35 V3.0 E3
Main board is SKR mini E3 V2
Latest Bugfix version of Marlin on the main board, Screen TFT35 precompiled firmware bin, also acted the same with firmware that came with the screen.

**Comment by oldman4U** [comment]
You likely use the wrong control. Can you mAke a Picture  which shows the screen where you try to change the color.

**Comment by oldman4U** [comment]
It is not possible to use encoder to change the mode but use the touchscreen to do so.

**Comment by sam01508** [comment]
Thanks for your input, I think I'm looking at the RGB lighting control I'll try and put a picture up tomorrow just for confirmation. Regarding the rotary encoder, I had seen it used to toggle between the two modes, and then when mine didn't I thought it was an issue. Thanks again.

**Comment by oldman4U** [comment]
Send the picture.

As far as i know the selection using the encoder has been removed because
using the encoder for selecting also changed the feedrate in the
background.

sam01508 <notifications@github.com> schrieb am So. 26. Juli 2020 um 23:49:

**Comment by Tygrys-1** [comment]
The "LED color" item in "Machine" menu is used to change the color of Neopixels attached to the printer.  You have to have leds attached and compile Marlin with the coresponding #define enabled, otherwise the M150 command is not recognized. To change the color of the knob backlight use the "Features" menu.

Encoder is not working on the mode change menu anymore, see #708.

**Comment by sam01508** [comment]
Great thank you that's the thinking I had once I'd had the chance to study it better. Thanks to everyone who took the time to comment I'll close this now.
