### ISSUE TITLE
Please add a status screen

### ISSUE THREAD

**Issue by hapklaar** [bigtreetech/BIGTREETECH-TouchScreenFirmware#88]
To make this screen a little more useful, can you add a status screen that shows while the printer is printing something? I would like to see the details you normally see on an LCD12864 all together on this status screen:

- Printing time
- Progress (when printing from SD)
- Nozzle temperature 
- Bed temperature
- X/Y/Z position
- Fan speed
- Info that can be placed using M117

**Comment by JRoz17** [comment]
This is a must for these screens to be a complete upgrade from the LCD12864

**Comment by arminth** [comment]
I second that!! Without, I am just using the 12864 emulation as I am printing from octoprint.

**Comment by Patag** [comment]
Just pull the latest commits ! It's a giant step for users with this new status screen. This new UI is quite perfect 👍 . I'd just like a small change in fan speed display : a % value would be more user friendly than a 0-255 raw value. Except this, I want to congratulate the devs. Keep on this great work.
Thanks

**Comment by guruathwal** [comment]
@hapklaar  you can close this now... 👍

**Comment by hapklaar** [comment]
@guruathwal right :)

**Comment by JRoz17** [comment]
> Just pull the latest commits ! It's a giant step for  with this new status screen. This new UI is quite perfect  . I'd just like a small change in fan speed display : a % value would be more user friendly than a 0-255 raw value. Except this, I want to congratulate the devs. Keep on this great work.
> Thanks @Msq001

Could you point me to the right direction? Github is not too intuitive for me and I just keep getting lost. I have tried searching for tft35 v2 but does not seem to take me to any update for the screen.

Really appreciate any help you could provide.

**Comment by UnknownHero99** [comment]
> 
> 
> > Just pull the latest commits ! It's a giant step for  with this new status screen. This new UI is quite perfect  . I'd just like a small change in fan speed display : a % value would be more user friendly than a 0-255 raw value. Except this, I want to congratulate the devs. Keep on this great work.
> > Thanks @Msq001
> 
> Could you point me to the right direction? Github is not too intuitive for me and I just keep getting lost. I have tried searching for tft35 v2 but does not seem to take me to any update for the screen.
> 
> Really appreciate any help you could provide.

download code that's available on github and compile it using platformio
