### ISSUE TITLE
[FR] IDEA: Iconpack 'The Round Miracle' - Update for SW v26.x @ 2020/08/05

### ISSUE THREAD

**Issue by Acenotass** [bigtreetech/BIGTREETECH-TouchScreenFirmware#885]
Added 3 new icons (global_chamber.bmp, chamber.bmp, point_5.bmp) in the current update 26.x
Update: Added 10 new Icons for update SW @ 2020/08/02
Update: Added new Icon "Bltouch_Reset.bmp" for update SW @ 2020/08/05

![All Icons26 x](https://user-images.githubusercontent.com/44540957/89126197-b36c6680-d505-11ea-8f9e-07b45b542d23.png)

[TFT24 Iconpack 'The Round Miracle' by Acenotass for v26.x.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5026562/TFT24.Iconpack.The.Round.Miracle.by.Acenotass.for.v26.x.zip)
[TFT28 Iconpack 'The Round Miracle' by Acenotass for v26.x.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5026563/TFT28.Iconpack.The.Round.Miracle.by.Acenotass.for.v26.x.zip)
[TFT35 Iconpack 'The Round Miracle' by Acenotass for v26.x.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5026564/TFT35.Iconpack.The.Round.Miracle.by.Acenotass.for.v26.x.zip)
[TFT43 Iconpack 'The Round Miracle' by Acenotass for v26.x.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5026565/TFT43.Iconpack.The.Round.Miracle.by.Acenotass.for.v26.x.zip)
[TFT50 Iconpack 'The Round Miracle' by Acenotass for v26.x.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5026566/TFT50.Iconpack.The.Round.Miracle.by.Acenotass.for.v26.x.zip)
[TFT70 Iconpack 'The Round Miracle' by Acenotass for v26.x.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5026567/TFT70.Iconpack.The.Round.Miracle.by.Acenotass.for.v26.x.zip)

**Comment by Old-Trekee** [comment]
Any chance of adding for the TFT43?

**Comment by DrumClock** [comment]
Can you please add also for FTF 50 V3.0?

**Comment by labotecno** [comment]
great update !

**Comment by DrumClock** [comment]
Thanks, today a few new icons have been added for TFT 50.
Can you please add them?

**Comment by radek8** [comment]
@bigtreetech, can you put this icon theme on the main download page?
I think they are the best and used :-)

**Comment by Acenotass** [comment]
Done!

**Comment by Old-Trekee** [comment]
Thanks much Acenotass.

**Comment by Mistigris18** [comment]
Super thèmes, merci 👍

**Comment by DrumClock** [comment]
Hi, @Acenotass 
please is it possible to get source images of icons for TFT 50 ?
Thanks

**Comment by Acenotass** [comment]
Hi! @DrumClock Source images for TFT50 is the images of TFT35

**Comment by DrumClock** [comment]
Thanks @Acenotass 
I meant source images. If I wanted to create my own icon. 
For example in Adobe Illustrator or Corel Draw format ... etc

**Comment by Acenotass** [comment]
I am using GIMP, as indicated in the readme.md file

**Comment by charakaSamawry** [comment]
These icons werent replaced when i used your iconpack acenotass. Not sure if your just yet to update them or missed them. (Or they are no longer used or are renamed?)

**Comment by Acenotass** [comment]
@charakaSamawry https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/935

**Comment by Acenotass** [comment]
Obsolete

**Comment by charakaSamawry** [comment]
@Acenotass Many Thanks!
