### ISSUE TITLE
[FR] (Add menu to power off printer after print)

### ISSUE THREAD

**Issue by xhejtman** [bigtreetech/BIGTREETECH-TouchScreenFirmware#892]
Add menu option so you can select **during print** that printer should power off after print (M81 cmd).

**Comment by radek8** [comment]
You can paste the M81 command into an ini file

# end_gcode:G90\nG1 E-4\nG92 E0\nM18\nM81\

**Comment by xhejtman** [comment]
But can I turn on/off the end_gcode while printing?

**Comment by radek8** [comment]
Why?
So set it to fill in after each print.
You turn the printer back on before printing again
If you do not want to turn it off before printing, you will cancel it

**Comment by xhejtman** [comment]
Well, the FR is about to select during print, whether the printer should turn off or not.

Also, you should wait until hotend is cool, not turn off with hot hotend and I'm not sure, you can actually cancel print while marling is waiting for sth.

**Comment by radek8** [comment]
You can set at what hotend temperature the hotend cooling fan should turn off. Default 50 ° C. I assume the printer could turn off along with the fan.

**Comment by radek8** [comment]
#define AUTO_SHUT_DOWN_MAXTEMP 50

**Comment by bigtreetech** [comment]
As mentioned above, this function is already available in firmware. you can click "More > Feature > Auto power" to ON/OFF power off function in Printing

**Comment by bigtreetech** [comment]
Hello， I will close here because this feature already exists, please confirm. If you have any questions, please reopen here and contact me

**Comment by xhejtman** [comment]
Yes, it is already present, thanks.
