### ISSUE TITLE
Folder upload

### ISSUE THREAD

**Issue by AntoszHUN** [bigtreetech/BIGTREETECH-TouchScreenFirmware#896]
How do I upload a folder?

**Comment by oldman4U** [comment]
Hi.

I just make a new ticket with all the feature requests, so it is easier to search and also for the developers to see what has been requested. Unfortunately I do not understand your request, so could you please explain.

Thank you

**Comment by AntoszHUN** [comment]
I wanted to create a folder for new menu icons. Only ZIP folder was created / uploaded. You can see it in the main directory.

Hello, AntoszHUN

**Comment by oldman4U** [comment]
You mean while updating the firmware for example?

This is a folder and not a zip.

**Comment by AntoszHUN** [comment]
![Screenshot_20201013-134948~2](https://user-images.githubusercontent.com/45710979/95856945-22163d80-0d5b-11eb-9994-b0df6359986c.png)

I'm talking about this. I wanted to upload it as a folder. Only ZiP allowed.

**Comment by oldman4U** [comment]
So you uploaded this theme, but it did not accept a folder, so you uploaded a zip, right?

I guess you did this using a PR?

**Comment by AntoszHUN** [comment]
Yes. Exactly. Shouldn't there have been an enhancement then?

**Comment by oldman4U** [comment]
Hi. Could you please check if this is what you want? https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/1187

We should also update the ReadMe to cover this theme. Have you made it?

**Comment by oldman4U** [comment]
I do not know which tools you are using, but  I use GitDesktop on Mac and there I had to add a comment before I could add the folder to my branch. Maybe this helps.

Could you please be so kind and close this ticket.

Jonapot
