### ISSUE TITLE
[FR] reset BL-touch

### ISSUE THREAD

**Issue by traffic-light** [bigtreetech/BIGTREETECH-TouchScreenFirmware#902]
At this moment, when I need to reset the BL-touch, I've got to go back to the marlin screen.

It would be great if this is possible in the new bl-touch menu under the bed levelling menu.

(It's a feature what you normally do not need a lot. But would be great if it's possible within the touchmode)

**Comment by thisiskeithb** [comment]
See https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/pull/903

**Comment by traffic-light** [comment]
That is really fast. Nice!
