### ISSUE TITLE
[BUG] (tft70 and skr mini e3 v2.0 no marlin)

### ISSUE THREAD

**Issue by Robenc** [bigtreetech/BIGTREETECH-TouchScreenFirmware#906]
LCD 12864 Simulator but no marlin

TFT 70 v3.0 and the skr mini e3 v2.0

BIGTREE_TFT70_V3.0.26.x.bin and skr mini is the firmware.bin listed on here no extras added to the board at this time

need help getting this fixed

**Comment by oldman4U** [comment]
Hi.

LCD and Marlin mode is the same, so I guess you mean you have no touch screen mode?

How many and which cables have you connected between the display and the mainboard and which baud rate have you defined? How many and which serial ports do you have defined in the firmware of the mainboard? What exactly do you mean with no Marlin - maybe a picture can help?

**Comment by Tygrys-1** [comment]
Just press the knob. The Marlin interface should show up.

**Comment by Robenc** [comment]
it does not work

**Comment by oldman4U** [comment]
Could you make a photo which shows the problem

**Comment by oldman4U** [comment]
And maybe you can answer the question above. Thank you

**Comment by Robenc** [comment]
found the problem hooked the data cable from exp1 to exp3 and now it is working

**Comment by oldman4U** [comment]
Cables - an evergreen. 

Glad we could help
