### ISSUE TITLE
Using an encoder in touch screen mode?

### ISSUE THREAD

**Issue by AntoszHUN** [bigtreetech/BIGTREETECH-TouchScreenFirmware#915]
A question arose as to whether this encoder could be used in touch screen mode? Can it be solved by programming? For example, when entering values or just navigating the menu. Can anyone be interested in this thing?

Hello, AntoszHUN

**Comment by traffic-light** [comment]
It's already mentioned a lot. But when using the encoder in touch mode, it will also do things in marlin. 
It's hardwired through the flat cables. So, when you want to disable the encoder in marlin there should change something in marlin or in the hardware for the screen.

I'm thinking to make sort of plug witch you can break the connections to the band cable. Some sort of switch that can be controlled by the tft screen.

**Comment by AntoszHUN** [comment]
Do not quite understand. But so far it has come down that it cannot be solved.

**Comment by traffic-light** [comment]
I'm sorry. Maybe this will help:

look at
#680
#757

**Comment by AnHardt** [comment]
Could sending the Marlin-Menu into a lock-screen, just preventing from leaving the lock-screen by the encoder, lockable and unlockable by g-codes when entering/leaving Marlin-Mode, be a solution?
https://github.com/MarlinFirmware/Marlin/issues/18661

**Comment by traffic-light** [comment]
That could be helpful yes

**Comment by radek8** [comment]
This is a beautiful solution, but modified by Marlin

**Comment by radek8** [comment]
###  I have a temporary solution to this problem.
I set up in Marlin
#define LCD_TIMEOUT_TO_STATUS -1
This deactivates the return to the status screen in Marlin.
After starting the printer, press the encoder knob  once.
Marlin switches to the menu in the background. Returning to the status screen in Marlin is deactivated, so the menu remains open.
I can rotate the touch screen with the encoder and the print speed does not change. Wow
