### ISSUE TITLE
G29 and other Gcodes in top of Marlin mode

### ISSUE THREAD

**Issue by RicardoEmePe** [bigtreetech/BIGTREETECH-TouchScreenFirmware#921]
### Description

When I switch to Marlin mode, at the windows  top some Gcodes are displayed. I had before firm. TFT35_V3.0.25.1 and  it works well !!!
![IMG_7382](https://user-images.githubusercontent.com/37264449/89563955-904ef900-d81c-11ea-9f6d-b4d17335d787.jpg)

### Steps to reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior**
No Gcodes in top. 

**Actual behavior**
Read description bug

### Hardware Variant
BIGTREETECH_TFT35_V3.0
### TFT Firmware Version & Main Board Firmware details
TFT35_V3.0.26.x jul 13 2020  // SKR V1.3

### Additional Information
* Include a ZIP file containing your `Configuration.h` or use [Pastebin](https://pastebin.com/) and paste a link in this issue.
* Provide pictures or links to videos that clearly demonstrate the issue.

**Comment by guruathwal** [comment]
you need to reflash the config.ini file

**Comment by RicardoEmePe** [comment]
Ok, now it's Ok. Yesterday eveningh I did it, but no changes. Now, Ok and "Invalid Keyword" message while reading config.ini don't show " Lcd12864_title: LCD12864 simulator" , and "lcd2004_title: LCD2004 simulator".
Anyway, while config.ini reading, the message in "Invalid Keyword" shows: 
ack_popup_type:1
marlin_type:1
bed_en:1
chamber_en:0
pl_recovery_en:1
knob_led_idle:1
lcd_brightness:11

I don't know if this is important. 

Thanks, guruathwal, for your quick reply !!!

**Comment by guruathwal** [comment]
that's because you are using a new config file with old firmware

**Comment by traffic-light** [comment]
@RicardoEmePe you can close this one when it's working again

**Comment by RicardoEmePe** [comment]
I come back home next Sunday, I’ll try and close if ok. Many thanks 

Enviado desde mi iPhone

**Comment by RicardoEmePe** [comment]
New firmware and new config file. Same problem. Enclosed you have a film with the  issues

[https://drive.google.com/file/d/1ProUmeQCrPmC9IbuyJh4kZ1BtTsY6WxV/view?usp=sharing]

**Comment by traffic-light** [comment]
We don't have permission to see the file
