### ISSUE TITLE
Dimmer

### ISSUE THREAD

**Issue by bigtreeteche3** [bigtreetech/BIGTREETECH-TouchScreenFirmware#922]
Please add the possibility to dim the screen down to 1% and or even 0%. People like me that have the printer in the bedroom would love the possibility to turn it off during the print.

Of course to implement also a filament load and unload button like said in a previous post would be also great. 

best regards

**Comment by traffic-light** [comment]
For now a easy fix for you:
Go to file *lcd_init.h*
Add a new line between 8 and 9 and add there this line of code:
````
  #define LCD_0_PERCENT    0
````

And change line 43 to this (change 11 to 12):
````
  #define ITEM_BRIGHTNESS_NUM 12
````

Go to file *lcd_init.c*
Add a new line between 26 and .27 and add there this line of code:
````
LCD_0_PERCENT,
````
