### ISSUE TITLE
TFT24 freezes randomly

### ISSUE THREAD

**Issue by matbhe** [bigtreetech/BIGTREETECH-TouchScreenFirmware#927]
Hello

I'm using the TFT24 with a SKR 1.4 Turbo (marlin 2.0.x-bugfix) for a CNC machine. Because this machine has 0 extruders it does not know the M221 gcode. To fix the continuous error messages on the TFT24 i commented out the storeCmd("M221") in StatusScreen.c. After the upgrade the display works but randomly freezes (touch does no longer react to input). As soon as i comment out the other storeCmd - calls (M114/M220) in statuspage.c it seems to work without crashing. I could not find the bug until now. Does anyone have the same problems?

Regards Matthias

**Comment by bigtreetech** [comment]
Hello, Can you confirm if the problem still exists after #950
Thank you very much!

**Comment by matbhe** [comment]
Hello

The bug seems to be fixed with #950 . 
Well done :-)

Regards Matthias

**Comment by matbhe** [comment]
Fixed
