### ISSUE TITLE
TFT24 : font need update

### ISSUE THREAD

**Issue by spilz87** [bigtreetech/BIGTREETECH-TouchScreenFirmware#93]
after update/merge 7490542f564debb42825cefb5f9e3d581d1c71fc text are no more display, the font files need an update but they are not provided with last updates files.

**Comment by arminth** [comment]
I can confirm that. I tried to copy the fonts from TFT35 to the TFT24 directory but thsi just caused garbled stuff insteasd of empty text.

**Comment by arminth** [comment]
Solved with today's commit.
