### ISSUE TITLE
[FR] IDEA: Iconpack 'The Round Miracle' - Update for SW v26.x @ 2020/11/04

### ISSUE THREAD

**Issue by Acenotass** [bigtreetech/BIGTREETECH-TouchScreenFirmware#935]
Big SW 26.x update @ 2020/08/07. Added 9 new icons, redrawn 4 old ones.
UPD: @ 2020/08/13 Redrawn: RGB_Settings.bmp. Removed: Silent_Off.bmp, Silent_On.bmp. Added: Sound.bmp. Swap: Tuning.bmp <--> Parameter.bmp
UPD: @ 2020/08/26 Minor redrawn: BigTreeTech.bmp, Marlin.bmp, EEProm_Reset.bmp, EEProm_Restore.bmp, Z_Fade.bmp
UPD: @ 2020/09/04 Added: Tune_Extruder.bmp, Apply.bmp. Removed: XY_Unlock.bmp, Extrude_100.bmp, S_Save.bmp, S_Load.bmp
UPD: @ 2020/11/04 Added: Case_Light.bmp. Minor redrawn:  Chamber.bmp, Nozzle_Down.bmp, Nozzle_Up.bmp, Folder.bmp, Dec.bmp, Inc.bmp, Machine_Settings.bmp, Status_Bed.bmp, Status_Fan.bmp, Status_Flow.bmp, Status_Nozzle.bmp, Status_Speed.bmp, Parameter.bmp

![All Icons26 x@2020 11 04](https://user-images.githubusercontent.com/44540957/98237647-662de400-1f8f-11eb-9801-2304abae0c56.png)

[TFT24 Iconpack 'The Round Miracle' by Acenotass for v26.x@2020.11.04.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5494143/TFT24.Iconpack.The.Round.Miracle.by.Acenotass.for.v26.x%402020.11.04.zip)
[TFT28 Iconpack 'The Round Miracle' by Acenotass for v26.x@2020.11.04.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5494144/TFT28.Iconpack.The.Round.Miracle.by.Acenotass.for.v26.x%402020.11.04.zip)
[TFT35 Iconpack 'The Round Miracle' by Acenotass for v26.x@2020.11.04.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5541896/TFT35.Iconpack.The.Round.Miracle.by.Acenotass.for.v26.x%402020.11.04.zip)
[TFT43 Iconpack 'The Round Miracle' by Acenotass for v26.x@2020.11.04.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5494146/TFT43.Iconpack.The.Round.Miracle.by.Acenotass.for.v26.x%402020.11.04.zip)
[TFT50 Iconpack 'The Round Miracle' by Acenotass for v26.x@2020.11.04.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5494147/TFT50.Iconpack.The.Round.Miracle.by.Acenotass.for.v26.x%402020.11.04.zip)
[TFT70 Iconpack 'The Round Miracle' by Acenotass for v26.x@2020.11.04.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5494148/TFT70.Iconpack.The.Round.Miracle.by.Acenotass.for.v26.x%402020.11.04.zip)

**Comment by Mistigris18** [comment]
tu est très réactif 👍

**Comment by DrumClock** [comment]
HI,
again some new icons have been added.
Please update, Thanks

![ico 13820](https://user-images.githubusercontent.com/64655979/90181150-48961780-ddb0-11ea-92a1-924e1c31458d.JPG)

**Comment by Mistigris18** [comment]
Regarde bien, ils y sont 😉

**Comment by oldman4U** [comment]
@Acenotass 

Are you going to add the missing extruder tune icon?

**Comment by el-quique** [comment]
Nice job. The only change if you can make is: Extrude_100.bmp to Tune_Extruder.bmp
Thx

**Comment by Acenotass** [comment]
@oldman4U  Done!

**Comment by oldman4U** [comment]
Hi.

Could you please check #1187 to see if this would be something you would also like do with your theme.

Thank you

**Comment by Acenotass** [comment]
hi! 
@oldman4U 
If you want you can include it in the firmware, maybe it makes sense to make a mechanism for easier changing of themes. Thanks.

**Comment by oldman4U** [comment]
I will mention you as the one who provided the theme. Ok!?

Maybe I can not do it, because the whole package becomes too big...

Will see.

Acenotass <notifications@github.com> schrieb am Mo. 2. Nov. 2020 um 14:29:

**Comment by oldman4U** [comment]
Is this OK?

![Round Miracle Mainscreen](https://user-images.githubusercontent.com/54359396/97899478-a3993400-1d39-11eb-8aee-b7a8dd0296af.png)

**Comment by Acenotass** [comment]
@oldman4U ok

**Comment by cimoalpacino** [comment]
Great work! Thank you for sharing your design 👍

**Comment by Mistigris18** [comment]
Très bon travail , merci je les utilises sur toutes mes imprimantes 👍👍

**Comment by oldman4U** [comment]
Hi.

Somehow the Case light and chamber icons of the TFT35 folder seem to be broken. Could you please check.

Thank you

**Comment by oldman4U** [comment]
And some more, like Apply Dec, Folder, Inc, Level Edge Distance, Machine Settings, Nozzle Up and Down,  Parameter, PID, Status Bed, Flow, Nozzle and Speed, Tune Extruder and Tuning.

**Comment by oldman4U** [comment]
All others seem to be OK.

**Comment by Acenotass** [comment]
HI @oldman4U 
I downloaded the archive from the post for TFT35, found no problems. What is your problem?

**Comment by oldman4U** [comment]
Look at the attached screenshot.

Previous packs are fine. Only the newly added items seem to have the issue.
<img width="1680" alt="Screenshot 2020-11-15 at 07 51 27" src="https://user-images.githubusercontent.com/54359396/99178844-a4f23580-2717-11eb-9d82-73501bc84f83.png">

**Comment by Acenotass** [comment]
re-download archive TFT35

**Comment by oldman4U** [comment]
Perfect!!

Thank you

<img width="1680" alt="Screenshot 2020-11-15 at 08 17 57" src="https://user-images.githubusercontent.com/54359396/99179163-26979280-271b-11eb-8c92-b8bea8e0e763.png">

**Comment by oldman4U** [comment]
I had to start a new PR, #1251 is now used. Please check if everything is fine.

Thank you

**Comment by Acenotass** [comment]
@oldman4U 
what do you think of this icon?
![BabyStep](https://user-images.githubusercontent.com/44540957/99552535-4f53ac80-29e7-11eb-9479-46827b524b8d.png)

**Comment by oldman4U** [comment]
I would keep it more simple. The icons are already hard to understand
especially on small tfts.

Acenotass <notifications@github.com> schrieb am Mi. 18. Nov. 2020 um 16:45:

**Comment by oldman4U** [comment]
Hi. If you want you can close this ticket now. 

Thank you
