### ISSUE TITLE
[FR] Temperature Fluctuation Graphs

### ISSUE THREAD

**Issue by jedisintraining3** [bigtreetech/BIGTREETECH-TouchScreenFirmware#949]
Can you add temperature Fluctuation Graphs to visualize current, past, and required temperatures. I'm thinking of the graphs that are found in octoprint. I think I would add a lot of use and feature to the display.

**Comment by oldman4U** [comment]
So far all features are available independent on the size of the Screen. Not sure how this works on smaller screens. Why not using Octo or Pronter for this?

**Comment by jedisintraining3** [comment]
So, this is available for the bigger ones? I dont use octo because It would get rid of power det and filament runout functionality. Pronter is only USB.

**Comment by oldman4U** [comment]
No. All sizes of TFTs are using the same interface.

You could get it with the WIFI module also. Which screen and mainboard are
u using?

jedisintraining3 <notifications@github.com> schrieb am Di. 11. Aug. 2020 um
05:23:

**Comment by oldman4U** [comment]
Hi.

Please close this ticket

**Comment by jedisintraining3** [comment]
May the force be with you too, 

Always.
