### ISSUE TITLE
[Q] I am having issues updating to version 26.

### ISSUE THREAD

**Issue by MrJabu** [bigtreetech/BIGTREETECH-TouchScreenFirmware#954]
i have a BTT TFT35 and cannot get the new version installed.

i have grabbed the TFT35 folder and BIGTREE_TFT35_V3.0.26.x.bin file on an sdcard. when i boot it up it looks like it is updating but then jumps to a calibration screen with unreadable text. 

what am i doing wrong?

**Comment by radek8** [comment]
TFT35 ? what version?

**Comment by radek8** [comment]
Unzip to SD card and restart the display.
if it requires calibration, perform calibration
[TFT35V30.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5052950/TFT35V30.zip)

**Comment by MrJabu** [comment]
> Unzip to SD card and restart the display.
> if it requires calibration, perform calibration
> Edit the INI file according to your own configuration
> 
> [TFT35V30.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5052950/TFT35V30.zip)

Ok that worked! 

why did your file work and the one on the github did not?

**Comment by MrJabu** [comment]
> Unzip to SD card and restart the display.
> if it requires calibration, perform calibration
> Edit the INI file according to your own configuration
> 
> [TFT35V30.zip](https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/files/5052950/TFT35V30.zip)

Actually, now my Marlin mode doesnt work.

**Comment by carl1961** [comment]
that zip looks like stock, maybe try the unified

**Comment by carl1961** [comment]
@radek8 where that zip come from? bin file different size.

**Comment by radek8** [comment]
> 
> Dobře, že to fungovalo!
> 
> proč váš soubor fungoval a ten na githubu ne?

I have compiled a new version for your display.
There are obsolete bin files on github, but current INI files.
Together they may not work well ...

**Comment by radek8** [comment]
> Like @radek8 asked what version TFT 3.5 ? theres many versions

Yes, there are many HW versions of the TFT35

**Comment by radek8** [comment]
> @radek8 where that zip come from? BIGTREE_TFT35_V3.0.26.x.bin file different size (larger).

It is the latest compilation. Bin file is 29 days old :-(

**Comment by carl1961** [comment]
Thanks @radek8  Good to know that, I did not notice that.

**Comment by MrJabu** [comment]
> > Ok that worked!
> > why did your file work and the one on the github did not?
> 
> I have compiled a new version for your display.
> There are obsolete bin files on github, but current INI files.
> Together they may not work well ...

Can you post the fumes you used to compile the .bin

**Comment by carl1961** [comment]
MrJabu You use vscode  https://code.visualstudio.com/, it's all documented on the BTT github   https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware

**Comment by MrJabu** [comment]
> @MrJabu You use vscode https://code.visualstudio.com/, it's all documented on the BTT github https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware Click on View full instructions towards the bottom Under Firmware

i actually did try to compile it before i posted the question here. i was able to create the .bin and did have the correct screen selected but it still didn't work

**Comment by oldman4U** [comment]
Hello @MrJabu 

Seems this issue is solved.

Please close this ticket

Thank you

**Comment by oldman4U** [comment]
@MrJabu 

Close this ticket or reply

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you
