### ISSUE TITLE
[FR] Probing point values

### ISSUE THREAD

**Issue by Guilouz** [bigtreetech/BIGTREETECH-TouchScreenFirmware#957]
Do you think is it possible to add values from BlTouch probing points on the screen like Creality printers ?

![igtlq7fggfd31](https://user-images.githubusercontent.com/12702322/89840138-c61f1500-db6f-11ea-8afa-c7b29f0957c4.jpg)

![image png 7684f5cfe02a7fe22cdd4f0f8492b349](https://user-images.githubusercontent.com/12702322/89840309-2b730600-db70-11ea-81cc-0f52a9c56b9e.png)

This is very useful to see if the leveling is correct.

**Comment by oldman4U** [comment]
Hi.

Isn't this more or less exactly like this pinned ticket: https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/288

**Comment by radek8** [comment]
Look at this # 963
You cannot edit individual points, but you can check the point values.

**Comment by Guilouz** [comment]
> #963

Yes that what I want, just see values. Is it not possible to have values in real time ? Like creality printers when it probing a point it show value directly.
Maybe create a new page when we start a leveling who show values, no ?

**Comment by Hyrules** [comment]
I would like this as well. Coming from at CR10SPRO touchscreen it would be nice to see the values of the bed level. I can cope meanwhile with the Bedlevel visualizer in octoprint but it would make a nice addition to the TFT screen.

**Comment by oldman4U** [comment]
@Guilouz 
@Hyrules 

Would it be possible for you to design a interface which works from 2.4 to 7“ display and describe the features? Only the functionality not the look.

**Comment by Hyrules** [comment]
It really depends on the number of point you have to probe. Lets say someone has 4 point X and Y. That 16 point to show on screen. That should not be a problem for at TFT3.5 and bigger but let's say someone has decided to compile marlin with 8 point X and Y that 64 points on screen. I don't believe there is enough room on the 3.5 and smaller to display those 64 points.

**Comment by oldman4U** [comment]
I agree.

So this function should not be available for 2.4“ screens?

Or what would be the solution for you?

Hyrules <notifications@github.com> schrieb am Di. 25. Aug. 2020 um 13:04:

**Comment by Hyrules** [comment]
This should be really dependant of 2 things the TFT size and the number of points. If someone has a TFT3.5 but decide to use 64 points it might not show properly on screen too. It might be available but only list the points on screen as a XY : Value pair one under the other.

**Comment by oldman4U** [comment]
Take some pieces of paper and a pen and make the design. This could help a
lot.

Hyrules <notifications@github.com> schrieb am Di. 25. Aug. 2020 um 13:21:

**Comment by Hyrules** [comment]
I'll try to get a design for you asap.

**Comment by oldman4U** [comment]
No hurry.

So 2 designs. One where the grid fits and one where it does not.

I would also need the design how the grid is then edited.

Hyrules <notifications@github.com> schrieb am Di. 25. Aug. 2020 um 13:35:

**Comment by oldman4U** [comment]
Thank you 👍🏻

Hyrules <notifications@github.com> schrieb am Di. 25. Aug. 2020 um 13:35:

**Comment by radek8** [comment]
@oldman4U Traffic-light is already working on it :-)
See #963

**Comment by oldman4U** [comment]
Hi radek8.

I hop traffic light is as good in UI design like in coding😁

Many others including myself have been working on it but for good reasons nobody was able to release it so far. My experience is that it is almost impossible to get a feature rich solution which works fine on all sizes of displays. So for me every additional input is welcome and as soon as traffic light adds letters to his grid, the problem will start. With the current monospace font and the limited amount of pixels available there is simply not enough space to make it happen. Do you know that the TFT43 and 50 have less pixels than the TFT35. So it is a question of the size of the screen, the number of pixels available and the aspect ratio. 

This is a UI developers nightmare

**Comment by Hyrules** [comment]
Basically I'm not good either at making ui. I'm hopefully a good coder but not a gui maker. I maintained an app for the best part of the last 6 -7 years and I always had troubles designing a gui.

**Comment by oldman4U** [comment]
Also good coders are always welcome😊

**Comment by Hyrules** [comment]
I might try myself at forking this repo and make some bugfix and add features. I would just need an extra TFT because the only one I have is on my printer and I don't want to mess around with it too much.

**Comment by oldman4U** [comment]
Welcome to the "I have two printers - one is printing and one is just parts" world;-)

**Comment by oldman4U** [comment]
Hi.

What is the status of this ticket?

**Comment by oldman4U** [comment]
Hi.

I am just working on a new ticket which collects all the features which have been requested in the past. Yours have been requested before and after, so could you please close it.

Thank you
