### ISSUE TITLE
[FR] M600 support in Unified menus

### ISSUE THREAD

**Issue by jariivanoff** [bigtreetech/BIGTREETECH-TouchScreenFirmware#965]
**Is your feature request related to a problem? Please describe.**
I like to print with different colors, and change filament at a certain layerheight. I use to make that in slicer, and it sends an M600 command. Now that I have installed an TFT35 v2.0 I have no way to continue the print since there is no support for that in the menus and the TFT2.0 have no Marlin mode which I could switch over to and make the print continue after filament change.

**Describe the solution you'd like**
A button that I can press to make the print continue after a M600

**Describe alternatives you've considered**
Getting an other display with Marlin support or go back to my LCD12864

**Additional context**

**Comment by bigtreetech** [comment]
Hello, It has supported M601 for gcode pause after #764 
And after #971 The default Settings included M600/M601
They are consistent with the action of manual pause(click pause button in touch screen)
Can this solve your needs?

**Comment by ETE-Design** [comment]
@bigtreetech Is it possible to use this feature if my sensor is connected to the mainboard and not the screen? End where in firmware do I define the pin so it know It's connected to the mainboard?

**Comment by jariivanoff** [comment]
Well.. the thing is that if you use a slicers feature of M600 the board won't know that the printer has paused.. if it  comes with the gcode so to say... and besides that.. I haven't found the pausfunction yet.. but that is perhaps since I always print from Octoprint and never use the display for pausing...

**Comment by bigtreetech** [comment]
> Well.. the thing is that if you use a slicers feature of M600 the board won't know that the printer has paused.. if it comes with the gcode so to say... and besides that.. I haven't found the pausfunction yet.. but that is perhaps since I always print from Octoprint and never use the display for pausing...

@jariivanoff Hello, Please come #966  to discuss it

**Comment by bigtreetech** [comment]
> @bigtreetech Is it possible to use this feature if my sensor is connected to the mainboard and not the screen? End where in firmware do I define the pin so it know It's connected to the mainboard?

Hello, it also need support for HOST_ACTION_COMMANDS and HOST_PROMPT_SUPPORT in Marlin and Touch Screen, TouchScreen has not  implement it now.
 Please come #966 to discuss it
