### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by Porkisek** [bigtreetech/BIGTREETECH-TouchScreenFirmware#97]
Hi, at TFT35 is only 9 new icons instead 15.

**Comment by huczas** [comment]
I can only confirm that some of new icons are not showing properly in menu. - latest compile and icon pack

**Comment by guruathwal** [comment]
Some new icons have been added since this issue has been opened. You can check if it solves the problem. 
Don't forget to close the issue if it is solved.

**Comment by huczas** [comment]
ok, now all works fine 🙂 thanks

**Comment by guruathwal** [comment]
Good to know.. please close the issue. 👍🏼

**Comment by Porkisek** [comment]
Thank you.
