### ISSUE TITLE
[Q] Neopixel - LED strip

### ISSUE THREAD

**Issue by DrumClock** [bigtreetech/BIGTREETECH-TouchScreenFirmware#978]
I connected the LED strip type WS2812B to the Neopixel connector in the TFT 50 panel.
**How can I control this LED strip?**

**Comment by abacabie** [comment]
On the TFT35 you can control the LED from touch screen mode, its under "machine" settings, should be the same for the TFT 50.

**Comment by DrumClock** [comment]
If the LED strip is connected to the Neopixel connector on the TFT board, then only one LED is expanded based on the "Rotary knob LED" setting. The color settings in the "Machine Settings" menu are not functional for this connector.

**Comment by abacabie** [comment]
I see, i have neopixels connected to the skr mini v2 not the TFT screen, someone more knowledgeable than myself should be able to answer this.

**Comment by DrumClock** [comment]
**Yes,** if I connect the Neopixel strip to the RUMBA board, everything works as it should according to the settings in Marlin FW.
It would be good to add brightness settings to the FTF menu as well. 
After selecting a color, the brightness is set to maximum (P255).
