### ISSUE TITLE
TFT35-E3 V2 Speed will be overwrite while turning an control wheel for Temperatur or Fan

### ISSUE THREAD

**Issue by Bastlwastl84** [bigtreetech/BIGTREETECH-TouchScreenFirmware#979]
TFT-Firmware is only changed Temperature values an Language to german and LED to green.

if i'm turning the wheel to change the Temperature, Fanspeed or Flow, than it's overwriting the speed from the Printer at TFT, i'f im doing the same in Marlin Mode it's working correctly.

**Comment by traffic-light** [comment]
To be honest with you: this question is starting to irritate me 😞 
It's asked in this month at least 10 times...
There is no easy fix for this.


look at
#680
#757 

@bigtreetech please close this issue. It's already mentioned.

**Comment by radek8** [comment]
look at
#886
