### ISSUE TITLE
Compiling for TFT35 V3.0 Fails

### ISSUE THREAD

**Issue by kstanley74** [bigtreetech/BIGTREETECH-TouchScreenFirmware#98]
Tried several times to compile and received the following error in the build panel.

Compiling .pio\build\BIGTREE_TFT35_V3_0\src\src\User\delay.o
TFT\src\User\Menu\ScreenSettings.c: In function 'menuScreenSettings':
TFT\src\User\Menu\ScreenSettings.c:140:7: error: duplicate case value
       case LCD12864_BG_INDEX:
       ^~~~
TFT\src\User\Menu\ScreenSettings.c:131:7: note: previously used here

       case BUZZER_KEY_INDEX:
       ^~~~
*** [.pio\build\BIGTREE_TFT35_V3_0\src\src\User\Menu\ScreenSettings.o] Error 1
Compiling .pio\build\BIGTREE_TFT35_V3_0\src\src\User\main.o

**Comment by UnknownHero99** [comment]
errors are fixed in latest merges :P

**Comment by kstanley74** [comment]
Thank you, Jakob!



Kevin


-------- Original message --------

**Comment by hapklaar** [comment]
Please close if it is fixed for you!

**Comment by kstanley74** [comment]
Closing. This issue has been resolved.
