### ISSUE TITLE
[Q] Using onscreen Layer info

### ISSUE THREAD

**Issue by blueeagle69** [bigtreetech/BIGTREETECH-TouchScreenFirmware#983]
During a print using TFT mode, the Layer information always remains at 0.00.
Do I need layer information in my Gcode?

I'm using Prusaslicer.

Thanks.

**Comment by traffic-light** [comment]
What's your firmware (see settings -> info

**Comment by blueeagle69** [comment]
My firmware is dated August 16 2020 (3.026)
TFT35 E3.

Thanks.

**Comment by traffic-light** [comment]
Oh wait. You should add  something in slicer. I will post it tomorrow.

**Comment by blueeagle69** [comment]
> Oh wait. You should add something in slicer. I will post it tomorrow.

Thank you :)
I added [layer_z] to my Before layer change in Prusaslicer, but haven't printed since that change (if that's it)  😀

Thanks again.

**Comment by traffic-light** [comment]
It should be this:
![image](https://user-images.githubusercontent.com/37051137/90378893-41099380-e07a-11ea-8b85-8b009e45cd24.png)

(i've placed two of them. Some applications I did run before needed one of them.)

**Comment by blueeagle69** [comment]
Cheers, I'll put it in later  :)

**Comment by blueeagle69** [comment]
Hi.

Just an update to this.
My On-screen layer info is no-longer working.
During the print it remains at 0.00

**Comment by oldman4U** [comment]
Hi. A function does not change by itself. What changed and what is the status of the reported issue?

Please let us know

**Comment by blueeagle69** [comment]
I wish I knew.
I'm using Prusaslicer with the same Before Layer Change as before when it worked.
I updated the firmware (I think it was a build before the recent one) and the Layer Info stopped working.
But as for my Slicer and gcode, nothing has changed. I am back on the Biqu B1 build now because I'm suffering from the screen switching to TFT mode when starting a print from Marlin. But that's another issue,

**Comment by oldman4U** [comment]
It would be important to know the firmware versions and make a new ticket with that information. Do you know how to compile intermediate firmware versions?

**Comment by blueeagle69** [comment]
Hi.
I know how to compile from source, if that's what you mean.
Apologies if you meant something else 😃

**Comment by oldman4U** [comment]
You wrote that one firmware worked well. So it would be important to find out which one it was and which version does not work. And it would be good to add this information to the new ticket.

**Comment by blueeagle69** [comment]
Unfortunately, I can't recall which build it was.
But on saying that I am back using an old build again because of my screen switching to TFT mode when I confirm a print in Marlin, and the Layer info isn't working on that one either when printing from the onboard SD card (mainboard).
So I think, when I reported it as working I must have been printing from an SD card in the TFT.
Because that's the only time it appears to work.

**Comment by oldman4U** [comment]
Would it make sense to attach a gcode file which has been working before.

**Comment by blueeagle69** [comment]
I not entirely sure.
As previously mentioned, I believe it worked before because I was printing from media connected to the TFT.
It just doesn't work from the mainboard onboard SD.

**Comment by blueeagle69** [comment]
Shall I close this open Question ticket as I have an open bug report concerning the Layer Info not working when printing from the mainboard onboard SD.

**Comment by oldman4U** [comment]
Feel free to close it whenever you want.

Where did you start the bug report, in Marlin repo?

**Comment by blueeagle69** [comment]
Hi.

No here;
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues/1135#issuecomment-701599394

Thanks 😀

**Comment by oldman4U** [comment]
Hi. I believe you can close this ticket now. Thank you
