### ISSUE TITLE
control knob LED not working.

### ISSUE THREAD

**Issue by PigeonFX** [bigtreetech/BIGTREETECH-TouchScreenFirmware#986]
Whenever I try and set the LED colour I get the error:

`Unknown Comand: "M105 R0 U255 B0 P255" `

Using Marlin 2.0.6 and the latest TFT35 Firmware from the BTT Github.

**Comment by Guilouz** [comment]
M105 is used to report temperature, see : https://marlinfw.org/docs/gcode/M105.html

**Comment by Tygrys-1** [comment]
Use M150 to change LED colors. But, this will set the color of neopixels (or other type) leds connected to the printer itself.
If you get this error using the menu in TFT, that means that Marlin is compiled without M150 support.
To change the color of the knob, please use the features menu. See #870

**Comment by oldman4U** [comment]
Hi

Have you been able to change the color of the knob using the correct menu?

**Comment by PigeonFX** [comment]
> Hi
> 
> Have you been able to change the color of the knob using the correct menu?

Yep
