### ISSUE TITLE
[BUG] Issue with ESP01S ESP8266 Wifi module

### ISSUE THREAD

**Issue by Guilouz** [bigtreetech/BIGTREETECH-TouchScreenFirmware#993]
### Description

When I plug Wifi module on my TFT43, I have this message at startup :

![IMG_1661](https://user-images.githubusercontent.com/12702322/90557212-6e4d6300-e19a-11ea-97f8-e9e5d1bc1cd9.jpg)

If I valid this message, wifi module is connecting correctly but this popup is boring...

I use latest master compiled firmware.

When I plug it on my SKR 1.4 Turbo no problem.

**Comment by oldman4U** [comment]
One month and noone replied. What is the status of the reported issue. 

Please let me know

**Comment by oldman4U** [comment]
Please help the community and close the ticket once you do not need it anymore. Thank you

**Comment by oldman4U** [comment]
You seem to be a respected person. Why not answering or closing this ticket?

**Comment by Guilouz** [comment]
Oh an oversight sorry.

**Comment by oldman4U** [comment]
Thank you 👍🏻
